### ISSUE TITLE
Add platform information into body class

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/ionic-cli#1]
See if we can insert each platform's name into their respective build's index.html body class tag.

For example, an ios build would automatically get this in their body tag:

```
<body class="platform-ios">
```

And Android would automatically build with:

```
<body class="platform-android">
```

Not necessarily required, but may be a nice to have

**Comment by omeid** [comment]
wouldn't platform specific css includes a better solution than to have a class in body?
