### ISSUE TITLE
2.x.x-beta: please support CoffeeScript gulpfiles

### ISSUE THREAD

**Issue by youurayy** [ionic-team/ionic-cli#1004]
In 1.x the `gulpStartupTasks` were correctly found in CoffeeScript versions of the gulpfile, i.e.:

```
Gulpfile.coffee
Gulpfile.litcoffee
gulpfile.coffee
gulpfile.litcoffee
```

but v2.x only tries to load the gulpfile from:

```
Gulpfile.js
gulpfile.js
```

as per `lib/cli.js loadGulpfile()`.

**Comment by dwieeb** [comment]
Hi @youurayy, thanks for the request. Unfortunately, I don't think we'll be supporting coffeescript gulpfiles for Ionic 1 projects at this time.
