### ISSUE TITLE
Error: Cannot find module 'config-chain'

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1007]
_From @threezj on May 17, 2016 16:32_

when use `ionic platform add android`

> Error: Cannot find module 'config-chain' 

ionic info

> Cordova CLI: Not installed
> Ionic Version: 1.3.1
> Ionic CLI Version: 1.7.14
> Ionic App Lib Version: 0.7.0
> OS:
> Node Version: v4.4.4
> 
> npm -v 2.15.1

I use window 10

_Copied from original issue: driftyco/ionic#6549_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is more related to the ionic-cli and not the framework i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by anthony-ngu** [comment]
Also noticed this issue with ionic 2 beta 8
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS:
Node Version: v5.4.1

using windows 10

**Comment by imanube** [comment]
I have this issue as well right now. 
$ ionic platform add android
Error: Cannot find module 'config-chain'

I have no idea what a solution would be. ive tried to clear the cashe and reinstall stuff but it does not work.  when i reinstall i get a lot of errors i dont understand as well


$ npm install -g cordova ionic
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@2.1.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\cally\AppData\Roaming\npm
`-- ionic@2.1.0

npm WARN In ionic@2.1.0 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.1.0 replacing bundled version of ionic-app-lib with ionic-app-lib@2.1.0-beta.1
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\cally\AppData\Roaming\npm\node_modules\.staging\abbrev-769ab754
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\cally\AppData\Roaming\npm\node_modules\.staging\abbrev-769ab754' -> 'C:\Users\cally\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\cally\AppData\Roaming\npm\node_modules\.staging\abbrev-769ab754' -> 'C:\Users\cally\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cally\npm-debug.log
