### ISSUE TITLE
Ionic serve CLI Loop Error

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-cli#1023]
Hi,
if i use the command ionic serve the gulp process is running and at sass i get a loop error:
`Caught exception:
 Error: watch null UNKNOWN
    at exports._errnoException (util.js:893:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues`

My CLI:
Package        Current
ionic    2.0.0-beta.25
![unbenann1t](https://cloud.githubusercontent.com/assets/19570043/15537532/4b5718c8-2277-11e6-96bd-0a08add0d3d8.PNG)
![unbenannt](https://cloud.githubusercontent.com/assets/19570043/15537533/4b5b6bda-2277-11e6-8b9b-e56b5440fc64.PNG)

**Comment by danielehrhardt** [comment]
Run the CMD as Admin fix the Problem

**Comment by jthoms1** [comment]
Could your provide the output from `ionic info`? Thanks

**Comment by Codzart** [comment]
I have same issue....
**Caught exception:**
 **Error: watch null UNKNOWN**
    **at exports._errnoException (util.js:893:11)**
    **at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)**

**Mind letting us know? https://github.com/driftyco/ionic-cli/issues**


Opening Node CMD window as Administrator did not resolve for me.


G:\apps\MyIonic2TSProject>ionic info ?
Your system information:

Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Windows 7 SP1
Node Version: v5.11.0

**Comment by ne6toto** [comment]
I am getting the same issue (or a very similar one) when I try to go through the ionic getting started guide at http://ionicframework.com/docs/v2/getting-started/installation/ and reach the 'ionic serve'

**Caught exception:
 Error: Error watching file for changes: UNKNOWN
    at exports._errnoException (util.js:1007:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1400:11)**


Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 7 SP1
Node Version: v6.2.1

**Comment by juanf9224** [comment]
I think this is caused due to npm failing to install fsevents on OS other than macOS, im getting that exception too. This is npm warn about failing to install fs events:

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

this info might help:
[https://github.com/nodejs/node/issues/7858](url)
