### ISSUE TITLE
Improve output from ionic info

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-cli#1051]
There is so much information being displayed from `ionic info` that it may be confusing to the user what is what. We should somehow make this more clear what each version refers to (Specifically the CLI, framework, app lib):

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jthoms1** [comment]
Do you think we should restructure the output so that it is grouped?  I think all of the information is valuable for troubleshooting.

```
Ionic
  - Version: 2.0.0-beta.8
CLI
  - Version: 2.0.0-beta.30
  - App Lib Version: 2.0.0-beta.16
Dependencies
  - Cordova CLI: 6.1.1
  - Gulp version: CLI version 3.9.0
  - Gulp local: Local version 3.9.1
  - ios-deploy version: Not installed
  - ios-sim version: 5.0.6
Environment
  - OS: Mac OS X El Capitan
  - Node Version: v4.4.2
  - Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by brandyscarney** [comment]
Yes! Maybe we should put the npm modules? @adamdbradley care to weigh in?

**Comment by jthoms1** [comment]
We could add an additional flag passed to `ionic info` like `ionic info --verbose` to provide additional details.

**Comment by supasheva** [comment]
Hi. I can't seem to see my framework version when i run `ionic info` . 
![untitled](https://cloud.githubusercontent.com/assets/10486306/16150383/be719a58-348e-11e6-8612-4173c1719814.jpg)

**Comment by jthoms1** [comment]
@supasheva If you run `ionic info` from inside of your project folder it includes the 'Ionic Framework Version'. So to see it just start a new ionic project go into the newly created folder and type `ionic info` again.
