### ISSUE TITLE
No portrait splashscreens generated with "ionic resources" when orientation set to landscape

### ISSUE THREAD

**Issue by teledemic** [ionic-team/ionic-cli#1058]
When the app is marked with `<preference name="Orientation" value="landscape"/>`, no portrait mode splash screens are generated when you run `ionic resources`. However cordova-plugin-splashscreen doesn't allow landscape splashscreens for iPhone 5 and 6, so you end up with the default cordova splashscreen (in portrait orientation).
May be the same problem as #397 

`Cordova CLI: 6.2.0`
`Ionic Framework Version: 2.0.0-beta.7`
`Ionic CLI Version: 2.0.0-beta.30`
`Ionic App Lib Version: 2.0.0-beta.16`
`Node Version: v6.2.0`

See also
https://github.com/apache/cordova-plugin-splashscreen/blob/master/src/ios/CDVSplashScreen.m#L212

**Comment by CookieCookson** [comment]
+1, it should generate 90 degree rotated images in portrait configurations for the non-landscape-supported devices
