### ISSUE TITLE
Can't downgrade ionic

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/ionic-cli#107]
From @colllin: https://github.com/driftyco/ionic/issues/2205

Tried `ionic lib update -v 1.0.0-beta.11`

It likes the version number, but gives:

```
collin@colllin whatever $ ionic lib update -v 1.0.0-beta.11
Are you sure you want to replace /Users/collin/Projects/Whiteboard/temp/whatever/www/lib/ionic with an updated version of Ionic?
(yes/no): yes
Version: undefined  (released undefined)
Downloading: https://github.com/driftyco/ionic-bower/archive/vundefined.zip
[=============================]  100%  0.0s
Invalid version: undefined
```

**Comment by periyasamy17** [comment]
npm uninstall -g ionic
npm install -g ionic@1.7.6

I am not sure this is work or not just try this step to downgrade.

**Comment by madhavanks26** [comment]
@periyasamy17  when i tried the command mentioned by you, I am getting the permission denied EPERM error.

I tried by running as admin in my windows 7 PC ,Kindly check the following error log and please do provide me a solution.


`$ npm install -g ionic@1.7.15
C:\Users\dell\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8                                                                                                                6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic@1.7.15"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path C:\Users\dell\AppData\Roaming\npm\node_modules\ionic\node_modules\                                                                                                                ionic-app-lib\node_modules\cross-spawn\node_modules\spawn-sync
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\dell\AppData\Ro                                                                                                                aming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\cross-spawn                                                                                                                \node_modules\spawn-sync' -> 'C:\Users\dell\AppData\Roaming\npm\node_modules\ion                                                                                                                ic\node_modules\ionic-app-lib\node_modules\cross-spawn\node_modules\.spawn-sync.                                                                                                                DELETE'
npm ERR!     at moveAway (C:\Program Files (x86)\nodejs\node_modules\npm\lib\ins                                                                                                                tall\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files (x86)\nodejs\node_modules\npm\lib\                                                                                                                install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\dell\AppData\Ro                                                                                                                aming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\cross-spawn                                                                                                                \node_modules\spawn-sync' -> 'C:\Users\dell\AppData\Roaming\npm\node_modules\ion                                                                                                                ic\node_modules\ionic-app-lib\node_modules\cross-spawn\node_modules\.spawn-sync.                                                                                                                DELETE'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\dell\AppDat                                                                                                                a\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\cross-s                                                                                                                pawn\node_modules\spawn-sync' -> 'C:\Users\dell\AppData\Roaming\npm\node_modules                                                                                                                \ionic\node_modules\ionic-app-lib\node_modules\cross-spawn\node_modules\.spawn-s                                                                                                                ync.DELETE'] parent: 'cross-spawn' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\Git\npm-debug.log
npm ERR! code 1
`
