### ISSUE TITLE
Ionic package using old code

### ISSUE THREAD

**Issue by teledemic** [ionic-team/ionic-cli#1077]
I am developing on PC for iOS with v2, and I use `ionic package build ios --profile dev --noresources` to get an iOS build. However, it doesn't always appear to upload the changes I've made. The upload looks fine:

```
Saved api_key, writing to ionic.io.bundle.min.js...
Uploading your project to Ionic...
Submitting your app to Ionic Package...
Your app has been successfully submitted to Ionic Package!
Build ID: 42
We are now packaging your app.
```

But when I download that build, it often shows code from a previous version. I can go into the IPA and look at www/build/js/app.bundle.js and see the old code. It doesn't always happen either. It's making debugging really difficult.

I also see that my project's www/build/js/app.bundle.js is out of date. Am I supposed to run `ionic build ios` first? I can't do that because I'm on a PC, which I understand is the exact situation ionic package is for.

```
Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS:
Node Version: v4.4.5
```

**Comment by dennis3001** [comment]
Same issue here!

**Comment by rahul-bhiwagade** [comment]
me too. Can someone suggest a command to compile the code or clean old one ??

**Comment by teledemic** [comment]
For a workaround, I've been running ionic serve before I do an ionic package. It's a real bummer when you forget to do that and then try to figure why your fix didn't fix anything though.

**Comment by dennis3001** [comment]
I would be fine with running serve but even this does not help in my case.
I had a build error with one of the plugins. 

I even tried uninstalling the plugin and I still see the same error!
I tried to delete the app from the ionic cloud and upload again. 
Doesn't help, it still remembers the history...

**Comment by SEAnderson07** [comment]
I encountered this same issue when packaging for both iOS and android. I was able to resolve the issue by running `ionic server` before packaging as mentioned above.

**Comment by JacerOmri** [comment]
I think the right behaviour here is to actually build the project before uploading.

**Comment by mleu** [comment]
I was also quite astonished that ionic package seems to just grab `www/` without first building from source. As a workaround for our CI we currently do a build with a dummy platform name before using package:

`ionic build www-dir-for-ionic-package && ionic package build ...`

**Comment by efares** [comment]
I am still getting this issue. I have tried removing and add the platform. I tried running sudo `cordova prepare` in my project root. I have incremented my app version but it is still compiling old code. On `Ionic serve -l`, it shows the latest code.
