### ISSUE TITLE
.io-config.json is recreated on certain commands

### ISSUE THREAD

**Issue by Maistho** [ionic-team/ionic-cli#1084]
Moving forward, the recommended way to use Ionics cloud services will be ionic-cloud, and it doesn't use the `.io-config.json` file. So at some point in the future, this file should be removed. I'm already using ionic-cloud, since it solves some problems I had with `ionic-platform-web-client`.

Ionic CLI seems to recreate the `.io-config.json` file whenever I run certain commands (tested with `package`), which _might_ be good for now, but that functionality should probably be removed in the near future.

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by Maistho** [comment]
Tested with both ionic@1.7.15 and ionic@beta, both recreate a missing .io-config.json if it's missing when running `ionic package build android`.

### stable:
```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
OS: Distributor ID:	Arch Description:	Arch Linux 
Node Version: v6.2.1
```

### beta:
```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS: Distributor ID:	Arch Description:	Arch Linux 
Node Version: v6.2.1
```

**Comment by rolandjitsu** [comment]
I have the same behaviour. It also keeps overriding the `ionic.config.json` file and it just replaces tabs with spaces.

**Comment by martyzz1** [comment]
same here

```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

```
