### ISSUE TITLE
`ionic start` get stuck at `Initializing cordova project`

### ISSUE THREAD

**Issue by panlina** [ionic-team/ionic-cli#1088]
I'm creating a project from the blank template:
`ionic start blank blank`
After downloading templates, it gets stuck at:
`Initializing cordova project`
What is it doing here? What can I check?
_Windows 10, node.js 4.4.0_

**Comment by rpamaral** [comment]
Had the same problem here. How did you solve it?

**Comment by shawnvan** [comment]
the problem still exists 
mac 10.11.5 with node 4.4.5

**Comment by jun283** [comment]
Hello, not stuck, just wait long time

**Comment by panlina** [comment]
@rpamaral Not solved yet.

**Comment by Alfonsopl** [comment]
I had the same problem and it was becouse I had cordova 4.
Fixed upgrading to cordova 5 (6 should work too) :
npm install -g cordova@5

**Comment by alexandervlpl** [comment]
Same problem. I need to maintain a legacy codebase, so simply upgrading is not a solution.

**Comment by moja-apps** [comment]
I also need to maintain a legacy codebase using an older version of ionic-cli (1.7.x). I use the --no-cordova option to prevent ionic-cli from hanging when trying to install an unexpected version of cordova:
ionic start myApp blank --no-cordova

Once the ionic project is setup, I manually install the cordova version I need:
cd myApp && npm install cordova@4.1.2
