### ISSUE TITLE
"ionic platform update ios" rewrite files

### ISSUE THREAD

**Issue by skyylex** [ionic-team/ionic-cli#1092]
My case was the following I need to update existing ionic project with additional js plugins.

I found unexpected that `ionic platform update ios` replaces .gitignore, Info.plist, project.pbxproj, also as source files for the iOS platform like AppDelegate.m, MainViewController.m. I expected that required libraries will be added (if needed) as dependencies in the build settings. Instead of that ionic just replaced all files. 

As iOS developer I see that:
- iOS target requires sometimes extending Objective-C source code files with lines that override styles (for NavigationBar for instance).
- .gitignore file is needed to be customised due to the project requirements of the project type or additional developer tools usage. 
- Info.plist, project.pbxproj - project files also could be used in setup additional tools like Crashlytics.

With the current implementation of this command developer forced to write additional script to apply changed files back after `ionic platform update` and it's not convenient way to do. Or maybe there is a proper way to get updates of the Javascript plugins and dependencies for the platform without breaking existing code?

Thanks in advance.

**Comment by abusharaf** [comment]
I did this update platform command, but it ruined my entire ios and android project files, however the good thing is this,  I did remove all the plugins i am using in  the project and then add them again here is a sample from the command line

cordova plugin rm cordova-plugin-device
cordova plugin rm cordova-plugin-statusbar
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-statusbar
cordova plugin rm cordova-plugin-globalization
cordova plugin add cordova-plugin-globalization
cordova plugin rm cordova-plugin-touchid
cordova plugin add cordova-plugin-touchid
cordova plugin rm ionic-plugin-keyboard
cordova plugin add ionic-plugin-keyboard


after that just try to rebuild your project like "ionic build ios " and "ionic run ios " for example everything should work.

**Comment by dwieeb** [comment]
This is Cordova overwriting these files because Cordova considers the native platforms as build artifacts. This is being flipped with [Capacitor](https://capacitor.ionicframework.com/). I'm closing this as it's not an issue with the Ionic CLI.
