### ISSUE TITLE
(bug) [ionic run/emulate ios] option --target is ignored

### ISSUE THREAD

**Issue by galuszkak** [ionic-team/ionic-cli#1095]
Hi,
Firstly thanks for awesome work on ionic framework!
My problem is that in ionic@beta `--target` is ignored always.

```
[app]$ ios-sim showdevicetypes
iPhone-6s, 9.3
Apple-Watch-38mm, watchOS 2.2
```

OK. So I want to run iPhone-6s:
`ionic emulate ios --target="iPhone-6s, 9.3"` or `ionic run ios --target="iPhone-6s, 9.3"`
and after a while in my terminal there is this information: `--devicetypeid was not specified, using first available device: Apple Watch - 38mm.` 

In this state debugging on iOS is unusable because my app isn't for Apple Watch but for iPhone.

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by galuszkak** [comment]
@jthoms1 sure!

```
ionic info                                                                               15:51:56  ☁  dev ☂ ⚡ ✭

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by Barryrowe** [comment]
Has there been an update on this at all? This really slows down our debug cycle having to go run without console output/livereload or having to deploy to a device.

My ionic-info:

ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.1.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by Barryrowe** [comment]
I spoke too soon, My info showingup against  @galuszak 's data showed I needed an update. I just unintsalled and reinstalled ionic and the --target parameter appears to be working now. in ionic@2.0.0

```
npm uninstall -g ionic && npm install -g ionic
```
