### ISSUE TITLE
Running ionic serve doesn't build ubuntu 14.04

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1106]
_From @jpmsegurado on June 23, 2016 22:41_

I installed the starter tabs project, and Idk why, when I run ionic serve it doesn't build, I have to run gulp build to see the modifications. The ionic 1 works fine but the 2 doesn't.

_Copied from original issue: driftyco/ionic#7030_

**Comment by jgw96** [comment]
Hello! Thank you for opening an issue with us! As this is an issue with the cli and not the framework I will be moving this issue to the cli repo. Thanks for using Ionic!

**Comment by jpmsegurado** [comment]
Ok, thanks, sorry for the mistake. But is there anything that I can provide to help you guys help me?

**Comment by jgw96** [comment]
No problem! What version of the cli are you running? For Ionic 2 projects you will need to install the ionic beta cli which supports both Ionic 1 and Ionic 2 projects. To install it you can run `sudo npm install -g ionic@beta`.

**Comment by jpmsegurado** [comment]
I actually already did that and still don't build when I serve :(
