### ISSUE TITLE
error to run android

### ISSUE THREAD

**Issue by emoryr** [ionic-team/ionic-cli#1113]
Hi, 
When I run "ionic run android" I get the error below:

Running 'run:before' gulp task before run
[09:15:02] Starting 'clean'...
[09:15:02] Finished 'clean' after 43 ms
[09:15:02] Starting 'build'...
[09:15:02] Starting 'sass'...
[09:15:02] Starting 'html'...
[09:15:02] Starting 'fonts'...
[09:15:02] Starting 'scripts'...
[09:15:02] Finished 'scripts' after 54 ms
[09:15:02] Finished 'html' after 61 ms
[09:15:02] Finished 'fonts' after 64 ms
[09:15:03] Finished 'sass' after 974 ms
[09:15:16] Finished 'build' after 15 s
[09:15:16] Starting 'run:before'...
[09:15:16] Finished 'run:before' after 6.53 μs

Running command: /home/emory/Ionic-projects/RankingSGV-v2/hooks/after_prepare/010_add_platform_class.js /home/emory/Ionic-projects/RankingSGV-v2

add to body class: platform-android

ANDROID_HOME=/home/emory/Android/Sdk

JAVA_HOME=/usr/lib/jvm/java-8-oracle

ERROR running one or more of the platforms: Error: adb: Command failed with exit code 1 Error output:
error: could not install _smartsocket_ listener: Address already in use
ADB server didn't ACK
- failed to start daemon *
  error: cannot connect to daemon
  You may not have the required environment or OS to run this project

---

ionic info:

Your system information:

Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.29
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID: Ubuntu Description: Ubuntu 16.04 LTS 
Node Version: v5.6.0

Did I missing something? 

THanks in advanced

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post the output of ionic info here please? Thanks for using Ionic!

**Comment by emoryr** [comment]
Hi, it is the first message:

ionic info:

Your system information:

Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.29
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID: Ubuntu Description: Ubuntu 16.04 LTS 
Node Version: v5.6.0

Anyway, thanks for the prompt message
