### ISSUE TITLE
proxy issue with gradlew and ionic-cli

### ISSUE THREAD

**Issue by mike-aungsan** [ionic-team/ionic-cli#1128]
I am behind proxy. Try this command. ionic run android

I set proxy at cmd, set proxy=proxy.domain.com:811
I also put proxy info in gradle.properties in .gradle folder.
systemProp.http.proxyHost=proxy.domain.com
systemProp.http.proxyPort=811
systemProp.https.proxyHost=proxy.domain.com
systemProp.https.proxyPort=812

This cmd work tho.
C:\Users\a\Documents\ionic\cutePuppyPics>gradlew -Dhttp.proxyHost=pro
xy.domain.com -Dhttp.proxyPort=811

Error: Error code 1 for command: cmd with args: /s,/c,"C:\Users\a\Documents
\ionic\cutePuppyPics\platforms\android\gradlew cdvBuildDebug -b C:\Users\a\Documents\ionic\cutePuppyPics\platforms\android\build.gradle -PcdvBu
ildArch=x86 -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"

No target specified, deploying to emulator

FAILURE: Build failed with an exception.
- What went wrong:

A problem occurred configuring root project 'android'.

> Could not resolve all dependencies for configuration ':classpath'.
> 
> Could not resolve com.android.tools.build:gradle:1.5.0.

```
 Required by:

     :android:unspecified
```

> Could not GET 'https://repo1.maven.org/maven2/com/android/tools/build/gradle/1
> .5.0/gradle-1.5.0.pom'.
> 
> Connection to https://repo1.maven.org refused

**Comment by swbradshaw** [comment]
You need to configure gradle to work behind a proxy server. 

See this solution: http://stackoverflow.com/questions/30219065/gradle-cant-connect-to-maven-repo-through-corporate-proxy-need-to-configure-t/30243902#30243902

I'm not sure if Ionic team is trying to solve that, if so they need special proxy handling for NPM, Gradle, and Typings (node module) to make them all work behind proxy.

**Comment by oikonomopo** [comment]
For me the [issue][1] was the `http` prefix! If this is your case, remove `http/https` prefixes!

I had my gradle.properties like this, and was failing:

    systemProp.http.proxyHost=http://squid.proxy.com
    systemProp.http.proxyPort=8080
    systemProp.https.proxyHost=http://squid.proxy.com
    systemProp.https.proxyPort=8080


----------

> Proper way to set proxy settings for gradle is:
> 
>     systemProp.http.proxyHost=squid.proxy.com
>     systemProp.http.proxyPort=8080
>     systemProp.https.proxyHost=squid.proxy.com
>     systemProp.https.proxyPort=8080


  [1]: https://github.com/gradle/gradle/issues/2182
