### ISSUE TITLE
Ionic serve unable to update live reload 

### ISSUE THREAD

**Issue by giorgiopiatti** [ionic-team/ionic-cli#1130]
When I edit a file I show that error in the command line: Unable to update live reload: Error getaddrinfo EONENT localhost:35729

Cordova Cli: 6.0.0
Gulp version: cli version 3.9.1
Gulp local: local version 3.9.1
Ionic framework version: 2.0.0@beta.9
Ionic cli version: 2.0.0-beta.32
Ionic app lib version: 2.0.0-beta.18
OS: Windows 10
Node version v6.2.2

**Comment by KevinQiaoL** [comment]
Hi, have you solved this problem, I met the same problem. Looking forward to your reply soon!
