### ISSUE TITLE
individual providers should not get their own folder

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1135]
After chatting with the team this morning we have decided that it does not make sense for each individual provider to have its own folder. Currently when you generate a provider using `ionic g provider CoolProvider` it creates a provider at this path `app/providers/cool-provider/cool-provider.ts`, with this proposal the path would be `app/providers/cool-provider.ts`.

**Comment by thibaudsowa** [comment]
It is the actual behavior now. I think you can close this issue.

**Comment by phice** [comment]
is it possible to still specify it with a flag?

**Comment by ricardo-mello** [comment]
I know that it's the actual behavior, but where should we put the tests and mocks? I think that generate folders prepares the provider to be tested and mocked.
