### ISSUE TITLE
ionic plugin add de.appplant.cordova.plugin.background-mode

### ISSUE THREAD

**Issue by HuiguangChu** [ionic-team/ionic-cli#1136]
Error: egistry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.plugin.background-mode

so the URL is not correct anymore

**Comment by Natanael1234** [comment]
Same problem here.

**Comment by mamartins** [comment]
also here

**Comment by pblpzmn** [comment]
cordova plugin add https://github.com/katzer/cordova-plugin-background-mode.git
