### ISSUE TITLE
package.json version

### ISSUE THREAD

**Issue by Zorgatone** [ionic-team/ionic-cli#1143]
Hi, everytime I create a new app with ionic@beta some standard properties are missing from the package.json file, could you fix it?

In particular I'm using the [Cmder](http://cmder.net/) console on Windows and it's getting annoying everything `cd` to the project folder and i get a lua error when parsing the package.json, because the command prompt displays the nodeJS package version.

**Comment by jthoms1** [comment]
Not sure I understand.  Are you saying that the package.json file is missing something or are you requesting that we cd to the newly created directory after creating it with `ionic start`?

Thanks

**Comment by Zorgatone** [comment]
No there's no need to 'cd' in the directory. I'm saying the package.json is
missing some standard fields, and my command prompt emulator environment is
failing to parse it when I 'cd' in the project directory
