### ISSUE TITLE
Ionic build android Error

### ISSUE THREAD

**Issue by SellvakumarSS** [ionic-team/ionic-cli#1147]
throwing please install android:target23 error is coming and i already install android sdk target 23 and set the environment variable.
Pls suggest me a solution.

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by SellvakumarSS** [comment]
This is my details and 
i set tools & platform tools path in environment variables
but still throwing error like install android23 and i want a apk to be built 

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 8.1
Node Version: v6.2.2

**Comment by SellvakumarSS** [comment]
the exact error i got in CLI is as follows:


D:\ionic2R&D\ionic2tabs>ionic build android
(node:4928) fs: re-evaluating native module sources is not supported. If you are
 using the graceful-fs module, please update it to a more recent version.

Running 'build:before' gulp task before build
[13:00:10] Starting 'clean'...
[13:00:10] Finished 'clean' after 62 ms
[13:00:10] Starting 'build'...
[13:00:10] Starting 'sass'...
[13:00:10] Starting 'html'...
[13:00:10] Starting 'fonts'...
[13:00:10] Starting 'scripts'...
[13:00:10] Finished 'html' after 44 ms
[13:00:10] Finished 'scripts' after 45 ms
[13:00:10] Finished 'fonts' after 52 ms
[13:00:11] Finished 'sass' after 843 ms
[13:00:20] Finished 'build' after 9.72 s
[13:00:20] Starting 'build:before'...
[13:00:20] Finished 'build:before' after 3.53 µs

 0=82, 1=117, 2=110, 3=110, 4=105, 5=110, 6=103, 7=32, 8=99, 9=111, 10=109, 11=1
09, 12=97, 13=110, 14=100, 15=58, 16=32, 17=34, 18=68, 19=58, 20=92, 21=80, 22=1
14, 23=111, 24=103, 25=114, 26=97, 27=109, 28=32, 29=70, 30=105, 31=108, 32=101,
 33=115, 34=92, 35=110, 36=111, 37=100, 38=101, 39=106, 40=115, 41=92, 42=110, 4
3=111, 44=100, 45=101, 46=46, 47=101, 48=120, 49=101, 50=34, 51=32, 52=34, 53=68
, 54=58, 55=92, 56=105, 57=111, 58=110, 59=105, 60=99, 61=50, 62=82, 63=38, 64=6
8, 65=92, 66=105, 67=111, 68=110, 69=105, 70=99, 71=50, 72=116, 73=97, 74=98, 75
=115, 76=92, 77=104, 78=111, 79=111, 80=107, 81=115, 82=92, 83=97, 84=102, 85=11
6, 86=101, 87=114, 88=95, 89=112, 90=114, 91=101, 92=112, 93=97, 94=114, 95=101,
 96=92, 97=48, 98=49, 99=48, 100=95, 101=97, 102=100, 103=100, 104=95, 105=112,
106=108, 107=97, 108=116, 109=102, 110=111, 111=114, 112=109, 113=95, 114=99, 11
5=108, 116=97, 117=115, 118=115, 119=46, 120=106, 121=115, 122=34, 123=32, 124=3
4, 125=68, 126=58, 127=92, 128=105, 129=111, 130=110, 131=105, 132=99, 133=50, 1
34=82, 135=38, 136=68, 137=92, 138=105, 139=111, 140=110, 141=105, 142=99, 143=5
0, 144=116, 145=97, 146=98, 147=115, 148=34
 0=13, 1=10
 0=97, 1=100, 2=100, 3=32, 4=116, 5=111, 6=32, 7=98, 8=111, 9=100, 10=121, 11=32
, 12=99, 13=108, 14=97, 15=115, 16=115, 17=58, 18=32, 19=112, 20=108, 21=97, 22=
116, 23=102, 24=111, 25=114, 26=109, 27=45, 28=97, 29=110, 30=100, 31=114, 32=11
1, 33=105, 34=100, 35=10
Error: Please install Android target: "android-23".

Hint: Open the SDK manager by running: "D:\softwares\android-sdk-windows\tools\a
ndroid.bat"
You will require:
1. "SDK Platform" for android-23
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)


Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by SellvakumarSS** [comment]
My path:
D:\softwares\android-sdk-windows\tools;D:\softwares\android-sdk-windows\platform-tools

**Comment by SellvakumarSS** [comment]
![android-sdk-windows-andriod23](https://cloud.githubusercontent.com/assets/20293500/16645924/f62839dc-4444-11e6-8b45-31e05f18b04a.png)

**Comment by SellvakumarSS** [comment]
plz do reply...

**Comment by ViolaMa** [comment]
#1185 the same issue have been solved by updating the ionic to ionic-beta.35

**Comment by SellvakumarSS** [comment]
Upgraded to ionic-beta.35 
But getting below error....

Running 'build:before' gulp task before build
[15:44:48] Starting 'clean'...
[15:44:48] Finished 'clean' after 32 ms
[15:44:48] Starting 'build'...
[15:44:48] Starting 'sass'...
[15:44:48] Starting 'html'...
[15:44:48] Starting 'fonts'...
[15:44:48] Starting 'scripts'...
[15:44:48] Finished 'html' after 34 ms
[15:44:48] Finished 'scripts' after 33 ms
[15:44:48] Finished 'fonts' after 42 ms
[15:44:49] Finished 'sass' after 787 ms
[15:44:54] Finished 'build' after 5.56 s
[15:44:54] Starting 'build:before'...
[15:44:54] Finished 'build:before' after 3.85 µs

Running command: "D:\Program Files\nodejs\node.exe" "D:\ionic2R&D\build\hooks\af
ter_prepare\010_add_platform_class.js" "D:\ionic2R&D\build"


add to body class: platform-android

ANDROID_HOME=D:\androidsdk

JAVA_HOME=C:\Program Files\java\jdk1.7.0_75

'D\build\platforms\android\' is not recognized as an internal or external comman
d,
operable program or batch file.

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

Error: cmd: Command failed with exit code 1 Error output:
'D\build\platforms\android\' is not recognized as an internal or external comman
d,
operable program or batch file.
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by SellvakumarSS** [comment]
any reply plz.....
