### ISSUE TITLE
Add username and password arguments to package commands

### ISSUE THREAD

**Issue by webberig** [ionic-team/ionic-cli#1150]
Hi,

I'm trying to set up CI for an ionic 2 project using Jenkins. I'm having trouble running the package build command on the server because the cli requires a login. While the upload command supports arguments for logging in, the packag commands do not.

Since our Jenkins is running in a docker container, I can't simply perform the login manually, the container is recreated regularly and loses the saved credentials.

Is there a way around this? Can you please add arguments so we can pass credentials to the command as arguments?

**Comment by rolandjitsu** [comment]
Any news on this, it's been quite some time?

**Comment by dwieeb** [comment]
Closing as this is related to Ionic Cloud. 

The new CLI 4 will have `IONIC_TOKEN` environment variable you can set (alternatively you can use `IONIC_USERNAME` and `IONIC_PASSWORD`).

But I don't think this issue is relevant anymore with the Pro services we offer.
