### ISSUE TITLE
Ionic Crosswalk Apache Cordova vulnerability

### ISSUE THREAD

**Issue by pushparajsamant** [ionic-team/ionic-cli#1158]
Hi,
We are using Ionic 1.3.21 and crosswalk 13.41.318.0. So when I add crosswalk to my project it replaces my android platform with android 4.0.0-dev. Now google is giving me the following warning.
"Your app is using a version of Apache Cordova containing one or more security vulnerabilities. Please migrate your app(s) to Apache Cordova v.4.1.1 or higher as soon as possible and increment the version number of the upgraded APK"
My Cordova CLI version is 6.2.0. I am not sure as to what I need to update to satisfy Google's requirement. Can anyone help me with this ?

**Comment by leonardobazico** [comment]
@pushparajsamant, try:

```bash
cordova platform update android@4.1.0
```

**Comment by pushparajsamant** [comment]
Hi Leonardo,
Thanks for the response but I am already using cordova android@5.0.0. My first command is
cordova platform add android@5.0.0. But when I add crosswalk it replaces this platform with android@4.0.0dev.

**Comment by leonardobazico** [comment]
Hi Pushparaj,

Now I'm using cordova-plugin-crosswalk-webview@1.5.0 and my installed platforms are android 5.1.1 and ios 4.1.0.

How you installed crosswalk?

I know two methods:
```bash
#old method
ionic browser add crosswalk

#new method
ionic plugin add cordova-plugin-crosswalk-webview
```

**Comment by jthoms1** [comment]
@pushparajsamant Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by pushparajsamant** [comment]
Here it is Josh.

OS: Mac OS X Yosemite
Node Version: v0.10.36
Cordova CLI: 5.4.1
Ionic CLI Version: 1.3.19
Xcode version: Xcode 7.3 Build version 7D175 
ios-sim version: 5.0.6 
ios-deploy version: Not installed



------------------------------------
Ionic CLI is out of date:
 * Locally installed version: 1.3.19
 * Latest version: 1.7.16
 * https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md
 * Run npm install -g ionic to update
-----------------------------------

**Comment by pushparajsamant** [comment]
I add crosswalk using ionic browser add crosswalk

**Comment by leonardobazico** [comment]
@pushparajsamant, so try: 

```bash
ionic browser rm crosswalk
cordova platform update android@5.2.0
ionic plugin add cordova-plugin-crosswalk-webview
```

**Comment by pushparajsamant** [comment]
I did the above things you mentioned and then when I run cordova build android my build fails with the following error
/Users/pushparaj/Documents/Workspaces/crossWalkUpdate/mobile-app/platforms/android/src/org/crosswalk/engine/XWalkCordovaHttpAuthHandler.java:22: error: cannot find symbol
import org.xwalk.core.XWalkHttpAuthHandler;
                     ^
  symbol:   class XWalkHttpAuthHandler
  location: package org.xwalk.core
/Users/pushparaj/Documents/Workspaces/crossWalkUpdate/mobile-app/platforms/android/src/org/crosswalk/engine/XWalkCordovaHttpAuthHandler.java:30: error: cannot find symbol
    private final XWalkHttpAuthHandler handler;

**Comment by pushparajsamant** [comment]
Any help available on this. I am still struggling with this

**Comment by lbngoc** [comment]
same problem as here.
Is there any updates for this issue ?

> $ ionic -v                                                                                                                                                                                                                                                            
> 2.0.0 
> $ cordova -v                                                                                                                                                                                                                                                          
> 6.3.1

I think this issue is occur when I updated some things (may be ionic-cli), because before a month, I built and ran my app on android device successfully. I almost run on iOS and not face this issue.

**Comment by pushparajsamant** [comment]
I ended up removing crosswalk from my android build.

**Comment by dwieeb** [comment]
Yes, Crosswalk is no longer maintained. Please do not use it.
