### ISSUE TITLE
ionic serve not working after installing ionic 2

### ISSUE THREAD

**Issue by praveens96** [ionic-team/ionic-cli#1162]
recently installed ionic2. after that when i try to run/open (i.e. ionic serve) ionic 1 projects which i have done earlier it is throwing me a message: "WARN: ionic.project has been renamed to ionic.config.json, please rename it. Uh oh! Looks like you're missing a module in your gulpfile: Cannot find module 'gulp' Do you need to run npm install?"

I have tried installing bower,gulp, gulp-util. but nothing worked. has anybody got this issue? can somebody help me?

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by praveens96** [comment]
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Windows 7 SP1
Node Version: v0.12.7

**Comment by phice** [comment]
Did you manage to solve this problem? I've found no answers yet to this very critical problem, how do the ionic team thinks we can build apps with ionic 2 if we cannot maintain our ionic 1 apps?

**Comment by praveens96** [comment]
ran npm install
then did ionic serve, it helped me

**Comment by gruppjo** [comment]
make sure you have `v2.1.0` of the CLI
```sh
ionic -v
```

**Comment by phice** [comment]
I've managed to solve it, I've also put all my procedure here :[http://stackoverflow.com/questions/37468749/ionic-2-ionic-1-work-on-different-node-versions/39765640#39765640]
