### ISSUE TITLE
Email or Password incorrect

### ISSUE THREAD

**Issue by rohankveer** [ionic-team/ionic-cli#1170]
**Type**: bug

When using **ionic login** I am getting an error "Email or Password incorrect". Please visit https://apps.ionic.io for help.

I am using :

Ionic Framework Version : 1.3.1
Ionic CLI Version : 2.0.0-beta.32

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Are you logging in with the correct credentials?

**Comment by rohankveer** [comment]
Yes I am using the correct credentials.

**Comment by mhartington** [comment]
Can you provide node version and OS version

**Comment by rohankveer** [comment]
I am using Windows 10 ( 64 bit ) and Node version 4.4.7

**Comment by daanylo** [comment]
I have the same problem. 
I'm using:

Your system information:

```
Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

And the Error Message:

```
ionic login

To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

Email: danilo@tpass.com.br
Password: 
Email or Password incorrect. Please visit https://apps.ionic.io for help.
```

Or:

```
ionic upload
WARN: No 'upload:before' gulp task found!
If your app requires a build step, you may want to ensure it runs before upload.

Uploading app....
An error occurred uploading the build: Forbidden upload (403)

Forbidden upload (403) (CLI v2.0.0-beta.37)
```

**Comment by zeqk** [comment]
I have the same problem

Cordova CLI: 6.0.0                                                                                                       
Gulp version:  CLI version 3.9.1                                                                                         
Gulp local:   Local version 3.9.1                                                                                        
Ionic Framework Version: 2.0.0-beta.10                                                                                   
Ionic CLI Version: 2.0.0-beta.30                                                                                         
Ionic App Lib Version: 2.0.0-beta.16                                                                                     
OS: Windows 8.1                                                                                                          
Node Version: v6.2.1

**Comment by wayoff** [comment]
> ionic upload --note "description" --deploy dev
No previous login existed. Attempting to log in now.

To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

Email: my_email@mail.com
Password:
Email or Password incorrect. Please visit https://apps.ionic.io for help.
Uploading app....
An error occurred uploading the build: TypeError: Cannot read property 'map'
of undefined
--------------------------------

TypeError: Cannot read property 'map' of undefined
    at Object.getDirectUploadKey (C:\Users\MyComputerName\AppData\Roaming\nvm\v6.6.0
\node_modules\ionic\node_modules\ionic-app-lib\lib\upload.js:262:18)
    at C:\Users\MyComputerName\AppData\Roaming\nvm\v6.6.0\node_modules\ionic\node_mo
dules\ionic-app-lib\lib\upload.js:40:21
    at _fulfilled (C:\Users\MyComputerName\AppData\Roaming\nvm\v6.6.0\node_modules\i
onic\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\MyComputerName\AppData\Roaming\nvm\v6.6.0
\node_modules\ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\MyComputerName\AppData\Roaming\nvm\
v6.6.0\node_modules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\MyComputerName\AppData\Roaming\nvm\v6.6.0\node_modules\ionic\node_mo
dules\q\q.js:509:49
    at flush (C:\Users\MyComputerName\AppData\Roaming\nvm\v6.6.0\node_modules\ionic\
node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


Cannot read property 'map' of undefined (CLI v2.1.4)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Windows 7 SP1
Node Version: v6.6.0

note:  login is working and also upload when logged.. it just that it's giving an error (i really think it should not) when there's an incorrect email or password upon log in.. just letting you know guys

**Comment by shankari** [comment]
any solution or workaround for this?

**Comment by Zwoch** [comment]
i have the same problem. 
cli packages: (/Users/torstenzwoch/projects/tfs/sopi/sopi.ionic.demo/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.0 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.3.0 browser 4.1.0 ios 4.5.1 windows 5.0.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    ios-deploy : 1.9.2 
    Node       : v6.11.0
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235

**Comment by Zwoch** [comment]
now i get the following error

HTTP Error 503: POST https://api.ionic.io/login
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>

**Comment by pavel-kurnosov** [comment]
Same problem, I updated to last version and now can't use ionic cli to generate anything.
