### ISSUE TITLE
ionic build Caught exception: undefined

### ISSUE THREAD

**Issue by zaratamo** [ionic-team/ionic-cli#1177]
I created a new project with " ionic start 'name' blank --v2 " and add android platform, then i run ionic build and it launch exception

Running 'build:before' gulp task before build
[13:00:27] Starting 'clean'...
[13:00:27] Finished 'clean' after 68 ms
[13:00:27] Starting 'build'...
[13:00:27] Starting 'sass'...
[13:00:27] Starting 'html'...
[13:00:27] Starting 'fonts'...
[13:00:27] Starting 'scripts'...
[13:00:27] Finished 'html' after 100 ms
[13:00:27] Finished 'scripts' after 126 ms
[13:00:27] Finished 'fonts' after 152 ms
[13:00:29] Finished 'sass' after 2.28 s
[13:00:45] Finished 'build' after 18 s
[13:00:45] Starting 'build:before'...
[13:00:45] Finished 'build:before' after 16 μs

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Ionic info shows:

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS:
Node Version: v4.2.4

**Comment by nottinhill** [comment]
Getting the same. Did you figure out your problem?

**Comment by nottinhill** [comment]
btw. your node version is pretty old.

**Comment by n00b42** [comment]
Getting the same error in my project.
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 10
Node Version: v4.3.1
```

**Comment by n00b42** [comment]
`ionic serve` works without errors.
And manually running `cordova build android` seems to work though.

**Comment by zaratamo** [comment]
I launch 'ionic build' seems to must specific platfoms, 'ionic build android' works.

**Comment by n00b42** [comment]
Executing `ionic build android` or `ionic build --release android` both resulted in the exception for me.

**Comment by nottinhill** [comment]
I'm a step further, it seems to be an Android version and/or path relatwd issue. After downgrading to droid toolkit v23 I at least am getting into the gradle build process, still failing, but different errors, so its progress.


stephan kristyn

Am 20. Juli 2016, 11:43 +0200 schrieb n00b42<notifications@github.com>:

**Comment by ThorConzales** [comment]
Same problem here. However without --release key it worked. So current workaround is to run either "ionic build android" or "ionic run android" to get the files compiled and then running "cordova build --release android" on top of it.

**Comment by soulman-is-good** [comment]
Same here. Builds fine without _--release_ key but throws undefined exception with.

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.2 Rafaela 
Node Version: v4.0.0

**Comment by nottinhill** [comment]
I figured it out, cordova has a bug. You need to create build-extras.gradle file to override cordova bug. I made a blog post about this morning: http://meshfields.de/build-android-apk-with-ionic2-beta-and-cordova-on-a-osx/

May the (hybrid) force be with you!

stephan kristyn

Am 22. Juli 2016, 15:45 +0200 schrieb Maxim Savin <notifications@github.com>:

**Comment by mahdihrz** [comment]
Got the same issue 

`cordova build android` worked for me
`ionic build android` worked too.

still got `Caught exception: undefined` when running `ionic build` `ionic build ios`

For next versions, it will be great to show more meaningful error message or to run CLI in verbose mode

+1

**Comment by ranbuch** [comment]
+1

**Comment by Jenthe** [comment]
Got the exact same problem here.

**Comment by shaaaaawn** [comment]
Same issue here

**Comment by ryanlin1986** [comment]
This bug is here for at least two months. Come on please fix it

**Comment by in-dex** [comment]
I was getting the same problem until now

This worked for me: 
`npm update -g cordova`
`platform update android`

**Comment by ryanlin1986** [comment]
use ionic@beta latest version solved the problem
