### ISSUE TITLE
bug: error in android s not installed build tool 19.1.0

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1180]
_From @rakeshtiwari on July 15, 2016 14:15_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>After Gradle sync get "Error:No installed build tools found. Please install the Android build tools version 19.1.0 or higher". But i have installed latest version of android sdk with build tool  from 19.1.0 to 24.

My system information is as below:

Cordova CLI: 6.2.0
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Windows 7 SP1
Node Version: v4.2.2</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#7329_

**Comment by DrMabuse23** [comment]
````bash
ionic platform add android
(node:44483) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Adding android project...


Creating Cordova project for the Android platform:


	Path: platforms/android

	Package: io.ionic.starter
	Name: V2_Test
	Activity: MainActivity
	Android target: android-23

Android project created with cordova-android@5.1.1


Running command: /Users/pascalbrewing/htdocs/windows-test/wtest/client/hooks/after_prepare/010_add_platform_class.js /Users/pascalbrewing/htdocs/windows-test/wtest/client


Error: spawn EACCES


Caught exception:
 undefined 
````
same here 

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.5 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by almajidi** [comment]
hi im having the same problem with my cli. it shows this

C:\Users\abdullah izzudin\IIUMakan>cordova run android
Android Studio project detected
ANDROID_HOME=C:\Users\abdullah izzudin\android-sdks
JAVA_HOME=C:\Program Files\java\jdk1.8.0_102
studio
Subproject Path: CordovaLib
Subproject Path: app

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\abdullah izzudin\IIUMakan\platforms\android\CordovaLib\cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

can you help me fix this? much thanks!

**Comment by mehdi-bouhalassa** [comment]
Fucking shit...

**Comment by dwieeb** [comment]
@mehdi-bouhalassa I removed your comment. Please keep comments constructive. See our code of conduct: https://github.com/ionic-team/ionic/blob/master/CODE_OF_CONDUCT.md

Locking this issue. The error message is correct. You must install and configured Android build tools. These build tools come with Android Studio, which we recommend for managing Android projects.
