### ISSUE TITLE
ionic build android issued: Error: Cannot read property '1' of null

### ISSUE THREAD

**Issue by erwinpagulong** [ionic-team/ionic-cli#1182]
I have a project and tried to build in android and it gives me an error below. Even tho trying to build into a fresh project still the same.

Error: Cannot read property '1' of null

Caught exception:
 undefined 

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID: elementary OS Description:  elementary OS Freya 
Node Version: v4.4.7

**Comment by lenvonsam** [comment]
i faced the same problem , have you resolved it?@erwinpagulong
