### ISSUE TITLE
ionic resources --splash command not updating ios resources

### ISSUE THREAD

**Issue by rongg** [ionic-team/ionic-cli#1191]
Running the resources command resulted in correct assets generated everywhere except ios. Took a look at platforms/ios/myApp/resources and the newly generated images were not updated, even though the correct drawables were added to android/res.

**Workaround:** Had to copy files manually from resources/ios to platforms/ios/myApp/resources

**Comment by schankam** [comment]
Same problem here.

Related to https://github.com/driftyco/ionic-cli/issues/1166

**Comment by DavidTalamona** [comment]
@tisron resources are not atomatically deployed / copied to the platforms!
You have remove and re-add the platform (`ionic platform remove ios` and `ionic platform add ios`).
After that the icons and splashscreens should be there in the platform.

Would be nice for the Ionic team to fix that cause I saw many people in other forums having the same issue.

**Comment by Ross-Rawlins** [comment]
+1 this is still an issue I just tried it.

**Comment by brunobc182** [comment]
Same problem here, any fix or workaround for this?

**Comment by DavidTalamona** [comment]
The "resources" command creates a directory named "res" in the project root.
As a workaround you can manually move those files to the correct directory in the patform.
