### ISSUE TITLE
ionic@beta won't live-reload sass on ionic1 projects

### ISSUE THREAD

**Issue by voliva** [ionic-team/ionic-cli#1192]
Related to #1157, if you have a project in ionic1 with sass support, the live-reload feature on `ionic serve` won't work if you have ionic2 cli installed.

Steps to reproduce the issue:

```
npm install -g ionic
ionic start blank blank
cd blank
ionic setup sass
ionic serve
- Make a change on sass file and see how it live-reloads -
^C
npm install -g ionic@beta
ionic serve
- Make a change on sass file and see how it doesn't live-reload -
```

As a workaround, you have to keep a separate terminal open and call `gulp sass`, then it will live-reload the changes on the .css file.

**Comment by barocsi** [comment]
This is poor. My ionic beta 2 on my v1 project is not livereloading, just serving. I need to manually run gulp build tasks and there is no reference on how to do it with v1 projects properly.

**Comment by kelvinblade** [comment]
+1

**Comment by cleever** [comment]
Same here.

It's awful for whom develop ionic v1 and v2 apps.

**Comment by okonon** [comment]
+1

**Comment by DevNIX** [comment]
Can you provide your package.json and your gulpfile?

**Comment by voliva** [comment]
@DevNIX This is such an old issue that I guess it's not longer relevant. I'm not even working on that project anymore. If anyone could confirm this is solved, we should close this issue.

The steps to reproduce are exactly as told in the original report, now adding versions from #1157:
```
npm install -g ionic@1.7.16
ionic start blank blank
cd blank
ionic setup sass
ionic serve
- Make a change on sass file and see how it live-reloads -
^C
npm install -g ionic@2.0.0-beta.32
ionic serve
- Make a change on sass file and see how it doesn't live-reload -
```

The ionic starter for that version should provide the package.json and gulpfile you need.

**Comment by dwieeb** [comment]
@voliva I didn't test `ionic@2.0.0-beta.32`. Not sure what that even is. The latest CLI works fine for me, though (`3.14.0`).

`npm install -g ionic@latest`
