### ISSUE TITLE
project structure should follow Angular 2 styleguide

### ISSUE THREAD

**Issue by rolandjitsu** [ionic-team/ionic-cli#1194]
It would be nice if the v2 of Ionic will follow the Angular 2 [styleguide](https://angular.io/styleguide#!#naming). Especially when naming the classes when using `ionic g page <my>`, there might be some confusion around `MyPage` because of the `@Component()` decorator (might make more sense to name it `MyComponent`).

It would also be more consistent with the Angular 2 apps that are not Ionic and are following the same styleguide.

**Comment by dwieeb** [comment]
Duplicate of https://github.com/ionic-team/ionic/issues/6847

Closing, if that's alright.
