### ISSUE TITLE
config.xml under the project root folder is not updated after ionic plugin add 

### ISSUE THREAD

**Issue by zjx** [ionic-team/ionic-cli#1207]
i encounter this problem recently which is weird, after i run the plugin add command from the root folder of the project, the platform (android & iOS ) level config.xml is updated automatically. 

for example, after "cordova plugin add cordova-plugin-geolocation", the xml under /PROJECT_ROOT/platforms/android/res/xml/config.xml is updated automatically to include something like below:

```
    <feature name="Geolocation">
        <param name="android-package" value="org.apache.cordova.geolocation.Geolocation" />
    </feature>
```

Anyway the /PROJECT_ROOT/config.xml is not updated.. I should manually merge the change from platform level config.xml.

Can it be an issue?

**Comment by dwieeb** [comment]
I don't think this is an issue. If it is, it'd be an issue with Cordova, not with the Ionic CLI. Thanks!
