### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by vpego** [ionic-team/ionic-cli#1251]
I was working on a simple app: 

updated ionic - OK
started new project - OK
created a couple of pages - OK
served the app - OK

but then I've tried to add the android platform:

> _ionic platform add android_

and got this error:

![image](https://cloud.githubusercontent.com/assets/15097772/17522453/7e4c6fca-5e2d-11e6-8e6e-589f5bec5d3e.png)

Any idea on how to fix it? Thanks!

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by arkwills** [comment]
the same message is reported on mine too even as I run ionic info
