### ISSUE TITLE
`ionic platform` commands not updating package.json

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/ionic-cli#1254]
The following comes by default...

```
"cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ]
```

...but `ionic platform` commands are not updating it. I've tried:

```
ionic platform remove ios
ionic platform add android
ionic platform remove android
```

My system information:

```
Cordova CLI: 6.3.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by devillized** [comment]
running `ionic state save`  persists it all to package.json

**Comment by amymarsh4work** [comment]
This worked for me too. Wish I had known about it sooner.

**Comment by AdrianTeh** [comment]
+1 Happening here as well. Used to update, but now its not :(

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014
