### ISSUE TITLE
`ionic plugin` commands not updating package.json/config.xml

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/ionic-cli#1255]
The following comes by default...

`package.json`:

```
"cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ]
```

`config.xml`:

```
<plugin name="cordova-plugin-device" spec="~1.1.2"/>
<plugin name="cordova-plugin-console" spec="~1.0.3"/>
<plugin name="cordova-plugin-whitelist" spec="~1.2.2"/>
<plugin name="cordova-plugin-splashscreen" spec="~3.2.2"/>
<plugin name="cordova-plugin-statusbar" spec="~2.1.3"/>
<plugin name="ionic-plugin-keyboard" spec="~2.2.1"/>
```

...but `ionic plugin` commands are not updating those. I've tried:

```
ionic plugin add cordova-plugin-inappbrowser
```

My system information:

```
Cordova CLI: 6.3.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by gligoran** [comment]
@nunoarruda: To have your plugins saved to config.xml, add the `--save` argument to the installation command.

`package.json`, however, is still not being updated. Is this even a bug, or is it by design and the `"cordovaPlugins"` section doesn't do anything?

**Comment by newelement** [comment]
I'm having the same issue installing native audio. The plugin is installed, but xcode is not recognizing it. My post in the forums: https://forum.ionicframework.com/t/native-audio-will-not-install/61226/6

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3.1 Build version 7D1014
