### ISSUE TITLE
`ionic start` improperly names Cordova project when default ios platform is added

### ISSUE THREAD

**Issue by amuramoto** [ionic-team/ionic-cli#1261]
Running `ionic start <project_name> <template> --v2` automatically adds a default ios platform in `/platforms`, but it does not use the correct project name. Instead it defaults to 'HelloCordova'. This can cause issues with some Cordova plugins.

For example:
1. Run `ionic start myApp blank --v2` 
2. CLI creates `/platforms/ios/HelloCordova` and `/platforms/ios/HelloCordova.xcodeproj`
3. CLI also sets `<name>HelloCordova</name>` in `/platforms/ios/HelloCordova/config.xml`

**Comment by amuramoto** [comment]
Not sure if this bug should be filed in https://github.com/driftyco/ionic-app-lib

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by amuramoto** [comment]
```
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014 
```
