### ISSUE TITLE
ionic serve not showing ts errors - but 'gulp build' does

### ISSUE THREAD

**Issue by greenstevester** [ionic-team/ionic-cli#1264]
I am using the following and saw multiple times that app.bundle.js was not getting gen'd only to find that there was an error which was not shown via ionic serve - but 'gulp build' does show the ts error.

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.3 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by spellman** [comment]
ionic serve started showing errors for me ONLY on the first build, when [transpileWorker](https://github.com/ionic-team/ionic-app-scripts/blob/master/src/transpile.ts#L94) is run.
After file changes, when [transpileWorkerUpdate](https://github.com/ionic-team/ionic-app-scripts/blob/master/src/transpile.ts#L191) is run, no errors are displayed in the terminal output or in the browser.
In the latter case, [diagnostics](https://github.com/ionic-team/ionic-app-scripts/blob/master/src/transpile.ts#L191) is empty so y'all's code in ionic-app-scripts is right not to display any errors.

Still, this started after I updated to ionic-app-scripts 3.0.0.
I'm seeing this behavior with both typescript 2.5.2 and 2.5.3.
