### ISSUE TITLE
Ionic Emulate IOS Live Reload - Blank Screen

### ISSUE THREAD

**Issue by ksclark** [ionic-team/ionic-cli#127]
Hello,
When I run the command
" ionic emulate ios -livereload " 
The emulator comes up but the screen is just white.

If i run " ionic emulate ios " the sample tabs app opens up just fine.

*_Versions : *_
ios-Sim : 3.0.0
Ionic : 1.2.7
Ios Simulator : Version 8.0 (550.1)
Xcode: Version 6.0.1 (6A317)
OSX : 10.9.4

Here's the output for the ionic emulate console
 ionic emulate ios --target="iPad (Retina)" -l
Setup Live Reload

Multiple addresses available.
Please select which address to use by entering its number from the list below:
Note that the emulator/device must be able to access the given IP address
Running dev server: http://192.168.18.21:8100
Running live reload server: http://192.168.18.21:35729
Watching : [ 'www/**/*', '!www/lib/**/*' ]
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

add to body class: platform-ios
Running command: /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/cordova/run --emulator "--target=iPad (Retina)"
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/build/emulator
    SDKROOT = iphonesimulator8.0
    VALID_ARCHS = i386

=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET BarBot OF PROJECT BarBot WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution Copy\ www\ directory build/BarBot.build/Debug-iphonesimulator/BarBot.build/Script-304B58A110DAC018002A0835.sh
    cd /Users/kclark/Desktop/webdevel/BarBot/platforms/ios
    /bin/sh -c /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/build/BarBot.build/Debug-iphonesimulator/BarBot.build/Script-304B58A110DAC018002A0835.sh

real    0m0.229s
user    0m0.085s
sys 0m0.138s

ProcessInfoPlistFile build/emulator/BarBot.app/Info.plist BarBot/BarBot-Info.plist
    cd /Users/kclark/Desktop/webdevel/BarBot/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    builtin-infoPlistUtility /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/BarBot/BarBot-Info.plist -genpkginfo /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/build/emulator/BarBot.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/build/BarBot.build/Debug-iphonesimulator/BarBot.build/MainViewController-PartialInfo.plist -o /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/build/emulator/BarBot.app/Info.plist

GenerateDSYMFile build/emulator/BarBot.app.dSYM build/emulator/BarBot.app/BarBot
    cd /Users/kclark/Desktop/webdevel/BarBot/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/build/emulator/BarBot.app/BarBot -o /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/build/emulator/BarBot.app.dSYM

Touch build/emulator/BarBot.app
    cd /Users/kclark/Desktop/webdevel/BarBot/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /usr/bin/touch -c /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/build/emulator/BarBot.app

*\* BUILD SUCCEEDED **

2014-10-14 14:00:54.286 ios-sim[22963:507] stderrPath: /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/cordova/console.log
2014-10-14 14:00:54.287 ios-sim[22963:507] stdoutPath: /Users/kclark/Desktop/webdevel/BarBot/platforms/ios/cordova/console.log
Usage of '--family' is deprecated in 3.x. Use --devicetypeid instead.
Usage of '--retina' is deprecated in 3.x. Use --devicetypeid instead.

Here's the image of the ios simulator when you run " ionic emulate ios --livereload
![ios simulator screen shot oct 14 2014 1 31 08 pm](https://cloud.githubusercontent.com/assets/6753827/4634066/bad46adc-53cc-11e4-94ee-6beaa6c13471.png)

**Comment by wadeanderson7** [comment]
+ 1

**Comment by numerized** [comment]
Same problem here option LiveReload doesn't let me launch the app, without live reload everything is fine, I tried to bootstrap manually, same pb.

**Comment by pencilcheck** [comment]
Can't livereload as well, all I see is the lines in the log

```
Installing app on device...
Launching application...
LAUNCH SUCCESS
cordova process is exiting
```

Somehow cordova process is exiting if livereload is enabled

**Comment by nileshlg2003** [comment]
Same problem for me too, Can't liverload app on android device. Shows black screen.
Installing app on device...
Launching application...
LAUNCH SUCCESS
cordova process is exiting

**Comment by chillyprig** [comment]
This problem happens to me too,

Installing app on device...
Launching application...
LAUNCH SUCCESS
cordova process is exiting

**Comment by mattezell** [comment]
I believe that the most common cause for this is as some have described - wifi being off or the device being on a different network from your dev pc hosting the live reload server.

For those of you who began experiencing this recently and who are perhaps using Crosswalk, apparently the whitelist functionality has been split off into a plugin from Cordova.  For many of us, it's this missing whitelist that's leading to the white screen / app not loading issue...

Adding the whitelist plugin directly as is described in this thread resolved the white screen issue for me: http://forum.ionicframework.com/t/crosswalk-integration-beta-in-ionic-cli-v1-3-2/15190/270

**Comment by shanecp** [comment]
Had the same issue, but anything listed above didn't fix it for me.

The app will load on the simulator by XCode, but not from command line.

Finally I updated XCode and XCode tools to the latest version, and it fixed it for me. 
So try doing that as well.

**Comment by braidenjudd** [comment]
I replicated this issue when I had something other than * in the line <access origin="*"/>.

If I had a URL there, I would get the loading splash screen then nothing, if I have * the app loads fine.

**Comment by emve-dev** [comment]
Turning off Windows Firewall solved the issue. Try adding exceptions in firewall settings for ports that you use.

**Comment by emve-dev** [comment]
I spent some time configuring the firewall settings and managed to get things work.

###### Here are some tips:
1. Make sure your computer and phone are connected to the same wireless network.
2. Add Inbound Windows Firewall Rule in here `Control Panel\All Control Panel Items\Windows Firewall -> Advanced Settings`. Set protocol TCP, desired ports (in my case: 8100, 35729), and Profile: Private (under `Advanced` tab).
3. The connection on your computer MUST use `Home` or `Work` profile (Private) because if connection is Public firewall will still block the connection (I'm guessing because of disabled network discovery). (Look here: `Control Panel\All Control Panel Items\Network and Sharing Center`)

_Hope it will save you some time._

**Comment by frazras** [comment]
I was running Cloak VPN, once I disabled it, everything worked fine.

**Comment by dhcar** [comment]
+1 on ios simulator and on device

**Comment by muro9358** [comment]
+1 on ios simulator and on device

**Comment by wilsolutions** [comment]
+1 same here
Note: looking at the logs I see that it complains that could not find the app. I did double check and the app is there the difference is: the app does not have the same name as the folder so, it keeps saying: .app doesn't exist!

**Comment by bcolston** [comment]
I also get this error on iOS when the device changes wifi networks and is no longer on the same network as the development laptop. On Android, it at least pops up a message that it can't reach the IP Address of the development laptop, which is how I finally figured out what was happening.

**Comment by nrempel** [comment]
Thanks @bcolston, that helped me sort out my issue.

**Comment by han4wluc** [comment]
For some reason, it would gave me a blank screen on Simulator iPhone 8.4. It works with Simulator Iphone 8.2.

**Comment by novarac23** [comment]
Hi!

I have the same issue here, when I was working from my home office and wifi there everything was working fine. Right now I am on a road and I have some mobile USB modem and I can not get livereload to work. So my guess is that its the wifi problem thing.

**Comment by madvas** [comment]
+1 Have the same problem on OS X and IOS simulator

**Comment by faizalzakaria** [comment]
+1 have the same problem in OS X + IOS simulator.

**Comment by gaballard** [comment]
+1 Same problem with OS X El Capitan and the Xcode 7.1 iOS simulator. My Ionic CLI console log shows absolutely nothing and I get a blank white page instead of my app.

**Comment by mfkenson** [comment]
+1 have the same problem in OS X + IOS simulator.

**Comment by mnewmedia** [comment]
+1 for OSX

Cordova CLI: 5.4.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by berkaey** [comment]
+1

**Comment by barocsi** [comment]
+1
any news?

**Comment by okonon** [comment]
I am still having same problem

**Comment by amirabiri** [comment]
+1

**Comment by gaballard** [comment]
For anyone still having this problem, a new Github issue has been opened about it:

[https://github.com/driftyco/ionic-cli/issues/605](https://github.com/driftyco/ionic-cli/issues/605)

**Comment by kadoshms** [comment]
+1

**Comment by tetpsy** [comment]
I have this issue if the connected device is on a different network that my pc. As soon as they are on the same network it works. In my case i connected to the shared internet hotspot that my mac created. Must be the livereload port that needs this connection

**Comment by realadamsmith** [comment]
Still a problem using an iphone cable to Macbook, and typing ionic cap run ios -l

**Comment by realadamsmith** [comment]
It's just best to do "ionic cap run ios -l --external"
