### ISSUE TITLE
app.bundle.js is over 1mb after minification

### ISSUE THREAD

**Issue by tomardern** [ionic-team/ionic-cli#1275]
Hi,

I'm using Ionic 2 to develop a web app that will be accessed through a standard browser (so not a cordova app). I've developed a basic app with three "pages".

When I run "gulp build --release", the app.bundle.js is over 1.5mb, which seems very large for such an app.

Thanks,

**Comment by dwieeb** [comment]
@tomardern I would maybe try filing an issue in the v1 repo if this is still a concern: https://github.com/ionic-team/ionic-v1/

But I know this is fairly old now.
