### ISSUE TITLE
ionic run android grabs wrong (old) apk after installing crosswalk 

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1283]
_From @daixtrose on August 17, 2016 17:1_
#### Short description of the problem:

When you install crosswalk, the old apk files do not get removed during android build and android run then takes the old packages. You have to delete all files below `platforms\android\build\outputs\apk\`first.
#### What behavior are you expecting?

`ionic run android` should run the x-walk version 

**Steps to reproduce:**
1. `ionic plugin add cordova-plugin-crosswalk-webview`
2. `ionic run android`

**Which Ionic Version?**  2.x

_Copied from original issue: driftyco/ionic#7758_

**Comment by Geoffrey-D** [comment]
I also had that issue. Removing the previous apk files manually in platforms\android\build\outputs\apk did solve the issue (took me some times to figure it out :p )

**Comment by AlDrag** [comment]
+1

**Comment by c0bra** [comment]
Almost a year later this is still an issue. Any plans for either a fix or adding this info to the docs so people like me and @Geoffrey-D don't waste a bunch of time?

**Comment by dwieeb** [comment]
Crosswalk is no longer maintained, so please do not use it. 

If anything this is a Cordova issue anyway, not an issue with the Ionic CLI.
