### ISSUE TITLE
getting err updating ionic cli 

### ISSUE THREAD

**Issue by saurabhvyas** [ionic-team/ionic-cli#1286]
``npm WARN In ionic@2.0.0 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.0.0 replacing bundled version of ionic-app-lib with ionic-app-lib@2.0.0
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\saurabhorange\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v5.12.0
npm ERR! npm  v3.10.5
npm ERR! path C:\Users\saurabhorange\AppData\Roaming\npm\node_modules.staging\ansi-d79499e3
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\saurabhorange\AppData\Roaming\npm\node_modules.staging\ansi-d79499e3' -> 'C:\Users\saurabhorange\AppData\Roaming\npm\node_modules\ionic\node_modules\cordova-lib\node_modules\ansi'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\saurabhorange\AppData\Roaming\npm\node_modules.staging\ansi-d79499e3' -> 'C:\Users\saurabhorange\AppData\Roaming\npm\node_modules\ionic\node_modules\cordova-lib\node_modules\ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     e:\ionic2\learning\myapp\campusapp\app\pages\npm-debug.log
npm ERR! code 1 
``

**Comment by blablapolicja** [comment]
I'm on Mac, but... Try to restart console and update again. I tried for 3 times. Then it got updated

**Comment by saurabhvyas** [comment]
I have tried 5 times same err  , now when I build my ionic project I am getting another err , My existing development environment is all gone :(

```
e:\ionic2\learning\myapp\campusapp>ionic build android
Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\saurabhorange\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:5:12)
    at Object.<anonymous> (C:\Users\saurabhorange\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:14:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

```

**Comment by ivanmayes** [comment]
Having the same issue upgrading from 1.7.6,

**Comment by saurabhvyas** [comment]
Thanks for the advice! I always have problems when it comes to updating stuff

**Comment by paulogr** [comment]
I have to run `npm clean cache` before update cli. It worked!
