### ISSUE TITLE
Error when try to run on iOS, brand new project

### ISSUE THREAD

**Issue by joyceview** [ionic-team/ionic-cli#1293]
Hi there,

I just started a new Ionic2 project, and tried to run on iOS. Got error below:

```
Error: ios-deploy was not found. Please download, build and install version 1.8.3 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g iso-deploy'


Caught exception:
 undefined 

```

My node is version 6, not sure is this the reason. 

FYI, Ionic Serve and Ionic emulate iOS both works fine.

Thanks,

**Comment by unostella** [comment]
Got same problem but on I1

**Comment by dwieeb** [comment]
`ios-deploy` and `ios-sim` are packages that must be installed globally to deploy to iOS devices and simulators, respectively.
