### ISSUE TITLE
Ionic start

### ISSUE THREAD

**Issue by mjaravinda** [ionic-team/ionic-cli#1294]
I  updated ionic version 2. when I create a new app, or create a app from tutorials it is showing
**_Error with start Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1061:14)_**

I m working on Wndows pc  and DOS command prompt
![dos](https://cloud.githubusercontent.com/assets/12888400/17828843/85c9ed64-66ba-11e6-86fc-c5647ce1af5e.png)

can you help me on this

**Comment by robertolabarca** [comment]
i have the same problem. How to get file to disk folder ?
