### ISSUE TITLE
Page generator creates incomplete css classname

### ISSUE THREAD

**Issue by moberwasserlechner** [ionic-team/ionic-cli#1302]
**Description**
- Generate Page

```
$ ionic g page sharedCalendarDetail
√ Create app\pages\shared-calendar-detail\shared-calendar-detail.html
√ Create app\pages\shared-calendar-detail\shared-calendar-detail.scss
√ Create app\pages\shared-calendar-detail\shared-calendar-detail.ts

Don't forget to add an import for shared-calendar-detail.scss in app\themes\app.core.scss:

@import "..\pages\shared-calendar-detail\shared-calendar-detail.scss";
```
- Do some styling in `shared-calendar-detail.scss`
- Add the scss to `app.core.scss`
- Try testing with `ionic serve`
- Weird, my styles are not applied to the page, what has happened? Inspecting the html reveals that that the css-class applied to `ion-page` is `shared-calendar-detail-page` instead of `shared-calendar-detail`.
- If I rename the css-class in my scss it works instantly.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v5.12.0
```

BR,
Michael

**Comment by dwieeb** [comment]
@moberwasserlechner Is this still an issue?

**Comment by moberwasserlechner** [comment]
@dwieeb I dont think so. Although I can't verify it any more because I move to pure Angular some time ago. But I'm closing it.
