### ISSUE TITLE
Ionic CLI adds iOS back in after I've removed it

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic-cli#1320]
I made a new project and it added iOS automatically. I added Browser, removed iOS. Now when I `ionic build`, I get this message:

• You're trying to build for ios but don't have the platform installed yet.

And iOS is added back in. Why is it coming back?

**Comment by cfjedimaster** [comment]
Note - this is in a v2 app.

**Comment by cfjedimaster** [comment]
Also - if I remove the Splashscreen plugin, and run the browser platform again, Ionic adds it back in.

**Comment by cfjedimaster** [comment]
It looks like package.json is not being updated when I remove plugins/platforms. Should it be?

**Comment by cfjedimaster** [comment]
Heck, it isn't even being updated when I add browser.

**Comment by dwieeb** [comment]
I'm quite sure this is a Cordova issue that is likely fixed by now. Let me know if I'm mistaken.
