### ISSUE TITLE
ionic package problem Authentication credentials

### ISSUE THREAD

**Issue by fx69005** [ionic-team/ionic-cli#1323]
Hi , Since one week i have this problem when i use command :  ionic package on windows 10:

Body: {"detail":"Authentication credentials were not provided."}
Error in package service. (CLI v2.0.0)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.0
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:
Node Version: v4.4.1

Someone can help me please ? thanks

**Comment by nfallon** [comment]
I had the same issue and resolved it as follows -from the Ionic CLI, type:

ionic login

You'll be prompted to login again (supply email/pwd). The package command should then work.

**Comment by ntziolis** [comment]
I think this happens the first time after upgrading to plus. Re-login solved it to me too.

**Comment by dwieeb** [comment]
@ntziolis If you're referring to Ionic Pro, yes, you will need to login again. The CLI should prompt for credentials if they're missing, though. Let me know if there's a sequence of commands which result in an ugly server error instead of a pretty login prompt.

**Comment by ntziolis** [comment]
No. I'm talking about having a free app in Ionic Cloud and then upgrading to "Ionic Cloud Plus" at 20$/app (still only thing you can buy as Ionic Pro is not yet available to purchase).

**When you have been logged in prior to your purchase you HAVE to log out and re-login MANUALLY to make the CLI understand that you are now on a Plus plan with access to package etc.**

To be clear:
The CLI did not prompt as I was already logged in. And there was no notification of any kind that I need to relogin. Hence this comment to make sure that others don't fall into this trap.

General comment:
Bad CLI design if it either caches things that are account related or it uses a different API while on non Plus plan that need to be switched through re-login.
No matter what causes this this, it should be dealt with server side not client side.

**Comment by dwieeb** [comment]
@ntziolis Okay, thanks for clearing that up. This is likely a result of our old authentication tokens for Cloud. We've change them for Pro and this won't be an issue for users of Pro.
