### ISSUE TITLE
ionic upload fails with differing project structure

### ISSUE THREAD

**Issue by gruppjo** [ionic-team/ionic-cli#1332]
@dwieeb, @jthoms1. I hope it's alright if I directly mention you in this issue. 

I'm currently trying to make integration of `ionic-cloud` work with [Generator-M-Ionic](https://github.com/mwaylabs/generator-m-ionic) projects and update our [ionic integration guide](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/ecosystems/ionic_platform.md). Integration seemed fairly easy apart `ionic-cloud` not being available through bower. For which I created an issue: https://github.com/driftyco/ionic-cloud/issues/43. However I need `ionic upload` to work with our project structure. In recent versions of the Ionic CLI `ionic upload` was satisfied as long as the following criteria were met:
- an uploadable app in `www/`, mainly an existing `index.html` seemed important
- presence and proper configuration of `ionic.config.json` and `.io-config.json` 

Unfortunately this no longer works with `v2.0.0`. I get the following error when running `ionic upload`:

```
$ ionic upload
Uploading app....
Saved app_id, writing to ionic.io.bundle.min.js...

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/jonathan/Projects/play/test2/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/jonathan/Projects/play/test2/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/jonathan/Projects/play/test2/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as info] (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
    at Request._callback (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:150:11) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

One of our users had this issue before but I failed to track it down https://github.com/mwaylabs/generator-m-ionic/issues/409.

With version `v2.0.0` I can reliably reproduce this issue now and was able to track down the error to the following two lines of code in the Ionic CLI: https://github.com/driftyco/ionic-app-lib/blob/master/lib/upload.js#L150-L151 Apparently `log` is undefined at this point. Not sure why. By commenting those lines, I got `ionic upload` to work.

In my discussion with @tlancina in march (https://github.com/driftyco/ionic-cli/issues/845) I think he mentioned that other project structures should technically be supported. So my question is: am I doing something wrong? How can I get around this to allow our users to reliably upload to ionic?

**Comment by gruppjo** [comment]
I created a repo especially for this case that you can use to reproduce this issue.
It contains a valid `ionic.config.json` and `.io-config.json`

**Setup**
```
git clone https://github.com/mwaylabs/generator-m-ionic-demo/tree/ionic-cloud
cd generator-m-ionic-demo
npm i && bower i
```

Then you should replace the `app_id` with a valid one of your account in both config files. Then run:

```
gulp watch # to see if everything is working
gulp build   # build into www/ folder
ionic upload # with version 2.0.0
```
You then should get the same error as above.

Uncomment these lines in your installation of `ionic-cli` and it will work:  https://github.com/driftyco/ionic-app-lib/blob/master/lib/upload.js#L150-L151

Open Ionic View and tada!

**Comment by jaworskm** [comment]
I have the exact same issue. +1

**Comment by gruppjo** [comment]
@jaworskm, oh! It never occurred to me to check. Thanks!

**Comment by coderroggie** [comment]
This looks similar to the issue found here: https://github.com/driftyco/ionic-cli/issues/984.  I'm guessing commenting out line 150 in '''/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js''' would fix the issue, similar to how the fix described in the other issue fixes it.  Pretty sure that is a hack though.

**Comment by sdemurjian** [comment]
since the issue is closed has this been fixed? this is essentially the same issue with `bold` in #1038 and prevents me from uploading to the ionic cloud with `ionic upload`.

**Comment by gruppjo** [comment]
@sdemurjian it's not closed.

**Comment by sdemurjian** [comment]
@gruppjo Oops, sorry. I think I mixed up this issue with the other one -- Editing my comment to reflect this

**Comment by gruppjo** [comment]
I find it confusing some times as well, when linked issues are closed ;)

**Comment by coderroggie** [comment]
Still having this issue after upgrading to version 2.1.0 of the CLI.

**Comment by coderroggie** [comment]
Upgrading the ionic-cli to version 2.1.6 fixed the issue for me.  I believe the commit that fixed it was https://github.com/driftyco/ionic-cli/pull/1605

**Comment by Sogapp** [comment]
I've got this issue with the version 2.1.4 of the CLI
With 2.1.8 version it's OK
