### ISSUE TITLE
Paths in config.xml are written with backslashes, causing problems on OS X

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1342]
_From @Z3roCoder on September 6, 2016 11:27_
#### Short description of the problem:

We develop on a Windows Machine
Everytime we use ionic resources and ionic prepare, the config.xml is changed to paths like "resources\android\splash\" and "resources\android\splash\"
While this is no problem on a Windows-Machine, it gives us regularly problems building on OS X

remotebuild on OS X tells us evrey time that the resources can not be found
#### What behavior are you expecting?

Paths should contain fowardslashes and no backslashes.
<icon src="resources/android/icon/drawable-mdpi-icon.png" density="mdpi"/>
instead of 
<icon src="resources\android\icon\drawable-mdpi-icon.png" density="mdpi"/>

**Steps to reproduce:**
1. call ionic resources
2. call ionic prepare
3. build the app on OS X

**Which Ionic Version?** 1.x or 2.x
"ionic -v" -> 2.0.0
But Ionic 1 is used in the project

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: (Windows 10, apparently not detected correctly)
Node Version: v6.3.1

_Copied from original issue: driftyco/ionic#7990_

**Comment by Z3roCoder** [comment]
There seems to have been a problem with me pasting some XML in here.
It should correctly be:

#### What behavior are you expecting?

Paths should contain fowardslashes and no backslashes.
"resources/android/splash/" 
instead of 
"resources\android\splash\"

**Comment by Sroose** [comment]
Issue is still present with latest version.

**Comment by dwieeb** [comment]
I think I may have introduced a bunch, @Sroose. I fixed it and will release a new version of the Cordova plugin soon.
