### ISSUE TITLE
[Bug][Crit] Remove '.bold' or '.bold()' method from cli utils

### ISSUE THREAD

**Issue by luchillo17** [ionic-team/ionic-cli#1344]
Related to this post comment https://github.com/driftyco/ionic-cli/issues/1038#issuecomment-234997779 the `.bold()` method doesn't work in terminals as the cli expects, this generates an error of type `TypeError: Can't call method on undefined`, that itself blocks the user to see the original error, many of us have had to get into the lib itself and remove that part of the code just to see the original error, and that repeats each time we update the `ionic-cli`.

The line in question is in `/lib/node_modules/ionic/lib/utils/cordova.js:83` in other peoples pc, in my case is in `/usr/local/lib/node_modules/ionic/lib/utils/cordova.js:83` which means is in the `ionic-cli` cordova utils, line 83.

This should be fixed now, for starters not all ionic devs are good enough to go edit this file in `node_modules`, most of them will never know or care about that particular problem, and as such will never know what's their real bug, and the ones like me that do know this issue exists is a nuisance to do this deletion each time we update the `ionic-cli` library.

**Comment by ahmed-abdulmoniem** [comment]
Any permanent fix to this?

**Comment by dwieeb** [comment]
Should be resolved in the latest version of the CLI, which now uses chalk.
