### ISSUE TITLE
Ionic CLI commands a lot slower than Cordova

### ISSUE THREAD

**Issue by MisterDev** [ionic-team/ionic-cli#1348]
I'm using `ionic 2.0.0-beta.37`, `cordova 6.2.0` and `node 6.2.0` and these are the results using `time` on `OSX 10.11.4`

`cordova platform list`       |   `ionic platform list`

```
real  0m19.449s       |    real   1m16.809s
user  0m0.890s        |    user   0m2.711s
sys   0m0.166s        |    sys    0m0.685s
```

`cordova plugin list`     |   `ionic plugin list`

```
real  0m0.587s        |    real   0m41.768s
user  0m0.503s        |    user   0m2.362s
sys   0m0.055s        |    sys    0m0.891s
```

Why my Ionic CLI is so much slower?

**Comment by dwieeb** [comment]
The latest CLI is much faster. Let me know if it's still unacceptable.
