### ISSUE TITLE
File naming conventions of ionic 2 to follow angular 2 style guide

### ISSUE THREAD

**Issue by vijquick** [ionic-team/ionic-cli#1350]
All the files generated using **ionic-cli** for **ionic 2** app has it's own **file name conventions** which is slightly different to [angular 2 style guide](https://angular.io/docs/ts/latest/guide/style-guide.html#!#naming). Even though the current conventions doesn't have any flaw can this be aligned more to angular 2 style guides?

**Comment by leonardobazico** [comment]
Structure of directories and encourage use of modules would be good too

**Comment by neo-split** [comment]
I dont see any apparent reason for deviation from the file naming conventions so why not stick to the guidelines and reduce headache of developers?

**Comment by glebmachine** [comment]
@mlynch

**Comment by dwieeb** [comment]
The next version of Ionic Framework for Angular will have a project structure almost identical to an app created with `ng new`. 

Closing this as it will come by default with Ionic Angular v4.

**Comment by glebmachine** [comment]
@dwieeb sound great, thank you!

Could you please share estimate release date?
I prefer to wait for ionic, than use phonegap(
