### ISSUE TITLE
Error: npm install -g ios-deploy

### ISSUE THREAD

**Issue by Aditya-app-dev** [ionic-team/ionic-cli#1363]
Hello,

I am not able to install ios-deploy in OSX. Below is the error:

```
npm WARN lifecycle ios-deploy@1.8.6~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.8.6 ./src/scripts/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AdityaBatra/Documents/xcode/sidemenuapp/npm-debug.log
```

Attached npm-deploy.log file

[npm-deploy.txt](https://github.com/driftyco/ionic-cli/files/469687/npm-deploy.txt)

**Comment by gekonwi** [comment]
same here

**Comment by gekonwi** [comment]
overcame the error by running the following on OS X 10.11.6:
```
npm install -g ios-deploy --unsafe-perm=true
```

**Comment by tomibady** [comment]
I had the same issue too, @gekonwi's solution worked for me.

**Comment by rickykennedy** [comment]
I have this issue as well. My OSX is macOS Sierra which is 10.12.2 but apparently during the installation, it is recognized as El Capitan 10.11, the warning message shown below. 
`!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!! WARNING: You are on OS X 10.11 El Capitan, you may need to add the
!!!! WARNING:   '--unsafe-perm=true' flag when running 'npm install'
!!!! WARNING:   or else it will fail.
!!!! WARNING: link:
!!!! WARNING:   https://github.com/phonegap/ios-deploy#os-x-1011-el-capitan`

Adding --unsafe-perm=true does solve the problem for me but I am not sure if it is the correct things to do.

**Comment by felipeladislau** [comment]
Run @gekonwi solution on OS 10.11, works just fine :D

**Comment by raydelto** [comment]
Thanks @gekonwi `sudo npm install -g ios-deploy --unsafe-perm=true`  worked for me too.

**Comment by qiluo** [comment]
My build script is `ionic cordova build ios --prod --release --buildConfig ./build.config`, it worked before ionic cli 3.0beta, but now failed with same error. I haven't used `--debug` option, weird, theoretically `ios-deploy` is not required since it's only a build, not deploy.

**Comment by MrAshTag** [comment]
Thanks @gekonwi, this problem took my sleep, until I tried your solution

**Comment by Rasfuranku** [comment]
Thanks @gekonwi

**Comment by vamshipoornima** [comment]
Thanks @gekonwi sudo npm install -g ios-deploy --unsafe-perm=true this worked for me  on MAC OS 10.12.6.

**Comment by feiandytan** [comment]
I had the same error. Thanks to @gekonwi . --unsafe-perm=true works for me.

**Comment by nitish75** [comment]
@gekonwi worked for me,
saved my day,
thanks
