### ISSUE TITLE
ionic-angular package not found

### ISSUE THREAD

**Issue by KawtharE** [ionic-team/ionic-cli#1370]
I have started a new blank ionic project using the command _ ionic start MyApp blank --v2 --ts_ and to add a new page, i used the command _ionic generate page Login_ i installed all the necessary packages but it keep show this error and i can't add my Login page:

No ionic-angular package found, do you have Ionic installed? (CLI v2.0.0-beta.37)

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID: Ubuntu Description: Ubuntu 14.04.5 LTS 
Node Version: v0.10.25

Help please, i really appreciate that :)

**Comment by jwhubert91** [comment]
Any responses on this? I'm having the same problem right now, it's very frustrating. Especially considering it literally worked yesterday.

**Comment by KawtharE** [comment]
Hi, i have managed that error by doing that, you can do the same:
First, i have removed ionic and cordova using this command line:
$sudo npm uninstall -g cordova
$sudo npm uninstall -g ionic
$sudo npm cache clean

Then, re-installed:
$sudo npm install -g cordova
$sudo npm install -g ionic@beta
$sudo npm install -g n
$sudo  n stable 
the two previous command will install the last stable version of node, for now it is node v6.6.0 on ubuntu.
$sudo npm install -g typescript
$sudo npm install -g typeings

So the problem it is all about the version of node, this solution worked well for me, but i would like to advice you to try just the two mentioned commands to install a stable version of the node if it works for you then no need to remove ionic and reinstalled it.

Good luck :)

**Comment by amsubway** [comment]
@KawtharE 
sudo npm install -g typings

**Comment by KawtharE** [comment]
:) sorry that was my mistake, thank you :)

**Comment by ah3243** [comment]
great post, worked like a charm

**Comment by KawtharE** [comment]
Happy to hear that :) good luck

**Comment by hsuDev** [comment]
same problem occurs
tried your way but shows sudo is not recognised
