### ISSUE TITLE
What to Replace "ionic lib update"?

### ISSUE THREAD

**Issue by johnmiroki** [ionic-team/ionic-cli#1380]
I am using the latest Ionic Cli (installed yesterday). When trying to update the lib of an existing project (the official starter to be exact) to the brand new angular 2 release version, I got this: 

```
This command has been deprecate.  All resources are currently available in NPM and we recommend that you use NPM to manage these.
More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower

Unable to load ionic lib version information

Are you sure you want to replace C:\playground\MyIonic2Project\www\lib\ionic with an updated version of Ionic?
(yes/no): yes
Invalid version: undefined
```

Following the link above(https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower) didn't help since it's practically a blank page.

Any idea would be appreciated!

**Comment by johnmiroki** [comment]
I am using the latest Ionic Cli (installed yesterday). When trying to update the lib of an existing project (the official starter to be exact) to the brand new angular 2 release version, I got this: 

```
This command has been deprecate.  All resources are currently available in NPM and we recommend that you use NPM to manage these.
More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower

Unable to load ionic lib version information

Are you sure you want to replace C:\playground\MyIonic2Project\www\lib\ionic with an updated version of Ionic?
(yes/no): yes
Invalid version: undefined
```
Following the link above(https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower) didn't help since it's practically a blank page.

Any idea would be appreciated!

**Comment by brace110** [comment]
+1

**Comment by polonel** [comment]
So as right now we are stuck in limbo. Its either old version of lib or manually migrate the entire deps?

**Comment by brace110** [comment]
I just downloaded the latest framework version from the ionic website and pasted it over the old one. It works but it might be risky.

**Comment by katche70** [comment]
still not solved?

**Comment by wxmerkt** [comment]
Any update on how to get this correctly migrated? Or how to continue to support an Ionic1 project with newer versions of Cordova and the Ionic-CLI?

**Comment by rgecy** [comment]
This totally screwed up my app! I updated the CLI and Cordova and now I am having nothing but issues! Tried updating the project lib and got the same message as OP.

**Comment by anuradhawick** [comment]
Is this some thing necessary to do. Because I started the project when angular 2 and ionic 2 was in beta. Anyway the update command lead to the "Invalid version: undefined" error.

**Comment by prantikv** [comment]
👍

**Comment by betollaque** [comment]
I'm using cli 2.2.1, same issue I can't run ionic lib update, there is not ..\www\lib\ionic\bower.json

**Comment by johannds** [comment]
Any news on this?

**Comment by dwieeb** [comment]
Use bower to update Ionic 1 lib.
