### ISSUE TITLE
Unexpected end of JSON input and MISSING_SOURCE_FILE (CLI v2.0.0)

### ISSUE THREAD

**Issue by daviddexter** [ionic-team/ionic-cli#1393]
I get this error when in run the build command

**The resources folder already exists. We will not overwrite your files unless you pass the --force argument.
Running with the force flag will overwrite your resources directory and modify your config.xml file
Preparing your resources...
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/io-config.js:169:24
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:445:3) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

icon source file not found in any of these directories: resources, resources/android, resources/ios, resources/wp8
valid icon source files: icon.psd, icon.ai, icon.png
splash source file not found in any of these directories: resources, resources/android, resources/ios, resources/wp8
valid splash source files: splash.psd, splash.ai, splash.png

MISSING_SOURCE_FILE (CLI v2.0.0)**

I however have my icon.png in the resource folder. I don't understand the error that has to do with JSON input.

How can i resolve them?

**Comment by MEmmanuel** [comment]
Exact same issue, with CLI v2.1.0
`ionic package build ios --profile dev` is looking in wp8 folder...

**Comment by MEmmanuel** [comment]
I have a track:
`ionic package build ios --profile dev` makes the file.io-config.json empty.
And that causes SyntaxError: Unexpected end of JSON input
I put back this in the file: `{"app_id":"...","api_key":"..."}`
For the resources, I ran it myself `ionic resources` and then build with `ionic package build android --profile dev --noresources`

And I finally successfully built it. Let's try now...

**Comment by dwieeb** [comment]
Closed as this is the legacy CLI. If this is still an issue with the latest version, please make a new issue.
