### ISSUE TITLE
Cordova Ionic - Error when starting new blank project - Error: settings not defined

### ISSUE THREAD

**Issue by jeremysmartin399** [ionic-team/ionic-cli#1395]
In Windows 7, in the CLI, when I start a new ionic blank project, I receive an error when it tries to add initial native plugins. I think it is the "Error: settings not defined" problem. I've updated cordova and ionic several times. 

E:\Projects\Sandbox\ionic-mapsPart1v2>ionic start map blank --log
Creating Ionic app in folder E:\Projects\Sandbox\ionic-mapsPart1v2\map based on
blank project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...

Adding initial native plugins
[=============================]  100%  0.0s
{ [Error: Command failed: C:\windows\system32\cmd.exe /s /c "cordova plugin add
--save cordova-plugin-device && cordova plugin add --save cordova-plugin-console
 && cordova plugin add --save cordova-plugin-whitelist && cordova plugin add --s
ave cordova-plugin-splashscreen && cordova plugin add --save cordova-plugin-stat
usbar && cordova plugin add --save ionic-plugin-keyboard"
Error: settings is not defined
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\windows\system32\cmd.exe /s /c "cordova plugin add --save cordova-
plugin-device && cordova plugin add --save cordova-plugin-console && cordova plu
gin add --save cordova-plugin-whitelist && cordova plugin add --save cordova-plu
gin-splashscreen && cordova plugin add --save cordova-plugin-statusbar && cordov
a plugin add --save ionic-plugin-keyboard"' } 'Error: settings is not defined\r\
n'

Unable to add plugins. Perhaps your version of Cordova is too old. Try updating
(npm install -g cordova), removing this project folder, and trying again: (CLI v
2.0.0)

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Windows 7 SP1
Node Version: v4.5.0

**Comment by jeremysmartin399** [comment]
I completely uninstalled cordova and ionic, then reinstalled both, then updated minimatch.

npm uninstall -g cordova
npm uninstall -g ionic
npm install -g cordova
npm install -g ionic

Then [update minimatch to fix the warning about outdated minimatch]([url](https://github.com/npm/npm/issues/13323)): 
npm install -g minimatch@3.0.2

After this, I was able to create Ionic projects.

**Comment by mika-lsv** [comment]
Thanks jeremysmartin399!
It works for me.
