### ISSUE TITLE
ionic cli upload

### ISSUE THREAD

**Issue by wouafff** [ionic-team/ionic-cli#1396]
Hi,
submitting the request : ionic upload --note "test",
I do have the following logs in the terminal : 

Uploading app....
Caught exception:
 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/Cellar/node/0.12.5/libexec/npm/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/io-config.js:169:24
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Successfully uploaded (0e490b5d)

Share your beautiful app with someone:

$ ionic share EMAIL

Caught exception:
 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/Cellar/node/0.12.5/libexec/npm/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/io-config.js:169:24
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

It doesn't affect the fact that the app is upload correctly

**Comment by wouafff** [comment]
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.1.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by pedrohills** [comment]
Same here...
![image](https://cloud.githubusercontent.com/assets/8502303/19223140/7c1639f2-8e3e-11e6-83bf-84e792f7a54f.png)

**Comment by anujmpec** [comment]
same here

**Comment by dwieeb** [comment]
@anujmpec If you're getting this error it means you're on a very old version of the CLI. Please upgrade to the latest 3.x CLI.
