### ISSUE TITLE
after trying to update ionic  lodash/assign not found

### ISSUE THREAD

**Issue by pdemilly** [ionic-team/ionic-cli#1402]
$ ionic 
Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:5:12)
    at Object.<anonymous> (/usr/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by pdemilly** [comment]
Thanks but you can close this. Problem was probably a lower version of
lodash which I needed for another app. Wish that ionic-cli could just be a
self contained app. There are too many apps requiring too many different
version of node packages. Wonder if something like nar (
https://github.com/h2non/nar) could help

**Comment by msegers** [comment]
Which version of Lodash should you be using? Some sub modules are complaining for me. And I still have this issue after getting the latest

**Comment by eboukamza** [comment]
I have solved the problem just re-installing the package

`npm remove -g ionic`
`npm install -g ionic`

**Comment by glanzkinderbuild** [comment]
Can't fix this problem by reinstalling. Cannot provide `ionic info` because every `ionic` command fails:

```
$ ionic info
Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:5:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

```
$ node -v
v7.3.0
```

```
$ npm -v
3.9.6
```

My depencies: 
```
"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.6",
    "@types/ng-cordova": "0.0.11",
    "async": "^2.1.4",
    "color": "^1.0.3",
    "crypto-js": "^3.1.6",
    "ionic-angular": "2.0.0-rc.4",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "leveldown": "^1.5.3",
    "lodash": "^4.15.0",
    "ng2-pdf-viewer": "^0.1.5",
    "ng2-translate": "^4.2.0",
    "pouchdb": "^6.1.0",
    "rxjs": "5.0.0-beta.12",
    "store.pouchdb": "git+https://github.com/heikoholland/store.pouchdb.git",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.47",
    "typescript": "2.0.9"
  },
```

```
$ npm ls -g -depth=0
~/.nvm/versions/node/v7.3.0/lib
+-- abbrev@1.0.9
+-- aproba@1.0.4
+-- asap@2.0.5
+-- config-chain@1.1.11
+-- cordova@6.4.0
+-- fstream@1.0.10
+-- fstream-npm@1.2.0
+-- glob@7.1.0
+-- graceful-fs@4.1.9
+-- has-unicode@2.0.1
+-- inherits@2.0.3
+-- ionic@2.1.18
+-- lockfile@1.0.2
+-- lodash.clonedeep@4.5.0
+-- lodash.union@4.6.0
+-- lodash.uniq@4.5.0
+-- lodash.without@4.4.0
+-- minimatch@3.0.3
+-- node-gyp@3.4.0
+-- npm@3.10.10
+-- npm-package-arg@4.2.0
+-- npm-registry-client@7.2.1
+-- npm-user-validate@0.1.5
+-- npmlog@4.0.0
+-- once@1.4.0
+-- opener@1.4.2
+-- path-is-inside@1.0.2
+-- read-package-tree@5.1.5
+-- readable-stream@2.1.5
+-- request@2.75.0
+-- retry@0.10.0
+-- rimraf@2.5.4
+-- semver@5.3.0
+-- sorted-object@2.0.1
+-- which@1.2.11
+-- wrappy@1.0.2
`-- write-file-atomic@1.2.0
```

**Comment by glanzkinderbuild** [comment]
Alright. I fixed it. I messed up my environment with an old installation of node not using nvm. After removing all node modules in `/usr/local/lib/node_modules/` and only using the node version of my nvm installed node versions everything is good again.
