### ISSUE TITLE
bug(resources): path issues on mac

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic-cli#1408]
On a mac I ran `ionic resources`. It added a whole bunch of icons and splash entries into my config. 

An example:

```
<icon src="resources\android\icon\drawable-ldpi-icon.png" density="ldpi"/>
```

When running `ionic platform add android` or `ionic run android` on the Mac I got an error:

```
Error: Source path does not exist: resources\android\icon\drawable-hdpi-icon.png
```

I am assuming this is because the path is not valid on a mac? It worked fine on my colleagues machine running Windows. So now I have had to fix the paths manually for all Android entries so that I can run an app on my machine. 

Is there no code somewhere that checks what OS is being run and adjusts the paths respectively when running commands like `ionic run android`?

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by dylanvdmerwe** [comment]
So tired of receiving this error!!
`Error: Source path does not exist: resources\android\icon\drawable-hdpi-icon.png`

A colleague generated resources on a Windows machine, to which this was added into the config file:
`<icon src="resources\android\icon\drawable-xhdpi-icon.png" />`

This file does exist but the `ionic run android` build process does not seem to think so on my Mac!!
![image](https://cloud.githubusercontent.com/assets/2852839/19576632/f30fc234-9713-11e6-90a8-aa2f8b6ab948.png)

**Comment by finalxcode** [comment]
+1

**Comment by rnarian** [comment]
👍 

Same issue here.

**Comment by Donnici** [comment]
try
`ionic resources`

**Comment by dwieeb** [comment]
This is fixed in latest CLI!
