### ISSUE TITLE
When adding Crosswalk, ionic build failed

### ISSUE THREAD

**Issue by xlkit456852** [ionic-team/ionic-cli#1410]
ionic version:2.0.0
cordova version:6.3.1

I used "ionic/cordova plugin add cordova-plugin-crosswalk-webview" to add the plugin.

I have tried #1390 this method to remove all the generated apks from the platforms/android/build/outputs/apk ,but it still show me this :

BUILD FAILED

Total time: 18.757 secs

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'android'.
  
  > Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
  > Could not find any matches for com.android.support:support-v4:[13.0.0,) as no versions of com.android.support:support-v4 are available.
  >  Searched in the following locations:
  >      https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
  >      https://repo1.maven.org/maven2/com/android/support/support-v4/
  >      https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml
  >      https://jcenter.bintray.com/com/android/support/support-v4/
  >      https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/maven-metadata.xml
  >      https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/
  >  Required by:
  >      :android:unspecified > org.xwalk:xwalk_core_library:21.51.546.6
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'android'.
  
  > Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
  > Could not find any matches for com.android.support:support-v4:[13.0.0,) as no versions of com.android.support:support-v4 are available.
  >  Searched in the following locations:
  >      https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
  >      https://repo1.maven.org/maven2/com/android/support/support-v4/
  >      https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml
  >      https://jcenter.bintray.com/com/android/support/support-v4/
  >      https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/maven-metadata.xml
  >      https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/
  >  Required by:
  >      :android:unspecified > org.xwalk:xwalk_core_library:21.51.546.6
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by estyles** [comment]
Try installing, 'android support repository' using the android SDK manager 
it's listed under extras
that fixed it for me.

**Comment by dwieeb** [comment]
Crosswalk is no longer maintained. Please do not use it.
