### ISSUE TITLE
error starting app error initializing app

### ISSUE THREAD

**Issue by fatimaasamee** [ionic-team/ionic-cli#1412]
I get this error when I try to start new project in ionic 
`Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error with start Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
Error Initializing app: Error: connect ETIMEDOUT 192.30.253.113:443
 Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
Caught exception:
 Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)`

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting. Also could you verify that you are able to visit this URL from within your web browser?

**Comment by fatmaasamee** [comment]
Thanks for your comment this is when I run ionic info
I could not visit URL from my browser .
`$ ionic info
Your system information:
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 8
Node Version: v4.4.7
`

**Comment by jthoms1** [comment]
Are you working behind a firewall? If you are unable to access the following zip file from github is it possible you could just clone the repo into a new directory? The following commands should allow you to get started.

```
git clone https://github.com/driftyco/ionic-app-base.git newapp
cd newapp
npm install
```

**Comment by fatmaasamee** [comment]
I run the commands
 `git clone https://github.com/driftyco/ionic-app-base.git newapp
cd newapp
npm install`
 and the project cloned successfully but when I run ionic serve I got this message
`Couldn't find ionic.config.json file. Are you in an Ionic project?
 ` I don't know how to start ionic project from it or do I need to add any configuration
 I'm sorry if my question looks stupid but I'm new to ionic 
Thanks

**Comment by sandeep540** [comment]
@fatmaasamee , the moment you run 
**git clone https://github.com/driftyco/ionic-app-base.git newapp** 
it creates a folder "**newapp**" and gets all the content
then **cd newapp**
then **npm install**
