### ISSUE TITLE
When i was updating Ionic lib

### ISSUE THREAD

**Issue by dlillard78** [ionic-team/ionic-cli#1423]
npm WARN In ionic@2.1.0 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.1.0 replacing bundled version of ionic-app-lib with ionic-app-lib@2.1.0-beta.1
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Wolf\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\Wolf\AppData\Roaming\npm\node_modules.staging\ansi-28486b2b
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Wolf\AppData\Roaming\npm\node_modules.staging\ansi-28486b2b' -> 'C:\Users\Wolf\AppData\Roaming\npm\node_modules\ionic\node_modules\cordova-lib\node_modules\ansi'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Wolf\AppData\Roaming\npm\node_modules.staging\ansi-28486b2b' -> 'C:\Users\Wolf\AppData\Roaming\npm\node_modules\ionic\node_modules\cordova-lib\node_modules\ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Wolf\myplayertraining\npm-debug.log
npm ERR! code 1

C:\Users\Wolf\myplayertraining>ionic lib update
Caught exception:
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Wolf\AppData\Roaming\npm\node_modules\ionic\node_modules\glob\glob.js:42:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by dlillard78** [comment]
86043 silly gunzTarPerm extractEntry node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-installed/node_modules/util-extend/test.js
86044 silly gunzTarPerm modified mode [ 'node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-installed/node_modules/util-extend/test.js',
86044 silly gunzTarPerm   420,
86044 silly gunzTarPerm   438 ]
86045 silly gunzTarPerm extractEntry node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/package.json
86046 silly gunzTarPerm modified mode [ 'node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/package.json',
86046 silly gunzTarPerm   420,
86046 silly gunzTarPerm   438 ]
86047 silly gunzTarPerm extractEntry node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/.npmignore
86048 silly gunzTarPerm modified mode [ 'node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/.npmignore',
86048 silly gunzTarPerm   420,
86048 silly gunzTarPerm   438 ]
86049 silly gunzTarPerm extractEntry node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/README.md
86050 silly gunzTarPerm modified mode [ 'node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/README.md',
86050 silly gunzTarPerm   420,
86050 silly gunzTarPerm   438 ]
86051 silly gunzTarPerm extractEntry node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/LICENSE
86052 silly gunzTarPerm modified mode [ 'node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/LICENSE',
86052 silly gunzTarPerm   420,
86052 silly gunzTarPerm   438 ]
86053 silly gunzTarPerm extractEntry node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/read-json.js
86054 silly gunzTarPerm modified mode [ 'node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/read-json.js',
86054 silly gunzTarPerm   420,
86054 silly gunzTarPerm   438 ]
86055 silly gunzTarPerm extractEntry node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/.travis.yml
86056 silly gunzTarPerm modified mode [ 'node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/.travis.yml',
86056 silly gunzTarPerm   420,
86056 silly gunzTarPerm   438 ]
86057 silly gunzTarPerm extractEntry node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/test/basic.js
86058 silly gunzTarPerm modified mode [ 'node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/test/basic.js',
86058 silly gunzTarPerm   420,
86058 silly gunzTarPerm   438 ]
86059 silly gunzTarPerm extractEntry node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/test/bin.js
86060 silly gunzTarPerm modified mode [ 'node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/read-package-json/test/bin.js',

**Comment by dlillard78** [comment]
I tried to do the install unistall, and everything else, I cant lose this project its due today..

**Comment by dlillard78** [comment]
So Am I just screwed is there no answer to this I have tried everything

**Comment by jthoms1** [comment]
Can you provide me with the commands you execute when you tried to uninstall/reinstall?

Thanks!

**Comment by shuhanxu** [comment]
try ionic remove -g ionic
ionic remove -g ionic@beta
npm cache clean
ionic install -g ionic

**Comment by jthoms1** [comment]
@dlillard78 Where you able to get this working or are you still having problems?

Thanks!
