### ISSUE TITLE
Error on latest version installation

### ISSUE THREAD

**Issue by bazigatabassum** [ionic-team/ionic-cli#1427]
npm install -g ionic@2.1.0-beta.3

npm WARN deprecated lodash@2.1.0: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\DELL\AppData\Roaming\npm
`-- (empty)

npm WARN In ionic@2.1.0-beta.3 replacing bundled version of semver with semver@4
.2.0
npm WARN In ionic@2.1.0-beta.3 replacing bundled version of ionic-app-lib with i
onic-app-lib@2.1.0-beta.1
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic@2.1.0-beta.3"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\DELL\AppData\Roaming\npm\node_modules.staging\
ansi-0e9facce
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\DELL
\AppData\Roaming\npm\node_modules.staging\ansi-0e9facce' -> 'C:\Users\DELL\AppData\Roaming\npm\node_modules\ionic\node_modules\cordova-lib\node_mod
ules\ansi'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\DELL\AppData\Roaming\npm\node_modules.staging\ansi-0e9facce' -> 'C:\Users\DELL\AppData\Roaming\npm\node_modules\ionic\node_modules\cordova-lib\node_mod
ules\ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DELL\npm-debug.log
npm ERR! code 1

latest version gives the above error...
kindly suggest the stable version...

**Comment by mnasyrov** [comment]
Following helps me: updated npm to the latest version, deleted node_modules and install everything from the scratch.

**Comment by jthoms1** [comment]
@bazigatabassum could you try the following to get the latest.

```
npm uninstall -g ionic
npm install -g ionic@2.1.0
```

Let me know if this works for you. Thanks!
