### ISSUE TITLE
ionic serve no longer working after rc update

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1435]
_From @fuggfuggfugg on September 29, 2016 20:32_
#### Short description of the problem:

Trying to run `ionic serve` on an older project (v2 beta) isn't updating the build folder. 
#### What behavior are you expecting?

I tried updating a label on the login page and run `ionic serve` and it still shows the old login page. If I empty the contents of www/build folder and try again. I get the white screen of death.

**Steps to reproduce:**
1. Update ionic and npm 
2. Use an older project 
3. ionic serve

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?** 1.x or 2.x
2.1.0

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v0.12.0
Xcode version: Xcode 8.0 Build version 8A218a

_Copied from original issue: driftyco/ionic#8321_

**Comment by fuggfuggfugg** [comment]
Update: I uninstalled npm and node. Reinstalled using nvm. 

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by fuggfuggfugg** [comment]
Reverted to `npm install -g ionic@2.1.0-beta.1` and it is working currently.

**Comment by fuggfuggfugg** [comment]
My apologies, I completely missed the [upgrade notes.](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0) I'll update soon.

**Comment by jthoms1** [comment]
Let me know if the problem is resolved once you do so. Thanks!

**Comment by ramonornela** [comment]
@jthoms1 

Lots bugs related the version of the ionic-app-lib
```
ionic info
Ionic App Lib Version: 2.0.0-beta.20
```

Thanks
