### ISSUE TITLE
`ionic emulate ios --livereload` gets stuck on loading the app

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/ionic-cli#1436]
![screen shot 2016-09-29 at 22 19 32](https://cloud.githubusercontent.com/assets/1189149/18974513/06f0b664-8693-11e6-8d78-b314e143cde3.png)
**Steps to reproduce:**
1. `ionic start demo blank --v2`
2. `ionic emulate ios --livereload`
Note: Just `ionic emulate ios` (without the `--livereload`) works fine

My Ionic info:

```
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan (Wrong info by the cli, it's macOS Sierra)
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by pjorquera** [comment]
Add the following to your `config.xml`:

```
<allow-intent href="*"/>
<allow-navigation href="*"/>
```

**Comment by nunoarruda** [comment]
Thanks @pjorquera, I know that workaround and while it fixes the app loading it also makes external URLs open in the app's web-view which is undesirable. Also the livereload doesn't work.

**Comment by pjorquera** [comment]
You can have livereload working again if you start (in another shell) the following command in your ionic2 app folder:

`npm run watch`

Probably, buy I'm not sure, this is a bug in ionic2 after they moved away from gulp to @ionic/app-scripts. Until they fix that you can use that command as a workaround.

If you want to disable loading *any* external URL inside the WebView you can enable only navigation from your local network IP:

```
<allow-navigation href="192.168.1.2"/>
```

Also, ensure you start emulator with `--address` flag:

```
ionic emulate iOS -l -c -s --address 192.168.1.2
```

(replace `192.168.1.2` with your local IP)

**Comment by ibexel** [comment]
I don't know about --livereload. But I was having this issue with ionic serve. It turns out that it was because i had changed the names of the scripts in the package.json file. I changed them back to ionic:build and ionic:serve, and it worked again.

**Comment by ibexel** [comment]
sorry that was more related to #8314

**Comment by REPTILEHAUS** [comment]
Yeah Im getting something similar too. 

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8B62

It reloads but it cant seem to find the cordova.js file - If I run the app it works just fine and if I use emulator without livereload its fine too..

But with the following command I get this output: 
 ionic emulate ios --livereload --consolelogs --serverlogs


OUTPUT:
[18:41:57]  console.warn: Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to 
            include cordova.js or run in a device/simulator 
[18:41:57]  console.warn: Native: tried calling Splashscreen.hide, but Cordova is not available. Make sure to include 
            cordova.js or run in a device/simulator 





Here is my config.xml

  <description>An awesome Ionic/Cordova app.</description>
  <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
  <content src="index.html"/>
  <access origin="*"/>
  <allow-intent href="*"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>
  <allow-intent href="geo:*"/>
  <allow-navigation href="*"/>
  <allow-navigation href="http://192.168.56.1:8000"/>
  <platform name="android">
    <allow-intent href="market:*"/>
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
  </platform>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="SplashMaintainAspectRatio" value="true"/>
  <preference name="FadeSplashScreenDuration" value="300"/>
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar"/>
  </feature>
  <plugin name="ionic-plugin-keyboard" spec="~2.2.1"/>
  <plugin name="cordova-plugin-device" spec="~1.1.3"/>
  <plugin name="cordova-plugin-statusbar" spec="~2.2.0"/>
  <plugin name="cordova-plugin-whitelist" spec="~1.3.0"/>
  <plugin name="cordova-plugin-console" spec="~1.0.4"/>
  <plugin name="cordova-plugin-splashscreen" spec="~4.0.0"/>
  <plugin name="cordova-plugin-facebook4" spec="~1.7.4">
    <variable name="APP_ID" value="APPID"/>
    <variable name="APP_NAME" value="APP_NAME"/>
  </plugin>
  <plugin name="cordova-plugin-inappbrowser" spec="~1.5.0"/>
  <plugin name="cordova-plugin-transport-security" spec="~0.1.2"/>
</widget>

**Comment by Wolf00Bomber** [comment]
Any progress on this issue?

**Comment by leontyr** [comment]
After running `npm run watch` I receive:

`npm ERR! missing script: watch`
