### ISSUE TITLE
when ionic serve ,the error throw

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1441]
_From @webapp20 on September 30, 2016 7:15_

```
D:\nodeJS\ionic\cutePuppyPice>ionic serve

Running 'serve:before' npm script before serve
> ionic-app-base@ watch D:\nodeJS\ionic\cutePuppyPice
> ionic-app-scripts watch
'ionic-app-scripts' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���



npm
 ERR! Windows_NT 6.1.7601

npm
 ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\nod
e_modules\\npm\\bin\\npm-cli.js" "run" "watch"

npm
 ERR! node v4.6.0
npm ERR!
 npm  v2.15.9
npm
 ERR! code ELIFECYCLE
npm ERR! ionic-app-base@ watch: `ionic-app-scripts watch`
npm
ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-app-base@ watch script 'ionic-app-scripts watch'.
npm ERR! This is most likely a problem with the ionic-app-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm
ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-app-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ionic-app-base
npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodeJS\ionic\cutePuppyPice\npm-debug.log

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

_Copied from original issue: driftyco/ionic#8338_

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by BradyLiles** [comment]
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v5.12.0

I'm getting the same error as well.

**Comment by BradyLiles** [comment]
***npm-debug.log***

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\bliles\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.8
3 info using node@v5.12.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle ionic-hello-world@~prewatch: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prewatch: no script for prewatch, continuing
7 info lifecycle ionic-hello-world@~watch: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~watch: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~watch: PATH: C:\Users\bliles\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\dev2\AgentCubed\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Android\android-sdk\tools;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\dev\DevPath;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\Nmap;C:\Users\bliles\AppData\Local\atom\bin;C:\Users\bliles\AppData\Roaming\npm
10 verbose lifecycle ionic-hello-world@~watch: CWD: C:\dev2\AgentCubed
11 silly lifecycle ionic-hello-world@~watch: Args: [ '/d /s /c', 'ionic-app-scripts watch' ]
12 silly lifecycle ionic-hello-world@~watch: Returned: code: 3  signal: null
13 info lifecycle ionic-hello-world@~watch: Failed to exec watch script
14 verbose stack Error: ionic-hello-world@ watch: `ionic-app-scripts watch`
14 verbose stack Exit status 3
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\bliles\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\bliles\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd C:\dev2\AgentCubed
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bliles\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
19 error node v5.12.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ionic-hello-world@ watch: `ionic-app-scripts watch`
22 error Exit status 3
23 error Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by keyframeindia** [comment]
I have also same issue...

**Comment by gregor-srdic** [comment]
more issues with ionic serve:

ionic $ Caught exception:
 Error: watch null EPERM
    at exports._errnoException (util.js:907:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1217:21)

and

[11:43:00]  Error: Could not resolve entry (./.tmp/app/main.dev.js)
    at C:\Nomnio\SeltronHome\SeltronHome.Kelvin\node_modules\rollup\dist\rollup.js:8602:28

**Comment by Perroquiet** [comment]
I get the same error when making changes with my code. I have to stop and re-run `ionic serve` again from time to time.

**Comment by tezcane** [comment]
Only way I could fix it (tried everything I saw in multiple forums) was to make a new project and port over code.  I saw this when upgrading from Ionic RC0 to RC1.

**Comment by ratikanta-sdrc** [comment]
I was facing the same problem.
And for me 
npm install @ionic/app-scripts@latest --save-dev 
worked. after cd in to the project.
My ionic info is the following 
--------------------------------
Your system information:
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v5.12.0
--------------------------------
