### ISSUE TITLE
RC-0: Name pattern of generated pages

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1442]
_From @ecureuill on September 29, 2016 20:7_
#### Short description of the problem:

Ionic CLI **generate page** command doesn't add 'Page' sufix to the class name 
#### What behavior are you expecting?

When generating new page through ionic cli,  the class name of the .ts file generated should contains **Page** at the end of the name  

```
@Component({
  templateUrl: 'build/pages/home/home.html',
})
export class HomePage {}

```

**Steps to reproduce:**
1. ionic start myApp --v2
2. ionic build
3. ionic g page myPage

```
@Component({
  templateUrl: 'build/pages/home/home.html',
})
export class Home {}

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Like in ionic beta, set "Page" to the ClassName variable

```
function PageGenerator(options) {
  Generator.call(this, options);
  this.directory = 'pages';
  this.jsClassName += 'Page';
}

```

**Which Ionic Version?** 1.x or 2.x
2 RC0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID: Debian Description: Debian GNU/Linux 8.6 (jessie) 
Node Version: v4.5.0

_Copied from original issue: driftyco/ionic#8320_

**Comment by jgw96** [comment]
_From @ramonornela on September 30, 2016 14:20_

Not see problem **Uninstall Ionic CLI first, and then reinstall**
> Important: if you have installed the beta cli you should run npm uninstall -g ionic first. You need version 2.1.0 for this release. Check your cli version by running ionic -v in the command line.

Thanks

**Comment by ramonornela** [comment]
Close issue reproduced in project https://github.com/ramonornela/ionic_playground_rc0/commit/93fd132c7bd019f135241b06ca4a801a6f96077f installed cli local in project.

see page created https://github.com/ramonornela/ionic_playground_rc0/blob/93fd132c7bd019f135241b06ca4a801a6f96077f/src/pages/my-page/my-page.ts

Code reported are of the templates of beta.11.

```
node_modules/.bin/ionic g page myPage
```

Thanks

**Comment by ecureuill** [comment]
I have uninstalled ionic cli before installed the rc

In beta
`ionic g page myTeste`  generates **myTestePage** class

In RC
`ionic g page myTeste` generates **myTeste** class

**Comment by ramonornela** [comment]
Please run ```ionic info``` in the folder project and paste

**Comment by ecureuill** [comment]
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.6 (jessie) 
Node Version: v4.5.0

**Comment by ramonornela** [comment]
What version NPM?

**Comment by ecureuill** [comment]
$ npm --v
3.10.6

**Comment by ramonornela** [comment]
1 - Install bin in project ```npm install ionic@latest``` 
2 - Create page ```node_modules/.bin/ionic g page myTeste```

**Comment by ramonornela** [comment]
Is suffix, problem with template generator in Ionic

Thanks

**Comment by ramonornela** [comment]
Related https://github.com/driftyco/ionic/pull/8368

**Comment by yelhouti** [comment]
Hey guys, thank you for the great work.
Are you guys planing to fix this by any chance any time soon?
