### ISSUE TITLE
Ionic.io instagram access_token

### ISSUE THREAD

**Issue by sabre96** [ionic-team/ionic-cli#1458]
I use Ionic Cloud to login with instagram: `$ionicAuth.login('instagram').then( ... );`
 when logged in i try to get the list of follows with `$http.get("https://api.instagram.com/v1/users/self/follows?access_token="+$ionicAuth.getToken())`

I get an error saying the token is invalid, where does Ionic cloud store the token?

**Comment by flyfj** [comment]
also had this issue, please help if someone knows how

**Comment by sabre96** [comment]
It apparently has something to do with the sandbox thing. I've heard you can only get data from users within the sandbox.

**Comment by flyfj** [comment]
I think I have the user in the sandbox already. And the token returned by ionic has different format than a working token. 
Did you make it work?

**Comment by sabre96** [comment]
No not with ionic. Got close with a auth0 token but  that was an empty array cuz of the sandbox thing

**Comment by juliussohn** [comment]
I'm having the same issue. Sombody got a solution yet?
