### ISSUE TITLE
"…:before" npm scripts should not be hardcoded to be tied specifically to a dev or prod build

### ISSUE THREAD

**Issue by jdat82** [ionic-team/ionic-cli#1465]
With the actual defaults, there is no way to use the `--livereload` option of `ionic run` and `ionic emulate` commands.

You will always use a `prod` build because of these scripts: 

``` json
"serve:before": "watch",
"emulate:before": "build",
"deploy:before": "build",
"build:before": "build",
"run:before": "build"
```

As you see, `ionic serve` is using a `dev` build cause it uses the `watch` script but all other commands are using the `build` script which is a `prod` build.

I think we should be able to choose ourselves which type of build we want independently of the final command. Just because I'm executing an `ionic run` command doesn't mean I want a prod `build` especially if I want livereload support.

A very simple solution until the default build is more tolerant and subtle is to remove these lines entirely in `package.json`. Just launch `npm run watch` in one terminal and whatever command you want in another like `ionic emulate -l ios`.

Plus the `--livereload` option is blocking deployment in the ios simulator but there is already several issues referenced for that.

**Comment by dwieeb** [comment]
@jdat82 Is this still an issue?

**Comment by jdat82** [comment]
Sorry guy, don't know, there was so many bugs in ionic and especially the CLI at that time, I stopped using it. I'm not developing with ionic anymore. Things have probably changed a lot since that day.
