### ISSUE TITLE
Ionic 2 start command failed to create new sample project

### ISSUE THREAD

**Issue by sunilverma003** [ionic-team/ionic-cli#1486]
Hi All,

I am getting below error while creating sample blank app using ionic start command on windows 10 machine. I am able to install any npm package in my environment. I am not getting any proxy issue while installing npm package.

D:\Projects\Ionic2_Sample>ionic start ionic2_HelloWorld blank --v2 --ts
Creating Ionic app in folder D:\Projects\Ionic2_Sample\ionic2_HelloWorld based on blank project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1077:14)
Error Initializing app: Error: connect ETIMEDOUT 192.30.253.113:443
 Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1077:14)
Caught exception:
 Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1077:14)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

My system information:

---

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v4.5.0

Kindly help on this issue.

**Comment by jthoms1** [comment]
It appears that Github timed out.  Could you try running the command again and try accessing the URL directly from within your browser?  Thanks!

**Comment by sunilverma003** [comment]
Thanks Josh.

I tried commands multiple time but unfortunately getting same error on cmd. I accessed the URL directly from browser and downloaded sample app without any www folder. 
I

**Comment by chaitanyaphanikumar** [comment]
I too had the same error.. Any help is really appreciated.. 

This is my system info

Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.9.0
Xcode version: Not installed
