### ISSUE TITLE
When running on android,the main screen shows blank page with no error

### ISSUE THREAD

**Issue by NealBeat** [ionic-team/ionic-cli#1494]
when i run the ionic app on android devices ,it shows me a blank page without any error.
i tried to use chrome inspect to debug the app ,then i got the following errors!
`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///build/js/es6-shim.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///build/js/Reflect.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///build/js/zone.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///build/js/app.bundle.js Failed to load resource: net::ERR_FILE_NOT_FOUND`

![ionic22](https://cloud.githubusercontent.com/assets/20578354/19210668/0aefc690-8d5c-11e6-91e5-122afce1746c.png)

i found the needed js file is all blank,i'v checked the android apk file,the js files in apk is correct.so... please tell me why~.

**Comment by NealBeat** [comment]
who's ganna to help me? thanks a lot

**Comment by balasivagnanam** [comment]
there are many errors which are not shown during `ionic serve`. but when you try to build for device or run in device there should have been some errors on your command prompt. we need to clear all of them to avoid white screen. this is what i encountered.

**Comment by JamesLiuft** [comment]
I have the same question, have you get the solution?

**Comment by vicatcu** [comment]
Use chrome dev tools /  remote devices debugging capability with a phone attached,  and maybe you will see something in the console logs would be my advice.

**Comment by JamesLiuft** [comment]
@vicatcu  thanks for your answer,but I don't see any log,warning or error in console.
