### ISSUE TITLE
Android release apk build failed with exception: execution failed for task ":processDebugManifest"

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1509]
_From @ashutoshagg on October 10, 2016 9:34_

Execution failed for task ':processDebugManifest'.

> Manifest merger failed : Attribute activity#com.facebook.FacebookActivity@theme value=(@android:st
> yle/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:26:184-243
>         is also present at [com.facebook.android:facebook-android-sdk:4.16.1] AndroidManifest.xml:32
> :13-63 value=(@style/com_facebook_activity_theme).
>         Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml
> :26:9-246 to override.

**I have tried to add tools:replace="android:theme" in AndroidManifest.xml but still facing this error.**

_Copied from original issue: driftyco/ionic#8604_

**Comment by mmazloum** [comment]
I have a similar issue due with ionic build android command, it seems to be related to the ionic native image picker plugin which generates 2 identical activity in the androidManifest.xml : 

`Error: /Users/marwanmazloum/Desktop/Developpement/Cordon/mobileApp/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/marwanmazloum/Desktop/Developpement/Cordon/mobileApp/platforms/android/AndroidManifest.xml:36:9-163 Error:
	Element activity#com.synconset.MultiImageChooserActivity at AndroidManifest.xml:36:9-163 duplicated with element declared at AndroidManifest.xml:12:9-160
/Users/marwanmazloum/Desktop/Developpement/Cordon/mobileApp/platforms/android/AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

or am I wrong ?

**Comment by juni381** [comment]
i have the similar issue in running Ionic cordova run android 
Following are the errors :
`app:processDebugManifest
F:\Ionic Projects\MyIonicProject\platforms\android\app\src\main\AndroidManifest.xml:23:5-65 Error:
        Element uses-permission#android.permission.CAMERA at AndroidManifest.xml:23:5-65 duplicated with element declared at AndroidManifest.xml:19:5-90
F:\Ionic Projects\MyIonicProject\platforms\android\app\src\main\AndroidManifest.xml:25:5-84 Error:
        Element uses-feature#android.hardware.camera at AndroidManifest.xml:25:5-84 duplicated with element declared at AndroidManifest.xml:20:5-85
F:\Ionic Projects\MyIonicProject\platforms\android\app\src\main\AndroidManifest.xml Error:
        Validation failed, exiting


See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:app:processDebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
23 actionable tasks: 1 executed, 22 up-to-date
(node:324) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
F:\Ionic Projects\MyIonicProject\platforms\android\app\src\main\AndroidManifest.xml:23:5-65 Error:
        Element uses-permission#android.permission.CAMERA at AndroidManifest.xml:23:5-65 duplicated with element declared at AndroidManifest.xml:19:5-90
F:\Ionic Projects\MyIonicProject\platforms\android\app\src\main\AndroidManifest.xml:25:5-84 Error:
        Element uses-feature#android.hardware.camera at AndroidManifest.xml:25:5-84 duplicated with element declared at AndroidManifest.xml:20:5-85
F:\Ionic Projects\MyIonicProject\platforms\android\app\src\main\AndroidManifest.xml Error:
        Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
(node:324) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[OK] Your app has been deployed.
     Did you know you can live-reload changes from your app with --livereload? `
