### ISSUE TITLE
Permission from Config.xml not applied to AndroidManifest.xml '<config-file>'

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1510]
_From @BramDecuypere on October 10, 2016 14:7_
#### Short description of the problem:

When adding a permission in the config.xml file for android specific rights. 
This permission is not being copied to the AndroidManifest.xml
#### What behavior are you expecting?

The build process should add specific config-file target nodes 

**Steps to reproduce:**
1. Add permission to android only in the config.xml file
2. Run cordova prepare to make sure the AndroidManifest.xml is being overwritten
3. Watch at the AndroidManifest.xml file to check if the permission is being added

Config.xml:

```
<widget android-versionCode="1010001" id="be.xxxx.xxxxx" ios-CFBundleVersion="1.0.10001" version="1.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
 <platform name="android">
        ....
        <config-file target="AndroidManifest.xml" parent="/manifest">
            <uses-permission android:name="android.permission.CAMERA"/>
        </config-file>
        ...
    </platform>
.....
```

AndroidManifest.xml:

```
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1010001" android:versionName="1.0.1" package="be.xxxxx.xxxx.xxxx" xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application>
        <activity android:label="@string/multi_app_name" android:launchMode="singleTop" android:name="com.synconset.MultiImageChooserActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.Holo.Light" />
        <receiver android:enabled="true" android:name="com.google.android.gms.analytics.AnalyticsReceiver">
            <intent-filter>
                <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />
            </intent-filter>
        </receiver>
        <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.analytics.AnalyticsService" />
        <receiver android:enabled="true" android:exported="true" android:name="com.google.android.gms.analytics.CampaignTrackingReceiver">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
        <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.analytics.CampaignTrackingService" />
        <receiver android:name="cordova.plugins.Diagnostic$LocationProviderChangedReceiver">
            <intent-filter>
                <action android:name="android.location.PROVIDERS_CHANGED" />
            </intent-filter>
        </receiver>
    </application>
    <uses-sdk android:minSdkVersion="16" />
</manifest>

```

**Which Ionic Version?** 2.0.0-beta.11
#### Plunker that shows an example of your issue

Only visible after 'cordova prepare' to 

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 8.0 Build version 8A218a

_Copied from original issue: driftyco/ionic#8609_

**Comment by mebibou** [comment]
This is an old thread but how come this is still not resolved? how can we add a permission for Android using Ionic?

**Comment by iBasit** [comment]
+1

**Comment by englund** [comment]
To fix this I used the [cordova-custom-config plugin](https://github.com/dpa99c/cordova-custom-config).

**Comment by NeoLSN** [comment]
Add `xmlns:android="http://schemas.android.com/apk/res/android"` on root `<widget>` tag.

**Comment by charlesen** [comment]
That works ! Thank you so much @NeoLSN !

**Comment by dwieeb** [comment]
@NeoLSN Think we should add that to our starters? https://github.com/ionic-team/starters/blob/master/integrations/cordova/config.xml

**Comment by Laubeee** [comment]
this is ridiculous. I can't get it to work to set permissions from config.xml... how is this not an absolute standard use case?
