### ISSUE TITLE
ionic serve listen EADDRNOTAVAIL

### ISSUE THREAD

**Issue by zhao5436** [ionic-team/ionic-cli#1521]
Hi guys, I met a problem ,help me!

Running 'serve:before' npm script before serve

> ionic-hello-world@ watch /Users/wangjia/Desktop/zpp
> ionic-app-scripts watch
> [18:16:34]  ionic-app-scripts 0.0.30
> [18:16:34]  watch started ...
> [18:16:34]  build dev started ...
> [18:16:34]  clean started ...
> [18:16:34]  clean finished in 6 ms
> [18:16:34]  copy started ...
> [18:16:34]  bundle dev started ...
> [18:16:35]  lint started ...
> [18:16:36]  copy finished in 1.66 s
> [18:16:40]  lint finished in 5.57 s
> [18:16:49]  bundle dev finished in 14.83 s
> [18:16:49]  sass started ...
> [18:16:50]  sass finished in 1.14 s
> [18:16:50]  build dev finished in 16.17 s
> [18:16:50]  watch ready in 16.44 s
> There was an error serving your Ionic application: Error: listen EADDRNOTAVAIL 202.102.110.203:8100
>     at Object.exports._errnoException (util.js:893:11)
>     at exports._exceptionWithHostPort (util.js:916:20)
>     at Server.__dirname.Server.Server._listen2 (net.js:1233:19)
>     at listen (net.js:1282:10)
>     at net.js:1391:9
>     at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:63:16)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:82:10)
> Caught exception:
>  Error: listen EADDRNOTAVAIL 202.102.110.203:8100
>     at Object.exports._errnoException (util.js:893:11)
>     at exports._exceptionWithHostPort (util.js:916:20)
>     at Server.__dirname.Server.Server._listen2 (net.js:1233:19)
>     at listen (net.js:1282:10)
>     at net.js:1391:9
>     at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:63:16)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:82:10)

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-scripts#265
