### ISSUE TITLE
Error adding page to project

### ISSUE THREAD

**Issue by GrahamLock** [ionic-team/ionic-cli#1536]
Command: ionic g page loginsuccess

TypeError: undefined is not a function
    at /usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:23939:22
    at Array.filter (native)
    at filterAndCleanUpTemplates (/usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:23938:8)
    at Generator.renderAndWriteTemplates (/usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25310:133)
    at /usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25304:26

undefined is not a function (CLI v2.1.0)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v0.12.16
Xcode version: Xcode 8.0 Build version 8A218a 

OS version is actually 10.12 Sierra

**Comment by rahulthakur319** [comment]
I am also facing same issue

**Comment by richpolis** [comment]
I have the following error, not if the same case

MBP-de-Ricardo:todoLists richpolis$ ionic g provider todo-service
--------------------------------

Error: ENOENT: no such file or directory, scandir '/Users/richpolis/Proyectos/ionic2/todoLists/node_modules/ionic-angular/templates/provider'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at getTemplatesInDir (/usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:23931:65)
    at Generator.renderAndWriteTemplates (/usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25309:116)
    at /usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25304:26


ENOENT: no such file or directory, scandir '/Users/richpolis/Proyectos/ionic2/todoLists/node_modules/ionic-angular/templates/provider' (CLI v2.1.1)

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v6.6.0
Xcode version: Xcode 8.1 Build version 8B62 

What should the problem?
