### ISSUE TITLE
Error adding platform

### ISSUE THREAD

**Issue by GrahamLock** [ionic-team/ionic-cli#1537]
Command: ionic platform add ios
Adding ios project...

Creating Cordova project for the iOS platform:

```
Path: platforms/ios

Package: io.ionic.starter
Name: V2 Test
```

iOS project created with cordova-ios@4.2.1

Running command: "/Users/GDL/Cognition/Ionic Work/myNavApp/hooks/after_prepare/010_add_platform_class.js" "/Users/GDL/Cognition/Ionic Work/myNavApp"

Error: spawn EACCES

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v0.12.16
Xcode version: Xcode 8.0 Build version 8A218a

Tried with / without sudo

**Comment by danilosterrapid7** [comment]
I think this is related to the Mac OS Sierra version.
I am getting the same error when I try to spin up the phantomjs using karma.

**Comment by danilosterrapid7** [comment]
Definitely, it is a sierra issue. You need to figure out what directories you have your cordova and node installed. Then, you give permission of execute and read. It should work:

```
sudo chmod -R +xr PATH_CORDOVA_HERE
sudo chmod -R +xr PATH_NODE_HERE
```

**Comment by wavelynn** [comment]
https://cordova.apache.org/docs/en/latest/guide/cli/index.html#create-the-app

use cordova with same problem, 

so with --verbose parameter，you will see ,it gradle problem

in my computer, i installed android studio 3.0 preview & 2.x, it use gradle of 3.0 preview ,

```
ls -al /Applications/Android Studio 3.0 Preview.app/Contents/gradle/gradle-4.1/bin/gradle

-rw-r--r--@ 1 mix  staff  5286  8  7 14:40 /Applications/Android Studio 3.0 Preview.app/Contents/gradle/gradle-4.1/bin/gradle

ls -al /Applications/Android\ Studio.app/Contents/gradle/gradle-3.2/bin/gradle
-rwxr-xr-x@ 1 mix  staff  5231 11 15  2016 /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle
```

so you know how to sovle it
```
chmod a+x /Applications/Android\ Studio\ 3.0\ Preview.app/Contents/gradle/gradle-4.1/bin/gradle
```

it solved my problem
