### ISSUE TITLE
Failed to create ionic v2 project

### ISSUE THREAD

**Issue by shanmuga-axatech** [ionic-team/ionic-cli#1541]
I set my proxy and disabled the ssl details on npm still I am getting the following error 

<pre>
$ npm config list
; cli configs
user-agent = "npm/3.8.3 node/v5.10.1 win32 x64"

; userconfig C:\Users\Shanmuga Sundaram\.npmrc
http-proxy = "http://xx.xx.xx.x:8080"
https-proxy = "http://xx.xx.xx.x:8080/"
https.proxy = "http://xx.xx.xx.x:8080"
proxy = "http://xx.xx.xx.x:8080/"
registry = "http://registry.npmjs.org/"
strict-ssl = false

; globalconfig C:\Users\Shanmuga Sundaram\AppData\Roaming\npm\etc\npmrc
strict-ssl = false

; builtin config undefined
prefix = "C:\\Users\\Shanmuga Sundaram\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\wamp64\www\ionic
; HOME = C:\Users\Shanmuga Sundaram
; "npm config ls -l" to show all defaults.

</pre>

<pre>

$ ionic start MyIonic2Project tutorial --v2
Creating Ionic app in folder C:\wamp64\www\ionic\MyIonic2Project based on tutorial project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1059:14)
Error Initializing app: Error: connect ETIMEDOUT 192.30.253.113:443
 Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1059:14)
Caught exception:
 Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1059:14)

</pre>

**Comment by jthoms1** [comment]
Are you able to access the ionic2-app-base file from within your browser? https://github.com/driftyco/ionic2-app-base/archive/master.zip It appears to be failing while trying to download this file from github.

**Comment by shanmuga-axatech** [comment]
This because of proxy error if we execute this command then it's solved. I guess ionic is not considering the NPM proxy details

<pre>
PROXY=http://XX.XX.XX.XX:8080 ionic start crisis blank --v2
</pre>

If you think it's not an ionic bug then you can close this. I managed with the updated comment

**Comment by CodingYiyi** [comment]
weak network lead to this error。
do not use wifi in your office room。
using Ethernet cable fixed me this error。
