### ISSUE TITLE
[Feature Request] Test for templates

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-cli#1542]
_From @gperdomor on October 14, 2016 13:29_

Hi, thanks for this awesome framework.

Can you include or preconfigure test in the templates, and when generate a new page, generate the .spec.ts file too :D, the same behaviour that angular-cli

_Copied from original issue: driftyco/ionic#8707_

**Comment by Tiberriver256** [comment]
Any plans on this? 

Our company is pretty new to the framework. It's quite a bit of work to get Karma integrated into the default project generated from Ionic. It would be nice if it just did it straight out of the box.

**Comment by dwieeb** [comment]
@Tiberriver256 I am planning to look into it for Ionic Angular v4 projects. I don't have any dates, but it's something that the CLI should definitely do out of the box.

**Comment by Tiberriver256** [comment]
Would it be something you would consider PRs on? I'd be interested in contributing to learn more about the cli if PRs are open for consideration.

**Comment by dwieeb** [comment]
@Tiberriver256 PRs are most welcome! But, I actually started on these new generators myself for Ionic Angular v4. If you're interested, I've just made a label for some good first issues to tackle for people who want to get into the CLI code base: https://github.com/ionic-team/ionic-cli/blob/master/CONTRIBUTING.md#help-wanted

Thanks for your interest!

**Comment by dwieeb** [comment]
🔖 Update: Adding this to the 4.0.0 milestone because tests will be a part of the new starters for Ionic Angular v4+.
