### ISSUE TITLE
cli not creating apk for android

### ISSUE THREAD

**Issue by developercakephp** [ionic-team/ionic-cli#1545]
[npm-debug.zip](https://github.com/driftyco/ionic-cli/files/529978/npm-debug.zip)

Above is debug.log file attached

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by developercakephp** [comment]
Issue is solved. it was because of system error.
