### ISSUE TITLE
Package is not a valid task

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1552]
_From @anderson631 on October 17, 2016 14:0_

Hello,
I'm trying to use the "ionic package", but is returned the error: "package is not a valid task".

The version of my ionic-cli is v1.6.4.

Error screen in Windows CMD: https://goo.gl/SDPyE7

_Copied from original issue: driftyco/ionic#8758_

**Comment by jthoms1** [comment]
Could you try updating to a new version of the CLI.  We now have the latest release of 2.1.4.
