### ISSUE TITLE
Exit codes for Ionic

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1563]
_From @cincuranet on October 19, 2016 6:10_

I'm trying to script whole build-test-stage-publish process using Ionic 2, but it's really difficult because running i.e. `ionic build ios` always returns `0`. 

It should return some non-zero exit code when some error occurred.

_Copied from original issue: driftyco/ionic#8791_

**Comment by cincuranet** [comment]
An example. 

![example](https://i.snag.gy/OZyptL.jpg)

The `xcodebuild` ended with `65`, while the `ionic build ios` returned still 0 (and hence everything looked fine).

**Comment by packowitz** [comment]
I faced the same issue when I want to automate the build process. In my case there was a weired error in the lint step that made the build to exit with an error but it was treated as OK and the CI uploaded an empty app.
I use travis as CI, did an ionic build in the script step and an ionic upload in after_success so it should not upload anything when anything happen that makes the build not finishing completely.

**Comment by pvdyck** [comment]
Is the problem simply that the exit code of the app-script is not forwarded to npm ?

**Comment by schiller256** [comment]
When is planned to fix that?

**Comment by ambrosiawt** [comment]
+1

**Comment by hrzi** [comment]
+1
We're using TFS to automate builds and have the same problem. If there is an error in the build process, the exit code is always 0 and therefore the build status is always "Build succeeded" even if it fails.
Please fix this issue asap.

**Comment by guibernardino** [comment]
+1

**Comment by dwieeb** [comment]
This is not an issue with the latest CLI.
