### ISSUE TITLE
error caught undefined exception during ionic state restore

### ISSUE THREAD

**Issue by lucapug** [ionic-team/ionic-cli#1569]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts
#### Short description of the problem:

ionic state restore
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device
Caught exception:
 undefined
#### What behavior are you expecting?

expect to add all cordova plugins included in the package.json

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by aekevinscroggins** [comment]
I'm also having the same issue when running automated builds via buddybuild.

> cordova plugin add cordova-plugin-device
> Caught exception:
> undefined 
> Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Here is the output from ionic info:
> ******************************************************
>  Dependency warning - for the CLI to run correctly,
>  it is highly recommended to install/upgrade the following:
>  Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
>  Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)
> ******************************************************
> --------------------------------
> --------------------------------
> Your system information:
> Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
> 6.4.0
> Ionic Framework Version: 1.3.0
> Ionic CLI Version: 2.1.4
> Ionic App Lib Version: 2.1.2
> ios-deploy version: Not installed
> ios-sim version: 3.1.1
> OS: Mac OS X El Capitan
> Node Version: v4.2.1
> Xcode version: Xcode 7.3.1 Build version 7D1014

Looks like it might be a cordova related issue? Strange because there is a call to either install or update cordova prior to ionic info being called, ie:
```
echo '=== Start to run : npm install npm -g'
npm install npm -g

if hash cordova 2>/dev/null; then
	echo '=== Detected cordova command, run npm update -g cordova'
	npm update -g cordova
else
	echo '=== Can not detect cordova command, run npm install -g cordova'
	npm install -g cordova
fi

if hash ionic 2>/dev/null; then
	echo '=== Detected ionic command, run npm update -g ionic'
	npm update -g ionic
else
	echo '=== Can not detect ionic command, run npm install -g ionic'
	npm install -g ionic
fi

echo '=== Start to run : npm install'
npm install

echo '=== Start to run : bower install'
bower install

echo '=== Start to run : ionic info'
ionic info
```
