### ISSUE TITLE
Unable to add/remove platforms - android/ios

### ISSUE THREAD

**Issue by lakshmankotipalli** [ionic-team/ionic-cli#1572]
Hello,

I am not able to add/remove platforms - android/ios using the commands
`ionic platform add android / ionic platform add ios / ionic platform remove android / ionic platform remove ios`

I am getting the error saying : 
`Caught exception :
TypeError: Can't call method on  undefined
at TypeError (native)
at module.exports
at createHTML
at bold`

Please help me trace where it is going wrong. Thanks in advance :slightly_smiling_face:

**Comment by jayeshanandani** [comment]
Can you add some more information? The versions of Ionic and CLI you are using and in addition a stack trace snapshot.

**Comment by vuk-nikolic** [comment]
Same problem here:

> Caught exception:
>  TypeError: Can't call method on  undefined
>   at TypeError (native)
>   at module.exports (/Users/vuknikolic/projects/voyagecontrol/VoyageControlApp/node_modules/core-js/modules/_defined.js:3:28)
>   at createHTML (/Users/vuknikolic/projects/voyagecontrol/VoyageControlApp/node_modules/core-js/modules/_string-html.js:7:19)
>   at bold (/Users/vuknikolic/projects/voyagecontrol/VoyageControlApp/node_modules/core-js/modules/es6.string.bold.js:5:12)
>   at cb (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
>   at done (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
>   at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
>   at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
>   at [object Object].Console.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
>   at emit (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
>   at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
>   at _each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
>   at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
>   at [object Object].Logger.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
>   at [object Object].target.(anonymous function) [as error] (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
>   at Socket.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
>   at emitOne (events.js:95:20)
>   at Socket.emit (events.js:182:7)
>   at readableAddChunk (_stream_readable.js:153:18)
>   at Socket.Readable.push (_stream_readable.js:111:10)
>   at Pipe.onread (net.js:534:20)
> 
> 
> Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Ionic info:

> Cordova CLI: 6.3.1
> Gulp version:  CLI version 3.9.1
> Gulp local:   Local version 3.9.1
> Ionic Framework Version: 1.1.0
> Ionic CLI Version: 2.1.1
> Ionic App Lib Version: 2.1.1
> ios-deploy version: 1.9.0
> ios-sim version: 5.0.9
> OS: Mac OS X Sierra
> Node Version: v5.12.0
> Xcode version: Xcode 8.0 Build version 8A218a
