### ISSUE TITLE
Lost output from xcodebuild on fresh build

### ISSUE THREAD

**Issue by cincuranet** [ionic-team/ionic-cli#1573]
When I do `ionic build ios` on a fresh repository the end of the output from `xcodebuild` process is lost. Looks like it's not properly captured or some buffer is filled.

![img](https://cloud.githubusercontent.com/assets/4540597/19589595/6826477e-976d-11e6-88a4-33a2a5e9d1db.png)

I tried running in `ionic build ios` from `bash` in _iTerm2_. `bash` directly with output redirected to file. `sh` and `sh` from _TeamCity_ and `sh` via _Python_.

Running the build again (in any above mentioned environments), gives expected output with `** BUILD SUCCEEDED **`.

Here's the `ionic info`:

```
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Sierra
Node Version: v4.6.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by Tumeconnais** [comment]
Same problem here, any fix?

**Comment by pjorquera** [comment]
The problem is related with the amount of data allowed on stdout's Cordova child process that is spawned from Ionic CLI.

I sumbitted the following PR fixing that:

https://github.com/driftyco/ionic-cli/pull/1694
