### ISSUE TITLE
Error build platform androoid

### ISSUE THREAD

**Issue by houssenedao** [ionic-team/ionic-cli#1581]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--color' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild ionic-hello-world@
6 info build ionic-hello-world@
7 verbose unsafe-perm in lifecycle true
8 info ionic-hello-world@ Failed to exec build script
9 verbose stack Error: ionic-hello-world@ build: `ionic-app-scripts build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid ionic-hello-world@
11 verbose cwd /Users/twinscoding/Public/Mobile/Apr News
12 error Darwin 16.0.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
14 error node v4.6.1
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error ionic-hello-world@ build: `ionic-app-scripts build`
17 error Exit status 1
18 error Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
18 error This is most likely a problem with the ionic-hello-world package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ionic-app-scripts build
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs ionic-hello-world
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls ionic-hello-world
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
### Ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v4.6.1
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jthoms1** [comment]
Could you provide more information as to what you were doing when this occurred or steps that could reproduce this?  Thanks!
