### ISSUE TITLE
error: when ionic build android

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1585]
_From @tianleios on October 22, 2016 4:46_

ionic2 beat i can ionic build android. but ionic2-rc i got this error.
Error: /Users/tianlei/Desktop/new/src/main/cityNet/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':processDebugResources'.
  
  > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/tianlei/android-sdk-macosx/build-tools/23.0.3/aapt'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

_Copied from original issue: driftyco/ionic#8849_

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by tianleios** [comment]
@jthoms1 
Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by romanrast** [comment]
Getting the same issue here!

**Comment by romanrast** [comment]
Managed to fix this by adding xmlns:gap="http://phonegap.com/ns/1.0" to config.xml

`<widget id="com.ionicframework.yourpackagename" 
version="0.0.1" 
xmlns="http://www.w3.org/ns/widgets" 
xmlns:cdv="http://cordova.apache.org/ns/1.0"
xmlns:gap="http://phonegap.com/ns/1.0">`

not sure tho if this ist the best fix.

**Comment by Hardik170594** [comment]
Managed to fix this by adding xmlns:cdv="http://cordova.apache.org/ns/1.0" to config.xml

`<widget id="com.ionicframework.yourpackagename" version="0.0.1"  xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns="http://www.w3.org/ns/widgets">`
