### ISSUE TITLE
Ionic 1 console font color for livereload is unreadable

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1589]
_From @jraoatlogic on October 25, 2016 2:50_
#### Short description of the problem:

When running on device with live reload and redirect messages to cli, the default console font color is dark blue, this is unreadable on black background.
#### What behavior are you expecting?

Use a color that is readable.

**Steps to reproduce:**
1. Run an app with live reload on device
2. Trigger app js to print something to console.log
3. Read the message on command line window

```
ionic run android -l -s -c
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 This is on Windows

**Which Ionic Version?** 1.x 

_Copied from original issue: driftyco/ionic#8888_

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jraoatlogic** [comment]
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.4

**Comment by jthoms1** [comment]
Sorry one more request.  A screenshot would be very helpful. Thanks again!

**Comment by jraoatlogic** [comment]
<img width="385" alt="capture" src="https://cloud.githubusercontent.com/assets/8001440/19792918/641ef812-9cfc-11e6-990a-33422ee593d4.PNG">

**Comment by dwieeb** [comment]
Likely not an issue with the latest CLI, as I haven't heard any complaints. We use standard terminal colors (non-256), so your terminal theme must be configured to make those colors work. It'd be in your terminal settings.
