### ISSUE TITLE
cutePuupyPics in ionic serve

### ISSUE THREAD

**Issue by donernacio** [ionic-team/ionic-cli#1593]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts
#### Short description of the problem:

when doing ionic serve in different project.
the one that always shows is your cutePuppyPics sample app.

i can't use ionic serve to preview my project

i don't know what happen it was working perfectly in ionic 1 then when i tried ionic 2 even when i use ionic serve to ionic 1 project, the cutePuppyPics is the one showing.
i already tried removing ionic or even nodejs and reinstalling them. still shows same result when i use ionic serve.

thanks
#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.
