### ISSUE TITLE
ERROR: Plugin not found, or is not a CDVPlugin ... with reproducing step on ionic.rc-1

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1594]
_From @haxpor on October 26, 2016 13:13_

As per this discussion about this issue found since April 2014 https://forum.ionicframework.com/t/plugins-does-not-exist/2980/19. That issue is still existing as of today of ionic.rc-1.

I have tested and generated diff file between success project it generated, and failed one. You can see difference between the two projects, and how to reproduce it at https://gist.github.com/haxpor/bbf4dab73cb6883a8d5ef90890611671.

In general, it seems like you have to 
- remove ios platform
- remove `plugins/ios.json` file
- add ios platform again
- build via `ionic build`

Then you will get a ready plugins-error free project. But if you make a change in source code (.ts), and you have to build the project again to let changes take effect into target XCode project, this particular step will break things and "Plugin not found ..." will come back again.

Thus I did both path, saved them into 2 folder projects and execute `diff -rq failedProj successProj` to see what broke things there. It turns out that `ionic build` would be likely to cause the problem as we need to rely on it for code to take effect into target project. In conclusion, source files for plugins are not copied into target project again if we make change to source code, and rebuilding it. _Only removing platform, and starting over will do_.

This will be really painful if developers need to iterate fast on ios development that involves using plugins. Time wasted in re-adding, re-building, and bunch of necessary steps to make it work will accumulate and do more harm than good.

Please look at gist link above for more detail along with steps to reproduce.

My `ionic info` is as follows.

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.0 Build version 8A218a
```

Note: I'm on Sierra 10.12, not El Capitan like `ionic info` shown.

_Copied from original issue: driftyco/ionic-app-scripts#245_

**Comment by jthoms1** [comment]
This appears to be a bug I am going to flag it and we will hopefully get it resolved soon.  The `ionic info` issue with Sierra is resolved in a new version of the CLI.  Try installing 2.1.4 for that fix.
