### ISSUE TITLE
ionic build copies www/assets to platforms and not src/assets 

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1599]
_From @nottinhill on October 27, 2016 14:4_
#### Short description of the problem:

`ionic build` copies to platforms folder from www/assets and not from src/assets. Same for index.html. So in order run to develop on device we need to:

`rm -rf www`
`ionic build` 
`ionic run`
#### What behavior are you expecting?

All for the run on device folder should be taken from src. 
aka ionic run should perform ionic build first. 

**Steps to reproduce:**
1. create unique file in your src/assets folder
2. look at assets folder
3. ionic run
4. watch the unique file in src/assets folder not being copied over to platforms folder.

**Which @ionic/app-scripts version are you using?**

0.0.36

This whole topic needs some more testing on Ionic teams side in my opinion.

_Copied from original issue: driftyco/ionic-app-scripts#250_

**Comment by jthoms1** [comment]
I believe this is working as expected.  Are you able to correctly view the application through `ionic serve`?  I would assume that if the assets are not copied from the src directory to the www directory that this would also be an issue.

Please let me know.  Thanks!

**Comment by jmtech-online** [comment]
I think you have missed the point jthoms1. 

ionic serve copies from the src/assets into www/assets directory - so ionic serve works. 
ionic cordova build browser however copies from www/assets directory to /platforms/browser/www/assets which is wrong. 

Currently, it forces you to run ionic serve to get the assets in the right folder before running ionic cordova build browser. That's dumb. The build should be pulling from the src/assets directory.

**Comment by jmtech-online** [comment]
@dwieeb thanks for explaining, I'll check that out now.
