### ISSUE TITLE
IonicRC1 ionic serve failure

### ISSUE THREAD

**Issue by JacquesMarques** [ionic-team/ionic-cli#1610]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
When I try start ionic serve I receive an error message.

#### What behavior are you expecting?
I expect the app is serve to open in browser

**Steps to reproduce:**
1. ionic serve
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

$ ionic serve

Running 'serve:before' npm script before serve

> ionic-hello-world@ watch /home/jacques/desenvolvimento/mobile/ionic2/curso-iniciando-ionic-2/curso-iniciando-ionic2
> ionic-app-scripts watch

[09:39:50]  ionic-app-scripts 0.0.39 
[09:39:50]  watch started ... 
[09:39:50]  build dev started ... 
[09:39:50]  clean started ... 
[09:39:50]  clean finished in 25 ms 
[09:39:50]  copy started ... 
[09:39:50]  transpile started ... 
[09:39:50]  lint started ... 
[09:39:52]  lint finished in 1.66 s 
[09:39:53]  transpile finished in 3.40 s 
[09:39:53]  webpack started ... 
[09:39:53]  copy finished in 3.55 s 
[09:40:00]  webpack finished in 7.15 s 
[09:40:00]  sass started ... 
[09:40:02]  sass finished in 1.55 s 
[09:40:02]  build dev finished in 12.14 s 
[09:40:02]  watch failed: watcher error: 
            /home/jacques/desenvolvimento/mobile/ionic2/curso-iniciando-ionic-2/curso-iniciando-ionic2/home/jacques/desenvolvimento/mobile/ionic2/curso-iniciando-ionic-2/curso-iniciando-ionic2/src/**/*.ts:
            Error: watch /home/jacques/desenvolvimento/mobile/ionic2/curso-iniciando-ionic-2/curso-iniciando-ionic2/src 
            ENOSPC 
[09:40:02]  ionic-app-script task: "watch" 
[09:40:02]  Error: watcher error: 
            /home/jacques/desenvolvimento/mobile/ionic2/curso-iniciando-ionic-2/curso-iniciando-ionic2/home/jacques/desenvolvimento/mobile/ionic2/curso-iniciando-ionic-2/curso-iniciando-ionic2/src/**/*.ts:
            Error: watch /home/jacques/desenvolvimento/mobile/ionic2/curso-iniciando-ionic-2/curso-iniciando-ionic2/src 
            ENOSPC 

npm ERR! Linux 3.13.0-100-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jacques/desenvolvimento/mobile/ionic2/curso-iniciando-ionic-2/curso-iniciando-ionic2/npm-debug.log
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by WombatRunner** [comment]
Same here...ony problem with Ionic2...have updated NPM and Node but no joy...keep me informed please.

**Comment by seanmavley** [comment]
still having same issue.

**Comment by dm-grinko** [comment]
did you fix it guys?
watch failed: watcher error:

**Comment by Bajranghudda1** [comment]
same issue here with updated npm :-(

**Comment by sayyaff** [comment]
I found out another ENOSPC issue with the solution in it
https://github.com/ionic-team/ionic-cli/issues/1828
