### ISSUE TITLE
Windows: `ionic resources` creates invalid paths in config.xml, using back-slash instead of front-slash

### ISSUE THREAD

**Issue by loban** [ionic-team/ionic-cli#1613]
Ticket #625 was erroneously closed as a duplicate when it is completely different.

If one runs "ionic resources" on a windows machine, the paths generated into config.xml use back-slashes instead of front-slashes. Such a config.xml will

1. Not work in linux or mac.
2. Not even work in windows if you then run "ionic state restore" (if platforms and plugins folders are not generated yet).

Ionic CLI should always use front-slashes in all OS.

**Comment by nicopeeters** [comment]
Any news on this?

**Comment by AresDev** [comment]
+1

Same thing happened to me, Ionic version 2.2.1

**Comment by rnarian** [comment]
Same here on Ionic version 2.2.1 (even if I remember this issue popping up occasionally 
since version 1)

**Comment by dearibujar** [comment]
Any fix on this ?

**Comment by dwieeb** [comment]
@dearibujar Update your CLI to the latest version.
