### ISSUE TITLE
Error occured during initialization of VM Could not reserve enough space for object heap

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1616]
_From @pantonis on November 2, 2016 14:1_

#### Short description of the problem:
Error while running ionic run android --device
Error occured during initialization of VM Could not reserve enough space for object heap

#### What behavior are you expecting?
Successful app deployment on my device

**Steps to reproduce:**
1. ionic run android --device

insert any relevant code between the above and below backticks

**Which @ionic/app-scripts version are you using?**
@ionic/app-scripts": "0.0.37",

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
![capture](https://cloud.githubusercontent.com/assets/3295086/19931530/7af636c8-a115-11e6-8a11-a05dac272ee2.PNG)

I have about 4GB free RAM at the moment I run it

_Copied from original issue: driftyco/ionic-app-scripts#298_

**Comment by pantonis** [comment]
Any news on how to resolve this? I am currently stuck

**Comment by pantonis** [comment]
The suggestion to increase the the MaxHeapSize on this [link](https://forum.ionicframework.com/t/run-android-errors/25128/5) didnt help.

What I did and it solved the problem was to install a x64 version of Java and change the JAVA_HOME env variable to point to the x64 version of Java.

That did the trick

**Comment by PterPmnta** [comment]
@pantonis  maybe have JAVA for 64bits install ?
