### ISSUE TITLE
Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by macdasi** [ionic-team/ionic-cli#1618]
Packages.json 

> "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build",
    "typings": "typings"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21",
    "ng2-translate": "3.0.0",
    "stms-lib":"0.1.25"
  },
  "devDependencies": {
    "@ionic/app-scripts": "latest",
    "typescript": "^2.0.3"
  },

error

> [17:56:05]  ionic-app-scripts 0.0.39
[17:56:05]  build prod started ...
[17:56:05]  clean started ...
[17:56:05]  clean finished in 5 ms
[17:56:05]  copy started ...
[17:56:05]  ngc started ...
[17:56:05]  copy finished in 43 ms
[17:56:06]  lint started ...
[17:56:09]  lint finished in 3.04 s
[17:56:09]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider
            replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in
            C:/Repos/patient-portal/.tmp/app/app.module.ts, resolving symbol AppModule in
            C:/Repos/patient-portal/.tmp/app/app.module.ts
[17:56:09]  ngc failed
[17:56:09]  ionic-app-script task: "build"
[17:56:09]  Error: Error

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hadar.m\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! PatientPortal@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PatientPortal@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PatientPortal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PatientPortal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PatientPortal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Repos\patient-portal\npm-debug.log
Caught exception:
 undefined

as I run ionic build command

**Comment by macdasi** [comment]
My app.module.ts 

```
import {NgModule , OpaqueToken} from '@angular/core';
import {HttpModule, XHRBackend, RequestOptions, Http, ConnectionBackend}    from '@angular/http';
import {IonicApp, IonicModule, LoadingController, AlertController} from 'ionic-angular';
import {Storage} from '@ionic/storage';
import {MyApp} from './app.component';
import {CumulativePage} from "../pages/cumulative/cumulative.component";
import {DashboardPage} from "../pages/dashboard/dashboard";
import {ItemDetailsPage} from "../pages/item-details/item-details";
import {LoginPage} from "../pages/login/login";
import {OrderResultsPage} from "../pages/order-results/order-results.component";
import {OrdersPage} from "../pages/orders/orders";
import {PatientLoginPage} from "../pages/patient-login/patient-login";
import {ResultsPage} from "../pages/results/results";
import {SandboxPage} from "../pages/sandbox/sandbox";
import {SplashPage} from "../pages/splash/splash.component";
import {StmsModule, AuthHttpService, AuthConnectionBackend} from "stms-lib/index";
import {LoadingService} from "../shared/services/dialogs/loading.service";
import {AlertService} from "../shared/services/dialogs/alert.service";
import {TranslateModule, TranslateStaticLoader, TranslateLoader} from 'ng2-translate';
import {SideMenu} from "../shared/components/side-menu/side-menu";
import {ResultComponent} from "../shared/components/result/result.component";
import {SharedModule} from "../shared/shared.module";
import {AppSettingsService} from "./app.settings";

var FileHttpServiceOT = new OpaqueToken("FileHttpService");


export function authHttpServiceFactory(backend:XHRBackend,
                                       defaultOptions:RequestOptions) {
    return  new AuthHttpService(backend,
        defaultOptions,
        AppSettingsService.BASE_END_POINT,
        AppSettingsService.TIMEOUT); 
}

export function httpFactory(backend:XHRBackend,
                            defaultOptions:RequestOptions) {
    return  new Http(backend,
        defaultOptions);
}

export function createTranslateLoader(http:Http) {
    return  new TranslateStaticLoader(http, '/assets/i18n', '.json');
}


@NgModule({
    declarations: [
        MyApp,
        CumulativePage,
        DashboardPage,
        ItemDetailsPage,
        LoginPage,
        OrderResultsPage,
        OrdersPage,
        PatientLoginPage,
        ResultsPage,
        SandboxPage,
        SplashPage,
        ResultComponent,
        SideMenu
    ],
    imports: [
        StmsModule,
        SharedModule,
        HttpModule,
        TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (createTranslateLoader),
            deps: [Http]
        }),
        IonicModule.forRoot(MyApp)
    ],
    bootstrap: [IonicApp],
    entryComponents: [
        MyApp,
        CumulativePage,
        DashboardPage,
        ItemDetailsPage,
        LoginPage,
        OrderResultsPage,
        OrdersPage,
        PatientLoginPage,
        ResultsPage,
        SandboxPage,
        SplashPage
    ],
    providers: [
        Storage,
        {provide:ConnectionBackend , useClass:XHRBackend},
        {provide: XHRBackend, useClass: AuthConnectionBackend},
        {
            provide: Http,
            useFactory: authHttpServiceFactory,
            deps: [XHRBackend, RequestOptions ]
        },
        {
            provide: FileHttpServiceOT,
            useFactory: httpFactory,
            deps: [XHRBackend, RequestOptions]
        },
        {provide: LoadingController, useClass: LoadingService},
        {provide: AlertController, useClass: AlertService}]
})
export class AppModule {
}
```

**Comment by yogibaba2** [comment]
have you resolved the issue?
