### ISSUE TITLE
ionic resources command problems

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1638]
_From @mflmartin on November 4, 2016 10:2_

#### Short description of the problem:
`ionic resources` does not generate ios and android icons & splash screens in any way
`ionic resources --icons` generates icons for ios but NOT android. They are generated into the resources/android folder, BUT not copied and propertly renamed to platform/android/res, which means that when you compile the app, you get the cordova robot. 

`ionic resources --splash` generates splash for ios but NOT android They are generated into the resources/android/splash folder, BUT not copied and propertly renamed to platform/android/res, which means that when you compile the app, you get the cordova robot. 

#### What behavior are you expecting?
That it works correctly. 

**Steps to reproduce:**
1. place icon.png and splash.png in the resources folder
2. Execute `ionic resources`
3. They are not created propertly.
4. Execute `ionic resources --icons`
5. Android icons in platform/res, are not propertly updated
6. Execute `ionic resources --splash`
7. Android splash in platform/res, are not propertly updated

**Which @ionic/app-scripts version are you using?**
Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v6.4.0

_Copied from original issue: driftyco/ionic-app-scripts#312_

**Comment by jgw96** [comment]
_From @mflmartin on November 4, 2016 10:44_

I found a **res** folder at the ROOT of my project containing android resources. It might be that it creates it in the ROOT folder of the project, instead of placing it inside the platforms/android folder. If this helps you narrow it down more.

**Comment by jgw96** [comment]
_From @ferranvila on November 6, 2016 9:2_

@mflmartin Me too. I think this happens after the new [cordova-android version](https://github.com/apache/cordova-android/releases): 6.X.X. If you downgrade to 5.2.2 the icon is displayed but the splash screen don't.

**Comment by jgw96** [comment]
Possibly related https://github.com/driftyco/ionic/issues/9060

**Comment by RickMeijer** [comment]
Problem with cordova-android, should be fixed in 6.1.0, but it's not available on npm yet.

See changelog here: https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md, and issue here: https://issues.apache.org/jira/browse/CB-12077

**Comment by dasilvacontin** [comment]
https://github.com/driftyco/ionic/issues/9060#issuecomment-259445756

Can be closed.
