### ISSUE TITLE
Cross Platform Build Issue with Ionic Resources

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1639]
_From @ClickSimply on November 7, 2016 7:49_

#### Short description of the problem:
When you run "ionic resources" on a windows machine to build icons and splashscreens for iOS and Android, then transfer the project to a Macintosh, iOS & Android builds to the device/emulator fail until you run 'ionic resources' again on the Macintosh.

#### What behavior are you expecting?
I should be able to generate icons and splash screens on a Linux, Windows or Macintosh computer without breaking the build process when the project is transferred to another operating system.

**Steps to reproduce:**
1. Generate an Ionic2 project on  a Windows computer.
2. Run "ionic platform add ios && ionic platform add android && ionic resources"
3. Transfer the project to a Macintosh comptuer using GIT, thumb drive, etc.
4. Run "ionic build ios" or "ionic build android".
5. The build fails when it attempts to copy the icons and splash screen files.

**Which @ionic/app-scripts version are you using?**
0.0.39

**Other information:** 
This is clearly caused by the file paths generated by the script int he "config.xml" file.

When "ionic resources" is ran on a windows computer you end up with paths like this:

`resources\android\icon\drawable-ldpi-icon.png`

But when it's ran on a Macintosh or Linux computer the paths look like this:

`resources/android/icon/drawable-ldpi-icon.png`

Windows doesn't seem to have a problem running the build process using forward slashes, however Macintosh computers fail when the paths are using backslashes so the answer in my opinion is going to be to force the script to always use forward slashes.

_Copied from original issue: driftyco/ionic-app-scripts#318_

**Comment by dwieeb** [comment]
This is fixed in the latest CLI.
