### ISSUE TITLE
Ionic run in dev mode

### ISSUE THREAD

**Issue by PabloFNK** [ionic-team/ionic-cli#1642]
The problem is when we are testing in device 'ionic run' makes a production build, however, the ionic-app-scripts allow to create a dev build using the --dev flag.

At the moment we are adding that flag changing the build script in our package.json to this:

  "build": "ionic-app-scripts build --dev",

Could it be possible to execute the ionic-app-scripts build in development mode if we type 'ionic run --dev' in the console?

**Comment by dwieeb** [comment]
`--dev` is the default. The flag shouldn't be necessary.
