### ISSUE TITLE
ionic serve -l is broken

### ISSUE THREAD

**Issue by adjhernandez** [ionic-team/ionic-cli#1660]
System Info

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v7.1.0
Xcode version: Xcode 8.0 Build version 8A218a

When running ionic serve --lab from the terminal this is the output:

> ionic-hello-world@ ionic:serve /Users/aaronhernandez/Documents/IonicProjects/simpletabtest
> ionic-app-scripts serve "--lab"

[18:16:43]  ionic-app-scripts 0.0.43 
[18:16:44]  watch started ... 
[18:16:44]  build dev started ... 
[18:16:44]  clean started ... 
[18:16:44]  clean finished in 3 ms 
[18:16:44]  copy started ... 
[18:16:44]  transpile started ... 
[18:16:45]  transpile finished in 1.57 s 
[18:16:45]  webpack started ... 
[18:16:45]  copy finished in 1.67 s 
[18:16:48]  webpack finished in 3.09 s 
[18:16:48]  sass started ... 
[18:16:49]  sass finished in 811 ms 
[18:16:49]  build dev finished in 5.50 s 
[18:16:49]  watch ready in 5.53 s 
[18:16:49]  dev server running: http://localhost:8100/ 

When the browser launches it tries to go here:
http://localhost:8100//__ion-dev-server/ionic_lab.html

Displayed on the page is: 
Cannot GET //__ion-dev-server/ionic_lab.html

Not sure what's happening here. I can still emulate either platform and deploy to devices fine but the lab just simply doesn't work. As an alternative I can launch the lab from the "Ionic Lab" desktop app and it works fine.

**Comment by wbell** [comment]
Same issue. My system info:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by bilnkat** [comment]
This might help...

https://forum.ionicframework.com/t/ionic-serve-lab-dont-work-in-rc2/69862

**Comment by camuskool** [comment]
Please verify your package.json

https://github.com/driftyco/ionic-app-scripts

"scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch"
  },

Remove "ionic-build"

**Comment by gtejwani** [comment]
package.json and remove "ionic:serve"

"scripts": { "ionic:build": "ionic-app-scripts build", "ionic:serve": "ionic-app-scripts serve" },

Remove "ionic:serve"

"scripts": { "ionic:build": "ionic-app-scripts build" },
