### ISSUE TITLE
Capitalised Generator Types give "Unknown Generator Type" error.

### ISSUE THREAD

**Issue by Nicholas-Westley** [ionic-team/ionic-cli#1667]
`ionic generate Provider myprovider`

gives: 
```
Unknown Generator Type
Available generators:
 * Component
 * Directive
 * Page
 * Pipe
 * Provider
 * Tabs

```
Notice the capital letters at the start of every word.  Copying directly from the "available generators" list gives an "unknown generator" error.

Your system information:

Cordova CLI: 6.4.0   
Gulp version:  CLI version 3.9.1   
Gulp local:    
Ionic Framework Version: 2.0.0-rc.2  
Ionic CLI Version: 2.1.0  
Ionic App Lib Version: 2.1.0-beta.1  
ios-deploy version: 1.8.6   
ios-sim version: Not installed  
OS: Mac OS X El Capitan  
Node Version: v6.4.0  
Xcode version: Xcode 8.1 Build version 8B62

**Comment by jecht83** [comment]
https://github.com/driftyco/ionic/issues/9125
