### ISSUE TITLE
ionic icon/splash automatic image generation testing

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/ionic-cli#167]
We're testing out a new feature that's just in a beta version of the CLI. Please take a look at the [Icon and splash screen image generation](https://github.com/driftyco/ionic-cli/tree/v1_2_14#icon-and-splash-screen-image-generation) section in the 1.2.14 branch.

```
npm install -g ionic@1.2.14-beta1
```

If you'd like to help test it out, please us this issue to help group the discussion around it's development or any bugs. Thanks!

cc/ @cfjedimaster @hollyschinsky @nraboy

**Comment by aluna82** [comment]
Before automatically create the icon and splash
Is it possible to customize the icon and splash, so it would be different from the default? or is it possible to change the default size?
