### ISSUE TITLE
Receiving ERROR: Start Page at 'www/index.html' was not found -- after updating to RC2

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1675]
_From @axalon on November 12, 2016 4:16_

Updated to RC2, did the following:

**ionic start testproject blank --v2**

followed by

**ionic build ios**

Opened the XCode project and ran it received:

**testproject[15720:3726809] ERROR: Start Page at 'www/index.html' was not found.
testproject[15720:3726809] ERROR Internal navigation rejected - <allow-navigation> not set for url='about:blank'**

Checked www folder, no index.html to be found. Was not an issue in RC1 and prior. Any ideas?

_Copied from original issue: driftyco/ionic#9129_

**Comment by jgw96** [comment]
_From @ozexpert on November 12, 2016 18:23_

same thing happening. but building seems not running...

**Comment by jgw96** [comment]
_From @axalon on November 13, 2016 3:45_

Ah, someone on the Ionic forums pointed out that it's from not having the latest version of Ionic CLI

Just had to do a **npm install -g ionic**

**Comment by jgw96** [comment]
_From @MELAS007 on November 14, 2016 13:2_

i removed the new ionic i re-install ionic version 2.1.1 and i got this when i did ionic serve -l:
Error: ENOENT: no such file or directory, open 'D:\Mobile apps\test\push2\www\index.html'

when i did this : ionic start push2 blank -v2

Any help please.

**Comment by same07** [comment]
check this https://forum.ionicframework.com/t/ionic-serve-for-ionic-2/67886/2

**Comment by pickupman** [comment]
Updating the ionic CLI fixed this issue for me as well. The commands removed from `package.json` was done at https://github.com/driftyco/ionic2-app-base/commit/fbc66b6d5fa6c8d06eda1d4dc4cd812628a1b830#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
