### ISSUE TITLE
Generated icons not being recognized by Android Emulator or Devices

### ISSUE THREAD

**Issue by xke** [ionic-team/ionic-cli#1683]
#### Short description of the problem:

I tried to update the default Robot icon, and it didn't quite work.

#### What behavior are you expecting?

Running "ionic resources --icon" with a new image file, and then rebuilding will make the new icon appear.

**Steps to reproduce:**
1. "ionic resources --icon" on new image file
2. ionic build android
3. ionic run android

Bug is that it's still the default Robot icon.

Turns out that the icons in the <code>platforms/android/res/mipmap-*</code> folders are still the default Robot thing, and are the ones being used. I had to manually replace those files with new files in order to get the expected behavior to happen.

**Post the output of `ionic info` below please**

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.44
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by morisan** [comment]
I am also experiencing this problem.
`cordova -v #6.4.0` 
`ionic -v #2.1.8` 

Both of these have the stock Cordova robot icon.
`./platforms/android/res/mipmap-*/icon.png`
`./platforms/android/res/drawable-port-*/screen.png`

I did notice that the correct files are being written to:
`./res`
, and are seemingly unused.

**Comment by xke** [comment]
I just realized that another workaround is:
<code>cordova build --release android</code>

(via: https://ionicframework.com/docs/guide/publishing.html)

So the bright side is that the actual release APK has the correctly updated icon & splash screens. 

The confusion is that during the pre-release testing, it's not working as expected.

**Comment by morisan** [comment]
Thanks 👍  
Hadn't gotten that far since dev kept breaking ;-)

**Comment by cleever** [comment]
There are breaking changes in Cordova 6.0.0 release:
https://cordova.apache.org/announcements/2016/10/24/android-release.html

> Move icons from drawable to mipmap

**Comment by vijaydeep93** [comment]
worked by removing android platform and reinstalling using `ionic platform add android@latest`

**Comment by ZiFFeL1992** [comment]
Solved on `cordova-android@6.1.0` 👍

**Comment by xke** [comment]
@ZiFFeL1992  Is 6.1.0 already available? I tried `cordova platform update android` and ` npm install -g cordova@latest` and am still on the 6.0.0 version.

**Comment by ZiFFeL1992** [comment]
Steps:
```
Ionic rm platform android
Ionic add platform android
```

If it doesn't work add `@6.1.0` before android on add command.

**Comment by xke** [comment]
Ok, thanks for the tips @ZiFFeL1992 !

It worked with `cordova platform update android@6.1.0`

```
$ cordova platform version android
Installed platforms:
  android 6.1.0
  ios 4.1.1
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0

```

**Comment by 0x1ad2** [comment]
@ZiFFeL1992 ionic rm and add are deprecated now please use

`ionic platform remove android`

and

`ionic platform add android`

**Comment by ZhuShouyu** [comment]
It still does not work for me on Android.
$ cordova platform version android
Installed platforms:
  android 6.1.0
  ios 4.3.1
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0
