### ISSUE TITLE
ionic browser referenced in ionic docs

### ISSUE THREAD

**Issue by cgsmith** [ionic-team/ionic-cli#1685]
#### Short description of the problem:

http://ionicframework.com/docs/cli/browsers.html Shows `ionic browser` commands even though the CLI has removed it

#### What behavior are you expecting?

Indication that the commands are old CLI commands or remove the page.

**Comment by cgsmith** [comment]
Perhaps have a reference or redirect to using the cordova plugin instead?

**Comment by the7th** [comment]
i agree. i tried ionic browser command a few times. there really should be a reference to the updated command.

    ionic plugin add cordova-plugin-crosswalk-webview
