### ISSUE TITLE
`ionic build` does not build all installed platforms, just iOS

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1691]
_From @kelvindart on November 16, 2016 11:0_

#### Short description of the problem:
When running `ionic build` on macOS when you have two platforms installed (iOS and Android), the build process seems to not build every platform, just iOS in this instance.

#### What behavior are you expecting?
When `ionic build` is run, it builds every platform. I am basing this behaviour on `cordova build` which, I am aware, does not have the Angular 2 specific build steps, but it then builds both the Xcode project, and Gradle Project one after the other.

I am expecting `ionic build` to build all platforms enabled.

**Steps to reproduce:**
1. After you have initiated a new repository, add both Android and iOS platforms: `ionic platform add ios && ionic platform add android`
2. Issue a build command: `ionic build`
3. Observe just iOS is built.

**Which @ionic/app-scripts version are you using?**
0.0.43

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
N/A

_Copied from original issue: driftyco/ionic-app-scripts#402_

**Comment by jgw96** [comment]
_From @kelvindart on November 16, 2016 12:1_

Just seen, this is an ionic-cli issue: https://github.com/driftyco/ionic-cli/blob/master/lib/ionic/build.js#L35-L39.

I thought Ionic just passes the arguments through to `cordova build` but the script above confirms it does not.

Cordova build script: https://github.com/apache/cordova-cli/blob/master/src/cli.js#L346-L351

**Comment by mirkonasato** [comment]
On a related note, suppose I create a mobile website / PWA without Cordova

    ionic start my-pwa --v2 --no-cordova

then if type `ionic build` I get

	my-pwa$ ionic build
	• You're trying to build for ios but don't have the platform installed yet.
	∆ Installing ios for you.
	Installing cordova-plugin-device
	Installing cordova-plugin-console
	Installing cordova-plugin-whitelist
	Installing cordova-plugin-splashscreen
	Installing cordova-plugin-statusbar
	Installing ionic-plugin-keyboard
	 Error: Command failed: cordova plugin add --save cordova-plugin-whitelist
	Error: Current working directory is not a Cordova-based project.

That doesn't really make sense. I'm not trying to build for iOS at all. Maybe `ionic build` should just build the web app?

**Comment by saurabhgupta050890** [comment]
Had the same issue on ver 2.2.1
