### ISSUE TITLE
Unable to parse Ionic Config file. Please make sure it is valid JSON (.ionic/ionic.config)

### ISSUE THREAD

**Issue by dragonfly95** [ionic-team/ionic-cli#1696]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
Unable to parse Ionic Config file. Please make sure it is valid JSON (.ionic/ionic.config)
Caught exception:
 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.module.exports.load (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config.js:14:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/stats.js:31:31)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/cli.js:3:18) 

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by lisaiceland** [comment]
I'm getting this same issue this very morning ;-(

**Comment by lisaiceland** [comment]
cleaned cache
uninstalled node 
re-installed node 6.9.1 LTS
npm config get prefix and made sure /usr/local

chown'd permissions to make sure:
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
sudo npm install -g ionic cordova

RUN & MESSAGE:
$ npm install -g ionic cordova
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic
/usr/local/lib
├── cordova@6.4.0 
└── ionic@2.1.12 

STILL GET ERROR when:
ionic info
or try to build with ionic start...

MESSAGE:
ionic info

Unable to parse Ionic Config file. Please make sure it is valid JSON (.ionic/ionic.config)
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.load (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config.js:14:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/stats.js:31:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by matejamateusz** [comment]
> CONFIG_FILE: '.ionic/ionic.config',
> To have a slash after the dot:
> 
> CONFIG_FILE: './ionic/ionic.config',

is the right answer thanks ;)

**Comment by finalxcode** [comment]
thanks

**Comment by seokochin** [comment]
Just delete {user}/.ionic/ionic.config.json and run ionic serve
It will be fixed.
Delete this from terminal.

**Comment by ramoncardena** [comment]
@seokochin solution worked like a charm! 

I also did everything before...uninstalling node, and so. But just deleting ionic.config was the solution. Keep in mind that the file is in your home folder, not in the folder where you have your app.

**Comment by thiagopa** [comment]
Thanks @seokochin This worked for me as well

**Comment by zeeshananjumjunaidi** [comment]
Comments were causing problem for me. it needs to be pure simple json structure like following:
` json
{
  "name": "ionic3-sample",
  "app_id": "",
  "type": "ionic-angular",
  "integrations": {
    "cordova": {}
  },
  "proxies": [
    { 
      "path": "/JSON",
      "proxyUrl": "http://192.168.1.123/JSON"
    }
  ]
}
`

**Comment by yudhaDitya** [comment]
thanks a lot @seokochin you save my time a lot..

**Comment by HeshamEG** [comment]
the easy way just delete file config.json located in C:\.ionic\config.json then ionic serve again and solved :dango:

**Comment by Vajidbaba** [comment]
Goto this path- C:/Users/{username}/.ionic find file (ionic.config) and delete that file.
