### ISSUE TITLE
ionic start myApp tabs hangs

### ISSUE THREAD

**Issue by NHKK** [ionic-team/ionic-cli#1698]
I followed the get started guide off of ionic website(http://ionicframework.com/getting-started/). I did the whole nine yards (uninstall cordova and ionic. Clear out the cache. Reinstall cordova at the latest version and reinstall ionic. But as soon as i do "ionic start myApp tabs" it just hangs after downloading the zip.

**Comment by aero1508** [comment]
Hi all!

Sorry for reliving an old post, but actually i have the same problem:

**Version:** Ionic 3
**Short description of the problem:** I'm trying to create a new ionic project and unfortunately the ionic start command hangs as following.

`c:\ionic> ionic start mysampleapp <blank | sidemenu | blank>`

After running the `ionic start mysampleapp <any template option>`, This should create a new ionic project.

**Steps to reproduce:**   run the command `ionic start mysampleapp <blank | sidemenu | blank>`

**What I see in the console**

```
c:\ionic>ionic start mysampleapp blank
√ Creating directory .\aeroapp1 - done!
√ Downloading and extracting blank starter - done!

? Would you like to integrate your new app with Cordova to target native iOS and Android? Yes
>>>>>>>>>>>IN THIS STEP, IONIC HANGS
```
I get the same result if i write No in the integration question.

**Which version are you using?**:
```
cli packages: (C:\Users\XXXXX\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:
    Node : v10.3.0
    npm  : 6.1.0
    OS   : Windows 10

Misc:
    backend : pro

```
**Other information:** I tried using the parameter --no-git but the result is the same.

Thanks for your feedback, good day!

**Comment by dwieeb** [comment]
@NHKK Did you resolve the issue? If so, please post the solution in case others are experiencing the same issue.
