### ISSUE TITLE
Ionic serve fails with fresh v2 install

### ISSUE THREAD

**Issue by Libbux** [ionic-team/ionic-cli#1700]
#### Short description of the problem:
After installing a fresh ionic 2 app using `ionic start new-app --v2`, running `ionic serve` fails with an error that repeats several times:

```
Caught exception:
 TypeError: undefined is not a function
    at Socket.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/npmScripts.js:39:49)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Steps to reproduce:**
1. Run `ionic start new-app --v2`
2. Attempt `ionic serve` inside the new project directory

**Post the output of `ionic info` below please**
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: macOS Sierra
Node Version: v0.12.7
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by lisaiceland** [comment]
i'm facing same issue.

**Comment by Libbux** [comment]
@lisaiceland Can you post the output of `ionic info`?

**Comment by lisaiceland** [comment]
Unable to parse Ionic Config file. Please make sure it is valid JSON
(.ionic/ionic.config)
Caught exception:
SyntaxError: Unexpected end of JSON input
at Object.parse (native)
at Object.load
(/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config.js:14:26)
at Object. (/usr/local/lib/node_modules/ionic/lib/utils/stats.js:31:31)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


[image: --]

Lisa Kristinardottir
[image: https://]about.me/lisa.kristinardottir
<https://about.me/lisa.kristinardottir?promo=email_sig&utm_source=email_sig&utm_medium=external_link&utm_campaign=chrome_ext>


Thank You.
Lis

Regards,
Happy Analyzing, Developing, Managing & Launching Dreams Daily!

Bless. Ciao!

Lisa Kristinardottir (Lis) | Just Me
<http://lisakristinardottir.strikingly.com/> | Lisaiceland.com |
USAGains.com






<http://lisakristinardottir.strikingly.com/>




[image: --]

<http://about.me/lisa.kristinardottir?promo=email_sig>

**Comment by lisaiceland** [comment]
Can;'t run ionic at all.
I've checked & done chowns to make sure as well:

sudo uninstall -g ionic

sudo npm install -g ionic@latest
sudo npm install @ionic/app-scripts@latest

ionic info gets:

ionic info
Unable to parse Ionic Config file. Please make sure it is valid JSON
(.ionic/ionic.config)
Caught exception:
SyntaxError: Unexpected end of JSON input
at Object.parse (native)
at Object.load
(/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config.js:14:26)
at Object. (/usr/local/lib/node_modules/ionic/lib/utils/stats.js:31:31)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues




[image: --]

Lisa Kristinardottir
[image: https://]about.me/lisa.kristinardottir
<https://about.me/lisa.kristinardottir?promo=email_sig&utm_source=email_sig&utm_medium=external_link&utm_campaign=chrome_ext>


Thank You.
Lis

Regards,
Happy Analyzing, Developing, Managing & Launching Dreams Daily!

Bless. Ciao!

Lisa Kristinardottir (Lis) | Just Me
<http://lisakristinardottir.strikingly.com/> | Lisaiceland.com |
USAGains.com






<http://lisakristinardottir.strikingly.com/>




[image: --]

<http://about.me/lisa.kristinardottir?promo=email_sig>

**Comment by lisaiceland** [comment]
Jonathan hi:
Ok solved it!
I've updated it in this issue:
https://github.com/driftyco/ionic-cli/issues/*1696*

** #UPDATE 11/21/2016: Houston, we have a go woohoo!**
Ughhhh....kool finally can go back to work with Ionic 2!
OK: Found the fix here:
https://forum.ionicframework.com/t/ionic-command-not-work/19452/5You'llwant
to edit the file, .eg:
sudo nano /usr/local/lib/node_modules/ionic-app-lib/lib/config.js

or $ cd /usr/local/lib/node_modules/ionic-app-lib/lib/
$ atom . or $code . or whatever. Open the config.js file in the dir

then....change line 7 as it is if you install ionic@latest as of 11/21/2016:
CONFIG_FILE: '.ionic/ionic.config',
To have a slash after the dot:

CONFIG_FILE: './ionic/ionic.config',

Then save the file, and try running an ionic command:
ionic info or whatever Ionic CLI command you need to run!
Done.


Needs to be updated in the installation scripts to catch this and make it
part of the nightly builds.


[image: --]

Lisa Kristinardottir
[image: https://]about.me/lisa.kristinardottir
<https://about.me/lisa.kristinardottir?promo=email_sig&utm_source=email_sig&utm_medium=external_link&utm_campaign=chrome_ext>


Thank You.
Lis

Regards,
Happy Analyzing, Developing, Managing & Launching Dreams Daily!

Bless. Ciao!

Lisa Kristinardottir (Lis) | Just Me
<http://lisakristinardottir.strikingly.com/> | Lisaiceland.com |
USAGains.com






<http://lisakristinardottir.strikingly.com/>




[image: --]

<http://about.me/lisa.kristinardottir?promo=email_sig>

**Comment by erwinliong** [comment]
I get the same error with Ionic 2, too. Ionic1 project works fine, though.
I tried adding the '/' before the ionic/ionic.config but it does not work.

My system information:
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v0.12.2
Xcode version: Not installed

Any help, please? Thank you.

**Comment by tja4472** [comment]
@erwinliong I would update node to v6.9.1

http://ionicframework.com/docs/v2/setup/installation/

> To create Ionic 2 projects, you’ll need to install the latest version of the CLI and Cordova. Before you do that, you’ll need a recent version of Node.js. Download the installer for Node.js 6 or greater and then proceed to install the Ionic CLI and Cordova for native app development:

**Comment by erwinliong** [comment]
Ah.. Got it working now. Apparently, I had node installed in a couple of location and the old node.exe was still around.

Thanks for the great help, @tja4472 .
