### ISSUE TITLE
An error was encountered processing the command (domain=FBSOpenApplicationErrorDomain, code=1)

### ISSUE THREAD

**Issue by alvin-ho** [ionic-team/ionic-cli#1712]
Hi all, 

When I try to debug through emulator using command : 
**ionic run ios -lc --target="iPad-2"**

It returns an error as following:
An error was encountered processing the command (domain=FBSOpenApplicationErrorDomain, code=1):
The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)

It occurs on iPads simulators only but not iPhone emulators.

Any solutions? Many thanks!

Environment:
Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by lordgreg** [comment]
Hi @alvin-ho.

I'm currently having the exact same issue. Running the created project directly through Xcode works perfectly. The only issue I'm having is when starting that from CLI and, as you already found out, only on iPad-2 (iPad Air or iPad Air 2 works without any problems).

Have you found the source of the problem yet?

**Comment by jdat82** [comment]
Same here with `ionic run ios -l --target="iPhone-5, 9.3"`

Ionic info : 
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v7.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by luisnomad** [comment]
+1

**Comment by Bforsyth1234** [comment]
Same issue.

`global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.0.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 2.0.0

System:

    Node       : v6.9.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.1.0
    npm        : 3.10.8`


Going to change versions of cordova-cli and see if that helps.
