### ISSUE TITLE
Ionic run failing silently with Cordova 6.4

### ISSUE THREAD

**Issue by amuramoto** [ionic-team/ionic-cli#1715]
#### Short description of the problem:

As of Cordova 6.4, `ionic run ios --device` fails without printing an error. This only happens when the platform is added fresh with `ionic platform add ios`. 

It works as expected if `ionic run ios --device` is executed in a starter project with the default ios platform that is created as part of the starter.

For a vanilla Cordova project, `cordova run ios --device` works as expected, so this seem tobe specific to `ionic run` 

Everything works as expected with Cordova 6.3 and earlier. 

It also appears that the file structure created by Cordova 6.4 in `/platforms/ios/build` is different from what is created when `ionic start` adds the default ios platform: 

![screen shot 2016-11-21 at 3 50 22 pm](https://cloud.githubusercontent.com/assets/4483777/20579130/be41fa0a-b17f-11e6-91cd-1b7abf9238cb.png)

#### What behavior are you expecting?

`ionic run ios --device` should deploy the app to the device. If it fails, it should print some kind of error.

**Steps to reproduce:**

1. `ionic start myapp --v2`
2. `cd myapp`
3. `rm -rf platforms/ios`
4. `ionic platfom add ios`
5. `ionic build ios`
6. Open `myapp.xcodeproj` in Xcode and code sign
7. `ionic run ios --device`

**Post the output of `ionic info` below please**

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by shanesmith** [comment]
Seeing the same thing.

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```
