### ISSUE TITLE
Execution failed for task ':mergeDebugAssets'

### ISSUE THREAD

**Issue by yogeshlanjekar** [ionic-team/ionic-cli#1718]
I am converting my existing angular js web application to android using ionic. But while building it for android using command - **'ionic build android'**, I am getting below error. 

```
Execution failed for task ':mergeDebugAssets'.
> [www/lib/angular/angular-localization/angular-localization.min.js]  D:\AndroidApp\platforms\android\assets\www\lib\angular\angular-localization\angular-localization.min.js    [www/lib/angular/angular-localization/angular-localization.min.js] D:\AndroidApp\platforms\android\assets\www\lib\angular\angular-localization\angular-localization.min.js.gz: Error: Duplicate resources
```

I tried to remove _'D:\AndroidApp\platforms\android\assets\www\lib\angular\angular-localization\angular-localization.min.js'_ manually, but while building, this file gets generated automatically. What I am doing wrong? Please guide.

When I am using **'ionic serve'** command for testing purpose, my web application is working perfect.

**Comment by Aks6193** [comment]
HI were you able to fix this issue @yogeshlanjekar  i am facing the same issue

**Comment by wiggitamoo** [comment]
Same problem for me too, fyi @yogeshlanjekar

**Comment by sujit77** [comment]
I deleted the "platforms" folder and ran the build command again, which will app required folder before creating build.
It worked for me without error.

**Comment by AhmedHamedTN** [comment]
I think you can delete the **build** folder inside **www** and try again .. it might work .. good luck.
