### ISSUE TITLE
 There was an error with the spawned command: serve

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic-cli#1719]
I just decided to start developing with Ionic, but after a fresh installation as documented as described here:
http://ionicframework.com/docs/v2/getting-started/installation/

I got the following error:
```
c:\xampp\htdocs\app>ionic serve
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\home\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--"
npm ERR! node v6.5.0
npm ERR! npm  v4.0.2
npm ERR! path c:\xampp\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'c:\xampp\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'c:\xampp\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     c:\xampp\htdocs\npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve
```

What's wrong? I did also try @jthoms1 solution here: https://github.com/driftyco/ionic-cli/issues/1654

but the issue persists

**Comment by shouton** [comment]
obviously, the error caused, since path c:\xampp\package.json was not found.

check it.

**Comment by theunreal** [comment]
@shouton I created my project at `c:\xampp\htdocs\myproject` and I run my command from there, why would I create a package.json in my `c:\xampp\`?..

My package.json located at my project folder, `c:\xampp\htdocs\myproject`, the same place I run the command from. What's wrong? Why it tries reading the package.json from my previous folder?

**Comment by jthoms1** [comment]
You will need to execute the serve command from within the project base (the directory created by the `ionic start` command. According to your comments it is probably `c:\xampp\htdocs\myproject`. Thanks

**Comment by theunreal** [comment]
That's exactly what I did. I get this error when I run `ionic start` in `c:\xampp\htdocs\myproject`. I have no idea why it's looking for a `package.xml` outisde my project base...

**Comment by MAEVE007** [comment]
$ ionic serve -l
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
> ionic-app-base@ ionic:serve E:\Practice Projects\Ionic\angular2\myiapp1
> ionic-app-scripts serve "-l"
[08:44:14]  ionic-app-scripts 0.0.45
[08:44:15]  watch started ...
[08:44:15]  build dev started ...
[08:44:15]  clean started ...
[08:44:15]  clean finished in less than 1 ms
[08:44:15]  copy started ...
[08:44:15]  transpile started ...
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\Ionic_Framework\\nodejs\\node.exe" "C:\\Users\\Admin\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "-l"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! ionic-app-base@ ionic:serve: `ionic-app-scripts serve "-l"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-app-base@ ionic:serve script 'ionic-app-scripts serve "-l"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-app-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "-l"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-app-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-app-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Practice Projects\Ionic\angular2\myiapp1\npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve


This error is not resolving. I have tried the provided solutions. Please do help.

**Comment by pranay222** [comment]
I was having the issue. Now it's resolved, here's the secret:

While starting the app:
use '--v2'
ionic start myApp blank --v2

Then when you run ionic serve all should run fine!

**Comment by islamTaha12** [comment]
solved here:
https://github.com/driftyco/ionic-cli/issues/1480#issuecomment-294325881
