### ISSUE TITLE
ionic serve not working

### ISSUE THREAD

**Issue by dlemburg** [ionic-team/ionic-cli#1721]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Ionic serve not working. It was working great, now fails every time.

I've tried installing latest node, cordova versions, as well as deleting node_modules and then running npm install. Various tips on other github issues didn't get me any further.

This is the error message i'm getting:

```

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (node.js:348:7)
    at startup (node.js:140:9)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "--"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! ionic-app-base@ ionic:serve: `ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-app-base@ ionic:serve script 'ionic-app-scripts serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-app-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-app-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-app-base
npm ERR! There is likely additional logging output above.
```

[debug.zip](https://github.com/driftyco/ionic-cli/files/612169/debug.zip)

**Comment by br4nch** [comment]
I have a same problem. Any idea?

**Comment by dlemburg** [comment]
I tried a number of things, so I'm not exactly sure which one worked (updated npm, node, cordova cli, etc). But it started working again directly after restarting my computer. I'm skeptical that this actually temporarily fixed the issue, but it may be worth a shot

**Comment by br4nch** [comment]
I just fixed it. Updated npm, node, cordova and ionic work for me.

**Comment by MELAS007** [comment]
@br4nch - How did you update?

**Comment by br4nch** [comment]
i don't quite remember what i did but reinstall always do the trick. Good luck @MELAS007

**Comment by oikonomopo** [comment]
Try `ionic serve --address=127.0.0.1`!
