### ISSUE TITLE
Just letting you know

### ISSUE THREAD

**Issue by YANOUSHek** [ionic-team/ionic-cli#1729]
> ionic state restore
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME="allegroapproval"
cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME="allegroapproval" --variable DEEPLINK_SCHEME="https" --variable DEEPLINK_HOST="allegroapproval.com" --variable ANDROID_PATH_PREFIX="/"
cordova plugin add phonegap-plugin-push
cordova plugin add cordova-plugin-inappbrowser
Caught exception:
 undefined

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by YANOUSHek** [comment]
I was just having a joke about the

```
Caught exception:
undefined
```

and a sentence below which asked me to submit this issue. I bet you can get a lot of info from this message. Maybe, when something fails it should automatically add some information to the output so you can get more info about the error? Just thinking out loud.

Can anyone close this? I seem to not be able to.

**Comment by vjanssens** [comment]
Seems to be related to #1673.
