### ISSUE TITLE
Why install plugins hook is reading the package.json instead of the config.xml

### ISSUE THREAD

**Issue by Maxwell2022** [ionic-team/ionic-cli#1732]
#### Short description of the problem:
All the (Cordova) plugins are saved and configured in the `config.xml`. When running `cordova prepare` cordova is looking in this config.xml to install the correct version of the plugins with the correct build options.

However it looks like when running `cordova platform add android`, it's then running the `hooks/after_platform_add/010_install_plugins.js` which is reading another source of information: `package.json` where there is no build options specified.

https://github.com/driftyco/ionic-cli/blob/master/lib/hooks/after_platform_add/010_install_plugins.js

For instance, Facebook plugin is requiring the APP_ID and APP_NAME to be set. It doesn't make sense to add this variables in the `package.json` because the `cordovaPlugins` is generated.

#### What behavior are you expecting?

I think `hooks/after_platform_add/010_install_plugins.js` should look at the `config.xml` to get the proper plugin configuration.

**Steps to reproduce:**
1. cordova prepare
2. cordova platform remove android
3. cordova platform add android

```
Total time: 1.445 secs
Dependent plugin "cordova-plugin-dialogs" already installed on android.
Installing "cordova-plugin-facebook4" for android
Failed to install 'cordova-plugin-facebook4':Error: Variable(s) missing: APP_ID, APP_NAME
    at /xxxx/v6.9.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:362:23
    at _fulfilled (/xxxx/v6.9.0/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/xxxx/v6.9.0/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/xxxx/v6.9.0/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /xxxx/v6.9.0/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/xxxx/v6.9.0/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Variable(s) missing: APP_ID, APP_NAME
```

**Comment by biesbjerg** [comment]
IMO, it's also confusing to keep list of platforms and plugins in both package.json and config.xml.

Can't it be dropped from package.json now that Cordova-cli supports it via config.xml?

**Comment by NoNameProvided** [comment]
This always cause confusion for the new members in our team. Everyone try to install plugins with `cordova add xy --save`, but in our docs, we embrace the usages of `ionic state restore` so for project setup, which won't read the config.xml leading to broken builds because of missing plugins. So now we have to keep config.xml and the package.json consistent all the time by copy pasting values.

As this is a breaking change I would really like to see this in 3.0 instead of 4.0 or whatever x.0

Shameless mentioning cc @mlynch @adamdbradley 

I am up for creating a PR, just give me some guidance on the how to.

**Comment by dwieeb** [comment]
We no longer use this hook, `ionic state` is no longer a thing, and we recommend using Cordova to manage platforms and plugins. It's good at it now. Closing! 😄
