### ISSUE TITLE
Ionic issue while building the app,

### ISSUE THREAD

**Issue by dileep017** [ionic-team/ionic-cli#1733]
Hi Everyone,

Can someone help me in building the ionic app for iOS,While i ran the command ionic build ios i got the below error,

The following build commands failed:
	CompileC /Users/digaddam/Library/Developer/Xcode/DerivedData/pradeep-bfgsgcpzuaeypfaiarathcugylpq/Build/Intermediates/pradeep.build/Debug-iphonesimulator/pradeep.build/Objects-normal/x86_64/AppDelegate.o pradeep/Classes/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/digaddam/Library/Developer/Xcode/DerivedData/pradeep-bfgsgcpzuaeypfaiarathcugylpq/Build/Intermediates/pradeep.build/Debug-iphonesimulator/pradeep.build/Objects-normal/x86_64/MainViewController.o pradeep/Classes/MainViewController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/digaddam/Desktop/pradeep/platforms/ios/cordova/build-debug.xcconfig,-workspace,pradeep.xcworkspace,-scheme,pradeep,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/digaddam/Desktop/pradeep/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/digaddam/Desktop/pradeep/platforms/ios/build/sharedpch

ionic info:
Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v7.2.0
Xcode version: Xcode 8.1 Build version 8B62

And tried to install ,npm install -g ios-deploy and got the below errors,

sudo npm install -g ios-deploy
Password:
npm WARN lifecycle ios-deploy@1.9.0~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.9.0 ./src/scripts/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/digaddam/npm-debug.log

Please let me know what to do :(

**Comment by vjanssens** [comment]
Your first issue seems to be related to #1060. 
Please try below code and see if it helps.
```
ionic platform remove ios
ionic platform add ios
```

For your second issue, the comment by @Vgerris may be of help:
https://github.com/npm/npm/issues/10055#issuecomment-180101705

**Comment by karlpatrickespiritu** [comment]
also having this issue. tried the `add/remove` method. but after, still having the issue.

**Comment by VGerris** [comment]
If you have a problem, please describe exactly what it is and what you tried. Please follow the instructions that people posted already and then be specific when that didn't help. Thanks

**Comment by mayurpanchal24111986** [comment]
I am also facing same issue when i have upgrade my OS form IOS 9 to 10 and Update Xcode version from 7.2 to 8, after lots of research i have find solution and based on that solution i have write a blog.

http://satvasolutions.com/microsoft-visual-studio-tools-for-apache-cordova-build-failed-error-code-65-for-command-when-using-xcode-8-and-ios-10/
