### ISSUE TITLE
"Ionic Serve" command not working

### ISSUE THREAD

**Issue by abissa76** [ionic-team/ionic-cli#1742]
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
There was an error serving your Ionic application: TypeError: Cannot read proper
ty 'hasOwnProperty' of undefined
    at C:\Users\arvind\AppData\Roaming\npm\node_modules\ionic\lib\utils\npmScrip
ts.js:17:31
    at _fulfilled (C:\Users\arvind\AppData\Roaming\npm\node_modules\ionic\node_m
odules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\arvind\AppData\Roaming\npm\node_modul
es\ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\arvind\AppData\Roaming\npm\node
_modules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\arvind\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.j
s:557:44
    at flush (C:\Users\arvind\AppData\Roaming\npm\node_modules\ionic\node_module
s\q\q.js:108:17)
    at process._tickDomainCallback (node.js:381:11)

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by SaadeMotion** [comment]
Rename your `ionic.project` file at the root of app, to `ionic.config.json`

If problem persists, delete your `node_modules` folder, and run `npm install` again.

If problem persists again, you are a unlucky guy (joke), then update your ionic-cli to the latest version using `npm install ionic-cli@latest`

**Comment by abissa76** [comment]
i have renamed the "ionic.project" to "ionic.config.json"
but the problem persist except this message is removed from the above error **"ionic.project has been renamed to ionic.config.json, please rename it."**

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by osmanra2** [comment]
Not working for me either

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by ronaldoxgh** [comment]
some ionic versions use 'ionic,project' file, other versions use 'ionic.config.json'
both files have the same mission, but 'ionic.project' always have precedence against 'ionic.config.json'
it doesnt matter if you delete 'ionic.project' file, when the build process starts, the file is created again with no content, and no proxy entries within.
my solution?
i kept both files with the same content
