### ISSUE TITLE
tabs template and sidemenu template are not working on Windows

### ISSUE THREAD

**Issue by tecsined** [ionic-team/ionic-cli#1745]
Windows 10
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v0.12.7
Xcode version: Not installed

Projects-> "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
}

Caught exception:
 TypeError: undefined is not a function
    at Socket.<anonymous> (C:\Users\olivad\AppData\Roaming\npm\node_modules\ionic\lib\utils\npmScripts.js:39:49)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)

**Steps to reproduce:**
1. Create a sidemenu or tabs application using version 2
2. Run ionic serve 

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by SaadeMotion** [comment]
![image](https://cloud.githubusercontent.com/assets/14329460/20809925/b63236e8-b7ee-11e6-9356-963cb4e2e3c9.png)

fine here...

**Comment by tecsined** [comment]
@SaadeMotion is that a Mac or Windows ? It is till not working on W10

**Comment by tja4472** [comment]
You need to update node to 6.9.1
https://nodejs.org/en/

**Comment by JuanLuisGarciaBorrego** [comment]
I have installed node v7.2.0 and it does not work
