### ISSUE TITLE
ionic serve --address not working

### ISSUE THREAD

**Issue by Uriel96** [ionic-team/ionic-cli#1748]
It seems like the newer version of ionic (2.1.12) doesn't work as expected in the cli.
Last version of ionic 2 (don't remember with exactitude the version). 
When I used: 
```
ionic address
```
it showed me whether I wanted it on localhost or a chosen ip address, but now it doesn't show anything.
Then I try using:
```
ionic serve --address AN_IP_ADDRESS
```
and i get the following error:

```
Uhoh. Got error listen EADDRNOTAVAIL 192.168.15.2:35729 ...                 Error: listen EADDRNOTAVAIL 192.168.15.2:35729
    at Object.exports._errnoException (util.js:1026:11)                             at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1244:19)                                             at listen (net.js:1293:10)
    at net.js:1403:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)                  at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 192.168.15.2:8100
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1244:19)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```
I have searched in other posts, but without success.
Please help me, it's getting frustrating because I want to test it on the browser of my phone.

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by mayurdhanokar8527** [comment]
In my case port `8100` (ionic uses it as default) was blocked, you can either remove binding from `8100` before `ionic serve` or use this command to run ionic on another port `ionic serve -p 8080` or any other port that is not bound with any program

**Comment by Uriel96** [comment]
Sure @jthoms1, it is:
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.8.0
Xcode version: Not installed

And  @mayurdhanokar8527 I already  tried that but it still doesn't work :cambodia:

**Comment by Mokto** [comment]
+1. 

I'm using a docker container to run an android app so my container IP is different than my host IP.


```bash
$ ionic run android -lcs address                                                                                

Addresss XXX.XX.XX.XX not available.

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed
```

Seems to come with this commit but I'm not sure : https://github.com/driftyco/ionic-cli/commit/70531bc

Can you please allow us to run apps specifying the address we want ?

**Comment by tamerbak** [comment]
ionic address returns nothing..
```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.9 
OS: OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by ZebGirouard** [comment]
I also have this issue...hope this helps?
