### ISSUE TITLE
deviceready event not triggered when running --livereload

### ISSUE THREAD

**Issue by cj** [ionic-team/ionic-cli#1755]
running `ionic run --device`, `deviceready` is triggered.
running `ionic run --device -l`, `deviceready` is **NOT** triggered.

This seems like it's a bug.

```
± ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by cj** [comment]
It might not be deeper than not triggering `device ready`. The code below works just fine with `ionic run --device` but when you use `ionic run --device -l` nothing happens.

```javascript
import { StatusBar, Keyboard } from 'ionic-native'

setTimeout(function () {
  if (window.StatusBar) {
    Keyboard.disableScroll(true)
    StatusBar.overlaysWebView(false)
  }
}, 300)
```

**Comment by cj** [comment]
So it's both things, `deviceready` is never triggered and `ionic-native` doesn't work.

**Comment by Maziar-Fotouhi** [comment]
For me, `deviceready` is not triggered regardless of `livereload`. I have realized that **cordova platform is not available** even on an actual device, when you update `ionic-app-scripts` to version **0.0.42 and above**.
