### ISSUE TITLE
CLI help leads to wrong usage of platform command

### ISSUE THREAD

**Issue by simonech** [ionic-team/ionic-cli#1758]
#### Short description of the problem:
When you type `ionic --help` the help specific to the `platform` command just mentions `<platform>` and `[options]`. 

In reality the usage is more complicate:

1. just calling `ionic platform` lists the available platforms
2. to add a platform the `add` verb must be specified `ionic platform add <platform>`
3. you can use the `rm` to remove a platform

#### What behavior are you expecting?

See a better help that mentions the 2 other verbs.

Also the `plugin` command has a similar problem: it shows that you have to use `plugin add` but doesn't show the `rm` verb.

**Comment by dwieeb** [comment]
This has been improved in the latest version.
