### ISSUE TITLE
Error Handling and Reporting with regards to WSOD

### ISSUE THREAD

**Issue by softroots** [ionic-team/ionic-cli#1761]
I am currently working with Ionic v2 RC3 and Cordova, and from time to time I would run into the "White Screen of Death" WSOD, which (in my case) was the result of inserting other Internet sample code that no longer works with the newer Angular, Ionic, or 3rd party libraries (that have been changing frequently). 

The Ionic error reporting is exceptionally good. However, one short-coming is in its ability to report when an module import is no longer valid (either because it's been renamed or the path is wrong). 

This can leave you with a WSOD, and can be seen using the following:

import 'rxjs/add/operator/'; 

This should be identified and reported by the error handler.

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.
