### ISSUE TITLE
Unable to parse Ionic Config file

### ISSUE THREAD

**Issue by mai852852** [ionic-team/ionic-cli#1762]
Unable to parse Ionic Config file. Please make sure it is valid JSON (.ionic/ionic.config)
Caught exception:
 SyntaxError: Unexpected token

**Comment by jthoms1** [comment]
What command are you executing when you receive this error?  Also can you provide output from `ionic info`? Thanks

**Comment by clarzou** [comment]
I am currently facing the same issue by running all ionic commands (also ionic info). It happened suddenly.

**Comment by nabinkumarn** [comment]
In
C:\Users\nabin\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\config.js

change
'.ionic/ionic.config',
to
'./ionic/ionic.config'

this link helped me. [http://stackoverflow.com/questions/40776922/unable-to-parse-ionic-config-file-please-make-sure-it-is-valid-json/40805175#40805175](http://stackoverflow.com/questions/40776922/unable-to-parse-ionic-config-file-please-make-sure-it-is-valid-json/40805175#40805175)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.  Some more info on your system setup could help me track down why this might be occurring.

**Comment by LeonardoRossetti** [comment]
Heey.. thanks @nabinkumarn ... this solution is perfect... i'll go back to work now!

**Comment by plauzul** [comment]
Just Delete C:/Users/{username}/.ionic/ionic.config
