### ISSUE TITLE
Error while starting the new app with ionic cli

### ISSUE THREAD

**Issue by Ramesh209025** [ionic-team/ionic-cli#1774]
$ ionic start --v2 myapp slidemenu
Creating Ionic app in folder C:\Users\ee209025\Desktop\New folder\myapp based on                slidemenu project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:569:26)
Error Initializing app: Error: read ECONNRESET
 Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:569:26)
Caught exception:
 Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:569:26)

i'm not behind  proxy ,but still facing issue ..please help to resolve this.

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info`? Thanks, this should help in troubleshooting.  Also could you try access that url from a web browser on your machine?

**Comment by julianhansby** [comment]
I also have the same issue (and I am not behind a proxy)

ionic info:

@ionic/cli utils : 1.92
ionic (ionic cli) : 3.9.2

System:
Node: v6.11.1
npm: 3.10.10
OS: windows 7

**Comment by Joselonia** [comment]
Same issue: 
ionic info:
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-plugin-proxy : 1.4.6
    @ionic/cli-utils        : 1.9.2
    ionic (Ionic CLI)       : 3.9.2

System:
    Node : v6.11.2
    npm  : 3.10.10 
    OS   : Linux 3.19
I'm behind a proxy and everything works ok with npm (ie. npm install -g ionic cordova) . From my browser I can download the resource without any problem.

**Comment by dwieeb** [comment]
The Ionic CLI must be configured separately to work with a proxy: https://github.com/ionic-team/ionic-cli#using-a-proxy

**Comment by Joselonia** [comment]
Same issue with the config related in:  https://github.com/ionic-team/ionic-cli#using-a-proxy. 
Npm works ok, but ionic-cli doesn't connect.
Is possible to get any help here? As I see after the comment, dwieeb close the issue. May be this is not the place where I should look for help.
Thanks.

**Comment by dwieeb** [comment]
@Joselonia haven't been able to reproduce, but you're not the first person to mention proxying broke with CLI 3.9.x. 

You tried this example? `HTTP_PROXY=https://internal.proxy.com ionic start`

**Comment by Joselonia** [comment]
Yes, I tried, but same issue. My intention was not to be rude with my comment, I just ask if someone else (maybe stackoverflow user ) was able to solve this issue and get that reference.
Should I downgrade ionic-cli? in that case do you know what version should I try?
Thanks

**Comment by dwieeb** [comment]
@Joselonia I didn't take it as rude 😄 These folks are getting the same issue: https://github.com/ionic-team/ionic-cli/issues/2317#issuecomment-325858877

**Comment by Joselonia** [comment]
Got It! 
I will downgrade to 3.3.0.
Thank you!

**Comment by julianhansby** [comment]
Let me know how this goes gents, because if the downgrade does indeed work, then I will gladly do the same (in an attempt to get mine to work).

**Comment by Joselonia** [comment]
After reinstall the last version (ionic-cli 3.9.2) and using: PROXY=https://internal.proxy.com ionic start
finally works for me. I use:"PROXY=https://internal.proxy.com ionic start" instead of "HTTP_PROXY=https://internal.proxy.com ionic start". 
So the recommended command without the "HTTP_" token works for me.
I hope it will be useful for someone else.
Thanks, and good luck.

**Comment by techogate** [comment]
Thanks for the 'PROXY' env var tip. However, that changes my error from:
```
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
× Downloading - failed!
Error: connect ETIMEDOUT 192.30.253.112:443
```
to 
```
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
× Downloading - failed!
Error: unable to verify the first certificate
```

My company's proxy rewrites ssl certs. For npm, I can whitelist untrusted certs (cafile) and/or turn of strict ssl  checking (strict-ssl) using npm config. **How can I do either for ionic-cli / cli-plugin-proxy?**

I'm on win 7 pro 64 bit:
>node -v
```
v6.11.2
>npm ls -g -depth 0
c:\nvm_nodes\nodejs
+-- @ionic/cli-plugin-proxy@1.4.6
+-- ionic@3.9.2
`-- npm@4.2.0
```

Thanks in advance.

**Comment by dwieeb** [comment]
@techogate This was missing functionality--I just added it.

Would you mind testing?
Steps:
```
$ npm i -g ionic@canary`
$ ionic config set -g ssl.cafile /path/to/cafile
$ ionic start
```

(You'll still need your `PROXY` env variable).

**Comment by techogate** [comment]
@dwieeb, many thanks, that worked first time. 

( FTR, As of writing, ionic@canary gets you ionic@3.10.0-alpha.b9cee01b)

**Comment by dwieeb** [comment]
@techogate Thank you so much for testing!

**Comment by anuoluwapo** [comment]
please i need you guys help. am unable to start new ionic4 app, am getting this error:
npm ERR! path C:\ionic4App\myNewApp\node_modules\.staging\typescript-2a8702e5\lib\ru\diagnosticMessages.generated.json

thanks in advance.

**Comment by dwieeb** [comment]
@anuoluwapo Please create a new issue and fill out the template.
