### ISSUE TITLE
ionic2 ios splash blank screen

### ISSUE THREAD

**Issue by finalxcode** [ionic-team/ionic-cli#1776]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:

after i use ionic template `blank` to reproduce a new app, when i run ios simulator, the simulator appears 2s~4s blank screen before app load.

#### What behavior are you expecting?

i expect there is not blank screen before app load.

**Steps to reproduce:**

```
1.ionic start myapp blank --ts --v2
2.ionic platform add ios
3.ionic run ios
```

**Post the output of `ionic info` below please**

 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.4.0
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

my config.xml:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="com.ionicframework.k100whysionic829613" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>K100WhysIonic</name>
  <description>An awesome Ionic/Cordova app.</description>
  <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
  <content src="index.html"/>
  <access origin="*"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>
  <allow-intent href="geo:*"/>
  <platform name="android">
    <allow-intent href="market:*"/>
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
  </platform>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="SplashMaintainAspectRatio" value="true"/>
  <preference name="FadeSplashScreenDuration" value="300"/>
  <preference name="ShowSplashScreenSpinner" value="false"/>
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar"/>
  </feature>
</widget>
```

after few hours, i fixed it as follows:

add
 ```
<preference name="AutoHideSplashScreen" value="false" />
<plugin name="cordova-plugin-splashscreen" spec="~4.0.0"/>
```

 in your config.xml， because when you don't set "AutoHideSplashScreen" false, ios default  "AutoHideSplashScreen" is true, now i'm not sure this is a correct way to fix it, any advise will be appreciated?

**Comment by jaonhe** [comment]
i have same issue!

ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.4.0
Xcode version: Not installed

**Comment by Fdom92** [comment]
i have the same issue on Android. My ionic info:

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.6
Node Version: v6.9.1
Xcode version: Not installed

Im trying to add a splashscreen but even with the png generated this blank screen appears, and after a few seconds my app start.

**Comment by Abineshlal** [comment]
Try to run the code with --prod flag. Below is the complete command,
ionic cordova run <platform> --prod

eg: ionic cordova run android --prod

**Comment by newuser44** [comment]
Did this get fixed?  I have an issue with the white screen on Android.  I tried a prod build and still see a white screen for 4-5 seconds.  On Android I don't have a splash screen. 
Can't figure out how to get rid of the white screen before the apps loads. ????

**Comment by dwieeb** [comment]
Your `config.xml` is missing quite a bit of default configuration from our starters: https://github.com/ionic-team/starters/blob/master/integrations/cordova/config.xml

It will need to be properly configured to see a splash screen while the app loads. I'm closing this issue as it's not an issue with the Ionic CLI.
