### ISSUE TITLE
ionic state restore shows caught exception message of "undefined"

### ISSUE THREAD

**Issue by KinsonDigital** [ionic-team/ionic-cli#1780]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
I had a pulled down code base of a company project that a fellow employee had.  I used the ionic command of "ionic state restore" to pull down all of the plugins via the package.json, and all of the plugins worked fine except this one.  Unfortunately this only shows this uninformative message of undefined that that's it.  I am new to ionic so I don't know if there is some kind of log file I can reference for more information for you guys.  This isn't a show stopper for me.  All I was doing was poking around and I tried out the command and this was the result.

Here is the result:

cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-console
cordova plugin add cordova-plugin-whitelist
cordova plugin add cordova-plugin-splashscreen
cordova plugin add cordova-plugin-statusbar
cordova plugin add ionic-plugin-keyboard
cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-actionsheet.git
Caught exception:
 undefined

#### What behavior are you expecting?
I was expecting for it to pull down the actionsheet plugin.

**Steps to reproduce:**
1. Goto project folder
2. Run ionic command => ionic state restore
3. Watch the ninja exception in all its glory.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by ryanjohnstone** [comment]
Having the same issue but occurs when trying to restore the first plugin which is cordova-plugin-whitelist

**Comment by mapierce** [comment]
Having the same issue. It's the same as you @ryanjohnstone I've tried switch the order of the plugins, but it always trips up at the first one

**Comment by rlindgren** [comment]
@ryanjohnstone and @mapierce,
I was having the same issue as the two of you, so I tried installing the plugins manually (outside the `ionic state restore` wrapper) by running `cordova plugin add cordova-plugin-whitelist` directly.  This way I could see the actual exception.

For me, it was that the Android SDK on this machine was not up-to-date and I hadn't accepted the license agreement.  I had previously added the android platform on a different machine with compatible Android SDKs, so restoring on this machine failed for that reason.  `ionic state restore` apparently doesn't do a very good job of passing along that exception...

If this is same for you, or for anyone else who comes across this, easy fix is to run `android` in a terminal and install the required platform (24 for me, at time of writing) from the Android SDK Manager window that pops up, then try the command again.
