### ISSUE TITLE
resources not being included inside platform/android

### ISSUE THREAD

**Issue by chrisbenseler** [ionic-team/ionic-cli#1786]
After upgrade ionic-cli and cordova to latest, the following behaviour started:

- remove android platform (ionic platform add android)
- generate icons and splash (ionic resources android)
- add android platform (ionic platform add android)
- the platforms/android/res/ folder does not contain the generated resources (placed in resources/android/splash and resources/android/icon), but it has the default cordova logo/splash
- a res/ folder is created in the root of the project.

I guess that the 'platform add' is not copying the res/ directory to the proper path.

My Ionic info

Your system information:

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.4.0
Xcode version: Not installed

```

**Comment by vjanssens** [comment]
I can confirm something strange is going on. 

After running `ionic resources` the proper icon and splash files are created in the `resources/{platform}` folders. 

After that, I ran `ionic run android --device`, build script starts, app gets deployed to the phone but also a /res folder with android icons was created in the root of the project. I don't think that should happen.

**Comment by chrisbenseler** [comment]
@vjanssens I downgrade my cordova back to the 6.3.1, it started to work properly now. I think this is a bug related to this version.

`sudo npm install -g cordova@6.3.1`

**Comment by Alberick0** [comment]
I'm having the same issue on windows, after upgrading everything, I tried downgrading to 6.3.1 as @chrisbenseler did and it's started to work as expected.

**Comment by rallu** [comment]
Same issues with mac. Downgraded to 6.3.1 and issue didn't go away.

```
Cordova CLI: 6.3.1 
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: OS X El Capitan
Node Version: v7.2.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by teerasej** [comment]
The issue still here. Both splash screen and icon doesn't included in Android's `res` folder

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jbfm21** [comment]
I'm having the same issue and  when downgrading cordova to 6.3.1 work as expected. So, the issue still here.

**Comment by jbfm21** [comment]
To solve the problem with cordova version 6.4.0

ionic platform rm android
ionic resources android
ionic resources ios
ionic platform add android@latest
