### ISSUE TITLE
Gradle error to download when execute ionic build android

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1800]
_From @PterPmnta on December 20, 2016 5:12_

### I am try to compile an new project using command ionic build android, but i get this error:

```
C:\Users\pedromiguel\aplicacionesIonic\sqliteTest>ionic build android
Running command: "C:\Program Files\nodejs\node.exe" C:\Users\pedromiguel\aplicacionesIonic\sqliteTest\hooks\after_prepare\010_add_platform_class.js C:\Users\pedromiguel\aplicacionesIonic\sqliteTest


add to body class: platform-android

ANDROID_HOME=C:\Users\pedromiguel\AppData\Local\Android\sdk

JAVA_HOME=C:\Program Files\Java\jdk1.8.0_101

Subproject Path: CordovaLib



FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.2.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.2.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

###System info

```
C:\Users\pedromiguel\aplicacionesIonic\sqliteTest>ionic info

Your system information:

 ordova CLI: 6.4.0
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v5.5.0
Xcode version: Not installed
```

I do it all answer in that question, but dont work. If anyone know some solution, help me.

_Copied from original issue: driftyco/ionic#9718_

**Comment by jgw96** [comment]
_From @jayeshanandani on December 20, 2016 18:2_

Please try to use Node LTS (6.9.2) and also this seems more of an android issue rather than an ionic issue.  Just looking at your error messages:

`Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap`

This lines should help you resolve that. Please ask at `StackOverflow` or `Ionic Support Forums`.

**Comment by jgw96** [comment]
_From @PterPmnta on December 20, 2016 22:59_

@jayeshanandani  I ask in StackOverflow, but the same answer don't work for me, but i don't in ionic forum yet.

**Comment by tusharkkumar** [comment]
**fix is here** (FOR WINDOWS ONLY)

I am facing the same problem of Build then i finally found out the solution.<br><br>


**SOLUTION**<br>
So You must have the Android Api 23 in order for this command to work.<br>
Error of Daemon process will be solve after installing the Api 23 and extra <br>build tools and run command <br>
COMMAND : cordova build android --release<br>
I am sure this fix would help you to solve the problem.


**STEPS**<br>
1. First check the version of android through this COMMAND:
   cordova platform help <br>
2. Run the build command after installing the Api 23 and extra build tools.<br>
3. If Even this not work then Try add the variable in the <br>
 Environment variables > System variables > <br>
 add _JAVA_OPTIONS and value = -Xmx512M

Then Run cordova build android --release

BUT FIRSTLY SET UP THE ENVIRONMENT VARIABLES <br>
[Environment Variable setup Image][2]<br>
[android API 23][1]


**COPY FROM HERE** <br>
ENVIRONMENT VARIABLES:-

1. **USER VARIABLES**<br>
 **PATH** <br>
 C:\Ruby23\bin;C:\Users\kumar\AppData\Roaming\npm;C:\ANDROID_SDK\tools;%SystemRo
 ot%\system32; %SystemRoot%; %SystemRoot%\System32\Wbem;


2.  **SYSTEM VARIABLES** <br>
  **ADD NAME AND VALUE** <br>
  2.1  **_JAVA_OPTIONS**   -Xmx512M <br>
  2.2  **ANDROID_HOME**    C:\ANDROID_SDK <br>
  2.3  **PATH** -> <br>
 	C:\ProgramFiles\Java\jdk1.8.0_60\bin;C:\ProgramFiles\nodejs;C:\Gradle\gradle-4.0\bin;C:\ANDROID_SDK\tools;%SystemRoot%\system32; %SystemRoot%; %SystemRoot%\System32\Wbem;%SystemRoot%\system32; %SystemRoot%; %SystemRoot%\System32\Wbem;


  [1]: https://i.stack.imgur.com/wLI0J.png
  [2]: https://i.stack.imgur.com/M5InU.png
