### ISSUE TITLE
Ionic Serve is not working

### ISSUE THREAD

**Issue by Varras** [ionic-team/ionic-cli#1810]
#### Short description of the problem:
When I run:
ionic serve 
it opens the browser and I cannot type Ionic Server Commands in console, like:
```
restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

**Post the output of `ionic info` below please**
 ordova CLI: 6.4.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.1
Xcode version: Not installed

**Comment by DILEEP-YADAV** [comment]
Same issue ! Here 
![ionic issue](https://cloud.githubusercontent.com/assets/8583769/21481050/8018d3c4-cb89-11e6-9585-faf9e93e2756.PNG)

**Comment by ch-weiss** [comment]
I have the same issue. No error shown, App is being served but no commands possible.

System information:
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by DILEEP-YADAV** [comment]
Please Uninstall app related software and clear cache. install all latest . I hope , it will help you. 
Thank you.

**Comment by ch-weiss** [comment]
@DILEEP-YADAV Thanks four your help. I uninstalled Ionic and Cordova globally, cleared the cache and installed both again. The result is the same. 

But I found some other interesting fact. If I try to use ionic serve with an older project that was created with an older Ionic cli version then it works as expected!

And if I just follow the step described in "Getting started" : sudo ionic start --v2 myApp
and I change dir to myApp and try ionic serve the console looks like this:

```
Christophs-MBP:myApp user$ sudo ionic serve

> ionic-hello-world@ ionic:serve /Users/user/Documents/myApp
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

[19:49:18]  ionic-app-scripts 1.0.0 
[19:49:18]  watch started ... 
[19:49:18]  build dev started ... 
[19:49:18]  clean started ... 
[19:49:18]  clean finished in less than 1 ms 
[19:49:18]  copy started ... 
[19:49:18]  transpile started ... 
[19:49:21]  transpile finished in 2.60 s 
[19:49:21]  webpack started ... 
[19:49:21]  copy finished in 2.71 s 
[19:49:28]  webpack finished in 7.06 s 
[19:49:28]  sass started ... 
[19:49:29]  sass finished in 1.23 s 
[19:49:29]  build dev finished in 10.90 s 
[19:49:29]  watch ready in 10.95 s 
[19:49:29]  dev server running: http://localhost:8100/ 
```

No possible commands listed. Nor does I the console react to any.

**Comment by almobams** [comment]
same issue we have with both mac and windows.. any solution to this?

**Comment by globalepub** [comment]
npm cache clean
npm install -g ionic@beta cordova (or npm install -g ionic cordova)

**Comment by almobams** [comment]
thank you for your reply.

I tried npm cache clean then  npm install -g ionic cordova but still same problem.

**Comment by almobams** [comment]
thank you for your reply.

I tried npm cache clean then npm install -g ionic cordova but still same
problem.

**Comment by globalepub** [comment]
You also need to delete and recreate new "**node_modules**".
Find more [here](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0)...

**Comment by ch-weiss** [comment]
It seems the problem is connected to the command ionic start. In app projects created with ionic start of an older ionic cli the command ionic serve works as expected. So to reproduce the problem just update to the latest cli, start a new app project with ionic start, go into the new app directory and try ionic serve. It does not work as expected. 
By the way this basically the same issue as #1898.
