### ISSUE TITLE
Cannot update to v2

### ISSUE THREAD

**Issue by bbatie** [ionic-team/ionic-cli#1814]

**Comment by bbatie** [comment]
I have been trying to update to version 2 and cannot get the CLI to update. I can run the commands and it says it has installed. But when I do the —v it return 1.7.15.

If I run npm uninstall it will say it is unbuilding 2.1.18, but right after uninstalling it still says ver 1.7.15.

I have tried cleaning the npm cache as well and still no luck.

My best guess it is has somehow installing in a different location or something, but not sure how to fix it.

**Comment by rapropos** [comment]
This seems like a better fit for [the support forums](https://forum.ionicframework.com/).
