### ISSUE TITLE
ERROR while uploading iOS app to APP STORE

### ISSUE THREAD

**Issue by PremkumarAgrawal** [ionic-team/ionic-cli#1815]
Hello everyone...

ITunesSoftwareServiceAuthenticationErrorDomain error 434

Facing this error ITunesSoftwareServiceAuthenticationErrorDomain error 434 from last 3 days while validating & uploading my IONIC iOS app on APP STORE. Please Please help me out, tell me what to do, what is going wrong. Here are the screen shots of errors & warnings I am facing...
![screen shot 2016-12-27 at 4 57 18 pm](https://cloud.githubusercontent.com/assets/9786096/21520424/3620f8b8-cd1a-11e6-9f39-1316aee271d1.png)

![screen shot 2016-12-28 at 3 39 07 pm](https://cloud.githubusercontent.com/assets/9786096/21520423/361feb80-cd1a-11e6-9ca5-bbbd3e543cdb.png)

![screen shot 2016-12-28 at 4 06 57 pm](https://cloud.githubusercontent.com/assets/9786096/21520425/362228dc-cd1a-11e6-94cd-3c1ca51e3a6d.png)

![screen shot 2016-12-28 at 4 07 25 pm](https://cloud.githubusercontent.com/assets/9786096/21520426/3624e1da-cd1a-11e6-97c0-e9fed211a1c4.png)

![screen shot 2016-12-28 at 4 07 29 pm](https://cloud.githubusercontent.com/assets/9786096/21520427/3626bf0a-cd1a-11e6-9f52-df9f3ab1a0e2.png)

**Comment by XingChen123** [comment]
have you solved it ? I'm also facing this and have no idea.
