### ISSUE TITLE
ionic --help does not document --dev-logger-port

### ISSUE THREAD

**Issue by tomsun** [ionic-team/ionic-cli#1819]
`ionic --help` does not document `--dev-logger-port` , a parameter [implemented by ionic-app-scripts](https://github.com/driftyco/ionic-app-scripts/blob/2a2d98ab47e19cbcd7808c40b8188ba444ee304f/src/serve.spec.ts#L95-L96) which is useful to know about when running multiple ionic projects at once ( https://github.com/driftyco/ionic-cli/issues/1678 ) or when otherwise desired to manage ports explictly ( https://github.com/driftyco/ionic-app-scripts/issues/599#issuecomment-269699582 ).

The parameter seems to behave as desired, i.e. probably just a documentation shortcoming?
```
$ ionic serve serve --port 7812 --livereload-port 7813 --dev-logger-port 7814
npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v6.9.2
npm info lifecycle ionic-hello-world@~preionic:serve: ionic-hello-world@
npm info lifecycle ionic-hello-world@~ionic:serve: ionic-hello-world@

> ionic-hello-world@ ionic:serve /opt/ionic-iris-playback-example/example
> ionic-app-scripts serve "--dev-logger-port" "7814" "--v2" "--port" "7812" "--livereload-port" "7813" "--address" "0.0.0.0"
...
```

**Comment by dwieeb** [comment]
It should be documented now. I also just made an app-scripts release which works well with the latest Ionic CLI to choose a different dev-logger port. Thanks!
