### ISSUE TITLE
Launch 2 parallel ionic serve failed

### ISSUE THREAD

**Issue by aloumeau-hager** [ionic-team/ionic-cli#1822]
#### Short description of the problem:
Since ionic-cli 2.1.18 i can't run 2 ionic serve at the same time
 

#### What behavior are you expecting?
run 2 ionic serve at the same time 

i think ionic-cli just not test anymore if the port is already use.
But something more strange is the difference between "--livereload-port" "**35730**"" and "listen EADDRINUSE 0.0.0.0:**53703**" i don't know if it's normal

```
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8101" "--livereload-port" "35730"

[10:14:36]  ionic-app-scripts 0.0.47
[10:14:37]  watch started ...
[10:14:37]  build dev started ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:53703
```
hope it can help you to improve ionic-cli

**Comment by matomesc** [comment]
Getting a similar error when I'm running `ionic serve` followed by `ionic run android --device`. I tried using different ports via `-r <port>` and `-p <port>` but it fails with the same error message above.

**Comment by gianpaj** [comment]
For others looking for this, the workaround can be found here:

#1678 -> https://github.com/driftyco/ionic-cli/issues/1678#issuecomment-261683261

**Comment by dwieeb** [comment]
This was just fixed in https://github.com/ionic-team/ionic-app-scripts/commit/271a6e17552e34da92c7b63a7fca203247b130b1

Please upgrade to the latest app-scripts.
