### ISSUE TITLE
watchPatterns in ionic.config.json not working (v2)

### ISSUE THREAD

**Issue by Richie765** [ionic-team/ionic-cli#1823]
#### Short description of the problem:

I have some `.js` files in `src/lib`. When using `ionic serve`, a rebuild isn't triggered when one of those files are changed. I added `watchPatterns` to `ionic.config.json` but it doesn't make a difference:

```json
{
  "name": "my_app",
  "app_id": "",
  "v2": true,
  "typescript": true,
  "watchPatterns": [
    "src/lib/*.js"
  ]
}
```

#### What behavior are you expecting?

Rebuild when those files are changed.

**Steps to reproduce:**
1. Add some .js files in `src/lib`
2. Modify `ionic.config.json` as above
3. Run `ionic serve`
4. Modify one of the .js files
5. Rebuild isn't triggered

**Post the output of `ionic info` below please**
Cordova CLI:  6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by adinu** [comment]
same thing here.

**Comment by VinceOPS** [comment]
same thing here too

**Comment by dwieeb** [comment]
`watchPatterns` is just for Ionic 1. Ionic 2 uses `@ionic/app-scripts`/webpack.
