### ISSUE TITLE
'ionic lib update' cannot update, gives error 'Invalid version: undefined'

### ISSUE THREAD

**Issue by JLLLinn** [ionic-team/ionic-cli#1827]
'ionic lib update' should update the local library to the latest version but instead it gives this error: 'Invalid version: undefined'

The entire history looks like this:
$ ionic lib -version
This command has been deprecated.  All resources are currently available in NPM and we recommend that you use NPM to manage these.
More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower

Local Ionic version: 1.3.1
Invalid version: undefined

**Output of `ionic info` below**
Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.3.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by rgecy** [comment]
having same issue.

**Comment by prantikv** [comment]
👍

**Comment by noor92** [comment]
same issue

**Comment by gompa** [comment]
it would be nice if the link in the error message would actually show some information

**Comment by giovanigenerali** [comment]
having same issue 
```
ionic lib update
This command has been deprecated.  All resources are currently available in NPM and we recommend that you use NPM to manage these.
More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower
Unable to load ionic lib version information
Are you sure you want to replace /Users/user/projects/ionic2-project/www/lib/ionic with an updated version of Ionic?
(yes/no): yes
Invalid version: undefined
```

**Comment by BrunoFDeveloper** [comment]
having same issue.

**Comment by feliperbferraz** [comment]
same

**Comment by codoffer** [comment]
I am having same issue. Not able to update or install the storage plugin.
