### ISSUE TITLE
Erro ionicons.woff ENOSPC 

### ISSUE THREAD

**Issue by Eduardo-Vieira** [ionic-team/ionic-cli#1828]
help!
ionic 2.1.18
ionic serve

> ionic-hello-world@ ionic:serve /home/eduardo/public_ionic/gpm
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

keywords if/then/else require v5 option
[09:53:37]  ionic-app-scripts 0.0.47 
[09:53:37]  watch started ... 
[09:53:37]  build dev started ... 
[09:53:37]  clean started ... 
[09:53:37]  clean finished in 5 ms 
[09:53:37]  copy started ... 
[09:53:37]  transpile started ... 
[09:53:39]  transpile finished in 2.54 s 
[09:53:39]  webpack started ... 
[09:53:39]  copy finished in 2.65 s 
[09:53:46]  webpack finished in 6.94 s 
[09:53:46]  sass started ... 
[09:53:47]  sass finished in 1.11 s 
[09:53:47]  build dev finished in 10.62 s 
[09:53:47]  watch failed: watcher error: 
            /home/eduardo/public_ionic/gpm/home/eduardo/public_ionic/gpm/src/assets/**/*,/home/eduardo/public_ionic/gpm/src/index.html,/home/eduardo/public_ionic/gpm/src/manifest.json,/home/eduardo/public_ionic/gpm/src/service-worker.js,/home/eduardo/public_ionic/gpm/node_modules/ionicons/dist/fonts/**/*,/home/eduardo/public_ionic/gpm/node_modules/ionic-angular/fonts/**/*,/home/eduardo/public_ionic/gpm/node_modules/ionic-angular/polyfills/polyfills.js:
            Error: watch /home/eduardo/public_ionic/gpm/node_modules/ionic-angular/fonts/ionicons.woff ENOSPC 
[09:53:47]  dev server running: http://localhost:8100/

**Comment by dm-grinko** [comment]
I have the same issue.

Your system information:
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.5.0
Xcode version: Not installed

**Comment by arialblack14** [comment]
I too got that error today. Here is my ionic info:

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by dm-grinko** [comment]
You should bump down to app-scripts 1.0.0
And then if you will get this new error - 
`[19:17:12]  watch failed: watcher error: /home/dmitry/work/wanted/home/dmitry/work/wanted/src/**/*.(ts|html|s(c|a)ss): Error: watch /home/dmitry/work/wanted/src ENOSPC`
you should do it -
 echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
