### ISSUE TITLE
ionic 2 throw errors module.js:471 in some specific folders

### ISSUE THREAD

**Issue by adirzoari** [ionic-team/ionic-cli#1832]
I worked on my project in ionic 2 and suddenly when I tried to run ionic serve i got

`module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\adirz\myapps\HaverSami\node_modules\ionic\bin\ionic'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

`

that's what I did and it still shows:
1. removed node & npm.
2. uninstall cordova and ionic.
3. restart my pc.
4. install node, npm,cordova and ionic.
node -v: v6.9.3
npm -v: 4.0.5
ionic -v:2.1.18 (not in all folders, some folders i got this error module.js:471 error)

**Comment by DaiyangLiu** [comment]
have you solved this issue yet?
I faced the same problem today.
I'd greatly appreciate it if you help me.
