### ISSUE TITLE
keypress event is not working in Android 4.4.2 device for Ionic 2 App

### ISSUE THREAD

**Issue by bazigatabassum** [ionic-team/ionic-cli#1836]
I am using keypress event to restrict the special chars in my input. It is going fine with the version lollipop and above, but its not working in Android 4.4.2. 
Kindly suggest for this.
Thank You.

**Comment by haxwell** [comment]
I too am having a problem in Ionic such that the keypress event fires in the browser, but not on the Android device.

**Comment by gopi2mohan** [comment]
Any update on this

**Comment by dwieeb** [comment]
`keypress` is deprecated: https://www.w3.org/TR/DOM-Level-3-Events/#event-type-keypress

Please consider using Angular Form Validation: https://angular.io/guide/form-validation

If you don't want to use validation, you may be able to restrict the characters entered by setting up an `ngModel` and listen on `(input)` or `(beforeinput)` events.

But, this isn't really a CLI issue, so I'm closing this. Please consider creating a topic in the [Ionic Forum](https://forum.ionicframework.com/) and seeing what others have to say. (I'm not an Angular expert.)
