### ISSUE TITLE
`ionic state restore` fails due to no 'www' folder being present when initialising from a Git repo

### ISSUE THREAD

**Issue by kelvindart** [ionic-team/ionic-cli#1843]
#### Short description of the problem:
When initialising a new Ionic 2 project, .gitignore informs Git to ignore the `./www/` folder. Which is fine, since it is built dynamically upon the compilation stage.

This however causes a problem when downloading a project fresh from Git since the `www` folder is not created automatically, when running. This is a problem since Cordova requires this to recognise the directory as an active Cordova project. As a result, `ionic state restore` fails because when it attempts to run the underlying command `cordova plugin add ...`, the command returns with an error 

    Error: Current working directory is not a Cordova-based project.

Which could cause confusion if you are unfamiliar with Cordova. 

I fell either as a `npm postinstall` script, or part of `ionic state restore` an empty www should be created if one is not present?

#### What behavior are you expecting?
For an empty `www` folder to be created upon the `npm postinstall` step OR `ionic state restore` step, in order to satisfy the Cordova requirements and allow successful execution of the command.

**Steps to reproduce:**
1. Clone an Ionic 2 example app running rc.4 (unfortunately I do not have one to hand).
2. Run `npm install` to install all dependencies.
3. Run `ionic state restore` and observe the error.

**Post the output of `ionic info` below please**
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by kelvindart** [comment]
I've just seen in the Ionic super-starter to use a .gitkeep - I guess that would suffice as a solution :)

**Comment by mrbfrank** [comment]
+1 just ran into this issue with my team.
