### ISSUE TITLE
After ionic upload - console is stuck on "Saved app_id, writing to ionic.io.bundle.min.js..."

### ISSUE THREAD

**Issue by jpca999** [ionic-team/ionic-cli#1846]
Using ionic1 

pls help

**Comment by chunxchun** [comment]
same here, I logged into ionic cloud, saw there are a duplicated apps with the same name i am trying to upload. I deleted both of them, then i create a new app in ionic cloud, get the app id and try to link it with my code by 'ionic link <id>', but it fails with "You cannot run this command unless you are in an Ionic Project folder" warning, but i do have ionic.config.json in my folder.
