### ISSUE TITLE
There was an error with the spawned command: npminstall

### ISSUE THREAD

**Issue by tim-minter** [ionic-team/ionic-cli#1848]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version` = 2.1.18

#### Short description of the problem:
An uncaught exception while running ionic start --v2 (but the app folder stature appear to be created OK)

#### What behavior are you expecting?
An uncaught exception while running ionic start --v2

**Steps to reproduce:**
1. ionic start --v2 PushDemo sidemenu
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
Creating Ionic app in folder /Users/xx/Documents/Documentation/AngularJS xx Push/Ionic2/PushDemo based on sidemenu project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by himanshushankhala** [comment]
Also faced the same. Just now at 17-January-2017, 17:33 Indian Standard Time (GMT +5:30).

**Comment by himanshushankhala** [comment]
My Terminal logs:

> 

Himanshus-Mac-mini:test obbserv$ ionic start mySideMenu sidemenu --v2
Creating Ionic app in folder /Volumes/Data/workspace/ionic/test/mySideMenu based on sidemenu project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Himanshus-Mac-mini:test obbserv$ node -v
v4.4.5
Himanshus-Mac-mini:test obbserv$ ionic -v
2.0.0

Himanshus-Mac-mini:test obbserv$ cordova -v
6.3.1
npmHimanshus-Mac-mini:test obbserv$ npm -v
2.15.5

>

**Comment by leann-dev** [comment]
@ himanshushankhala try updating your npm version

**Comment by himanshushankhala** [comment]
Sure, I'll try that as well.
