### ISSUE TITLE
Generating resources is faulty for browser

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-cli#1855]
#### Short description of the problem:
After putting an `icon.png` and a `splash.png` to specification, in the resources folder, and running: `ionic resources`, it generates only android resources, and gives a 404 on browser:
> `localhost:8000/splash` Failed to load resource: the server responded with a status of 404 (Not Found)

Also, it does not show the app icon no where.

#### What behavior are you expecting?
- Generation for `ios` and `android`
- not to get a 404

**Steps to reproduce:**
1. Create an icon and a splash screen
2. `ionic resources`
3. `ionic run browser`

**Post the output of `ionic info` below please**

>  ordova CLI: 6.4.0
> Ionic Framework Version: 2.0.0-rc.4
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 0.0.47
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Windows 10
> Node Version: v6.9.1
> Xcode version: Not installed

**Comment by seiyria** [comment]
Are you intending for this to generate favicons for browser, etc?

**Comment by AmitMY** [comment]
No, no need for that, I just don't know why there needed to be a 404 error at all. Don't generate it, but also don't load it.

**Comment by mburger81** [comment]
Same here, ionic resource creates only icons for android but not for ios.

In contrast to @AmitMY I would like also create the favicons for browser. Is that possible?

**Comment by AmitMY** [comment]
Update because it has been a while, and ionic 3 was released:
This is still an issue.
Generated for browser, this error happens:
> GET http://localhost:8000/screen 404 (Not Found)

**Comment by mburger81** [comment]
I had also other problems creating resources using new ionic3 cli
https://github.com/driftyco/ionic-cli/issues/2027

**Comment by pbnelson** [comment]
Same error here.

**Comment by arcio** [comment]
i'm having the same issue. I'm trying to build a web app only. I build for browser and then load to server. This is so large and I can't pare it down so i want a splash screen while it loads for like 8 seconds. But all I get is the aforementioned 404. 

Really need a resolution to this asap. 
I'm building with: ionic cordova build browser --prod --release

**Comment by shamank** [comment]
Same issue here with @5.3.0: http://lite.appdoone.com
It's trying to load a /screen with a 404 and it shows a broken image while initializing.
I'm serving /platforms/browser/www after doing:
```
# ionic cordova platform add browser
# ionic build browser
```
There is no `ionic cordova resources` for browser either (not sure if it's needed here).

**Comment by dwieeb** [comment]
This can probably be bundled into the broader issue for Cordova browser support: https://github.com/ionic-team/ionic-cli/issues/2312
