### ISSUE TITLE
ionic resources doesn't copy the android icon/splash into the android platform folder

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1857]
_From @tones411 on January 16, 2017 19:44_

**Ionic version:**  (check one with "x")
[ X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report

**Current behavior:**
Android icon and splash screen are not copied to the Android platform folders.

**Expected behavior:**
Android icon and launch screen would be generated and added to the Android platform

**Steps to reproduce:**
Create a new project by running: "ionic start TestResources --v2"
copy your splash.png and icon.png into the resources folder
run "ionic resources"
Navigate to ./TestResources/platforms/android/res" folders
You will see that the icon and splash images are still using the default Cordova images.

** Notes **
This works for iOS, but not Android

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0 
ios-sim version: 3.1.1 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

_Copied from original issue: driftyco/ionic#10056_

**Comment by jgw96** [comment]
_From @ghenry22 on January 17, 2017 0:38_

make sure you have at least android platform version 6.1, verison 6.0 of the android platform introduced this problem, it was a cordova issue not an ionic issue if it's the same one.

**Comment by jgw96** [comment]
_From @tones411 on January 17, 2017 1:20_

I have now confirmed that I was on Android platform 6.0.

However, I just I created a new project and ran "ionic platform add android@6.1.0" and then ran "cordova platform version android" to confirm the version installed.

I ran "ionic resources" again but still no luck. It copies the files to the sub-directories within the ./resources/android/splash/ folder (with a naming convention like this: drawable-land-hdpi-screen.png), but in the corresponding ./platform/android/res/ folders I still have the original Cordova images.

**Comment by jgw96** [comment]
_From @netsesame2 on January 17, 2017 3:54_

Yes, I confirm. I use android sdk 24, that is android 7. 
Resources can't be applied in platform folder under windows.
However, MacOs will works well.

**Comment by jgw96** [comment]
_From @tones411 on January 17, 2017 3:56_

Interesting. The issue happens to me on MacOS.

**Comment by jgw96** [comment]
_From @tones411 on January 17, 2017 3:57_

@netsesame2 can you run "cordova platform version android" in your console and show the output?

**Comment by jgw96** [comment]
_From @ghenry22 on January 17, 2017 3:59_

odd mine has been fine since the platform 6.1 update.  I don't have a android 7 device to test on though currently.

**Comment by jgw96** [comment]
_From @tones411 on January 17, 2017 4:1_

@ghenry22, the issue manifests itself without actually running it on a device, or even on an emulator. You run "ionic resources" and then browse the file system and you can see that it did not copy the images over to the android platform folder.

**Comment by jgw96** [comment]
_From @netsesame2 on January 17, 2017 4:3_

By checking the platform version, I correct to confirm that I still use the android@6.0.0. 

So I update to android@6.1.0 by now, it works.

**Comment by jgw96** [comment]
_From @netsesame2 on January 17, 2017 4:5_

But I can say, on Macos I do use the default version which cordova platform offer, 6.0.0. It works on both android and ios.

**Comment by jgw96** [comment]
_From @ghenry22 on January 17, 2017 4:6_

yes for some reason npm still provides v6.0 by default

**Comment by jgw96** [comment]
_From @tones411 on January 17, 2017 4:8_

@ghenry22 I guess it's probably something wrong on my side. But just to clear up confusion in my mind, can someone explain how the issue is related to Cordova and not Ionic? I didn't think "ionic resources" was dependent on Cordova.

**Comment by jgw96** [comment]
_From @ghenry22 on January 17, 2017 4:46_

@tones411 at lot of what the ionic cli does is passed through to the cordova cli.  There was a specific bug with android platform version 6.0 which introduced this exact problem, android platform version 6.1 resolves the issue with never a change to ionic-cli.  I suspect that the android platform defines the file names, sizes and locations and ionic generates them and puts them where the platform says.

**Comment by jgw96** [comment]
_From @tones411 on January 17, 2017 4:55_

That makes sense. Thanks!

**Comment by jgw96** [comment]
_From @fabiancarlos on January 17, 2017 6:5_

I update my ionic from 2.1.1 to 2.2.1 and have solved this problem building the android again.

**Comment by adirzoari** [comment]
@jgw96  my updated version on this project is "2.2.1"..  what the solution from this conversation?

**Comment by WebAddict** [comment]
I too had this issue generating the wrong icon.

Solved by:
ionic platform rm android
ionic platform add android@6.1.0

**Comment by adirzoari** [comment]
@WebAddict thank you it solve my problem!!!

**Comment by Fogetti** [comment]
@WebAddict Your proposed solution does not work.

My environment is the following:
```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

My cordova android version looks like this:
```
Installed platforms:
  android 6.1.0
  browser 4.1.0
  ios 4.3.1
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0
```

And whenever I run `ionic resources` and `ionic build android` consecutively the following happens: the resources are properly generated in the `resources` folder but none of them copied over to the platforms folder.

And even when I copy the `resources` folder to the platforms folder manually, the cordova build does not honor my resources and simply excludes them from the APK.

Also, the config.xml under `platforms/android/res/xml` is expecting the icon and splash screen to be under `resources` like this:
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.ionicframework.myapp" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <feature name="AppVersion">
        <param name="android-package" value="uk.co.whiteoctober.cordova.AppVersion" />
    </feature>
    <feature name="Device">
        <param name="android-package" value="org.apache.cordova.device.Device" />
    </feature>
    <feature name="InAppBrowser">
        <param name="android-package" value="org.apache.cordova.inappbrowser.InAppBrowser" />
    </feature>
    <feature name="SplashScreen">
        <param name="android-package" value="org.apache.cordova.splashscreen.SplashScreen" />
        <param name="onload" value="true" />
    </feature>
    <feature name="StatusBar">
        <param name="android-package" value="org.apache.cordova.statusbar.StatusBar" />
        <param name="onload" value="true" />
    </feature>
    <feature name="Keyboard">
        <param name="android-package" onload="true" value="org.apache.cordova.labs.keyboard.Keyboard" />
    </feature>
    <name>Tado Installer App</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-navigation href="http://ionic.local/*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" />
    <allow-intent href="market:*" />
    <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
    <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
    <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
    <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
    <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
    <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
    <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
    <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
    <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
    <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
    <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
    <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
    <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
    <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
    <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
    <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
    <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
    <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    <preference name="loglevel" value="DEBUG" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
</widget>
```

Which is of course wrong! Because there is no such folder under `platforms`.

At this point I have no clue who does what and who to blame, because not clear: why isn't the `ionic resources` command copy over the resources, and secondly why are the resources excluded from the APK, and thirdly, why are the config xml entries referencing the wrong locations?

I see that there is a closed issue in ionic which looks painfully similar to what I described: https://github.com/driftyco/ionic-cli/issues/1608

So I just leave this here for people who later stumble upon this problem.
