### ISSUE TITLE
Getting Caught exception: undefined on cordova plugin

### ISSUE THREAD

**Issue by philipbrack** [ionic-team/ionic-cli#1878]
#### Expected behavior was to rebuild the platforms with plugins

**Steps to reproduce:**
1.  ionic start someProject --v2
2. Update your plugins to match this list-

`
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-geolocation",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "cordova-plugin-nativeaudio",
    "cordova-plugin-network-information",
    "ionic-plugin-keyboard",
    "com-sarriaroman-photoviewer",
    "cordova-plugin-ios-non-exempt-encryption"
  ],
`

3. ionic state reset

**Post the output of `ionic info` below please**
/Users/pbrack/dev/ionic2/i2_final:ionic info

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.2.1 Build version 8C1002

/Users/pbrack/dev/ionic2/i2_final:

**Comment by philipbrack** [comment]
Seems like the issue is related to one of the plugin dependencies of ionic native.

```
>ionic plugin add cordova-plugin-nativeaudio
Fetching plugin "cordova-plugin-nativeaudio" via npm


Error: Invalid character in entity name
Line: 8
Column: 54
Char:
```

**Comment by Maziar-Fotouhi** [comment]
Yes I am getting the exact same thing with **nativeaudio**.

**Comment by dhaval85** [comment]
What's the solution for this?

**Comment by philipbrack** [comment]
My solution was to refactor my code to use cordova-plugin-media.  Total time was about 20 minutes.

**Comment by dhaval85** [comment]
Alright. Thanks man. I fixed the original plugin and sent a pull request. :)

**Comment by AhadCove** [comment]
So is this the only way. Don't really understand what you mean by refactoring the code.

**Comment by dhaval85** [comment]
@AhadCove I have fixed the module in below branch. You can use it until they integrate it in main line.

https://github.com/dhaval85/cordova-plugin-nativeaudio

**Comment by AhadCove** [comment]
Would I have to manually download and install it or could I modify this cli somewhere to point to yours?

ionic plugin add cordova-plugin-nativeaudio

**Comment by dhaval85** [comment]
Instead of module name provide URL which I gave you.

**Comment by keep1982** [comment]
`ionic plugin add https://github.com/dhaval85/cordova-plugin-nativeaudio` works like a charm. Thanks a lot for the fix @dhaval85

**Comment by dhaval85** [comment]
@keep1982 : No problem. The fix has been merged to main project. You can switch back to main plugin project now.

**Comment by dhaval85** [comment]
@philipbrack : Please close this issue now. It's been fixed in main project.

**Comment by WiNNiep00h** [comment]
Your sure? i sill have the same error using. https://github.com/dhaval85/cordova-plugin-nativeaudio is working for me

**Comment by dhaval85** [comment]
@WiNNiep00h : I am sure. They have merged into main line. Once they will make a release. It will work in main module as well. The dhaval85 fork is not going to be maintained. So make sure you switch to original repo.
