### ISSUE TITLE
Tool for Unit Testing

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1891]
_From @nicobytes on February 1, 2017 2:42_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request 

**Current behavior:**
In ionic should have a tool for setup unit testing like nativescript. like this:

```
tns test init
```

**Expected behavior:**
![nativescript-select-unit-test-framework](https://cloud.githubusercontent.com/assets/7611944/22493392/d6107f58-e7fd-11e6-9197-c2423cc1685a.gif)

_Copied from original issue: driftyco/ionic#10263_

**Comment by rapropos** [comment]
While I would also like to see testing support, please do not make it interactive like the above screenshot. That will wreak havoc with CI systems, I believe.

**Comment by chrisbenseler** [comment]
I have set up in an ionic 2 app unit testing with angular-cli, following its structure, with karma & jasmine, istanbul for code coverage, etc... it worked like a charm and was supper easy. I think that this could come out-of-the-box in the future.

**Comment by Coly010** [comment]
@chrisbenseler Could you provide a minimal repo that shows this setup?

**Comment by danielsogl** [comment]
@Coly010 https://github.com/ionic-team/ionic-unit-testing-example

**Comment by chrisbenseler** [comment]
Full Ionic 3 app with unit testing @Coly010 
https://github.com/chrisbenseler/enderecoporcepapp

**Comment by Coly010** [comment]
@danielsogl That example had an issue with resolving modules and dependencies.

@chrisbenseler Thank you! Using the following solved our issue:

```js
beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [OurIonicPage],
            imports: [
                IonicModule,
                ReactiveFormsModule
            ],
            providers: [
                { provide: StatusBar, useClass: StatusBarMock },
                { provide: SplashScreen, useClass: SplashScreenMock },
                { provide: Platform, useClass: PlatformMock },
                { provide: NavController, useValue: NavMock },
                { provide: NavParams, useValue: mockParams },
                { provide: DeepLinker, useValue: DeepLinkerMock },
                App, Form, DomController, MenuController, GestureController, Config, Keyboard,
            ]
        }).compileComponents().then(() => {
            fixture = TestBed.createComponent(OurIonicPage);
            component = fixture.componentInstance;
        })
    }));
```

We were missing the following: 

```js
.compileComponents().then(() => {
            fixture = TestBed.createComponent(OurIonicPage);
            component = fixture.componentInstance;
        })
```

Without it, we were unable to import the `ReactiveFormsModule` from `@angular/forms` or other modules decorated with `NgModule()`

@ionic-team Maybe it would be worth adding Testing Documentation around this for Unit Testing of Mobile Apps

**Comment by dwieeb** [comment]
v4 will have testing setup out of the box exactly how Angular does it. `ng test` will run unit tests, `ng e2e` will run end-to-end tests.

Closing this, as it will be added automatically in v4.
