### ISSUE TITLE
"Ionic build windows" not working correctly, not add tag wp

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1892]
_From @edy-ap on November 16, 2016 19:33_

"Ionic build windows" not working correctly, not add tag wp, Therefore looks bad

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

_Copied from original issue: driftyco/ionic-app-scripts#408_

**Comment by jgw96** [comment]
_From @danbucholtz on January 28, 2017 5:24_

@jgw96,

Can you move this to the cli repo?

Thanks,
Dan

**Comment by dwieeb** [comment]
We don't fully support the windows platform.
