### ISSUE TITLE
Feature Request: Option to add index.ts file when using ionic g page <page>

### ISSUE THREAD

**Issue by swaheed2** [ionic-team/ionic-cli#1893]
#### Short description of the problem:

After generating the page, I have to manually create index.ts file in the new page's folder:

```
export * from './<page>';

```

#### What behavior are you expecting?

Would be great to see 4 files like this:

```
1. index.ts
2. <page>.html
3. <page>.scss
4. <page>.html
```

Then with the implementation of https://github.com/driftyco/ionic-cli/issues/1875, generate page command would be perfect for me.

**Bonus:**

_Pages/index.ts_
```
export { Page1 } from './page1'; 
export { Page2 } from './page2'; 
export { <page>} from './<page>';   
```

Then importing looks very clean:

```
import {
  Page1,
  Page2,
  Page3,
} from '../pages';
```

**Comment by dwieeb** [comment]
Closing this as generators are done the Angular way for v4.
