### ISSUE TITLE
Issue in converting angular 1 directive in angular 2

### ISSUE THREAD

**Issue by kurnoolmohammadmujahid** [ionic-team/ionic-cli#1894]
Dear Team,

I am using this directive in ionic 1 project and its working fine.

How to convert the same directive in angular 2.

angular.module('abc').directive('awLimitLength', function () {
  return {
    restrict: "A",
    require: 'ngModel',
    link: function (scope, element, attrs, ngModel) {
      attrs.$set("ngTrim", "false");
      var limitLength = parseInt(attrs.awLimitLength, 10);// console.log(attrs);
      scope.$watch(attrs.ngModel, function(newValue) {
        if(ngModel.$viewValue.length>limitLength){
          ngModel.$setViewValue( ngModel.$viewValue.substring(0, limitLength ) );
          ngModel.$render();
        }
      });
    }
  };
  });

**Comment by rapropos** [comment]
Perhaps this is better suited for [the support forums](https://forum.ionicframework.com/)?
