### ISSUE TITLE
iOS package build failed because of Mixpanel

### ISSUE THREAD

**Issue by vntcapillarygithub** [ionic-team/ionic-cli#1895]
Hi,

I am developing an app using Ionic 2. I have used Mixpanel library in my project. In iOS, there is a issue building the project. The issue is :

"cordova-plugin-mixpanel/Mixpanel/UIImage+MPAverageColor.m:42:23: Variable-sized object may not be initialized"

To resolve that issue mixpanel provided few steps that resolves the issue. Steps for the resolution are :- 

- open your project in xcode
- goto build settings tab
- scroll down to "apple llvm 8.0 - language"
- set "C language dialect" to be default

After following these steps I am able to build my project. 

**Here is my issue**

In my project, I am using Ionic Package. When I am uploading iOS package, it is getting uploaded to ionic.io package section. But build is getting failed because of mixpanel issue. 

Please provide me some way of  resolving the mixpanel issue while uploading iOS package. I am using this command :-

 ionic package build ios --profile dev_profile

I attached screenshots also. Please fid the attachment.
<img width="1226" alt="screen shot 2017-02-03 at 5 35 52 pm" src="https://cloud.githubusercontent.com/assets/25004595/22620902/191cbe56-eb3c-11e6-8dd0-b81b608c8621.png">

Error logs of failed build in Ionic.io.

<img width="1254" alt="screen shot 2017-02-03 at 5 36 09 pm" src="https://cloud.githubusercontent.com/assets/25004595/22620901/191b2654-eb3c-11e6-95bd-a7cdf26ca6a4.png">

**Comment by pverma007** [comment]
Hi @adamdbradley,

Could you please help us on how we should proceed in this case.

--
Prakhar

**Comment by dwieeb** [comment]
Closing. Ionic Cloud is no longer a thing.
