### ISSUE TITLE
ionic build android --prod get error

### ISSUE THREAD

**Issue by jyj545** [ionic-team/ionic-cli#1904]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### Short description of the problem:
use "ionic build android --prod" get error
----------------------------cmd error-------------------------------------------------------------------------------
D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4>ionic build android --prod

> ionic-hello-world@ ionic:build D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4
> ionic-app-scripts build "--prod"

[17:03:46]  ionic-app-scripts 1.0.0
[17:03:46]  build prod started ...
[17:03:46]  clean started ...
[17:03:46]  clean finished in 12 ms
[17:03:46]  copy started ...
[17:03:46]  ngc started ...
[17:03:50]  ionic-app-script task: "build"
[17:03:50]  TypeError: compiler_cli_1.ReflectorHost is not a constructor
TypeError: compiler_cli_1.ReflectorHost is not a constructor
    at new AotCompiler (D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:31:30)
    at ngcWorker (D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4\node_modules\@ionic\app-scripts\dist\ngc.js:19:20)
    at Object.ngc (D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4\node_modules\@ionic\app-scripts\dist\ngc.js:9:12)
    at buildProject (D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4\node_modules\@ionic\app-scripts\dist\build.js:95:51)
    at D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4\node_modules\@ionic\app-scripts\dist\build.js:43:16

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jyj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--" "--prod"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build "--prod"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4\npm-debug.log

attempt to call a nil value
-------------------------------------npm-debug.log----------------------------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\jyj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic:build',
1 verbose cli   '--',
1 verbose cli   '--prod' ]
2 info using npm@4.1.1
3 info using node@v6.9.4
4 verbose run-script [ 'preionic:build', 'ionic:build', 'postionic:build' ]
5 info lifecycle ionic-hello-world@~preionic:build: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:build: no script for preionic:build, continuing
7 info lifecycle ionic-hello-world@~ionic:build: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:build: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:build: PATH: C:\Users\jyj\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4\node_modules\.bin;D:\迅雷下载\cmder\bin;D:\迅雷下载\cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\迅雷下载\cmder\vendor\conemu-maximus5;D:\迅雷下载\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\Lenovo\Lenovo Home\;C:\Program Files\TortoiseSVN\bin;D:\JDK1.8\bin;D:\androidsdk\platform-tools;D:\androidsdk\tools;C:\Program Files\Git\cmd;C:\Python27;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\nodejs\;D:\迅雷下载\cmder;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\jyj\AppData\Roaming\npm;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\share\vim\vim74;D:\迅雷下载\cmder\
10 verbose lifecycle ionic-hello-world@~ionic:build: CWD: D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4
11 silly lifecycle ionic-hello-world@~ionic:build: Args: [ '/d /s /c', 'ionic-app-scripts build "--prod"' ]
12 silly lifecycle ionic-hello-world@~ionic:build: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~ionic:build: Failed to exec ionic:build script
14 verbose stack Error: ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\jyj\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\jyj\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd D:\donghuawork\06_JAVA_PRODUCT_V6\02_Product\01_Trunk\01_PublicAPP\ionicdemorc4
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jyj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--" "--prod"
19 error node v6.9.4
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod"`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build "--prod"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

#### What behavior are you expecting?
correctly build apk

**Steps to reproduce:**
1.use "ionic build android" build apk correct
2.use "ionic build android --prod" build apk failed
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
my ionic info print:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
added crosswalk plugin
os enviriment:windows 7

**Comment by zhudms** [comment]
is anybody can help?I got the same error ,I don't know why.
even I start a new project ,I can run ionic build android ,but got error when add --prod

**Comment by gkiran1** [comment]
@zhudms, @jyj545 Have you managed to fix this. I am facing the same issue.

**Comment by zhudms** [comment]
@gkiran1  maybe i forgot node.js environment,and beside i reinstall the system
