### ISSUE TITLE
add unit test by default?

### ISSUE THREAD

**Issue by calidion** [ionic-team/ionic-cli#1906]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### Short description of the problem:

when ionic projects created, there are no buildin test frameworks at all.

#### What behavior are you expecting?

providing a default config for unit testing.

**Comment by eikooc** [comment]
I think this is a very valid point.
The generation of components should help developers write better code and a nudge in the direction of writing tests would be good. Maybe have a flag where you can opt out of automatic test generation?

**Comment by dwieeb** [comment]
Unit tests come by default in v4 projects and are set up to work with the Angular CLI via `ng test`. There is also `ng e2e`. Closing this as it will automatically be resolved in v4.
