### ISSUE TITLE
Package.js SyntaxError end of input

### ISSUE THREAD

**Issue by MaximeIJ** [ionic-team/ionic-cli#1950]
`npm view ionic@latest version`

2.2.1

#### What version of the CLI are you using? Output of `ionic --version`

2.2.1

#### Short description of the problem:

There's a recurring syntax error when using package about unexpected end of input. What few others have reported similar issues mentioned io-config being corrupted, but I deleted and regenerated mine with no success.

#### What behavior are you expecting?

At least an attempt at running the build or a more explicit error

**Steps to reproduce:**
1. ionic package build ios --profile MY_PROFILE_TAG

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

Your system information:

Cordova CLI: 6.5.0
 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v4.4.5
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Caught exception:
 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (C:\Users\\[my-username]\AppData\Roaming\npm\n
onic-app-lib\lib\package.js:117:27)
    at Request.self.callback (C:\Users\\[my-username]\AppData\Roaming\n
es\ionic-app-lib\node_modules\request\request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\\[my-username]\AppData\Roaming\npm
\ionic-app-lib\node_modules\request\request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\\[my-username]\AppData\Roa
_modules\ionic-app-lib\node_modules\request\request.js:1266:12)
    at emitNone (events.js:72:20)

**Comment by MaximeIJ** [comment]
I see someone added a v2 label. The app in question is v1, could this be the cause of the issue? I'm not clear on what the compatibility between CLI v2 and framework v1 are

**Comment by shawns582** [comment]
im having this issue on my v2 app. Did you ever figure out the problem?

**Comment by MaximeIJ** [comment]
Unfortunately no, I quickly gave up on using package for the time being. If I had to look at it again today I'd try deleting node_modules and rerunning "npm install", making sure the CLI is up to date all that, I had not tried that last time

**Comment by shawns582** [comment]
ahh ok thanks for letting me know. Hopefully someone has the answer

**Comment by dwieeb** [comment]
The answer is there's a JSON syntax error in your `package.json`, probably from manual edits or an empty file.

Upgrade to CLI v3. The error messages are a bit nicer.
