### ISSUE TITLE
process.stdout.getWindowSize is not a function

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1957]
_From @bradrust on March 7, 2017 0:41_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
"ionic package" commands are not usable other than via interactive terminals

**Expected behavior:**
we should be able to automate (grep, pipe, redirect, etc...) the use of "ionic package" commands.  For example, to execute deterministic and automated configuration management processes ... like building releases.

**Steps to reproduce:**

from a bash shell
  ionic package list | grep SUCCESS

**Other information:**
```
TypeError: process.stdout.getWindowSize is not a function
    at /usr/lib/node_modules/ionic/lib/ionic/package.js:183:42
    at _fulfilled (/usr/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.16
Node Version: v6.10.0
Xcode version: Not installed
```

_Copied from original issue: driftyco/ionic#10670_

**Comment by leosoto** [comment]
We (with @vutreras) were just bitten by this problem when setting up continuous integration in our app. We are using bash scripts to drive ionic cloud packaging and this problem is a showstopper.

If the simple approach of #2075 isn't enough, we are willing to contribute a better solution, given some guidance :)

**Comment by tuomassalo** [comment]
You could try something like this: (only tested on macOs, might need tweaking on other platforms)

    script /dev/null ionic package list | perl -wne 's/\033....//g; if(/ (\d+) .*? ([A-Z]{2,})/) { print "$1 $2\n"; exit }'


The command first (naïvely) attempts to remove color coding, then tries to find the topmost build and prints its number and status.

Still something odd with linefeeds, but should help for scripting.

**Comment by dwieeb** [comment]
I've noticed this doesn't happen with CLI v3. Is this still an issue? Also, I would be careful parsing output of any CLI without explicit parseable modes (`--porcelain` for git, `--json` for npm, etc), as the output could stylistically change and break your script.

I am migrating this issue to: https://github.com/ionic-team/ionic-cli/issues/2388
