### ISSUE TITLE
Build fails after adding crosswalk

### ISSUE THREAD

**Issue by kasumbarobert** [ionic-team/ionic-cli#1985]
-compile:
    [javac] Compiling 38 source files to /home/kasumba/Documents/ionic apps/platforms/android/bin/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaClientCertRequest.java:22: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.ClientCertRequest;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaClientCertRequest.java:31: error: cannot find symbol
    [javac]     private final ClientCertRequest request;
    [javac]                   ^
    [javac]   symbol:   class ClientCertRequest
    [javac]   location: class XWalkCordovaClientCertRequest
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaClientCertRequest.java:33: error: cannot find symbol
    [javac]     public XWalkCordovaClientCertRequest(ClientCertRequest request) {
    [javac]                                          ^
    [javac]   symbol:   class ClientCertRequest
    [javac]   location: class XWalkCordovaClientCertRequest
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:22: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkCookieManager;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:26: error: cannot find symbol
    [javac]     protected XWalkCookieManager cookieManager = null;
    [javac]               ^
    [javac]   symbol:   class XWalkCookieManager
    [javac]   location: class XWalkCordovaCookieManager
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaHttpAuthHandler.java:22: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkHttpAuthHandler;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaHttpAuthHandler.java:30: error: cannot find symbol
    [javac]     private final XWalkHttpAuthHandler handler;
    [javac]                   ^
    [javac]   symbol:   class XWalkHttpAuthHandler
    [javac]   location: class XWalkCordovaHttpAuthHandler
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaHttpAuthHandler.java:32: error: cannot find symbol
    [javac]     public XWalkCordovaHttpAuthHandler(XWalkHttpAuthHandler handler) {
    [javac]                                        ^
    [javac]   symbol:   class XWalkHttpAuthHandler
    [javac]   location: class XWalkCordovaHttpAuthHandler
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:32: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.ClientCertRequest;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:33: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkHttpAuthHandler;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:34: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkResourceClient;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:35: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkView;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:40: error: cannot find symbol
    [javac] public class XWalkCordovaResourceClient extends XWalkResourceClient {
    [javac]                                                 ^
    [javac]   symbol: class XWalkResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:51: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkActivityDelegate;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:52: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkNavigationHistory;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:53: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkView;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:54: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkGetBitmapCallback;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:60: error: cannot find symbol
    [javac]     public void onReceivedLoadError(XWalkView view, int errorCode, String description,
    [javac]                                     ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:68: error: cannot find symbol
    [javac]     public WebResourceResponse shouldInterceptLoadRequest(XWalkView view, String url) {
    [javac]                                                           ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:98: error: cannot find symbol
    [javac]     public boolean shouldOverrideUrlLoading(XWalkView view, String url) {
    [javac]                                             ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:111: error: cannot find symbol
    [javac]     public void onReceivedSslError(XWalkView view, ValueCallback<Boolean> callback, SslError error) {
    [javac]                                    ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:132: error: cannot find symbol
    [javac]     public void onReceivedHttpAuthRequest(XWalkView view, XWalkHttpAuthHandler handler,
    [javac]                                           ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:132: error: cannot find symbol
    [javac]     public void onReceivedHttpAuthRequest(XWalkView view, XWalkHttpAuthHandler handler,
    [javac]                                                           ^
    [javac]   symbol:   class XWalkHttpAuthHandler
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:148: error: cannot find symbol
    [javac]     public void onReceivedClientCertRequest(XWalkView view, ClientCertRequest request) {
    [javac]                                             ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:148: error: cannot find symbol
    [javac]     public void onReceivedClientCertRequest(XWalkView view, ClientCertRequest request) {
    [javac]                                                             ^
    [javac]   symbol:   class ClientCertRequest
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:4: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkPreferences;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:5: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkResourceClient;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:6: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkUIClient;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:7: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkView;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:22: error: cannot find symbol
    [javac] public class XWalkCordovaView extends XWalkView implements CordovaWebViewEngine.EngineView {
    [javac]                                       ^
    [javac]   symbol: class XWalkView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:78: error: cannot find symbol
    [javac]     protected XWalkActivityDelegate activityDelegate;
    [javac]               ^
    [javac]   symbol:   class XWalkActivityDelegate
    [javac]   location: class XWalkWebViewEngine
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:219: error: cannot find symbol
    [javac]     private static void exposeJsInterface(XWalkView webView, CordovaBridge bridge) {
    [javac]                                           ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkWebViewEngine
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:31: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkJavascriptResult;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:32: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkUIClient;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:33: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.XWalkView;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:37: error: cannot find symbol
    [javac] public class XWalkCordovaUiClient extends XWalkUIClient {
    [javac]                                           ^
    [javac]   symbol: class XWalkUIClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:73: error: cannot find symbol
    [javac]     public void setResourceClient(XWalkResourceClient client) {
    [javac]                                   ^
    [javac]   symbol:   class XWalkResourceClient
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:82: error: cannot find symbol
    [javac]     public void setUIClient(XWalkUIClient client) {
    [javac]                             ^
    [javac]   symbol:   class XWalkUIClient
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:54: error: cannot find symbol
    [javac]     public boolean onJavascriptModalDialog(XWalkView view, JavascriptMessageType type, String url,
    [javac]                                            ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:54: error: cannot find symbol
    [javac]     public boolean onJavascriptModalDialog(XWalkView view, JavascriptMessageType type, String url,
    [javac]                                                            ^
    [javac]   symbol:   class JavascriptMessageType
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:55: error: cannot find symbol
    [javac]                                            String message, String defaultValue, XWalkJavascriptResult result) {
    [javac]                                                                                 ^
    [javac]   symbol:   class XWalkJavascriptResult
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:76: error: cannot find symbol
    [javac]     public boolean onJsAlert(XWalkView view, String url, String message,
    [javac]                              ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:77: error: cannot find symbol
    [javac]                               final XWalkJavascriptResult result) {
    [javac]                                     ^
    [javac]   symbol:   class XWalkJavascriptResult
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:94: error: cannot find symbol
    [javac]     public boolean onJsConfirm(XWalkView view, String url, String message,
    [javac]                                ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:95: error: cannot find symbol
    [javac]                                 final XWalkJavascriptResult result) {
    [javac]                                       ^
    [javac]   symbol:   class XWalkJavascriptResult
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:117: error: cannot find symbol
    [javac]     public boolean onJsPrompt(XWalkView view, String origin, String message, String defaultValue,
    [javac]                               ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:118: error: cannot find symbol
    [javac]                                final XWalkJavascriptResult result) {
    [javac]                                      ^
    [javac]   symbol:   class XWalkJavascriptResult
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:149: error: cannot find symbol
    [javac]     public void onPageLoadStarted(XWalkView view, String url) {
    [javac]                                   ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:167: error: cannot find symbol
    [javac]     public void onPageLoadStopped(XWalkView view, String url, LoadStatus status) {
    [javac]                                   ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:167: error: cannot find symbol
    [javac]     public void onPageLoadStopped(XWalkView view, String url, LoadStatus status) {
    [javac]                                                               ^
    [javac]   symbol:   class LoadStatus
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java:179: error: cannot find symbol
    [javac]     public void openFileChooser(XWalkView view, final ValueCallback<Uri> uploadFile,
    [javac]                                 ^
    [javac]   symbol:   class XWalkView
    [javac]   location: class XWalkCordovaUiClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkExposedJsApi.java:26: error: package org.xwalk.core does not exist
    [javac] import org.xwalk.core.JavascriptInterface;
    [javac]                      ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkExposedJsApi.java:35: error: cannot find symbol
    [javac]     @JavascriptInterface
    [javac]      ^
    [javac]   symbol:   class JavascriptInterface
    [javac]   location: class XWalkExposedJsApi
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkExposedJsApi.java:43: error: cannot find symbol
    [javac]     @JavascriptInterface
    [javac]      ^
    [javac]   symbol:   class JavascriptInterface
    [javac]   location: class XWalkExposedJsApi
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkExposedJsApi.java:48: error: cannot find symbol
    [javac]     @JavascriptInterface
    [javac]      ^
    [javac]   symbol:   class JavascriptInterface
    [javac]   location: class XWalkExposedJsApi
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:29: error: cannot find symbol
    [javac]         cookieManager = new XWalkCookieManager();
    [javac]                             ^
    [javac]   symbol:   class XWalkCookieManager
    [javac]   location: class XWalkCordovaCookieManager
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:59: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:67: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:97: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:110: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:131: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:144: error: cannot find symbol
    [javac]         super.onReceivedHttpAuthRequest(view, handler, host, realm);
    [javac]         ^
    [javac]   symbol:   variable super
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:147: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:157: error: cannot find symbol
    [javac]         super.onReceivedClientCertRequest(view, request);
    [javac]         ^
    [javac]   symbol:   variable super
    [javac]   location: class XWalkCordovaResourceClient
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:104: error: cannot find symbol
    [javac]                         XWalkWebViewEngine.this.webView.onNewIntent(intent);
    [javac]                                                        ^
    [javac]   symbol:   method onNewIntent(Intent)
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:114: error: cannot find symbol
    [javac]                                             new XWalkGetBitmapCallback() {
    [javac]                                                 ^
    [javac]   symbol: class XWalkGetBitmapCallback
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:136: error: cannot find symbol
    [javac]                     webView.load(startUrl, null);
    [javac]                            ^
    [javac]   symbol:   method load(String,<null>)
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:140: error: cannot find symbol
    [javac]         activityDelegate = new XWalkActivityDelegate((Activity) context, cancelCommand, completeCommand);
    [javac]                                ^
    [javac]   symbol:   class XWalkActivityDelegate
    [javac]   location: class XWalkWebViewEngine
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:175: error: cannot find symbol
    [javac]                 webView.setNetworkAvailable(value);
    [javac]                        ^
    [javac]   symbol:   method setNetworkAvailable(boolean)
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:193: error: incompatible types: XWalkCordovaView cannot be converted to View
    [javac]         return webView;
    [javac]                ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:197: error: cannot find symbol
    [javac]         webView.setVerticalScrollBarEnabled(false);
    [javac]                ^
    [javac]   symbol:   method setVerticalScrollBarEnabled(boolean)
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:200: error: cannot find symbol
    [javac]         webView.setZOrderOnTop(zOrderOnTop);
    [javac]                ^
    [javac]   symbol:   method setZOrderOnTop(boolean)
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:205: error: cannot find symbol
    [javac]             webView.setUserAgentString(xwalkUserAgent);
    [javac]                    ^
    [javac]   symbol:   method setUserAgentString(String)
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:210: error: cannot find symbol
    [javac]             webView.setUserAgentString(webView.getUserAgentString() + " " + appendUserAgent);
    [javac]                                               ^
    [javac]   symbol:   method getUserAgentString()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:238: error: cannot find symbol
    [javac]             webView.getExtensionManager().loadExtension(XWALK_EXTENSIONS_FOLDER + File.separator + path);
    [javac]                    ^
    [javac]   symbol:   method getExtensionManager()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:245: error: cannot find symbol
    [javac]         return this.webView.getNavigationHistory().canGoBack();
    [javac]                            ^
    [javac]   symbol:   method getNavigationHistory()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:250: error: cannot find symbol
    [javac]         if (this.webView.getNavigationHistory().canGoBack()) {
    [javac]                         ^
    [javac]   symbol:   method getNavigationHistory()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:251: error: package XWalkNavigationHistory does not exist
    [javac]             this.webView.getNavigationHistory().navigate(XWalkNavigationHistory.Direction.BACKWARD, 1);
    [javac]                                                                                ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:251: error: cannot find symbol
    [javac]             this.webView.getNavigationHistory().navigate(XWalkNavigationHistory.Direction.BACKWARD, 1);
    [javac]                         ^
    [javac]   symbol:   method getNavigationHistory()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:264: error: cannot find symbol
    [javac]             webView.resumeTimers();
    [javac]                    ^
    [javac]   symbol:   method resumeTimers()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:271: error: cannot find symbol
    [javac]         webView.onDestroy();
    [javac]                ^
    [javac]   symbol:   method onDestroy()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:277: error: cannot find symbol
    [javac]         this.webView.getNavigationHistory().clear();
    [javac]                     ^
    [javac]   symbol:   method getNavigationHistory()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:283: error: cannot find symbol
    [javac]         this.webView.stopLoading();
    [javac]                     ^
    [javac]   symbol:   method stopLoading()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:289: error: cannot find symbol
    [javac]         webView.clearCache(true);
    [javac]                ^
    [javac]   symbol:   method clearCache(boolean)
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:295: error: cannot find symbol
    [javac]         return this.webView.getUrl();
    [javac]                            ^
    [javac]   symbol:   method getUrl()
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:309: error: cannot find symbol
    [javac]         webView.load(url, null);
    [javac]                ^
    [javac]   symbol:   method load(String,<null>)
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:319: error: cannot find symbol
    [javac]         webView.evaluateJavascript(js, callback);
    [javac]                ^
    [javac]   symbol:   method evaluateJavascript(String,ValueCallback<String>)
    [javac]   location: variable webView of type XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:44: error: cannot find symbol
    [javac]             XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, prefAnimatable || manifestAnimatable);
    [javac]                                       ^
    [javac]   symbol:   variable XWalkPreferences
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:44: error: cannot find symbol
    [javac]             XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, prefAnimatable || manifestAnimatable);
    [javac]             ^
    [javac]   symbol:   variable XWalkPreferences
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:46: error: cannot find symbol
    [javac]                 XWalkPreferences.setValue(XWalkPreferences.REMOTE_DEBUGGING, true);
    [javac]                                           ^
    [javac]   symbol:   variable XWalkPreferences
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:46: error: cannot find symbol
    [javac]                 XWalkPreferences.setValue(XWalkPreferences.REMOTE_DEBUGGING, true);
    [javac]                 ^
    [javac]   symbol:   variable XWalkPreferences
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:48: error: cannot find symbol
    [javac]             XWalkPreferences.setValue(XWalkPreferences.JAVASCRIPT_CAN_OPEN_WINDOW, true);
    [javac]                                       ^
    [javac]   symbol:   variable XWalkPreferences
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:48: error: cannot find symbol
    [javac]             XWalkPreferences.setValue(XWalkPreferences.JAVASCRIPT_CAN_OPEN_WINDOW, true);
    [javac]             ^
    [javac]   symbol:   variable XWalkPreferences
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:49: error: cannot find symbol
    [javac]             XWalkPreferences.setValue(XWalkPreferences.ALLOW_UNIVERSAL_ACCESS_FROM_FILE, true);
    [javac]                                       ^
    [javac]   symbol:   variable XWalkPreferences
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:49: error: cannot find symbol
    [javac]             XWalkPreferences.setValue(XWalkPreferences.ALLOW_UNIVERSAL_ACCESS_FROM_FILE, true);
    [javac]             ^
    [javac]   symbol:   variable XWalkPreferences
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:72: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:78: error: cannot find symbol
    [javac]         super.setResourceClient(client);
    [javac]         ^
    [javac]   symbol:   variable super
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:81: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:87: error: cannot find symbol
    [javac]         super.setUIClient(client);
    [javac]         ^
    [javac]   symbol:   variable super
    [javac]   location: class XWalkCordovaView
    [javac] /home/kasumba/Documents/ionic apps/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:93: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 100 errors
    [javac] 3 warnings

BUILD FAILED
/home/kasumba/Android/Sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/home/kasumba/Android/Sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 6 seconds
Error: ant: Command failed with exit code 1 Error output:
BUILD FAILED
/home/kasumba/Android/Sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/home/kasumba/Android/Sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 6 seconds

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.
