### ISSUE TITLE
v3 - cordova:resources not working

### ISSUE THREAD

**Issue by Richie765** [ionic-team/ionic-cli#1991]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.4

#### Short description of the problem:
```
$ ionic cordova:resources
✔ Collecting resource configuration and source images - done!
✔ Uploading source images to prepare for transformations - done!
⠏ Generating platform resources Error: STATUS: 400 {"Error":"error resizing image: e8536419316670cc866da71f4468761b.png"}
    at Object.<anonymous> (/Users/blabla/path/node_modules/@ionic/cli-plugin-cordova/dist/index.js:2016:23)
    at next (native)
    at fulfilled (/Users/blabla/path/node_modules/@ionic/cli-plugin-cordova/dist/index.js:1847:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I also tried with --splash and --icon with the same result.

Image formats:
```
$ file *.png
icon.png:   PNG image data, 3922 x 3135, 8-bit/color RGBA, non-interlaced
splash.png: PNG image data, 2208 x 2208, 8-bit/color RGB, non-interlaced
```

The same files worked before with cli v2.x

#### What behavior are you expecting?
Resources generated

**Post the output of `ionic info` below please**
    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v6.9.4
    Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jthoms1** [comment]
The error being returned is from the image resizing service so I would be surprised if it worked in v2.  Either way could you provide me with the images that are failing?

https://github.com/blog/2061-attach-files-to-comments

**Comment by Richie765** [comment]
I see my icon file is the wrong size, normally I use 1024x1024 without Alpha. The splash should be fine but also doesn't work. I tested again with v2 and it passes without errors. I checked the files with `pngcheck` and they are fine.

Can you also tell me what the recommended dimensions are?

Here are the files.
[icon](https://cloud.githubusercontent.com/assets/4173168/24063315/e9c4cdd4-0b3d-11e7-949b-ac13927224c9.png)
[splash](https://cloud.githubusercontent.com/assets/4173168/24063314/e9bbd2ce-0b3d-11e7-85a7-9b6baaabdeef.png)

**Comment by Richie765** [comment]
It seems to work fine now. Even though I got an error in the beginning that was a bit confusing:

```
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of date.
✖ Generating platform resources - failed!
Error: encountered bad status code (400) for https://res.ionic.io/api/v1/transform
body: {"Error":"source image 2208x2208 too small for Default-Portrait@~ipadpro.png, requires at least 2048x2732 source file"}
```

Turned out plugins weren't out of date, just the source image had to be scaled bigger. Elsewhere it says the size should be at least 2732x2732px, not 2048x2732px. So that could be improved a bit, but it is working fine so far. Thanks for fixing!

**Comment by anil1712** [comment]
I am also getting the same.

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.11.1
    npm   : 6.0.1 
    OS    : macOS High Sierra
    Xcode : Xcode 9.3.1 Build version 9E501 

```

Is someone got any solution?

**Comment by dwieeb** [comment]
@anil1712 Not sure which issue you're referring to. It seems this issue is resolved. Please create a new issue if you're having a problem and fill out the issue template. 

Closing for now! 🎉
