### ISSUE TITLE
error ionic upload --note "XXXXX"  --deploy production

### ISSUE THREAD

**Issue by rolandoDev** [ionic-team/ionic-cli#1996]
not uploaded

**Comment by jthoms1** [comment]
Can you provide the output from `ionic info` as well as the actual error output from the command execution?

**Comment by rolandoDev** [comment]
Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.1 
    ios-sim version: 5.0.13 
    OS: macOS Sierra
    Node Version: v6.10.0
    Xcode version: Xcode 8.2.1 Build version 8C1002

Does not display an error message, but does not raise the snapshot to the cloud

✔ Requesting snapshot - done!
⠸ Uploading snapshot [===============] 100% 0.0s
✔ Uploading snapshot - done!
[OK] Uploaded snapshot 2eac441f-305a-434e-9562-5f5a10905s2c!
