### ISSUE TITLE
ionic cordova:build android does not display the apk path

### ISSUE THREAD

**Issue by Langstra** [ionic-team/ionic-cli#2003]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.4

#### Short description of the problem:
After running `ionic cordova:build android` I did not see where the new apk was build.

#### What behavior are you expecting?
The path to where the apk was build.

**Steps to reproduce:**
1. Just run the command `ionic cordova:build android` in any project

**Post the output of `ionic info` below please**
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.4
    Node Version: v7.3.0
    Xcode version: Not installed

**Comment by jthoms1** [comment]
Could you try rerunning the command with the `--log-level=debug` option?

**Comment by 14753690** [comment]
Still got the same error 
![image](https://cloud.githubusercontent.com/assets/26458643/24000016/f559b962-0a51-11e7-8a6c-61aece4a4208.png)

**Comment by 14753690** [comment]
and this is the line error 

![image](https://cloud.githubusercontent.com/assets/26458643/24000049/0d6ca136-0a52-11e7-9097-8f2d92e9e3bd.png)

**Comment by jthoms1** [comment]
Sorry this is a bit confusing.  The error is being thrown by a package that is not used by Ionic CLI v3. Could you first run `npm uninstall -g ionic` and then `npm install -g ionic@beta`?

Then try the command again.

**Comment by Langstra** [comment]
Sorry, my issue was not about an error. It was about an improvement to the cli. I never experienced an error.

**Comment by 14753690** [comment]
Still doesn't work, stuck on starting server-done! It doesn't show my app

Envoyé de mon iPhone

Le 16 mars 2017 à 14:44, Wybren Kortstra <notifications@github.com<mailto:notifications@github.com>> a écrit :


Sorry, my issue was not about an error. It was about an improvement to the cli. I never experienced an error.

**Comment by jthoms1** [comment]
@Langstra understood, but if you run `ionic cordova:build android --log-level=debug` are you able to see the apk path?

**Comment by Langstra** [comment]
@jthoms1 I tried that just now, but unfortunately no luck.

**Comment by 14753690** [comment]
No!

Envoyé de mon iPhone

Le 17 mars 2017 à 19:30, Josh Thomas <notifications@github.com<mailto:notifications@github.com>> a écrit :


@Langstra<https://github.com/Langstra> understood, but if you run ionic cordova:build android --log-level=debug are you able to see the apk path?

**Comment by leandroz** [comment]
No logs at all, I think that by default it should show whats going on under the hood when doing cordova commands, and not hide the logs.

**Comment by 14753690** [comment]
Hey, please can you help me, in my ionic app, every time i want to add sass setup i get unknow plugin :@ionic/cli-plugin. Please i need help asap.

thank you


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by Langstra** [comment]
Ionic 2 has sass by default if I am not mistaken. However, if you feel there is a bug, then file a separate issue, but I would advise you to make a post on the community board. They are quite helpful.
