### ISSUE TITLE
Not able to add android platform.

### ISSUE THREAD

**Issue by anjuthanmj** [ionic-team/ionic-cli#2010]
Ionic version: 2.2.1
cordova version: 6.5.0

Not able to add android platform. I'm able to run the app in browser using 'ionic serve' command. 
I use Windows 10. I have android sdk installed. (I work on android studio)

**Steps to reproduce:**
1. ionic start myApps tabs
2. ionic platform add android

D:\Docs\myApp>ionic platform add android
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
function bold() { [native code] } https://github.com/driftyco/ionic-default-resources/archive/master.zip
Caught exception:
 Error: spawn C:\Windows\system32\cmd.exe;C:\Program Files\Git\bin;C:\Program Files\Git\cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by lightsonupstairs** [comment]
I also have this issue with  cli not having the option(s) cordova in ionic commands.

my Ionic info:

global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.4.0

System:

    Node       : v7.7.4
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by anjuthanmj** [comment]
I could not solve this issue. Uninstalling NodeJS, Ionic and cordova and reinstalling them didn't help. I formatted my PC and reinstalled everything. It worked fine after that. Something is messed up but do not know what.

**Comment by dwieeb** [comment]
Probably a PATH issue. https://github.com/ionic-team/ionic-cli/issues/2214
