### ISSUE TITLE
v3.beta4 signup command does not work

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-cli#2027]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.4

#### Short description of the problem:
I tried to create new icons and splash screens for ios, you wrote in some issue with ionic cli v3 the creation of icons for ios should work,

after launch
`ionic cordova:resources --icon`
I get the message:
`You need to be logged into your Ionic account in order to run the cordova:resources command`

So I tried this but got an error:
```
ionic signup
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/ionic/dist/xdg-open ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

#### What behavior are you expecting?
1) First off all your readme for version 3. is wrong you have to put cordova: before resources to launch the command
2) Close this new bug :)
3) @jthoms1 I'm still waiting for the new release you promises 10 days and 7 days ago :) :) :)

**Post the output of `ionic info` below please**
```
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.8
    Node Version: v6.10.1
    Xcode version: Not installed

```

**Comment by jthoms1** [comment]
@mburger81 Release of beta.5 is out as of 2 days ago.

This appears to be an issue specific to linux.  The signup command opens up a browser for the signup process.  What distro are you using?

**Comment by mburger81** [comment]
@jthoms1 I'm using Kubuntu 16.10 64bit and the error persist also on ionic-cli beta.5

**Comment by mburger81** [comment]
On creating a simple empty side-menu  project with beta.5 I get this error at the end

```
? What would you like to name your project: ionic3-modal
? What starter would you like to use sidemenu
✔ Creating directory /home/michi/software/workspace/tmp/ionic3-modal - done!
✔ Downloading 'sidemenu' starter template - done!
✔ Updating project dependencies to add required plugins - done!
✔ Creating configuration file for the new project - done!
✔ Executing: npm install within the newly created project directory - done!

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Run your app in the browser (great for initial development):
  ionic serve

Run on a device or simulator:
  ionic cordova:run ios

Test and share your app on a device with the Ionic View app:
  http://view.ionic.io
                                                                                                                                                                                                                                                   
**[ERROR] You are not logged in! Run 'ionic login'.**    
```

**Comment by dwieeb** [comment]
I'm guessing it's a bug with `opn`, the npm package we're using to open a browser page cross-platform. Please update if this is still an issue.
