### ISSUE TITLE
ionic generate directive (one template) fails selecting component (v3)

### ISSUE THREAD

**Issue by ammulder** [ionic-team/ionic-cli#2071]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta.5

#### Short description of the problem:

`ionic generate`
* What would you like to generate: directive
* What should the name be? foo
* Use this directive in more than one template? No
* Page or component that will be using this directive

Then it's just blank -- no way to pick a page or component that will be using this directive.  Says to use arrow keys, but using arrow keys does nothing.  Tried typing a page name (without file extension) and hit Enter and got a stack trace:

```
TypeError: Cannot read property 'value' of undefined
    at Prompt.getCurrentValue (/Users/ammulder/dev/dragonlock/node_modules/inquirer/lib/prompts/list.js:129:51)
    at tryCatcher (/Users/ammulder/dev/dragonlock/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.next (/Users/ammulder/dev/dragonlock/node_modules/rx/dist/rx.js:5407:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/ammulder/dev/dragonlock/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/Users/ammulder/dev/dragonlock/node_modules/rx/dist/rx.js:63:31)
...
```

#### What behavior are you expecting?

Either shows a list of pages to pick from, or using arrow keys shows options to pick from, or lets me type in a name, and doesn't blow up.

**Steps to reproduce:**
1. Generate an app from the "sidemenu" template
2. `ionic generate`
3. Answer directive, some name, n

**Post the output of `ionic info` below please**
```
  Your system information:

    Cordova CLI:  You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: OS X El Capitan
    Node Version: v6.10.0
    Xcode version: Xcode 8.2.1 Build version 8C1002
```
**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
@ammulder As you may know, Ionic 4 will use Angular CLI for generators. This issue will be resolved in v4. Closing this to clean up the repo a bit. Thanks!
