### ISSUE TITLE
ionic cordova emulate android -l shows "The webpage at http://undefined:8100/ could not be loaded..."

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2104]
_From @terravibe on April 14, 2017 20:33_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When i run "ionic cordova emulate android -l", the emulation says:
"Webpage not available
The webpage at http://undefined:8100 could not be loaded because:
net::ERR_NAME_NOT_RESOLVED"
Without the -l, it's working as should, on ionic serve it's runs too.

**Expected behavior:**

The emulation should work.

**Steps to reproduce:**

I have no idea how can be the localhost undefined at the livereload enabled emulation.

**Related code:**

```
The terminal output from 'ionic cordova run android -l':
  Starting app-scripts server: --livereload --address 0.0.0.0 --port 8100 --livereload-port 35729 --iscordovaserve --externalIpRequired --nobrowser
[22:15:35]  watch started ...
[22:15:35]  build dev started ...
[22:15:35]  clean started ...
[22:15:35]  clean finished in 5 ms
[22:15:35]  copy started ...
[22:15:35]  transpile started ...
[22:15:38]  transpile finished in 3.20 s
[22:15:39]  preprocess started ...
[22:15:39]  deeplinks started ...
[22:15:39]  deeplinks finished in 56 ms
[22:15:39]  preprocess finished in 57 ms
[22:15:39]  webpack started ...
[22:15:39]  copy finished in 3.50 s
[22:15:47]  webpack finished in 8.71 s
[22:15:47]  sass started ...
[22:15:48]  sass finished in 1.13 s
[22:15:48]  postprocess started ...
[22:15:49]  postprocess finished in 295 ms
[22:15:49]  lint started ...
[22:15:49]  build dev finished in 13.42 s
[22:15:49]  watch ready in 13.54 s
[22:15:49]  dev server running: http://localhost:8100/
....
Executing cordova command: cordova emulate android - done!

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.9.0


```

_Copied from original issue: driftyco/ionic#11229_

**Comment by mwaa** [comment]
With version 3.0.0-beta9 this is no longer an issue as tested on 

npm (global):

    @ionic/cli-utils : 1.0.0-beta0
    cordova          : 6.5.0
    ionic            : 3.0.0-beta9

npm (local):

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.0.0-beta0
    @ionic/cli-plugin-ionic-angular : 1.0.0-beta0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by wearetelescopic** [comment]
Same issue here - livereload doesn't work on android,

error shows "The webpage at http://undefined:8100 could not be loaded because"

If i try and set the IP address directly with:

`ionic cordova run android -l --address xxx.xxx.xx.x`

shows the following:

```
Error: The platform "192.168.0.15" does not appear to have been added to this project.


[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova run android 192.168.0.15 (exit code 1).
```


```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
@wearetelescopic That's an entirely different error. Please try updating your CLI plugins.

**Comment by TheCorbin** [comment]
Hmm, We're still having this issue in 2018.  Did anyone find a solution?

**Comment by dwieeb** [comment]
@TheCorbin `ionic info` ?

**Comment by abraham** [comment]
```
cli packages: (/Users/abraham/.nvm/versions/node/v8.9.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/abraham/Library/Android/sdk

Misc:

    backend : pro
```

**Comment by TheCorbin** [comment]
@dwieeb Abraham has our details above.

**Comment by dwieeb** [comment]
@abraham @TheCorbin Check `config.xml`. Perhaps the URL was leftover in there?

**Comment by abraham** [comment]
Switching from enterprise wifi to standard pre-shared secret wifi fixed the issue for us.
