### ISSUE TITLE
Ionic ngc failed with ionic build android --prod

### ISSUE THREAD

**Issue by gkiran1** [ionic-team/ionic-cli#2122]
Below is Error and tsconfig. 

> ionic-app-scripts build "--prod"

[16:05:41]  ionic-app-scripts 1.3.4
[16:05:41]  build prod started ...
[16:05:41]  clean started ...
[16:05:41]  clean finished in less than 1 ms
[16:05:41]  copy started ...
[16:05:41]  ngc started ...
[16:05:43]  ionic-app-script task: "build"
[16:05:43]  TypeError: Cannot read property 'codeGen' of undefined
TypeError: Cannot read property 'codeGen' of undefined
    at Object.doCodegen (F:\Councils-Code\node_modules\@ionic\app-scripts\dist\a
ot\codegen.js:6:50)
    at F:\Councils-Code\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js
:42:30

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--" "--prod"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! councils@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
npm ERR! 

TsConfig

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}

Ionic Info:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.5
Xcode version: Not installed

**Comment by danbucholtz** [comment]
Hi - how can I recreate this issue?

Thanks,
Dan

**Comment by JohnKimDev** [comment]
I have same issue. 
@danbucholtz , you can reproduce this issue by 
`ionic build --prod`

**Comment by ourarash** [comment]
I have the same issue

**Comment by matheusjov** [comment]
I have the same issue
:(

**Comment by rudolfnoe** [comment]
I have the same issue. Here mey ionic info output:
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.0
Xcode version: Not installed

**Comment by apolishch** [comment]
I have the same issue:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.2
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.2
Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by peterhoang064** [comment]
I have the same issue by running ionic build android --prod --release

**Comment by nnonimus** [comment]
same issue

ordova CLI: 7.0.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.3

**Comment by brunosfreitas** [comment]
I'm also getting this error right now...

**Comment by matheusjov** [comment]
@brunosfreitas Update your native plugins, that solved for me, I had this same problem yesterday
