### ISSUE TITLE
Android Emulator specify debug keystore.

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2127]
_From @ianlintner-wf on April 21, 2017 15:48_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When running emulate the application currently uses the default Android debug key when building the APK. 

**Expected behavior:**
The feature I would like is a ionic/build config to specify a different keystore.

**Steps to reproduce:**
ionic emulate android --live-reload --target="my-device"
 

_Copied from original issue: driftyco/ionic#11311_

**Comment by dwieeb** [comment]
Use `ionic cordova run --help` in the latest CLI to find out how.
