### ISSUE TITLE
Ionic ios build failed Error code 65 for command: xcodebuild with args: -xcconfig

### ISSUE THREAD

**Issue by vahidvdn** [ionic-team/ionic-cli#2133]
I'm trying to build ios version of my app (I'm using MacinCloud)
When I run `ionic build ios` or `ionic emulate ios`, I get the following errors:

```

** BUILD FAILED **
Error code 65 for command
```

**Comment by jfchatelain** [comment]
Hi any hints on this. I'm receiving the same error. Thanks for your help.

**Comment by vahidvdn** [comment]
@jfchatelain I built my app by ionic package.
