### ISSUE TITLE
v3 - syntax error in package.json are not reported to the console

### ISSUE THREAD

**Issue by marcorosi** [ionic-team/ionic-cli#2152]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

syntax errors in package.json are not reported to the console and ionic serve starts the local server even if the application files was not correctly generated

#### What behavior are you expecting?

if there is a syntax error in package.json the console should report it and stop processing

here is an example with the same project and version ionic-cli version 2.2.3:

```
$ ionic serve -lcs

SyntaxError: /home/marco/work/app-docenti/docenti-mobile/package.json: Unexpected token ] in JSON at position 1721
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.loadNpmScripts (/usr/local/nvm/versions/node/v6.10.0/lib/node_modules/ionic/lib/cli.js:372:23)
    at Object.runr (/usr/local/nvm/versions/node/v6.10.0/lib/node_modules/ionic/lib/cli.js:172:26)
    at /usr/local/nvm/versions/node/v6.10.0/lib/node_modules/ionic/lib/cli.js:54:9 
```

**Steps to reproduce:**

just put an extra comma in a valid package.json and run 'ionic serve'

**Post the output of `ionic info` below please**

npm (global):

    @ionic/cli-utils : 0.0.12
    cordova          : 6.5.0 
    ionic            : 3.0.0-beta8

npm (local):

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 0.0.13
    @ionic/cli-plugin-ionic-angular : 0.0.7
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v7.9.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by danbucholtz** [comment]
We will fix this eventually but this is low priority for us. Sorry.

Thanks,
Dan

**Comment by dwieeb** [comment]
The latest CLI prints this:

```
[ERROR] Could not parse package.json. Is it a valid JSON file?
```

Which I think is a lot better. So, closing this issue.
