### ISSUE TITLE
ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

### ISSUE THREAD

**Issue by PrasadD7** [ionic-team/ionic-cli#2167]
Co
[npm-debug.txt](https://github.com/driftyco/ionic-cli/files/963470/npm-debug.txt)

Complete description ::

module.js:327
    throw err;
    ^

Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\LENOVO\Desktop\newApp\newApp\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@0.0.0 ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@0.0.0 ionic:serve script 'ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.

**Comment by danbucholtz** [comment]
Hi,

How can I recreate this issue? I have never heard of this issue before.

Thanks,
Dan

**Comment by TShelton41** [comment]
I'm having the same issue. I just upgraded everything 
ionic version v2.2.3  
cordova v6.5.0
node v4.6.0
npm v2.15.9

I then just ran ionic start project-name blank. Once complete I put ionic serve then I got this error. 
Any help would be great.

**Comment by TShelton41** [comment]
So here is how I was able to get my project to run. I put in the command

`ionic start project-name blank --v2`

I didn't think we needed to do that anymore, but to recreate the issue if you build your project like this. 

`ionic start project-name blank`

and then try to serve it will throw the error. 

So do we need to put --v2?

**Comment by PrasadD7** [comment]
I got the solution myself. I installed both the versions of node.js and then restarted the PC. And then entered "ionic start project_name --v2", changed directory and  then "ionic serve". It worked...

**Comment by xinyueyang** [comment]
I had the same issue. I was developing an Ionic 2 app for the past three months. It has been working great until three days ago this error coming out. App is not compiled anymore. I have tried everything found on various forum and had no luck. Please help, great appreciated. Here is npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'bug',
1 verbose cli   'iinsight' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly fetchPackageMetaData iinsight
5 silly fetchNamedPackageData iinsight
6 silly mapToRegistry name iinsight
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'iinsight',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'iinsight',
9 silly mapToRegistry   name: 'iinsight',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/iinsight
11 verbose request uri https://registry.npmjs.org/iinsight
12 verbose request no auth needed
13 info attempt registry request try #1 at 11:04:36 AM
14 verbose request id 6cda2af4d69b061c
15 http request GET https://registry.npmjs.org/iinsight
16 http 404 https://registry.npmjs.org/iinsight
17 verbose headers { 'content-type': 'application/json',
17 verbose headers   'cache-control': 'max-age=0',
17 verbose headers   'content-length': '2',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Thu, 04 May 2017 16:04:34 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-ord1739-ORD',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1493913874.415075,VS0,VE161',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 404,
18 silly get   { 'content-type': 'application/json',
18 silly get     'cache-control': 'max-age=0',
18 silly get     'content-length': '2',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Thu, 04 May 2017 16:04:34 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-ord1739-ORD',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1493913874.415075,VS0,VE161',
18 silly get     vary: 'Accept-Encoding' } ]
19 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/iinsight
19 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
19 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
19 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
19 silly fetchPackageMetaData  error for iinsight { Error: Registry returned 404 for GET on https://registry.npmjs.org/iinsight
19 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
19 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
19 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12) pkgid: 'iinsight', statusCode: 404, code: 'E404' }
20 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/iinsight
20 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
20 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
20 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
20 verbose stack     at emitTwo (events.js:106:13)
20 verbose stack     at Request.emit (events.js:191:7)
20 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
20 verbose stack     at emitOne (events.js:96:13)
20 verbose stack     at Request.emit (events.js:188:7)
20 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
21 verbose statusCode 404
22 verbose pkgid iinsight
23 verbose cwd C:\Development\angular2\Ionic2App\iinsight
24 error Windows_NT 10.0.14393
25 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "bug" "iinsight"
26 error node v6.10.3
27 error npm  v3.10.10
28 error code E404
29 error 404 Registry returned 404 for GET on https://registry.npmjs.org/iinsight
30 error 404
31 error 404 'iinsight' is not in the npm registry.
32 error 404 You should bug the author to publish it (or use the name yourself!)
33 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]
