### ISSUE TITLE
Rename ionic to @ionic/cli

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/ionic-cli#2173]
Hey,
I just want to know if the CLI will be renamed to match the other Ionic packages.

In my opinion, it will be much better to rename all Ionic packages to @ionic/package-name like @ionic/native etc. Also, the ionic-angular package could be renamed to @ionic/angular.

**Comment by wbhob** [comment]
I suggested @ionic/framework a few months ago, I am stil a fan of that.

**Comment by piotrowski** [comment]
As I just installed `@angular/cli` I was reminded of this and will abuse this comment to +1 this idea. So very much.
