### ISSUE TITLE
No Windows Support for `ionic cordova resources`

### ISSUE THREAD

**Issue by zoinkydoink** [ionic-team/ionic-cli#2174]
Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
`3.0.0-beta10`

#### Short description of the problem:
`ionic cordova resources windows` does nothing, running the same command for android creates all the icons

#### What behavior are you expecting?
Expecting the resources to be generated

**Steps to reproduce:**
1. run `ionic cordova resources windows`
2. 
`
✔ Collecting resource configuration and source images - done!

✔ Uploading source images to prepare for transformations - done!

✔ Generating platform resources: 0 / 0 complete - done!

✔ Modifying config.xml to add new image resources - done!
`

**Post the output of `ionic info` below please**
`

    npm (global):

    @ionic/cli-utils : 1.0.0-beta1
    cordova          : 6.5.0
    ionic            : 3.0.0-beta10

    npm (local):

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.0.0-beta1
    @ionic/cli-plugin-ionic-angular : 1.0.0-beta1
    Ionic Framework                 : ionic-angular 3.0.1

    System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
Windows support hasn't been a priority for the beta. It would be a useful feature sometime down the road.

**Comment by digaus** [comment]
Was reported already 1 year ago... Ionic officially supports windows so generating icons and splashscreens should be part of it https://github.com/ionic-team/ionic-cli/issues/628

**Comment by dwieeb** [comment]
@zoinkydoink @digaus Just so we're clear, we're talking about the `windows` Cordova platform, not `wp8`, right?

**Comment by digaus** [comment]
@dwieeb
Yes

**Comment by ToomasT** [comment]
As a workaround, create the enlisted image files under the resources windows folder and add the following to config.xml:

```
    <platform name="windows">
        <icon src="resources/windows/storelogo.png" target="StoreLogo" />
        <icon src="resources/windows/smalllogo.png" target="Square30x30Logo" />
        <icon src="resources/windows/Square44x44Logo.png" target="Square44x44Logo" />
        <icon src="resources/windows/Square70x70Logo.png" target="Square70x70Logo" />
        <icon src="resources/windows/Square71x71Logo.png" target="Square71x71Logo" />
        <icon src="resources/windows/Square150x150Logo.png" target="Square150x150Logo" />
        <icon src="resources/windows/Square310x310Logo.png" target="Square310x310Logo" />
        <icon src="resources/windows/Wide310x150Logo.png" target="Wide310x150Logo" />
    </platform>
```

_where storelogo.png is 50px by 50px, and smalllogo.png 30px by 30px._

Based on https://cordova.apache.org/docs/en/latest/config_ref/images.html#windows

**Comment by VahidNaderi** [comment]
Why hasn't it  implemented yet? Maybe I can contribute to this if I know why it's not done yet.

**Comment by dwieeb** [comment]
@VahidNaderi Just been focused on higher priority stuff. Lots on my plate. I would welcome a PR. Let me know if you need pointers in the right direction or help of any kind.

**Comment by VahidNaderi** [comment]
@dwieeb I created a fix but I have problem debugging it, can you provide me some guidance toward attaching a debugger and tracing cli code? I'm not that familiar with this environment.

**Comment by dwieeb** [comment]
@VahidNaderi Sure! I added a section in `CONTRIBUTING.md` for this: https://github.com/ionic-team/ionic-cli/blob/master/CONTRIBUTING.md#debugging

**Comment by bobpearson** [comment]
If anyone needs a script for making the icons,   put this script in your /src/ directory, add imagemagick to your package.json,   use the config.xml snip thaat ThomasT posted above:

```
<platform name="windows">
        <icon src="resources/windows/storelogo.png" target="StoreLogo" />
        <icon src="resources/windows/smalllogo.png" target="Square30x30Logo" />
        <icon src="resources/windows/Square44x44Logo.png" target="Square44x44Logo" />
        <icon src="resources/windows/Square70x70Logo.png" target="Square70x70Logo" />
        <icon src="resources/windows/Square71x71Logo.png" target="Square71x71Logo" />
        <icon src="resources/windows/Square150x150Logo.png" target="Square150x150Logo" />
        <icon src="resources/windows/Square310x310Logo.png" target="Square310x310Logo" />
        <icon src="resources/windows/Wide310x150Logo.png" target="Wide310x150Logo" />
        <splash src="resources/windows/splashscreen.png" target="SplashScreen" />
    </platform>
```
 and run this:

```
const path = require("path");
const fs = require("fs");
const promisify = require("util").promisify;
const im = require('imagemagick');

const p_stat = promisify(fs.stat);
const p_mkdir = promisify(fs.mkdir);
const p_resize = promisify(im.resize);


function trace(msg) {
	console.log(msg);
}

function err(msg) {
	console.error(msg);
}

const iconOutputs = [{
		name: "storelogo.png",
		width: 50,
		height: 50
	},
	{
		name: "smalllogo.png",
		width: 30,
		height: 30
	},
	{
		name: "Square44x44Logo.png",
		width: 44,
		height: 44
	},
	{
		name: "Square70x70Logo.png",
		width: 70,
		height: 70
	},
	{
		name: "Square71x71Logo.png",
		width: 71,
		height: 71
	},
	{
		name: "Square150x150Logo.png",
		width: 150,
		height: 150
	},
	{
		name: "Square310x310Logo.png",
		width: 310,
		height: 310
	},
	{
		name: "Wide310x150Logo.png",
		width: 310,
		height: 150
	}
];

const splashOutputs = [{
	name: "splashscreen.png",
	width: 620,
	height: 300
}, ];

class WindowsIcons {
	constructor() {
		this.resourceDir = path.resolve(__dirname, "..", "resources");
		this.resourceWinDir = path.join(this.resourceDir, "windows");
		this.iconFile = path.join(this.resourceDir, "icon.png");
		this.splashFile = path.join(this.resourceDir, "splash.png");
	}

	async checkIconFile() {
		const f = this.iconFile;
		const stat = await p_stat(f);
		if (stat.isFile()) {
			trace(`icon file '${f}' exists`);
			return true;
		} else {
			err(`icon file ${f} does not exist`);
			return false;
		}
	}

	async checkSplashFile() {
		const f = this.splashFile;
		const stat = await p_stat(f);
		if (stat.isFile()) {
			trace(`splash file '${f}' exists`);
			return true;
		} else {
			err(`splash file ${f} does not exist`);
			return false;
		}
	}

	async checkWinDir() {
		const f = this.resourceWinDir;
		try {
			const stat = await p_stat(f);
			trace(`windows resource directory '${f}' exists`);
		} catch (e) {
			try {
				await (p_mkdir(f));
				trace(`windows resource directory '${f}' created`);
				return true;
			} catch (e) {
				trace(`windows resource directory '${f}' not created: ${e}`);
				return false;
			}
		}
		return true;
	}

	async makeIcons() {
		for (let icon of iconOutputs) {
			const srcPath = this.iconFile;
			const dstPath = path.join(this.resourceWinDir, icon.name);
			const opts = {
				srcPath,
				dstPath,
				quality: 1,
				format: 'png',
				width: icon.width,
				height: icon.height
			};
			try {
				await p_resize(opts);
				trace(`created '${dstPath}'`)
			} catch (e) {
				err(`creation of '${dstPath}' failed`);
				return false;
			}
		}
		return true;
	}

	async makeSplash() {
		for (let icon of splashOutputs) {
			const srcPath = this.splashFile;
			const dstPath = path.join(this.resourceWinDir, icon.name);
			const opts = {
				srcPath,
				dstPath,
				quality: 1,
				format: 'png',
				width: icon.width,
				height: icon.height
			};
			try {
				await p_resize(opts);
				trace(`created '${dstPath}'`)
			} catch (e) {
				err(`creation of '${dstPath}' failed`);
				return false;
			}
		}
		return true;
	}

	async execute() {
		const hasIcon = await this.checkIconFile();
		if (!hasIcon) {
			return false;
		}
		const hasSplash = await this.checkSplashFile();
		if (!hasSplash) {
			return false;
		}
		const hasOutput = await this.checkWinDir();
		if (!hasOutput) {
			return false;
		}
		const iconsMade = await this.makeIcons();
		if (!iconsMade) {
			return false;
		}
		const splashMade = await this.makeSplash();
		if (!splashMade) {
			return false;
		}
		return true;
	}
}

async function runme() {
	const wi = new WindowsIcons();
	const res = await wi.execute();
	if (res) {
		console.log("Success");
		process.exit(0);
	} else {
		console.error("Failure");
		process.exit(-1);
	}
}

runme();
```

**Comment by dwieeb** [comment]
This should be resolved as of Ionic CLI 5.

Please update and test:

```
npm i -g ionic@latest
npm i -g cordova-res
ionic cordova resources
```

Please create new issues for feedback or bug reports.

**Comment by aharonlis** [comment]
Ionic cli 5.2.6 and still this doesn't work

**Comment by dwieeb** [comment]
Subscribe to https://github.com/ionic-team/cordova-res/pull/41 for adding support for the Windows platform.

**Comment by pjc2007** [comment]
@bobpearson - Thanks for that script

> If anyone needs a script for making the icons, put this script in your /src/ directory, add imagemagick to your package.json, use the config.xml snip that ThomasT posted above. It expects the files "resources/icon.png" and "resources/splash.png" to exist.

But I tried running it, and get the error 
```
node platform_build_files\\windows\\create-resources.js
icon file 'D:\devmyApp\resources\icon.png' exists
splash file 'D:\devmyApp\resources\splash.png' exists
windows resource directory 'D:\devmyApp\resources\windows' exists
creating 'D:\devmyApp\resources\windows\storelogo.png'
creation of 'D:\devmyApp\resources\windows\storelogo.png' failed: Error: Command failed: Invalid Parameter - -set

Failure
```
Thats after adding a couple of tracing lines in makeIcon()', and adjusting resource path since I put the script in a sub folder - all the paths do look correct

```
 try {
        trace(`creating '${dstPath}'`)
        await p_resize(opts);
        trace(`created '${dstPath}'`)
      } catch (e) {
        err(`creation of '${dstPath}' failed: ${e}`);
        return false;
      }
```
