### ISSUE TITLE
v3-rc0: Different handling of commands outside of project directory

### ISSUE THREAD

**Issue by piotrowski** [ionic-team/ionic-cli#2181]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc.0

#### Short description of the problem:

`ionic upload` and `ionic cordova build ios` are handled differently when run outside of project directory:
```
PS C:\Users\Jan\Documents> ionic upload
[ERROR] Sorry! ionic upload can only be run in an Ionic project directory.
```
```

PS C:\Users\Jan\Documents> ionic cordova build ios
[ERROR] Unable to find command: cordova build ios
        You may need to be in an Ionic project directory.

   _             _
  (_)           (_)
   _  ___  _ __  _  ___
  | |/ _ \| '_ \| |/ __|
  | | (_) | | | | | (__
  |_|\___/|_| |_|_|\___|  CLI 3.0.0-rc.0


  Usage:

    $ ionic <command> [args/options]
    $ ionic help <command> (for command details)

  Global Commands:

    docs ................ Open the Ionic documentation website
    info ................ Print system/environment info
    login ............... Login with your Ionic ID
    signup .............. Create an Ionic account
    start ............... Create a new project

  Project Commands:

    You are not in a project directory.
```

#### What behavior are you expecting?

Same style of error message for all project commands outside of project directory.

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Ionic CLI        : 3.0.0-rc.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
The cordova commands are supplied by the locally installed plugin. 

This hints at an architecture problem with the CLI that I'm hoping to address soon. All the strange runtime errors are because we're sharing code between global and local installations. If the code interfaces don't line up perfectly, boom, you have an obscure error.

**Comment by dwieeb** [comment]
Actually, I'm not sure if there's much benefit to trying to fix this. The errors are technically correct...

**Comment by piotrowski** [comment]
Yes, not really a bug but maybe a "code smell": Same problem (You are outside project directory) is handled by two different "error handlers" depending on the command. Maybe just a code order thing, maybe bigger architecture problem not worth fixing.

**Comment by dwieeb** [comment]
It's because the cordova commands come from the cordova plugins. The `upload` command is a known "project" command, where as the cordova command is an unknown command (because it's a plugin). The cordova command is only known when inside an Ionic project with `@ionic/cli-plugin-cordova` installed.

**Comment by piotrowski** [comment]
Damn, makes sense.
