### ISSUE TITLE
npm ERR! Failed at the ionic-hello-world@0.0.0 ionic:serve script 'ionic-app-scripts serve "--v2" "--lab" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.

### ISSUE THREAD

**Issue by Naminator69** [ionic-team/ionic-cli#2196]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`

2.2.1

#### Short description of the problem:

Can't launch my ionic app all of a sudden

#### What behavior are you expecting?

the app launches in the lab like the other 3893e5 times

**Steps to reproduce:**
1.type ionic serve projectName -l
2. get errors in console
3. be sad

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (C:\Users\Vince\playersOnCall2\node_modules\source-map\lib\source-node.js:115:26)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\Vince\playersOnCall2\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (C:\Users\Vince\playersOnCall2\node_modules\source-map\lib\source-node.js:80:24)
    at SourceMapSource.node (C:\Users\Vince\playersOnCall2\node_modules\webpack-sources\lib\SourceMapSource.js:42:20)
    at ReplaceSource.node (C:\Users\Vince\playersOnCall2\node_modules\webpack-sources\lib\ReplaceSource.js:69:29)
    at CachedSource.node (C:\Users\Vince\playersOnCall2\node_modules\webpack-sources\lib\CachedSource.js:12:23)
    at C:\Users\Vince\playersOnCall2\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\Users\Vince\playersOnCall2\node_modules\webpack-sources\lib\ConcatSource.js:39:60)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--lab" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@0.0.0 ionic:serve: `ionic-app-scripts serve "--v2" "--lab" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@0.0.0 ionic:serve script 'ionic-app-scripts serve "--v2" "--lab" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--v2" "--lab" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Vince\playersOnCall2\npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve

attached is the log

[npm-debug - Copy.txt](https://github.com/driftyco/ionic-cli/files/970412/npm-debug.-.Copy.txt)

**Comment by manueloleaga** [comment]
Same Error, Same Version...  #BeSad jajajajj

**Comment by markiam11** [comment]
SAME error.. anyone already resolve this? i need help

**Comment by dwieeb** [comment]
Upgrade to CLI 3 and if this is still an issue, create a new issue.
