### ISSUE TITLE
Error -There is a problem parsing the package when installing apk  generated by Ionic 2 project

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2200]
_From @dulajsan on April 29, 2017 3:46_

**Reason for opening issue**

When I try to install ionic2 generated apk in android it shows the above issue.
android version 4.0.4
I executed following command to generate apk

 **Steps that I followed**

1.ionic platform add android
2.ionic build --release android

**alternative steps that I followed**
ionic build  android

**Other information**

$ ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.10.1
Xcode version: Not installed

******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

$ cordova -v

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

_Copied from original issue: driftyco/ionic-app-scripts#942_

**Comment by dwieeb** [comment]
@dulajsan Please update to the latest CLI and make a new issue if this is still a problem.
