### ISSUE TITLE
feature(v3): ionic info --> Android SDK

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/ionic-cli#2205]
#### Short description of the problem:
It would be great if the CLI gives some information about the installed AndroidSDK and the Installed JavaJDK. I often read questions in the forum and at the end, the AndroidSDK is missing or the installed version was too old.

Actually, the command `cordova requirements` can do that but only inside a Cordova / Ionic project

#### What behavior are you expecting?

```bash
$ ionic info

global packages:

    @ionic/cli-utils : 1.0.0-rc.1
    Ionic CLI        : 3.0.0-rc.1

System:

    Node                  : v7.9.0
    OS                      : Windows 10
    AndroidSDK       : 26
    JDK                     : 1.8.0_131
    Xcode                 : not installed
    ios-deploy          : not installed
    ios-sim                : not installed
```

**Comment by piotrowski** [comment]
`cordova requirements` already does something like that, so maybe an implementaion can be "inspired" by what they are doing:

```
PS C:\Users\Jan\Documents\rc0test> cordova requirements

Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: not installed
cmd: Command failed with exit code 1
Gradle: installed C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle

Requirements check results for ios:
Apple OS X: not installed
Cordova tooling for iOS requires Apple OS X
Error: Some of requirements check failed
```

**Comment by MTechDE** [comment]
Yes becuase actually i

**Comment by dwieeb** [comment]
I agree. We'll look at this after our stable release 👍
