### ISSUE TITLE
Cant build for iOS since Update

### ISSUE THREAD

**Issue by nivida** [ionic-team/ionic-cli#2209]
#### Output of `ionic --version`
3.0.0-rc.1-alpha.2bb303a6

#### Short description of the problem:
I start with "ionic cordova build ios" and become an Error:

```
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Sam/Documents/BadenfahrtAPP/platforms/ios/cordova/build-debug.xcconfig,-workspace,Badenfahrt.xcworkspace,-scheme,Badenfahrt,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/Sam/Documents/BadenfahrtAPP/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Sam/Documents/BadenfahrtAPP/platforms/ios/build/sharedpch
```

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### What behavior are you expecting?
Build without Error

**Post the output of `ionic info` below please**
global packages:

    @ionic/cli-utils : 1.0.0-rc.1-alpha.2bb303a6
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.1-alpha.2bb303a6

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.1-alpha.2bb303a6
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.1-alpha.2bb303a6
    Ionic Framework                 : ionic-angular 3.1.0

System:

    Node       : v6.9.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.0
    ios-sim    : 5.0.11

**Comment by sfabriece** [comment]
@nivida did you find a temporary fix for this?

**Comment by jumong** [comment]
How to Fix ?

**Comment by raugaral** [comment]
you are using alpha versions, update the packages and try again

**Comment by dwieeb** [comment]
@nivida Please update to the latest CLI and make a new issue if this is still a problem.
