### ISSUE TITLE
(v3)linting is not working..

### ISSUE THREAD

**Issue by sfabriece** [ionic-team/ionic-cli#2218]
What version of the CLI are you using? Output of ionic --version

3.0.0-rc.1

Short description of the problem:

if have the following script defined in 'package.json'

`"lint": "ionic-app-scripts lint"` 

When I run it, doesn't produce any errors even though vscode is showing the errors.

the output

```
> ionic-app-scripts lint

[10:54:42]  ionic-app-scripts 1.3.7
[10:54:42]  lint started ...
[10:54:46]  lint finished in 3.28 s
```

What behavior are you expecting?

linting to work

Post the output of ionic info below please

global packages:

    @ionic/cli-utils : 1.0.0-rc.1
    Ionic CLI        : 3.0.0-rc.1

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.1
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.8.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by danielsogl** [comment]
Hey,

thank you for opening an issue here.

This issue has nothing to do with the Ionic CLI and relates to ionic-app-scripts: https://github.com/driftyco/ionic-app-scripts

But I also can't reproduce your error. Can you open your issue again on the app-scripts repo and post your code you want to lint?

Thank you
