### ISSUE TITLE
v3: Notify v2 Users

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2220]
Random thought:

When v3 gets released parts of the documentation and blog posts will change to the new `ionic cordova` command. This will cause problems for all the people still using the v2 CLI - and let's be honest, they will exist. 

It would be a simple solution to this problem to just add the `ionic cordova` command as a alias for `ionic` itself to v2. With this, no harm done if they try to execute one of the newly namespaced commands.

**Comment by dwieeb** [comment]
Even if we add that, people would need to update their CLI versions anyway to see it.

CLI v2 has a server notification feature that we're planning to use to notify people about v3. We'll want everyone to switch over as there should be no reason to stick to v2.
