### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by zindelluib** [ionic-team/ionic-cli#2241]
I upgraded my ionic version and an error appears when I run it in Windows cmd

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at Project.BaseConfig (C:\Users\zindel\AppData\Roaming\npm\node_modules\ioni
c\node_modules\@ionic\cli-utils\dist\lib\config.js:27:30)
    at Project (C:\Users\zindel\AppData\Roaming\npm\node_modules\ionic\node_modu
les\@ionic\cli-utils\dist\lib\project.js:25:1)
    at C:\Users\zindel\AppData\Roaming\npm\node_modules\ionic\dist\index.js:54:2
5
    at next (native)
    at fulfilled (C:\Users\zindel\AppData\Roaming\npm\node_modules\ionic\dist\in
dex.js:4:58)

When I try to ionic serve  this appears
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[ERROR] No updates found after plugin error--please report this issue.

Ionic Version :  3.0.0
Cordova : 7.0.0
Node Version : 6.10.3
NPM : 4.5.0

**Comment by Petruccini** [comment]
Same here and curiously same versions

**Comment by msudharsanam** [comment]
all ionic commands give this error after I upgraded to ionic3.0.0.

**Comment by piotrowski** [comment]
Herre is @Petruccini 's forum post with additional information:
https://forum.ionicframework.com/t/typeerror-path-must-be-a-string-received-undefined/89647

**Comment by dwieeb** [comment]
@zindelluib Does `ionic info` work for you?

**Comment by c350156378** [comment]
the same issue

**Comment by techhunting** [comment]
I am getting the same issue while creating a project

**Comment by dwieeb** [comment]
@techhunting @c350156378 @zindelluib All on Windows 10?

**Comment by c350156378** [comment]
@dwieeb 

upgrade to 2.2.3, works again. 

`$ ionic info

Your system information:

Cordova CLI: 7.0.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.0
Xcode version: Not installed
`

**Comment by zindelluib** [comment]
@dwieeb  Windows 8.1

**Comment by piotrowski** [comment]
Another one on Win10: v

**Comment by dwieeb** [comment]
@zindelluib We're not able to reproduce this on our Windows machine, but I may have found the offending line. Can you try with the latest alpha version? `npm i -g ionic@canary`

**Comment by Jigglypow** [comment]
@dwieeb I got the same error and tried the latest alpha vesion -> didn't work.
I reinstalled my whole environment completely new just a few hours ago and got the error since then.

ionic v3.0.0 and 3.0.0-alpha.256503ea
cordova 7.0.0
and newest nodejs v7.10.0 (if that matters?)

**Comment by zindelluib** [comment]
@dwieeb  I just reverted version to 2.2.3

**Comment by c350156378** [comment]
@dwieeb 
uninstall the current and install the beta and it works 
`$ ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

global packages:

    @ionic/cli-utils : 1.0.0-alpha.8fcb0a8d
    Ionic CLI        : 3.0.0-alpha.8fcb0a8d

System:

    Node       : v6.10.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
`

**Comment by nagarajusomalraju** [comment]
Getting the same error while creating new project ot ionic -v or ionic info

Plz help find a solution asap

**Comment by LeandroBernardino** [comment]
Guys, please! Let's keep it simple! Noob's asking.

What's the **solution** for the following problem?
I've ran the commands "ionic serve" and"ionic -info" in my Git CLI.

The output, and I quote, is:
"
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
Checking for CLI updates now...
[ERROR] No updates found after plugin error--please report this issue.
global packages:
@ionic/cli-utils : 1.0.0
Ionic CLI        : 3.0.0
System:
Node       : v7.9.0
OS         : Windows 10
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed
"
End quote.

![image](https://cloud.githubusercontent.com/assets/22240062/26012690/c608ca16-372b-11e7-9144-6247493de76f.png)

Thank you!

**Comment by piotrowski** [comment]
@LeandroBernardino Your problem is totally different from the one you responded to (different error message) and probably solved by following this: https://github.com/driftyco/ionic-cli#existing-project

**Comment by LeandroBernardino** [comment]
@piotrowski as u've seen, i'm no good reader also. Srry. I'll give it a try. Tks!

**Comment by AnasAl-qudah** [comment]
I have the same error when i tried to create new ionic project  :

TypeError: Path must be a string. Received undefined
at assertPath (path.js:7:11)
at Object.resolve (path.js:186:7)

Please can you advice how to fix this error .

Best regards

**Comment by lucifer-AM** [comment]
I have the same error with all the ionic cli commands after I upgraded ionic to the latest version. Currently I have downgraded the ionic to v2.2.3. Hope for a fix soon. Thanks in advance.

**Comment by tocanto** [comment]
Hi @dwieeb 
In what folder I can change this files? I got the same problem

**Comment by dwieeb** [comment]
@tocanto If you want to try using the alpha CLI with this fix in it: `npm i -g ionic@canary`
