### ISSUE TITLE
Slow connection blocks the start of command execution

### ISSUE THREAD

**Issue by Manduro** [ionic-team/ionic-cli#2259]
#### Short description of the problem:
Try running `ionic serve` on a *really* slow connection. I noticed it doesn't start doing anything until after a 5-10 seconds. On a good connection it works fine. Disabling telemetry solved this. 

#### What behavior are you expecting?
The telemetry calls are done async and do not block the awesome new CLI speediness.

**Post the output of `ionic info` below please**
```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.9.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```

**Other information:**

Thanks for the `ionic ionitron` t-shirt ;)

**Comment by dwieeb** [comment]
The telemetry stuff is async. (see https://github.com/driftyco/ionic-cli/blob/master/packages/cli-utils/src/lib/command/command.ts#L61-L80). 

I'm wondering how it could slow down serve...

**Comment by Manduro** [comment]
Hmm, did some more testing and it still happens with telemetry off, so it must be something else. The delay is definitely there on a slow connection. Of course it's inconsistent, like the connection, so it's hard to track, but it does not appear to be just `serve`.

I'll keep an eye out and report back when I find out more.

**Comment by Manduro** [comment]
@dwieeb Still experiencing this. The title of the terminal window mentions `npm` when it happens. Just now it was just hanging there forever, while I was not connected to any network. Some `npm` task runs before `ionic serve`? Using `npm@4.6.1`.

**Comment by dwieeb** [comment]
@Manduro We occasionally check for CLI updates at the start of a fresh "session" (like, when you haven't used the CLI in an hour). We didn't assume no network connectivity when building the new CLI, so this may require additional work. As a workaround, you can delete the `lastCommand` key in `~/.ionic/config.json` and re-run serve. Let me know if that solves your issue.

**Comment by Manduro** [comment]
@dwieeb That explains a lot! Thanks for the info and workaround. 

Running that update check async with a timeout would be nice!

**Comment by dwieeb** [comment]
We can't really run it "async". Updates should probably happen before command execution, not indeterminately during command execution. I have plans for this!

Thank you!

**Comment by dwieeb** [comment]
Actually I'll leave this open.

**Comment by dwieeb** [comment]
See also https://github.com/driftyco/ionic-cli/issues/2335

**Comment by dwieeb** [comment]
Resolved through the new daemon, which can be totally disabled. Also resolved through `--no-interactive` flag.
