### ISSUE TITLE
console.log: deviceready has not fired after 5 seconds.

### ISSUE THREAD

**Issue by denisrai** [ionic-team/ionic-cli#2262]
After update to the new cli it's taking a long time to refresh the code using **ionic cordova run android --livereload -c -s**.

I've tried to reinstall all my plugins and nothing.
I've even tried to start a new blank app via **ionic start <folder> blank** and when I run on my android using --liverealod it's happening the same thing.

**Post the output of `ionic info` below please**
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

That's my log:

[15:35:13]  console.log: Angular is running in the development mode. Call enableProdMode() to enable the production
            mode.
[15:35:14]  console.log: OPEN database: _ionicstorage
[15:35:14]  console.log: new transaction is waiting for open operation
[15:35:14]  console.log: new transaction is waiting for open operation
[15:35:14]  console.log: OPEN database: _ionicstorage - OK
[15:35:14]  console.log: DB opened: _ionicstorage
**[15:35:14]  console.log: deviceready has not fired after 5 seconds.
[15:35:14]  console.warn: Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an
            inconsistent state. Try removing plugins from plugins/ and reinstalling them.**

That's my list of plugins:
cordova-plugin-ble-central 1.1.4 "BLE"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

Thank you,

**Comment by developer-prosenjit** [comment]
try ionic cordova run android --livereload -c -s --prod

**Comment by denisrai** [comment]
It's something to do with the tablet I'm testing with.
When I use my own mobile it works fine.

Thank you 😃

**Comment by ValentinMerlet** [comment]
Hi, I'm facing the same issue here. 

It happens on android only with or without livereload, I tried to reinstall every plugins I'm using, but still having the issue :/

I'm not using crosswalk.

**Comment by dwieeb** [comment]
This is just a warning. If your app is working, then you need not be concerned.

**Comment by ValentinMerlet** [comment]
Just a warning that cause ~15 seconds of waiting before the app starts :/

Running the app in prod environment with flag --prod did the trick for me : 
`ionic cordova run android --prod`

**Comment by Nitishreddy787** [comment]
I have chanced ionic storage to native storage.after making changes its showing white screen in log there are no errors related to that

**Comment by cyonusg** [comment]
2020:

i update my plugin cordova version and works for ios (13.3);

my problem was onFileSystemPathsReady not fired ready

- Cordova-plugin-file 6.0.3
-Cordova plugin-file-transfer 1.7.1
-cordova-plugin-code-push 1.11.18

i hope some help this help because documentation is scarce

**Comment by SusanOC** [comment]
> 2020:
> 
> i update my plugin cordova version and works for ios (13.3);
> 
> my problem was onFileSystemPathsReady not fired ready
> 
> * Cordova-plugin-file 6.0.3
>   -Cordova plugin-file-transfer 1.7.1
>   -cordova-plugin-code-push 1.11.18
> 
> i hope some help this help because documentation is scarce

May I know how do you fix this? what cordova version do you use?
