### ISSUE TITLE
How to trigger customized script in the build process

### ISSUE THREAD

**Issue by iron9light** [ionic-team/ionic-cli#2267]
When using ionic cli v2.x, I added my script in package.json this way:
```javascript
{
  "scripts": {
    "ionic:build": "ionic-app-scripts build --prod && npm run svgo",
    "ionic:serve": "ionic-app-scripts serve",
    "svgo": "svgo -f ./www/assets/img"
  },
}
```
Now with ionic cli v3, the `ionic:build` will be ignored.
Is there anyway to add my script?

Thanks.

**Comment by dwieeb** [comment]
It's something I'm thinking about. I'm thinking about the entire tooling chain we have for building Ionic apps. It's something that will be addressed in a later release.

**Comment by pickupman** [comment]
There certainly needs to be a way to customize the build command. We use commands to change  environment configuration to compile for `ionic serve` vs `ionic build`. It's done using a node script to copy in server urls.  Back in ionic  v1 we did this using hooks, and those went away.

**Comment by RyanHow** [comment]
This is a showstopper for me. And app-scripts has no way to put custom build steps in. Kinda stuck without any flexibility.

**Comment by dwieeb** [comment]
Hey all, the CLI now has [CLI Hooks](https://github.com/ionic-team/ionic-cli#cli-hooks) you can use to run npm scripts before and after the app-scripts build. It's the best I can do from my end in the short term. Let me know if this suits your needs.

**Comment by iva2k** [comment]
Looks like the hooks were moved to @ionic/cli-hooks [https://www.npmjs.com/package/@ionic/cli-hooks](https://www.npmjs.com/package/@ionic/cli-hooks)

**Comment by dwieeb** [comment]
@iva2k No, please ignore that package for now. Here is the updated link to CLI Hook docs: https://ionicframework.com/docs/cli/configuring.html#hooks

These may be changing slightly for v4.
