### ISSUE TITLE
Have to call `ionic` outside project directory first to make it work inside

### ISSUE THREAD

**Issue by piotrowski** [ionic-team/ionic-cli#2270]
... otherwise `TypeError: Cannot read property 'includes' of undefined`:

https://forum.ionicframework.com/t/ionic-serve-fails-with-error-on-cli-3-0-0/90110

**ionic info**

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 2.2.0

System:

    Node       : v7.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13

**Comment by dwieeb** [comment]
This is possibly the weirdest issue I've seen. Please chime in if you're also getting it. I have no idea how to reproduce.

**Comment by ryanrain** [comment]
first i upgraded from beta 7 because my uploaded snapshots weren't showing up:
```
sudo npm uninstall -g ionic
sudo npm install ionic@latest
```
ionic -v  now gives 3.0.0
cd to project/folder
ionic serve
...long wait and then same error "TypeError: Cannot read property 'includes' of undefined"

**Comment by dwieeb** [comment]
@ryanrain I think that's a different issue. You were using an ancient beta and then upgraded. Your plugins will need to be updated as well. 

https://github.com/driftyco/ionic-cli#existing-project

**Comment by ryanrain** [comment]
@dwieeb Thank you Dan you were totally right! Same error text that brought me here, but simply following instructions: 

    sudo npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest @ionic/cli-plugin-cordova@latest

did the trick. thanks again! ionic rocks!

**Comment by ryanrain** [comment]
ps. the whole typing ionic from outside the project folder routine never made any difference for me.
