### ISSUE TITLE
"CLI functionality may be limited." can also be caused by just not running `npm install`

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2296]
#### Short description of the problem:

I just downloaded an Ionic project and then ran `ionic info` in the project directory. I got this error:

```
PS C:\Users\Jan\Documents\Tenlan> ionic info
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[ERROR] No updates found after plugin error--please report this issue.

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

Running with `--verbose` it got expanded to this:

```
PS C:\Users\Jan\Documents\Tenlan> ionic info --verbose
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[DEBUG] Plugin error: Dependency missing for @ionic/cli-plugin-ionic-angular:

          [ERROR]: Cannot find module 'C:\Users\Jan\Documents\Tenlan\node_modules\@ionic\cli-plugin-ionic-angular'
[DEBUG] Checking for latest plugin version of ionic@latest.
"3.0.0"

[DEBUG] Latest version of ionic@latest is .
[DEBUG] !!! ERROR ENCOUNTERED !!!
SyntaxError: Unexpected end of JSON input
[DEBUG] SyntaxError: Unexpected end of JSON input
            at Object.parse (native)
            at C:\nvm\v6.10.2\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\plugins.js:212:36
            at next (native)
            at fulfilled (C:\nvm\v6.10.2\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\plugins.js:4:58)
```

**THEN** I remembered I actually hadn't run `npm install`! I expect this to be a quite common error. Could the CLI maybe catch this and improve the error messages?

#### What behavior are you expecting?

Something like this:

> Your project and installation seem to be just fine, but you <strike>idiot</strike> didn't run `npm install` yet so all the dependencies are missing. Please run `npm install` and then try again.

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by piotrowski** [comment]
After `npm install` I get this, as expected, all good:

```
PS C:\Users\Jan\Documents\Tenlan> ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
I've never been able to reproduce this. I still can't. But the next version of the CLI will have better error reporting and messaging for this. We'll take a look then.

**Comment by piotrowski** [comment]
What happens for you if you execute `ionic info` after cloning a v2 project from Github without running `npm install` then?
