### ISSUE TITLE
Cordova Browser Platform Support

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#2312]
Support for the "browser" platform of Cordova is lackluster in the CLI.

This issue is here as a placeholder to investigate supporting it. This may evolve into suggesting alternative workflows.

See:
* https://github.com/ionic-team/ionic-cli/issues/2306
* https://github.com/ionic-team/ionic-cli/issues/2282
* https://github.com/ionic-team/ionic-cli/issues/2307
* https://github.com/ionic-team/ionic-cli/issues/2312

**Comment by astec** [comment]
Please consider scenario where HTTPS is working via proxy (_nginx_).

I have scenario where I serve API and web app (_browser platform_) from the same domain over HTTPS.

- https://mydomain.local/app/ => maps to `localhost:port` created by "`ionic serve --browser`"
- https://mydomain.local/* => rest maps to AppEngine dev server (_could be anything_).

Live reload does not work in this setup. It would be cool if it does.

**Comment by gischy** [comment]
any idea when #2307 will be fixed, it is a pretty necessary functionality

**Comment by bradrust** [comment]
@gischy, `ionic cordova run browser -- --port=9009` seemed to work for me.  Obviously there might be other CLI things that need review but this might help you based on #2307

**Comment by dwieeb** [comment]
Folks, I'm gonna call it. The Ionic CLI likely will not support the Cordova browser platform now or in the future. From what I can tell, it's a side project that doesn't get much support from the Cordova team and it has poor plugin support from the community. I'd be happy to look at submitted PRs, but the browser platform spins up a development server that is entirely separate from the one in `ionic serve`, which makes it difficult/infeasible to support for frameworks that ship their own dev servers with livereload, hot module replacement, etc. 

As an alternative to using the Cordova browser platform, please use [platform detection](https://ionicframework.com/docs/api/platform/Platform/#is) and `ionic serve` for developing for the browser. For stuff like camera, audio, storage, and other native functionality please see [whatcanwebdo.today](https://whatwebcando.today/).

For Ionic Angular v4, the Ionic CLI inserts Cordova functionality only when building for Cordova. This means `cordova.js` is added to `index.html` during `ionic cordova build`, not `ionic build`. Additionally, all the Cordova JS files are copied into your project during `ionic cordova build`, not `ionic build`. This lets you easily target platforms such as Cordova or the browser with a single code base. Our story for this is not yet perfect, but it will be a major focus going forward.

**Comment by dwieeb** [comment]
For those following this issue, I did create a feature idea for **mobile** apps (not mobile + desktop) using the Cordova browser platform and `ionic serve` for app development: https://github.com/ionic-team/ionic-cli/issues/3043
