### ISSUE TITLE
CLI provides incorrect commands list when typing an invalid command

### ISSUE THREAD

**Issue by fiznool** [ionic-team/ionic-cli#2322]
#### Short description of the problem:

When running an invalid command, the helper text shows commands such as `run` that are no longer available (must be prefixed with `cordova`)

#### What behavior are you expecting?

Valid commands to be displayed.

**Steps to reproduce:**
1. Install latest CLI (3.1.2)
2. Run `ionic cordova simulate ios` (this is an invalid command)
3. Read terminal output

The following is displayed:

```
ionic cordova simulate ios
[ERROR] Unable to find command: cordova simulate ios

  Commands:

    build ............... Build (prepare + compile) an Ionic project for a given platform
    compile ............. Compile native platform code
    emulate ............. Emulate an Ionic project on a simulator or emulator
    platform ............ Add or remove a platform target for building an Ionic app
    plugin .............. Manage Cordova plugins
    prepare ............. Transform metadata to platform manifests and copies assets to Cordova platforms
    resources ........... Automatically create icon and splash screen resources
    run ................. Run an Ionic project on a connected device
```
Some of these commands don't work, as they must be prefixed with `cordova`.

**Post the output of `ionic info` below please**

```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/cli-plugin-cordova : 1.1.2
    @ionic/cli-plugin-ionic1  : 1.1.2
    Ionic Framework           : unknown

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by piotrowski** [comment]
Technically all the output is correct: "ionic cordova **simulate ios**" is an incorrect command, but "ionic cordova *" where * is any of the shown commands is correct. Of course that is not really what the user is expecting, so this should probably be changed to include the "ionic cordova" before the commands.

**Comment by dwieeb** [comment]
Hmm. CLI 4 will show the entire help page for the `ionic cordova` namespace, which provides context such as this:

![image](https://user-images.githubusercontent.com/236501/42658675-9efa9020-85eb-11e8-87d7-3f4f62e183d7.png)

So I think this issue will be resolved with CLI v4. Thanks!
