### ISSUE TITLE
Feature Request: Allow additional browser options to be passed in when calling ionic serve

### ISSUE THREAD

**Issue by ChrisPearce** [ionic-team/ionic-cli#2325]
It would be very useful if the Ionic CLI allowed additional options to be passed through to the browser when calling
`ionic serve --browser chrome`

A common scenario when starting Google Chrome as part of development activities is for remote debugging to be enabled via the Chrome command line option
`--remote-debugging-port=9222`

**Comment by piotrowski** [comment]
Ok so these parameters should be supplied to chrome when starting via `ionic serve`, correct?

**Comment by ChrisPearce** [comment]
Yes. 

The most common scenario is the need to start Google Chrome with remote debugging enabled using the command line statement:
`google chrome --remote-debugging-port=9222`
or
`chrome.exe --remote-debugging-port=9222`

**Comment by dwieeb** [comment]
@ChrisPearce Right now we don't execute the chrome binary, we just open the webpage. Interesting idea! I could explore this sometime, but sort of low priority for me right now.

**Comment by ciekawy** [comment]
another opportunity here is to pass `--user-data-dir` to enable using dedicated browser instance with its own settings (i.e. breakpoints), extensions (i.e. chrome redux dev tools) etc.

**Comment by sbatezat** [comment]
I thinks it's indeed un must-have.
In dev environment, I need to launch my chrome browser with security disabled "--disable-web-security --user-data-dir". I'm currently compelled to do that manually.

**Comment by dwieeb** [comment]
Moved to https://github.com/ionic-team/ionic-cli/issues/3362
