### ISSUE TITLE
Where did `resources` documentation move to?

### ISSUE THREAD

**Issue by piotrowski** [ionic-team/ionic-cli#2330]
v2 had this quite elaborate documentation for `ionic resources` at https://github.com/driftyco/ionic-cli/tree/2.x#icon-and-splash-screen-image-generation. For v3, I only find https://ionicframework.com/docs/cli/cordova/resources/ which doesn't explain anything. Did I miss it?

PS: Why does this live under `cordova` by the way? Isn't this functionality supported by an Ionic hosted webserver?

**Comment by dwieeb** [comment]
@piotrowski All the commands will receive lengthy documentation. It's on my todo list. This will show up in the command help pages and the CLI docs which you linked to. 

As for resources living under `cordova`, yeah it seems a bit weird to me. The functionality could be reused for other platforms. PWAs support icons of some particular format in their manifest file. This can be part of a bigger discussion. 

📝 for me: `longDescription`
