### ISSUE TITLE
swap out xml2js for elementtree (for parsing/writing config.xml)

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#2332]
Use the same XML library as Cordova, to avoid issues such as:

- https://github.com/driftyco/ionic-cli/issues/645 (literally breaking `<config-file` definitions)
- https://github.com/driftyco/ionic-cli/issues/2193 (whitespace/indentation)
- https://github.com/driftyco/ionic-cli/issues/2230 (huge reformatting)

**Comment by piotrowski** [comment]
If I remember correctly Cordova had its own set of sorting and merging problems with `config.xml` and the created `AndroidManifest.xml` - but I am not sure. I'll keep an eye open for issues on their side. Ignore this if I don't find any.

**Comment by dwieeb** [comment]
`AndroidManifest.xml` is a required file for Android projects. Cordova modifies it in accordance to configuration from `config.xml`, etc

**Comment by piotrowski** [comment]
Yes, but I had in my mind that I had seen issues that the Cordova CLI also produced broken xml files with their XML library - but on searching their (terribly slow) JIRA I only found conceptual problems (like: how to merge these two almost identical tags, if Android only accepts one).
