### ISSUE TITLE
CLI generate provider/page issues

### ISSUE THREAD

**Issue by AndrewsDevTeam** [ionic-team/ionic-cli#2336]
#### Short description of the problem:
In CLI, run the generate command for page and provider.  Does not create the appropriate files under source.

Ionic CLI :          3.1.2
Cordova CLI :    7.0.1
@ionic/cli-utils:  1.1.2
Ionic Framework:  ionic-angular 3.2.1

#### What behavior are you expecting?
Expect the new page or new provider I am wishing to create will generate the proper folder and files.  Specifically I was ran the following 
ionic cordova plugin add cordova-sqlite-storage --save

then proceeded to generate the provider.

**Steps to reproduce:**
1. install ionic package 
2. Open CLI
3. Go to project folder
4. type: ionic g provider myprovider
5. enter

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by piotrowski** [comment]
You are missing your `ionic info` output at the bottom of the issue. Please append that.

> In CLI, run the generate command for page and provider. Does not create the appropriate files under source.

What does it create then? What exactly happens?

>  `ionic cordova plugin add cordova-sqlite-storage --save`

How is this command connected to this?

**Comment by AndrewsDevTeam** [comment]
To your question:  When I run the ionic g provider [name] command the command states completes successfully creating the new provider with [name]!  However, in my source code:  -->src-->providers-->[name folder]  is not generated.  

This also occurs when trying to generate a page.  I was successful a few times during the same session to create a few pages, but now it no longer creates pages nor the needed provider.  

Wondering if I am missing something or could be a potential issue.  First time developing using ionic.

thank you all in advance


ionic info---
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
Very strange behavior! I'm not able to reproduce this on my end. Is your project in source control? Do you notice any file changes at all?

**Comment by AndrewsDevTeam** [comment]
The project is not in source control.  The only file changes were to app/app.module.ts adding the provider reference.

**Comment by piotrowski** [comment]
I suggest you create a local git repo in the project directory and try
again - just to make sure.

2017-05-24 14:02 GMT+02:00 AndrewsDevTeam <notifications@github.com>:

**Comment by dwieeb** [comment]
@AndrewsDevTeam Is this still an issue? I'm trying to clean up this repo's issues.

**Comment by AndrewsDevTeam** [comment]
No


________________________________
