### ISSUE TITLE
CLI v3: Checking for updates should timeout after a few seconds

### ISSUE THREAD

**Issue by fiznool** [ionic-team/ionic-cli#2340]
#### Short description of the problem:

When using the new CLI, the first thing it does is check for updates to the global and local plugins. If the network connection is bad, this can take ages, and worse still there is no feedback to the user unless the command is run with `--verbose`.

#### What behavior are you expecting?

The check for updates is a nice to have, it shouldn't take longer than a couple of seconds. I don't want to be waiting around for update checks when I'm just trying to start a local dev server.

Maybe the updates should only happen (at most) once a day?

**Steps to reproduce:**
1. Get a flaky network connection
2. Run `ionic serve --verbose`

**Post the output of `ionic info` below please**

```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.2.0
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by dwieeb** [comment]
@fiznool The latest CLI no longer checks for updates on the main process.
