### ISSUE TITLE
Unable to generate new projects from external templates (non-Ionic hosted)

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-cli#2343]
#### Short description of the problem:
Running ionic start Ionic2Parks https://github.com/chrisgriffith/Ionic2Parks will no longer generate an Ionic App. Only the Ionic hosted templates are supported.

#### What behavior are you expecting?
The ability to use properly configured third party templates

**Steps to reproduce:**
1. ionic start Ionic2Parks https://github.com/chrisgriffith/Ionic2Parks

global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.4
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.8.6 
    ios-sim    : 5.0.8

**Comment by oskr** [comment]
Hi there, I'm working on a disconnected environment and can't use ionic hosted templates so this would be a great addition to ionic3 cli.

**Comment by dwieeb** [comment]
Duplicate of https://github.com/ionic-team/ionic-cli/issues/2156

I'm working on it 😄
