### ISSUE TITLE
Generator Overwrite Protection

### ISSUE THREAD

**Issue by lucascrandle** [ionic-team/ionic-cli#2350]
Hey Ionic Team!

I have a small feature request, check for existing files when generating new objects.

Steps to reproduce:
1. Hit the up arrow 1000 times in a row to run/build from the command line as I develop
2. Generate a new page using ionic generator
3. Spend 5 minutes developing without committing or issuing different commands
4. Hit the up arrow and execute without thinking
5. Files are overwritten, development is wasted.

Could the CLI generate command do a quick check to see if it would overwrite files and then request for a confirmation from the user? It would save me some time in the future.

Thanks and keep up the great work!

**Comment by dwieeb** [comment]
@jgw96 @danbucholtz This presents a challenge with how generators were designed.

**Comment by sambengtson** [comment]
I've got to agree with this request.  I've done this twice already today :(

**Comment by danbucholtz** [comment]
Hi,

Full disclosure, I love the idea but I know we're not going to get to this anytime soon. There is way too much other stuff on our list. We'd be open to a well-tested PR. We can even help. Please reach out to me if interested.

Thanks,
Dan
