### ISSUE TITLE
Problems with Cordova flags when building for iOS

### ISSUE THREAD

**Issue by zarko-tg** [ionic-team/ionic-cli#2354]
We're on ionic@2.2.3 and normally make our production builds for iOS using a command like:

ionic build ios --device --prod --release --developmentTeam=FOO --codeSignIdentity="iPhone Developer" --provisioningProfile=BAR --packageType=development

Running the same command (with **cordova** added after ionic) while using the latest ionic(-cli) doesn't finish successfully, complaining about the signing process/archiving.

I've tried using -- and -- -- right after --release in that command but no luck.

It looks like a problem with the interpretation of the Cordova flags. At the moment a big block for moving on to the latest ionic-cli.

**ionic info**
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

**Comment by dwieeb** [comment]
@zarko-tg Does the output look like it forwards the arguments with you use `-- --` ?

**Comment by zarko-tg** [comment]
A little bit hard to tell but if i remember well it was failing in the archive stage/signing regarding missing development team (value).

I'm stuck on cli 2.x.x until fix is in place. We do everything via command line and depend on working Cordova flags.

**Comment by dwieeb** [comment]
Oh, that's weird, cordova says this:

> To provide platform specific options, you must include them after \`--\`.

But it looks like it only works if I don't include the `--`: 

```bash
$ cordova build ios --release --device --developmentTeam=FOO --codeSignIdentity="iPhone Developer" --provisioningProfile=BAR --packageType=development
```

Is that right? I can't find documentation on where to put these flags: https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#using-flags

**Comment by zarko-tg** [comment]
I'll stick to the original description of the issue for the time being. Tried all sorts of variants by pure guessing but no luck.

**Comment by zarko-tg** [comment]
Thanks @dwieeb, I can confirm it's all good after the fix.

If anyone still wondering, the following command pattern applies for iOS now:
ionic cordova build ios --device --prod --release **--** --developmentTeam=FOO --codeSignIdentity="iPhone Developer" --provisioningProfile=BAR --packageType=development
(Notice the extra **--** after --release)

**Comment by dwieeb** [comment]
Oops, I forgot to include those in an example command.

**Comment by vicatcu** [comment]
I think i was fighting this or something like it all day... I ended up running ionic cordova build ios --prod --release and then (re-)signing the binary using ota-tools isa_sign (https://github.com/RichardBronosky/ota-tools)
