### ISSUE TITLE
How to Use cordova-plugin-background-mode ?

### ISSUE THREAD

**Issue by romandahidayat** [ionic-team/ionic-cli#2358]
> Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.5
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.3.1 Build version 8E1000a

How To Use cordova-plugin-background-mode ?

**Comment by danielsogl** [comment]
This has nothing to do with this repo. Please close it and read the ionic native docs.
