### ISSUE TITLE
on ionic-1 i keep getting asked to install cli plugin for ionic-2

### ISSUE THREAD

**Issue by mnewmedia** [ionic-team/ionic-cli#2360]
#### Short description of the problem:
I use ionic v1 and after every command i get asked if i wan't to install `@ionic/cli-plugin-ionic-angular ` but this is for v2.

#### What behavior are you expecting?
not getting asked to install stuff for ionic 2 when i use ionic 1.

**Post the output of `ionic info` below please**
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/cli-plugin-cordova : 1.2.1
    @ionic/cli-plugin-ionic1  : 1.2.0
    Cordova Platforms         : ios 4.3.1
    Ionic Framework           : unknown

System:

    Node       : v6.9.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

**Comment by piotrowski** [comment]
Do you have a `ionic.project` file in your project folder? If so, rename it to `ionic.config.json` to fix this.

**Comment by dwieeb** [comment]
^ definitely do this, if this is the case.

Do you somehow have `ionic-angular` in your `package.json`?

**Comment by mnewmedia** [comment]
Yep I had both, just removed the old one. thank you. =)
