### ISSUE TITLE
Ionic3 - Ionic start command hangs

### ISSUE THREAD

**Issue by sameera207** [ionic-team/ionic-cli#2361]
### version

[x] ionic3

#### Short description of the problem:

I'm trying to create a new ionic project and unfortunately the ionic start command hangs as following. 

It asks me for `You need a passphrase to unlock the secret key for` but never stops me to enter the password. And then it goes to the next steps and I can see the loading icon running with the 

`⠋ Running command`

#### What behavior are you expecting?

After running the `ionic start <app name> blank`, I would expect it will create a new ionic 3 project for me.

**Steps to reproduce:**
1. run the command ` ionic start <app name> blank`

**What I see in the console**

```
~/workspace/personal/ionic ionic start myapp blank
✔ Creating directory ./myapp - done!
[INFO] Fetching app base (https://github.com/driftyco/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank (https://github.com/driftyco/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✔ Running command - done!
> npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
✔ Running command - done!
> git init
✔ Running command - done!
> git add -A
✔ Running command - done!
> git commit -m Initial commit

You need a passphrase to unlock the secret key for
user: "sameera207 <sameera207@gmail.com>"
2048-bit RSA key, ID 1FDE7F52, created 2016-09-01

⠋ Running command
```

**Which @ionic/app-scripts version are you using?**

```
global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

System:

    Node       : v7.10.0
    OS         : OS X El Capitan
    Xcode      : Xcode 7.3.1 Build version 7D1014 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.8
```

**Other information:** 

I've posted the same question on the [ionic forum as well](https://forum.ionicframework.com/t/ionic-start-command-hangs/92007)

Any help would be much appreciated :)

cheers
Sam

This issue is moved from [ionic scripts](https://github.com/driftyco/ionic-app-scripts/issues/1013)

**Comment by sameera207** [comment]
Robert Coie (rapropos) from ionic forum suggested a [workaround](https://forum.ionicframework.com/t/ionic-start-command-hangs/92007/2?u=sameera207) that works fine.  ✅

Workaround:

Run with `--no-git` option

So for the moment, I'll go with it. But I'll keep the issue open

cheers

Sam

**Comment by dwieeb** [comment]
Ah, interesting. I'll disable gpg signed commits for that initial commit for now.
