### ISSUE TITLE
TypeError: platform.trim is not a function (ionic cordova build android --prod)

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2363]
_From @sunilkconsultant on May 27, 2017 6:39_

**Ionic version:**  

[x] **3.x**

**I'm submitting a ...** 
[x] bug report

**Current behavior:**
After creating a new app with CLI ionic start xyz sidemenu --id xyz.com.app, move to app folder with CLI cd xyz, run CLI ionic cordova build android --prod, i get below error in red (TypeError: platform.trim is not a function)

? What platform would you like to build: ios, android: **android**
_TypeError: platform.trim is not a function_

**Expected behavior:**

it should build for android.

**Steps to reproduce:**

After creating a new app with CLI ionic start xyz sidemenu --id xyz.com.app, move to app folder with CLI cd xyz, run CLI ionic cordova build android --prod

? What platform would you like to build: ios, android: **android**
_TypeError: platform.trim is not a function_

**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.1.2
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.8.6 
    ios-sim    : 5.0.8 

```

**Package.json**

 ```
"dependencies": {
    "@angular/common": "4.1.2",
    "@angular/compiler": "4.1.2",
    "@angular/compiler-cli": "4.1.2",
    "@angular/core": "4.1.2",
    "@angular/forms": "4.1.2",
    "@angular/http": "4.1.2",
    "@angular/platform-browser": "4.1.2",
    "@angular/platform-browser-dynamic": "4.1.2",
    "@ionic-native/core": "3.10.2",
    "@ionic-native/splash-screen": "3.10.2",
    "@ionic-native/status-bar": "3.10.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.3.0",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.11"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@ionic/cli-plugin-cordova": "1.2.1",
    "@ionic/cli-plugin-ionic-angular": "1.2.0",
    "typescript": "2.3.3"
  },
```

_Copied from original issue: ionic-team/ionic#11809_

**Comment by jgw96** [comment]
_From @rapropos on May 27, 2017 23:38_

Should probably be migrated to CLI.

**Comment by jgw96** [comment]
_From @reviloera on May 28, 2017 6:30_

getting same error when I run  `ionic cordova build --release android`

**Comment by jgw96** [comment]
_From @satnam348 on May 29, 2017 17:52_

getting same error when I run ionic cordova build

**Comment by dwieeb** [comment]
@sunilkconsultant @reviloera @satnam348 Sorry about this. Please make sure your CLI is up to date.

**Comment by plantlog-jduffy** [comment]
I'm also getting this error with the latest 3.13.2 CLI. I tried uninstalling all global npm modules and reinstalling to no avail.

Running a MacBook Pro with macOS 10.13.

**Comment by beloitdavisja** [comment]
Also getting this on a macOS 10.13. 

3.17.0 ionic CLI, node 8.9.0, npm 5.5.1, cordova 7.1.0. 

I am getting the msg.trim() error after any CLI command (e.g. ionic --version)

**Comment by dwieeb** [comment]
@beloitdavisja That is a different issue. Please create a new issue and fill out the issue template. It looks like a problem with the logger, but I can't be sure without the stack trace and full command output.

**Comment by joelgarciajr84** [comment]
Same here

**Comment by joelgarciajr84** [comment]
TypeError: msg.trim is not a function
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/utils/logger.js:78:21)
    at Logger.error (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/utils/logger.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/dist/index.js:186:22)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/ionic/node_modules/tslib/tslib.js:101:69)
    at <anonymous>

**Comment by dwieeb** [comment]
@joelgarciajr84 Thank you for the stack trace. I believe this fix will reveal more: https://github.com/ionic-team/ionic-cli/commit/3433fdf620c4f68c1228333f57898e6507dc028b

@beloitdavisja @joelgarciajr84 If you're up for it, you can test this by installing the alpha CLI: `npm i -g ionic@canary` -- it should reveal more about the issue you're getting
