### ISSUE TITLE
TypeError: AppScripts.processProviderRequest is not a function

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2364]
_From @ianlikono on May 28, 2017 2:29_

Short description of the problem:

Running npm ionic g provider authService aborts with the following error:
TypeError: AppScripts.processProviderRequest is not a function
**Which version are you using?**
 @ionic/cli-utils : 1.2.0
 Ionic CLI        : 3.2.0

@ionic/app-scripts              : 1.1.4
@ionic/cli-plugin-ionic-angular : 1.2.0
Ionic Framework                 : ionic-angular 3.3.0

_Copied from original issue: ionic-team/ionic#11818_

**Comment by dwieeb** [comment]
@ianlikono Your app-scripts version is ancient. Please update `npm i --save-dev @ionic/app-scripts@latest`

**Comment by sivakumar1987** [comment]
my package.json contains the same version of app-scripts(1.1.4) and also getting the same error. Kindly help me to solve the issue. Im working under corporate environment(proxy) so npm is not working.

**Comment by dwieeb** [comment]
@sivakumar1987 Here is an npm proxy tutorial: https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by sivakumar1987** [comment]
Hi team,
consider:
uname is sivakumar.p19
pword is Chem@2
proxy address is 120.120.120.120:80

i have set all this things and found the same in .npmrc file

npm config set http_proxy http://"sivakumar.p19:Chem@2"@120.120.120.120:80
npm config set https_proxy http://"sivakumar.p19:Chem@2"@120.120.120.120:80
npm config set proxy http://"sivakumar.p19:Chem@2"@120.120.120.120:80
npm config set http-proxy http://"sivakumar.p19:Chem@2"@120.120.120.120:80
npm config set https-proxy http://"sivakumar.p19:Chem@2"@120.120.120.120:80
strict-ssl=false
registry=http://registry.npmjs.org/


But still im facing the issue. Can you please help me on solving the issue.
in .pac file i can find four proxy i used this 120 apart from this 121 is
available and mycompanyproxy1,mycompanyproxy2 i dunno which one to use.
Also please let me know to use which one.


TIA
Sivakumar.P
