### ISSUE TITLE
Unable to write provisioning.plist

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2365]
_From @pdxwebdev on May 29, 2017 22:22_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
$ ionic package build
then I choose ios
then in the ionic console, I see the build failed.
the output is: "Unable to write provisioning.plist"

**Expected behavior:**
successful build

**Steps to reproduce:**
As seen above. I'm pretty new to ionic so I don't really know what to include.

For Ionic V1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

_Copied from original issue: ionic-team/ionic#11852_

**Comment by jgw96** [comment]
_From @danielsogl on May 29, 2017 22:52_

Can you run ionic cordova build iOS locally without any errors?

**Comment by jgw96** [comment]
_From @pdxwebdev on May 30, 2017 7:17_

Correct. The build succeeds locally.

**Comment by dwieeb** [comment]
@pdxwebdev There was an issue with Ionic Package earlier. Are you still getting this?

**Comment by pdxwebdev** [comment]
@dwieeb Yes, just issued the `ionic package build` -> `ios` command again and received the error again, just now.

**Comment by pdxwebdev** [comment]
![ionic](https://cloud.githubusercontent.com/assets/490176/26605048/52dcda90-4541-11e7-8c9a-5b9f2d307bd9.png)

**Comment by dwieeb** [comment]
@pdxwebdev It's a bad error message (which @tlancina is fixing). Can you make sure that you've uploaded a valid provisioning profile?

**Comment by pdxwebdev** [comment]
Oops! You were correct. I had to upload my updated provisioning profile and corresponding p12 to the security profile area (verbosity for posterity). I did that and it got me to another error that I think I can handle. Thanks!

**Comment by pdxwebdev** [comment]
Yup, worked out the other error and now I have an .ipa file. thanks!

**Comment by dwieeb** [comment]
You're welcome!
