### ISSUE TITLE
[CLI 3] Error trying to add android platform

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic-cli#2367]
#### Short description of the problem:
I'm trying to add the android platform to my project using `ionic cordova platform add android`
and I get the following error:

```
c:\xampp\htdocs\myproj>ionic cordova platform add android
> cordova platform add android --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova platform add android --save (exit code 1):

        Error: Current working directory is not a Cordova-based project.
```

I tried to run `cordova platform add android --save` as the error refers, and I get the following error:

```
c:\xampp\htdocs\myproj>cordova platform add android --save
Using cordova-fetch for cordova-android@~6.2.2
Error: Failed to fetch platform cordova-android@~6.2.2
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Failed to get absolute path to installed module
```

#### What behavior are you expecting?
adding android platform in the CLI 3

**Steps to reproduce:**
1. run `ionic cordova platform add android`

**Post the output of `ionic info` below please**

```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
Can you try `cordova platform add android@6.2.3` ?

**Comment by theunreal** [comment]
@dwieeb, I get the same error in this version and any other

**Comment by dwieeb** [comment]
I've never seen that error before. It says "Probably this is either a connection problem, or platform spec is incorrect." 

We know the platform spec is correct, so what's your connection like?

**Comment by mtayyip** [comment]
Hi,
Is there any solution anyone found

**Comment by madsongr** [comment]
Try setting path = "C:\Windows\System32" in variable/system variable

**Comment by Cdvalencia** [comment]
There seems to be an error with android@6.2.x and later. I had the same issue and using the below step was able to build my apk.

Do the following:

`cordova platform remove android`

Then add 6.1.2 specifically

`cordova platform add android@6.1.2`

Also found the following as an temporary workaround

`cordova platform add android --nofetch`

**Comment by nhoangdieu** [comment]
thanks @Cdvalencia  it works for me

**Comment by darrencole** [comment]
Thank you madsongr, that solved my issue!!!

**Comment by mhbt** [comment]
I am having the same problem. Neither of solution have worked. What can I do?

**Comment by mhbt** [comment]
@darrencole  What you did to solve this issue?

**Comment by darrencole** [comment]
@mhbt I did this: Try setting path = "C:\Windows\System32" in variable/system variable

**Comment by Amoioo** [comment]
@darrencole  how can write this in terminal ?

**Comment by darrencole** [comment]
@Amoioo what type of machine are you on?

**Comment by Amoioo** [comment]
@darrencole  windows os and visual studio code platform

**Comment by Amoioo** [comment]
When I write this command (Ionic cordova build - - release android) this Error appears it is shown in attached picture.
![0](https://user-images.githubusercontent.com/46760610/52451332-2a11e900-2b47-11e9-9de0-5fb80d6ba224.JPG)

**Comment by darrencole** [comment]
Ok. Try this. Go to Environmental Variables on your PC and set the 'system variable' as we discussed above.

**Comment by Amoioo** [comment]
How please Explain ? @darrencole

**Comment by darrencole** [comment]
Sure buddy:
1. Go to Control Panel > System > Advanced System Settings
2. Click on the Advanced tab then press the "Environment Variables" button
3. Go to the "System Variables" section  and click on the "Path" variable.
4. Click on edit.
5. Append C:\Windows\System32 to the end of the Path value. Note, each new addition to Path must be separated from the last by a semi colon.

I hope this helps.

**Comment by Supadtra** [comment]
![image](https://user-images.githubusercontent.com/43342838/68834071-83ff9a80-06e7-11ea-8f5d-cd550fcbdee5.png)
