### ISSUE TITLE
Why `ionic cordova resources`?

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2369]
We talked about this in #2330:

@piotrowski
> Why does this live under `cordova by the way? Isn't this functionality supported by an Ionic hosted webserver?

@dwieeb
> As for `resources` living under `cordova`, yeah it seems a bit weird to me. The functionality could be reused for other platforms. PWAs support icons of some particular format in their manifest file. This can be part of a bigger discussion.

**Comment by dwieeb** [comment]
The `ionic cordova resources` does do Cordova things, as well, such as modify the `config.xml`, which is entirely a Cordova file.

The prefix `ionic cordova` isn't necessarily 1:1 with Cordova commands. We have additional options in almost every command. We have an additional command under the `ionic cordova` namespace, as well.
