### ISSUE TITLE
ionic cordova prepare ios

### ISSUE THREAD

**Issue by Bernardoow** [ionic-team/ionic-cli#2376]
#### Short description of the problem:
HI,  get from my repository the source  and run ionic cordova prepare ios and deploy to my app.
My app was bugged because didn't found index.html.

#### What behavior are you expecting?
When I type ionic cordova prepare ios, compile my ts and after this prepare ios.

**Steps to reproduce:**
1. ionic cordova prepare ios
2.
3.

**Comment by ironbone** [comment]
ionic serve
when the browser is openn CTRL C
ionic cordova prepare ios

before we have 
ionic prepare 
to do it 
unfortunately it does not work now
