### ISSUE TITLE
Add support for nodejs v8

### ISSUE THREAD

**Issue by themastersoda** [ionic-team/ionic-cli#2377]
#### Short description of the problem:
Currently ionic does not support nodejs v8, even though if you have a lower than the latest LTS version of node 6, it tells you to update to that, or just latest node.

It seems that the package causing the issue is node-sass. Version 4.5.0 only supports node up to v7, however, v4.5.3 added support for node v8 as well. It seems that simply updating the package version would solve the issue.

#### What behavior are you expecting?
Ionic should work without errors with the latest node version

**Steps to reproduce:**
1. Make sure your node version is v8
2. Run ionic serve
3. Read the error

**Post the output of `ionic info` below please**
```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v8.0.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by themastersoda** [comment]
Oops, this should be in app-scripts. Closing this, since app-scripts already has a pull request for it.

**Comment by piotrowski** [comment]
Here is the issue for it https://github.com/ionic-team/ionic-app-scripts/issues/1016
