### ISSUE TITLE
Why I am not getting generated files in ‘www’ folder in ionic1 app after 'ionic serve'?

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2379]
_From @tousif12 on June 1, 2017 12:34_

I am using ionic 1 to run a already build app 1 year ago . Now after ionic serve its not creating data in 'www' folder . Just gave this
'Error: ENOENT: no such file or directory, open '/home/m/DimDrop_graphs/www/index.html'' 
According to my knowledge it should create itself 'www' folder data ? as I have lost now 'www' folder.

_Copied from original issue: ionic-team/ionic#11889_

**Comment by tousif12** [comment]
my ionic version is 2.0.0

**Comment by danielsogl** [comment]
@tousif12 Can you post your `ionic info` output

**Comment by tousif12** [comment]
@danielsogl  sure sir
![currenenenene](https://cloud.githubusercontent.com/assets/10029089/26682787/1fdd2760-46fb-11e7-84ec-9117a8e6f3a4.png)

**Comment by tousif12** [comment]
@danielsogl  I didnt upgrade versions as I am working on ionic1

**Comment by dwieeb** [comment]
Upgrade your CLI to v3. We aren't supporting CLI v2. If you have issues running your Ionic 1 app in CLI v3, let me know.

**Comment by tousif12** [comment]
@dwieeb  Yes When I use it in V3 then I got 'Its not ionic project directory' error. I tried all solution given in other issue of github but not helping.

**Comment by dwieeb** [comment]
@tousif12 You can make a new issue detailing the problem. We definitely want to support older Ionic 1 apps.
