### ISSUE TITLE
ionic cordova resources  -i did not generate rounded icon

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2380]
_From @BoltLiu on June 1, 2017 8:45_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

   $   "ionic cordova resources  android -i "  command  could not generate rounded icon.but just a square icon.
**Expected behavior:**

 want generating  rounded icon for app.

**Steps to reproduce:**

**Related code:**

  $ ionic cordova resources android -i
  $ ionic cordova resources android 

```
insert any relevant code here
```
➜  mytabs git:(master) ✗ ionic info

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

_Copied from original issue: ionic-team/ionic#11884_

**Comment by dwieeb** [comment]
@BoltLiu Android doesn't automatically apply a mask to icons for you like iOS does. You have to make the decision of how your icon should look before running `ionic cordova resources`, which just crops/resizes. Android has changed the look and feel of its icons drastically through the years, and we don't assume what you want. 

Round the corners to your own desire and place the icon in `resources/android/icon.png`.  Then, run it again.

**Comment by jrmistry** [comment]
Does this mean that `ionic cordova resources` will not auto generate both original and rounded versions of the app icon?
