### ISSUE TITLE
Checking for update block CI, option to disable auto-check?

### ISSUE THREAD

**Issue by qiluo** [ionic-team/ionic-cli#2382]
#### Short description of the problem:
Prompt for new version of cli has blocked automated CI process, had to manually enter 'Y/n' to continue the build

#### What behavior are you expecting?
A option to disable auto-check for new version

**Post the output of `ionic info` below please**
```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v8.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by Inlustra** [comment]
Also having this problem, we had to update to fix the build but the forced update is a shame.

**Comment by dwieeb** [comment]
Please see the readme for `--no-interactive`: https://github.com/ionic-team/ionic-cli#cli-flags

This has also been asked several times, do the issues not appear in google results?
