### ISSUE TITLE
Error doing ionic serve after v1.3.0 of plugins was released (+fix)

### ISSUE THREAD

**Issue by larssn** [ionic-team/ionic-cli#2383]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/ionic-team/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### Short description of the problem:
So after the recent update:
```
ionic serve
Local plugin @ionic/cli-plugin-cordova has an update available (1.2.1 => 1.3.0)! Would you like to install it? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
✔ Running command - done!
[OK] Upgraded @ionic/cli-plugin-cordova to 1.3.0! 🎉
Error: ENOENT: no such file or directory, open './node_modules/@ionic/cli-plugin-ionic-angular/dist/index.js'
```

So i did a `rm -rf node_modules` and then `npm install`

`ionic serve`
`Error: Cannot find module 'reflect-metadata'`

**Steps to reproduce:**
Well my problem happening doing an upgrade request, as seen above. So try that.

**Fix**
Had to manually update the `@ionic/cli-plugin-ionic-angular` plugin to 1.3.0 to get the build process working again. The CLI didn't ask me to do it, since it err'ed out before that.

**Info**
```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.11 
```

**Comment by dwieeb** [comment]
@larssn Has this happened again since updating that plugin?

**Comment by larssn** [comment]
We've moved away from Ionic, so I can't say. Sorry
