### ISSUE TITLE
[Feature Request] ionic cordova resources - image per platform

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/ionic-cli#2384]
It would be great if it's possible to add a different icon and splash per platform.
So that you can put in a `icon-android.png` and `icon-ios.png`. It would be cool, if it's searching for `icon-<platform>.png` and if it's not available use `icon.png` as default. And the same thing for the Splashscreen of course.

**Comment by dwieeb** [comment]
You can do this today--I just forgot to document it (fixed in https://github.com/ionic-team/ionic-cli/commit/3a135e99e486cc7d107690e69470c59e6f1cfca5)

Basically, put them in `resources/ios/icon.png` to override `resources/icon.png` for that platform.
