### ISSUE TITLE
super starter + generators : TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2386]
_From @martineca on June 2, 2017 9:46_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>To reproduce the bug simply do 'ionic start sampleApp' then choose super as option. After installation is complete try creating a service with 'ionic g provider sampleService' and you will get error: cannot read property of 'length' of undefined.</span>

<span is-issue-template></span>

_Copied from original issue: ionic-team/ionic#11898_

**Comment by jgw96** [comment]
_From @AmitMY on June 2, 2017 10:38_

What version CLI are you using? Please add the output of `ionic info`

**Comment by jgw96** [comment]
_From @martineca on June 2, 2017 11:0_

global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by jgw96** [comment]
_From @AmitMY on June 2, 2017 11:3_

Thanks, so it seems like the issue should be moved to ionic-cli. @jgw96 can you please move it?

**Comment by dwieeb** [comment]
Yuuup. App-scripts can't append the NgModule definition for the super starter because it uses a different format for `app.module.ts`

```
[DEBUG] TypeError: Cannot read property 'length' of undefined
            at Object.appendNgModuleDeclaration (/Users/dan/ionic/wowsuper/node_modules/@ionic/app-scripts/dist/util/typescript-utils.js:213:25)
            at /Users/dan/ionic/wowsuper/node_modules/@ionic/app-scripts/dist/generators/util.js:163:46
```

**Comment by martineca** [comment]
Thanks for replying. Could you give me an example similar to 'ionic g provider sampleService' that would work with the super starter?

**Comment by dwieeb** [comment]
@martineca No, it's a bug.

Move the array returned by the silly `providers()` function into the `@NgModule` decorator. 

For a workaround, replace 
```typescript
providers: providers()
```
with
```typescript
providers: [
    Api,
    Items,
    User,
    Camera,
    GoogleMaps,
    SplashScreen,
    StatusBar,

    { provide: Settings, useFactory: provideSettings, deps: [Storage] },
    // Keep this to enable Ionic's runtime error handling during development
    { provide: ErrorHandler, useClass: IonicErrorHandler }
  ]
```

**Comment by bleuscyther** [comment]
@dweib nice, it fixed the issue.
For those of you who use the function providers() to switch between mocks and real-cordova-plugins  for example, you can use multi providers instead to programmatically use the class you need.

https://angular.io/docs/ts/latest/api/core/index/ValueProvider-interface.html:
https://blog.thoughtram.io/angular2/2015/11/23/multi-providers-in-angular-2.html

**Comment by marwan2** [comment]
Same issue, fixed by the replace stated by @dwieeb

**Comment by glennlawyer** [comment]
@bleuscyther could you give a quick example on how to use multiproviders to accomplish this? I'm finding the docs slightly opaque on the topic.

**Comment by bleuscyther** [comment]
I use a different approach now for the mock:  
``` typescript
\* app.module.ts*\
...
// Mocks
import {CameraMock} from "../mocks/camera";
...

const USE_MOKS = false; // should not be in a config file , doesn't work well with  `build --prod`
....
@NgModule({
    ...
     providers: [
        {provide: Camera, useClass: USE_MOKS ? CameraMock : Camera},
         ...
    ]
})
export class AppModule {
}
````
And here is an example of mock:
``` typeScript
import {Camera} from "@ionic-native/camera";

export class CameraMock extends Camera {
    getPicture(options) {
        console.warn('Camera - Using mocks - getPicture');

        return new Promise((resolve, reject) => {
            let fakeImage = '<yourImageDataURL>`
           resolve(fakeImage);
        })
    }
}

```

**Comment by dwieeb** [comment]
This is fixed in latest super starter.
