### ISSUE TITLE
--json for parseable commands

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#2388]
Might be cool for:

* `ionic package list`
* `ionic package info`
* `ionic config get`
* others?

**Comment by leosoto** [comment]
Since we bumped into #1957 when trying to use ionic-cli as part of continuous integration scripts, I'd say that having parseable output from the build process would be cool too (although just returning a non-zero exit code on failure is enough to begin with)

**Comment by dwieeb** [comment]
That's asking a ton, since we just forward the output from Cordova, and it's entirely platform specific. If a Cordova build fails, we exit with an appropriate exit code. 

We can do some regex matching on common errors and try to give useful info, but I'm not sure what you're expecting from a parseable output.

**Comment by leosoto** [comment]
That's right. The exit code and not crashing anymore is good enough :)
