### ISSUE TITLE
Ionic v1: `ionic serve` tells user that app is available at 0.0.0.0:8100 instead of localhost:8100

### ISSUE THREAD

**Issue by piotrowski** [ionic-team/ionic-cli#2392]
Noticed several threads about this on the forum:

https://forum.ionicframework.com/t/ionic-serve-is-not-working/92937
https://forum.ionicframework.com/t/ionic-serve-points-to-0-0-0-0-8100/92902
https://forum.ionicframework.com/t/how-i-run-my-ionic-1-application-on-cli-3-using-the-serve/92455
https://forum.ionicframework.com/t/ionic-serve-lab-not-working-after-updating-to-latest-ionic-version-ionic-v1/91743

**Comment by danielsogl** [comment]
@piotrowski could you reproduce the problems?

**Comment by dwieeb** [comment]
Yeah, I know what this is about. It defaults to `0.0.0.0` for Ionic 1.
