### ISSUE TITLE
 Invalid name: "@ionic/cli-utils"

### ISSUE THREAD

**Issue by LiveRock** [ionic-team/ionic-cli#2393]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/ionic-team/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### Short description of the problem:
Platform: Mac Pro Sierra
Command:  sudo npm install -g ionic

Errors:
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@ionic/cli-utils"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

#### What behavior are you expecting?
Proper install

**Steps to reproduce:**
1. sudo npm install -g ionic
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
Duplicate: https://github.com/ionic-team/ionic-cli/issues/2357
