### ISSUE TITLE
`cordova telemetry`  sideffect: info notice shown before `cordova` (and platforms) version 

### ISSUE THREAD

**Issue by piotrowski** [ionic-team/ionic-cli#2398]
Noticed this several times in the forum now:

![cb1fcf37e8e1815b89b57858baeae5a5bfde27a8](https://user-images.githubusercontent.com/183673/26842079-e5e024a0-4aeb-11e7-9555-47bf7e3b9dca.png)
(via https://forum.ionicframework.com/t/please-help-me-ionic-connection-unsuccessful/93217)

(Somehow these users also always only post there `ionic info` output as images... sorry)

**Comment by dwieeb** [comment]
Yeah, I saw this too. It looks like there's a `--no-telemetry` flag I can use.

**Comment by piotrowski** [comment]
Maybe talk to the Cordova people for another solution (or just replace this static string that is inserted)? I assume Ionic is a big part of the Cordova install base now and it would be a shame for them to lose all telemetry information from Ionic users, wouldn't it?

**Comment by dwieeb** [comment]
This would just be for getting the Cordova version.
