### ISSUE TITLE
Clean up CLI plugins when both are installed

### ISSUE THREAD

**Issue by piotrowski** [ionic-team/ionic-cli#2401]
See this `ionic info` [someone posted at the forum](https://forum.ionicframework.com/t/problem-tracker-not-started/93342):

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    @ionic/cli-plugin-ionic1        : 1.3.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0
    Ionic Framework                 : unknown

System:

    Node       : v8.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

Obviously, he has both Cordova Plugins for CLI v3 installed. I advised him to uninstall one of them, but theoretically the CLI could take care of that and warn the user of what he is doing (maybe already when he is installing it?). On the other hand I don't know how common this is or if it is causing any actual problems at all - keeping an eye open for more cases.

**Comment by dwieeb** [comment]
I'll have the CLI warn about it. Having multiple project plugins installed is not good.
