### ISSUE TITLE
Ionic CLI update request should be just a warning

### ISSUE THREAD

**Issue by Takkuz** [ionic-team/ionic-cli#2402]
#### Short description of the problem:

Using Ionic in a CI context the request "There's an update, you want to install it" is overwhelming. It blocks the script and prevent it to complete the execution.

#### What behavior are you expecting?

I'm using Ionic in a CI environment with a builder which creates the _www_ folder dinamically and then launches `ionic build`. The request for the update that waits for a user input keeps the script from running ahead and blocks the whole chain.

I think it could be correct to notice the update available but it shouldn't block the command from running. Maybe it could be noticed to user at the end of the building process

**Steps to reproduce:**
The request is the one you get when launching every Ionic command with @ionic/cli-plugin-ionic1@1.2.0 installed.

**Comment by dwieeb** [comment]
Please see the README for CI servers: https://github.com/ionic-team/ionic-cli#cli-flags
