### ISSUE TITLE
Ionic deploy with metadata

### ISSUE THREAD

**Issue by harshabonthu** [ionic-team/ionic-cli#2403]
#### Short description of the problem:
Current workflow to do an ionic deploy doesn't support setting the metadata for a snapshot through cli, we can do the deploy through cli but again need to login to ionic.io and set the metadata for the snapshot. This is a blocker to automate deploy process.

#### What behavior are you expecting?
We should be able to set metadata for a snapshot while doing the deploy / upload using the cli without the need to login to ionic.io dashboard.

#### Possible solutions right now
- We need to write our own build script to use the ionic.io API and get all snapshots, set the metadata using the PATCH endpoint.

I tried looking at the source code for `deploy.ts` in cli-utils package and based on my understanding, I think right now the endpoint used to upload snapshot by cli i.e `'POST' -> '/deploy/snapshots'` ignores metadata value from request body. (Also not documented here -> https://docs.ionic.io/api/endpoints/deploy.html)

Ideally this should be a feature supported by ionic-cli rather than using hacky solution of writing our own build script to deploy + set metadata.

**Post the output of `ionic info` below please**
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : 1.9.0
    ios-sim    : 5.0.8

**Comment by piotrowski** [comment]
Duplicate here: #660

**Comment by harshabonthu** [comment]
Agree, I did look at the gulp script and it works. But again its something that should be in the cli rather than maintaining our own script, so I was looking to submit a PR but currently I see a limitation on 'POST' -> '/deploy/snapshots' endpoint ignoring metadata value and would need to do another PATCH request.

**Comment by piotrowski** [comment]
I don't think there is a repo for the Ionic Deploy API where we could raise this as an issue (or PR) :/

Sending a second request only if the values are attached to the call would be a valid workaround in the CLI though, what do you think @dwieeb?

**Comment by dwieeb** [comment]
I am going to keep track of this issue in the milestone for future stuff. I just don't have time right now to add this to the deploy API and there is a workaround in place.
