### ISSUE TITLE
can't login when i use VPN in CLI 

### ISSUE THREAD

**Issue by invalidtruck** [ionic-team/ionic-cli#2406]
Cant login when i use VPN 

response message is exceed 5000ms 

global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
@invalidtruck Can you try with `--no-timeout` and see if it resolves the issue?

**Comment by invalidtruck** [comment]
thanks it solved

**Comment by dwieeb** [comment]
@ricardo-mello I think this is a rare case, but good to know that someone hit that 5s response timeout.

**Comment by ricardo-mello** [comment]
@dwieeb yeah, the VPN is our villain. I think that we can increase the timeout to 10s and suggest the `--no-timeout` flag when it happens.
