### ISSUE TITLE
Generators Revamp

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#2407]
The current functionality of `ionic generate` is a stopgap. This is a placeholder issue for revamping generators for better UX, stability, features, etc. 

See:
- https://github.com/ionic-team/ionic-cli/issues/1838
- https://github.com/ionic-team/ionic-cli/issues/1838#issuecomment-307167053
- https://github.com/ionic-team/ionic-cli/issues/2439
- https://github.com/ionic-team/ionic-cli/issues/2720
- https://github.com/ionic-team/ionic-cli/issues/2745
- https://github.com/ionic-team/ionic-cli/issues/868
- https://github.com/ionic-team/ionic-cli/issues/2496
- https://github.com/ionic-team/ionic-cli/issues/2960

**Comment by Robinyo** [comment]
Just started to look at [Schematics](https://github.com/angular/devkit/tree/master/packages/angular_devkit/schematics).

See: 
- https://robferguson.org/blog/2017/12/31/the-future-of-the-ionic-cli/
- https://github.com/Robinyo/ionic-angular-schematics

**Comment by dwieeb** [comment]
Impressive work, @Robinyo! Schematics is definitely what we're planning on using for Ionic Angular v4+ generators in the Ionic CLI. I took a look into Schematics a little while ago when the project was just getting started, and it looks like your work is very similar to what I was doing. This will definitely help when we go to implement this in the Ionic CLI. 👍 

One difference is that we were going to work with the Angular team to get our schematics in the npm org: https://www.npmjs.com/~schematics. 

If you're interested in going further and helping with the Ionic CLI implementation, I'd love to talk and bring you up to speed with what I've been working on to get ready for Ionic Angular v4. Are you on Ionic Worldwide? 👉 https://ionicworldwide.herokuapp.com/

**Comment by Robinyo** [comment]
Hi,

-> Impressive work

Thanks

-> If you're interested in going further and helping with the Ionic CLI
implementation, I'd love to talk and bring you up to speed with what I've
been working on to get ready for Ionic Angular v4.

Ok

-> Are you on Ionic Worldwide?

Yes

Cheers
Rob

**Comment by dwieeb** [comment]
v4 generators use the Angular CLI and most, if not all, requests are fulfilled by it. Please see https://github.com/ionic-team/ionic-cli/issues/3019 to get started testing.

v3 generators use `@ionic/app-scripts` and likely won't be revamped.
