### ISSUE TITLE
Feature Request: add 'multiple' attribute to ionic segment 

### ISSUE THREAD

**Issue by lukejoliat** [ionic-team/ionic-cli#2408]
For the ion-select element, there is the option to add an attribute: `multiple="true"`

This attribute allows users, "to select multiple options. When multiple options can be selected, the alert overlay presents users with a checkbox styled list of options. The ion-select multiple="true" component's value receives an array of all the selected option values."

Is it possible to add this attribute for ion segments so that we can select several segments. I have a several segment buttons in my application and it would be fantastic if I could allow users to select several values:
![beacon](https://user-images.githubusercontent.com/23531241/26959738-abb3d99c-4c9f-11e7-87cc-ed8a460a89c5.png)

**Comment by tolsam** [comment]
Why was it closed?

**Comment by dwieeb** [comment]
@tolsam Please see https://github.com/ionic-team/ionic/issues/11985 -- I reopened it.
