### ISSUE TITLE
Handle presence of `ionic.project` file

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2409]
Quite common that very long time Ionic users still have the `ionic.project` file instead of `ionic.config.js` file in their Ionic folder. This causes the project not to be recognized as an Ionic project at all and stuff doesn't work. Example:

https://forum.ionicframework.com/t/how-to-run-ionic-1-project-in-ionic3-enviroment/93524

Would it be possible to recognize this and output a helpful message for these people? Theoretically you could also rename the file automatically, but I think having them do it manually would make them more aware of the change (and probably also be less code to maintain).

**Comment by dwieeb** [comment]
Good idea. I definitely want to ease the transition of all Ionic projects using legacy.
