### ISSUE TITLE
Generate resources failed behind proxy

### ISSUE THREAD

**Issue by micha-walter** [ionic-team/ionic-cli#2411]
**Description:**

"ionic cordova resources" behind a proxy is failed with connection timeout. On our Proxy we see no log entrys but on my local machine I see connections to the resource server directly.

Otherwise the CLI is able to use our proxy for update itself and his plugins, so the environment variable IONIC_HTTP_PROXY is set correctly.

To resolve this issue in the meantime we have created firewall rules to access the resource server without a proxy.

Please let me know, if you need more infos. Thanks.

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

global packages:

    @ionic/cli-plugin-proxy : 1.3.0
    @ionic/cli-utils        : 1.3.0
    Cordova CLI             : 7.0.1
    Ionic CLI               : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.8.0
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Other Information:**

**Comment by dwieeb** [comment]
Gonna mark this as fixed. The plugin will need to be installed globally and locally in order to proxy all CLI HTTP requests. https://github.com/ionic-team/ionic-cli#using-a-proxy

With this upcoming CLI release, the CLI recommends a local CLI installation.
