### ISSUE TITLE
Failed to fetch platform cordova-android@~6.2.2

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2412]
_From @iamkhan001 on June 9, 2017 7:20_

getting error while adding android platform

D:\Imran\ionic\notifications>ionic cordova platform add android
> cordova platform add android --save
? Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova platform add android --save (exi
t code 1):

        Using cordova-fetch for cordova-android@~6.2.2
        Error: Failed to fetch platform cordova-android@~6.2.2
        Probably this is either a connection problem, or platform spec is incorr
ect.
        Check your connection and platform name/version/URL.
        Error: cmd: Command failed with exit code ENOENT

_Copied from original issue: ionic-team/ionic#11989_

**Comment by jgw96** [comment]
_From @piotrowski on June 9, 2017 8:37_

As the error message says:

> Probably this is either a connection problem
> ...
> Check your connection

Are you behind a corporate proxy?

**Comment by toddmedema** [comment]
I'm getting something similar:
```
Error: Failed to fetch platform cordova-android@6.2.2
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 194 Error output:
npm ERR! path /Users/todd/code/expedition-app/node_modules/es6-promise-plugin/package.json
npm ERR! code ELOOP
npm ERR! errno -62
npm ERR! syscall open
npm ERR! ELOOP: too many symbolic links encountered, open '/Users/todd/code/expedition-app/node_modules/es6-promise-plugin/package.json'
```

The NPM log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/todd/.nvm/versions/node/v8.1.2/bin/node',
1 verbose cli   '/Users/todd/.nvm/versions/node/v8.1.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   'cordova-android@6.2.2',
1 verbose cli   '--save' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session f287ac4f152a5ee4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/cordova-android 19ms (from cache)
8 silly pacote version manifest for cordova-android@6.2.2 fetched in 63ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly fetchPackageMetaData error for es6-promise-plugin@file:node_modules/es6-promise-plugin ELOOP: too many symbolic links encountered, open '/Users/todd/code/expedition-app/node_modules/es6-promise-plugin/package.json'
13 verbose stack Error: ELOOP: too many symbolic links encountered, open '/Users/todd/code/expedition-app/node_modules/es6-promise-plugin/package.json'
14 verbose cwd /Users/todd/code/expedition-app/node_modules
15 verbose Darwin 16.6.0
16 verbose argv "/Users/todd/.nvm/versions/node/v8.1.2/bin/node" "/Users/todd/.nvm/versions/node/v8.1.2/bin/npm" "install" "cordova-android@6.2.2" "--save"
17 verbose node v8.1.2
18 verbose npm  v5.0.3
19 error path /Users/todd/code/expedition-app/node_modules/es6-promise-plugin/package.json
20 error code ELOOP
21 error errno -62
22 error syscall open
23 error ELOOP: too many symbolic links encountered, open '/Users/todd/code/expedition-app/node_modules/es6-promise-plugin/package.json'
24 verbose exit [ -62, true ]
```

**Comment by toddmedema** [comment]
Downgraded from Node 8 to Node 6 (as suggested here: https://github.com/katzer/cordova-plugin-local-notifications/issues/1329) and cordova was able to add android. Still ran into some difficulties with old plugins whose repos lacked package.json files, so had to hunt down forks of those plugins that're maintained / have a package.json file.

**Comment by marcelodeandrade** [comment]
@toddmedema Thank you for the information.

**Comment by pkitatta** [comment]
What was the solution here?

**Comment by hadijahangiri** [comment]
i have this error plz help me

**Comment by madsongr** [comment]
@hadijahangiri Try setting path = "C:\Windows\System32" in variable/system variable

**Comment by satyanarayanapalli** [comment]
add this line in your environment varible in path
C:\Windows\System32
its working now

**Comment by musasesay** [comment]
× Running command - failed!
[ERROR] Exception: Using cordova-fetch for cordova-android@~6.2.2

**Comment by jumong** [comment]
<img width="649" alt="screen shot 2017-08-19 at 2 26 34 am" src="https://user-images.githubusercontent.com/447246/29478344-db04bc5c-8485-11e7-82ee-56343cd76b49.png">

**Comment by jumong** [comment]
<img width="378" alt="screen shot 2017-08-19 at 2 29 31 am" src="https://user-images.githubusercontent.com/447246/29478429-409dae02-8486-11e7-9afd-595066a4f6d5.png">

**Comment by jumong** [comment]
How to fix it ?

**Comment by madsongr** [comment]
@jumong you must open windows environment variables and add to path = "C:\Windows\System32" in system variables

**Comment by musasesay** [comment]
ok thanks

**Comment by jumong** [comment]
@madsongr  my os osX

**Comment by jln1989** [comment]
Am having the same issue now and adding "C:\Windows\System32" did not resolve my issue. Any help here would be great.

My Ionic Info command returns the below: 

> 
>     @ionic/cli-utils  : 1.9.2
>     ionic (Ionic CLI) : 3.9.2
> 
> global packages:
> 
>     Cordova CLI : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.3
>     Cordova Platforms  : android 5.1.1
>     Ionic Framework    : ionic-angular 3.6.0
> 
> System:
> 
>     Node : v6.11.0
>     npm  : 3.10.10
>     OS   : Windows 10

**Comment by Daym3l** [comment]
i have the same error..
I add C:\Windows\System32, but the same error

**Comment by madsongr** [comment]
@jln1989 @Daym3l did you try to open windows cmd again? Every change on system environment variables requires to close cmd and open it again.

**Comment by Daym3l** [comment]
@jln1989  thank you ... 👍

**Comment by madsongr** [comment]
@jln1989 is it working now?

**Comment by Daym3l** [comment]
@madsongr yes thank you

**Comment by Ivan-Perez** [comment]
I downgraded `npm` to version 3.10.0 and worked again. Previously I had npm 5.4.0.

**Comment by topphon** [comment]
I have C:\Windows\System32 already, but I still have this problem.
ps. npm vsersion 3.10.10 and node version 6.11.0

**Comment by Daym3l** [comment]
@topphon  try update to node 8.4.0, work for me...

**Comment by VovanSuper** [comment]
Well, generally adding `System32` folder to path helps; also somehow only powershell running `as administartor` resolves different `EPERM` issues (when building Ionic 3 apps)

**Comment by madsongr** [comment]
@topphon follow the steps from this link [http://ionicframework.com/docs/v1/guide/installation.html](url) and pay attention on red links for windows/linux

**Comment by jln1989** [comment]
@madsongr : Apologies for not getting back early. My issue got resolved yesterday after reinstalling NPM and running the CMD as administrator. Thanks for the help.

**Comment by topphon** [comment]
Thank you, My issue got resolved when I updated to node 8.4.0. and now I got new issue when i use 

> **ionic cordova plugin add https://github.com/phonegap/phonegap-plugin-barcodescanner.git** command

```
> cordova plugin add https://github.com/phonegap/phonegap-plugin-barcodescanner.git --save
× Running command - failed!
[ERROR] An error occurred while running cordova plugin add

        https://github.com/phonegap/phonegap-plugin-barcodescanner.gi... (exit
        code 1):

        Error: Failed to fetch plugin
        https://github.com/phonegap/phonegap-plugin-barcodescanner.git via
        registry.
        Probably this is either a connection problem, or plugin spec is
        incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! code 1
        npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule
        update -q --init --recursive
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule:
        line 7: basename: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule:
        line 7: sed: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule:
        line 19: .: git-sh-setup: file not found
        npm ERR!

        npm ERR! A complete log of this run can be found in:
        npm ERR!
        C:\Users\TopPhon\AppData\Roaming\npm-cache\_logs\2017-08-30T10_30_34_703Z-debug.log
```

**Comment by luckylooke** [comment]
none of the fixes mentioned here helped.. 
cli packages:

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v6.9.5
    npm        : 5.4.0 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

**Comment by crlang44** [comment]
I had this same issue, adding the C:\Windows\System32 did not work for me, and I was already running it as admin. I finally got it to work but downgrading my npm to 3.10.0.

**Comment by JayanthkumarJK** [comment]
Same issue i am encontering in Linux system how to solve this...???

**Comment by crlang44** [comment]
@JayanthkumarJK what version of node and npm are you running? May have to upgrade node to 8.4.0 like @Daym3l or downgrade npm to something like 3.10.0

**Comment by f4bio** [comment]
[work-around](https://github.com/ionic-team/ionic-cli/issues/2538#issuecomment-332099954) at silimar issue (#2538)

**Comment by TomohikoTsuji** [comment]
Install old version.
①npm uninstall -g cordova
②npm install -g cordova@6.5.0
③cordova platform add android

**Comment by rahadur** [comment]
Today i am getting this ERROR, try every possible solution above  mentioned but did not working. 

`× Running command - failed!
[ERROR] Exception: Using cordova-fetch for cordova-android@~6.2.2

        Adding android project...
        Creating Cordova project for the Android platform:
                Path: platforms\android
                Package: io.ionic.starter
                Name: MyApp
                Activity: MainActivity
                Android target: android-25
        Subproject Path: CordovaLib
        Android project created with cordova-android@6.2.3
        Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
        Installing "cordova-plugin-device" for android
        Adding cordova-plugin-device to package.json
        Saved plugin info for "cordova-plugin-device" to config.xml
        Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
        Installing "cordova-plugin-ionic-webview" for android
        Adding cordova-plugin-ionic-webview to package.json
        Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
        Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
        Installing "cordova-plugin-splashscreen" for android
        Adding cordova-plugin-splashscreen to package.json
        Saved plugin info for "cordova-plugin-splashscreen" to config.xml
        Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
        Failed to restore plugin "cordova-plugin-statusbar" from config.xml. You might need to try adding it again.
        Error: Failed to fetch plugin cordova-plugin-statusbar@https://github.com/apache/cordova-plugin-statusbar.git
        via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! Error while executing:
        npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/apache/cordova-plugin-statusbar.git
        npm ERR!
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR! exited with error code: 128

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Rahadur\AppData\Roaming\npm-cache\_logs\2017-10-06T11_51_14_477Z-debug.log
        Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
        Installing "cordova-plugin-whitelist" for android

                        This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a
        previous platform version, you do *not* need this plugin since the whitelist will be built in.

        Adding cordova-plugin-whitelist to package.json
        Saved plugin info for "cordova-plugin-whitelist" to config.xml
        Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project
        Failed to restore plugin "ionic-plugin-keyboard" from config.xml. You might need to try adding it again. Error:
        Failed to fetch plugin ionic-plugin-keyboard@~2.2.1 via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 4294963248 Error output:
        npm ERR! path C:\apps\notes\node_modules\fsevents\node_modules
        npm ERR! code EPERM
        npm ERR! errno -4048
        npm ERR! syscall scandir
        npm ERR! Error: EPERM: operation not permitted, scandir 'C:\apps\notes\node_modules\fsevents\node_modules'
        npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\apps\notes\node_modules\fsevents\node_modules'
        npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir
        \'C:\\apps\\notes\\node_modules\\fsevents\\node_modules\'',
        npm ERR!   errno: -4048,
        npm ERR!   code: 'EPERM',
        npm ERR!   syscall: 'scandir',
        npm ERR!   path: 'C:\\apps\\notes\\node_modules\\fsevents\\node_modules' }
        npm ERR!
        npm ERR! Please try running this command again as root/Administrator.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Rahadur\AppData\Roaming\npm-cache\_logs\2017-10-06T11_52_06_760Z-debug.log
        --save flag or autosave detected
        Saving android@~6.2.3 into config.xml file ...`

**Comment by ThalesMatoso** [comment]
I also have this error, some solution? I've tried everything above, and I'm a linux user.

**Comment by Alb93** [comment]
@TomohikoTsuji solution solved for me.
I'm running on Win10

**Comment by foongpon** [comment]
@TomohikoTsuji solution worked for me too.

**Comment by masrar** [comment]
Error: Failed to fetch platform cordova-android@~6.2.2
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code ENOENT


I have the above problem please help me if anyone knows , thanks .

**Comment by foongpon** [comment]
As @TomohikoTsuji stated, just use the below commands. That worked for me

npm uninstall -g cordova
npm install –g cordova@6.5.0 or npm install –g cordova@latest
ionic cordova platform add android

**Comment by armmmo** [comment]
adding the PATH helped me..thanks

**Comment by lnkhanh** [comment]
Try this:
sudo npm install --global --unsafe-perm cordova-android@latest
and run again :)
ionic cordova platform add android

**Comment by jqzhao** [comment]
I wasn't able to add both cordova-ios@^4.4.0 and cordova-android@^6.2.3. Tried to ran 'npm update' before 'ionic cordova prepare', which updated the version of cordova-ios and cordova-androi and fixed the platform fetch issue.

**Comment by capitalgerald** [comment]
##Here is the Solution that help me.
@jgw96  @jumong 

If you are in Windows usually this kind of error happens when you don't have all the paths required in your system environment path variable . 
Especially the path variables given bellow.

Please paste this line on your system environment Path variable:

**%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;C:\Windows\System32;**

`Then close the current cmd and open a new cmd`

[Visit this Link - That helped me](https://stackoverflow.com/questions/36831690/ionic-platform-error-when-adding-android-platform )

**Comment by suraj1212** [comment]
hey @madsongr  i tried your method but whenever i am setting my path variable to  C:\Windows\System32
i am getting another msg like "node is not recognized as an internal or external command" 
Guys i nedd help...

**Comment by madsongr** [comment]
@suraj1212 probably you don't have node installed globally.

**Comment by lexyfeito** [comment]
So i installed OpenSSH and it erased my whole PATH, adding C:\Windows\System32 to the PATH fixed it

**Comment by phoenixsachin** [comment]
C:\Windows\System32  this is awesome . add to system variable in path.

**Comment by Kreedzt** [comment]
After those steps, i cleaned the dir at `C:\Users\${username}\.config\configstore`.
So that worked.

**Comment by blakcoder2017** [comment]
This worked for me:
`npm cache clean -f`

**Comment by ionic4themes** [comment]
I added C:\Windows\System32 to system variables and clean the directory as @Kreedzt said, but still the same error, please help:

```
> cordova platform add android --save
Using cordova-fetch for cordova-android@~7.1.1
Failed to fetch platform cordova-android@~7.1.1
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\PROYECTOS\\hs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova-android@~7.1.1" "--production" "--save-exact"
npm ERR! node v8.11.3
npm ERR! npm  v2.15.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@2.6.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/compiler-cli@5.1.3 wants typescript@>=2.4.2 <2.6
npm ERR! peerinvalid Peer @angular/tsc-wrapped@4.4.6 wants typescript@^2.1.5
npm ERR! peerinvalid Peer tsickle@0.21.6 wants typescript@^2.1.0
npm ERR! peerinvalid Peer tsutils@2.15.0 wants typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev || >= 2.5.0-dev || >= 2.6.0-dev || >= 2.7.0-dev || >= 2.8.0-dev
npm ERR! peerinvalid Peer tslint@5.8.0 wants typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev

npm ERR! Please include the following file with any support request:
npm ERR!     C:\PROYECTOS\hs\npm-debug.log
[ERROR] An error occurred while running subprocess cordova.

        cordova platform add android --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

**Comment by dante8300** [comment]
Anyone solved this for Linux or iOS ?

**Comment by nebi19** [comment]
10q sir it works

**Comment by oyepez003** [comment]
Try removing the `package-lock.json` and reinstall with `npm install --cache=/tmp/empty-cache`

**Comment by oyepez003** [comment]
Try removing the `package-lock.json` and reinstall with `npm install --cache /tmp/empty-cache`
