### ISSUE TITLE
app-scripts fails to minify es6 code, even when using the harmony branch of uglify-js

### ISSUE THREAD

**Issue by KarimMesallam** [ionic-team/ionic-cli#2414]
**Description:**

**Steps to Reproduce:**

Example repo: N/A

1. import an es6 library like `@types/lodash`
2. Run ionic `cordova build android --prod` or `ionic cordova build ios --prod`
3. You'll get the error mentioned below.
4. follow jgw96 comment here: https://github.com/ionic-team/ionic-app-scripts/issues/239 that says the following:

> On your root project directory, edit node_modules/@ionic/app-scripts/package.json file. Then in that file update uglify-js like this "uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony".
> 
> Then after that execute npm install (make sure right now you're at node_modules/@ionic/app-scripts. Ignore error that shown. I have shown error about jasmine's build for path variable that it seems like it need src, but it works at the end.

5. You'll still get the same error mentioned in the output below.

**Output:**

```
[21:42:34]  build prod started ...
[21:42:34]  clean started ...
[21:42:34]  clean finished in 2 ms
[21:42:34]  copy started ...
[21:42:34]  ngc started ...
[21:42:47]  ngc finished in 12.12 s
[21:42:47]  preprocess started ...
[21:42:47]  deeplinks started ...
[21:42:48]  deeplinks finished in 1.03 s
[21:42:48]  optimization started ...
[21:42:48]  copy finished in 13.41 s
[21:43:08]  optimization finished in 20.37 s
[21:43:08]  preprocess finished in 21.40 s
[21:43:08]  webpack started ...
[21:44:41]  webpack finished in 93.22 s
[21:44:41]  sass started ...
[21:44:41]  uglifyjs started ...
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of date.
Error: Unexpected token operator «=», expected punc «,» in /Users/UserName/Sites/AppName/www/build/main.js at line 110238, col 38, pos 4240027
```

**My `ionic info`:**

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.10.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13

```

**Other Information:**

- I have been able to fix this issue on old `app-scripts` versions but was never able to fix it on `app-scripts@v1.3.7`.
- I think `app-scripts` should rely on https://github.com/mishoo/UglifyJS2/tree/harmony out of the box.
- This is a very critical issue blocking the production of our app that we've been developing for almost a full year.

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1032
