### ISSUE TITLE
HTTP 404 Running NPM Install

### ISSUE THREAD

**Issue by mateusmcg** [ionic-team/ionic-cli#2416]
**Ionic version: (check one with "x")**
[ ] 1.x (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] 2.x
[x] 3.x

**I'm submitting a ... (check one with "x")**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Description:**

I get the following error after creating a new application, on the "npm install" step:

```
$ ionic start beep blank
✔ Creating directory .\beep - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank (https://github.com/ionic-team/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
        npm WARN prefer global node-gyp@3.6.2 should be installed with -g

        > node-sass@4.5.0 install C:\_Repos\Udemy\beep-chatapp\beep\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

        HTTP error 404 Not Found
```

I don't think the entire log will be needed because the error itself is shown above (Cannot download - HTTP 404).

Maybe the SASS team removed this zip file?

But dispite that, i tried to run the application to see if its working anyway, and i get the following:

```
$ ionic lab
Error: Cannot find module '@ionic/app-scripts'
```

**Steps to Reproduce:**
See above.

**Example repo**: 

N/A

**Output:**

**My `ionic info`:**

In failing project dir:

```
$ ionic info
[ERROR] Error with .\node_modules\@ionic\app-scripts\package.json file: FILE_NOT_FOUND

global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : not installed
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v8.0.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

Outside project dir:

```
$ ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

System:

    Node       : v8.0.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by piotrowski** [comment]
Ionic CLI (or more correctly `@ionic/app-scripts`) is not ready for Node v8 yet as it uses a `node-sass` version that didn't support node8 on Windows. The change is already merged in app-scripts, but not yet released.

**Comment by mateusmcg** [comment]
@piotrowski Thanks for the quick resposne.

In fact, i downgraded node from v8 to v7.6.0 and all seems to work fine with ionic CLI.

The next Ionic CLI version (3.4.0?) will have this fix then?

**Comment by piotrowski** [comment]
Next version of `@ionic/app-scripts`, that is part of Ionic CLI, will.

**Comment by saivamsi123** [comment]
I am stucked please help me with this error
 Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):


        npm WARN deprecated @angular/http@5.0.0: Switch to @angular/common/http - see https://angular.io/guide/http
        npm WARN deprecated sw-toolbox@3.6.0: Please migrate to Workbox:
        https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
        npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in
        other tools.

        > node-sass@4.5.3 install F:\manavooru\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-67_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-67_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
               try setting a proxy via HTTP_PROXY, e.g.

               export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

               npm config set proxy http://example.com:8080

        > uglifyjs-webpack-plugin@0.4.6 postinstall F:\manavooru\node_modules\uglifyjs-webpack-plugin
        > node lib/post_install.js


        > node-sass@4.5.3 postinstall F:\manavooru\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Program Files\nodejs\node.exe F:\manavooru\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose
        --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'F:\\manavooru\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.8.0
        gyp info using node@11.9.0 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (F:\manavooru\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (F:\manavooru\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (F:\manavooru\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at F:\manavooru\node_modules\which\which.js:89:16
        gyp verb `which` failed     at F:\manavooru\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at F:\manavooru\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:159:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (F:\manavooru\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (F:\manavooru\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (F:\manavooru\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at F:\manavooru\node_modules\which\which.js:89:16
        gyp verb `which` failed     at F:\manavooru\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at F:\manavooru\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:159:21)
        gyp verb `which` failed   stack:
        gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError
        (F:\\manavooru\\node_modules\\which\\which.js:13:12)\n    at F
        (F:\\manavooru\\node_modules\\which\\which.js:68:19)\n    at E
        (F:\\manavooru\\node_modules\\which\\which.js:80:29)\n    at
        F:\\manavooru\\node_modules\\which\\which.js:89:16\n    at F:\\manavooru\\node_modules\\isexe\\index.js:42:5\n  
        at F:\\manavooru\\node_modules\\isexe\\windows.js:36:5\n    at FSReqCallback.oncomplete (fs.js:159:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` succeeded python C:\Users\Vamsi\AppData\Local\Programs\Python\Python36-32\python.EXE
        gyp ERR! configure error
        gyp ERR! stack Error: Command failed: C:\Users\Vamsi\AppData\Local\Programs\Python\Python36-32\python.EXE -c
        import sys; print "%s.%s.%s" % sys.version_info[:3];
        gyp ERR! stack   File "<string>", line 1
        gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
        gyp ERR! stack                                ^
        gyp ERR! stack SyntaxError: invalid syntax
        gyp ERR! stack
        gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
        gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
        gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
        gyp ERR! System Windows_NT 10.0.17134
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\manavooru\\node_modules\\node-gyp\\bin\\node-gyp.js"
        "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd F:\manavooru\node_modules\node-sass
        gyp ERR! node -v v11.9.0
        gyp ERR! node-gyp -v v3.8.0
        gyp ERR! not ok
        Build failed with error code: 1
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted
        {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.5.3 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Vamsi\AppData\Roaming\npm-cache\_logs\2019-06-04T06_21_20_569Z-debug.log
