### ISSUE TITLE
--no-build argument for `ionic cordova build`

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2420]
It would be great if you could trigger a `cordova build` via Ionic without forcing a `ionic:build` again (but getting all the other stuff `ionic` does) if you already know that `/www` is in a good state.

Use case example:
https://forum.ionicframework.com/t/solved-is-there-a-cmd-to-build-both-android-and-ios-at-the-same-time/93799

**Comment by dwieeb** [comment]
Good idea, thanks.
