### ISSUE TITLE
Cannot find module 'amdefine'

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-cli#2423]
**Description:**
Today I installed `ionic@3.4.0` and run `ionic serve` on our `ionic@3.0.1` project.

As expected the ionic cli is asking to upgrade also the plugins, and this is the output

michi@zotacei730:~/software/workspace/web-client-ionic$ ionic serve
? Local plugin @ionic/cli-plugin-cordova has an update available (1.3.0 => 1.4.0)! Would you like to install it? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
✔ Running command - done!
[OK] Upgraded @ionic/cli-plugin-cordova to 1.4.0! 🎉
? Local plugin @ionic/cli-plugin-ionic-angular has an update available (1.3.0 => 1.3.1)! Would you like to install it? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
✔ Running command - done!
[OK] Upgraded @ionic/cli-plugin-ionic-angular to 1.3.1! 🎉
Error: Cannot find module 'amdefine'

As you can see at the end the process is stopping by the error
`Error: Cannot find module 'amdefine'`

**My `ionic info`:**

```
global packages:
    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.0.1

System:
    Node       : v6.11.0
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3
```

**Comment by mburger81** [comment]
I have to revert to previous version, always
```
ionic serve
Error: Cannot find module 'amdefine'
```

**Comment by mburger81** [comment]
As reverting does not work I tried to resolve this issue by remove anything, nodejs and npm installed globally and any node module installed globally. Also I removed any .npm folder for sudo and for user

After that I installed simple ionic and cordova by `sudo npm install -g cordova ionic`
and then I tried to do a fresh install on our ionic project, but I got the same error

The next thing is I installed manually `process-nextick-args` `buffer-shims` and `amdefine` with
```
sudo npm install -g process-nextick-args
sudo npm install -g buffer-shims
sudo npm install -g amdefine

```
and re-do a clean `npm install` which now works.

So I can run `ionic serve` which starts but with an error:
```
[11:41:49]  typescript: src/components/player/webrtc-player/la-webrtc-player.component.ts, line: 5 
       Cannot find name 'require'. 

       L4:  import { LaWebRTCPlayerStore } from './la-webrtc-player.store';
       L5:  var JsSIP = require('../../../../node_modules/jssip/dist/jssip.min.js');

```
So I can not use a require anymore.

Bug problems updating new cli and the biggest problem is we can not revert anymore!!!!

Removing require the app is loading and anything is fine, but there are several problems we have to arrive at this point.

**Comment by mburger81** [comment]
I found the problem, upgrading to ionic@3.4.0 was breaking me the `package-lock.json` file which was introduced in `npm@5.0`

After deleting this file from ionic project and removing global modules `process-nextick-args` `buffer-shims` and `amdefine` installed before I re-do simple `npm install` and everything works like a sharm!!! :+1: 

**Probably the problem is the ionic serve functionallity which is asking the update of the plugin, this is going breaking the package-lock.json file.**

But there remains the problem of require which doesn't work anymore. Also reverting to ionic@3.3.0 and dependencies require does not work.

So resuming there are two problems
a) broken `npm install` after `ionic serve`'s automatic plugin updating, resolving by removing lock file
b) require which does not work anymore?

**Comment by dwieeb** [comment]
a) we simply run `npm install --save-dev --save-exact @ionic/cli-plugin-x@latest` to update the plugins, as you can see from the command output. If npm's new `package-lock.json` can't figure that out, then it's a bug in npm. I'm not personally recommending npm@5 to people yet. I think there's some work that needs to be done.

b) you can't use `require` in a browser app, it's a node construct.
