### ISSUE TITLE
PLUGIN_NOT_INSTALLED on ionic use and ionic serve did not start (npm 5, ionic 3)

### ISSUE THREAD

**Issue by patrickbussmann** [ionic-team/ionic-cli#2424]
**Description:**
I updated my npm packages.

    npm i -g npm @angular/cli @ionic/cli-plugin-cordova bower-npm-resolver ionic mjml node-gyp

And after that I removed the node_modules folder of my project.

    rm -rf node_modules

And then I installed them again.

    npm install

And then I tried to ionic serve.

    ionic serve -a --nobrowser

And then I get this error.

	[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
	[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
	[DEBUG] Throwing PLUGIN_NOT_INSTALLED for local @ionic/cli-plugin-cordova
	[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
	[DEBUG] Throwing PLUGIN_NOT_INSTALLED for local @ionic/cli-plugin-ionic-angular
	[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
			Checking for CLI updates now...
	[DEBUG] Plugin error: PLUGIN_NOT_INSTALLED
	[DEBUG] Getting plugin info for ionic
	[DEBUG] Getting plugin info for @ionic/cli-plugin-proxy
	[DEBUG] Checking for latest plugin version of ionic@latest.
	[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-proxy@latest.
	PLUGIN_NOT_INSTALLED
	[DEBUG] Latest version of ionic@latest is 3.4.0.
	[DEBUG] Latest version of @ionic/cli-plugin-proxy@latest is 1.3.1.
	[ERROR] No updates found after plugin error--please report this issue.

You can see in ionic info at the bottom of this post that the info is working. Only `ionic serve` seems to be broken.

**Steps to Reproduce:**
See description above.

**Output:**

	[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
			Checking for CLI updates now...
	PLUGIN_NOT_INSTALLED
	[ERROR] No updates found after plugin error--please report this issue.

**My `ionic info`:**

	$ ionic info
	[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
			Checking for CLI updates now...
	PLUGIN_NOT_INSTALLED
	[ERROR] No updates found after plugin error--please report this issue.

	global packages:

		@ionic/cli-utils : 1.4.0
		Ionic CLI        : 3.4.0

	System:

		Node       : v6.9.1
		OS         : Windows 10
		Xcode      : not installed
		ios-deploy : not installed
		ios-sim    : not installed
		npm        : 5.0.3

Thank's in Advance for any informations :+1:

**Comment by dwieeb** [comment]
@patrickbussmann What version of the local plugins do you have in your `package.json`?

**Comment by shamank** [comment]
You can see my fix here https://forum.ionicframework.com/t/error-error-occurred-while-loading-plugins-cli-functionality-may-be-limited/94176

Take note that I'm using ionic as local in my project, so you'd need to add `-g` to every url.

**Comment by Wunmest** [comment]
i had also encountered this problem after i updated to 3.4.0.
then i removed the node_modules folder, and npm install.
it works

**Comment by danielsogl** [comment]
@Wunmest there is not Ionic 3.4 release. Why do you isntalled this version?

**Comment by Wunmest** [comment]
@danielsogl It seems like a WebStorm prompt  when run ionic serve, and the npmjs.com also update to ionic 3.4, [https://www.npmjs.com/search?q=ionic](url).
It seems that many people have encountered this problem in the last few hours  because of the upgrade to 3.4

**Comment by danielsogl** [comment]
But there is no "Upgrade to 3.4 Guide" or something else. 
I think you and other people with this problem thought Ionic CLI 3.4 == Ionic-Angular 3.4

**Comment by danielsogl** [comment]
@patrickbussmann why did you installed `@ionic/cli-plugin-cordova` global? You only have to install this plugin in your dev dependencies.

**Comment by patrickbussmann** [comment]
Hey @danielsogl,

why it make no sense?
I'm using ionic globally. So if I use the ionic comand on folders I want that it work.
The cli-plugin-cordova is installed globally **and** local so don't know why it's not working.

The main problem is that if I'm using `ionic -v` it shows the error **BUT** the version is shown or only `ionic` command then the commands are shown.

So there must be a problem with the `serve` command and not with ionic cli.


I downgraded npm to 4.6.1 with `npm -g i npm@4` and now after reinstall node_modules it works.
So there must be a problem between ionic 3 and npm 5.

**Comment by janpio** [comment]
@Wunmest @danielsogl Actually there is no real reason to have `ionic` (the Ionic CLI) in `package.json` unless you really, really know what you are doing. Normally you install `ionic` globally and are done with it.

@patrickbussmann Afaik the Cordova plugin is expected to be installed locally and is matches the cordova-* "packages" you are using in /platforms. If you are on Windows there are still problems with npm5, but you would get an error when you create a project with `ionic start` as it can't install the project properly. Otherwise there are no known problems with npm5.

**Comment by dwieeb** [comment]
@patrickbussmann Have you had a chance to read up on the latest release? https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#360-2017-07-27 I think you'll like the changes re: local CLI. Basically, we don't mix global/local `node_module` folders anymore. Things should be less confusing because the CLI is either working globally or locally.

I am closing this for now, but please make a new issue if something doesn't seem right.
