### ISSUE TITLE
[Feature Request] Pass in a flag to the CLI to disable update prompts

### ISSUE THREAD

**Issue by Tankatronic** [ionic-team/ionic-cli#2425]
**Description**
I have an automated build set up on TFS 2017 where I run 'ionic cordova build browser'. Whenever there is an update to a local plugin, it generates a prompt asking if I would like to update the plugin. At this point, TFS considers the command completed and considers it successful. I would like to be able to pass in a flag to prevent ionic from checking for updates and just run the command.

**Comment by Tankatronic** [comment]
Nevermind. Found another issue someone submitted related to no-interactive mode already.

**Comment by dwieeb** [comment]
@Tankatronic The next release will be using the `ci-info` npm package to automatically do this. 😄
