### ISSUE TITLE
ionic-cli trying to update plugins with -g but I'm using ionic as local in my project

### ISSUE THREAD

**Issue by shamank** [ionic-team/ionic-cli#2427]
I know it's not usual, but since new Ionic cli versions are not fully backward compatible with beta versions (specially some plugins and dependencies), I was required to find a way to work with "static" Ionic / Cordova versions in my projects. I was able to do it by modifying my ~/.bashrc like this:
```bash
...
export NODE_LOCAL="./node_modules/.bin"
export PATH=...:${NODE_LOCAL}:$PATH
set +h
```
And installing ionic and cordova without the "-g" param.
The new cli has a new feature that checks for new cli/plugin versions and can automatically download and deploy them in the current environment, but it always adds the "-g" param, assuming I'm using ionic-cli from my global installation.

It would be nice if the cli could try to determine if the current ionic command is being executed from my local project (like analyzing a simple `which ionic` command) so not to add the "-g" param and install it in locally.

BTW, the most of Linux users (at least those ones using Ubuntu, like me), need to run npm installs with sudo, and since these updates appears with simple commands like `ionic serve` which they don't need it, they will allways fail because of permissions.

Thanks!

**Comment by dwieeb** [comment]
@shamank Most people run the CLI globally, and it doesn't add the `-g` flag for CLI plugins (except the proxy plugin). What you're saying doesn't make sense. Can you fill out the issue template so I know more about your environment. I need `ionic info` and command output.

Linux users do not need to run npm installs with sudo. See [the npm docs](https://docs.npmjs.com/getting-started/fixing-npm-permissions). Additionally, you said yourself that you're using all local packages, which would never need sudo unless you overwrote some local files as root by an accidental `sudo npm install`.

**Comment by shamank** [comment]
@dwieeb In OSX you don't need sudo for npm global installs, but in Linux (Ubuntu at least), yes. It's the default way you install npm and global packages. Of course you can change this, but this is the default install way for everybody.

> Most people run the CLI globally, and it doesn't add the -g flag for CLI plugins (except the proxy plugin). What you're saying doesn't make sense. Can you fill out the issue template so I know more about your environment. I need ionic info and command output.

You are right, most of people don't do that. That's why I started like this: "I know it's not usual...". But you are wrong with these words "it doesn't make sense". If you are using Ionic since it was a beta (specially before beta 10) and you have built a robust app that includes a lot of third party code, native and old plugins, you may find that your app won't work anymore in cli v3, even with last v2 versions. So, if you have an old app and your client tells you that you need to replace the splash image, I can't tell them that the cost of changing an image is the cost of refactoring the app to fit Ionic 3 requirements. And it will happen again with Ionic 4, 5 or 6 in the future. So this is why I'm working like this and if you think my case is 1 in 1 million, it's unreal and makes no sense, well, I disagree my friend.

**Comment by shamank** [comment]
Sorry, I forgot "ionic info" data.

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : Linux 3.19
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3 
```

**Comment by shamank** [comment]
> and it doesn't add the -g flag for CLI plugins (except the proxy plugin)

Sorry, I misunderstood this. You are right, it's not adding the -g param for installing those. I'm pretty sure I saw something trying to install in the global scope but I can't find it now, so my apologies. Anyway, updating to npm 5.x started the problem with Ionic. You can close this issue.

**Comment by shamank** [comment]
BTW,
```bash
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for local @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for local @ionic/cli-plugin-ionic-angular
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[DEBUG] Plugin error: PLUGIN_NOT_INSTALLED
[DEBUG] Getting plugin info for ionic
[DEBUG] Checking for latest plugin version of ionic@latest.
PLUGIN_NOT_INSTALLED
[DEBUG] Latest version of ionic@latest is 3.4.0.
[ERROR] No updates found after plugin error--please report this issue.
```
Those plugins were already locally installed when running `$ ionic serve --verbose`. That started happening after npm update.

**Comment by dwieeb** [comment]
Sorry, there's been some misunderstandings. I understand the value of running the CLI locally. I've been working on it on a local branch to allow exactly this. It's just not as easy as it sounds to make it a great experience and all the plugin code assumes global usage, which is why you're getting weird messages. 

I'm gonna migrate this issue here, because there may be a bunch of issues with a local CLI installation that I haven't considered: https://github.com/ionic-team/ionic-cli/issues/2443

**Comment by shamank** [comment]
> It's just not as easy as it sounds to make it a great experience and all the plugin code assumes global usage, which is why you're getting weird messages.

I can imagine the trouble behind the scenes, specially because of interoperability (plugins, npm, etc) and I completly understand what you mean. So I can only say: good luck! Thanks.

**Comment by dwieeb** [comment]
@shamank I think you'll like the new CLI when it's released. (Look for 3.6.0 release tomorrow.) If something is still not fulfilling your use case, please let me know ASAP (make a new issue please) and I will do what needs to be done. 😄

**Comment by shamank** [comment]
Great! Can't wait to test this :) thanks!
