### ISSUE TITLE
Whenever using livereload on device with ionic v1 and cli v3 the device's browser doesn't refresh

### ISSUE THREAD

**Issue by Spriz** [ionic-team/ionic-cli#2433]
**Description:**
Whenever using `$ ionic cordova run ios --device --livereload` the device's browser (iPhone 6 iOS 10 + Oneplus One Android 6) doesn't reload. The files are transfered without issue but the reload itself is not triggered

**Steps to Reproduce:**
run `$ionic cordova run ios --device --livereload` and change a file in your code.

**Output:**
No changes happens on the device

**My `ionic info`:**
```
$ ionic info
? Looks like this is an Ionic Angular project, would you like to install @ionic/cli-plugin-ionic-angular and continue? No
[ERROR] Error with /Users/.../www/lib/ionic/version.json file: FILE_NOT_FOUND

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Gulp CLI         : CLI version 3.9.1 Local version 3.9.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/cli-plugin-cordova : 1.4.0
    @ionic/cli-plugin-gulp    : 1.0.1
    @ionic/cli-plugin-ionic1  : 2.0.0
    Cordova Platforms         : android 6.2.3 ios 4.4.0
    Ionic Framework           : unknown

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : not installed
    ios-sim    : 5.1.0
    npm        : 5.0.3
```

**Other Information:**
Discussed on Ionic slack and @mhartington could successfully reproduce this.

**Comment by mateosss** [comment]
@dwieeb Is this expected behaviour for v1 projects?

**Comment by dwieeb** [comment]
No, it's not. I found the bug and a fix will be in the next release. My apologies!
