### ISSUE TITLE
`ionic g` can generate a telephone!

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2439]
```
PS C:\Users\Jan\Documents\superTest> ionic g telephone foo
[OK] Generated a telephone named foo!
```
No file changes of course.

**ionic info**

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0

**Comment by dwieeb** [comment]
I'm using this issue because I'm just going to do a big refactor of generators: https://github.com/ionic-team/ionic-cli/issues/2407

There are a bazillion of generator issues.
