### ISSUE TITLE
Unable to pass custom parametrs to hooks

### ISSUE THREAD

**Issue by jgermanis** [ionic-team/ionic-cli#2440]
**Description:**
Running ionic cordova build android --customParam, it is not passing --customParam to cordova build therfore it can not be used in hooks.

**Steps to Reproduce:**

Example repo: https://github.com/jgermanis/cli-test.git

1. ionic cordova build android --customParam

**Output:**
Hook listing available proc.args, there is no customParam in the args:

> cordova build android
/ Running command [17:18:03]  lint finished in 2.84 s
✔ Running command - done!
test hook script
proc value:  C:\Program Files\nodejs\node.exe
proc value:  C:\Users\Janis\AppData\Roaming\npm\node_modules\cordova\bin\cordova
proc value:  build
proc value:  android

**My `ionic info`:**

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.0.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.8

**Other Information:**
It should pass the custom parameters to cordova so it could be used in the hooks

**Comment by coltcook** [comment]
Agreed. This is a pretty big pain point.

**Comment by dwieeb** [comment]
You are using Cordova hooks. Follow their hook guide for `context`, which has all the information you'll need: https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/

Since you're wrapping Cordova CLI with Ionic CLI, you'll need to separate the args:
```bash
ionic cordova build android -- --customParam
```
