### ISSUE TITLE
ionic v3.4.0 to ionic v1 downgrade issue

### ISSUE THREAD

**Issue by Senthilkumark** [ionic-team/ionic-cli#2445]
I am trying to downgrade ionic v3.4.0 to ionic v1.

npm install -g ionic
npm uninstall -g ionic
npm install -g ionic@1.7.8

While try to download 1.7.8 i am getting ionic v3.4.0 
How achieve version degradation Could you help in this one.

**Comment by danielsogl** [comment]
I don't get it. Why do you want to downgrade?
And you can't downgrade just by changing the dependencies.
Ionic v2 runs with AngularJs while Ionic 2.0 and newer runs with Angular.
If you want to start a new Ionic V1 project check out the Ionic CLI doc's first.

**Comment by Senthilkumark** [comment]
i checked the V1 doc's and followed the steps. It's not downloading v1 but i got 3.4.0.

**Comment by danielsogl** [comment]
@Senthilkumark Ah okay. Yes the V1 docs are out of date. Here do you find the updated CLI Docs: https://ionicframework.com/docs/cli/

To start a new V1 project run this: `ionic start mynewapp blank --type ionic1`

**Comment by Senthilkumark** [comment]
@danielsogl  : i have already ionic v1 project but my cli in 3.4.0  so i could't able to run my code.
Anyway to get ionic v1  restore .

**Comment by danielsogl** [comment]
@Senthilkumark The Ionic CLI has nothing to do with your Ionic project. Ionic CLI != Ionic Angular.
I posted the link to the new CLI. I don't have problems to run Ionic V1 projects with the newest CLI release.

**Comment by Senthilkumark** [comment]
BLRPYANGA42426:iOS skuppu$ cordova build ios
 Using this version of Cordova with older version of cordova-ios is deprecated. Upgrade to cordova-ios@4.0.0 or newer.
Error: Your ios platform does not have Api.js


I am getting error like this and old command also not working

**Comment by alvaromorenomorales** [comment]
@danielsogl Hi I´ve just updated ionic cli to version 3.20.0 and I did a new project. The new project has the 1.3.4 version but on github I can see the 1.3.5. How can I force the use of the latest version? Is [this url ](https://github.com/ionic-team/ionic-v1)repo an unofficial one?

Thank in advance.

**Comment by dwieeb** [comment]
This is the official repo for Ionic 1: https://github.com/ionic-team/ionic-v1

Use bower to upgrade it. Look at the `bower.json` file.
