### ISSUE TITLE
can't generate icon and splash in ionic 2

### ISSUE THREAD

**Issue by Marimuthu1** [ionic-team/ionic-cli#2447]
Output:
 Collecting resource configuration and source images - done!
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of
       date.
✖ Uploading source images to prepare for transformations - failed!
HTTP Error 403: POST https://res.ionic.io/api/v1/upload
<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>

<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</ ...

[ truncated 4526 characters ]

My ionic info:
global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Cordova CLI             : 7.0.1
    Ionic CLI               : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

   I have icon.png with 192x192 px and have splash.png with 2208x2208 px.
   When i try with ionic cordova resources shows above error.
   I tried different project and different desktop also.

**Comment by janpio** [comment]
Open this URL manually: https://res.ionic.io/api/v1/upload It will probably show a Captcha or something.

**Comment by Marimuthu1** [comment]
Hi thanks for your response.

when open this url i am getting below output.

"{"Error":"invalid request: GET","Width":0,"Height":0,"Type":"","Vector":false}"

How to resolve this issue?

**Comment by janpio** [comment]
Try again on the command line - this request seems to have gone through no problem.

**Comment by Marimuthu1** [comment]
yes. i got that. last two days it is not working. But now i try with

ionic cordova resources android --icon

its working. both app icon and splash.

**Comment by janpio** [comment]
Great. 

As an explanation: Cloudflare is used as a CDN in front of the API that generates the resources for you. Seems Cloudflare somehow decided you (your IP address) are/were "bad" and blocked your requests. If this happens in the browser they show a Captcha for you to solve to prove you are "good", but of course you can't do that on the command line.

**Comment by Marimuthu1** [comment]
okay, thank you for your valuable information

**Comment by arumuganainar** [comment]
when i run app into command line  getting below output.

✖ Uploading source images to prepare for transformations - failed!
HTTP Error 400: POST https://res.ionic.io/api/v1/upload

{"Error":"unable to read uploaded image","Width":0,"Height":0,"Type":"png","Vector":false}

**Comment by yassen-itlabs** [comment]
@arumuganainar: make sure the size of your images needs to be exactly the same as the samples there (icon: 192x192, splash: 2732x2732).

**Comment by Antoniely** [comment]
Saludos : 
La solución es como dice el compañero @yassen-itlabs pero con la dimension 1024 x 1024.
Cuando lo intentaba subir con la demension 192x192 solo me transformo 8 de 32 img.
Solo utilize este editor en line http://www.online-image-editor.com/ o programa que prefieran le quite el fondo y renderize a 1024x1024 y listo.

**Comment by elalealvaro** [comment]
@Antoniely is right, I wrongly had an icon with 1025x1025 and got the error. I modify it to 1024x1024 and works as expected!

**Comment by Antoniely** [comment]
@elalealvaro How good to have helped you

**Comment by ricardoparro** [comment]
remove transparent backgrounds and should work as a charm

**Comment by patrickegp** [comment]
my solution was select one of the default icons inside icon/icon-1024.png and modify it, then copy and paste un /sources/ then use ionic source bla bla bla icon and it work perfectly, and the same for the splash. hope its help someone

**Comment by shadygoneinsane** [comment]
IDK why but its not working

**Comment by brianivander** [comment]
Mine was related to my wifi problem. I suppose it has some kinda security feature that makes it a problem. Try to use other wifi or internet network.

In my case, I was using my office's wifi and I had that problem. I changed to my own mobile hotspot and now it works.

**Comment by tingweibai** [comment]
https://res.ionic.io/api/v1/upload not work again, it is a problem server? have to wait?
