### ISSUE TITLE
.gitignore files can have .vscode/

### ISSUE THREAD

**Issue by amandeepmittal** [ionic-team/ionic-cli#2448]
**Description:**

Every time I setup a new Ionic Project with any template, I have to manually update `.gitignore` file to add `.vscode/` directory. I hope you take this in consideration as quite a few developers are using VSCode for Ionic development.

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.4.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.1 Build version 8B62
    ios-deploy : not installed
    ios-sim    : not installed

**Other Information:**

**Comment by danielsogl** [comment]
@amandeepmittal are your sure? Look here: https://github.com/ionic-team/ionic2-app-base/blob/master/.gitignore

The vsc files are already added to the .gitignore. Btw this has nothing to do with the Ionic CLI

**Comment by amandeepmittal** [comment]
@danielsogl You are right. It's there. I did not look carefully, my bad. May be the other project had a modified `.gitignore` by me already.
