### ISSUE TITLE
CLI 3.4.0: Empty lines when running "run android"

### ISSUE THREAD

**Issue by JaneDawson** [ionic-team/ionic-cli#2450]
**Description:**
Since upgrading to Ionic CLI 3.4.0 I have several blank lines when running `ionic cordova run android --prod`.
See picture: http://i.imgur.com/tUhg4aa.png

**Comment by janpio** [comment]
Same for `ionic cordova run android`?
Same for `npm run ionic:build` and `npm run ionic:build --prod`?

**Comment by JaneDawson** [comment]
`ionic cordova run android`: Yes, same problem
`npm run ionic:build`: Everything works as expected.
`npm run ionic:build --prod`: Everything works as expected.

**Comment by janpio** [comment]
Ok, last one to try: `cordova run android`

**Comment by JaneDawson** [comment]
`cordova run android`: Works as expected, no blank lines

**Comment by JaneDawson** [comment]
Any idea what this is about?

**Comment by janpio** [comment]
I don't, but I think we collected enough information about this now so someone from the team might be able to debug this.

It's only a cosmetic "problem", right?

**Comment by JaneDawson** [comment]
Yes, you are right, this is more or less o cosmetic issue. However, the speed of building for android differs a lot as well, but this issue might be unrelated.

`ionic info` gives me:

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by JaneDawson** [comment]
I just recognized, that the lines are not really empty. The color of the font at this point is just the same as the background. Beginning from `cordova run android` the font color becomes normal again...

**Comment by janpio** [comment]
Can you copy/paste them here so we can check if the content is normal?

**Comment by JaneDawson** [comment]
sure:

```
ionic cordova run android --prod
Running app-scripts build: --prod --address 0.0.0.0 --port 8100 --p 8100 --livereload-port 35729 --r 35729 --iscordovaserve --externalIpRequired --nobrowser
**[from here on everything is hidden]**
[18:45:08]  build prod started ...
[18:45:08]  clean started ...
[18:45:08]  clean finished in 3 ms
[18:45:08]  copy started ...
[18:45:08]  ngc started ...
[18:45:23]  ngc finished in 15.59 s
[18:45:23]  preprocess started ...
[18:45:23]  deeplinks started ...
[18:45:24]  deeplinks finished in 745 ms
[18:45:24]  optimization started ...
[18:45:25]  copy finished in 16.80 s
[18:45:41]  optimization finished in 16.42 s
[18:45:41]  preprocess finished in 17.17 s
[18:45:41]  webpack started ...
[18:46:00]  webpack finished in 18.99 s
[18:46:00]  sass started ...
[18:46:00]  uglifyjs started ...
[18:46:02]  sass finished in 2.00 s
[18:46:02]  cleancss started ...
[18:46:04]  cleancss finished in 2.89 s
[18:46:23]  uglifyjs finished in 23.72 s
[18:46:23]  postprocess started ...
[18:46:23]  postprocess finished in 11 ms
[18:46:23]  lint started ...
[18:46:23]  build prod finished in 75.57 s
> cordova run android **[from here on everything is visible as expected]**
```

**Comment by janpio** [comment]
That's normal. 

Could you create a new issue that only includes the relevant information (invisible output, ionic info) and says that the build process output is invisible for you, then close this issue?

**Comment by JaneDawson** [comment]
[done](https://github.com/ionic-team/ionic-cli/issues/2458). 
Thank you.
