### ISSUE TITLE
`node_modules` and `package.json` mismatch

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2453]
Probably one of the most widespread reasons for longtime problems with projects (when the project should be update 6 months later, when projects are handed off to new developers, when developers change their development machine) are incorrect `package.json` files.

Could Ionic CLI maybe support developers a bit here? 
Is there a command that could e.g. be run asynchronously when building that warns people that their `package.json` doesn't match the installed packages?

**Comment by dwieeb** [comment]
I can't write a package manager into the CLI. People really need to learn npm and node environments if they hope to properly manage such things. Or use yarn.

**Comment by janpio** [comment]
Luckily this will (hopefully) go away with adoption of npm5 where `--save` is default.

**Comment by dwieeb** [comment]
Yes, I think npm 5 is improving things slowly.
