### ISSUE TITLE
`undefined` exception when running `ionic state restore`

### ISSUE THREAD

**Issue by rquinlivan** [ionic-team/ionic-cli#2455]
I ran `ionic state restore` and got the following exception that has halted the CLI runner. I'm afraid I don't have much context for this project, so I can't read the tea leaves here, just reporting the issue.

This is my output from `ionic state restore`:
 
`******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios@4.3.0
cordova platform add android@6.1.2

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-globalization
cordova plugin add cordova-plugin-file
cordova plugin add cordova-plugin-inappbrowser
cordova plugin add cordova-plugin-file-transfer
cordova plugin add cordova-plugin-network-information
cordova plugin add cordova-plugin-camera
cordova plugin add cordova-plugin-media-capture --variable CAMERA_USAGE_DESCRIPTION="We'd like to access your camera to let you take a photo" --variable PHOTOLIBRARY_USAGE_DESCRIPTION="We'd like like to open your photo library to let you pick a photo" --variable MICROPHONE_USAGE_DESCRIPTION="We'd like to access your microphone to let you record an audio" 
cordova plugin add cordova-plugin-splashscreen
cordova plugin add cordova-plugin-statusbar
cordova plugin add cordova-plugin-whitelist
cordova plugin add https://github.com/Tunts/WebIntent 
cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME="moodlemobile" 
cordova plugin add ionic-plugin-keyboard
cordova plugin add https://github.com/ti8m/DocumentHandler 
cordova plugin add cordova-plugin-local-notifications-mm
cordova plugin add cordova-plugin-zip
cordova plugin add phonegap-plugin-push --variable SENDER_ID="694767596569" 
Caught exception:
 undefined 
`

**Comment by davidecheli** [comment]
I'm having the same issue:

```
> ionic state restore

Restoring Platforms


Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-console
cordova plugin add cordova-plugin-whitelist
cordova plugin add cordova-plugin-transport-security
cordova plugin add cordova-plugin-network-information
cordova plugin add cordova-plugin-inappbrowser
cordova plugin add cordova-plugin-geolocation
cordova plugin add ionic-plugin-keyboard
cordova plugin add https://github.com/phonegap-build/PushPlugin.git
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by janpio** [comment]
`ionic state` is not present on CLI v3, CLI v2 is not supported any more. Are you using CLI v3?

If you are, please post your `ionic info`. Otherwise, please update.

**Comment by davidecheli** [comment]
Yes, I'm using ionic-cli 3.4.0.

`global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10`

There is any similar command on ionic-cli v3?

**Comment by janpio** [comment]
`ionic cordova prepare` does the same thing. See here: https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#removed-commands
