### ISSUE TITLE
when i installing ionic 3 cli i getting such kind errors idk why please help me out.

### ISSUE THREAD

**Issue by Vips120** [ionic-team/ionic-cli#2456]
![ionicerror](https://user-images.githubusercontent.com/15245230/27329301-caf7cd9a-55d2-11e7-85d7-dc166abe37b7.PNG)

**Comment by janpio** [comment]
Ionic CLI (via @ionic/app-scripts) is not ready for npm5 on Windows.
Use an older node with an older npm to fix this.

**Comment by Vips120** [comment]
ok i did nw its working ..!!!! ty

**Comment by dwieeb** [comment]
Seems to be an npm5 on Windows problem. This issue gets reported a lot.

**Comment by janpio** [comment]
Got reported while app-scripts wasn't using a node-sass version that was available for Windows. Fortunately @ionic/app-scripts got updated and now works just fine with node8/npm5.
