### ISSUE TITLE
Error when packaging for IOS

### ISSUE THREAD

**Issue by royibernthal** [ionic-team/ionic-cli#2457]
**ionic package info 1 --verbose**

> Task: title=package, name=package, summary=Use Ionic Package to build your app, <command>=build android, build ios, list, info, or download, [options]=, --release=(build <platform>) Mark this build as a release, --profile|-p <tag>=(build <platform>) Specify the Security Profile to use with this build, --noresources=(build <platform>) Do not generate icon and splash screen resources during this build, --destination|-d <path>=(download) Specify the destination directory to download your packaged app., module=./ionic/package, isProjectTask=true, run=function run(ionic, argv) {
>   var cmd;
> 
>   if (argv._.length < 2) {
>     cmd = 'list';
>   } else {
>     cmd = argv._[1];
>   }
> 
>   var dir = null;
>   var project = null;
>   var appId = null;
> 
>   try {
>     dir = process.cwd();
>     project = Project.load(dir);
>     appId = project.get('app_id');
> 
>     if (!appId) {
>       throw new Error('Missing Ionic App ID. Make sure to run "ionic upload" first or set ' +
>         'your app_id in the ionic.config.json file.');
>     }
>   } catch (ex) {
>     return fail(ex, 'package');
>   }
> 
>   switch (cmd) {
>   case 'build':
>     return packageBuild(ionic, argv, dir, project, appId);
>   case 'list':
>     return packageList(ionic, argv, dir, project, appId);
>   case 'info':
>     return packageInfo(ionic, argv, dir, project, appId);
>   case 'download':
>     return packageDownload(ionic, argv, dir, project, appId);
>   }
> 
>   return fail("Unknown subcommand '" + cmd + "'.", 'package');
> }
> Looking up Ionic root, cwd: D:\Projects\trt\client
> Ionic root directory:  D:\Projects\trt\client
> Package.json found scripts: clean=ionic-app-scripts clean, build=ionic-app-scripts build, ionic:build=ionic-app-scripts build, ionic:serve=ionic-app-scripts serve
> 
> Npm scripts: clean=ionic-app-scripts clean, build=ionic-app-scripts build, ionic:build=ionic-app-scripts build, ionic:serve=ionic-app-scripts serve
> Gulpfile found: false
> 
> Caught exception:
>  SyntaxError: Unexpected end of JSON input
>     at Object.parse (native)
>     at Request._callback (C:\Users\royib\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\package.js:117:27)
>     at Request.self.callback (C:\Users\royib\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\request\request.js:373:22)
>     at emitTwo (events.js:106:13)
>     at Request.emit (events.js:191:7)
>     at Request.<anonymous> (C:\Users\royib\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\request\request.js:1318:14)
>     at emitOne (events.js:101:20)
>     at Request.emit (events.js:188:7)
>     at IncomingMessage.<anonymous> (C:\Users\royib\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\request\request.js:1266:12)
>     at emitNone (events.js:91:20)

**ionic info**

> Your system information:
> 
>  ordova CLI: 7.0.1
> Ionic Framework Version: 3.1.1
> Ionic CLI Version: 2.2.3
> Ionic App Lib Version: 2.2.1
> Ionic App Scripts Version: 1.3.6
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Windows 10
> Node Version: v6.9.5
> Xcode version: Not installed

**Comment by janpio** [comment]
> Missing Ionic App ID. Make sure to run "ionic upload" first or set ' your app_id in the ionic.config.json file.

Did you? Is the app available on apps.ionic.io and uploaded at least once?
Is the app_id in ionic.config.json?

**Comment by royibernthal** [comment]
Yes to all, I don't think it threw that error it was just part of the code that appears because I used --verbose.

That's the actual exception:

> 
> Caught exception:
> SyntaxError: Unexpected end of JSON input
> at Object.parse (native)
> at Request._callback (C:\Users\royib\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\package.js:117:27)
> at Request.self.callback (C:\Users\royib\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\request\request.js:373:22)
> at emitTwo (events.js:106:13)
> at Request.emit (events.js:191:7)
> at Request. (C:\Users\royib\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\request\request.js:1318:14)
> at emitOne (events.js:101:20)
> at Request.emit (events.js:188:7)
> at IncomingMessage. (C:\Users\royib\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\request\request.js:1266:12)
> at emitNone (events.js:91:20)

I understand, next time I'll use the forum for things like that, I followed the note:

> Mind letting us know? https://github.com/driftyco/ionic-cli/issues

that appeared after the exception.

**Comment by janpio** [comment]
Yeah not wrong what you did, debugging is just hard here.

Could you please open a forum topic and post the URI here?
Include the full error message and make it readable, also include you `ionic info` output already.

**Comment by royibernthal** [comment]
Sure, here you go:
https://forum.ionicframework.com/t/error-when-packaging-for-ios/95173

**Comment by janpio** [comment]
Thanks. You can close this here.
