### ISSUE TITLE
CLI 3.4.0: Build process output is invisible

### ISSUE THREAD

**Issue by JaneDawson** [ionic-team/ionic-cli#2458]
**Description:**
Since upgrading to Ionic CLI 3.4.0 I have several invisible lines when running `ionic cordova run android` or `ionic cordova run android --prod`. Somehow, the build process output is invisible to me (everything up to `cordova run android`).

Everything works as expected when running `npm run ionic:build`, `npm run ionic:build --prod` or `cordova run android`

See picture: http://i.imgur.com/tUhg4aa.png

`ionic info` gives me:

global packages:

```
@ionic/cli-utils : 1.4.0
Cordova CLI      : 6.5.0
Ionic CLI        : 3.4.0
```

local packages:

```
@ionic/app-scripts              : 1.3.7
@ionic/cli-plugin-cordova       : 1.4.0
@ionic/cli-plugin-ionic-angular : 1.3.1
Cordova Platforms               : android 6.1.2
Ionic Framework                 : ionic-angular 3.4.2
```

System:

```
Node       : v6.11.0
OS         : Windows 10
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed
npm        : 3.10.10
```

**Comment by dwieeb** [comment]
This is a terminal color problem, then. It's strange because I can't think of anything different we're doing as far as colors go between the normal text and the text from app-scripts:

![image](https://user-images.githubusercontent.com/236501/28041823-73ac709a-6590-11e7-8d5c-b77f556787f5.png)

**Comment by JaneDawson** [comment]
It was a problem with my terminal (cmder). I found a workaround:
https://github.com/cmderdev/cmder/issues/1346
Hence, this issue can be closed. Thank you!
