### ISSUE TITLE
Differentiate dependencies and devDependencies in `ionic info`

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2459]
When people post their `ionic info`, "local packages" outputs app-scripts version, CLI plugins etc. It would be great if we would know if they are in dependencies or devDependencies of `package.json` to be able to recommend improvements to users.

**Comment by dwieeb** [comment]
We don't even look at their `package.json` for that output. A package is either installed locally or it's not. Why would that be useful? I'm curious

**Comment by janpio** [comment]
Because people tend to install packages in the "wrong" place because... I have no idea. Or in multiple places. People do all kinds of strange things - and the more you know the better.

**Comment by dwieeb** [comment]
True, but both deps and dev deps get installed into `node_modules`. We can ask them to show `package.json` if it is relevant.

**Comment by janpio** [comment]
To have an indication when it is in the wrong part of `package.json`. `app-scripts` in `dependencies` mostly which is just not necessary.

**Comment by janpio** [comment]
I deleted my first reply as it was unrelevant to the problem.
