### ISSUE TITLE
"Your plugins may be out of date."

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2460]
Right now every error during plugin command execution gives you an error like that:

> [WARN] Error occurred during command execution from a CLI plugin (`@ionic/cli-plugin-cordova`). Your plugins may be out of date.

Is this "Your plugins may be out of date." message useful? Doesn't the CLI check for updates anyway?

I see this all the time right now with `cordova` execution problem, be it because of missing dependencies like Android SDK or other build problems. Is this message helpful?

**Comment by santamaria7** [comment]
It's definitely not helpful. At least tell the user what plugin is out-of-date! I've been struggling with this during the build process and I am about to miss my deadline just because the errors are not very clear and I can't actually find out what's going on!

**Comment by janpio** [comment]
> At least tell the user what plugin is out-of-date!

That it actually does tell you - the error message includes the plugin name. But this is most probably not a plugin out of date problem, but just something totally unrelated in the plugin execution.

@santamaria7 Post on https://forum.ionicframework.com/ and we'll try to help.

**Comment by dwieeb** [comment]
The error was popping up because a lot of people had/have older plugins that don't work with newer versions of the CLI. The plugins basically have to be updated at the same time as the CLI right now to ensure nothing goes wrong, which is terrible. The CLI does check for updates, but only after an hour of not using the CLI. Not useful when someone is spending hours trying to fix the error.

**Comment by janpio** [comment]
`ionic fix` maybe?

**Comment by dwieeb** [comment]
Closing this. The requirement in 3.6 to use local CLI should be the biggest helper yet for weird CLI/plugin incompatibilities.

**Comment by Bubelbub** [comment]
Is it possible to ignore this error's? Or how to solve?
I not want the latest version because it's not compatible with all of my components 👎 

    [WARN] Error occurred during command execution from a CLI plugin
           (@ionic/cli-plugin-cordova). Your plugins may be out of date.

**Comment by dwieeb** [comment]
@Bubelbub How is it incompatible? Please elaborate so I can help you stay up to date.

**Comment by Bubelbub** [comment]
@dwieeb: The warning is not the error. There was an error with malformed TypeScript:
https://github.com/zyra/ionic2-super-tabs/issues/109

I'm using other version then I'm getting:
`TypeError: env.runcmd is not a function`

And with that problem I'm fighting currently 😄

**Comment by dwieeb** [comment]
@Bubelbub I think you're confused. When you update the CLI, you're not updating the framework version.

For the `env.runcmd` issue, please see https://github.com/ionic-team/ionic/issues/12561#issuecomment-320016615

**Comment by Sangrampatil4141** [comment]
I'm using other version then I'm getting:
TypeError: env.runcmd is not a function

And with that problem I'm fighting currently :smile:

**Comment by dwieeb** [comment]
@Sangrampatil4141 For the `env.runcmd` issue, please see https://github.com/ionic-team/ionic/issues/12561#issuecomment-320016615

**Comment by PaulHost** [comment]
fIxed this problam in unix-like-os:
```
sudo -i
npm install -g ionic@latest
```
if it is not updated automatically: 
```
npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
```

**Comment by dwieeb** [comment]
@PaulHost `@ionic/cli-plugin-cordova` and `@ionic/cli-plugin-ionic-angular` have been deprecated and are no longer loaded by the CLI. Do not install them. The CLI will warn you to uninstall them.
