### ISSUE TITLE
`ionic cordova requirements`

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2461]
Cordova offers this nice call `requirements` that outputs a list of the requirements met or not met for the currently installed platforms:

```
PS C:\Users\Jan\Documents\superAfter> cordova requirements

Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-25
Gradle: installed C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle

Requirements check results for ios:
Apple OS X: not installed
Cordova tooling for iOS requires Apple OS X
Error: Some of requirements check failed
```

I propose this should be offered by `ionic` as well so we can point people to it when they have problems building their apps because of missing SDK etc.

(I actually thought this was already implemented, but checking 3.3 and 3.4 both gave me a missing command error... Strange)

**Comment by dwieeb** [comment]
We kinda do enough of this now, I think. We get the Android SDK version and all the iOS info. If we do need additional information, such as gradle path/version, we can ask. I assume at that point we'd be deep diving some Cordova bug with the user anyway. Closing for now.

**Comment by janpio** [comment]
Disagree. This is mostly about people where the (Android) SDK is not correctly installed, PATH for them is messed up and similar. They then can't build their app with Cordova via Ionic.

It would be beneficial to be able to tell people "Please run `ionic cordova requirements` to check if everything is installed correctly. Fix stuff until it tells you everything is ok.". 

Right now telling people to run a `cordova` command directly is always a bit strange, compared to all the other `ionic cordova` commands, and requires additional explanation (and linking to Cordova docs etc).

This is just one more command of Cordova you could (and imo should) proxy through - no additional logic, just making sure it appears in the command list, docs and help files so people are more aware of it and use it as a normal command in their Ionic workflow.

**Comment by dwieeb** [comment]
Fair point.
