### ISSUE TITLE
More accurate error message in cli-plugin-gulp

### ISSUE THREAD

**Issue by notsyncing** [ionic-team/ionic-cli#2465]
When I ran `ionic serve` on an ionic-v1 project, I got a message complaining `gulpfile.js` not found, but it actually exists. After many unsuccessful tries, I added a line to `node_modules/@ionic/cli-plugin-gulp/index.js`:

```js
if (e.code !== 'MODULE_NOT_FOUND') {
     throw e;
}

console.dir(e); // ADD THIS

throw new cli_utils_1.FatalException(`Gulpfile not found: ${chalk.bold(cli_utils_1.prettyPath(gulpFilePath))}\n` +
                `You can set the ${chalk.bold('gulpFile')} attribute in ${chalk.bold(cli_utils_1.PROJECT_FILE)} for custom Gulpfile locations, otherwise the default Ionic Gulpfile can be downloaded from ${chalk.bold('https://github.com/ionic-team/ionic-app-base/blob/master/gulpfile.js')}\n\n` +
                `Or, if you no longer use gulp, you can remove the CLI Gulp Plugin:\n\n` +
                `    ${chalk.green(gulpPluginUninstallArgs.join(' '))}`);
```

then run `ionic serve` again, the console now prints out why it fails, and I finally solved the problem (lacking some gulp related packages). 

So I'm wondering if we could add some more detailed error outputs instead of simply printing `Gulpfile not found` for every unrelated error?

ionic-cli version 3.4.0

**Comment by janpio** [comment]
(See related discussion in thi forum thread: https://forum.ionicframework.com/t/error-gulpfile-not-found-gulpfile-js/94253)

**Comment by dwieeb** [comment]
_groan_ ... the `MODULE_NOT_FOUND` error is bubbling up. I had hoped it would only be thrown for the require statement above. You'll notice it throws a proper error if it's anything else.

I will fix the message.

Thanks!

**Comment by MarcioQuimbundo** [comment]
Solution:
npm update
npm remove gulp-sass
npm install gulp-sass --save-dev
