### ISSUE TITLE
ionic install throws error  "@ionic/cli-utils@1.4.0"

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2466]
_From @sruthakeerthikotla on June 22, 2017 11:25_

npm version : 5.0.3
node version : 8.1.2
cordova version : 7.0.1

On trying to execute ionic using the command `npm install -g ionic cordova`, an error is thrown as follows : 
```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! code E404
npm ERR! 404 Not Found: @ionic/cli-utils@1.4.0
```
I have tried installing with `sudo` as well but same error occurs and ionic does not install at all.

_Copied from original issue: ionic-team/ionic#12131_

**Comment by jgw96** [comment]
_From @janpio on June 22, 2017 11:46_

Wrong repo, this should be posted at the Ionic CLI one: https://github.com/ionic-team/ionic-cli

**Comment by janpio** [comment]
@sruthakeerthikotla That is strange. Are you behind a strange proxy, firewall, national cencorship?

**Comment by sruthakeerthikotla** [comment]
Nope. Nothing of that sort at all. I had ionic previously and wanted to uninstall and reinstall. Tried doing an uninstall and it failed. So I manually deleted the ionic folder from within the npm and tried to do an npm install and this is the error that keeps coming :/

P.S. I am using a mac.

**Comment by dwieeb** [comment]
Using a different registry?

```bash
npm set registry https://registry.npmjs.org/
```

This issue has been posted before. It's something with your npm configuration.
