### ISSUE TITLE
Error occurred while loading plugins. CLI functionality may be limited.Checking for CLI updates now...

### ISSUE THREAD

**Issue by sure2darling** [ionic-team/ionic-cli#2468]
**Description:**

[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[ERROR] No updates found after plugin error--please report this issue.

**Steps to Reproduce:**

Example repo: 

1.npm install -g ionic@3.4.0
2.ionic start myApp blanck
3.ionic serve

**Output:**

**My `ionic info`:**

已经是最新的版本了，功能受限，提示让更新ionic，

**Other Information:**

**Comment by dwieeb** [comment]
Use `--verbose` to show more. If you can, please use English.

**Comment by dmunicio** [comment]
I had the same problem behind a corporate proxy in Windows 7. If that is your case, try this:
npm config set proxy http://user:password@your.proxy:8080
set http_proxy=http://user:password@your.proxy:8080
set https_proxy=http://user:password@your.proxy:8080
npm install -g @ionic/cli-plugin-proxy
ionick start myApp whatever
