### ISSUE TITLE
Ionic deploy -username and -password not

### ISSUE THREAD

**Issue by obkdev** [ionic-team/ionic-cli#2469]
**Description:**
When running the command `ionic upload -email ***** -password ****` the account doesn't change, when I enter different account details.

I have previously uploaded without these flags, and been prompted for my email and password for the ionic.io service. I now don't seem to be able to upload to a different account. If I run the command above using the wrong email and password, it still uploads to the original account.

**Steps to Reproduce:**

1. `ionic upload`
2. enter account details when prompted
3. `ionic upload -email not@correct.com -password wrongpassword`

**Output:**
App is uploaded to the original account, not the account `not@correct.com`. It doesn't even identify that I have entered the password incorrectly.

**My `ionic info`:**

Your system information:

Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 1.0.0
OS:
Node Version: v6.10.3

**Comment by janpio** [comment]
I don't think `ionic upload` has `email` and `password` parameters. These exist on `ionic login` though.

**Comment by dwieeb** [comment]
@janpio Is correct. While those params may have existed in the old CLI, they've been taken out in favor of a single CLI session at a time.
