### ISSUE TITLE
ionic serve results in TypeError

### ISSUE THREAD

**Issue by mattalco** [ionic-team/ionic-cli#2470]
**Description:**

running `ionic serve --lab` results in an error

**Steps to Reproduce:**

in an app, run `ionic serve --lab`

**Output:**

```
C:\Users\malcorn\Documents\xmobile>ionic serve --lab
[INFO] Starting server: --lab --l --port=8100 --p=8100 --livereload-port=35729 --r=35729 --address=0.0.0.0 - Ctrl+C to
       cancel
[INFO] Development server running
       Local: http://localhost:8100

C:\Users\malcorn\Documents\xmobile\node_modules\@ionic\cli-plugin-ionic1\dist\serve\live-reload.js:19
    let contentStr = content.toString();
                            ^

TypeError: Cannot read property 'toString' of undefined
    at Object.injectLiveReloadScript (C:\Users\malcorn\Documents\xmobile\node_modules\@ionic\cli-plugin-ionic1\dist\serve\live-reload.js:19:29)
    at ReadFileContext.fs.readFile [as callback] (C:\Users\malcorn\Documents\xmobile\node_modules\@ionic\cli-plugin-ionic1\dist\serve\http-server.js:59:39)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)

C:\Users\malcorn\Documents\xmobile>ionic -v
3.4.0
```

**My `ionic info`:**

**Other Information:**

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Gulp CLI         : CLI version 3.9.1 Local version 3.9.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/cli-plugin-cordova : 1.4.0
    @ionic/cli-plugin-gulp    : 1.0.1
    @ionic/cli-plugin-ionic1  : 2.0.0
    Cordova Platforms         : android 6.1.2
    Ionic Framework           : unknown

System:

    Node       : v6.9.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by knowngate** [comment]
???
