### ISSUE TITLE
add info for non available generators

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/ionic-cli#2471]
**Description:**

If you want to generate for example a class or interface the CLI don't throw an error/warning

**Output:**

```bash
Daniels-iMac:gotWiki danielsogl$ ionic generate interface Age
[OK] Generated a interface named Age!
```

**Comment by clariontools** [comment]
+1 Just saw this today, I agree it should throw an error/warning. Is there any value in actually adding new options for generate to generate class and interface stubs in appropriate folders under src?

**Comment by danielsogl** [comment]
To generate interfaces etc. we have to add these options to the app-scripts and ionic-angular repo.
The CLI calls app-scripts and app-scripts calls the templates in the ionic-angular package.
