### ISSUE TITLE
ionic build command not getting executed

### ISSUE THREAD

**Issue by Anjaney26** [ionic-team/ionic-cli#2473]
**Description:**

Hello All. I am facing a problem while creating build for android/ios. Would you please tell me what is happening with ionic? This is my old project which is in ionic1, and now My system got updated.

**Output**

" You are not in a project directory."

**My `ionic info`:**

[WARN] You are not in an Ionic project directory. Project context may be
       missing.

global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10 

**Other Information:**

Cordova version:  7.0.1
npm Version: 3.10.10

**Comment by Sampath-Lokuge** [comment]
The error is clear no? `You are not in a project directory`.You need to move into your project directory before running any Ionic command.

**Comment by Anjaney26** [comment]
Hi Sampath, I am currently in my project root directory and then running ionic commands. Please if you have solution for this, Please share with me.

**Comment by dwieeb** [comment]
@Anjaney26 What command are you running?
