### ISSUE TITLE
ERR_OUT_OF_MEMORY on GET/POST from android device in production mode

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-cli#2478]
**Description:**
I don't know what the hell we have done, but from a few days we are not able to do a GET/POST from android devices in production mode.

If we do `ionic cordova run android` everything is fine but this naturally is not the same as run `ionic cordova run android --prod`, in this case the app is running not in the "browser" and in this case the GET/POST returns with this error:
`Failed to load resource: net::ERR_OUT_OF_MEMORY`

We also revert to old working versions, but it is not working anymore, some ideas?

Honestly no idea if the problem is coming from ionic-cli, @ionic/app-scripts or ionic-angular.
But the fact is, we reverted anything but it doesn't work anymore. Perhaps is is a problem with cordova?

We created a new project with ionic start, added the android platform and added  a simple http.get
```
this.http.get('http://192.168.8.1/blalba')
                    .subscribe((data) => {
                        console.log('data: ', data);
                    },
                    (error) => {
                        console.log('error: ', error);
                    });
```

and run it with, `ionic cordova run android --prod`. But there is still the same problem.

We googled and found nothing about it.

Did you notice also the exception?

**My `ionic info`:**
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.4.2-201706271925

System:

    Node       : v6.11.0
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.4 
```

**Comment by Sampath-Lokuge** [comment]
`map` is missing no?

this.http.get('http://192.168.8.1/blalba').map(res => res.json())
                    .subscribe((data) => {
                        console.log('data: ', data);
                    },
                    (error) => {
                        console.log('error: ', error);
                    });

**Comment by mburger81** [comment]
@Sampath-Lokuge this should not be the problem, on DESKTOP BROWSER and also on ANDROID devices with LIVERELOAD it does work.

It does only not work on android devices with in production build "--prod"

**Comment by mburger81** [comment]
After rebooting the Android tablet, the error disappeared and the app works again!!

So first of all, it was not a problem of angular, but a problem of Android Device / Cordova.

**Does anyone know how can this happen, and how we can this prevent?**
