### ISSUE TITLE
`ionic start` broken for starters with patch.package.json on npm5 systems 

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2485]
Right now `ionic start myionic super` is broken on systems with npm5. `patch.package.json` gets merged into `package.json` on install, but the `package-lock.json` stays untouched.

See https://github.com/ionic-team/ionic-starter-super/issues/118 for example investigation.

Is there a system to merge the lock files together?
If so, how to use it?
If not, is this actually possible and should this be implemented?

**Comment by vswarte** [comment]
As a temp fix, running `$ npm update` will update the lock file and seems to leave the newly created project in a working state.

**Comment by dwieeb** [comment]
Yeah, honestly I really dislike the `patch.package.json` method. It's been on my todo list to do this better, but it's already caused a few problems.

**Comment by dwieeb** [comment]
This is fixed with the new starters as of CLI 3.17.0.
