### ISSUE TITLE
`ionic` commands unnecessarily manipulate default files

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2486]
There are multiple `ionic` commands that mess with the default "config" files `cordova.xml` and `package.json` and by that create unnecessary changes that have to be checked in with Git. Here are some examples for a project created with the `blank` template:

1. `ionic cordova platform add android` removes empty lines + comments and changes the ordering of `<icon>` attributes in `config.xml`. In `package.json` it changes the indendation from 2 spaces to 4 spaces:
https://github.com/janpio/ionic-default-files-messing/commit/3db056994ff89256d6b94e03c8e8074df4a53e22

2. `ionic cordova resources` replaces the existing images with the exact same images - same file size, pixel identical. Looking at the binary of the images it seems only some dates in metadata (?) at the end of the file is different. Should this be in the files at all?
https://github.com/janpio/ionic-default-files-messing/commit/f58c2de710ba271d7cd9234335ce11fa739d1c5f

3. `ionic cordova run android` then completely rewrite `config.xml` again. It changed `"` to `'` in the `<?xml>` tag, and removed `standalone="yes"` completely from it. Then it added spaces in front of the closing `/` in all the tags, moved the density attribute of `<icon>` for android to the front of the tag, and completely resorted the `<plugin>`s in the bottom.
https://github.com/janpio/ionic-default-files-messing/commit/c440bec7e46dd28882bbdc5bc2e7288bffdd85bf

Of course you can now say "well, only cosmetic changes, no functionality change, doesn't matter" and you would be technically correct of course. But for beginners (and old timers getting confused easily...) this is a real and unnecessary burden.

(Could someone please execute the same commands on Mac OS or Linux to see if this is reproducible? I only tested this on Windows 10 for now)

Can the CLI be improved so this doesn't happen?
Can or should the default `config.xml` and `package.json` be adapted to their "intended" format?

**Comment by pjorquera** [comment]
@janpio I can confirm that the same happens on macOS with the following configuration:

```
global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Ionic CLI               : 3.4.0

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 5.0.4
```

**Comment by dwieeb** [comment]
Cordova is _mostly_ responsible for 1 and 3. I think `ionic cordova resources` does some checking to see if it's really necessary to redo all the images, but I think the first time it generates new images.

This is a known issue, but more important things to tackle first.

**Comment by janpio** [comment]
If Cordova is the culprit, wouldn't the best quick fix be to change the starters and app-base? Say so and it will be done (= PRd).

**Comment by dwieeb** [comment]
No solution will be perfect. We are using a different xml library, which causes some issues. It's just not a good situation right now.

There is an existing issue: https://github.com/ionic-team/ionic-cli/issues/2332

**Comment by dwieeb** [comment]
@janpio While working on the resources command for the xml fixes, I noticed the command is still replacing the images pixel-for-pixel every time it runs. How annoying. I think I can take a look at this tomorrow.
