### ISSUE TITLE
How To Stop LiveReload on ionic Serve

### ISSUE THREAD

**Issue by moda20** [ionic-team/ionic-cli#2488]
**Description:**
So i am trying to stop my ionic2 app from reloading each time i switch from IDE to browser, or actually to anything even terminal. i tried all the options on the docs even the one supposed to stop this livereload but it failed and nothing happened.

So is there anyway to force this livereload to stop ?

**Comment by janpio** [comment]
What do you mean by "each time i switch from IDE to browser"? It is only supposed to reload (after rebuilding) when you change something in your project and save the file. What exactly is happening for you?

Also, what options did you try that didn't work?

**Comment by moda20** [comment]
What i meant is that every time write something in the code but do not save then i just switch windows it does the reload. The option is : --nolivereload, -d

**Comment by moda20** [comment]
I think i did Find out the problem. Thinking about it now, my IDE which is Webstorm has the option " save on frame deactivation " checked automatically. Turning it off fixed my problem with the reload. I feel embarrassed now thinking it was a problem with ionic CLI. 
Thank You.

**Comment by janpio** [comment]
Nah, don't be - we both learned something today ;)
You can close this issue now though.

**Comment by kishandonepudi** [comment]
**--nolivereload** is now **--no-livereload**

**Comment by mrunwal** [comment]
This is not working. 
so everytime I hit save button browser get reloaded. 
is it changed with different property ?

**Comment by mrsamyway** [comment]
@mrunwal you can use "ng serve --live-reload=false" instead of "ionic serve"
