### ISSUE TITLE
Native: tried accessing the GoogleMaps plugin but Cordova is not available. Make sure to include cordova.js 

### ISSUE THREAD

**Issue by webmobiles** [ionic-team/ionic-cli#2490]
**Description:**
Have no google maps showing, in chrome error is:
util.js:63 Native: tried accessing the GoogleMaps plugin but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

**Steps to Reproduce:**
1. ionic start myionic super
2. change en /src/app/app.component.ts

export class MyApp {
  //rootPage = FirstRunPage;
  rootPage = MapPage;

3. ionic serve,  or,  ionic cordova run android

**Output:**
blank page

**My `ionic info`:**
 

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.2
    OS         : OS X El Capitan
    Xcode      : Xcode 8.0 Build version 8A218a 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 5.0.3

**Comment by jayeshanandani** [comment]
@webmobiles : which plugin are you using? Can you please post a link to that?

**Comment by janpio** [comment]
Please post at the forum at https://forum.ionicframework.com/. This is not a question for a Github issue, but a discussion over there.

**Comment by Sampath-Lokuge** [comment]
The error is very clear no `run in a device/simulator`?

**Comment by webmobiles** [comment]
sorry, was my mistake, browser is not able to work with google maps; anyway i've updated all packages and it's working. Next post like that i'll use the forum. Thanks

**Comment by franzisk** [comment]
What if I want the app running maps on a browser and on a device?

I use to test "almost" everything using Developer Tools on Chrome.

**Comment by jayeshanandani** [comment]
@franzisk : It is not possible at this time with Cordova plugin as the wrapper that is present in Cordova doesn't allow google maps to be rendered on the browser.

**Comment by Davidcorral94** [comment]
@jayeshanandani any news about using cordova plugins for Ionic 3+ in browser?

**Comment by jayeshanandani** [comment]
@Davidcorral94 : you can use google maps in browser via js [plugin](https://www.npmjs.com/package/@types/googlemaps).  This will use Javscript Google Map SDK.

**Comment by hhidalgo90** [comment]
try : ionic cordova prepare android
