### ISSUE TITLE
用命令ionic cordova build browser --prod的时候，某些安卓手机运行起来是白屏，而用ionic cordova build browser打包的手机浏览网页运行起来就不是白屏？求解答

### ISSUE THREAD

**Issue by xiaoman627** [ionic-team/ionic-cli#2492]
**Description:**

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

**Other Information:**

**Comment by danielsogl** [comment]
@xiaoman627 Please fill out the Issue template.

**Comment by xiaoman627** [comment]
When using the ionic cordova build browser - prod, some android phones run white, and the ionic cordova build browser's mobile browser is not a white screen.？？

**Comment by xiaoman627** [comment]
@danielsogl danielsogl When using the ionic cordova build browser - prod, some android phones run white, and the ionic cordova build browser's mobile browser is not a white screen.？

**Comment by pixelsf** [comment]
config.xml
`<preference name="SplashScreenDelay" value="10000"/>`
`<preference name="loadUrlTimeoutValue" value="700000"/>`

**Comment by janpio** [comment]
Please post at the forum at https://forum.ionicframework.com/. This is not a question for a Github issue, but a discussion over there.
