### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by azakusilo** [ionic-team/ionic-cli#2494]
Hello I got lastest ionic CLI and ionic installed.
But when I try to login, it is shows me a Error

```
 Try to exec command <b>ionic login --email a******@mail.ru --password **** --no-interactive</b>
RS Mobile:
 Ionic Log In status [WARN] You are already logged in as a****@mail.ru!
[WARN] You are in non-interactive mode. Use --interactive to re-enable prompts.
[ERROR] email must not be empty.
[ERROR] password must not be empty.
Use the --help flag for more details.
```

**Comment by dwieeb** [comment]
@azakusilo Which guide/tutorial/docs are you using to use `--email` and `--password`? The email and password are just positional arguments, not options.

Try `ionic login a******@mail.ru **** --no-interactive`

**Comment by azakusilo** [comment]
That was in previous docs for version 3.4.3 of ionic.

**Comment by dwieeb** [comment]
Previous docs? Can you please send a link?

**Comment by azakusilo** [comment]
It was here - http://ionicframework.com/docs/cli/login/. Now it is updated.
