### ISSUE TITLE
`ionic serve` taking extremely long to start

### ISSUE THREAD

**Issue by jacquesdev** [ionic-team/ionic-cli#2495]
#### Short description of the problem:
I have an ionic 1 project, using ionic cli 3.4.0. When I run `ionic serve`, it sometimes seems like nothing is happening for about 4-5 minutes. When I run it with the --verbose flag, I can see what is happening. It does attempt to start the server, but sometimes it checks for updates and for some reason it takes really long while these checks are happening.

```
mac-mini:mobile jacques$ ionic serve -b --verbose
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for global @ionic/cli-plugin-proxy
[DEBUG] Detected ./gulpfile.js in project directory
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-gulp
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic1
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] Getting plugin info for ionic
[DEBUG] Getting plugin info for @ionic/cli-plugin-cordova
[DEBUG] Getting plugin info for @ionic/cli-plugin-gulp
[DEBUG] Getting plugin info for @ionic/cli-plugin-ionic1
[DEBUG] Getting plugin info for @ionic/cli-plugin-proxy
[DEBUG] Checking for latest plugin version of ionic@latest.
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-cordova@latest.
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-gulp@latest.
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-ionic1@latest.
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-proxy@latest.
[DEBUG] Latest version of ionic@latest is 3.4.0.
[DEBUG] Latest version of @ionic/cli-plugin-proxy@latest is 1.3.1.
[DEBUG] Latest version of @ionic/cli-plugin-ionic1@latest is 2.0.0.
[DEBUG] Latest version of @ionic/cli-plugin-gulp@latest is 1.0.1.
[DEBUG] Latest version of @ionic/cli-plugin-cordova@latest is 1.4.0. 
```

#### What behavior are you expecting?
I expect that ionic serve should pretty much just run immediately and not wait to check for the latest versions, because in some cases this takes incredibly long. Happy to see an info message if one of the scripts is out of date, but it should definitely not hang the entire process for me to run up a server. Ideally a flag should be made to skip these checks if possible, because I really don't want ionic serve to take 5 minutes to run.

**Which @ionic/app-scripts version are you using?**
Running ionic info displays:

global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Cordova CLI             : 7.0.1 
    Gulp CLI                : CLI version 3.9.1 Local version 3.9.1
    Ionic CLI               : 3.4.0

local packages:

    @ionic/cli-plugin-cordova : 1.4.0
    @ionic/cli-plugin-gulp    : 1.0.1
    @ionic/cli-plugin-ionic1  : 2.0.0
    Cordova Platforms         : android 6.2.3 ios 4.4.0
    Ionic Framework           : unknown

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : not installed
    npm        : 3.10.10 

Any help is appreciated.

**Comment by janpio** [comment]
You mentioned this only happens sometimes. What is the output of `--verbose` when it is not slow?

**Comment by dwieeb** [comment]
@jacquesdev I believe the new daemon option in CLI 3.6 should speed this up for you. Please open a new issue if the speed is still not desirable.

**Comment by jacquesdev** [comment]
Thank you!
