### ISSUE TITLE
Rename pages

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2496]
Ionic CLI can already generate pages. Why not also offer renaming them? 

Would be pretty useful for newbies that use e.g. the tab template and start working in home.ts, contact.ts etc. and then later want to rename their page to something useful.

**Comment by deniprogram** [comment]
+1

**Comment by adailsonfilho** [comment]
+50

**Comment by gmaggess** [comment]
+1

**Comment by donJusto** [comment]
I'm aggree with you

**Comment by dwieeb** [comment]
Merging this into the revamp issue: https://github.com/ionic-team/ionic-cli/issues/2407
