### ISSUE TITLE
打包特别快，进入APP特别慢，已经使用了--prod

### ISSUE THREAD

**Issue by wardenlzr** [ionic-team/ionic-cli#2497]
Packaging is fast,Special slowly into the APP
I have used --prod
How can I solve?

ionic info

global packages:

@ionic/cli-utils : 1.4.0
Ionic CLI        : 3.4.0
local packages:

@ionic/app-scripts              : 1.3.0
@ionic/cli-plugin-ionic-angular : 1.3.1
Ionic Framework                 : ionic-angular 3.0.1
System:

Node       : v7.9.0
OS         : Windows 7
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed
npm        : 4.2.0

**Comment by janpio** [comment]
Please post at the forum at https://forum.ionicframework.com/. This is not a question for a Github issue, but a discussion over there.
