### ISSUE TITLE
Default Ionic template's structure is bad for large projects

### ISSUE THREAD

**Issue by sinedied** [ionic-team/ionic-cli#2501]
It's not really a new topic as I've seen a few other issues on the matter here and there, but I would like to open a real discussion on this: the starter projects generated by the Ionic CLI encourages **bad practices**.

- First and foremost, all Angular apps should follow the [Angular Style Guide](https://angular.io/guide/styleguide). Ionic apps are based on Angular, and there is no good reasons to not follow the best practices and app structure used everywhere else.

- Not using a *folder-by-feature* organization hurts scalability and modularity. Even worst, the whole new *pages* concept from Ionic 3 prevents us from doing this properly! It's not new, and has really proven to be way more effective than *folder-by-type* organization.

- Due to Ionic's specific oddities, it's hard to share code and/or structure an app designed for both mobile *and* web with the same code.

- No unit tests by default, seriously? We're in 2017 guys...  

And a bonus question: why not using [angular-cli](https://github.com/angular/angular-cli) under the hood for the build tools? It works better than your *yet-another-build-workflow*, and would simplify moving between web and mobile projects.

Mobile web apps - hybrid or not - are not specific cases of web apps, they ARE web apps and should be considered as such, especially seeing how you promote PWA. Good web apps in 2017 are fully unit and end-to-end tested, scalable and built for speed, which is not what your tools promotes.

Don't get me wrong, I *love* Ionic since I've started using the first v1 beta, but I'm really disappointed with the direction it's taking in.

Any opinion on this is welcome.

**Comment by janpio** [comment]
I don't disagree in principle, but you make it a bit easy:

> Even worst, the whole new pages concept from Ionic 3 prevents us from doing this properly!

Pages were introduced with Ionic 3?

> No unit tests by default, seriously? We're in 2017 guys...

As Ionic is OSS the only answer can be: Feel free to submit PRs to the repos.

> why not using angular-cli under the hood for the build tools?

Probably because angular-cli didn't exist when Ionic v2 was started?

More serious: 
Can you offer a starter repo with the structure and syntax you would suggest?

**Comment by sinedied** [comment]
@janpio 
> Pages were introduced with Ionic 3?
I was referring to the `@ionicPages` annotation

> As Ionic is OSS the only answer can be: Feel free to submit PRs to the repos.
> Probably because angular-cli didn't exist when Ionic v2 was started.
> Can you offer a starter repo with the structure and syntax you would suggest?
And I'm working on it, to make it part of https://github.com/ngx-rocket/generator-ngx-rocket
I'm struggling to make Ionic fit a more "standard" Angular structure, especially due to the Ionic navigation concept, but it will sort out eventually.

What I did not suspected at first was that some Ionic concepts (`@ionicPages` again) seems to heavily rely on `ionic-cli` "magic", which is currently lacking documentation (if there's some info I'll gladly take it!). This makes it very hard to fit Ionic in an `angular-cli` project which is my goal, and the Ionic team does not seem to be supportive of this approach ATM.

**Comment by janpio** [comment]
If there is magic, you will probably find it in @ionic/app-scripts.

**Comment by danbucholtz** [comment]
@sinedied,

Thank you for the feedback. At this time we don't have any plans to change our project structure. If we continue to hear more of this feedback from the community, we will adjust as needed. As far as unit testing goes, we would like to have it, believe me, but we're strapped for time. We're open to a well-tested PR. If you'd like to help with that, I'm definitely open to it and will help you along the way. I'm `danb` in the ionic slack if you'd like to send me a message about how to get started.

As far as integrating with the CLI, in the future we may do this. I will stress that we're Ionic, not Angular, though. When we built @ionic/app-scripts and the Ionic CLI, the Angular CLI did not exist or was not ready for production. Angular team have a much larger team than us - so in some places they may have pulled ahead of us from a CLI perspective. Behind the scenes, they are revamping all of their tooling right now. When they ship the new Angular DevKit and it's better/faster/more capable than what we have, we'll move over to it when it's the highest priority item for our team.

Thanks,
Dan

**Comment by sinedied** [comment]
@danbucholtz Thanks for your answer, at least it's reassuring knowing that you're not closing the door to some changes.

I'm still trying to pursue a different approach for now with fixing the points I mentioned above and using `angular-cli` instead of Ionic CLI. So far, only `@IonicPages` custom processing is a blocking issue, but I have gone without it and tied Ionic navigation to `@angular/router`, so far it works well and allows lazy loading modules the Angular router way.

If you ever start switching to using Angular build tools I'll be glad to help in the process!

**Comment by danbucholtz** [comment]
@sinedied,

There's no need. You can import the `IonicModule` into Angular CLI apps.

Thanks,
Dan
