### ISSUE TITLE
Icons rendering incorrectly after upgrading to CLI V3

### ISSUE THREAD

**Issue by mos-ie** [ionic-team/ionic-cli#2502]
**Description:**

First time posting here, so apologies if it's the wrong place etc.
After installing Ionic and required dependencies on a new machine, icons are being rendered incorrectly. The project is Ionic v1 and Cordova/Ionic/Gulp CLIs are near to latest versions:
    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Gulp CLI         : CLI version 3.9.1 Local version 3.9.1
    Ionic CLI        : 3.4.0

Example of what's happening; if I run `ionic serve`  icons are rendered correctly in the browser:
![image](https://user-images.githubusercontent.com/2778940/27975026-6c483102-6358-11e7-9bb8-4f0ae5323097.png)

However, when I run `cordova run android --device` the same icons as above are rendered like this on my phone:
![image](https://user-images.githubusercontent.com/2778940/27975221-414635d4-6359-11e7-99da-45762fb42585.png)

Update: after doing some more digging, it seems that the culprit icons were manually added to the  fontello.css file. I also added new icon resources and these render incorrectly too. So, I'm thinking it's either something to do with different versions of the CLI behaving differently?

**Comment by janpio** [comment]
This sounds more like a problem you should post at https://forum.ionicframework.com/ so we can debug it together.
