### ISSUE TITLE
`ionic link` parses App IDs as scientific notation numbers

### ISSUE THREAD

**Issue by alansfyeung** [ionic-team/ionic-cli#2506]
**Description:**
When using `ionic link`, if you have an unfortunate Ionic App ID, it gets parsed as if it were in scientific notation. Subsequently the App ID gets represented as Infinity.
For example: `8655e445` is parsed as "8655 with 455 zeros"

**Steps to Reproduce:**
`ionic link 8655e445`
`ionic link '8655e445'`

Example repo: N/A

**Output:**
```
PS D:\OPICA Projects\opica-app> ionic link '8655e445' --verbose
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for global @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
? App ID 8655e445 already exists in project config. Would you like to link a different app? Yes
[DEBUG] !!! ERROR ENCOUNTERED !!!
✖ Looking up app Infinity - failed!
[ERROR] A token does not exist for your account on app Infinity.
```

**My `ionic info`:**
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.1.4
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 2.3.0

System:

    Node       : v7.2.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3
```

**Other Information:**

**Comment by dwieeb** [comment]
I'm sorry, we don't support the app ID: `86550000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`.

Please choose another app ID to work with our system.

**Comment by dwieeb** [comment]
I'm just kidding--this is hilarious. I'll be sure to fix this for you with the next release. 😂 

My new favorite issue.
