### ISSUE TITLE
module.ts file missing with 4.0.0

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-cli#2511]
ionic g page name

-->
`C:\Users\Daniel\Desktop\Alles\Projekte\Contacts\contacts-app\src\pages\search-overview\search-overview.ts
            has a @IonicPage decorator, but it does not have a corresponding "NgModule" at
            C:\Users\Daniel\Desktop\Alles\Projekte\Contacts\contacts-app\src\pages\search-overview\search-overview.module.ts`

**Comment by saimon24** [comment]
Yes I can confirm this, latest version is not creating a module file for pages anymore.

**Comment by mhartington** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1105
