### ISSUE TITLE
Ionic CLI @latest BREAKS every project

### ISSUE THREAD

**Issue by adadgio** [ionic-team/ionic-cli#2516]
**Description:**
Followed the lastest CLI update instructions from the command line (the CLI poped them up).

`ionic serve` give Error: Cannot find module 'os-name' (or 'request', or 'fs-extra' etc...).

Every project is borken even after doing a node_modules delete and npm reinstall.

NPM: 5.0.3
Ionic --version = 3.5.0
Node JS: 8.1.0

**Steps to Reproduce:**
Just answser `Y` to CLI update instructions to break everything.

**Comment by CaptainMM** [comment]
What else can I say except, balls....

**Comment by dwieeb** [comment]
The cli updates are nothing special, just npm installs. `node_modules` and npm are super finicky these days.

Do what @CaptainMM said (check here for more details https://github.com/ionic-team/ionic-cli/issues/2512#issuecomment-314815081).

**Comment by adadgio** [comment]
Downgrading didn't work but reinstalling Node and NPM to stable version, removing ionic and cordova worked. Super annoying but managed to make it work...

**Comment by mburger81** [comment]
Updating npm to 5.3.0 resolves the issue out of the box! :+1:
