### ISSUE TITLE
Desktop Support For Components : Feature Request

### ISSUE THREAD

**Issue by saniyusuf** [ionic-team/ionic-cli#2518]
Firstly thanks, @brandyscarney and @adamdbradley for your great work in desktop support. However, we have soo many components that are not desktop ready. The perfect example is the DatePicker Plugin. It's awesome on mobile but for desktop, it should be similar to the NG-Material2 one where it behaves like a tooltip. 

There are other components too that require this. But I have spoken to a couple of people and the date picker is the one that has people mixing Material or Bootstrap with Ionic just for one component

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic#12336
