### ISSUE TITLE
generators: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by CristianG540** [ionic-team/ionic-cli#2519]
![image](https://user-images.githubusercontent.com/1929796/28137215-1792184a-6712-11e7-8339-8a595f481e92.png)

**Comment by tscislo** [comment]
Same here

**Comment by dwieeb** [comment]
@CristianG540 @tscislo Fill out the issue template, please. 

Also, which starter did you use?

**Comment by CristianG540** [comment]
@dwieeb sorry i don't know what do you mean by wich starter i use , i'm too new, but look:

**Description:**
After upgrading to ionic-cli 3.5.0 i'm having problems generating tabs using the CLI, i try to generate some tabs but the CLI throw this error "TypeError: Cannot read property 'replace' of undefined"

**Steps to Reproduce:**
![image](https://user-images.githubusercontent.com/1929796/28140334-8ddc460a-671d-11e7-88ce-09bec4d92d58.png)

**My `ionic info`:**

global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by dwieeb** [comment]
@CristianG540 Can you run the command with `--verbose`? It will show the stack trace.

For the starter, I am just asking which template you used with `ionic start`? Was it `tabs`, `blank`, or `super`?

**Comment by CristianG540** [comment]
@dwieeb ok sorry look, i'm using ionic start with tabs just like in the img that i post above.

![image](https://user-images.githubusercontent.com/1929796/28140959-23ac6474-6720-11e7-833c-a4549af84a66.png)

**Comment by dwieeb** [comment]
@CristianG540 That's `ionic g`, not `ionic start`. 

Does this file exist in your app: `src/app/app.module.ts`?

**Comment by CristianG540** [comment]
yep i know, i only highlight the command that i use with verbose, i start the project with the tabs template, and yes i have that file in my app look: 
![image](https://user-images.githubusercontent.com/1929796/28141578-cacdea78-6722-11e7-8998-8d97eb4862ca.png)

**Comment by havo07** [comment]
you can intent with 

ionic generate tabs

**Comment by dwieeb** [comment]
@CristianG540 Odd. Do you mind if you paste the contents of `app.module.ts`? There's something that the CLI doesn't like about that file

**Comment by CristianG540** [comment]
@dwieeb of course, i'm going to put all the steps and the contents of `app.module.ts`:

- ![image](https://user-images.githubusercontent.com/1929796/28168110-a6fadc56-67a3-11e7-90e6-3f630a629c4c.png)
- ![image](https://user-images.githubusercontent.com/1929796/28168301-3efe8106-67a4-11e7-993c-35437d5a7ab8.png)
- 
```
import { NgModule, ErrorHandler } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';

import { AboutPage } from '../pages/about/about';
import { ContactPage } from '../pages/contact/contact';
import { HomePage } from '../pages/home/home';
import { TabsPage } from '../pages/tabs/tabs';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {} 



```

**Comment by dwieeb** [comment]
Hi @CristianG540, I think we're on to something. I believe there is a bug.

**Comment by mhartington** [comment]
Soo I have a PR in place to fix this in app-scripts. This was an oversight on my part, sorry 😄

**Comment by iam3fun** [comment]
still persist.
executed steps:

- npx create-nx-workspace simpleWorkspace
- Empty project
- ng add @nrwl/angular

########..........
Installed packages for tooling via npm.
Cannot read property 'replace' of undefined

**Comment by mhartington** [comment]
@iam3fun your commands have no references to ionic, not sure if it is related to this issue. This issue is over 2 years old l
