### ISSUE TITLE
ionic resources error

### ISSUE THREAD

**Issue by jasonz1987** [ionic-team/ionic-cli#2520]
```
ionic cordova resources --splash --verbose
```

[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for global @ionic/cli-plugin-proxy
[DEBUG] Detected ./gulpfile.js in project directory
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-gulp
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic1
[DEBUG] resourceJsonStructure=3
[DEBUG] platformDirContents=.DS_Store,android,ios,platforms.json
[DEBUG] buildPlatforms=android,ios
[DEBUG] getProjectPlatforms completed - length=2
[DEBUG] imgResources=24
[DEBUG] createImgDestinationDirectories completed - length=2
[DEBUG] getSourceImages completed - 1
✔ Collecting resource configuration and source images - done!
[DEBUG] uploadSourceImages completed - responses=[
        {}
        ]
✔ Uploading source images to prepare for transformations - done!
⠧ Generating platform resources: 2 / 24 complete 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:355:17)

```
ionic info
```

[ERROR] Error with /Users/tuo3/git/drip-ionic/www/lib/ionic/version.json file:
        FILE_NOT_FOUND

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Gulp CLI         : CLI version 3.9.0 Local version 3.9.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/cli-plugin-cordova : 1.4.1
    @ionic/cli-plugin-gulp    : 1.0.2
    @ionic/cli-plugin-ionic1  : 2.0.1
    Cordova Platforms         : android 6.2.3 ios 4.4.0
    Ionic Framework           : unknown

System:

    Node       : v7.3.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 4.1.1 
    npm        : 4.0.5

**Comment by dwieeb** [comment]
It's odd that your source image response is just _blank_: 

```
[DEBUG] uploadSourceImages completed - responses=[
  {}
]
```

Does this happen consecutively? Maybe it was just a server blip. Can you try again?

**Comment by jasonz1987** [comment]
@dwieeb it's be succesd when i try run it today,so i may be sever problem. thanks very much.
