### ISSUE TITLE
Ionic metadata upload error in JSON

### ISSUE THREAD

**Issue by jgermanis** [ionic-team/ionic-cli#2522]
**Description:**
Ionic upload when adding metadata fails with:
 SyntaxError: Unexpected token ' in JSON at position 0

**Steps to Reproduce:**
IF use exact command as in documentation it has the error:
ionic upload --deploy=production --note="add menu entry" --metadata='{"custom_data":true}'

Example repo: 

**Output:**

SyntaxError: Unexpected token ' in JSON at position 0

**My `ionic info`:**
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.0.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.8

**Other Information:**

**Comment by dwieeb** [comment]
The syntax in the example is bash syntax. Single quotes aren't allowed in Windows command prompt, so you'd have to do:
```
ionic upload --deploy=production --note="add menu entry" --metadata="{\"custom_data\":true}"
```

Thanks for bringing this to my attention, I'll update the example so it's platform agnostic.
