### ISSUE TITLE
Ionic generate page not create module inside page folder

### ISSUE THREAD

**Issue by cmtp** [ionic-team/ionic-cli#2523]
**Description:**
When I installed ionic-cli v3.5.0 and try to create a new page like 'Home' I did the command
```
ionic generate home
```
And generate the folder home with only 3 files: home.ts, home.scss, and home.html.
The home.module.ts is not created.

**Output:**
ionic g page home --verbose
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[OK] Generated a page named home!

**My `ionic info`:**

global packages:

    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-utils        : 1.5.0
    Ionic CLI               : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0

**Comment by CristianG540** [comment]
@cmtp look this 

- [https://github.com/ionic-team/ionic-app-scripts/issues/1105](url)

**Comment by cmtp** [comment]
I read the issue. Thanks!
