### ISSUE TITLE
"Ionic g page xx" command can not generate "xx.module.ts" files

### ISSUE THREAD

**Issue by qifanrui** [ionic-team/ionic-cli#2525]
**Description:**

I want the "ionic g page xx" command to generate the "xx.module.ts" file, but it will not be generated after I upgrade to this version.

**My `ionic info`:**

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v6.9.5
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 3.10.10

**Comment by CristianG540** [comment]
@qifanrui look this: [https://github.com/ionic-team/ionic-app-scripts/issues/1105](url)

**Comment by dwieeb** [comment]
@CristianG540 Your link is broken. All you need to do in Github is paste the URL: https://github.com/ionic-team/ionic-app-scripts/issues/1105

@qifanrui Thanks, this is a known bug. I will be closing this issue as a duplicate
