### ISSUE TITLE
ionic cordova prepare ios --release does not pass '--release' flag

### ISSUE THREAD

**Issue by jasonwinshell-br** [ionic-team/ionic-cli#2529]
**Description:**
--release, --debug or other command line flags are not being passed onto hook scripts when invoked as 'ionic cordova prepare'

**Steps to Reproduce:**
Assume you have a hook that reads the command line arguments 
Example repo: 

1. ionic cordova prepare ios --release

results in the following command being passed to hook scripts:

"cliCommand=/usr/local/Cellar/node/7.1.0/bin/node /usr/local/bin/cordova prepare ios"

   --release is missing

2. cordova prepare ios --release

results in the following command being passed to hook scripts:

"cliCommand=/usr/local/Cellar/node/7.1.0/bin/node /usr/local/bin/cordova prepare ios --release"

In short, extra flags are not passed from 'ionic cordova'

**My `ionic info`:**

global packages:

    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-utils        : 1.5.0
    Cordova CLI             : 7.0.1 
    Gulp CLI                : not installed globally
    Ionic CLI               : 3.5.0

local packages:

    @ionic/cli-plugin-cordova : 1.4.1
    @ionic/cli-plugin-gulp    : 1.0.2
    @ionic/cli-plugin-ionic1  : 2.0.1
    Cordova Platforms         : android 6.0.0 ios 4.4.0
    Ionic Framework           : ionic1 1.3.3

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
    npm        : 4.1.1 

**Other Information:**

**Comment by dwieeb** [comment]
Hi @jasonwinshell-br 

This has been requested before. I'm combining these issues into this one: https://github.com/ionic-team/ionic-cli/issues/2594. Please let me know if you have other use cases and needs.

Thanks!
