### ISSUE TITLE
Could not determine project type (project config: ..\ionic.config.json)

### ISSUE THREAD

**Issue by avaiskhatri** [ionic-team/ionic-cli#2531]
npm install -g cordova
npm install -g ionic

Output:
`-- ionic@3.5.0
  +-- @ionic/cli-utils@1.5.0
  | `-- inquirer@3.2.0
  |   `-- external-editor@2.0.4
  |     `-- jschardet@1.5.0
  `-- chalk@2.0.1
    `-- ansi-styles@3.1.0
      `-- color-convert@1.9.0
        `-- color-name@1.1.3

ionic info
 Looks like a fresh checkout! No ./node_modules directory found. Would you lik
e to install project dependencies? (Y/n) Y
> npm install
Running command - done!
[ERROR] Could not determine project type (project config: ..\ionic.config.json).

        For Ionic Angular projects, make sure 'ionic-angular' exists in the
        dependencies attribute of package.json.
        For Ionic 1 projects, make sure 'ionic' exists in the devDependencies
        attribute of bower.json.

        Alternatively, set type attribute in ionic.config.json to one of:
        'ionic-angular', 'ionic1'

**Comment by dwieeb** [comment]
I need more information. It'd be nice if you'd fill out the issue template.

Did you use `ionic start` to create this app? It looks like you're in a subdirectory of your project. Notice `(project config: ..\ionic.config.json)`. Is this correct? Does the same thing happen in the project root?

Do you have an `ionic.config.json`? Can you show it to me? Does it have the shape that all the text in the error message is describing?

Does the error happen with every command?
