### ISSUE TITLE
Ionic version not upgraded on Windows even after uninstalling 

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2535]
_From @abhi05b on July 18, 2017 9:19_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I was earlier working on Ionic1, now I want to build a new project in ionic2.
I uninstalled the previous version using commnads:
npm uninstall -g ionic
npm uninstall -g cordova

Cleaned the npm cache also. But still the on windows command prompt, the ionic cli version is still 2.1.18 and the ionic start is creating Ionic1 starter files.

**Expected behavior:**

Ionic start should create Ionic3 starter folder

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

_Copied from original issue: ionic-team/ionic#12395_

**Comment by dwieeb** [comment]
`npm info ionic dist-tags` shows the `@latest` tag being `3.5.0`, so it's something with your environment. 

You don't need to uninstall the Ionic CLI when switching between Ionic 1 and Ionic 2 projects. Install the new CLI:

```
npm i -g ionic@latest
```

Then see the help for start:

```
ionic start --help
```
