### ISSUE TITLE
Ionic generate page import pages into app.module.ts

### ISSUE THREAD

**Issue by Blackscr33n** [ionic-team/ionic-cli#2536]
Hey Community!

It would be great, if 
`ionic g page page-name`

would also import and add the page to the arrays in the app.module.ts, like it does it with components & directives.

and also a flag with --no-module which doesn't generate a .module.ts file.

Greets,
Blackscreen

**Comment by dwieeb** [comment]
@Blackscr33n Please see https://github.com/ionic-team/ionic-cli/issues/2519

@mhartington is working on a fix!
