### ISSUE TITLE
"If you want to create an Ionic/Cordova app, use the --cordova option."

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2543]
Docs at https://ionicframework.com/docs/cli/start/ and  `ionic help start` say:

> f you want to create an Ionic/Cordova app, use the `--cordova` option.

What does that mean? 
Not using the parameter creates the same project, doesn't it?

**Comment by dwieeb** [comment]
Using `--cordova` will install the `@ionic/cli-plugin-cordova` right away. In the next release of the CLI, it prompts the user if they'd like to integrate Cordova, which would imply `--cordova`.

I have more plans for this. Right now new apps get `config.xml`, `resources`, etc. even without the `--cordova` flag.

Follow this issue: https://github.com/ionic-team/ionic-cli/issues/2595
