### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2544]
_From @azakusilo on June 23, 2017 13:44_

Hello I got lastest ionic CLI and ionic installed.
But when I try to login, it is shows me a Error
```

 Try to exec command <b>ionic login --email a******@mail.ru --password **** --no-interactive</b>
RS Mobile:
 Ionic Log In status [WARN] You are already logged in as a****@mail.ru!
[WARN] You are in non-interactive mode. Use --interactive to re-enable prompts.
[ERROR] email must not be empty.
[ERROR] password must not be empty.
Use the --help flag for more details.

```

_Copied from original issue: ionic-team/ionic-app-scripts#1053_

**Comment by jgw96** [comment]
_From @janpio on June 25, 2017 16:9_

Error message tells you:

> Use --interactive to re-enable prompts.

Did you?

**Comment by jgw96** [comment]
_From @azakusilo on June 28, 2017 14:27_

I want to use in my case --no-interactive mode, because I setup the remote server script which is starts several commands at once and I need this flag. If use --interactive it may to await for prompts infinity time.

**Comment by jgw96** [comment]
_From @janpio on June 28, 2017 14:36_

Ok, then look at how `ionic login` actually works:
https://ionicframework.com/docs/cli/login/
The examples include one with email and password.

**Comment by jgw96** [comment]
_From @azakusilo on June 28, 2017 14:45_

It is works, but it is strange that it occurs a error. It does nothing bad, but really strange. What's why I'm asking.

**Comment by jgw96** [comment]
_From @janpio on June 28, 2017 15:9_

Oh, so the command you posted in the first post actually works, only the `[ERROR]` output is strange? 
Then this is a proper bug and should be fixed. Thanks for reporting.

**Comment by jgw96** [comment]
_From @azakusilo on June 28, 2017 15:15_

Yes, it is. Thank you too.

**Comment by jgw96** [comment]
_From @janpio on July 4, 2017 12:18_

(Just noticed: Then this is actually a Ionic CLI bug and should be posted or moved there: https://github.com/ionic-team/ionic-cli/issues)

**Comment by dwieeb** [comment]
This is not a bug. See `ionic login --help`. `email` and `password` are arguments, not options.

Try: `ionic login a******@mail.ru **** --no-interactive`
