### ISSUE TITLE
Livereload on serve not reloading ts files

### ISSUE THREAD

**Issue by adil-haddaoui** [ionic-team/ionic-cli#2546]
**Description:**

There is an error after the last update using --livereload either on browser or on simulator, the issue is that when changing on ts files the view is reloading but content isn't otherwise HTML and css are reloading and changing good !

**Steps to Reproduce / Example :**

there is a function called foo() which is foo() { let bar = 1; }
after deploy using livereload it will show that bar is 1, but change it to let bar = 2; the page will reload but the content will stay 1. so I have to kill the serve and relaunche it again. Which is so tiring and annoying.

```
**My `ionic info`:**

global packages:
    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-utils        : 1.5.0
    Cordova CLI             : 7.0.1 
    Ionic CLI               : 3.5.0

local packages:
    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.3

System:
    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.1.0 
    npm        : 3.10.10 

```

**Comment by janpio** [comment]
Ionic CLI only triggers the build, @ionic/app-scripts is the package actually doing the building and everything. Your issue is probably better suited for https://github.com/ionic-team/ionic-app-scripts (and as far as I remember there are already similar ones).

**Comment by adil-haddaoui** [comment]
@janpio  Ok thank you for your comment I will repost it there 👍

**Comment by dwieeb** [comment]
https://github.com/ionic-team/ionic-app-scripts/issues/1139
