### ISSUE TITLE
livereload broken for Ionic1/CLI 3.5 running on device (using //localhost)

### ISSUE THREAD

**Issue by jasonwinshell-br** [ionic-team/ionic-cli#2547]
livereload broken for Ionic1/CLI 3.5 running on device (using //localhost)

For command:

ionic cordova run -lc android --device

* v1 project, CLI 3.5, Android device

via cli-plugin-ionic1 plugin generates following reload snippet into a Ionic v1 index.html:

<script src="//localhost:35729/livereload.js?snipver=1" async="" defer=""></script>

This is incorrect. It should not be //localhost, since that refers to the device. It should
be the same as the v2 project - the live reload server. 

The work around is to pass an explicit value of --address
e.g. ionic cordova run -lc android --device --address 10.1.1.3

I believe the problem is in the cli-plugin-ionic1  (version = 2.0.1)

* v2 project, CLI 3.5, Android device  (working)

By comparison ...

CLI 3.5 injects the following reload snippet into a Ionic v2 index.html for app
running on Android device. The host:port points live reload server running on the computer,
not the device -- CORRECT

<script src="//10.1.1.3:35729/livereload.js?snipver=1" async="" defer=""></script>

**Steps to Reproduce:**

1. ionic cordova run -lc android --device
2. <script src="//localhost:35729/livereload.js?snipver=1" async="" defer=""></script> appears in index.html on app running on device.  You can verify that the script couldn't be found using Chrome debugger (Android). I assume the same is true on iOS.
3. Livereload does not work

**My `ionic info`:**

global packages:

    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-utils        : 1.5.0
    Cordova CLI             : 7.0.1 
    Gulp CLI                : not installed globally
    Ionic CLI               : 3.5.0

local packages:

    @ionic/cli-plugin-cordova : 1.4.1
    @ionic/cli-plugin-gulp    : 1.0.2
    @ionic/cli-plugin-ionic1  : 2.0.1
    Cordova Platforms         : android 6.0.0 ios 4.4.0
    Ionic Framework           : ionic1 1.3.3

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
    npm        : 4.1.1

**Comment by dwieeb** [comment]
Thanks for the detailed bug report! This was fixed for this issue: https://github.com/ionic-team/ionic-cli/issues/2433

The fix will be in CLI 3.6.

**Comment by jasonwinshell-br** [comment]
Thanks. Glad to help in anyway I can.  This may be related:

console log output is broken for ionic v1 / CLI 3.5  (does not go to terminal for server, run, emulate, etc).  --browser doesn't work either for v1/CLI 3.5

**Comment by jasonwinshell-br** [comment]
Can we get back the 'r' (application restart) option key that for CLI 3.x. Thanks.

**Comment by dwieeb** [comment]
@jasonwinshell-br I haven't been able to get around to looking into the console.log issue. 

You can make issues for both of those, if you like.
