### ISSUE TITLE
`ionic cordova resources` docs: add safe zone information

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2555]
See: http://blog.ionic.io/automating-icons-and-splash-screens/

> The splash screen’s artwork should roughly fit within a center square (1200×1200 px). [This template](http://code.ionicframework.com/resources/splash.psd) provides the recommended size and guidelines about artwork’s safe zone.

Link to template and "safe center square" should probably be added to docs.

**Comment by dwieeb** [comment]
Good catch! Thank you.
