### ISSUE TITLE
Remove livereload changed from `config.xml`

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2556]
Using `ionic cordova run android -l` (and similar livereload commands) adds stuff like this to `config.xml`:

```
    <content original-src="index.html" src="http://192.168.10.1:8100" />
    ...
    <allow-navigation href="http://192.168.178.34:8100" />
    <allow-navigation href="http://192.168.10.1:8100" />
```

If somehow possible this should also be removed again after the livereload session is killed to make sure this is not accidentally checked in or built.

**Comment by dwieeb** [comment]
Finally got around to this. The `original-src` attribute is reset to `src` upon all `ionic cordova` command invocations, but we were missing a handler for resetting the attributes when run/emulate was killed with CTRL-C.

Thanks!

**Comment by MaddHatters** [comment]
This is occurring again for me in Ionic 5. Should I open a new issue?

![image](https://user-images.githubusercontent.com/30221259/76906597-4d42b800-6872-11ea-965a-89bddcd5db16.png)
