### ISSUE TITLE
Compile TypeScript and prepare platform files with Ionic CLI

### ISSUE THREAD

**Issue by mifkys** [ionic-team/ionic-cli#2558]
Hello. This feature request is continue of next forum topic: https://forum.ionicframework.com/t/how-can-i-compile-ionic-with-cli-and-build-with-xcode/99329

**Short description**: Need ability to compile typescript code and prepare platform files for next step - build with XCode/AndroidStudio/VisualStudio. At this moment I am waiting ionic compile step, cordova build step (long time) then Xcode build/run step. Not so useful.

**Comment by dwieeb** [comment]
I have a plan for the next release.

**Comment by janpio** [comment]
Does `npm run build` copy to the Cordova platforms directory?

**Comment by mifkys** [comment]
I tried this command and it not copy code to platform directory

**Comment by dwieeb** [comment]
Oops, brain fart. You'll of course also need to use `cordova prepare`.

**Comment by janpio** [comment]
(Docs at https://ionicframework.com/docs/cli/cordova/prepare/ could probably use a little love [same applies for the original Cordova docs by the way - will create an issue shortly])

**Comment by dwieeb** [comment]
@mifkys There's now an `ionic build` command fresh off the press. If you'd like to give this a test, you can install the canary CLI:

`npm i -g ionic@canary`

**Comment by mifkys** [comment]
Since ionic 3.6 cli must installed locally so I also used `npm i --save-dev --save-exact ionic@canary`. After this ionic-cli start understood `ionic build` command. All works fine. Thanks!

**Comment by dwieeb** [comment]
Good to hear, thanks. `ionic build` will be a part of CLI 3.7.
