### ISSUE TITLE
Improve `ionic cordova prepare` docs

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2560]
https://ionicframework.com/docs/cli/cordova/prepare/ doesn't include the most important bit of "copied www to platforms".

**Comment by dwieeb** [comment]
Agreed. Any cordova command that says "Like running x, but provides friendly checks" needs work. This command is particularly important, so I took some time to write up a description.

**Comment by janpio** [comment]
(Related thought: The "like running `x` directly" could/should probably link to the Cordova docs. They might give more information, and are hopefully kept up to date what the commands actually do)
