### ISSUE TITLE
Inform users about alternatives to Cordova `browser` platform

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2561]
Using the `browser` platform is not recommended. Maybe the CLI should warn people about it when they try to use it, output a link to a documentation page about how it should really be done. (Of course after the warning the user should be free to do whatever he wants)

**Comment by dwieeb** [comment]
@janpio Can you expand on this? How should it "really be done"?

**Comment by janpio** [comment]
I have no idea - there is no "official" word on how to build a proper PWA, yet. If people use the browser platform, or report problems with it, they are only told that this is not the way and they should probably use the (not really documented) `npm run ionic:build`. For now there is no `ionic pwa build` or similar, so people use the cordova browser platform (also because it mostly works).
