### ISSUE TITLE
Ionic lab SyntaxError: Unexpected token ‘>’ in safari 9.1.2

### ISSUE THREAD

**Issue by gnprabhurightclick** [ionic-team/ionic-cli#2563]
I started a new ionic v2 app and as per the crash course on the ionicframework homepage tried to run the command sudo ionic lab.
The safari browser opens and throws a syntax error: SyntaxError: Unexpected token '>' on the console. Following is the screenshot of the safari browser.

![](https://cdn-enterprise.discourse.org/ionicframework/uploads/default/original/3X/e/1/e19679ac16edd4310fb0cec5d21f520bcb1a6902.png)

![](https://cdn-enterprise.discourse.org/ionicframework/uploads/default/original/3X/b/a/ba31b13d3c95fce1afd90b1d316af63236b3f0c0.png)

Following is the "ionic info" command for a new app created as per the crash course:

global packages:

@ionic/cli-utils : 1.5.0
Ionic CLI        : 3.5.0
local packages:

@ionic/app-scripts              : 2.0.2
@ionic/cli-plugin-ionic-angular : 1.3.2
Ionic Framework                 : ionic-angular 3.5.3
System:

Node       : v7.0.0
OS         : OS X El Capitan
Xcode      : Xcode 8.1 Build version 8B62 
ios-deploy : 1.9.0 
ios-sim    : 5.0.11 
npm        : 3.10.8
Note: once the lab server is started it works fine on Google Chrome but throws the Syntax Error on the Safari browser.

Kindly help me with the same. 

Thank You

**Comment by mhartington** [comment]
@gnprabhurightclick could you pull down the latest version of app-scripts?
Seems there was some es6 features in there that safari 9 did not support


```
npm install @ionic/app-scripts@latest
```

**Comment by gnprabhurightclick** [comment]
thanks it works for ionic v3 app.

the cli-plugin-ionic1/lab/static/lab.js still has the Error in Safari for the line:

let el = $('#app-info');

I went and changed the 'let' to 'var' in the lab.js and it works.

Is it possible that the change is made to the ionic repository so that it doesn't have to be manually changed.

Thank you

**Comment by dwieeb** [comment]
@gnprabhurightclick I believe @mhartington killed that in this commit: https://github.com/ionic-team/ionic-app-scripts/commit/41a133552ca7875c0fe825a49b51e779c91dc759

2.1.3 should have the fix. Thanks!
