### ISSUE TITLE
upload command fails silently

### ISSUE THREAD

**Issue by ruffzy** [ionic-team/ionic-cli#2564]
**Description:**
On the command line I was able to login on my apps.ionic.io account and I was also able to link my local code with the app that I have created in the browser on apps.ionic.io. My app_id was then written to ionic.config.json.

I am also able to build the app and run it in the android simulator.

But when I execute the upload command it just does a build but doesn't seem to upload the generated code.
When I go to my app on apps.ionic.io I can't see any hint at all that something has been uploaded. Therefore I guess that my upload command actually failed but wasn't brave enough to show me any exception. Meanwhile I have uninstalled and reinstalled ionic several times without any success. However when I run the upload command for the same files from another machine everything works as expected.

Can someone please give me at least an idea where I can start investigating? Is there a log somewhere?

**Steps to Reproduce:**
Not reprocucable, problem occurs only on my development machine.

**Output:**
```
PS D:\IonicTest\ionic-tabs-app> ionic upload --verbose
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
Running app-scripts build: --log-level debug

[14:37:02]  build dev started ...
[14:37:02]  clean started ...
[14:37:02]  clean finished in 3 ms
[14:37:02]  copy started ...
[14:37:02]  transpile started ...
[14:37:04]  transpile finished in 2.02 s
[14:37:04]  preprocess started ...
[14:37:04]  deeplinks started ...
[14:37:04]  deeplinks finished in 9 ms
[14:37:04]  preprocess finished in 11 ms
[14:37:04]  webpack started ...
[14:37:04]  copy finished in 2.16 s
[14:37:09]  webpack finished in 5.47 s
[14:37:11]  sass started ...
[14:37:12]  sass finished in 791 ms
[14:37:12]  postprocess started ...
[14:37:12]  postprocess finished in 5 ms
[14:37:12]  lint started ...
[14:37:12]  build dev finished in 9.98 s
PS D:\IonicTest\ionic-tabs-app>
```

**My `ionic info`:**
global packages:

    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-utils        : 1.5.0
    Ionic CLI               : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.0.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.3.0

**Comment by dwieeb** [comment]
Try with `--no-build`?

**Comment by ruffzy** [comment]
--nobuild didn't changed anything. The upload was not triggered. However after updating to ionic CLI version 3.6 the upload is working as expected. I have to say that I have also reinstalled node.js - therefore I can not say what has finally fixed the issue.
