### ISSUE TITLE
Cannot read property 'module' of undefined | ionic generate page

### ISSUE THREAD

**Issue by gabrieltobi** [ionic-team/ionic-cli#2566]
**Description:**

I got an error trying to generate a page.

**Steps to Reproduce:**

Example repo:  N/A

1. Execute `sudo ionic generate page name`

**Output:**

```
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] !!! ERROR ENCOUNTERED !!!
TypeError: Cannot read property 'module' of undefined
[DEBUG] TypeError: Cannot read property 'module' of undefined
        at Object.processPageRequest (/Users/desenvolvedor/Projetos
        Apps/Garbus/node_modules/@ionic/app-scripts/dist/generators.js:7:117)
        at Object.<anonymous> (/Users/desenvolvedor/Projetos
        Apps/Garbus/node_modules/@ionic/cli-plugin-ionic-angular/dist/generate.js:38:34)
        at next (native)
        at fulfilled (/Users/desenvolvedor/Projetos
        Apps/Garbus/node_modules/@ionic/cli-plugin-ionic-angular/dist/generate.js:4:58)
```

**My `ionic info`:**

global packages:

    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-plugin-proxy : 1.3.2
    @ionic/cli-utils        : 1.5.0
    Cordova CLI             : 7.0.1
    Ionic CLI               : 3.5.0

local packages:

    @ionic/app-scripts              : 2.1.0
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 6.0.0
    npm        : 5.3.0

**Other Information:**

**Comment by dwieeb** [comment]
@gabrieltobi This particular issue was just fixed in a new app-scripts release. Please update and let us know if there are any issues.
