### ISSUE TITLE
Error trying to update to latest CLI

### ISSUE THREAD

**Issue by HartHerbert** [ionic-team/ionic-cli#2572]
**Description:**
I can't update my ionic/cli-plugin-cordova from 1.4.1  to 1.5.0.
Everytime I try to update I get an npm error.
I even deleted my node_modules Folder but it didn't help.
Any suggestions ?

Log:
```
? Local plugin @ionic/cli-plugin-cordova has an update available (1.4.1 => 1.5.0)! Would you like to install it? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
✖ Running command - failed!
[ERROR] An error occurred while running npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest (exit code
        1):
        
        WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY:
        sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= integrity checksum failed when using sha1: wanted
        sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= but got
        sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==. (11423 bytes)
        WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during
        revalidation.
        npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
        npm WARN ionic-img-viewer@2.4.0 requires a peer of ionic-angular@~3.4.0 but none was installed.
        
        npm ERR! Cannot read property '0' of undefined
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/herberthart/.npm/_logs/2017-07-28T07_40_06_795Z-debug.log

```

**My `ionic info`:**

```
cli packages:

    @ionic/cli-utils  : 1.6.0 (/Users/herberthart/Pookypet_iOS/node_modules/ionic/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI) : 3.6.0 (/Users/herberthart/Pookypet_iOS/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    npm        : 5.3.0 

```

**Comment by HartHerbert** [comment]
npm 5.3.0 is broken, that was the error.

> 'jlchereau' npm 5.3.0 is broken (on windows 10) for me too after upgrading to nodeJS v8.2.0. Same symptoms/logs as described above. npm install -g npm@5.2.0 temporarily fixes the problem.

[Issue here](https://github.com/npm/npm/issues/17858)

**Comment by dwieeb** [comment]
@HartHerbert Hmm.. you may have other issues with npm 5.2 FYI. If all else fails, you can go back to npm 4. npm 5 is still trying to stabilize.

**Comment by MichaelHuy** [comment]
I installed ionic successfully. But Got this Error.:sweat::sweat:
Macs-MacBook-Pro-2:~ huyle$ sudo npm install -g ionic
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

/usr/local/Cellar/node/10.4.0/bin/ionic -> /usr/local/Cellar/node/10.4.0/lib/node_modules/ionic/bin/ionic

/usr/local/Cellar/node/10.4.0/lib

└── ionic@4.0.6

Macs-MacBook-Pro-2:~ huyle$ ionic info

**-bash: /usr/local/bin/ionic: No such file or directory**
