### ISSUE TITLE
Bug: Even with `--address localhost` set debug runs on ip address

### ISSUE THREAD

**Issue by shyamal890** [ionic-team/ionic-cli#2580]
**Description:**
Debugging with `ionic cordova run android --address localhost` used to set localhost as the server host address however now I get the following: 
![i](https://user-images.githubusercontent.com/6606965/28746834-895221b4-74af-11e7-8ddd-e80fb1fb2054.jpg)

Due to this the android app is running on the `ip address` instead of on `localhost`. This makes debugging impossible, since Chrome inspect doesn't allow forwarding on high port numbers (allows only till 10000) while all IIS based SSL ports are above 10000. If the app was running on `localhost` it is the connection is assumed to be on the same device while the same doesn't work with ip address. More on this here: 

https://stackoverflow.com/questions/8323357/cannot-access-localhost-from-android-device/16743134#16743134

**My `ionic info`:**

λ ionic info

cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0
    @ionic/cli-plugin-ionic-angular : 1.4.0
    @ionic/cli-utils                : 1.6.0 
    ionic (Ionic CLI)               : 3.6.0 

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.2
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node : v6.11.0
    OS   : Windows 10
    npm  : 3.10.10

**Comment by dwieeb** [comment]
Thanks, @shyamal890! I hope the behavior in CLI 3.7 will better suit your needs.
