### ISSUE TITLE
ionic cli  create icon and splash throw ERROE

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2583]
_From @1483799920 on July 28, 2017 7:26_

ionic-cli run 
> ionic cordova resources

throw ERROR

>✔ Collecting resource configuration and source images - done!
[WARN] Error occurred during command execution from a CLI plugin
       (@ionic/cli-plugin-cordova).
✖ Uploading source images to prepare for transformations - failed!
Error: read ETIMEDOUT

why is that?

>nodejs   v6.11.0
npm       v3.10.10
ionic-cli v3.6.0
cordova v7.0.1

_Copied from original issue: ionic-team/ionic#12494_

**Comment by dwieeb** [comment]
@1483799920 An upload of one of the source images to our servers timed out. If you are on very slow internet, you likely will not be able to use that command.

**Comment by 1483799920** [comment]
Ok,I see.Thank you for your help!
