### ISSUE TITLE
ERR_INSECURE_RESPONSE: https url not supported

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2584]
_From @shyamal890 on July 30, 2017 12:21_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Not able to access https api url on local network from mobile when debugging with `ionic cordova run --address 'ip address'`.
Getting `ERR_INSECURE_RESPONSE` error. This is because the local network api url has ssl certificate which only supports localhost and not IP address like `192.168.0.8`.

**Expected behavior:**
Should allow insecure https for debugging purpose

**Steps to reproduce:**
Simply create a https web api url binded with localhost ssl certificate. Try and access this url from ionic app in mobile.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

ionic info

cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0
    @ionic/cli-plugin-ionic-angular : 1.4.0
    @ionic/cli-utils                : 1.6.0 
    ionic (Ionic CLI)               : 3.6.0 

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.2
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node : v6.11.0
    OS   : Windows 10
    npm  : 3.10.10

_Copied from original issue: ionic-team/ionic#12513_

**Comment by dwieeb** [comment]
This would be configured in your Android device, not Ionic. You'd need to add the CA root certificate to your device as a trusted certificate. There may also be a setting for Chrome to ignore insecure SSL.

**Comment by shyamal890** [comment]
The problem is I have a webapi running on localhost (say https://localhost:44366). The ionic app should access this api for data. Since, the certificate is issued for localhost Ionic is not able to access the webapi on a ip address of the webapi host (say https://192.168.0.2:44366) giving insecure error. How to solve this?

**Comment by dwieeb** [comment]
Numerous ways:
* configuring your Android device to allow insecure SSL for Chrome
* using adb: https://stackoverflow.com/a/31944432
* using service proxies: https://github.com/ionic-team/ionic-cli#service-proxies
* don't issue the certificate for localhost
