### ISSUE TITLE
cordova android livereload on localhost

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2585]
_From @condorman on July 30, 2017 19:24_

Hi, 
Usualy work on trip or in companies where it is not possible to use wifi routers, in the ionic version 1 and 2 I resolved with command "Ionic cordova run android -l --address localhost" after set 

- adb reverse tcp: 53703 tcp: 53703
- Adb reverse tcp: 35729 tcp: 35729
- Adb reverse tcp: 8100 tcp: 8100

But from v3 it is no longer possible to indicate the address "localhost" it's possible to implement this function? Do you have others suggest to give me to develop in livereload on physical device only via usb cable?

thank you!!

_Copied from original issue: ionic-team/ionic#12517_

**Comment by dwieeb** [comment]
@condorman Looks like the CLI right now requires an external address for the Cordova run/emulate commands. I will fix this in the next release to work for your use case.

Thank you!
