### ISSUE TITLE
ionic upload isn't working 

### ISSUE THREAD

**Issue by Yassinelaadraoui** [ionic-team/ionic-cli#2588]
i'm trying to upload my app to ionic view but it doesn't work here's the output i get 

$ ionic upload
√ Requesting snapshot upload - done!
× Uploading snapshot - failed!
HTTP Error 400: POST https://ionic-apps.s3.amazonaws.com/
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>BE3FF442670EBD29</RequestId><HostId>MKWfhY7Ih5rroSPN7fQJOAdNZBKJi4Kwqpa6p5xDja2aNJ8UeTufn19aKklcIlQWC3uaqEjs4+0=</HostId></Error>
$ ionic upload
√ Requesting snapshot upload - done!
× Uploading snapshot - failed!
HTTP Error 400: POST https://ionic-apps.s3.amazonaws.com/
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>BE3FF442670EBD29</RequestId><HostId>MKWfhY7Ih5rroSPN7fQJOAdNZBKJi4Kwqpa6p5xDja2aNJ8UeTufn19aKklcIlQWC3uaqEjs4+0=</HostId></Error>

My `ionic info`:
$ ionic info

cli packages:

    @ionic/cli-plugin-gulp   : 1.1.0 (C:\Users\yassi\Desktop\snacks\blank\node_modules\@ionic\cli-plugin-gulp)
    @ionic/cli-plugin-ionic1 : 2.1.0 (C:\Users\yassi\Desktop\snacks\blank\node_modules\@ionic\cli-plugin-ionic1)
    @ionic/cli-utils         : 1.6.0 (C:\Users\yassi\Desktop\snacks\blank\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)        : 3.6.0 (C:\Users\yassi\Desktop\snacks\blank\node_modules\ionic)

global packages:

    Gulp CLI : not installed globally

local packages:

    Ionic Framework : ionic1 1.3.3

System:

    Node : v6.10.0
    OS   : Windows 10
    npm  : 3.10.10

**Comment by dwieeb** [comment]
Looks like a server initiated timeout.

Do you have access to faster internet?
