### ISSUE TITLE
Issue with ionic g page CLI

### ISSUE THREAD

**Issue by yajuve** [ionic-team/ionic-cli#2591]
**Description:**
The problem with this command 
`ionic g page test`
it doesn't generate the correctly page

1 - missing this import
`
import { NavController, NavParams } from 'ionic-angular';
`
2 - And strange tag like : $IMPORTSTATEMENT, $IONICPAGE, error in the syntax

**My `ionic info`:**
`
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.6.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 2.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.10
Node Version: v6.9.4
Xcode version: Not installed
`
Thanks

**Comment by dwieeb** [comment]
Your CLI version is very old. Please upgrade to the new CLI V3.

**Comment by saip92** [comment]
I'm getting the same problem after the CLI updated to v3.8.1 from v3.7.0

**Comment by dwieeb** [comment]
@saip92 Please also post your `ionic info`. It'd be best if you created a new issue, as it would be for CLI v3.

**Comment by saip92** [comment]
I got it to work

I had to update `@ionic/app-scripts` package too and then it worked

Thanks!
