### ISSUE TITLE
ionic start self signed certificate in certificate chain error

### ISSUE THREAD

**Issue by essaghir-m** [ionic-team/ionic-cli#2596]
**Description:**

when i run this cmd
`ionic start project1 blank`

i get to this error
`ionic start firstapp blank`
`[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)`
`× Downloading - failed!`
`Error: self signed certificate in certificate chain`

**My `ionic info`:**

**_cli packages_**:
    ionic/cli-utils: 1.6.0 
    ionic (Ionic CLI): 3.6.0 
**_System_**:
    Node : v8.2.1
    OS   : Windows 10
    npm  : 5.3.0

**Other Information:**

this's my first experience with ionic

**Comment by janpio** [comment]
Something between your computer and `https://github.com` is messing with the certificates, replacing the correct one with a self signed one. Try doing the same thing while connected to the hotspot of your mobile phone, quite often these then work.
