### ISSUE TITLE
White label branding support

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2598]
_From @irundaia on August 2, 2017 12:8_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

** Desired functionality
I'm currently working on an app that is going to be rebranded for a number of different client. Currently, what I have to do is: 
# replace the `config.xml` (with different app name/id)
# replace the spashscreen and icon resources
# replace the theme in the `src/theme` directory
# replace the fonts and images in `src/assets`

It would be great if this would be supported by the ionic cli.

_Copied from original issue: ionic-team/ionic#12550_

**Comment by dwieeb** [comment]
@irundaia Sounds like more of a job for a custom script that you could write.

**Comment by alejandromagnorsky** [comment]
We have exactly the same issue and I'm pretty sure it's quite common. 
We are in the process of migrating to Ionic 3 from Ionic 1. For Ionic 1 we have our own grunt task that does the job, but in Ionic 3 we are still newbies.
Can you stir us in the right direction on how to do it?

**Comment by rakshans1** [comment]
Is there any solution to this

**Comment by pulkitbhutani** [comment]
Is there any solution to this ?
