### ISSUE TITLE
update ionic problem 

### ISSUE THREAD

**Issue by zz373609** [ionic-team/ionic-cli#2600]
**Description:**

when i type the ionic --verbose 
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova 3
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for local @ionic/cli-plugin-cordova 3
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
[DEBUG] Plugin error: PLUGIN_NOT_INSTALLED
what is the @ionic/cli-plugin-cordova 3???

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

**Other Information:**

**Comment by dwieeb** [comment]
@zz373609 Make sure you're on the latest CLI:

```
npm i --save-dev --save-exact ionic @ionic/cli-plugin-cordova @ionic/cli-plugin-ionic-angular
```
