### ISSUE TITLE
cannot get rid of unmet dependency for rxjs library. 

### ISSUE THREAD

**Issue by fl0r1d4** [ionic-team/ionic-cli#2601]
Hello i am trying my best to update the rxjs library but I keep getting this warning message saying there is an unmet peer dependency. However inside the package.json file the rxjs version is being updated properly.
"rxjs": "^5.4.2"
When I install other packages it gives me the same warning again saying there is an unmet dependency for the rxjs library again though.  

Tried 1:
felixs-MacBook-Pro:tapping backup$ npm install --save rxjs@latest
Tapping@0.0.1 /Users/backup/Desktop/Work/Tapping
└── UNMET PEER DEPENDENCY rxjs@5.4.2

npm WARN ionic-angular@3.3.0 requires a peer of rxjs@5.1.1 but none was installed.
npm ERR! code 1
felixs-MacBook-Pro:tapping backup$ 

Tried 2:
felixs-MacBook-Pro:tapping backup$ npm install --save rxjs@5.1.1
Tapping@0.0.1 /Users/backup/Desktop/Work/Tapping
└── UNMET PEER DEPENDENCY rxjs@5.1.1

npm WARN ng2-fittext@1.0.21 requires a peer of rxjs@^5.4.0 but none was installed.
npm ERR! code 1

**Comment by dwieeb** [comment]
Thanks for posting your issue. Unfortunately, this repo is reserved for bug reports and feature requests of the Ionic CLI. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).
