### ISSUE TITLE
Reset plugins and platforms

### ISSUE THREAD

**Issue by videmort** [ionic-team/ionic-cli#2604]
In ionic v3  ionic state reset or ionic state restore is not available. How I can reset that and read the plugins from package.json?

**Comment by janpio** [comment]
What exactly do you want to achieve with each command?

In general: `ionic cordova prepare` should do the job.

**Comment by dwieeb** [comment]
@videmort I've added a nice informational message for invocations of `ionic start` in the latest CLI (3.8.0). For more information about managing Cordova platforms and plugins, please see the entry for `state` in the changelog: https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#removed-commands

**Comment by ValentinBragaru** [comment]
rm -rf /plugins && rm -rf /platforms &&  ionic cordova prepare
