### ISSUE TITLE
"Highlight" command line window on needed input?

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2606]
I use to execute commands like `ionic cordova run android --prod` and then switch to other taks and windows, waiting until my USB connected phones lights up with the running app (or the request to unlock).

With the added "? The Ionic CLI (local version) has an update available (3.6.0 => 3.7.0)! Would you like to install it?" and similar requests, this most often results in me getting back to the command line 10 minutes later with one of these waiting for input. 

Is there some way the CLI could "highlight" this? Blinking, making a sound, a notification appearing somewhere, whatever...

**Comment by janpio** [comment]
(I absolutely love it when this happens twice or more times 💯 )

**Comment by janpio** [comment]
Homebrew install on Mac does something like that when you install it via `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`.

**Comment by dwieeb** [comment]
We use inquirer for the prompts: https://github.com/SBoudrias/Inquirer.js

I don't know the answer off-hand, but I searched through their issues and this doesn't appear to be a feature request.
