### ISSUE TITLE
ionic-cli v3.7.0 does not support building with 64bit crosswalk

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-cli#2609]
**Description:**
After upgrading ionic ci from v2 to v3.7.0 i can't build apk for 64bit platform with crosswalk
Before this below command worked fine
`ionic build android --release --xwalk64bit --prod --generateSourceMap false`
After upgrade i tried
`ionic cordova build android --release --xwalk64bit --prod --generateSourceMap false` and it always creates APKs android-armv7-debug.apk and android-x86-debug.apk (not for 64bit platform)

**Steps to Reproduce:**
Run `ionic cordova build android --xwalk64bit`

**Output:**
ionic cordova build android --xwalk64bit
Running app-scripts build: --build --iscordovaserve --nobrowser

[09:20:46]  build dev started ...

**My `ionic info`:**
cli packages:

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.2
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
    ios-deploy        : 1.9.1
    ios-sim           : 6.0.0
    npm               : 3.10.10

**Other Information:**
--xwalk64bit flag in the build command works in v2. After upgrading to v3 it is not longer working

**Comment by dwieeb** [comment]
Please see the examples in `ionic cordova build --help`. If you don't separate the args with the `--` separator, the arg doesn't get passed to Cordova.

Try `ionic cordova build android -- --xwalk64bit`.

**Comment by bastakmusic** [comment]
another issue is signing apk file which Keytool is not recongnized in CLI v3 
not too expert with this platform but i researched using help and google search but not answer

**Comment by Acronus2008** [comment]
This command does not generate the architecture we want, with this we are only creating the one debug application, now if we make cordova build android --release --xwalk64bit this generates the architecture we want for amr64 and x86_64, this you can check with the following commands .

$ zipinfo -1 android-arm64-release-unsigned.apk |grep arm64
lib/arm64-v8a/libxwalkcore.so
lib/arm64-v8a/libxwalkdummy.so

and

$ zipinfo -1 android-x86_64-release-unsigned.apk |grep x86
lib/x86_64/libxwalkcore.so
lib/x86_64/libxwalkdummy.so

Hope that help
