### ISSUE TITLE
ionic-cli v3.7.0 does not generate component module anymore

### ISSUE THREAD

**Issue by Borongaj** [ionic-team/ionic-cli#2610]
**Description:**
ionic-cli v3.7.0 does not generate component module anymore

**Steps to Reproduce:**
ionic g page test

**Output:**
test.html
test.scss
test.js

_Missing file : test.module.ts_

**My `ionic info`:**
cli packages:

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 6.0.0
    npm        : 4.2.0

**Comment by dwieeb** [comment]
You must upgrade `@ionic/app-scripts` to the latest.
