### ISSUE TITLE
 There was no CLI project plugin that responded to ionic build.

### ISSUE THREAD

**Issue by huxiaozhong** [ionic-team/ionic-cli#2613]
[WARN] There was no CLI project plugin that responded to ionic build.
       Make sure you have the Ionic CLI and a suitable project plugin installed locally.

i have a project with ionic1  ,when i use  ionic build android  ,get this error,why?

cli packages: (D:\code\PetroChinaApp2017\CordovaAppFrameWork\node_modules)

    @ionic/cli-plugin-gulp   : 1.1.1
    @ionic/cli-plugin-ionic1 : 2.1.1
    @ionic/cli-utils         : 1.7.0
    ionic (Ionic CLI)        : 3.7.0

global packages:

    Gulp CLI : CLI version 3.9.1 Local version 3.9.1

local packages:

    Ionic Framework : ionic1 1.3.3

System:

    Node : v6.11.2
    OS   : Windows 10
    npm  : 3.10.10

**Comment by huxiaozhong** [comment]
how to fix it? thanks

**Comment by dwieeb** [comment]
Did you run `ionic build`?

**Comment by huxiaozhong** [comment]
yes    ionic build android

**Comment by huxiaozhong** [comment]
D:\code\PetroChinaApp2017\CordovaAppFrameWork>ionic build
[WARN] There was no CLI project plugin that responded to ionic build.
       Make sure you have the Ionic CLI and a suitable project plugin installed locally.

**Comment by huxiaozhong** [comment]
D:\code\PetroChinaApp2017\CordovaAppFrameWork>ionic build android
[WARN] There was no CLI project plugin that responded to ionic build.
       Make sure you have the Ionic CLI and a suitable project plugin installed locally.

**Comment by huxiaozhong** [comment]
can you help  me?

**Comment by huxiaozhong** [comment]
cordova build android    
success   .
when  i use     officer demo   ionic start myproject --type ionic1
and  use   ionic build android

get same result  
[WARN] There was no CLI project plugin that responded to ionic build.
Make sure you have the Ionic CLI and a suitable project plugin installed locally.

**Comment by janpio** [comment]
If you want to build for Cordova, the Ionic command is `ionic cordova build android` (since CLI 3.x).

(@dwieeb Maybe catch people calling it with `ios` and `android` and redirect them to the correct command?)

**Comment by dwieeb** [comment]
@huxiaozhong Where did you find docs/tutorials that told you to run `ionic build android`? I'm confused as to why people are still trying to run this command. 

@janpio Probably a good idea.

**Comment by LokeSonne** [comment]
I get the same error. Ionic build is (again) an official ionic cli command per v. 3.7.0. This is the only option to create a web build, say, for progressive web apps which are pushed heavily by the Ionic Team.

cli packages:

```
    @ionic/cli-utils  : 1.7.0
    ionic (Ionic CLI) : 3.7.0
```

global packages:

```
    Cordova CLI : 7.0.1 
    Gulp CLI    : CLI version 1.3.0 Local version 3.9.1
```

local packages:

```
    @ionic/cli-plugin-cordova : 1.4.1
    @ionic/cli-plugin-gulp    : 1.0.2
    @ionic/cli-plugin-ionic1  : 2.0.1
    Cordova Platforms         : android 6.2.3 browser 4.1.0
    Ionic Framework           : unknown
```

System:

```
    Node       : v6.11.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
    npm        : 4.0.5 
```

**Comment by janpio** [comment]
> Ionic Framework           : unknown

This doesn't look good. There should be a version number here.
Are you really using Ionic v1 (see plugin that is installed)?

**Comment by dwieeb** [comment]
@LokeSonne Hmm. Lovely relic of the old CLI. Okay, I will try to use `bower.json` to detect the version instead.

**Comment by dwieeb** [comment]
@LokeSonne Additionally, this isn't an error, it's a warning. There is no official "build step" for Ionic 1 projects, so `ionic build` won't _do_ anything unless you use CLI/gulp hooks. 3.8 will make this a bit more clear.

**Comment by LokeSonne** [comment]
@dwieeb True there's no build step for ionic 1 (or web builds for that matter). Guess it's been a while since I last had to make a build. Appreciate the version retrieval fix.
