### ISSUE TITLE
ionic share command not found

### ISSUE THREAD

**Issue by shreyashdholakia** [ionic-team/ionic-cli#2614]
**Description:**

Ionic share "email" is not working. Used to work but after updating to CLI 3.7.0 it has stopped working. 

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

    @ionic/cli-plugin-gulp   : 1.1.1
    @ionic/cli-plugin-ionic1 : 2.1.1
    @ionic/cli-utils         : 1.7.0
    ionic (Ionic CLI)        : 3.7.0

global packages:

    Gulp CLI : CLI version 3.9.0 Local version 3.9.1

local packages:

    Ionic Framework : unknown

System:

    Node       : v8.2.1
    OS           : macOS Sierra
    Xcode     : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim   : 5.0.13 
    npm        : 5.3.0 

**Other Information:**

**Comment by janpio** [comment]
`ionic share` is not a valid command of Ionic CLI 3.x:
https://ionicframework.com/docs/cli/

See here for what you should use instead: https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#removed-commands
