### ISSUE TITLE
Link to docs in generated component is wrong.

### ISSUE THREAD

**Issue by MartinMuzatko** [ionic-team/ionic-cli#2622]
**Description:**
Hope I'm writing this to the correct repository!

When I generate a new component (lets call it test), I will get the following comment in `components/test/test.ts`.
```
/**
 * Generated class for the TestComponent component.
 *
 * See https://angular.io/docs/ts/latest/api/core/index/ComponentMetadata-class.html
 * for more info on Angular Components.
 */
```

The link  https://angular.io/docs/ts/latest/api/core/index/ComponentMetadata-class.html is leading to a **page not found** page. I don't know where it is supposed to lead to.

**Steps to Reproduce:**

```bash
> $ ionic g
? What would you like to generate: component
? What should the name be? test
[OK] Generated a component named test!
```

**Output:**

**My `ionic info`:**
```
> $ ionic info
cli packages: (/Users/martinmuzatko/dev/test/ionic/test/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.2.1
    OS   : OS X El Capitan
    npm  : 5.3.0 
```

**Comment by dwieeb** [comment]
Thanks, @MartinMuzatko! Turns out most of those links were outdated. Hopefully Angular keeps the documentation URLs the same now. 😆
