### ISSUE TITLE
Using `--prod` with `ionic serve` seems to do strange things

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2625]
Super strange, can't replicate myself, but 2 users already reported something like that:

https://forum.ionicframework.com/t/building-with-release-prod-styling-issues/101135
https://forum.ionicframework.com/t/what-a-disappointment-ionic-has-become-the-java-of-mobile-development/101330/30?u=sujan12

**Comment by dwieeb** [comment]
Likely no longer an issue, as we now (CLI 3.8) filter args before passing them to app-scripts (see https://github.com/ionic-team/ionic-cli/blob/master/packages/@ionic/cli-utils/src/lib/ionic-angular/serve.ts#L74-L94).

Neither `--prod` nor `--release` are arguments for serve, as serve is meant only for a development tool.
