### ISSUE TITLE
3.8cli "cordova_not_available" on ios/android run livereload

### ISSUE THREAD

**Issue by MauroLescano** [ionic-team/ionic-cli#2633]
**Description:**
20 min ago i update from 3.7 cli to 3.8, now when run
ionic cordova run android -l
or
ionic cordova run ios -l
Any cordova plugin fails. "cordova_not_available"
in prev 3.7 was working fine.

I think is related that doesnt run "cordova prepare" in livereload

In standard way 3.8cli works fine
ionic cordova run ios
ionic cordova run android

**Output:**
Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
(anonymous) @ ion-dev.js:156

ion-dev.js:156 Native: tried calling SplashScreen.hide, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

Native: tried calling Facebook.login, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
(anonymous) @ ion-dev.js:156
ion-dev.js:156 
cordova_not_available
**My `ionic info`:**
    @ionic/cli-utils  : 1.8.0
    ionic (Ionic CLI) : 3.8.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v6.10.2
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002

**Comment by dwieeb** [comment]
Thanks @MauroLescano, I'm going to close this in favor of this issue: https://github.com/ionic-team/ionic-cli/issues/2634
