### ISSUE TITLE
Consider allowing --prod flag on ionic serve

### ISSUE THREAD

**Issue by fephil** [ionic-team/ionic-cli#2636]
Hi,

I certainly appreciate this could be a fringe use case but I set variables within my app depending on if the task has a --prod flag. (development and production database basically).

Would you consider allowing the prod flag in the serve task as it also allows me to see if the Javascript is minifying correctly (without waiting for an emulator/device to load).

https://github.com/ionic-team/ionic-cli/issues/2625 has disabled the use of --prod for the serve task.

Thanks,
Phil

**Comment by danbucholtz** [comment]
With Angular 5, we'll only support prod builds. We have no intention of adding this functionality until Angular 5 ships. Ionic 4 will likely use AOT for every build.

Thanks,
Dan
