### ISSUE TITLE
New ionic-cli 3.8.1 detects only a part of deprecated plugins

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-cli#2641]
We upgraded to the new `ionic-cli 3.8.1` version where four plugins now are deprecated (`@ionic/cli-plugin-ionic-angular, @ionic/cli-plugin-ionic1, @ionic/cli-plugin-cordova, and @ionic/cli-plugin-gulp`). We have installed two of them, cordova and ionic-angular.

After upgrading to **3.8.1** we run ionic command and get this log
```
[INFO] Enabling Cordova integration.
> ionic config set integrations.cordova {} --json --force
[OK] integrations.cordova set to {} in ./ionic.config.json!
[WARN] Detected @ionic/cli-plugin-cordova in your package.json.

       As of CLI 3.8, it is no longer needed. You can uninstall it.
       
[INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --consolelogs --nobrowser 

```

So as you can see we get warned cordova plugin is deprecated but nothing about the ionic-angular plugin. So we remove cordova plugin from pacakge.json and relaunch the command with no error warning.
I think you should warn also about the other plugins.

**My `ionic info`:**
```
cli packages: (/abc/node_modules)
    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:
    Cordova CLI : 7.0.1 

local packages:
    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:
    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 3.10.10 
    OS                : Linux 4.10
```

**Comment by dwieeb** [comment]
Thanks, @mburger81, I'll add in additional checks.
