### ISSUE TITLE
Automatic ionic upgrade does work only in part on Linux

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-cli#2642]
**Description:**
After launching a normal ionc command we got this message:
```
ionic cordova emulate android -lc
? The Ionic CLI (local version) has an update available (3.7.0 => 3.8.1)! Would you like to install it? Yes
> npm install --save-dev --save-exact ionic@latest
✔ Running command - done!

[OK] Updated Ionic CLI to 3.8.1! 🎉

Please re-run your command.

Note: You can downgrade to your old version by running: npm install --save --save-exact ionic@3.7.0
```

So as you can see there are an error on upgrade, but the message is not really good, what is happening? I think the problem is upgrading global ionic cli without root permissions.
After this command I have installed local cli but not global cli and so I'm pretty sure the problem is there.
**local:**
```
ionic --version
3.8.1
```

**global**
```
ionic --version
? The Ionic CLI has an update available (3.7.0 => 3.8.1)! Would you like to install it? (Y/n) 

```
I noticed this bug also on older version but I didn't had time to open a issue :smile: 

**My `ionic info`:**
```
cli packages: (/abc/node_modules)
    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:
    Cordova CLI : 7.0.1 

local packages:
    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:
    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 3.10.10 
    OS                : Linux 4.10
```

**Comment by mburger81** [comment]
Infact doing this outside of an  ionic project we get a more detailed error, this for sure is the same error on ionic project, I think you should handle the log better or perhaps relaunch the command  with sudo on linux?

```
ionic --version
? The Ionic CLI has an update available (3.7.0 => 3.8.1)! Would you like to install it? Yes
> npm install -g ionic@latest
✖ Running command - failed!
[ERROR] An error occurred while running npm install -g ionic@latest (exit code 243):
        
        npm WARN checkPermissions Missing write access to /usr/lib/node_modules/ionic
        npm WARN checkPermissions Missing write access to /usr/lib/node_modules
        /usr/lib
        └── ionic@3.8.1
        
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
        (node_modules/ionic/node_modules/chokidar/node_modules/fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted
        {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
        npm ERR! Linux 4.10.0-32-generic
        npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ionic@latest"
        npm ERR! node v6.11.2
        npm ERR! npm v3.10.10
        npm ERR! path /usr/lib/node_modules/ionic
        npm ERR! code EACCES
        npm ERR! errno -13
        npm ERR! syscall access
        
        npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/ionic'
        npm ERR! at Error (native)
        npm ERR! { Error: EACCES: permission denied, access '/usr/lib/node_modules/ionic'
        npm ERR! at Error (native)
        npm ERR! errno: -13,
        npm ERR! code: 'EACCES',
        npm ERR! syscall: 'access',
        npm ERR! path: '/usr/lib/node_modules/ionic' }
        npm ERR!
        npm ERR! Please try running this command again as root/Administrator.
        
        npm ERR! Please include the following file with any support request:
        npm ERR! /home/abc/npm-debug.log                     
```

**Comment by dwieeb** [comment]
I don't see any bugs in your original post. If you have the Ionic CLI installed locally _and_ globally, it will prompt you to update both. A single `npm install` won't magically upgrade both local and global installations.

As for your second post, I'm essentially using Node's `fs.access` with the mode `fs.constants.W_OK` to check whether I can write to that directory, which I think npm is doing as well (https://github.com/npm/npm/blob/d46015256941ddfff1463338e3e2f8f77624a1ff/lib/install/writable.js#L22), so not sure what the issue is there.

**Comment by mburger81** [comment]
You can see Please re run your command in the first log. 
I don't do npm install in my first post. I'm launching ionic command which checks for new cli and ask me to update it. After confirm with yes your automatic Update process is start but don't go until to the end. 
See confusing error message about re run command. 
After that I have to upgrade global cli with sudo command. 
I hope now it is more clear, if not please let me know

**Comment by dwieeb** [comment]
I want people to re-run the command because then it will run as the new version of the CLI.

**Comment by mburger81** [comment]
A okay sorry I didn't ubderstand the message in this way sorry. 
But at the end you would Update the cli which is installed globally by automatic update, this is in my case  not working and don't show any error message. 
I"ll try tomorrow updating to cli 3.9 and send you more details if it is ok for you.

**Comment by dwieeb** [comment]
The CLI either runs locally or globally and basically has no context or knowledge of the other installation. The "automatic update" feature is solely for a single installation.

**Comment by mburger81** [comment]
Okay, now doing a automatic update from inside a ionic project I got a sensed error which is the same as I get if I do it from outside, calling for example ionic info

So doing from ionic project I get this error:
```
ionic serve

? The Ionic CLI has an update available (3.8.1 => 3.9.2)! Would you like to install it? Yes
✖ npm install -g ionic@latest - failed!
[ERROR] An error occurred while running npm install -g ionic@latest (exit code 243):

        
        npm WARN checkPermissions Missing write access to /usr/lib/node_modules/ionic/node_modules
        npm WARN checkPermissions Missing write access to /usr/lib/node_modules/ionic/node_modules/@ionic
        npm WARN checkPermissions Missing write access to /usr/lib/node_modules
        npm ERR! path /usr/lib/node_modules/ionic/node_modules
        npm ERR! code EACCES
        npm ERR! errno -13
        npm ERR! syscall access
        npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/ionic/node_modules'
        npm ERR!     at Error (native)
        npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules/ionic/node_modules'
        npm ERR!     at Error (native)
        npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/lib/node_modules/ionic/node_modules\'\n    at 
        Error (native)',
        npm ERR!   errno: -13,
        npm ERR!   code: 'EACCES',
        npm ERR!   syscall: 'access',
        npm ERR!   path: '/usr/lib/node_modules/ionic/node_modules' }
        npm ERR! 
        npm ERR! Please try running this command again as root/Administrator.
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /home/abc/.npm/_logs/2017-08-21T12_11_10_694Z-debug.log
```

Do you don't think you can check if you are on systems like ubuntu and run the `npm install -g ionic@latest` as `sudo`, or would this be a bad practice?

**Comment by dwieeb** [comment]
I don't think people would like us running subcommands as `sudo`. 

Your file permissions seem odd. Can you post the output of these commands:

`$ id`

`$ stat -F /usr/lib/node_modules`

`$ stat -F /usr/lib/node_modules/@ionic`

`$ stat -F /usr/lib/node_modules/ionic`

**Comment by mburger81** [comment]
`-F` is not a valid parameter for me running stat under Ubuntu 17.4

I think at the end your solution you are suggesting is something like that right?
https://docs.npmjs.com/getting-started/fixing-npm-permissions

But I think if you raise up a question "would you like to run this command as sudo?" could be also very helpful or not?

**Comment by dwieeb** [comment]
I am trying to determine why the Node runtime is reporting different permissions than the OS. Again, I have file permission checks in the CLI already. I use `fs.access`. But the result of that call is lying to me, as you can see from your error.

What is `/abc/node_modules`? Did you scrub that? Why is it different than `/usr/lib/node_modules`, which is in the error message?

**Comment by dwieeb** [comment]
The automatic updates won't be a thing in CLI 4.
