### ISSUE TITLE
New ionic-cli 3.8.1 Replaces the App Icon & Splash image.

### ISSUE THREAD

**Issue by kumaresan-cgvak** [ionic-team/ionic-cli#2643]
**Description:**

New ionic-cli 3.8.1 replaces the App Icon & Splash image with default ionic images when adding a platform

**Steps to Reproduce:**

1. Update to latest CLI.
2. Create an Ionic Project.
3. Change the App Icon & Splash Image with a new one.
4. Add a new iOS Platform.
5. Execute `ionic cordova resources` command.
6. Remove the iOS Platform.
7. Add the iOS platform again.

Now the App Icons and Splash Image will be replaced with the default one. And the CLI will not allow us to run the  command `ionic cordova resources`

**My `ionic info`:**
cli packages: 

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1
    ios-sim           : 5.0.13
    Node              : v8.1.3
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

**Comment by pmurpmur** [comment]
I solved this issue by using the `-r` flag for the `ionic cordova platform add` command:

`--noresources, -r`
`...Do not add default Ionic icons and splash screen resources (corresponds to add)`

**Comment by janpio** [comment]
> And the CLI will not allow us to run the command `ionic cordova resources`

Why? Do you get an error message here?

**Comment by dwieeb** [comment]
The fix for this will be to detect `resources/ios/` or `resources/android/` and _not_ replace the contents of the directory if it exists, correct?

If so, I just pushed a fix.
