### ISSUE TITLE
CLI v3 custom flags not passed to ionic cordova command

### ISSUE THREAD

**Issue by dusted** [ionic-team/ionic-cli#2646]
**Description:**
After upgrading ionic from 2.0.0-rc-5 to 3.6.0 my custom rollup config has stop receiving my custom flag when i build to a platform. It does works for ionic serve and ionic build command.

before v2.0.0-rc5 (worked)
```
ionic build ios --production
```

after (v3.6.0)
```
ionic build --production
# console logs
Running app-scripts build: --production

ionic cordova build ios --production
# console logs
Running app-scripts build: --address 0.0.0.0 --port 8100 --p 8100 --livereload-port 35729 --r 35729 --iscordovaserve --nobrowser
```
**My `ionic info`:**
cli packages: (/Users/riccardo/code/ultimate-earth/app/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.4.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.0.0 ios 4.1.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.1.4
    OS                : OS X Yosemite
    Xcode             : Xcode 7.2.1 Build version 7C1002
    ios-deploy        : 1.9.0
    ios-sim           : 3.1.1
    npm               : 5.3.0

My custom rollup config

```
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');
var replace = require('rollup-plugin-replace');
var argv = require('yargs').argv;
var isProd = false;
if(argv.production){
  console.log('=====> configuring for production');
  isProd = true;
}

// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: process.env.IONIC_APP_ENTRY_POINT,

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: process.env.IONIC_GENERATE_SOURCE_MAP ? true : false,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: process.env.IONIC_OUTPUT_JS_FILE_NAME,

  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    replace({
        exclude: 'node_modules/**',
        // use the /config/environment-dev as the default import(!), no stub needed.
        // note we only replace the "last" part of the import statement so relative paths are maintained
        '/config/env.dev' : ( isProd ? '/config/env.prod' : '/config/env.dev'),
    }),
    builtins(),
    commonjs(),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};



module.exports = rollupConfig;

```

**Comment by dwieeb** [comment]
At the moment we're not passing unknown args onto app-scripts. 

Even though this doesn't _quite_ fit in, I'm gonna link this issue with this one: https://github.com/ionic-team/ionic-cli/issues/2594

We need to have a conversation about our build system before implementing features like this. Most people want a solution for app _environments_.

**Comment by dwieeb** [comment]
Consolidating for https://github.com/ionic-team/ionic-cli/issues/2594
