### ISSUE TITLE
Proxy Plugin is always requested but already installed CLI - 3.8.1

### ISSUE THREAD

**Issue by ataraxus** [ionic-team/ionic-cli#2647]
**Description:**
On Windows 7 we are always asked to install the `cli-plugin-proxy` with ionic-cli@3.6.0 are only asked once the plugin is not installed. somehow it is not detected correctly anymore. 

**Steps to Reproduce:**
Set `HTTPS_PROXY` and do a `ionic serve` or whatever. Type `y` if prompted to install, start over and you will prompted again... 

**Output:**
```
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'C:\\Users\\A\\workspace\\PROJECT\\client\\PROJECT\\trunk', local: true, binPath: 'C:\\Users\\A\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath: 'C:\\Users\\A\\workspace\\PROJECT\\client\\PROJECT\\trunk\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Detected HTTPS_PROXY in environment
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
 
? Detected HTTPS_PROXY in environment, but to proxy CLI requests, you'll need @
ionic/cli-plugin-proxy installed. Install now? (Y/n)
```

**My `ionic info`:**
```
$ ionic info
 
? Detected HTTPS_PROXY in environment, but to proxy CLI requests, you'll need @
√ npm install --save-dev --save-exact @ionic/cli-plugin-proxy@latest - done!
 
cli packages: (C:\Users\A\workspace\PROJECT\client\PROJECT\trunk\node_modules)
 
    @ionic/cli-plugin-proxy : 1.4.3
    @ionic/cli-utils        : 1.8.1
    ionic (Ionic CLI)       : 3.8.1
 
global packages:
 
    Cordova CLI : 7.0.1
 
local packages:
 
    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.2.0
 
System:
 
    Node : v6.11.2
    npm  : 5.3.0
    OS   : Windows 7
```

**Comment by dwieeb** [comment]
Darn, this bug snuck in during the plugins refactor. This will be fixed for 3.9.1.

Thanks for reporting the issue!

**Comment by ataraxus** [comment]
@dwieeb, thanks for fixing this one so fast! Is there a chance to get this one in a minor release, like 3.8.2? since we are forced in a corporate environment, this bug has a big impact on our dev and build workflows. if not any guess when 3.9.1 will be released?

**Comment by dwieeb** [comment]
@ataraxus I am working on a 3.9.1 release right now.

**Comment by ataraxus** [comment]
@dwieeb great news! Thanks for your reply and keep up the good work 👌
