### ISSUE TITLE
Cordova Run command changing config.xml

### ISSUE THREAD

**Issue by iget-master** [ionic-team/ionic-cli#2650]
**Description:**
We're working on a project with multiple developers. `config.xml` file is included on git.
The problem is that every dev have it own IP, for obvious reasons, right?

Everytime that `ionic cordova run` command is called, it changes the `config.xml` from

    <content original-src="index.html" src="http://192.168.2.X:8100" />

to

    <content original-src="index.html" src="http://192.168.2.Y:8100" />

This causes conflicts everytime on this file. 

The question is: **Shouldn't this file remains untouched?**

**Steps to Reproduce:**

Run `ionic cordova run --device -l`

**My `ionic info`:**
```
cli packages: (/home/***/ionic/node_modules)

    @ionic/cli-utils  : 1.9.0
    ionic (Ionic CLI) : 3.9.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 3.10.10 
    OS                : Linux 4.4
```

**Comment by dwieeb** [comment]
Well, we _must_ modify the file for livereload to work.

If you're referring to how it _leaves the file modified_ (does not undo that change after ctrl-c of Cordova run/emulate command), then this is a duplicate of https://github.com/ionic-team/ionic-cli/issues/2556

**Comment by iget-master** [comment]
Thanks @dwieeb, I'm pretty new on Ionic and cordova, so I don't understand how exaclty things work.
If it's necessary, then it may be undo as said on #2556.

**Comment by dwieeb** [comment]
@iget-master No worries. I agree. It must be undone. For what it's worth, running a different `ionic cordova` command (such as `ionic cordova prepare`) will undo it. But it should be undone when the process receives a ctrl-c event.
