### ISSUE TITLE
ionic cordova resources --force flag not working

### ISSUE THREAD

**Issue by kyleboucherlancom** [ionic-team/ionic-cli#2651]
As per the documents https://ionicframework.com/docs/cli/cordova/resources/ we should be able to pass --force flag for it ignore source images being unchanged.

> By default, this command will not regenerate resources whose source image has not changed. To disable this functionality and always overwrite generated images, use --force.

However, when running ```ionic cordova resources --force``` I still get the message 
>  [OK] No need to regenerate images--source files unchanged.

Steps to reproduce:

    ionic start blank blank
    cd blank
    ionic cordova resources
    ionic cordova resources --force <- no new images, source unchanged
    ionic cordova resources -f <- no new images, source unchanged

**Comment by dwieeb** [comment]
Thanks @kyleboucherlancom, I didn't actually mean to show that option yet! I will implement the functionality for the next release.

**Comment by dwieeb** [comment]
@kyleboucherlancom Current workaround: you can delete those `.md5` files in `resources/`.
