### ISSUE TITLE
ionic generate page broken

### ISSUE THREAD

**Issue by molinadavid** [ionic-team/ionic-cli#2652]
**Description:**
I updated the ionic in my project to 3.9.1, since then if I run the command
`ionic generate page wb1133 --no-module`
I get the module file anyway, and the generated page is as follows.

    import { Component } from '@angular/core';
    $IMPORTSTATEMENT
    
    /**
     * Generated class for the Wb1133Page page.
     *
     * See http://ionicframework.com/docs/components/#navigation for more info
     * on Ionic pages and navigation.
     */
    $IONICPAGE
    @Component({
      selector: 'page-wb1133',
      templateUrl: 'wb1133.html',
    })
    export class Wb1133Page {
    
      constructor(public navCtrl: NavController, public navParams: NavParams) {
      }
    
      ionViewDidLoad() {
        console.log('ionViewDidLoad Wb1133Page');
      }

**Steps to Reproduce:**
1. Use the command `ionic generate page wb1133 --no-module`

**Output:**
There are no errors, the folder is created with the name wb1133, inside the folder there are 4 files
- wb1133.html
- wb1133.module.ts (should not be generated)
- wb1133.scss
- wb1133.ts (contain the wrong header from the template I suppose)

**My `ionic info`:**
cli packages: (/home/{user}/Repositories/{package name}/node_modules)

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.6
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.1.2
    npm  : 5.3.0
    OS   : Linux 4.4

**Comment by dwieeb** [comment]
Please upgrade your `@ionic/app-scripts`, it is very out of date.
