### ISSUE TITLE
shell.js: internal error; Error: ENOENT: no such file or directory, lstat; '/Volumes/X/project/platforms/browser/www/views/._.DS_Store'

### ISSUE THREAD

**Issue by campbeln** [ionic-team/ionic-cli#2653]
When attempting to `sudo ionic cordova platform add browser` and subsequently `build`, I get errors associated with missing `/._.DS_Store` files (in my case, in a rotating batch of 6 different locations!?!).

I'm guessing there is some manifest file somewhere that was filled some time ago when these files existed and now that they have been removed it's crapping out. I try `touch`ing these files but the errors do not go away.

I am on the latest version of everything (`npm update -g`ed and everything) running on macOS 10.12.6.

Here's some output:

x@y:/opt/mobile-new$ sudo ionic cordova build browser
✖ cordova platform add browser --save - failed!
[ERROR] Exception: Adding browser project...

        Running command: /Users/admin/.cordova/lib/npm_cache/cordova-browser/4.1.0/package/bin/create 
        /Volumes/Z/opt/mobile-new/platforms/browser com.ionicframework.mobile995803 Zmobile
        Creating Browser project. Path: platforms/browser
        Installing "cordova-plugin-console" for browser
        Installing "cordova-plugin-device" for browser
        Installing "cordova-plugin-inappbrowser" for browser
        Installing "cordova-plugin-splashscreen" for browser
        Installing "cordova-plugin-statusbar" for browser
        Installing "cordova-plugin-whitelist" for browser
        Installing "cordova-plugin-whois" for browser
        Installing "ionic-plugin-deeplinks" for browser
        Installing "ionic-plugin-keyboard" for browser
        shell.js: internal error
        Error: ENOENT: no such file or directory, lstat 
        '/Volumes/Z/opt/mobile-new/platforms/browser/www/img/._.DS_Store'
             at Error (native)
             at Object.fs.lstatSync (fs.js:994:11)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:20:23)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:141:7
             at Array.forEach (native)
             at Object._rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:105:9)
             at Object.rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
             at browser_parser.update_www 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/metadata/browser_parser.js:76:11)
             at PlatformApiPoly.prepare 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:202:18)
        
x@y:/opt/mobile-new$ sudo ionic cordova platform remove browser
✖ cordova platform remove browser --save - failed!
[ERROR] An error occurred while running cordova platform remove browser --save (exit code 1):

        
        shell.js: internal error
        Error: ENOENT: no such file or directory, lstat 
        '/Volumes/Z/opt/mobile-new/platforms/browser/www/js/._.DS_Store'
             at Error (native)
             at Object.fs.lstatSync (fs.js:994:11)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:20:23)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:141:7
             at Array.forEach (native)
             at Object._rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:105:9)
             at Object.rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform.js:376:19
        
x@y:/opt/mobile-new$ sudo ionic cordova platform remove browser
✖ cordova platform remove browser --save - failed!
[ERROR] An error occurred while running cordova platform remove browser --save (exit code 1):

        
        shell.js: internal error
        Error: ENOENT: no such file or directory, lstat 
        '/Volumes/Z/opt/mobile-new/platforms/browser/www/js/full/._.DS_Store'
             at Error (native)
             at Object.fs.lstatSync (fs.js:994:11)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:20:23)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:141:7
             at Array.forEach (native)
             at Object._rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:105:9)
             at Object.rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
        
x@y:/opt/mobile-new$ sudo ionic cordova platform remove browser
✖ cordova platform remove browser --save - failed!
[ERROR] An error occurred while running cordova platform remove browser --save (exit code 1):

        
        shell.js: internal error
        Error: ENOENT: no such file or directory, lstat 
        '/Volumes/Z/opt/mobile-new/platforms/browser/www/lib/._.DS_Store'
             at Error (native)
             at Object.fs.lstatSync (fs.js:994:11)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:20:23)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:141:7
             at Array.forEach (native)
             at Object._rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:105:9)
             at Object.rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform.js:376:19
        
x@y:/opt/mobile-new$ sudo ionic cordova platform remove browser
✖ cordova platform remove browser --save - failed!
[ERROR] An error occurred while running cordova platform remove browser --save (exit code 1):

        
        shell.js: internal error
        Error: ENOENT: no such file or directory, lstat 
        '/Volumes/Z/opt/mobile-new/platforms/browser/www/lib/pdfjs/._.DS_Store'
             at Error (native)
             at Object.fs.lstatSync (fs.js:994:11)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:20:23)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:141:7
             at Array.forEach (native)
             at Object._rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:105:9)
             at Object.rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
        
x@y:/opt/mobile-new$ sudo ionic cordova platform remove browser
✖ cordova platform remove browser --save - failed!
[ERROR] An error occurred while running cordova platform remove browser --save (exit code 1):

        
        shell.js: internal error
        Error: ENOENT: no such file or directory, lstat 
        '/Volumes/Z/opt/mobile-new/platforms/browser/www/views/._.DS_Store'
             at Error (native)
             at Object.fs.lstatSync (fs.js:994:11)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:20:23)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at rmdirSyncRecursive 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:23:7)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:141:7
             at Array.forEach (native)
             at Object._rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/rm.js:105:9)
             at Object.rm 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform.js:376:19
        
x@y:/opt/mobile-new$ sudo ionic cordova platform remove browser
✔ cordova platform remove browser --save - done!
Removing platform browser from config.xml file...
x@y:/opt/mobile-new$

**Comment by dwieeb** [comment]
@campbeln Whoops, didn't necessarily mean to do that.

This looks like an issue between the Ionic CLI and the Cordova browser platform. See https://github.com/ionic-team/ionic-cli/issues/2312 for the status of that.
