### ISSUE TITLE
Live reload broken on iOS device (trying to connect to 127.0.0.1)

### ISSUE THREAD

**Issue by sachingarg05** [ionic-team/ionic-cli#2655]
Live reload does not work with iOS devices and stops with the log below.

Note that it is trying to connect to 127.0.0.1 even when on device which is bound to fail, it should be connecting to the actual IP of dev machine.

`(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:50629"`

Also note that it says `Connected: no` which might be the reason for all this.

Possibly related to https://github.com/ionic-team/ionic-cli/issues/2645 where details of target and platform etc were not getting passed on?

```
(lldb)     platform select remote-ios --sysroot '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/10.3 (14E269)/Symbols'
  Platform: remote-ios
 Connected: no
  SDK Path: "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/10.3 (14E269)/Symbols"
(lldb)     target create "/Users/user/Data/rwz_fixphoto_ion/platforms/ios/build/device/FixPhotoIon.app"
Current executable set to '/Users/user/Data/rwz_fixphoto_ion/platforms/ios/build/device/FixPhotoIon.app' (arm64).
(lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/640E01D0-129F-4726-8CCD-B2112386D389/FixPhotoIon.app"
(lldb)     script fruitstrap_connect_url="connect://127.0.0.1:50629"
(lldb)     command script import "/tmp/96119E05-B19E-49C1-9CB5-345AFC4D6496/fruitstrap_8de4fd22ccebb1e193c059548d640c0fb6366a14.py"
(lldb)     command script add -f fruitstrap_8de4fd22ccebb1e193c059548d640c0fb6366a14.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_8de4fd22ccebb1e193c059548d640c0fb6366a14.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_8de4fd22ccebb1e193c059548d640c0fb6366a14.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_8de4fd22ccebb1e193c059548d640c0fb6366a14.safequit_command safequit
(lldb)     connect
(lldb)     run
success
(lldb)     safequit
Process 297 detached

```

**My `ionic info`:**
```
cli packages:

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.3
    ios-deploy        : 1.9.1
    ios-sim           : 5.1.0
    Node              : v6.11.2
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.2 Build version 8E2002

```

**Comment by sachingarg05** [comment]
Fails both when using ionic wkwebview plugin, and without the ionic wkwebview plugin.

**Comment by sachingarg05** [comment]
Fails with CLI updates to latest:

```
cli packages:

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.3
    ios-deploy        : 1.9.1
    ios-sim           : 5.1.0
    Node              : v6.11.2
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.2 Build version 8E2002
```

**Comment by dwieeb** [comment]
If I'm going to help, I definitely need more info. I have no idea what fruitstrap is or how it relates to the Ionic CLI.

What command did you run, exactly?

**Comment by sachingarg05** [comment]
`ionic cordova run ios --prod -l`
  and
`ionic cordova run ios --prod -lcs`

We are not trying to use anything outside of what ionic does by itself, and we are not using npm/node for anything besides ionic/cordova development. So it is unlikely we have any extras installed which might be interfering. Maybe these are internal to ios-deploy or ios-webkit-debug-proxy etc...

**Comment by sachingarg05** [comment]
Seems to be fixed after updating ios-deploy and ios-webkit-debug-proxy. Don't know which one was causing it to fail.

npm -g update
brew upgrade ios-webkit-debug-proxy

**Comment by dwieeb** [comment]
fruitstrap is apparently some internal thing ios-deploy uses. 

Cordova is very complicated, my apologies. I hadn't heard of `ios-webkit-debug-proxy` either! 😂 

Sometimes with these weird issues it might be better to use the forum because it's likely someone has seen it before and knows what to do, whereas I'm just the CLI developer.

Glad you found the solution!
