### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT ....... livereload.js

### ISSUE THREAD

**Issue by harariyasanjay** [ionic-team/ionic-cli#2657]
After upgrading 3.8.1 liverelaod has just gone offline.......
when i run ionic serve it is able load page on browser but with lagging... 
any change in the code will not initiate livereload....I have to manually refresh the page everytime and get the same error over and again .
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT 

Created new apps with ionic1 but still got the same problems with new apps as well

```
Desktop\Main\eg1>ionic serve
[INFO] Starting server (address: 0.0.0.0, port: 8100, livereload port: 35729) - Ctrl+C to cancel
[INFO] Development server running
       Local: http://localhost:8100
       External: http://10.31.36.29:8100

<script src="//10.31.36.29:35729/livereload.js?snipver=1" async="" defer=""></script>
```

`http://localhost:35729/livereload.js?snipver=1` is reachable 
`http://10.31.36.29::35729/livereload.js?snipver=1` is not reachable 

**My `ionic info`:**
```
@ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    Cordova Platforms : android 6.2.3 ios 4.4.0
    Ionic Framework   : ionic1 1.3.3

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.0
    npm               : 3.10.10
    OS                : Windows 10
```

**Comment by dwieeb** [comment]
Thanks for the report, @harariyasanjay 

This won't be an issue for most people, but for some reason your computer doesn't loop back to "10.31.36.29". This will be fixed in 3.9.2, we'll just use "localhost" for serve.
