### ISSUE TITLE
--livereload disables --prod. (Bug or as-designed?)

### ISSUE THREAD

**Issue by sachingarg05** [ionic-team/ionic-cli#2659]
--livereload disables --prod. (Bug or as-designed?)

Doing `--prod` starts a prod build.
> ionic cordova run ios `--prod`
> Running app-scripts build: --prod
> 
> [16:00:57]  build `prod` started ...
> [16:00:57]  clean started ...
> [16:00:57]  clean finished in 3 ms
> [16:00:57]  copy started ...
> [16:00:57]  ngc started ...

But doing `--prod -l` starts a dev build.
> ionic cordova run ios `--prod -l`
> [INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --nobrowser --iscordovaserve -
>        Ctrl+C to cancel
> [16:01:20]  watch started ...
> [16:01:20]  build `dev` started ...
> [16:01:20]  clean started ...
> [16:01:20]  clean finished in 1 ms
> [16:01:20]  copy started ...
> [16:01:20]  transpile started ...

**My `ionic info`:**
```
cli packages:

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.3
    ios-deploy        : 1.9.1
    ios-sim           : 5.1.0
    Node              : v6.11.2
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.2 Build version 8E2002
```

**Comment by dwieeb** [comment]
Hi @sachingarg05, this can be answered by this comment here: https://github.com/ionic-team/ionic-cli/issues/2636#issuecomment-322504096

Thanks!
