### ISSUE TITLE
Live reload does not work with browser platform (starts two servers at port 8000 and 8100)

### ISSUE THREAD

**Issue by sachingarg05** [ionic-team/ionic-cli#2660]
When using this command:
  `ionic cordova run browser -l`

Editing source files initiates the fast rebuild as expected, but does not auto-refresh the page open in browser. Manually refreshing the browser tab does not reflect new code updates.

Surprisingly, the console output says the dev server is running on port 8100, but it opens the browser at port 8000. 

Manually opening http://localhost:8100/index.html also works, as does opening http://localhost:8000/index.html.

After editing source files, a fast rebuild happens as expected but none of the two above tabs get auto refreshed. Manually refreshing the 8100 tab reflects new code changes, manually refreshing the 8000 tab does not reflects new code changes.

Hope this helps.

**My `ionic info`:**
```
cli packages:

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.3
    ios-deploy        : 1.9.1
    ios-sim           : 5.1.0
    Node              : v6.11.2
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.2 Build version 8E2002
```

**Comment by dwieeb** [comment]
We don't officially support the Cordova browser platform yet, really. I am going to merge this issue with this: https://github.com/ionic-team/ionic-cli/issues/2312

**Comment by sachingarg05** [comment]
Then what is the supported way to build and test PWAs?

**Comment by dwieeb** [comment]
@sachingarg05 Ionic is very much a web platform, so just using the current Ionic CLI (without Cordova) and resources like those listed in https://whatwebcando.today can get you quite far. PWA _hosting_ is something we currently don't offer (check back very soon). 

This is more part of a guidance initiative that I hope to have soon. I know we're missing it, there's just been so much going on.

It's coming, trust me!

**Comment by dwieeb** [comment]
@sachingarg05 https://github.com/ionic-team/ionic-cli/issues/2664
