### ISSUE TITLE
adding platform android does not generate proper resources

### ISSUE THREAD

**Issue by mluis** [ionic-team/ionic-cli#2665]
**Description:**
Adding android platform after ios being added the resources are not generated correcly.

**Steps to Reproduce:**

`ionic --verbose cordova platform add android -- --debug --stacktrace`
**Output:**

```
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: '/Users/mluis/Documents/**SNIP**', local: true, binPath: 
        '/Users/mluis/.nvm/versions/node/v6.9.2/lib/node_modules/ionic/bin/ionic', libPath: 
        '/Users/mluis/Documents/**SNIP**/node_modules/ionic/dist/index.js' }
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] PLUGIN_INVALID: local @ionic/cli-plugin-proxy
[DEBUG] Daemon found (pid: 94763)
> cordova platform add android --save
✔ Running command - done!
✔ Copying default resources to project - done!
```
**My `ionic info`:**

```
[WARN] Error with ./www/lib/ionic/version.json file: FILE_NOT_FOUND, trying ./bower.json.

cli packages: (/Users/mluis/Documents/**SNIP**/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    Cordova Platforms : android 6.2.3 ios 4.4.0
    Ionic Framework   : ionic1 1.1.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    Node              : v6.9.2
    npm               : 3.10.9 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
```

**Other Information:**
The generated resources have the default ionic image instead of the app's custom icon.png splash.png .

**Comment by mluis** [comment]
After adding the platform, performing a r`m -rf resources/android `and then `ionic cordova resources android` solves this issue.

**Comment by dwieeb** [comment]
@mluis I just fixed this on `master`. Would you mind testing? You can install the alpha CLI with `npm i -g ionic@canary`

**Comment by mluis** [comment]
@dwieeb nice fix! I'm away from the computer until next week. I'll get back to you after then :)

**Comment by DevNIX** [comment]
I am experimenting a similar issue.

Logically, if I try to add the required resources without having android added as a platform, I get this from `ionic cordova resources`:

```
✔ Collecting resource configuration and source images - done!
[ERROR] No platforms detected. Please run: ionic cordova platform add
```

If I want to add the platform, ionic gives me this output:

```
> cordova platform add android --save
Using cordova-fetch for cordova-android@~6.3.0

Adding android project...

Creating Cordova project for the Android platform:
	Path: platforms/android

	Package: com.xxxxxxxxxxxxxxxx.xxx

	Name: XXXXXX
	Activity: MainActivity
	Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.3.0

Error: Source path does not exist: resources/android/icon/drawable-hdpi-icon.png

[ERROR] Exception:
```

After this error, I can run `ionic cordova resources`, and then I can finally do `ionic cordova platform rm android && ionic cordova platform add android`.

I've tried with ionic 1.19. This is my environment:

```
cli packages: (/Users/xxx/project/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.3.0
    Ionic Framework   : ionic1 1.3.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 5.1.0
    Node              : v7.0.0
    npm               : 4.1.2
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : /usr/local/Cellar/android-sdk/24.4/

Misc:

    backend : legacy
```

**Comment by dwieeb** [comment]
@DevNIX Thanks for posting!

The error `Source path does not exist: resources/android/icon/drawable-hdpi-icon.png` directly comes from an entry for `resources/android/icon/drawable-hdpi-icon.png` in the `config.xml` file but a missing asset at that location. 

When Ionic Cordova apps are created, we pair the resource entries in `config.xml` with a matching set of pre-generated icons and splash screens. We could probably do more for devs in the form of informational messages when the pair no longer match, for whatever reason. I've definitely seen it happen before.

**Comment by DevNIX** [comment]
Wow. I will have to remove every line of the Android assets if I have to remove and add the platform?

**Comment by jimitpatel** [comment]
@mluis Can you explain it? It worked for me, I have started ionic for the first time today.
