### ISSUE TITLE
Popover location changes if app is opened horizontally vs vertically on a horizontal page.

### ISSUE THREAD

**Issue by paqogomez** [ionic-team/ionic-cli#2666]
**Description:**
The issue is based on the direction of the device when the app is opened. 

If the app is opened up and the device is horizontal, then when going to the page that is locked in landscape, the popover is centered just fine. 

If the app is opened and the device is vertical, forcing the window to flip horizontal when the landscaped page is opened, then the window appears off center and low.

**Steps to Reproduce:**

Popover code: 
    
    let popover = this.popoverCtrl.create(ImageSigPopOverPage, {
      carriage: this.carriage,
      callback: data => {
        this.log.debug('message', 'In the callback for popover. The data returned: ', data);
        this.signaturePad.fromDataURL(img);
        this._generateSignatureObject(data.title, img, data.autoDispatch);
      }
    }, {showBackdrop: true, enableBackdropDismiss: true, cssClass: "signature--popover"});

In the constructor:
   
    _platform.ready().then(() => {
      screenOrientation.lock('landscape');
    });

**My `ionic info`:**

Ionic 2.2.3
Cordova 6.5.0

**Other Information:**

Stackoverflow question: https://stackoverflow.com/q/45744914/2589202

**Comment by janpio** [comment]
This doesn't really sound like a Ionic CLI problem. Are you in the correct repository?

**Comment by paqogomez** [comment]
I'm probably not.  Could you help point the way?

**Comment by janpio** [comment]
https://github.com/ionic or even the community forum: https://forum.ionicframework.com/
