### ISSUE TITLE
--release only android app apk is corrupted on Android 7.x.x

### ISSUE THREAD

**Issue by parveshhc** [ionic-team/ionic-cli#2667]
**Description:**

--release only android app apk is corrupted on Android 7.x.x
Debug build works fine but Release build say apk is corrupted only on Android 7.1.1

**Steps to Reproduce:**

start new ionic latest project.
cd into the folder, don't change any code
$ ionic cordova platform add android
$ ionic cordova build android --prod --release
the apk produced is corrupted. on Android 7.1.1

Example repo: 

1.
2.
3.

**Output:**

the apk produced is corrupted. on Android 7.1.1

**My `ionic info`:**

cli packages: (/Users/parvgarg/Cisco/Projects/ReleaseHub/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    Node              : v6.11.2
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

**Other Information:**

**Comment by janpio** [comment]
Does it work on other Android versions?
What device are you running Android 7.1.1 on?

You are running an older version of `@ionic/app-scripts`. Maybe try upgrading this.
Did you try this with a newly started project as you wrote in the repro steps? If so, could you please post the `ionic info` of that project please?

**Comment by parveshhc** [comment]
Thanks for your support. It works now with updating @ionic/app-scripts.
But zipalign is not working. If I do zip align with below command then again I get same app corrupted error. Please suggest.
zipalign -v 4 android-release.apk android-release-aligned.apk

My app ionic info:

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    Node              : v6.11.2
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

**Comment by janpio** [comment]
Ionic/Cordova can do that for you automatically:

`ionic cordova build android --prod --release -- -- --keystore=PATH--alias=ALIAS`

This prompts for the passwords and gives you a perfect APK.

**Comment by parveshhc** [comment]
Ok thanks for your support. I appreciate. This resolves my issue.

**Comment by dwieeb** [comment]
Alternatively you can use a `build.json` file: https://cordova.apache.org/docs/en/latest/guide/platforms/android/#using-buildjson

**Comment by jaigtz88** [comment]
hi Janpio, i have same problem when do the zipalign. itcorrupted..it work on android version 4 but not on version 7. Any idea?
