### ISSUE TITLE
With ng-model-option, ng-click fires before model update

### ISSUE THREAD

**Issue by potatopeelings** [ionic-team/ionic-cli#2668]
**Description:**
If I have a field with `ng-model-options={ updateOn; 'blur' }`, updating this field and then clicking a button runs the button's ng-click **before** the model is updated.

This happens only on Ionic. On a web page with the same code, Angular runs the button's ng-click **after** the model is updated.

**Example code:** 

`ionic start myApp tabs`

**tab-dash.html**
```
<ion-view view-title="Dashboard">
  <ion-content class="padding">
    <div class="list">
      <div class="item item-input-inset">
        <label class="item-input-wrapper">
          <input type="text" ng-model="model.myValue" ng-model-options="{ updateOn: 'blur' }" >
        </label>
        <button class="button" ng-click="showMyValue()">Show Value</button>
      </div>
    </div>
  </ion-content>
</ion-view>
```

**controllers.js**
```
...
.controller('DashCtrl', function($scope) {
  $scope.model = {
    myValue: 10
  }
  $scope.showMyValue = function() {
    alert($scope.model.myValue);
  }
})
...
```

**Steps to Reproduce:**
1. Update the textbox to 102
2. Click the button

**Output:**
Expected: 102
Actual: 10

**My `ionic info`:**
```
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Gulp CLI : CLI version 3.9.1 Local version 3.9.1

local packages:

    Ionic Framework : ionic1 1.3.3

System:

    Node : v6.9.5
    npm  : 3.10.8
    OS   : Windows 7

```

**Comment by janpio** [comment]
This doesn't really sound like a Ionic CLI problem. Did you post it in the correct repository?
Maybe try posting this at the community forum: https://forum.ionicframework.com/

**Comment by potatopeelings** [comment]
Sorry! I'm not sure how I ended up in CLI. I could have sworn I navigated to the ionic-v1 repository.
