### ISSUE TITLE
ionic cordova run android -l    cordova_not_available

### ISSUE THREAD

**Issue by JLBear** [ionic-team/ionic-cli#2669]
why cordova_not_available when use cordova run android -l in my ionic3 project
but when use cordova run android,cordova is availabl;
i want to debugging my ionic3 project on --liveload and cordova is available;
how can i do

ionic info
ionic/cli-utils  : 1.8.0
ionic (Ionic CLI) : 3.8.0
global packages:

Cordova CLI : 7.0.1
local packages:

ionic/app-scripts : 1.3.12
Cordova Platforms  : none
Ionic Framework    : ionic-angular 3.5.0
System:

Android SDK Tools : 25.2.3
Node              : v6.11.1
npm               : 3.10.10
OS                : Windows 10

**Comment by janpio** [comment]
Did you already post on the forum?
