### ISSUE TITLE
CORDOVA NOT SHOWED IN IONIC INFO 

### ISSUE THREAD

**Issue by MM-Furkan** [ionic-team/ionic-cli#2673]
Hi..
I am new to Cordova..
when i try to install Cordova by Following the Video https://youtu.be/geuW_BjR9hE i am getting an error that is my ionic.info file not showing cordova see the image of may terminal..
![screenshot from 2017-08-19 16-31-32](https://user-images.githubusercontent.com/31157611/29486354-693d4eb0-84d3-11e7-862c-9f4a2b2027f9.png)

an another on is also 
![screenshot from 2017-08-19 16-34-44](https://user-images.githubusercontent.com/31157611/29486360-740bfbb6-84d3-11e7-9cb0-71420356abe7.png)

i have install cordova latest version..

Can anyone help me plzzzzzzz....
its great thnx to him...

**Comment by janpio** [comment]
This is not an issue with Ionic CLI.

Please create a topic at the Ionic community forum: https://forum.ionicframework.com/
