### ISSUE TITLE
A problem occurred configuring root project 'android'.

### ISSUE THREAD

**Issue by jadeye** [ionic-team/ionic-cli#2674]
/usr/local/bin/cordova run --target=23a611a9 android --debug
ANDROID_HOME=/opt/android-sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_6gn0nn5raq2dj2zo0qm7tnuqs.run(/home/jadeye/cordova/hello/platforms/android/build.gradle:137)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.074 secs
Error: /home/jadeye/cordova/hello/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**OS**
Ubuntu 14.04
WebStorm 2017.2.2
Cordova 7.0.1

**Comment by quauhtlimtz** [comment]
Any response? I have the same issue.

**Comment by kojinanjo** [comment]
I've the same problem

**Comment by lucasprogamer** [comment]
i have the same problem. any thing?

**Comment by dwieeb** [comment]
I've gotten this before and usually updating my Android SDK, Cordova, and Cordova Android fixes it. (and `ionic cordova platform rm android`, `ionic cordova platform add android`)

**Comment by lucasprogamer** [comment]
I'm install android with homebrew and this fix the problem.

**Comment by MishraUdit** [comment]
move to the path: `yourProjectName\android\` and run the command `gradlew`. This will help you to figure out what's the issue exactly.

**Comment by ShahHussainBangash** [comment]
I have the same issues.
