### ISSUE TITLE
ionic package doesn't work with deeplinking

### ISSUE THREAD

**Issue by Blackscr33n** [ionic-team/ionic-cli#2676]
**Description:**

Deeplinking does work with Xcode
but doesn't work with ionic package 

**Steps to Reproduce:**
Setup an app like described here: http://blog.ionic.io/deeplinking-in-ionic-apps/
+ setup ionic package described here: https://docs.ionic.io/services/package/

**My `ionic info`:**
`cli packages: (/Users/bernhardmiehl/Development/ionic/SelfServiceMobile/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.5.0 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.3.0

System:

    ios-deploy : 1.9.1 
    Node       : v6.11.0
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b `

**Other Information:**

Maybe the solution could be a custom-hook, which adds on ios the 'Associated Domains' Capabilities to the project with the host given in config.xml or something like this way?

Greets

**Comment by dwieeb** [comment]
@Blackscr33n Closing this as it's pretty stale. Sorry I didn't get around to offering help. We have a support team for Ionic Pro (which has a "package" feature like Ionic Package), so I'm sure they'll be more responsive if this is still an issue. Thanks!
