### ISSUE TITLE
ionic build ios command prepares windows and android platform also

### ISSUE THREAD

**Issue by jayeshanandani** [ionic-team/ionic-cli#2677]
**Description:**

When I run ionic cordova build ios --prod it prepares all 3 platforms which was not the behavior earlier.

**Comment by dwieeb** [comment]
@jayeshanandani Not seeing this behavior. Also, please post your `ionic info`.

**Comment by jayeshanandani** [comment]
@dwieeb:

If I clean entire platform directory and remove plugin directory and try to run `ionic build ios --prod`, for some reasons it prepares all platforms for which I have resources tag. Pardon me in my issue text earlier.
```
cli packages: (/Users/jayesh/www/test)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 ios 4.2.0 windows 4.4.2
    Ionic Framework    : ionic-angular 3.5.3

System:

    ios-deploy : 1.9.0
    ios-sim    : 5.0.12
    Node       : v6.10.3
    npm        : 5.3.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
```

**Comment by dwieeb** [comment]
Do you mean `ionic cordova build ios --prod`?

**Comment by jayeshanandani** [comment]
Yes I mean `ionic cordova build ios --prod`

**Comment by dwieeb** [comment]
Does this break something, or is it just an annoyance?

**Comment by jayeshanandani** [comment]
@dwieeb : It doesn't breaks anything but it is annoying as it takes longer time as it goes to prepare all platforms unnecessarily :)

It can be very low priority.

**Comment by dwieeb** [comment]
Okay, thanks! The reason it does this is because `ionic cordova build <platform>` invokes an `ionic build`, which runs `cordova prepare` by default, not knowing about the target platform.

**Comment by jayeshanandani** [comment]
thanks for that information. any workaround that can be used (if any)? :)

**Comment by dwieeb** [comment]
@jayeshanandani Once the platforms are prepared, `cordova prepare` should have very little to do. How long does a `cordova prepare` invocation take?  

Run: `time cordova prepare` and post the output

**Comment by jayeshanandani** [comment]
@dwieeb I will try that tonight and let you know with timings.

**Comment by dwieeb** [comment]
`cordova prepare` will no longer run after `ionic build`

Please try the CLI RC to see if this issue is resolved: `npm i -g ionic@rc`

Closing this for now. I don't think it's an issue anymore. If I'm mistaken, please feel free to make a new issue. Thanks!
