### ISSUE TITLE
Ionic Serve Error

### ISSUE THREAD

**Issue by zindelluib** [ionic-team/ionic-cli#2680]
I use Ionic CLI version 3.8.1 and the error message appears:

**Error: It appears that you do not have any external network interfaces. In order to use livereload with emulate you will need one.**

Is that a bug?

**Comment by dwieeb** [comment]
@zindelluib Please fill out the issue template.

Can you also post the output of this:

```javascript
const os = require('os');
console.log(os.networkInterfaces());
```
