### ISSUE TITLE
Update local cli to 3.9.2, but it should remove the package not update

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-cli#2682]
**Description:**
We upgraded to global ionic cli 3.9.2 and launched our app using ionic serve where we get this output

```
ionic serve

? The Ionic CLI (local version) has an update available (3.8.1 => 3.9.2)! Would you like to install it? Yes
✔ npm install --save-dev --save-exact ionic@latest - done!

[OK] Updated Ionic CLI to 3.9.2! 🎉

Please re-run your command.

Note: You can downgrade to your old version by running: npm install --save --save-exact ionic@3.8.1
```

In package.json we had old ionic dependency, so the update process updated the dependencies, but as we know from 3.8.x or 3.9.x the local ionic package was removed right? So in this case if you install with global ionic in version 3.9.x it should remove the dependency from package.json and not install a higher version.
right?

**Comment by dwieeb** [comment]
Some people want/need the local CLI installed. It works globally or locally. You can uninstall it locally if you want, but we can't do that for you.
