### ISSUE TITLE
Sorry! The configured backend (pro) does not know about ionic upload.

### ISSUE THREAD

**Issue by HugoHeneault** [ionic-team/ionic-cli#2689]
**Description:**
I'm not able to upload a build to my pro deploy instance.

**Steps to Reproduce:**
1. Login to your account with the ionic CLI : `ionic login`
2. Add your SSH key
3. Run `ionic upload --note="Test Deploy"`
4. 💥 

**Output:**
```
ionic upload --note="Test Deploy" 

[ERROR] Sorry! The configured backend (pro) does not know about ionic upload.
```

**My `ionic info`:**
```
cli packages: (/Users/hugo/dev/ourco/mobile/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0 ios_bk 4.4.0
    Ionic Framework    : ionic-angular 3.4.2-201707210037

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1
    Node              : v7.10.1
    npm               : 4.2.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
```

**Comment by MBALOTA** [comment]
Same here:

**Output:**

```
ionic upload

[ERROR] Sorry! The configured backend (pro) does not know about ionic upload.
```

**My ionic info:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 
    Gulp CLI    : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.2.3
    Ionic Framework   : ionic1 1.3.3

System:

    Node  : v6.11.2
    npm   : 3.10.10 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by srphpprogrammer** [comment]
@monkeytronics @HugoHeneault @MBALOTA 
I'm also having this issue. Didi you guys solve it?

**Comment by HugoHeneault** [comment]
No, we ended up only using git for now... :(

**Comment by ngware** [comment]
Same here, try to run the command : 

> ionic config set -g backend

  but I get this error : 

> nicolas$ ionic config set -g backend
> [ERROR] value must not be empty.

**Comment by ngware** [comment]
Ok so I found out a solution, type : 

> ionic config set -g backend legacy

to get back to the cloud backend and be able to use the ionic upload command. If you want to go back to the pro version just type : 

> ionic config -set backend pro

**Comment by HugoHeneault** [comment]
The problem is the accounts created on the pro backend don't work on the legacy one.

**Comment by srphpprogrammer** [comment]
@HugoHeneault 
`No, we ended up only using git for now... :(`

This is my first time using Ionic Pro. I followed docs but I'm still stuck with error.
How were you able to upload your code to the Ionic Pro?
Push from git-hub to Ionic Pro? It'll be really helpful if you could explain the steps to deploy it to ionic cloud?

**Comment by patwaswapnil** [comment]
That is something I didn't like personally. :(

Now doing this force me to either get a paid private repository or make my code public on GitHub.

The Ionic team should have kept the `upload` service until 31 Jan.

**Comment by HugoHeneault** [comment]
@patwaswapnil The upload service is still up but you need to use the old backed. 
You juste have to push to ionic as stated on the pro dashboard: 


### 1. Install the latest Ionic CLI

```
npm install -g ionic@latest
```
### 2. Connect your app to Ionic Pro

#### START A NEW APP
```
ionic start --pro-id 16673d76
cd test
```

#### OR : CONNECT EXISTING APP
```
ionic link --pro-id 16673d76
```

### 3. Push your code up to the dashboard!

```
git push ionic master
```

### 4. Add your own external Repository as the default origin (optional)
```
git remote add origin [YOUR_REPOSITORY_URL]
git push --set-upstream origin master
```

**Comment by dwieeb** [comment]
I think others have summed it up nicely. For Ionic Pro, `ionic upload` is just `git push ionic master`. 

@patwaswapnil 
> Now doing this force me to either get a paid private repository or make my code public on GitHub.
> 
> The Ionic team should have kept the upload service until 31 Jan.

Nope, having the `ionic` git remote doesn't force you to do either of those things. Your code is "pushed" to our servers instead of uploaded. Github has nothing to do with `git push ionic master`.

If you switch the CLI back with the commands @ngware stated, you get `ionic upload` back, but on Jan 31st it won't work anymore.

**Comment by HugoHeneault** [comment]
@dwieeb The problem is some plugins (as Cocoa) doesn't work on your build environment. So uploading a build from our side would fix the problem.

**Comment by dwieeb** [comment]
@HugoHeneault Can you elaborate? This may be a feature request for Ionic Pro.

**Comment by HugoHeneault** [comment]
Sure: we're having issues when pushing a new snapshot using `git push ionic branch` : cocoapods is required for building or app (for the notifications plugin), but not installed on your build environment on Deploy. 
So the build is failing online (working with the `npm run build` fallback, but not completely (APK images won't have the push plugin :()

**Comment by HugoHeneault** [comment]
I can create a separate issue if you want. Here or on the deploy plugin?

**Comment by dwieeb** [comment]
_Deploy_ can't update the APK/IPA on devices. It can only update non-binary files such as web assets. _Package_ is probably what you're referring to, which would require an app store update. 

Package does not yet support cocoapods, but it's a highly requested feature and I'm sure it'll be in soon. 

You may get a more official response from our support page (I don't work on Pro full-time, just the CLI): https://ionic.zendesk.com/hc/en-us/requests/new?ticket_form_id=632048

**Comment by HugoHeneault** [comment]
I already tried the support, which is quite slow. :(
I know, but Deploy is using cordova prepare, which is trying to use cocoapods. 
So if you're build is using cocoapods, you can't create any prod builds on Deploy. :(

**Comment by HugoHeneault** [comment]
I created an issue one https://github.com/ionic-team/ionic-plugin-deploy/issues/138 but the repo does't seem updated for a while... :(

**Comment by patwaswapnil** [comment]
@dwieeb, My bad, I had confused this with PhoneGap build flow, Thank you so much for clarifying it.

**Comment by dwieeb** [comment]
@patwaswapnil No worries!

@HugoHeneault Deploy shouldn't use `cordova prepare` when you do `git push ionic master`. I see it running `npm run build`. What does it do for you?

**Comment by HugoHeneault** [comment]
@dwieeb Well it seems it is doing it while running `app-script build --prod` 

Dunno why, we don't need it :(

```
Running with gitlab-ci-multi-runner 9.1.0 
  on IonicJS Runner 2
Using Shell executor...
Running on ip-
Cloning repository...
Cloning into '/home/gitlab-runner/'...
Checking out #### as develop...
Skipping Git submodules setup
$ fetch-updates
Checking for build process updates...
$ build-app
Fetching build dependencies...
Running: npm install

### truncated log here

npm install succeeded
Detected local install of ionic cli...
Running: ionic build --prod
[ANNOUNCE] Hi! Welcome to CLI 3.9.

           We decided to merge core plugins back into the main ionic CLI package. The @ionic/cli-plugin-ionic-angular, @ionic/cli-plugin-ionic1, @ionic/cli-plugin-cordova, and @ionic/cli-plugin-gulp plugins have all been deprecated and won't be loaded by the CLI anymore. We listened to devs and determined they added unnecessary complexity. You can uninstall them from your project(s).
           
           No functionality was removed and all commands will continue working normally. You may wish to review the CHANGELOG: https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#changelog
           
           Thanks,
           The Ionic Team
           
           
[INFO] Running app-scripts build: --prod
       
[10:53:45]  build prod started ... 
[10:53:45]  clean started ... 
[10:53:45]  clean finished in 1 ms 
[10:53:45]  copy started ... 
[10:53:45]  ngc started ... 
[10:54:02]  ngc finished in 16.51 s 
[10:54:02]  preprocess started ... 
[10:54:02]  deeplinks started ... 
[10:54:04]  deeplinks finished in 2.00 s 
[10:54:04]  optimization started ... 
[10:54:04]  copy finished in 18.87 s 
[10:54:26]  optimization finished in 21.92 s 
[10:54:26]  preprocess finished in 23.93 s 
[10:54:26]  webpack started ... 
[10:56:26]  webpack finished in 120.34 s 
[10:56:26]  sass started ... 
[10:56:26]  uglifyjs started ... 
[10:56:32]  sass finished in 6.58 s 
[10:56:32]  cleancss started ... 
[10:56:37]  cleancss finished in 4.98 s 
[10:57:54]  uglifyjs finished in 87.86 s 
[10:57:54]  postprocess started ... 
[10:57:54]  postprocess finished in 95 ms 
[10:57:54]  lint started ... 
[10:57:54]  build prod finished in 248.94 s 
> ionic cordova prepare
> cordova prepare
[10:58:10]  lint finished in 16.13 s 
```

**Comment by aleksvidak** [comment]
I cannot use legacy backend and upload my application since my account is made on pro backend, does that make sense?
Is there any workaround?

**Comment by HugoHeneault** [comment]
Yeah you have to use git, as I wrote [there](https://github.com/ionic-team/ionic-cli/issues/2689#issuecomment-325339221)  :)

```
ionic link --pro-id YOUR_ID
git push ionic master
```

**Comment by HugoHeneault** [comment]
@dwieeb Any updates about https://github.com/ionic-team/ionic-plugin-deploy/issues/138 ?

**Comment by aleksvidak** [comment]
@HugoHeneault I get:

fatal: 'ionic' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by HugoHeneault** [comment]
@aleksvidak Have you done all that I wrote on https://github.com/ionic-team/ionic-cli/issues/2689#issuecomment-325339221 ?

**Comment by HugoHeneault** [comment]
Your message seems to say that you're not in a git repository... Maybe the linking was wrong, I don't know. But `git push ionic master` is the way of doing `ionic upload` in the pro backend version. 🙂

**Comment by aleksvidak** [comment]
@HugoHeneault I wonder if it has to do with ssh keys.
I am not the owner of the repository I am using in this case.

**Comment by Kapsul-Brice** [comment]
@aleksvidak 
Here's what worked for us : 

```
ionic link --pro-id abc45678
git remote add ionic git@git.ionicjs.com:ORGANIZATION-NAME/app-name.git
git add .
git commit -m "initial commit"
git push ionic master
```

**Comment by joseph-mpo** [comment]
it is not working at all. I tried everything as well but it always returns an error message.

**Comment by aleksvidak** [comment]
@Kapsul-Brice
Thanks, it worked!

**Comment by alltej** [comment]
I am getting error "Permission denied (publickey)." when `git push ionic master`. How can I generate the SSH keys (not the OpenSSH) but like using an existing public key?

**Comment by dwieeb** [comment]
`ionic ssh setup` will give you the choice to use existing keys.

**Comment by timbru31** [comment]
How can I configure the backend type on a per project basis? Our CI has no "global" config, even with `backend: legacy` in the project `ionic.config.json` it does not pickup this config setting.

**Comment by dwieeb** [comment]
@timbru31 If we do that, then devs would need to log in to each app independently. The backends do not share authentication. I'm fine with this being a configurable option, but it would be a feature request.

If you have a mix of Cloud and Pro apps, you could use different global config files for each backend with the `IONIC_CONFIG_DIRECTORY` environment variable: https://github.com/ionic-team/ionic-cli#environment-variables

I apologize for how convoluted this is. The CLI has a unique problem of handling both these backends unlike being able to have two distinct websites (https://apps.ionic.io and https://dashboard.ionicjs.com).

**Comment by ciotrade** [comment]
$ sudo git push ionic master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by dwieeb** [comment]
@ciotrade Please open a new issue and fill out the issue template.

**Comment by femithz** [comment]
having this error after trying to push my work to ionic dashboard : failed to push some refs to 'git@git.ionicjs.com:femith/myapp.git'

**Comment by dwieeb** [comment]
@femithz Please open a new issue and fill out the issue template.

**Comment by mhbt** [comment]
Hey guys I found the way. The problem was `ionic upload` is for legacy account. use `git push ionic <branch>`  for ionic pro
