### ISSUE TITLE
"ionic serve" fails if there are no external network interfaces 

### ISSUE THREAD

**Issue by antoine29** [ionic-team/ionic-cli#2690]
Hi guys
i'm new with developing ionic apps and i got this trouble when disconnect the internet from my pc

**Description:**

1. If i have a internet connection (wi fi) i can run "ionic serve" without problems
2. When i disconnect the wifi and i try run "ionic serve" i got this error message
"Error: It appears that you do not have any external network interfaces. In order to use livereload with emulate you will need one."

**Steps to Reproduce:**

1. Disconnect from wireless
2. try run "ionic serve"

**Output:**

"Error: It appears that you do not have any external network interfaces. In order to use livereload with emulate you will need one."

**My `ionic info`:**

$ ionic info
cli packages: (/usr/lib/node_modules)
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2
local packages:
    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0
System:
    Node : v6.11.2
    npm  : 3.10.10 
    OS   : Linux 4.9

**Comment by youngfeldt** [comment]
Why is this closed?   
If all it is is livereload, I should be able to run with --nolivereload   and it should work but it does not.

What do I do if I want to develop offline ??

**Comment by dwieeb** [comment]
It's not closed... I will be fixing it for 3.10.0 as the milestone states.

**Comment by hornbd96** [comment]
This is still an issue, can we get an update on this?

**Comment by dwieeb** [comment]
@hornbd96 Can you elaborate? Need `ionic serve` output and `ionic info` output.

**Comment by Kayl06** [comment]
This is still an issue, can we get an update on this?

**Comment by Kayl06** [comment]
Here's the ionic serve output in terminal when no internet connection.

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn "C:\Program Files\nodejs\node.exe" ENOENT
    at notFoundError (C:\Users\Kayl\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\Kayl\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\Kayl\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

and here is ionic info output


    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.2
    npm  : 6.2.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by BabyManisha** [comment]
try `npx cap sync`
