### ISSUE TITLE
Ionic cordova plugin add --link doesn't work the same as cordova plugin add --link to link to a plugin that is in development

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-cli#2691]
_From @ashgibson on August 23, 2017 2:44_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic cordova plugin add --link doesn't work the same as cordova plugin add --link to link to a plugin that is in development. Shouldn't it accept the same cli arguments?

_Copied from original issue: ionic-team/ionic#12726_

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

It appears that this is a CLI issue and not an issue with the Ionic Framework (ionic-angular). I will move this issue over to ionic-team/ionic-cli. 

Thank you for using Ionic

**Comment by kensodemann** [comment]
Can you provide some more specific examples showing how the two commands work differently to clarify exactly what you mean?

**Comment by ashgibson** [comment]
cordova plugin add --link {path to local plugin} creates a symbolic link to my local plugin package so I can develop it at the same time as my main application

ionic cordova plugin add --link {path to local plugin} doesn't do the install, instead it prompts me with 

? What plugin would you like to add:

**Comment by dwieeb** [comment]
In this case the wrapped Cordova commands will do nothing for you. Just use the Cordova CLI directly. It does not accept the same CLI arguments.
