### ISSUE TITLE
When adding platform cli validates android package name from id attribute instead of android-packageName

### ISSUE THREAD

**Issue by lpikora** [ionic-team/ionic-cli#2693]
**Description:**
Command
```
ionic cordova platform add android
```
validates `id` attribute of `widget` element in `config.xml` instead of using override attribute `android-packageName` for validation.

**Steps to Reproduce:**

- Set not valid android value to id eg. `id="com.example.my-test"`.
- Add valid value to overriding attribute `android-packageName="com.example.my_test"`
- Run `ionic cordova platform add android`
- CLI still validates value in `id` attribute `Error: Error validating package name. Package name must look like: com.company.Name`

**Output:**

```
16:40 $ ionic cordova platform add android
> cordova platform add android --save
✖ Running command - failed!
[ERROR] Exception: Using cordova-fetch for cordova-android@~6.2.2

        Adding android project...
        Error: Error validating package name. Package name must look like: com.company.Name
```
**My `ionic info`:**

```
cli packages: (/Users/lukaspikora/Mapotic/mapotic_app/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    Node              : v8.2.1
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by dwieeb** [comment]
@lpikora This is a cordova-android issue, not an Ionic CLI issue. Please see the Cordova issues page for reporting Cordova issues: https://cordova.apache.org/contribute/issues.html

**Comment by hinnerk-a** [comment]
Worked for me:
```
sudo npm install -g cordova
sudo npm install -g cordova-android
ionic cordova platform add android
```

**Comment by avazkhalikov** [comment]
I wish you that XAMARIN KILLS YOU ALL! Both Cordova and IONIC.
