### ISSUE TITLE
Flag --prod not working for ionic serve command

### ISSUE THREAD

**Issue by inakilz** [ionic-team/ionic-cli#2695]
**Short description of the problem:**

The --prod flag is not working with "ionic serve" command. Due to this issue, the IONIC_ENV environment variable available through process.env acquires the value 'dev' instead of 'prod' as it should.

**Which version are you using?**

```
@ionic/cli-utils  : 1.9.2
ionic (Ionic CLI) : 3.9.2

```

**Comment by cyberbobjr** [comment]
Same problem here, IONIC_ENV is not recognized anymore with ionic cordova build --prod

**Comment by giltotherescue** [comment]
I am also experiencing this bug with both `ionic upload --prod` and `ionic cordova build --prod`

**Comment by cyberbobjr** [comment]
My config info :
cli packages: (/Users/Benjamin/h2eauassistance-ionic/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.10 
    Node       : v7.8.0
    npm        : 4.2.0 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 

Still no news about this issue ?

**Comment by dwieeb** [comment]
@giltotherescue `ionic cordova build --prod` should work? Are you sure it doesn't? The others are  bugs.

**Comment by dwieeb** [comment]
app-scripts will never do a prod build for `ionic serve`. 

```bash
$ ./node_modules/.bin/ionic-app-scripts serve --prod
[17:52:10]  ionic-app-scripts 2.1.4
[17:52:10]  watch started ...
[17:52:10]  build dev started ...
```

^ notice dev build. 

"Production builds" with livereload aren't intended to work. `ionic serve` is entirely a dev tool. It won't set `IONIC_ENV` to prod because it's not prod.

**Comment by smrgrg** [comment]
If **ionic serve --prod** does not work, then they should remove it form their documentation on [https://ionicframework.com/docs/cli/commands/serve#option-prod](https://ionicframework.com/docs/cli/commands/serve#option-prod) as its misleading and leads to waste of time.

**Comment by dwieeb** [comment]
@smrgrg Those are the Ionic 4+ docs. This issue is for Ionic 3. You should look at the CLI docs for Ionic 3: https://ionicframework.com/docs/v3/cli/serve/
