### ISSUE TITLE
When I tried to make a splash screen by CLI, it returns the 503 error.

### ISSUE THREAD

**Issue by JeongJun-Lee** [ionic-team/ionic-cli#2696]
**Description:**

When I tried to make a splash screen by CLI, it returns the error.

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

$ ionic cordova resources android -s
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
√ Uploading source images to prepare for transformations - done!
× Generating platform resources - failed!
Error: encountered bad status code (503) for https://res.ionic.io/api/v1/transform
body: <!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
        </html>

**Other Information:**

**Comment by dwieeb** [comment]
@JeongJun-Lee Just a temporary server issue. Please keep trying. The resources server is unreliable, sorry.
