### ISSUE TITLE
ionic generate page ?

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#2700]
**Output:**

![capture147](https://user-images.githubusercontent.com/140737/29747132-42fe28ba-8aa4-11e7-83a6-048339fa7d21.png)

It says OK, but the page is not created.
It is a command line error.

![capture148](https://user-images.githubusercontent.com/140737/29747148-b06af6e4-8aa4-11e7-9b7a-0a77ccda379e.png)

**My `ionic info`:**

```
C:\ae\ae.fb\aedh>ionic info

cli packages: (C:\ae\ae.fb\aedh\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.0
    npm  : 3.10.10
    OS   : Windows 10


C:\ae\ae.fb\aedh>
```

**Comment by Sampath-Lokuge** [comment]
You need to give a `name` for the page :)

`ionic generate page Login`

**Comment by peterennis** [comment]
Yes, I did that.
The error message is incorrect.

**Comment by dwieeb** [comment]
Looks like it uses an empty string, because it makes these files for me:

```
-rw-rw-r--   1 dan  staff   286B Jul 12 16:57 .html
-rw-rw-r--   1 dan  staff   248B Jul 12 16:57 .module.ts
-rw-rw-r--   1 dan  staff    11B Jul 12 16:57 .scss
-rw-rw-r--   1 dan  staff   517B Jul 12 16:57 .ts
```

Anyway, yeah, that's a bug in v3 generators. We should validate the name.

v4 generators are implemented using Angular tooling and they're better.

**Comment by dwieeb** [comment]
We won't be fixing this for v3 generators, so I'm closing this.

The v4 generators have this error message, which I think is appropriate:

```
❯ ionic g page ?
> ng generate page ?
Selector (app-?) is invalid.
[ERROR] Could not generate page.
```
