### ISSUE TITLE
Setup "IONIC_CONFIG_DIRECTORY" then "ionic serve" failed.

### ISSUE THREAD

**Issue by block115** [ionic-team/ionic-cli#2701]
**Description:**
1. Set a custom "IONIC_CONFIG_DIRECTORY" into Windows 10 environment variable.
2. Delete the default "C:\Users\\<username\>\\.ionic" folder.
3. Go to project and run "ionic serve".
4. Error: ENOENT: no such file or directory, open "C:\Users\\<username\>\\.ionic\daemon.log"
5. There is only "config.json" file in the path of "IONIC_CONFIG_DIRECTORY".
6. "daemon.json", "daemon.log" and "daemon.pid" are not in the path of "IONIC_CONFIG_DIRECTORY".

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**
Error: ENOENT: no such file or directory, open "C:\Users\\<username\>\\.ionic\daemon.log"

**My `ionic info`:**
cli packages: (S:\Dev\IDE\Ionic\ionic3-components-master\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.3.0

System:

    Node : v6.11.2
    npm  : 3.10.10
    OS   : Windows 10

**Other Information:**

**Comment by dwieeb** [comment]
I'm scared to allow this to be changed. The daemon process really should exist in a single place in your computer because it should only be running one daemon at a time.

**Comment by block115** [comment]
@dwieeb Yours concern is totally valid. However, it is also a common use case that requires the development tools to move away from the windows installed drive in order to prolong the SSD lifespan.

**Comment by dwieeb** [comment]
@block115 CLI 3.10.0 will have `IONIC_DAEMON_DIRECTORY` as a separate environment variable.
