### ISSUE TITLE
Ionic pro issue with setting up SSH

### ISSUE THREAD

**Issue by Avislux** [ionic-team/ionic-cli#2702]
**EDIT: Looks like the fix for this is to delete a folder named `config` in `\.ssh\`**

**Description:**

`ionic ssh use` or `ionic ssh setup` to link a private key ends with
`Error: EISDIR: illegal operation on a directory, read`

**Steps to Reproduce:**
I'm just running these commands on Windows.

**Output:**

```
ionic ssh setup --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'D:\\Media\\Programming\\Websites\\app-ionic', local: false, binPath:
        'C:\\Users\\Jonathan\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:
        'C:\\Users\\Jonathan\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Daemon found (pid: 16300)
[INFO] Looks like you haven't configured your SSH settings yet.

? How would you like to connect to Ionic Pro? Use an existing SSH key pair
> ionic ssh add

? Enter the location to your public key file to upload to Ionic: C:\Users\Jonathan\test\ionicssh
[ERROR] C:\Users\Jonathan\test\ionicssh does not appear to be a valid SSH public key. (Not in authorized_keys file 

        format.)
        If you are having issues, try using ionic ssh setup.

D:\Media\Programming\Websites\app-ionic>ionic ssh setup --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'D:\\Media\\Programming\\Websites\\app-ionic', local: false, binPath:
        'C:\\Users\\Jonathan\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:
        'C:\\Users\\Jonathan\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Daemon found (pid: 16300)
[INFO] Looks like you haven't configured your SSH settings yet.

? How would you like to connect to Ionic Pro? Use an existing SSH key pair
> ionic ssh add

? Enter the location to your public key file to upload to Ionic: C:\Users\Jonathan\test\ionicssh.pub
[INFO] Pubkey already added to Ionic.

? Would you like to use this key as your default for Ionic? Yes
> ionic ssh use C:\Users\Jonathan\test\ionicssh
Error: EISDIR: illegal operation on a directory, read
[DEBUG] Error: EISDIR: illegal operation on a directory, read

ionic ssh use C:\Users\Jonathan\test\ionicssh --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'D:\\Media\\Programming\\Websites\\app-ionic', local: false, binPath:
        'C:\\Users\\Jonathan\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:
        'C:\\Users\\Jonathan\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Daemon found (pid: 16300)
Error: EISDIR: illegal operation on a directory, read
[DEBUG] Error: EISDIR: illegal operation on a directory, read

```

**My `ionic info`:**
cli packages: (C:\Users\Jonathan\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.1
    Node              : v7.8.0
    npm               : 4.2.0
    OS                : Windows 10

**Other Information:**
Initially I thought having a period in the path directory might have caused a problem so I copied the keys from a \.ssh\ directory into the \test\ and got the same result. Due to this issue I couldn't figure out how to push to ionic pro with SSH. I've ran these commands in PHPStorm's terminal, and Windows elevated command line. That is until I figured out I could do it pretty easily with SourceTree.

**Comment by dwieeb** [comment]
So `C:\Users\Jonathan\test\ionicssh` a directory?

**Comment by Avislux** [comment]
It's the name of the private key file, which has no extension. I've tried renaming it too.

**Comment by dwieeb** [comment]
What about `C:\Users\Jonathan\.ssh\config`, which should be a file?

**Comment by Avislux** [comment]
An empty folder, don't remember making it.
I deleted it, ran the command again and didn't get an error. Ran `git push ionic master` and that worked too. It appears to work now. 
Thanks!

**Comment by dwieeb** [comment]
Odd. Okay, great to hear!

**Comment by BamiGorengo** [comment]
I have no config folder and got the same error. I cant use my own ssh file.

**Comment by dwieeb** [comment]
@BamiGorengo Are any of the paths directories for some reason?

**Comment by BamiGorengo** [comment]
not really. i tryed with GitBash in Windows 10 and with Ubuntu Shell that is is includet in Dev Tools für Windows 10. Both same problem... And i also cant push into ionic master.

**Comment by Avislux** [comment]
Do any directories have spaces in them by any chance? SourceTree worked for me if you can't get command line working.

**Comment by alltej** [comment]
I also have the same problem. I use git bash in Windows 10.  There are no spaces  in my directories. Error is
`.ssh/config line 3: garbage at end of line; "...\\.ssh\\ionic\\743299_rsa"`
`fatal: Could not read from remote repository.`

**Comment by dwieeb** [comment]
@alltej That's not the same problem. Can you create a new issue?
