### ISSUE TITLE
Generate hash files only after successful resources generation

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-cli#2703]
**Description:**
Flaky networks sometimes get disconnected (Timeout or Refused) by the resources generator.
Currently, you check for the `md5` hash, and if it does not exist create it, and then download.
I ask for you to change this, to only create the hash if the process finished.

**Output:**

> ionic cordova resources
> √ Collecting resource configuration and source images - done!
> √ Filtering out image resources that do not need regeneration - done!
> √ Uploading source images to prepare for transformations - done!
> × Generating platform resources: 39 / 48 complete - failed!
> Error: connect ECONNREFUSED 104.20.6.16:443
> 
> ionic cordova resources
> √ Collecting resource configuration and source images - done!
> √ Filtering out image resources that do not need regeneration - done!
> [OK] No need to regenerate images--source files unchanged.

**My `ionic info`:**
```
cli packages: (D:\xampp\htdocs\apps\humhum_new\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.1.2 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.1.2
    npm  : 5.3.0
    OS   : Windows 10
```

**Comment by dwieeb** [comment]
Thanks, @AmitMY! This will be fixed for 3.10.0.
