### ISSUE TITLE
Error using ionic cordova platform add ios

### ISSUE THREAD

**Issue by gtzinos** [ionic-team/ionic-cli#2712]
Steps to reproduce:

1) Clone project
2) npm install
3) ionic cordova platform add ios
4) open xcode
5) run app

It returns me error that can't find index.html. As a workaround i executed:

1) ionic serve
2) stop serve
3) ionic cordova platform rm ios
4) ionic cordova platform add ios

FInally index.html and assets created successfully.

**Comment by dwieeb** [comment]
You're not doing an Ionic (web asset) Build. If you want to use Xcode for running your app, you need to run `ionic build` each time before running your app in Xcode.

Alternatively, `ionic cordova run ios` will run an Ionic Build for you.

**Comment by VlnRbn** [comment]
@gtzinos  @dwieeb ionic cordova run ios don't fix for me. bash displays "BUILD SUCCEEDED", but a white screen is displayed after splash with error 
`cannot get [path to] myApp.app/index.html`
Thanks

**Comment by fplopezt** [comment]
I'm getting the same error, anyone managed how to fix it?
