### ISSUE TITLE
Why it's not possible to target the device in compilation command?

### ISSUE THREAD

**Issue by JamilHijjawi** [ionic-team/ionic-cli#2715]
**Description:**

Why its not applicable to do this command `ionic cordova compile ios --device`

**My `ionic info`:**

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.0
    ios-sim    : 5.0.11
    Node       : v8.1.4
    npm        : 5.3.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

**Comment by dwieeb** [comment]
I will add this for 3.10.0. You have two workarounds:

`ionic cordova compile ios -- --device`
or
`cordova compile ios --device`

I am adding options for `compile` so that it will be possible to just do `ionic cordova compile ios --device`.
