### ISSUE TITLE
Ionic Generate Tabs will overwrite existing pages without warning

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-cli#2720]
**Description:**
When using the CLI's generate command to generate tabs, if the name of the tab you enter matches an existing page, it will overwrite it.

**Steps to Reproduce:**

1. Create a new Ionic project using either the blank or sidemenu template
2. Create a new Ionic page and then make some edit to it to track the overwrite
3. Run ionic g tabs
4. Enter some number of tabs
5. Have one of the tabs match the name of the page you just made.
6. Inspect the page that you made and confirm it was overwritten without warning.

**My `ionic info`:**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.8.6
    ios-sim    : 5.0.8
    Node       : v8.2.1
    npm        : 5.3.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002

**Comment by dwieeb** [comment]
Generators have poor UX in general. There have been a large number of issues reported with them and this one has been reported before. I've been consolidating the issues into this one: https://github.com/ionic-team/ionic-cli/issues/2407

Thanks!
