### ISSUE TITLE
Trailing comma in last line when using ionic generate

### ISSUE THREAD

**Issue by 1nfinite** [ionic-team/ionic-cli#2721]
I am using ionic-cli v3.6.0.

When i use ionic generate pages, following code is generated.
As what we can notice, there is trailing `,` in last line for both `module.ts` and `.ts` file.
But i don't see this practices in any other ionic clone project.
Please advice.

eg:
```
 declarations: [
    SecondPage,
  ],
```
I don't think we should have comma in the end of SecondPage.

```
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { SecondPage } from './second';

@NgModule({
  declarations: [
    SecondPage,
  ],
  imports: [
    IonicPageModule.forChild(SecondPage),
  ],
})
export class SecondPageModule {}


@IonicPage()
@Component({
  selector: 'page-second',
  templateUrl: 'second.html',
})
export class SecondPage {

  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad SecondPage');
  }

}

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

[Trailing commas](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) are perfectly valid syntactically, and some people find them stylistically desirable, while others do not. Personally, I am not a fan of them, and sometimes I take them out of the generated code and other times I simply ignore them.

Given that this is a stylistic choice, and that some people will want them and others will not, there is no "right" answer to this. I will close this issue.

Thank you for using Ionic
