### ISSUE TITLE
ionic live reloading in browser is never worked for me :( 

### ISSUE THREAD

**Issue by satish22** [ionic-team/ionic-cli#2722]
I have tried down grading to ionic@2.1.12 also no luck there , my Ionic Info is below -
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v8.1.3
    npm  : 5.0.3
    OS   : Windows 10

**Comment by dwieeb** [comment]
@satish22 Please fill out the issue template.

**Comment by Barathwaja** [comment]
Try to uninstall ionic and clear cache..

Then install like this npm install -g --save --save-exact ionic@3.x 
And now do.. for me it's working perfectly in ionic 3.9.1 .
