### ISSUE TITLE
Adding plugins doesn't respect package.json formatting

### ISSUE THREAD

**Issue by sketchthat** [ionic-team/ionic-cli#2723]
**Description:**
If you run the `ionic cordova plugin add` command the `package.json` file updates the indenting of lines to 4-spaces, regardless of what spacing was previously used.

[npm introduced a fix to respect formatting in June 2017.](https://github.com/npm/npm/issues/5694#issuecomment-307142476)

**Steps to Reproduce:**
Example repo: https://github.com/sketchthat/ionic-package-bug/pull/1

1. Start new Ionic project `ionic start`
2. `package.json` file is indented with 2-spaces.
3. Install cordova plugin `ionic cordova plugin add <some-plugin>`
4. `package.json` file is now indented with 4-spaces.

**My `ionic info`:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

System:

    Node : v6.11.1
    npm  : 5.4.1
    OS   : macOS Sierra
```

**Other Information:**
Worth reviewing what `npm` did to fix the issue; https://github.com/npm/npm/issues/5694#issuecomment-307142476

**Comment by dwieeb** [comment]
@sketchthat This is actually Cordova doing this. See https://issues.apache.org/jira/browse/CB-12810
