### ISSUE TITLE
Public vs private in constructor

### ISSUE THREAD

**Issue by 1nfinite** [ionic-team/ionic-cli#2724]
I have notice that in previous version (long, long ago), the constructor is private and is then changed into public. I read through it and it says something to do about make use of AOT compilation.

So, is the current best practice for constructor is to make it public as it comes generated with public by default?

```
 constructor(public navCtrl: NavController, public navParams: NavParams) {
  }
```

**Comment by dwieeb** [comment]
Thanks for posting your issue. Unfortunately, this repo is reserved for bug reports and feature requests of the Ionic CLI. For general Ionic questions, please see our [Support Page](https://ionicframework.com/support) for options.

If you're talking about the constructor _parameters_, I personally use `public` for injected services.
