### ISSUE TITLE
Linking new project creates invalid ssh config

### ISSUE THREAD

**Issue by Lingomat** [ionic-team/ionic-cli#2725]
**Description:**

Linking a project to Ionic Pro creates a config file in the user home/.ssh.
The problem is if the username has a space in it, which is quite common on Windows systems since it may be the full name of the user.

The problem is the IdentityFile line with looked like this for me:

IdentityFile C:\Users\Mat Bettinson\.ssh\ionic\xxxxxx_rsa

This needs to look like this:

IdentityFile "C:\Users\Mat Bettinson\.ssh\ionic\xxxxxx_rsa"

Otherwise a git push will fail straight out with a complained about garbage on the end of the line in the ssh config.

**Comment by dwieeb** [comment]
@Lingomat Thanks for the bug report! I've made a PR in the repo of the library we're using for parsing and writing SSH config files: https://github.com/dotnil/ssh-config/pull/13

**Comment by Lingomat** [comment]
Ah! That explains why I couldn't find it in your source. Doh :)

**Comment by dwieeb** [comment]
@Lingomat The maintainer of that library has merged my PR and made a release! If you update to CLI 3.10.3, it should install the newest version of the `ssh-config` dependency.
