### ISSUE TITLE
Can't Install CLI latest version

### ISSUE THREAD

**Issue by MohammadWaleed** [ionic-team/ionic-cli#2727]
**Description:**
I'm trying to update the cli version to the latest 3.10.0
but when i first run the command 
`npm install ionic`
it installed 3.9.2
then i tried to run this one
`npm install ionic@3.10.0`
then it gave the output below

**Steps to Reproduce:**
update the cli to version 3.10.0

**Output:**
```
Mohammads-MacBook-Pro:RM2017 mbarghash$ sudo npm install ionic@3.10.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ionic@3.10.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mbarghash/.npm/_logs/2017-09-12T06_15_25_914Z-debug.log
```

**My `ionic info`:**
```

cli packages: (/Users/mbarghash/NetBeansProjects/RM2017/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    Node       : v8.0.0
    npm        : 5.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
```

**Comment by ernofi** [comment]
The latest published version of Ionic in NPM is 3.9.2

https://www.npmjs.com/package/ionic

**Comment by MohammadWaleed** [comment]
i realize that,but if you checked the [changelog](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md) you'll see the latest version for ionic cli is 3.10.0

**Comment by danielsogl** [comment]
@MohammadWaleed Then they missed to release it on npm.

**Comment by ernofi** [comment]
Or they just didn't change the version number?

[package.json](https://github.com/ionic-team/ionic-cli/blob/master/packages/ionic/package.json) says it's still version 3.9.2

**Comment by MohammadWaleed** [comment]
@danielsogl maybe, also as @ernofi  pointed out the version in package.json is not updated

**Comment by danielsogl** [comment]
Then he missed both :D I wrote @dwieeb on Slack

**Comment by dwieeb** [comment]
Yep, sorry. I meant to release yesterday but didn't get a chance. I'll need to change the date in the changelog.
