### ISSUE TITLE
Docs: `cordova resources` formatting problems

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2729]
https://github.com/ionic-team/ionic-cli/blob/b34c24dcc2d9f78051abb73e51d803c6cc8a3cee/packages/ionic/src/commands/cordova/resources.ts#L30

is output strangely in the docs:

![image](https://user-images.githubusercontent.com/183673/30319650-b4f6cb34-97b0-11e7-9443-35c5c7f672f6.png)

https://ionicframework.com/docs/cli/cordova/resources/

No idea where and why this is breaking though.

**Comment by Barathwaja** [comment]
@janpio Couldn't get you. you are trying to copy your own generated icons and place in resources??

**Comment by dwieeb** [comment]
@janpio I fixed this on the website, thanks!

**Comment by rtpHarry** [comment]
This issue is happening again on the current docs site:

https://ionicframework.com/docs/cli/commands/cordova-run

![image](https://user-images.githubusercontent.com/1038062/53054233-a4bdfb00-349b-11e9-9c39-20a0a3d7aec5.png)

**Comment by dwieeb** [comment]
🤦‍♂️ Looking into it...
