### ISSUE TITLE
--prod flag not recognized in build with ionic-cli 3.10.0

### ISSUE THREAD

**Issue by Tott0** [ionic-team/ionic-cli#2730]
Ionic version: (check one with "x")
[ ] 1.x (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] 2.x
[x] 3.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Current behavior:
Running ionic cordova build android --prod ignores the prod flag and still makes a dev build

Expected behavior:
Ionic build to use "build prod"

Steps to reproduce:
I noticed the prod build being ignored when I was prompted to auto update the ionic cli by the cli itself, just running a build or run command with --prod flag will ignore the flag.

Other information:
I rolled back to ionic-cli 3.9.2 and now I'm able to do a prod build

**Comment by dwieeb** [comment]
Thanks @Tott0, my apologies. I've added a hot fix with tests. Releasing 3.10.1 now...
