### ISSUE TITLE
CLI 3.10.1 : console log doesn't work anymore with livereload

### ISSUE THREAD

**Issue by Borongaj** [ionic-team/ionic-cli#2733]
**Description:**
No logs since last update to 3.10.1.

**Steps to Reproduce:**
ionic cordova run ios --device -c
or
ionic cordova run android -c

**Output:**
No logs...

Need to downgrade to 3.9.2 to get logs again.

**Comment by dwieeb** [comment]
@Borongaj Need you to fill out the issue template. At least include your `ionic info`.

I noticed you're not using the livereload option: `-l`.

**Comment by Borongaj** [comment]
Since the 3.9.0 release, the --livereload option is automatically added when -c or -s is used.

**Comment by Borongaj** [comment]
cli packages: (**bug appear if I upgrade to 3.10.1**)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    ios-deploy : 1.9.1
    ios-sim    : 6.0.0
    Node       : v6.10.3
    npm        : 4.2.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

**Comment by darrinholst** [comment]
I'm seeing this as well.

[sample project](https://github.com/dholst/ionic-no-logs)

I noticed the following line is new in the output...

    logPath: /Users/darrinholst/Projects/ionic-no-logs/platforms/ios/cordova/console.log

That file doesn't exist

---

cli packages: (/Users/darrinholst/Projects/ionic-no-logs/node_modules)

    @ionic/cli-utils  : 1.10.1
    ionic (Ionic CLI) : 3.10.1

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-sim : 6.0.0
    Node    : v8.4.0
    npm     : 5.4.1
    OS      : macOS Sierra
    Xcode   : Xcode 8.3.3 Build version 8E3004b

**Comment by dwieeb** [comment]
Thanks  @darrinholst and @Borongaj ! I've found the bug and will have a fix out shortly. My apologies.
