### ISSUE TITLE
Ability to disable update checking (update check is blocking workflow)

### ISSUE THREAD

**Issue by fephil** [ionic-team/ionic-cli#2736]
Hi,

I'm currently using Ionic CLI 3.9.1 and every time our Fastlane based workflow tries to build the app, it stops and can't progress further because of the update check. (see attached screenshot).

![image](https://user-images.githubusercontent.com/1689044/30384750-0bc4e81e-989d-11e7-86fa-f37274dff862.png)

We manage our dependencies based on testing and approval so I can't update until our internal testing is complete. Can I disable the update check? If not, I believe it should be a feature as there could be valid reasons for not using the latest release (eg the fonts issue on v3.9.2).

Thanks.

**Comment by fephil** [comment]
Apologies, just found --no-interactive flag.

**Comment by dwieeb** [comment]
@fephil Do you use Fastlane in some CI server? The CLI tries to detect common CI servers. If the environment has `CI=1`, it should run in non-interactive mode without needing the flag.

**Comment by fephil** [comment]
@dwieeb at the moment its on local machines (with a strict version policy) with a plan to move to a CI soon.
