### ISSUE TITLE
Missing @IonicPage() decorator with generated pages

### ISSUE THREAD

**Issue by HugoHeneault** [ionic-team/ionic-cli#2740]
**Description:**
When using `ionic generate page Name`, `name.ts` file miss the `@IonicPage()` decorator, which triggers an error : 
```
ERROR Error: Uncaught (in promise): invalid link: NamePage
```

**Steps to Reproduce:**
1. Run `ionic generate page Name`
2. Add this page as your `rootPage` page in app.component.ts
3. Save and go to your browser

**My `ionic info`:**
```
cli packages: (/Users/hugo/dev/some-app/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.5.2-201708241838

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1
    Node              : v7.10.1
    npm               : 4.2.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
```

**Comment by dwieeb** [comment]
@HugoHeneault I don't think this is still an issue, correct?

In any case, we likely won't be updating the v3 generators as they were redone for v4 using Angular CLI and tooling.

Thanks!
