### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by ccravens** [ionic-team/ionic-cli#2741]
**Description:**
When trying to login with ionic-cli, I get the following error:
```bash
[ERROR] API request was successful, but the response format was unrecognized.

        Request: POST https://api.ionic.io/login
        Response: 200
        Body: 
        { user_id: '123456',
           token: 
        'xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxx' 
        }
```

**Steps to Reproduce:**
1) Run "ionic login"
2) Login with valid credentials

**Output:**

**My `ionic info`:**
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

System:

    Node : v8.4.0
    npm  : 5.4.1 
    OS   : macOS Sierra

**Other Information:**
I created an account a long time ago, maybe an incompatibility?

**Comment by janpio** [comment]
Can you login on https://dashboard.ionicjs.com/ or apps.ionic.io with your credentials?

**Comment by xuanphucmanagement** [comment]
use this command ionic config set -g backend legacy

**Comment by ccravens** [comment]
@xuanphucmanagement thanks! That worked!

Should this issue be left open so that this step is no longer required in future realeses or close it out?

**Comment by janpio** [comment]
I think you can close it, as this should go away over time by default - more people will have a new account, and in January '18 old accounts will go away completely. Also there is no way to "fix" this for all people right now - either for people with new accounts or people with old accounts login will fail in either backend mode.
