### ISSUE TITLE
Feature request: add no-interactive flag option into ionic.config.json

### ISSUE THREAD

**Issue by luckylooke** [ionic-team/ionic-cli#2744]
It would be nice to have opportunity of setting `no-interactive` flag for whole project and not to have put it into every command I am writing.. so I think the best place would be `ionic.config.json`, Thanks

**Comment by dwieeb** [comment]
@luckylooke Good idea. You could set an environment variable `CI=1` and it should kick into non-interactive mode. Is your use case a CI server? Or do you not like the interactivity for some reason?

**Comment by luckylooke** [comment]
No we don't use CI server, I am just writing commands manually and in the project we decided not to move versions as we are going into production and we don't want to risk anything, so now I need to answer "no" all the time, as it is faster then write --no-interactive into commands. But it would be nice to have opportunity to set it once and be happy :D Thanks PS: I have made npm run scripts  with most common commands but it is not so shiny solution ;)

**Comment by dwieeb** [comment]
@luckylooke Answer "no" to what? The update question? I am curious if there is a UX issue here as well.

**Comment by luckylooke** [comment]
Is your use case a CI server? => No we don't use CI server
I am curious if there is a UX issue here as well => Yes, if you CLI is meant to be used by human or just by automated processes?

**Comment by dwieeb** [comment]
@luckylooke 

> Yes, if you CLI is meant to be used by human or just by automated processes?

Both are supported. Automated processes should use non-interactive mode, humans should use interactive mode.

**Comment by luckylooke** [comment]
Humans want to have opportunity to turn the interactivity off per project ;) :D

**Comment by dwieeb** [comment]
_Per project_? That's not how this was implemented 😨 I agree it should be a CLI option (and it is, with `ionic config set -g interactive false`), but storing CLI configuration per-project has been something I've been avoiding.

**Comment by luckylooke** [comment]
I will quote your CLI: "Starting with CLI 3.6, the CLI must be installed locally to use local CLI plugins." And on projects which are not in production yet I ok with interactive mode, as I want to keep CLI up to date. But in project which is in production it is risky to update even building tools when I need to quickly build hotfixes. It happens to me many times that update of building tool breaks building process. I want to be safe and have control. In such project the interactivity is bothering me. Maybe I am weird and the only one who use it that way.. I don't know.
