### ISSUE TITLE
Bug: Hardcoded watch patterns in cli-utils

### ISSUE THREAD

**Issue by pavlo-liapin** [ionic-team/ionic-cli#2747]
In https://github.com/ionic-team/ionic-cli/blob/master/packages/%40ionic/cli-utils/src/lib/ionic1/serve.ts#L135, it seems like it's impossible to overwrite several hardcoded patterns defined in the same file on line 15. Even after adding `!www/**/*` to `project.watchPatterns`, *serve* command is detecting changes in `www` directory. Shouldn't default patterns be used only in absence of project-specific ones, instead of conjunction?

Thanks

**Comment by dwieeb** [comment]
@pavlo-liapin I think you're right. I'll review this tomorrow!

**Comment by dwieeb** [comment]
Should be fixed in the next release! Thanks!
