### ISSUE TITLE
Livereload won't reload in Xcode 9 iPad-Air simulator

### ISSUE THREAD

**Issue by KevinBeckers** [ionic-team/ionic-cli#2750]
**Description:**
IOS Simulator doesn't seems to reload with live reloading. 
This happend after updating to Xcode9.
The console prints output like:

```
[INFO] [11:28:05] www/css/ionic.app.css changed
[INFO] [11:28:06] www/css/ionic.app.min.css changed
[INFO] [11:28:06] www/js/main.min.js changed
```

Beside's off that the live reloading works in the browser. ( I checkt this by visiting the server url ).

**Steps to Reproduce:**
1. Upgrade to Xcode 9
2. Run `ionic cordova emulate ios --target="iPad-Air" -lc`

**My `ionic info`:**

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1
    Gulp CLI    : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.2.3 browser 4.1.0 ios 4.5.0
    Ionic Framework   : ionic1 1.3.1

System:

    ios-deploy : 1.9.0
    ios-sim    : 6.1.2
    Node       : v7.2.1
    npm        : 3.10.10
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235

**Comment by dwieeb** [comment]
@KevinBeckers I can't seem to reproduce this issue. I've tried iPhone X and iPad-Air simulator with Xcode 9. 

Are you seeing any network errors? You can open Safari debug tools to see

**Comment by KevinBeckers** [comment]
Safari console is empty doesn't seem to respond either.
I can't see any error of any kind. What is you ios-sim version?

**Comment by dwieeb** [comment]
If the Safari console isn't responding, this might be a bigger issue. Do you get any `console.log` entries in your terminal? (add one when your app boots up) You're using `-c`, so it should print console logs.

I have to `cd platforms/ios/cordova` and `npm i ios-sim@latest` otherwise I get this error:

```
Device type "com.apple.CoreSimulator.SimDeviceType.undefined" could not be found.
```

I'm using 6.1.2.

**Comment by KevinBeckers** [comment]
No there is no logging in the console. I placed the log in a  `$ionicPlatform.ready(function() {`
Is used the following command:
`ionic cordova emulate ios --target="iPad-Air" -lc`

I also updated ionic cli:
`3.10.3 => 3.12.0`

**Comment by KevinBeckers** [comment]
Looks like the problem is with `--target="iPad-Air"`.
The 'iPhone-X' and 'iPad-Air-2' simulators are working fine...
I will test more devices soon.

**Comment by dwieeb** [comment]
Odd. I got it to work with the iPad-Air target.
