### ISSUE TITLE
SSH Key parsing does not allow ed25519 keys

### ISSUE THREAD

**Issue by listrophy** [ionic-team/ionic-cli#2754]
The regexp on this line disallows public ssh keys of the form `ssh-ed25519 ....`

https://github.com/ionic-team/ionic-cli/blob/4835cd9acdb414b1d501a1e0aff99f5cb8782faa/packages/%40ionic/cli-utils/src/lib/ssh.ts#L36

**Comment by dwieeb** [comment]
Thanks @listrophy! We use a very recent version of OpenSSH, so we should be able to support ed25519.

**Comment by listrophy** [comment]
Cool. So.... can you change this regexp to allow that?

**Comment by dwieeb** [comment]
Yeah, sorry. I had already. I just didn't push.
