### ISSUE TITLE
ionic serve should not need internet connection (still does not work!)

### ISSUE THREAD

**Issue by JohnAReid** [ionic-team/ionic-cli#2755]
Ionic serve doers not complete when running without internet connection - it exists after copy finished.

> > ionic serve 
> [INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port
>        53703 --nolivereload - Ctrl+C to cancel
> [22:01:34]  watch started ...
> [22:01:34]  build dev started ...
> [22:01:36]  clean started ...
> [22:01:36]  clean finished in 63 ms
> [22:01:36]  copy started ...
> [22:01:36]  transpile started ...
> [22:01:56]  transpile finished in 19.61 s
> [22:01:56]  preprocess started ...
> [22:01:56]  deeplinks started ...
> [22:01:58]  deeplinks finished in 2.11 s
> [22:01:58]  preprocess finished in 2.12 s
> [22:01:58]  webpack started ...
> [22:02:30]  copy finished in 53.63 s

yet it is OK when running with internet turn on.

 ionic info details:

> cli packages: (C:\Users\John\AppData\Roaming\npm\node_modules)
> 
>     @ionic/cli-utils  : 1.11.0
>     ionic (Ionic CLI) : 3.11.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.4
>     Cordova Platforms  : android 6.2.3
>     Ionic Framework    : ionic-angular 3.6.1
> 
> System:
> 
>     Node : v8.3.0
>     npm  : 5.3.0
>     OS   : Windows 10
> 
> Misc:
> 
>     backend : legacy

**Comment by dwieeb** [comment]
@JohnAReid It works for me without an internet connection. 

I noticed it seems to fail before the `webpack` step finishes. Do you have a custom webpack config?

**Comment by JohnAReid** [comment]
It is really strange - I was working on my laptop which is a 32 bit processor - tried the very same ionic app on the desktop which is 64 bit processor and is ran OK with the network disconnected.

Apart from the processor bit size the only difference is the version of node - laptop 8.3.0  desktop : 8.2.1

**Comment by dwieeb** [comment]
I'll need your `ionic info` from both computers if I'm gonna have any hope of helping. I've seen this issue before, though. The node process seems to get killed in the middle of an app-scripts build.

**Comment by JohnAReid** [comment]
Laptop (the one with the problem)

> cli packages: (C:\Users\John\AppData\Roaming\npm\node_modules)
> 
>     @ionic/cli-utils  : 1.11.0
>     ionic (Ionic CLI) : 3.11.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.4
>     Cordova Platforms  : android 6.2.3
>     Ionic Framework    : ionic-angular 3.6.1
> 
> System:
> 
>     Node : v8.3.0
>     npm  : 5.3.0
>     OS   : Windows 10
> 
> Misc:
> 
>     backend : legacy
> 

Desktop:

> cli packages: (C:\Users\John\AppData\Roaming\npm\node_modules)
> 
>     @ionic/cli-utils  : 1.12.0
>     ionic (Ionic CLI) : 3.12.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.4
>     Cordova Platforms  : android 6.2.3
>     Ionic Framework    : ionic-angular 3.6.1
> 
> System:
> 
>     Node : v8.2.1
>     npm  : 5.3.0
>     OS   : Windows 10
> 
> Misc:
> 
>     backend : legacy

**Comment by JohnAReid** [comment]
installed same version of node on the laptop: - it got one step further:

> [18:13:24]  watch started ...
> [18:13:24]  build dev started ...
> [18:13:25]  clean started ...
> [18:13:25]  clean finished in 60 ms
> [18:13:25]  copy started ...
> [18:13:25]  transpile started ...
> [18:13:41]  transpile finished in 16.12 s
> [18:13:41]  preprocess started ...
> [18:13:41]  deeplinks started ...
> [18:13:43]  deeplinks finished in 1.57 s
> [18:13:43]  preprocess finished in 1.58 s
> [18:13:43]  webpack started ...
> [18:14:09]  copy finished in 44.24 s
> [18:14:32]  webpack finished in 48.71 s
> [18:14:32]  sass started ...

ionic info:

> cli packages: (C:\Users\John\AppData\Roaming\npm\node_modules)
> 
>     @ionic/cli-utils  : 1.11.0
>     ionic (Ionic CLI) : 3.11.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.4
>     Cordova Platforms  : android 6.2.3
>     Ionic Framework    : ionic-angular 3.6.1
> 
> System:
> 
>     Node : v8.2.1
>     npm  : 5.3.0
>     OS   : Windows 10
> 
> Misc:
> 
>     backend : legacy

**Comment by JohnAReid** [comment]
Tried a blank start app and it worked OK - so I think it might have something to do with the size of the app. Tested this by removing mp3 files (35 Mb) from assets folder and ionic serve worked OK.
