### ISSUE TITLE
`ionic cordova resources` Generates Slightly Fuzzy Edges Along Logo on Icons and Splash Images

### ISSUE THREAD

**Issue by stalinkay** [ionic-team/ionic-cli#2756]
**Description:**

I recently generated some icons and splash images with a logo and it didn't render so well (fuzzy edges).

**Steps to Reproduce:**

Example repo: N/A

1. Add the provided icon.psd into project `resources` directory
2. Run `ionic cordova resources`
3. This issue is also affecting splash images

**Note: I have both a .png and .psd of the icon in my `resources` directory**

**Output:**

**My `ionic info`:**
```
cli packages: (~/app/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v7.9.0
    npm        : 5.3.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235 
```

**Other Information:**

[icon.psd.zip - original](https://github.com/ionic-team/ionic-cli/files/1322912/icon.psd.zip)
[icon.png.zip - original](https://github.com/ionic-team/ionic-cli/files/1322913/icon.png.zip)
[ios-generates.zip](https://github.com/ionic-team/ionic-cli/files/1322914/ios-generates.zip)
![icon - Original](https://user-images.githubusercontent.com/198020/30721608-35e48302-9f2d-11e7-87c2-1e56152d27ca.png)
![icon-60 3x - Generated](https://user-images.githubusercontent.com/198020/30721628-4868df6e-9f2d-11e7-998e-bc9f165f233c.png)

@dwieeb See above.

**Comment by dwieeb** [comment]
I was able to get this result with the `convert` CLI:

![icon small](https://user-images.githubusercontent.com/236501/30726838-ed8fff42-9f12-11e7-8ff5-06b4cf3514a0.png)

`magick convert icon.png -define png:compression-level=9 -resize 180x180 icon.small.png`

Not quite sure yet why you're getting poor quality images.

**Comment by stalinkay** [comment]
@dwieeb I'll test with the latest ionic cli and revert back.

**Comment by stalinkay** [comment]
Hi @dwieeb. I neglected to mention that I also have an [icon.ai (See attachment)](https://github.com/ionic-team/ionic-cli/files/1324183/icon.ai.zip) , which seems to be the source of the problem. See results below. I believe the *.ai files are picked if available.

`magick convert resources/icon.ai -define png:compression-level=9 -resize 1024x1024 icon.1024.png`

![icon 1024](https://user-images.githubusercontent.com/198020/30740506-85248372-9f91-11e7-839d-2ea30a72f5fd.png)

`magick convert resources/icon.png -define png:compression-level=9 -resize 1024x1024 icon.1024.png`

![icon 1024](https://user-images.githubusercontent.com/198020/30740587-e9759dd4-9f91-11e7-9d3b-09f39d55f9da.png)

`magick convert resources/icon.ai -define png:compression-level=9 -resize 180x180 icon.small.png`

![icon small](https://user-images.githubusercontent.com/198020/30740507-85755590-9f91-11e7-9784-206336685da2.png)

`magick convert resources/icon.png -define png:compression-level=9 -resize 180x180 icon.small.png`

![icon small](https://user-images.githubusercontent.com/198020/30740588-e9c9ffaa-9f91-11e7-88f3-e7ba2df3d8c8.png)

**Comment by dwieeb** [comment]
I _think_ PNG source images are safer, but I haven't tested thoroughly.

I do see an improvement using `icon.png` as the source image, but if the image quality is still not desirable, you can use Adobe Illustrator to export the necessary resource images according to the manifest in `config.xml`. We are limited by the imagemagick tool here, and I'm not aware of any Adobe image processing CLI tools.

**Comment by stalinkay** [comment]
@dwieeb Agreed and that works for me. I'm gonna close this. Thanks.
