### ISSUE TITLE
Are there any option to customize ionic serve?

### ISSUE THREAD

**Issue by raxim1** [ionic-team/ionic-cli#2769]
I need to create some server side part (as a development server) based on node, but i want to serve the rest servlet on the same port to emulate some real behavior.

My aim is to quickly able to check some behavior of the WebRTC.

Are there any option that the ionic serve method can grab stuff from my project and deploy as a backend?

**Comment by dwieeb** [comment]
@raxim1 I think most people define [service proxies](https://ionicframework.com/docs/cli/configuring.html#service-proxies) and then write their server code separately.

**Comment by raxim1** [comment]
Thanks a lot! I have figured out myself, but that's the right answer.
