### ISSUE TITLE
Feature request: List the most recent library versions you support

### ISSUE THREAD

**Issue by SilverMountainSoftware** [ionic-team/ionic-cli#2771]
What I'd really like for an early Christmas present is for the ionic-cli to let me know what version of the various standard libraries you support. For example, how can I know that you only support Angular 4.1.3 when the current version is 4.4.3? Or is that even true? I know you don't support 4.43 with the Ionic Pro build, but what is the latest version? Don't know. I like the program npm-check-updates but I'd really like npm-check-updates-ionic so I could know.

I think that my current problem with building with Ionic Pro (local build works just fine) is that I am using firebase 4.4.0, but I don't know, and even if I knew for a fact that it was the problem, I have no idea what old version I have to move back to.

**Comment by dwieeb** [comment]
@SilverMountainSoftware Something I've personally been very interested in doing. Updates are quite confusing. It'd be nice to have a system that checks for updates and maybe takes an input of the target version desired and shows what we support in various areas. This is just not communicated well today imo.

**Comment by dwieeb** [comment]
We likely won't be doing this for Ionic v3. But in Ionic v4, we take advantage of the Angular CLI, which has the concept of update schematics. I think that would fulfill this issue. See https://github.com/ionic-team/ionic-cli/issues/3686.
