### ISSUE TITLE
Ionic commands never stop

### ISSUE THREAD

**Issue by javilingt** [ionic-team/ionic-cli#2773]
Hi, I am having troubles with the CLI commands, all the commands works, but I must to stop them manually with ctrl+C beacuse they never stop themself. Ionic version is 3.12.0

If I use 'ionic cordova platform add ios', the result is the next

Running command done!

But not stop the proccess, I need that the proccess finish because I am launching several commands from Jenkins. All works perfectly until I arrive to the ionic commands. It happend with all commands 'ionic -v', 'ionic cordova build'...

I have install but it doesnt fix nothing.

Thx

**Comment by dwieeb** [comment]
@javilingt You mentioned this happens in Jenkins. Unless it also happens locally for you, try setting the environment variable `CI=1` or using the `--no-interactive` flag: https://ionicframework.com/docs/cli/configuring.html#flags

**Comment by javilingt** [comment]
Thx @dwieeb, the problem is caused by a proxy, the network I must use has a corporate proxy, I have installed @ionic/cli-plugin-proxy followind the steps of the doc, and export the IONIC_HTTP_PROXY to the environment variables, but it continues doing the same, the command start and finsh, but never is finalized. If I test with other network without proxy it works correctly, but I need the commands works in the network with proxy.

Thank you

**Comment by dwieeb** [comment]
@javilingt Configuring the Ionic CLI with the same proxy settings as the npm CLI should work. Let me know if you encounter any more issues.

Proxy docs: https://ionicframework.com/docs/cli/configuring.html#using-a-proxy
