### ISSUE TITLE
feat(cli): Migration tool

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-cli#2777]
**Current Behaviour:**
Ionic does not always follow semantic versioning. As an example, moving from `app-scripts` 1 to 2 while still in `v3`, broke a bunch of apps (needed to add `vendor` to index), and there could be more cases but I am not aware.
Also, `v4` is coming with many breaking changes, and while that is OK, I don't like that the user is being forced to change a bunch of stuff.

**Expected Behaviour:**
Create `ionic migrate`, a migration command that checks for deprecated or missing code, and patches it or lets the user know exactly what to do.
Every version of the cli more rules can be added, and it can work really well, if you always get the target version from the package. (don't migrate to v4 if I'm on v3.7 for example)

Here is a migration tool I wrote for v4 that covers lots of cases, and can definetly be improved, you can check that at the bottom of the file: https://github.com/AmitMY/ionic-migration-v4/blob/master/migrate.js

It uses regex to change what certainly changed in the markup, and is structured.
(for example, we first run `Button (ion-button)"` and then `Chip`, which relies on the `ion-button` change)

**Comment by dwieeb** [comment]
I believe I can close this with a link to our tslint-based tool:

https://github.com/ionic-team/v4-migration-tslint
