### ISSUE TITLE
cli execute ioinc command issue

### ISSUE THREAD

**Issue by kuangqifu** [ionic-team/ionic-cli#2789]
My os is win10,I install Ionic with command "npm install -g ionic cordova",everything looks OK,but when I run "ionic start" command,normally,it should ask and wait me to enter my project name,but it just ask me but not wait me to wait,command quickly end.
"ionic start" command execute like this:
```
C:\WINDOWS\system32>ionic start
? What would you like to name your project:
C:\WINDOWS\system32>
```

execute "ionic start ionictest",it's the same([see here](https://stackoverflow.com/questions/46638242/win10-dos-execute-ioinc-command-issue)).I tried to update,and restart computer,but the same.

**Comment by dwieeb** [comment]
What terminal are you using? Normal Windows 10 command prompt?

**Comment by kuangqifu** [comment]
yes.other terminal is the same like vs code,git.

**Comment by dwieeb** [comment]
What's your `ionic info` output?

**Comment by kuangqifu** [comment]
just display "- Gathering environment info",then closed. every ionic command like this.
```
C:\WINDOWS\system32>ionic info
\ Gathering environment info
C:\WINDOWS\system32>
```

**Comment by dwieeb** [comment]
Can you try `ionic info --no-interactive` ?

**Comment by kuangqifu** [comment]
```
C:\Users\Donald>ionic info --no-interactive
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (C:\Users\Donald\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

System:

    Node : v6.10.2
    npm  : 5.4.2
    OS   : Windows 10

Misc:

    backend : pro
```
need any other information?

**Comment by dwieeb** [comment]
It seems to be related to the interactivity library we're using: https://github.com/SBoudrias/Inquirer.js/

Could you possibly update to Node 8 LTS and see if the issue persists?

**Comment by kuangqifu** [comment]
it is work now.I did the flowing steps:
1. npm install inquirer(not work).
2. install nvm,then update nodejs and use the new version(not work)
3. do "npm install -g npm"
4. do "npm update -g cordova ionic"

ionic informations:
```
C:\Users\Donald>ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (C:\Users\Donald\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

System:

    Node : v8.6.0
    npm  : 5.4.2
    OS   : Windows 10

Misc:

    backend : pro
```
thanks!

**Comment by dwieeb** [comment]
Nice. It must've been the Node version. If you're curious, there is a new `v6.11.4` for Node 6 that you could try. Perhaps the issue was fixed in that branch of Node as well.
