### ISSUE TITLE
cordova plugin add cordova-fabric-plugin Caught exception:  undefined

### ISSUE THREAD

**Issue by gbhar4** [ionic-team/ionic-cli#2790]
**Description:**
Getting undefined error on ionic state reset.
I tried sudo and deleting node modules from the app and then yarn install but nothing works.

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.1.0
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.3 Build version 8E3004b

**Comment by dwieeb** [comment]
@gbhar4 That CLI version is very out of date. Please upgrade to the latest and create a new issue if this is still a problem.
