### ISSUE TITLE
ionic cordova platform add ios / ionic cordova resources dead

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-cli#2793]
_From @IncognitoCore on October 10, 2017 10:35_

**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionic cordova platform add ios
> cordova platform add ios --save
✔ Running command - done!
> ionic cordova resources ios --force
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✖ Uploading source images to prepare for transformations - failed!
HTTP Error 503: POST https://res.ionic.io/api/v1/upload
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>

**Expected behavior:**
ionic cordova platform add ios
> cordova platform add ios --save
✔ Running command - done!
> ionic cordova resources ios --force
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations - done!

**Steps to reproduce:**
ionic start
> test
> blank
cd test
ionic cordova platform remove ios
ionic cordova platform add ios

**Related code:**

**Other information:**
`ionic cordova resources` gives the same error.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (/Users/Kevin/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.2
    ios-deploy        : 1.9.0
    ios-sim           : 5.0.8
    Node              : v8.4.0
    npm               : not installed
    OS                : macOS High Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy

_Copied from original issue: ionic-team/ionic#13098_

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

As this is not an issue with the Ionic Framework, I am going to move this to the Ionic CLI repo.

Thank you for using Ionic

**Comment by rashnk** [comment]
Same issue posted :  here[Error](https://github.com/ionic-team/ionic-cli/issues/2792)

**Comment by dwieeb** [comment]
Sorry all, our resource generation server has been flaky lately. Let me know if there are still issues.

**Comment by t-ricci-molecle** [comment]
@dwieeb Hi, I'm having the same 503 error right now when trying to generate the resources

**Comment by t-ricci-molecle** [comment]
@dwieeb also, cloud you guys post the sourcecode that you're using to generate the resources or provide within ionic-cli an offline resources generator? Because in case I need to deploy several apps and the service goes offline I'm really in trouble if I can't build the apps and need to make all the images manually

**Comment by jonathan-chin** [comment]
is there a reason this generator needs to be online? I've been trying to generate resources for the last hour (no exaggeration) and it keeps failing with a 503 error.

why can't we run this offline?

**Comment by 1pocketaces1** [comment]
I used ionic cordova resources and it said I have no platforms detected. When I ran the suggested command to add ios and then generate resources, my app broke and will no longer build when I try to package it for ios.
Here is the failure:
<img width="531" alt="screen shot 2018-05-02 at 12 11 35 pm" src="https://user-images.githubusercontent.com/34732486/39538323-0b6f5d2a-4e02-11e8-8a3a-b1fb8e41e45a.png">

I cannot figure out what action broke it and how to reverse the problem

**Comment by dwieeb** [comment]
@t-ricci-molecle @jonathan-chin The resources service likely won't exist in its current form long-term   (next few years). It was made to ease the common process of generating appropriately sized Cordova resources without having to compile some image library locally. It's a completely free service that everyone expects to be available 24/7. I'm not sure how or why this service would be tied to app deploys, considering the resources are generated and stored as files in the app. The only time the service is useful is when an icon or splashscreen is changed or when a new resource size is added, which generally happens during development, and certainly not deploy.

There are plenty of alternatives for offline, local image processing, if needed. They just need to be configured. There are even ones specifically for Cordova. 

We'll probably be redesigning the official story for app resources such as icons and splashscreens, especially with the arrival of [Capacitor](https://capacitor.ionicframework.com/). I talk a little bit about this [here](https://github.com/ionic-team/ionic-cli/issues/2132#issuecomment-375923308). More on this later.

@1pocketaces1 That looks like an unrelated issue and I can't read the full error line in your image. Please create a new issue.
