### ISSUE TITLE
Hook in Prepare Step gets executed twice

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-cli#2796]
_From @TheHighriser on October 4, 2017 10:21_

#### Short description of the problem: 

I have a hook running the after_prepare step. It gets executed twice when I use ionic cordova run android. If I only use cordova run android it works.

#### What behavior are you expecting?

That my hook gets executed only once.

**Steps to reproduce:**
1. Create a Plugin which uses Hook in the after_prepare step
2. Do ionic cordova run android
3. Step gets executed twice

**Which @ionic/app-scripts version are you using?**
2.1.3

_Copied from original issue: ionic-team/ionic-app-scripts#1262_

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This issue is being moved to the CLI repo. Please follow the issue over there.

Thank you for using Ionic

**Comment by dwieeb** [comment]
@TheHighriser Thanks for reporting the bug! The next release will include the fix. 😄
