### ISSUE TITLE
Docs: device/emulator parameter explanation is wrong

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2798]
From the docs at https://ionicframework.com/docs/cli/cordova/build/

param | explanation
-- | --
--device | Deploy Cordova build to a device
--emulator | Deploy Cordova build to an emulator

I don't think this is really correct, is it?

The build is made _for deploy_ on a device or emulator, but the command doesn't do any deploying.

**Comment by dwieeb** [comment]
Ahh, thanks for catching that.
