### ISSUE TITLE
Ionic CLI and `packageType`?

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2800]
I just found about `packageType`, a param for the Cordova CLI:

Parameter | Flag | Description
-- | -- | --
Packaging Type | `--packageType` | This will determine what type of build is generated by Xcode. Valid options are `development` (the default), `enterprise`, `ad-hoc`, and `app-store`.

Source: https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#using-flags

This sounds like it would be very important to be able to create a proper iOS build with the CLI (which almost nobody does but uses Xcode...). Any knowledge how this plays together with Ionic CLI? Or is this not really needed?

**Comment by dwieeb** [comment]
I think a lot of people use `--buildConfig` or the `--` separator for these signing options:

```bash
ionic cordova build ios --device --prod --release -- --developmentTeam="ABCD" --codeSignIdentity="iPhone Developer" --provisioningProfile="UUID"
```

**Comment by janpio** [comment]
Yeah, via `buildConfig` I have seen that - also because it is in the example of Cordova at https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#using-buildjson.

But if you are only using `-- --` you should _also_ use `-- --packageType` as it seems to be an important param - but in none of the Ionic examples it does appear, also almost nowhere on the net or in the forum. Get what I mean?

**Comment by dwieeb** [comment]
I can surely add it to the example. How does this look? https://github.com/ionic-team/ionic-cli/commit/299fd1747fc04c014c2f2a7802ae4e4cf21aa6e5

**Comment by janpio** [comment]
I am still trying to understand how it plays together with `provisioningProfile`... I think that one is for pre Xcode 8, `packageType` for 8+. As always, code signing is a confusing mess. Especially with the added layers of both Cordova and Ionic.

**Comment by dwieeb** [comment]
I'm not sure on the necessity of it either. The `packageType` should be inferrable from the type of `provisioningProfile`:

![image](https://user-images.githubusercontent.com/236501/31556189-8091880e-b009-11e7-8399-f72256de0004.png)

**Comment by janpio** [comment]
`provisioningProfile` is not really used with Xcode 8+ any more, see the build.json example: 
https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html#using-buildjson
I created a PR that makes this clearer in the table above.

(I wonder if Xcode 9 tumbled some stuff around again here...)

**Comment by dwieeb** [comment]
Ah, this is the autosigning introduced in Xcode 8. If you specify your development team and "package type", it'll automatically generate/download what it needs to sign the app. It's supposed to make the signing process easier.

**Comment by janpio** [comment]
Exactly. That's why https://github.com/ionic-team/ionic-cli/commit/299fd1747fc04c014c2f2a7802ae4e4cf21aa6e5 unfortunately makes no sense ;)

**Comment by dwieeb** [comment]
Yeah I've since fixed it: https://github.com/ionic-team/ionic-cli/commit/18cdc77655bbb99cfee2d3a6eaaf6e2af72023c3

I like to keep examples current.

**Comment by janpio** [comment]
(Careful, I'm not sure if this works with a default Cordova iOS project... these are _old_)
