### ISSUE TITLE
Ionic Cli VersionCode paramerter not available

### ISSUE THREAD

**Issue by prantikv** [ionic-team/ionic-cli#2801]
**Description:**
Version Code is not being set using the CLI parameter for Ionic but works for cordova.

**Steps to Reproduce:**
A thing to note here is that the following does not work
`ionic build --release android -- --versionCode=3`
while the following does work
`cordova build --release android -- --versionCode=3`

**My `ionic info`:**

```
    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 5.1.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.3
    npm               : 5.4.2
    OS                : Windows 10

Misc:

    backend : pro
```

**Other Information:**
More on this issue is mentioned in the followind forums and questions.
[number 1](https://forum.ionicframework.com/t/ionic-build-adds-8-to-version-code/108456/3)
[number 2](https://github.com/ionic-team/ionic-cli/issues/991)
[number 3](https://stackoverflow.com/questions/38078174/how-to-change-versioncode-with-cordova)

Let me know if further information is required.

**Comment by dwieeb** [comment]
Can you try `ionic cordova build android --release -- -- --versionCode=3`?

Options that the Ionic CLI doesn't know about must be further separated

If that doesn't work, a workaround would be to set these values in your `config.xml`: https://cordova.apache.org/docs/en/latest/config_ref/#widget

**Comment by prantikv** [comment]
The solution provided by @dwieeb works.
