### ISSUE TITLE
"Cordova Platforms : none"

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2804]
I see more and more forum posts with `Cordova Platforms : none`. Did something change there?

**Comment by dwieeb** [comment]
Nothing has changed. We use `cordova platform ls`, but I may change it soon to read directly from `platforms/platforms.json`, which we're already doing in other places.

**Comment by janpio** [comment]
Strange. 

Can Ionic Pro built without platforms being added locally?

**Comment by dwieeb** [comment]
Yes, Ionic Pro uses `cordova prepare`, which reads from `config.xml` and `package.json`. 

See https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/#saving-platforms and https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/#restoring-platforms

But, `Cordova Platforms` in `ionic info` is for which platforms are installed locally.

**Comment by janpio** [comment]
Ok, so these users have maybe defined the platforms in their files, but not installed them locally?

Meh, that makes it not easier to debug their stuff. What command should they run to install locally?

**Comment by dwieeb** [comment]
They can run `ionic cordova prepare` directly, but most of the other Cordova commands will run the Cordova prepare step, such as `ionic cordova build`, `ionic cordova run`, `ionic cordova emulate`, etc.

**Comment by janpio** [comment]
Ok. I assume they don't use these at all because they fully use Ionic Pro.

Will try and ask some...

**Comment by yxliang01** [comment]
I can see in commit https://github.com/ionic-team/ionic-cli/commit/2c2478ffd7dbe2981abca46829350936b33c0af0 , you changed it to make it use `platforms/platforms.json` for loading the platforms. However, I believe in many ionic projects' `.gitignore` files, the `platforms` folder has been ignored. Therefore, what will happen is that, under every new environment, `ionic cordova platform add` is needed to re-generated `platforms/platforms.json` to have ionic had a correct behaviour. I have spent a very long time (like days) to debug this... Although I am not sure why this is better, but I feel like it's better to have some notice for this change?

**Comment by dwieeb** [comment]
`platforms/` and `plugins/` should be git-ignored. Under new environments (via git clone), you won't have `platforms/` and `plugins/` and you'll need to perform a `cordova prepare` (or `cordova build <platform>`, which runs the `prepare` step) to initialize them again. This is standard behavior. Please read [Platforms and Plugins Version Management](https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/).

The gist is: `config.xml` (and `package.json`) list what Cordova platforms and plugins your project _should_ have installed. `platforms/platforms.json` lists what Cordova platforms you _do_ have installed. 

This is similar to how npm uses `package.json` as a manifest to know which packages to install into `node_modules`.

In the `ionic info` command, and other places in the CLI, we're interested in which platforms are _actually installed_, not which platforms you have listed in `config.xml`. That's what that commit (https://github.com/ionic-team/ionic-cli/commit/2c2478ffd7dbe2981abca46829350936b33c0af0) is fixing.

**Comment by yxliang01** [comment]
@dwieeb ah I see. Sorry for that. The reason why I thought that is because when I do `ionic cordova prepare`, it says no platform in `config.xml` while there are `android`, and `ios`, in both `config.xml` (as `<platform name="xx">`) and ``package.json` (in the platforms array). Also, when I did `ionic cordova platform ls`, it shows them as installed platform. And, when that problem happened, `platforms/platforms.json` doesn't exist. So, seems like I haven't really found the problem.

**Comment by dwieeb** [comment]
@yxliang01 No need to apologize! I think Cordova projects (just like node projects) can sometimes get in a weird state. From what you described, I would try the following:

- Make sure you're using Cordova 7+
- `cordova platform save` (this should add what you have installed locally to your `config.xml` & `package.json` files)

If that doesn't work, just try removing and re-adding the platforms:

- `cordova platform rm android`
- `cordova platform rm ios`
- `cordova platform add android`
- `cordova platform add ios`

**Comment by yxliang01** [comment]
@dwieeb nope. Unfortunately, the methods mentioned above don't work... `ionic cordova prepare` still gives me `No Cordova platforms listed in config.xml. Nothing to prepare` while the entries in config.xml and package.json are looking fine to me. However, `cordova prepare` does the right thing. So, I still suspect this has something to do with ionic 3.13.0 update. I have tried to downgrade. But, for some reason, it doesn't seem to be possible. When I tried to install 3.12.0, `ionic -v` still gives me 3.13.0 no matter the `ionic` installed globally or in my project folder. However, my project failed to build at the exact same time `ionic` updated to 3.13.0 .

**Comment by dwieeb** [comment]
Are you missing `<engine>` in `config.xml`? Those tags define the Cordova platforms in `config.xml`, not `<platform>` tags (believe it or not). See https://cordova.apache.org/docs/en/latest/config_ref/#engine

Are you sure removing and re-adding the platforms doesn't work? You could try `rm -rf platforms/ plugins/` and re-adding _everything_ that you have listed in `config.xml` & `package.json` with `cordova prepare`.

**Comment by yxliang01** [comment]
@dwieeb I have checked the `<engine>` tags, it's all there. I have also tried `rm -rf platforms plugins prepare node_modules`, remove all platforms, add all platforms again. And, `ionic cordova prepare` still gives me `No Cordova platforms listed in config.xml. Nothing to prepare` while `cordova prepare` does the job.

**Comment by dwieeb** [comment]
@yxliang01 Oh, I see the issue! I apologize. I will fix this promptly and have a fix out soon.
