### ISSUE TITLE
Don't use local installation for commands that are only meant to run outside project directories (`ionic start`)

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2810]
This problem of this user was caused by `ionic start` using a (broken) local Ionic installation:
https://forum.ionicframework.com/t/error-with-ionic-start-new-project/109164

If  `ionic start` wouldn't use a local installation, which really never makes sense anyway, this problem could have been avoided.

**Comment by dwieeb** [comment]
The issue would then happen for seemingly arbitrary commands, and potentially be even more confusing. 

I _could_ detect for an Ionic CLI >3.0.0. The issue arose due to `├── ionic@2.2.1 extraneous`. The part of `ionic` that uses a local installation if installed doesn't work for older CLI versions.

**Comment by janpio** [comment]
The problem then would only happen for commands where you expect a local Ionic installation being present in `node_modules` - inside a project folder. Outside of it I only "found" this because I helped debug several similar problems in the last few days.

**Comment by dwieeb** [comment]
So I'm looking for CLIs older than 3.10.0 (mostly arbitrary version I chose). If it is older, I'm not running the local version. I'm displaying a warning if that happens.
