### ISSUE TITLE
Feature Request: Add a cli mode for instantly displaying the whole log

### ISSUE THREAD

**Issue by Defcon0** [ionic-team/ionic-cli#2814]
Hello,

since one of the latest updates of the ionic cli, I get this spinner saying "Running command". Even --verbose doesn't help out in this case. Still not the whole log is shown *instantly* but only after the whole command had been run.

Also described here: https://forum.ionicframework.com/t/ionic-cli-not-showing-progress/99008

Is there any chance that we get a mode for having ordinary (not hidden) output *instantly* showing what's going on?

I really dislike the new behavior since I think it's patronising me (is this the right word in English ;-) ?).

**Comment by dwieeb** [comment]
I agree, @Defcon0 !

With the upcoming release, all Cordova output will be shown in real-time.

Thanks!
