### ISSUE TITLE
This is senseless: from one hour to another, I can't serve my application.

### ISSUE THREAD

**Issue by Zerokk** [ionic-team/ionic-cli#2817]
I've got a project that started a long time ago, and tried to retake it after a few months of inactivity. I cloned the repo, checked out to the latest version, and pulled it off. Installed the latest version of Node, downloaded the dependencies, and served my app. Perfect!

... thing is, after some time just checking out what's missing to finish the app (didn't even write any code), I closed my laptop and went to eat a nice chicken enchilada to the Foster's. When I came back home, I wanted to continue my job, so I wrote again: "ionic serve --lab", and suddenly, it gave me this error:

> Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)

hmmm what? I was a little surprised, since no change has been done either to my computer, the project, or the dependencies themselves. Tried to do evetyhing: "node install", "node update", "node uninstall node-sass", "node install node-sass"... after some time, I uninstalled Node and switched back to the current LTS version. 

Same error, again and again. Tried the prior steps, but no effect was done. At this moment, after reinstalling node-sass in the project, and ionic-app-scripts, this is what I get:

> ionic serve --lab
> [INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --lab
>        - Ctrl+C to cancel
> [16:56:50]  watch started ...
> [16:56:50]  build dev started ...
> Error: C:\some\path\my_project\src\app\main.ts was not found. The "main.dev.ts" and "main.prod.ts" files have been deprecated. Please create a new file "main.ts" containing the content of "main.dev.ts", and then delete the deprecated files.
>                             For more information, please see the default Ionic project main.ts file here:
>                             https://github.com/ionic-team/ionic2-app-base/tree/master/src/app/main.ts
>     at BuildError.Error (native)
>     at new BuildError (C:\some\path\my_project\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
>     at C:\some\path\my_project\node_modules\@ionic\app-scripts\dist\build.js:58:21

So now... my project is tottally stopped. I can't do anything. I seriously need a fix for this...

Any help?

PD: some info:

- SO: Windows 10 64 bits
- Node v: 6.11.4
- Ionic version: latest (3.13.2)

**Comment by dwieeb** [comment]
Did you take these steps? 

> Error: C:\some\path\my_project\src\app\main.ts was not found. The "main.dev.ts" and "main.prod.ts" files have been deprecated. Please create a new file "main.ts" containing the content of "main.dev.ts", and then delete the deprecated files.
For more information, please see the default Ionic project main.ts file here:
https://github.com/ionic-team/ionic2-app-base/tree/master/src/app/main.ts

By reinstalling `@ionic/app-scripts`, you may have updated it to the latest version, and there may have been several breaking changes since the version you originally had installed. You can also review the breaking changes in the app-scripts release notes: https://github.com/ionic-team/ionic-app-scripts/releases

**Comment by Zerokk** [comment]
Hello @dwieeb, thanks for helping! Although I followed the steps and deleted both files, moving the content from the dev- file to the new main.js, now I just can't go through the "transpile started..." phase. It just gets stuck there.

What's failing here? Should I go back to the latest Node version, and re-run npm update? Maybe creating a new fresh project and moving my files there? Maybe both?

**Comment by Zerokk** [comment]
Ok, no worries, I already fixed it.

What I did is just creating a fresh Ionic project, and moving my external dependencies, pages and assets to the new project. Now it's working neat!
