### ISSUE TITLE
Not able to use local plugin after 7.1.0 update

### ISSUE THREAD

**Issue by johanlantz** [ionic-team/ionic-cli#2818]
**Description:**
I am developing a native plugin for iOS and Android. Previously I have just pointed the path in my config.xml to the local directory while developing and it was working fine. So instead of:
<plugin name="myplugin" spec="*" />

I put 
<plugin name="myplugin" spec="../myplugin_local_dir" />

And it just worked. Instead of fetching the code from the repo, it was fetched from my local folder. However after updating to cordova 7.1.0 it no longer works.

**Steps to Reproduce:**
cordova plugin rm myplugin
cordova plugin add myplugin

The rebuild for Android.

I have also tried to edit package json manually but the same result.
I have also tried to use the -nofetch and -noregistry flags but same result.

The entry in config.xml looks the same as in previous versions after removing and adding the plugin:
<plugin name="myplugin" spec="../myplugin_local_dir" />

and the entry in package.json looks correct I think

"myplugin": "file:///Users/yc00025/projects/myplugin_local_dir",

**Output:**
Discovered plugin "myplugin" in config.xml. Adding it to the project
        Failed to restore plugin "myplugin" from config.xml. You might need to try adding it again. Error:
        Failed to fetch plugin file:///Users/yc00025/projects/myplugin_local_dir via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Failed to get absolute path to installed module

**My `ionic info`:**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    ios-sim           : 6.0.0
    Node              : v8.0.0
    npm               : 4.2.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9M137d

**Comment by ajcrites** [comment]
I think that this is most likely a Cordova 7 problem rather than ionic-cli. Does your local plugin have a package.json file?

**Comment by johanlantz** [comment]
It does have a package.json. You are probably right that its a Cordova 7 issue. Do you know the proper way to file an issue with them?

**Comment by dwieeb** [comment]
Looks like this issue is affecting plugins with a URL spec, too. Broken in 7.1.0 but works in 7.0.1.

**Comment by dwieeb** [comment]
I'm seeing related issues:
- https://issues.apache.org/jira/browse/CB-13503
- https://issues.apache.org/jira/browse/CB-13507

**Comment by fdambrosio** [comment]
I have the same problem: 

_Failed to restore plugin "cordova-plugin-screen-orientation" from config.xml_

```
    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v6.11.2
    npm        : 5.5.1
    OS         : macOS Sierra
```

**Comment by hmoratopcs** [comment]
Solved for me after updating to cordova@8.0.0

**Comment by alejandro-heredia-coderoad-com** [comment]
@hmoratopcs Yeah, it works great, but breaks other plugins :(

**Comment by dwieeb** [comment]
@alejandro-heredia-coderoad-com Try 7.0.1.

Closing as this is not an issue with the Ionic CLI. Please follow the issue with these links: https://github.com/ionic-team/ionic-cli/issues/2818#issuecomment-340493575
