### ISSUE TITLE
Indicate Ionic Deploy usage?

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2821]
More and more people in the forum seem to "forget" they are using Ionic Pro Deploy in their apps and are wondering or complaining their apps showing older versions of the app than what they just built.

Would there be a way to somehow indicate in the CLI that the built app will use Ionic Deploy to load whatever version is currently uploaded on Ionic Pro? Maybe in the build output, maybe in `ionic info`...

**Comment by Fuiste** [comment]
I agree this is a potentially confusing situation that can arrive when using Deploy, but a few thoughts on the current state of the plugin.

As of `cordova-plugin-ionic` v2.0.0, if you're running a debug build of the app, you should be see a dialog asking if you'd like to load in the update before any automatic redirection takes place.  I'm definitely open to talking about other ways this could be handled though, and if you'd like to start a discussion about it feel free to pop over to https://github.com/ionic-team/cordova-plugin-ionic/issues

Cheers!

**Comment by janpio** [comment]
Thanks @Fuiste, only now I understood what you meant. The problem still appears regularly on the forum, as I understood it people are just doing release builds and wondering what is happening. Them using "pro" is a good indicator to ask them if they use "Ionic Deploy", but most are honestly not aware and only come back later with a "Ahh, yes, that was it. Thanks.".

**Comment by dwieeb** [comment]
Yes, we should show version numbers/useful info for the stuff that Pro requires in apps.

**Comment by dwieeb** [comment]
🔖 This should be easy enough. During the `ionic info` gathering for the Cordova integration, check the output of `cordova plugins ls` and look for `cordova-plugin-ionic`. Then, get its version.
