### ISSUE TITLE
ionic proxy not working when update ionic-cli to 3.15.0

### ISSUE THREAD

**Issue by KevinFu** [ionic-team/ionic-cli#2824]
my proxy setting working fine when ionic serve & run in device and simulator

but update to 3.15.0  proxy failed on device and simulator

when I downgrade to 3.14.0 it works fine

**Comment by skyrain888** [comment]
the bug with me too

**Comment by ddiez31** [comment]
me too.
not function with 3.15.0 but ok after downgrade 3.14.0

**Comment by dwieeb** [comment]
Sorry about that! This issue should be fixed in 3.15.1.
