### ISSUE TITLE
exception ionic cordova run browser after upgrade to 3.15.0

### ISSUE THREAD

**Issue by luckychel** [ionic-team/ionic-cli#2826]
**Description:**

after upgrade to ionic cli 3.15.0 fired an exception
only downgrade to 3.14.0 ionic cordova run browser works fine

$ ionic cordova run browser
> cordova platform add browser --save
Using cordova-fetch for cordova-browser@^4.1.0

Error: Platform browser already added.

[ERROR] Exception:

**My `ionic info`:**

$ ionic info

? The Ionic CLI has an update available (3.14.0 => 3.15.0)! Would you like to install it? No
Not automatically updating your CLI.

cli packages: (C:\Users\kukoba.av\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.14.0
    ionic (Ionic CLI) : 3.14.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.3
    Node              : v6.11.2
    npm               : 3.10.10
    OS                : Windows 10

Misc:

    backend : legacy

**Comment by celinakhalife** [comment]
I found a temporary solution, remove the browser platform:
- ionic cordova remove platform browser --save
Then run your project with livereload
- ionic cordova run browser --livereload
 For some reason, when you run the project, the CLI is always adding the browser platform.
If the browser platform is already added, it will return an error and the run will be aborted.
Running the project with livereload will automatically re-run the project once changes are saved.

**Comment by luckychel** [comment]
thanks for temp solution

**Comment by dev-manager-uk** [comment]
We have the same bug.

Every time you run:
`ionic cordova remove platform browser`

Then the next time you run:
`ionic cordova run browser`

Then it builds correctly.

The 2nd time you run:
`ionic cordova run browser`

it fails every time.

**Comment by ThorvaldAagaard** [comment]
I have the same problem.

I just reverted to 3.14.0 with the command

```
npm install ionic@3.14.0
```

I think it might be ionic/cli-utils@1.15.0 that is causing problems, as there is a fix that it should only return valid platforms. That might have introduced the error

**Comment by dev-manager-uk** [comment]
thanks @ThorvaldAagaard 

Are there any downsides to permanently targeting a specific version like this?

And then only upgrading that version when we need new features from the latest release?

**Comment by ThorvaldAagaard** [comment]
Version 3.14.0 was only 2 days old before 3.15.0 arrived, so I guess it will be easy to fix.

But generally it should be ok to stick with a specific version like all other npm-packages, and then plan the upgrade. Only issue is that when you update all at the same time it might be difficult to see what introduces the error

**Comment by dev-manager-uk** [comment]
ok, thank you!

**Comment by dwieeb** [comment]
Sorry about that. Please keep in mind we don't "officially" support the browser platform yet--see https://github.com/ionic-team/ionic-cli/issues/2312.

**Comment by dev-manager-uk** [comment]
@dwieeb I was under the impression that Ionic fully supported the browser.  Am I wrong?

"Ionic is the perfect platform for building progressive web apps" 
" it’s already built to work perfectly in the browser"
http://blog.ionic.io/navigating-the-world-of-progressive-web-apps-with-ionic-2/

@mhartington perhaps you can clarify also?

"We support Safari, Chrome, firefox, and Edge."
mhartington - Ionic Team - Apr 28
https://forum.ionicframework.com/t/does-ionic-support-browser-project-and-which/88102/7

Also:
http://blog.ionic.io/announcing-pwa-support-in-ionic-2/
https://ionicframework.com/docs/developer-resources/desktop-support/

We are investing considerable time into an iOS, Android and Web Browser based app.  If Ionic are not planning to support the browser we would have to reevaluate our approach.

Many thanks.

**Comment by kensodemann** [comment]
@dev-manager-uk - I believe they are just talking about the cordova browser platform, which is more of plugin testing platform, at least currently. Many plugins don't work with it and some that do work with it do so by providing mock data and not real data. Others work great!

Running the browser, though, is perfectly fine. See the advice given here: https://blog.ionic.io/how-to-make-pwas-with-ionic/ pertaining to commenting out `cordova.js` if you are just going to run in the browser and about other current advice for deploying the application for web.

If running on both a native and a web environment, this article shows how to deal with the lack of plugins by either using Ionic Native and getting a warning but continuing on but without the support of the plugin functionality or by having separate code run depending environment: https://ionicframework.com/docs/developer-resources/desktop-support/

Finally, I find this page very helpful when running from the browser: https://whatwebcando.today

**Comment by dev-manager-uk** [comment]
Thank you @kensodemann 

I understand that lots of plugins might not work as well on web compared to mobile.  Fair enough.

However I don't understand why that is being used as an excuse for releasing a version of ionic-cli that breaks "ionic cordova run browser" because you don't "officially" support it.

Or is there a different command that you do "officially" support?

**Comment by ThorvaldAagaard** [comment]
I am using the browser platform and deploying it to firebase.

That is working fine, but it would be nice if it was a supported platform at the same level as the others.

After the latest update of ionic that fixed the problem with the platform getting added, there is still an issue as the command

```
ionic cordova build browser --prod
```

now fails with this error

Error: ./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (typescript.js:9341:17)

**Comment by dev-manager-uk** [comment]
Just seen #13248

So are you saying that instead of:
ionic cordova build browser --prod

We should be using:
npm run ionic:build -- --prod

**Comment by kensodemann** [comment]
Yes. Per the "Deploying" section of this article: https://blog.ionic.io/how-to-make-pwas-with-ionic/

But you will have to make sure you use web API calls to replace the functionality of the Cordova plugins that won't be there per the "plugins" section of this article: https://ionicframework.com/docs/developer-resources/desktop-support/

That would be my suggestion, anyhow.

**Comment by dev-manager-uk** [comment]
Thanks Ken, we'll give that a go.

**Comment by dev-manager-uk** [comment]
We have updated our build from:
ionic cordova build browser --prod

to use instead:
npm run ionic:build -- --prod

And it's now working.  

Thank you for your help @kensodemann @dwieeb
