### ISSUE TITLE
(IOS) Icon-40@2x.png (80x80 px) not transferred to the AppIcon.appiconset

### ISSUE THREAD

**Issue by telran** [ionic-team/ionic-cli#2827]
**Description:**

Only Icon-40@2x.png is not transferred to the AppIcon.appiconset although it exists in the resources/ios /icon/ and in the config.xml.

<icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

cordova-icon

**My `ionic info`:**

cli packages: (/Users/developer/work/app/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:

    cordova (Cordova CLI) : 7.1.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.1 
    Node       : v8.5.0
    npm        : 2.15.12 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004 

Misc:

    backend : legacy

**Other Information:**

**Comment by telran** [comment]
After update @ionic/app-scripts to 3.0.1 this issue was NOT fixed.

**Comment by janpio** [comment]
This is not an Ionic CLI bug but a bug in cordova-ios 4.5.2 that should be fixed with the next release:
https://issues.apache.org/jira/browse/CB-13454
You can also find a workaround in there.
