### ISSUE TITLE
Ionic lab defaults to --nolivereload

### ISSUE THREAD

**Issue by ahmadtawakol** [ionic-team/ionic-cli#2830]
**Description:**
I just updated ionic cli today and noticed that running `ionic lab` defaults to using the `--nolivereload` flag even though I did not use any flags. If I run `ionic lab --livereload` it works correctly.

**My `ionic info`:**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.1
    ionic (Ionic CLI) : 3.15.1

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.1.2 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v8.4.0
    npm        : 5.4.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**Comment by IsaacSomething** [comment]
I am getting this issue on a basic ionic serve cmd

![error](https://user-images.githubusercontent.com/25283027/32045331-466af598-ba40-11e7-9f33-ca56bd11d47a.jpg)

**Comment by Jeffrey93** [comment]
Same problem what's going on?
I just downgrade to 3.7

**Comment by dwieeb** [comment]
Hmm, that's odd. I'll fix this up right away.
