### ISSUE TITLE
Change in scss is not applied with ionic serve after updating ionic-cli from 3.15.0 to 3.15.1

### ISSUE THREAD

**Issue by vzts** [ionic-team/ionic-cli#2831]
**Description:**

I have updated ionic-cli to 3.15.1 this morning, and I was trying to "ionic serve" to start working on the view as usual. But then the change in scss was not applied automatically. So if I only change scss, the live preview gets spinning and the log says it has built the scss again, but the change is not shown. If I change scss, and then change also the html, then the change in scss and html both applies properly in the browser. I'm thinking it's somewhere in the updates is producing this bug, since until last night before I have updated the cli, none of these symtoms were found.

**Steps to Reproduce:**

Just run 'ionic serve'. Make some changes in scss. The spin will appear which says it's rebuilding the site, but the change in scss won't apply after the reload. If you make another change in html, then the change in scss would finally apply correctly.

Example repo: 
N/A

**Output:**

**My `ionic info`:**

cli packages: (C:\Users\***\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.15.1
    ionic (Ionic CLI) : 3.15.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.4.0
    npm  : 5.3.0 
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Other Information:**

**Comment by vzts** [comment]
I have downgraded the ionic-cli to 3.15.0, and everything is working fine now.
Please have a look into this problem. Thanks.

**Comment by mebibou** [comment]
I think this is the same issue as #2832
