### ISSUE TITLE
Live reloader is not working at all after latest CLI 

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-cli#2832]
The live reloader is not working at all after latest CLI  :(

`Note:` I have downgraded to `3.15.0` and now it works.

Ionic info:

```
 @ionic/cli-utils  : 1.15.1
    ionic (Ionic CLI) : 3.15.1

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    Node              : v6.10.0
    npm               : 3.10.10
    OS                : Windows 8.1

Environment Variables:

    ANDROID_HOME : C:\Program Files (x86)\Android\android-sdk

Misc:

    backend : pro
```

**Comment by vincentfierant** [comment]
Same here!

**Comment by zalog** [comment]
Same here.

**Comment by zarko-tg** [comment]
Confirmed @dwieeb.

![1ya0np](https://user-images.githubusercontent.com/6142411/32044198-2f475fc6-ba3d-11e7-83e3-89448bacfa6e.jpg)

**Comment by IsaacSomething** [comment]
same ... ionic serve by default seems to have the flag --nolivereload

**Comment by botweb** [comment]
Same here, but works using --livereload argument

**Comment by rfoel** [comment]
Can you guys confirm that this is on Windows? Otherwise, this should do the trick:
```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**Comment by Sampath-Lokuge** [comment]
Yes, Hope you can see the `Ionic info` above. @rfoel

**Comment by IsaacSomething** [comment]
Is it just me or is live reload not working properly at all? I have to save the file twice every time in order to get an updated version and sometimes it just reverts back to an older state giving an error that function does not exists, i then have to go to that file, make a change ( any small change ), re save ( twice ) and then it only shows the updated content.

**Comment by amerzad** [comment]
I am using 3.15.2 and it works for HTML changes only, but for ts files, it does not reflect changes.
I tried with --livereload and didn't work.
I downgraded to 3.13.0 step by step and none of them worked. The problem started only from a week or so.
I checked the source file www/build/main.js and found that the changes are not reflected, so it is not related to browser.
I remembered I had a custom webpack merge-webpack.config.js and merge-optimization.config.js, and they are just to allow sharing some of the code from backend, so basicly I need them only for tsconfig paths.
So, I removed them, and copied the files over, and refreshed all the references, and viola, the live reload started to work.
There must be something related to my custom webpack config files.
This is my merge-optimization.config.js:
```javascript

'use strict';

var path = require('path');
var merge = require('webpack-merge');

var projectRootDir = process.env.IONIC_ROOT_DIR;
var appScriptsDir = process.env.IONIC_APP_SCRIPTS_DIR;

var originalConfig = require(path.join(appScriptsDir, 'config', 'optimization.config.js'));
var myChanges = {
  resolve: {
    alias: {
      models: path.join(projectRootDir, 'api/server/imports/models'),
      collections: path.join(projectRootDir, 'api/server/imports/collections')
    }
  }
};
var config = {
  dev: myChanges,
  prod: myChanges
};
// console.log(__filename);
module.exports = merge(originalConfig, config);
```

And this is my merge-webpack.config.js
```javascript

'use strict';

var path = require('path');
var merge = require('webpack-merge');

var projectRootDir = process.env.IONIC_ROOT_DIR;
var appScriptsDir = process.env.IONIC_APP_SCRIPTS_DIR;

var originalConfig = require(path.join(appScriptsDir, 'config', 'webpack.config.js'));
var myChanges = {
  resolve: {
    alias: {
      models: path.join(projectRootDir, 'api/server/imports/models'),
      collections: path.join(projectRootDir, 'api/server/imports/collections')
    }
  },
  externals: [
    resolveExternals
  ],
  node: {
    __dirname: true
  }

}
var config = {
  dev: myChanges,
  prod: myChanges
};
function resolveExternals(context, request, callback) {
  return resolveMeteor(request, callback) ||
      callback();
}

function resolveMeteor(request, callback) {
  var match = request.match(/^meteor\/(.+)$/);
  var pack = match && match[1];

  if (pack) {
    callback(null, 'Package["' + pack + '"]');
    return true;
  }
}
// console.log(__filename);
module.exports = merge(originalConfig, config);

```

**Comment by IsaacSomething** [comment]
I sort of fixed it ( it seems to work a bit better ) by appending `-x` ( no proxy )  and setting my own `-p [port num] -r [livereload port num]

`ionic serve -x -p 1234 -r 12345`

**Comment by amerzad** [comment]
@IsaacSomething 
It didn't work for me!

**Comment by amerzad** [comment]
For my case, the ionic-cli is prompting on change and regenerating, but actually no ts files are regenerated. So I presume I don't need to do:
```bash
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
Yet I tried it and the problem persists.

**Comment by trkoch** [comment]
@amerzad Thanks for the hint! It appears that `webpack-merge` is doing something funny not compatible with Ionic default webpack configuration. I rewrote my customization without using `webpack-merge` and live reloading resumed to work.

**Comment by aaronneon2** [comment]
Hey guys, I managed to fix the broken live reload on my Mac by following the hint found in this issue.
#2757 
Hope it helps.
