### ISSUE TITLE
And again the error - Error: Error code 65 for command: xcodebuild with args:

### ISSUE THREAD

**Issue by Pavelask** [ionic-team/ionic-cli#2833]
> ter: 'command' has no keyword argument name
>     func getAppInfo(_ command: CDVInvokedUrlCommand) -> Void {
>                     ^~
>                     
> /Applications/XAMPP/xamppfiles/htdocs/mobapp/elprof/platforms/ios/MyApp/Plugins/cordova-plugin-ionic/IonicCordovaCommon.swift:8:23: error: use of unresolved identifier 'Bundle'
>         if let info = Bundle.main.infoDictionary {
>                       ^~~~~~
> /Applications/XAMPP/xamppfiles/htdocs/mobapp/elprof/platforms/ios/MyApp/Plugins/cordova-plugin-ionic/IonicCordovaCommon.swift:13:36: error: use of unresolved identifier 'Bundle'
>             let bundleIdentifier = Bundle.main.bundleIdentifier
>                                    ^~~~~~
> /Applications/XAMPP/xamppfiles/htdocs/mobapp/elprof/platforms/ios/MyApp/Plugins/cordova-plugin-ionic/IonicCordovaCommon.swift:14:35: error: type 'UIDevice' has no member 'current'
>             let platformVersion = UIDevice.current.systemVersion
>                                   ^~~~~~~~ ~~~~~~~
> /Applications/XAMPP/xamppfiles/htdocs/mobapp/elprof/platforms/ios/MyApp/Plugins/cordova-plugin-ionic/IonicCordovaCommon.swift:23:41: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsDictionary:')
>             let result = CDVPluginResult(status: CDVCommandStatus_OK, messageAs: infoDict)
>                                         ^                             ~~~~~~~~~
>                                                                       messageAsDictionary
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileSwift normal x86_64 /Applications/XAMPP/xamppfiles/htdocs/mobapp/elprof/platforms/ios/MyApp/Plugins/cordova-plugin-ionic/IonicCordovaCommon.swift
> 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (2 failures)
> Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Applications/XAMPP/xamppfiles/htdocs/mobapp/elprof/platforms/ios/cordova/build-debug.xcconfig,-workspace,MyApp.xcworkspace,-scheme,MyApp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 6s Plus,build,CONFIGURATION_BUILD_DIR=/Applications/XAMPP/xamppfiles/htdocs/mobapp/elprof/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Applications/XAMPP/xamppfiles/htdocs/mobapp/elprof/platforms/ios/build/sharedpch

**Data on ionic info** 

> cli packages: (/usr/local/lib/node_modules)
> 
>     @ionic/cli-utils  : 1.15.1
>     ionic (Ionic CLI) : 3.15.1
> 
> global packages:
> 
>     cordova (Cordova CLI) : 7.1.0 
> 
> local packages:
> 
>     @ionic/app-scripts : 3.0.0
>     Cordova Platforms  : android 6.3.0 ios 4.5.1
>     Ionic Framework    : ionic-angular 3.7.1
> 
> System:
> 
>     ios-deploy : 1.9.2 
>     Node       : v6.11.3
>     npm        : 5.4.2 
>     OS         : OS X Yosemite
>     Xcode      : Xcode 7.2.1 Build version 7C1002 
> 
> Environment Variables:
> 
>     ANDROID_HOME : not set
> 
> Misc:
> 
>     backend : pro
> 

> npm -v
> 5.4.2

What can I do? What information can I provide to solve this problem?

**Comment by dwieeb** [comment]
@Fuiste Looks like our plugin isn't compiling?

**Comment by Fuiste** [comment]
I'm able to build just fine with the latest version of `cordova-plugin-ionic` using both the CLI as well as the Ionic Pro dashboard.

One possible area of interest; I notice you're on an older version of MacOS + Xcode.  When I tested, I was using Xcode 9/

**Comment by brunolm** [comment]
iOS

- Open `platforms/ios` on XCode
- Find & Replace `io.ionic.starter` in all files for a unique identifier
- Click the project to open settings
- Signing > Select a team
- Go to your device Settings > General > DeviceManagement
  - Trust your account/team
- `ionic cordova run ios --device --livereload`

**Comment by sebitoelcheater** [comment]
use 
"cordova-ios": "^5.0.1"
