### ISSUE TITLE
ionic@3.15.2 reports itself as 3.15.1, keeps asking to update

### ISSUE THREAD

**Issue by FdezRomero** [ionic-team/ionic-cli#2840]
**Description:**
Just updated the Ionic CLI to 3.15.1, but kept asking to update to 3.15.2.

My guess is that the internal version in the CLI needs to be bumped, so it will stop asking to update (and will show the right version as well).

**Steps to Reproduce:**

1. `ionic -v` returns 3.15.1
2. `npm ls -g depth=0` returns 3.15.2, same as npm output after install

**Output:**

**My `ionic info`:**

**Other Information:**

cli packages: (/usr/local/Cellar/node/8.7.0/lib/node_modules)

    @ionic/cli-utils  : 1.15.1
    ionic (Ionic CLI) : 3.15.1 <-- Actually 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1-201710201922

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v8.7.0
    npm        : 2.15.12 <-- Actually 5.5.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**Comment by dwieeb** [comment]
That's odd, We use `package.json` to determine the version.

**Comment by FdezRomero** [comment]
Completely removing `ionic` and installing `ionic@latest` again seems to have solved the problem, weird. Closing for now, will reopen if it happens again. Thanks @dwieeb!
