### ISSUE TITLE
every time i try to create a new blank app it says like this

### ISSUE THREAD

**Issue by leul12** [ionic-team/ionic-cli#2848]
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: connect ECONNREFUSED 192.30.253.112:443
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
Error Initializing app: Error: connect ECONNREFUSED 192.30.253.112:443
 Error: connect ECONNREFUSED 192.30.253.112:443
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)

**Comment by leul12** [comment]
i tried npm install -g ionic@latest but then 

√ Creating directory .\myApp - done!
Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
× Downloading - failed!
Error: connect ECONNREFUSED 192.30.253.113:443
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
this error appeared i need help guys new for this thinhgs

**Comment by dwieeb** [comment]
@leul12 Are you behind a firewall? If so, you'll need to configure the CLI for your proxy settings: https://ionicframework.com/docs/cli/configuring.html#using-a-proxy

**Comment by leul12** [comment]
i am in a university internet coverage but i have configured the proxy i don't think its with proxy setting

**Comment by dwieeb** [comment]
If you're able to access Github in your browser but the Ionic CLI is unable to (192.30.253.112 is Github's IP), then it's 99% a proxy issue. Please run the command with `--verbose` and let me see your `ionic info` output.

**Comment by dwieeb** [comment]
You likely need to configure your environment for your network proxy:

* Please carefully follow the docs: https://ionicframework.com/docs/cli/using-a-proxy
* Your organization needs to provide proxy details for you. If you don't know the details, talk with your network administrator.
* Remember to avoid disabling SSL verification. This can lead to prolonged insecure configuration with your computer.
