### ISSUE TITLE
Error: Cannot find module '@ionic/cli-framework/utils/fs'

### ISSUE THREAD

**Issue by evknz** [ionic-team/ionic-cli#2849]
Since last update I got this error when I run "ionic info" command:

Error: Cannot find module '@ionic/cli-framework/utils/fs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@ionic/cli-plugin-proxy/node_modules/@ionic/cli-utils/lib/utils/npm.js:8:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Any ideas?

**Comment by lucasbsrs** [comment]
Try removing all node_modules folders, package-lock.json and www/index.html.
Then run npm install. Make sure no instances of your app are running.

**Comment by cambronjay** [comment]
I am getting this same issue and have been getting it every time I do ionic start. Except mine says Error: Cannot find module '@ionic/cli-framework/utils/fs' Looks like there is an issue with latest CLI

**Comment by cambronjay** [comment]
It would appear the module is actually missing because the installation of that module has been removed from the cli-framework package.json

**Comment by cambronjay** [comment]
Looks like it has something to do with webpack https://github.com/webpack-contrib/css-loader/issues/447

**Comment by dwieeb** [comment]
@evknz @cambronjay Make sure that proxy plugin is up to date. `npm i @ionic/cli-plugin-proxy@latest`

**Comment by hmoratopcs** [comment]
The [package.json of @ionic/cli-utlis](https://github.com/ionic-team/ionic-cli/blob/master/packages/%40ionic/cli-utils/package.json) lists `@ionic/cli-framework` in `devDependencies ` ¿Shouldn't it be in `dependencies` because it is imported at [npm.ts](https://github.com/ionic-team/ionic-cli/blob/master/packages/%40ionic/cli-utils/src/lib/utils/npm.ts)?

**Comment by evknz** [comment]
I don't know what else to do. I only could solve this just stepping back to the ionic@3.7.0 and the error stopped. 

However, it seems to be a silly mistake and it could/should be already fixed by the team. 

From ionic@3.7.0 to the latest ionic@3.15.2 (today) is ruge difference between both versions.

**Comment by shahramSo** [comment]
I removed package-lock.json and try " npm uninstall cordova ionic" and this  resolved this issue for me.

**Comment by cambronjay** [comment]
@shahramSo  where was your package lock located?

**Comment by hmoratopcs** [comment]
Quick and dirty fix: `npm install @ionic/cli-framework -g`

**Comment by cambronjay** [comment]
@hmoratopcs  this worked. I wonder why this worked when the actual install or update of the ionic cli does not?

**Comment by ryaa** [comment]
Downgrading to 3.15.0 fixed the problem. Just run npm install ionic@3.15.0 --save-dev --save-exact

I noticed that even though ionic prompted to upgrade to 3.15.2 this version is not listed in the releases list here yet https://github.com/ionic-team/ionic-cli/releases
The latest release is 3.15.1 (as of now)

**Comment by evknz** [comment]
Hi, @ryaa.

I did what you said and works fine for me now. 

Seems 3.15.2 version really has a bug. 

Thank you!

**Comment by synclary** [comment]
supprimer npm et npm-cache sur C:\Users\[User]\AppData\Roaming (pour moi ça a marché)
