### ISSUE TITLE
Unable to create an Ionic Project

### ISSUE THREAD

**Issue by aabhishekGhosh** [ionic-team/ionic-cli#2851]
**Description:**

npm: 5.5.1
Node: v7.9.0
Ionic: 3.15.2
Cordova: 7.1.0

With above mentioned versions, whenever i try to create a new ionic project i get the below error.

D:\Workspace\IONIC>ionic start myIonicApp tabs --type=ionic-angular --verbose
[DEBUG] Reason for not using local CLI: BASE_DIRECTORY_NOT_FOUND
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'D:\\Workspace\\IONIC', local: false, binPath:
        'C:\\Users\\Abhishek\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic',
        libPath:
        'C:\\Users\\Abhishek\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js'}
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Latest plugin version of @ionic/cli-plugin-proxy is 1.5.2, according to daemon file.
[DEBUG] Daemon found (pid: 9344)
[WARN] Git CLI not found on your PATH. You may wish to install it to version control your app.
       See installation docs for git:
       https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

       Use --no-git to disable this warning.

Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
x Downloading - failed!
Error: connect ECONNREFUSED 192.30.255.112:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
[DEBUG] Error: connect ECONNREFUSED 192.30.255.112:443
            at Object.exports._errnoException (util.js:1050:11)
            at exports._exceptionWithHostPort (util.js:1073:20)
            at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

Kindly help anyone!

**Comment by dwieeb** [comment]
@aabhishekGhosh You are likely behind a firewall and need to configure proxy settings: https://ionicframework.com/docs/cli/configuring.html#using-a-proxy
