### ISSUE TITLE
Ionic CLI 3.16 issue  => Error: send EHOSTDOWN

### ISSUE THREAD

**Issue by ohrrkan** [ionic-team/ionic-cli#2853]
Hi,

Since the update Getting an Error loop of  :

[ERROR] Error in DevApp service: Error: send EHOSTDOWN 169.254.255.255:41234

             at Object._errnoException (util.js:1041:11)
             at _exceptionWithHostPort (util.js:1064:20)
             at SendWrap.afterSend [as oncomplete] (dgram.js:474:11)

Did you try to reach an IP? 

**ionic info :** 

@ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2
    Node       : v8.4.0
    npm        : 5.5.1
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by sfaizanh** [comment]
Same issue 
```
[ERROR] Error in DevApp service: Error: send EHOSTDOWN 169.254.255.255:41234

             at Object.exports._errnoException (util.js:1020:11)
             at exports._exceptionWithHostPort (util.js:1043:20)
             at SendWrap.afterSend [as oncomplete] (dgram.js:405:11)
```

**Comment by dwieeb** [comment]
Hey all, these errors are poorly displayed. They simply mean the DevApp broadcast didn't work on one of the network interfaces, which is okay--connectivity with the DevApp should still work and this by no means affects `ionic serve` itself.

I will add a task to cleanup the error messages.

**Comment by peterpeterparker** [comment]
@ohrrkan @dwieeb have you try adding `--local` to your cmd? respectively `ionic serve --local`?

according the CHANGELOG of 3.16.0 this option will disable the external network broadcast and therefore you should avoid this error

**Comment by jQrgen** [comment]
Same error, fixed by reverting to 3.15.2:

```
npm uninstall -g ionic
npm install -g ionic@3.15.2
```

**Comment by dwieeb** [comment]
As I explained, it's a meaningless and non-fatal error. There is no reason to downgrade or add flags.

**Comment by jQrgen** [comment]
True, but my eyes are bleeding from all the red Error messages in the console x)

**Comment by jQrgen** [comment]
+ seems to be loading very slowly in browser, staying on 3.15.2 for now.

**Comment by mmolhoek** [comment]
@peterpeterparker but then you don't see the app in DevApp anymore :)

**Comment by peterpeterparker** [comment]
@mmolhoek understood

**Comment by Jatapiaro** [comment]
Do someone has the problem that the serve don't loads in your default browser? In my case Chrome is the default browser but safari is loaded instead
