### ISSUE TITLE
ionic cordova build andrid  error code E404

### ISSUE THREAD

**Issue by Cloud33** [ionic-team/ionic-cli#2856]
>ionic cordova build andrid

 cordova platform add andrid --save
Using cordova-fetch for andrid
Error: Failed to fetch platform andrid
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found: andrid@latest

npm ERR! A complete log of this run can be found in:
log：
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install',
1 verbose cli 'andrid',
1 verbose cli '--production',
1 verbose cli '--save-exact' ]
2 info using npm@5.5.1
3 info using node@v6.11.4
4 verbose npm-session 0a8e002d56671aeb
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npm.taobao.org/andrid 33829ms
8 silly fetchPackageMetaData error for andrid@latest 404 Not Found: andrid@latest
9 verbose stack Error: 404 Not Found: andrid@latest
9 verbose stack at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack at runCallback (timers.js:672:20)
9 verbose stack at tryOnImmediate (timers.js:645:5)
9 verbose stack at processImmediate [as _immediateCallback] (timers.js:617:5)
10 verbose cwd C:\node\cordova\xxx
11 verbose Windows_NT 10.0.15063
12 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "andrid" "--production" "--save-exact"
13 verbose node v6.11.4
14 verbose npm v5.5.1
15 error code E404
16 error 404 Not Found: andrid@latest
17 verbose exit [ 1, true ]

But Android already exists.

>ionic cordova platform list

cordova platform ls
Installed platforms:
  android 6.3.0
  ios 4.5.3
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~5.0.0
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0

**Comment by Cloud33** [comment]
log：
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'andrid',
1 verbose cli   '--production',
1 verbose cli   '--save-exact' ]
2 info using npm@5.5.1
3 info using node@v6.11.4
4 verbose npm-session 0a8e002d56671aeb
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npm.taobao.org/andrid 33829ms
8 silly fetchPackageMetaData error for andrid@latest 404 Not Found: andrid@latest
9 verbose stack Error: 404 Not Found: andrid@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:672:20)
9 verbose stack     at tryOnImmediate (timers.js:645:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
10 verbose cwd C:\node\cordova\xxx
11 verbose Windows_NT 10.0.15063
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "andrid" "--production" "--save-exact"
13 verbose node v6.11.4
14 verbose npm  v5.5.1
15 error code E404
16 error 404 Not Found: andrid@latest
17 verbose exit [ 1, true ]

**Comment by dwieeb** [comment]
You made a typo. It's `android`, not `andrid`.

**Comment by geongeorge** [comment]
@dwieeb  You saved my life! I made the same mistake and if it weren't for you I'd be stuck at this for the rest of my life

**Comment by BainViljoen** [comment]
hahahaahah i just did andriod... this save me

**Comment by numanayhan** [comment]
Thanks :D

**Comment by Cloud33** [comment]
@dwieeb  I've dealt with this problem, I'm too careless, thank you.

**Comment by lawphotog** [comment]
Lol Cloud you're not the only one who can't spell Andriod, i made the same mistake and landed on this page :D it's actually helpful. xD

**Comment by jigarce** [comment]
> You made a typo. It's `android`, not `andrid`.

True !, Thanks

**Comment by shekhars271991** [comment]
> @dwieeb You saved my life! I made the same mistake and if it weren't for you I'd be stuck at this for the rest of my life

me too!
