### ISSUE TITLE
ionic cordova platform add android failed

### ISSUE THREAD

**Issue by henryhe1993** [ionic-team/ionic-cli#2860]
run:
ionic cordova platform add android

output:
Using cordova-fetch for cordova-android@^6.3.0

Error: Failed to fetch platform cordova-android@^6.3.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Unexpected end of input at 1:73841
npm ERR! rg/cordova-android/-/cordova-android-5.3.0-nightly.2016.9.12.d2a159d2
npm ERR!                 

environment:
node: 8.5.0
npm: 5.3.0
ionic: 3.16.0
ionic/cli-utils  : 1.16.0
cordova: 7.1.0

It used to be fine, and I guess it is not my connection problem. Any help will be appreciated.

------------------------------------
It is working now. Seems like there was a problem with the repo. Sorry about this issue.

**Comment by sahilmo** [comment]
@henryhe1993 Can you please describe which repo , i am also getting the error.

ionic cordova platform add android
> cordova platform add android --save
Using cordova-fetch for cordova-android@6.3.0

Error: Failed to fetch platform cordova-android@6.3.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by houyewei** [comment]
same problem

**Comment by zompad** [comment]
I've also got the same problem:-

> cordova platform add android --save
Using cordova-fetch for cordova-android@6.3.0

Error: Failed to fetch platform cordova-android@6.3.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
