### ISSUE TITLE
--local stopped working, using 3.16.0 

### ISSUE THREAD

**Issue by Ben1nBlack** [ionic-team/ionic-cli#2867]
**Description:**

ionic serve --lab --local just stops

> /usr/local/bin/ionic serve --lab --local
Starting app-scripts server: --address localhost --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser --lab - Ctrl+C to cancel
[22:14:00]  watch started ... 
[22:14:00]  build dev started ... 

I was working with and it just stopped while i tested

I can do every thing if i remove **--local**

**Steps to Reproduce:**

Example repo: 

1. have CLI 3.16.0 installed
2. $ ionic serve --lab --local
3. stops at build dev started ...  

**Output:**

**My `ionic info`:**

**Other Information:**

`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : browser 5.0.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.0

System:

    ios-deploy : 1.9.2 
    Node       : v8.6.0
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
`

**Comment by dwieeb** [comment]
Hmm, seems to work for me for `@ionic/app-scripts` 3.0.1 and 3.1.0. It also works with my wifi off. How long have you let it run?

**Comment by Ben1nBlack** [comment]
it was nothing i had done, i changed nothing, i had been working on 3.16.0 since it came out without any change, I was in using ionic serve --local, and was looking and it and just stopped and crashed my webstorm out. when i restarted, I can do all but if --local is in, it just stops. 

Please make a 3.16.5 with out the spamming. being new im not sure of the ramifications of loosing Cordova

**Comment by Ben1nBlack** [comment]
> How long have you let it run?

I let it run for 10min+ it just sits there.

Can I get any feedback on this, now that 3.18.0 is out and no mention of --local
I paid for a Pro license ;-), I just need to know direction

**Comment by Ben1nBlack** [comment]
ok, I updated to 3.18.0,  my main project was setup prior to these new changes 
so when i run
`ionic serve --local --verbose`

`Ben-Johansens-Mac-Pro-2:DrugPricingTool benjohansen$ ionic serve --local --verbose
[DEBUG] Reason for not using local CLI: LOCAL_CLI_NOT_FOUND
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: '/Users/benjohansen/WebstormProjects/DrugPricingTool', local: false, binPath: 
        '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic/dist/index.js' }
Starting app-scripts server: --address localhost --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser 
- Ctrl+C to cancel
[00:00:12]  watch started ... 
[00:00:12]  build dev started ... 
`
How can I add local cli to this main project?

**Comment by Ben1nBlack** [comment]
I ran 
npm install --save-dev --save-exact ionic@latest
in my DrugPricingTool folder now when I run 

ionic serve --local --verbose

`
Ben-Johansens-Mac-Pro-2:DrugPricingTool benjohansen$ ionic serve --local --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: '/Users/benjohansen/WebstormProjects/DrugPricingTool', local: true, binPath: 
        '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: 
        '/Users/benjohansen/WebstormProjects/DrugPricingTool/node_modules/ionic/dist/index.js' }
Starting app-scripts server: --address localhost --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser 
- Ctrl+C to cancel
[00:17:58]  watch started ... 
[00:17:58]  build dev started ... 
`

**Comment by dwieeb** [comment]
My guess is something about your computer doesn't like a server binding on the address `localhost` and it hangs, whereas binding to `0.0.0.0` (all network interfaces) is fine. To test, please try running the following scripts and testing the output by opening your browser to `http://localhost:5000`:

`allinterfaces.js`
```javascript
var http = require("http");
var server = http.createServer(function(request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.write("Hello World");
  response.end();
});

server.listen(5000, '0.0.0.0');
console.log("Server is listening");
```

`localhost.js`
```javascript
var http = require("http");
var server = http.createServer(function(request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.write("Hello World");
  response.end();
});

server.listen(5000, 'localhost');
console.log("Server is listening");
```

**Comment by Ben1nBlack** [comment]
Thanks for response.

I went ahead and updated to 3.18.0 (I purchase pro license) and I figured I should be at latest.)

this lead to other issues ;-)
(I'm using WebStorm for development)
when i changed to different projects and ran ionic serve no matter which one it ran my main app
I found in WebStorm that I needed to  check [x] Single Instance only in my run configs

so on 3.18.0 i can now move around and run both "ionic serve" and "ionic serve --local"

thanks again for reply, I know your busy

**Comment by dwieeb** [comment]
What were the other issues... ?

Wait, so is this fixed for you?

**Comment by Ben1nBlack** [comment]
not sure if this is still issue in 3.16.0

but as for me and this issue, you can say it's resolved.

**Comment by dwieeb** [comment]
@Ben1nBlack Okay, great. I will investigate how the CLI works with WebStorm.
