### ISSUE TITLE
ionic doctor check fails if config.xml doesn't exist

### ISSUE THREAD

**Issue by SeijiSuenaga** [ionic-team/ionic-cli#2868]
**Description:**
`ionic doctor check` fails if config.xml doesn't exist.

**Steps to Reproduce:**
I had an existing PWA project with a config.xml file.  Since the Ionic CLI 3.17.0 changelog notes said new apps won't have config.xml if Cordova isn't used, I deleted the file.  Then, I ran `ionic doctor check`.

**Output:**
```
[WARN] For best results, please make sure you're logged in to Ionic.

       Some issues can't be detected without authentication. Run:

            ionic login

× Detecting issues: 5 / 16 complete - failed!
Error: ENOENT: no such file or directory, open 'E:\Projects\ionic\config.xml'
    at Error (native)
```

**My `ionic info`:**
```
cli packages: (C:\Users\username\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:

    Gulp CLI : not installed globally

local packages:

    @ionic/app-scripts : 3.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.1
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : legacy
```

**Comment by dwieeb** [comment]
Thanks @SeijiSuenaga - I had a line out of order. I also fixed this such that when it tries to detect an issue that throws an error, it just logs the error.

**Comment by dwieeb** [comment]
If you haven't already, you can also remove `resources/` if you're not using it.
