### ISSUE TITLE
ionic start myApp blank

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/ionic-cli#2876]
**Description:**

When I run ionic start and it starts to run npm i (or I run npm i by myself) an error saying npm ERR! code EINTEGRITY happens. 

It also mention about sha1something integrity checksum failed when using sha1: wanted sha1something but got sha1somethingelse

**Steps to Reproduce:**

ionic 3.18.0

Example repo: 

1. ionic start myapp blank

**Output:**

**My `ionic info`:**

**Other Information:**

this was on the debug.log generated:
****info about extracting packages and then this comes after*****
```
8511 verbose unlock done using /Users/bandito/.npm/_locks/staging-23465838a0e12cf8.lock for /Users/bandito/Projects/assistanceApp/node_modules/.staging
8512 verbose type Error
8513 verbose stack Error: sha1-+DlfhdRZJ2BnyYiqQYN6j4KHCEQ= integrity checksum failed when using sha1: wanted sha1-+DlfhdRZJ2BnyYiqQYN6j4KHCEQ= but got sha1-CjscuUAn+DHGYAEeeXqXnT5Lxq4=. (1572491 bytes)
8513 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
8513 verbose stack     at emitNone (events.js:111:20)
8513 verbose stack     at Transform.emit (events.js:208:7)
8513 verbose stack     at endReadableNT (_stream_readable.js:1056:12)
8513 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
8513 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
8514 verbose cwd /Users/bandito/Projects/assistanceApp
8515 verbose Darwin 16.7.0
8516 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
8517 verbose node v8.9.0
8518 verbose npm  v5.5.1
8519 error code EINTEGRITY
8520 error sha1-+DlfhdRZJ2BnyYiqQYN6j4KHCEQ= integrity checksum failed when using sha1: wanted sha1-+DlfhdRZJ2BnyYiqQYN6j4KHCEQ= but got sha1-CjscuUAn+DHGYAEeeXqXnT5Lxq4=. (1572491 bytes)
8521 verbose exit [ 1, true ]


```

**Comment by dwieeb** [comment]
The integrity check failure means that a downloaded package archive does not match what the server is reporting it should. This is a security check--but it usually means something messed with the connection somehow.

Are you behind a proxy?

**Comment by Bandito11** [comment]
I am not. Did a quick web search after reading your post and it could be my internet connection. Was hit by Hurricane Maria back at PR and I am using my cellphone hotspot connection which is slow at best. I am able to watch youtube videos and such but the speed is not optimal. Maybe that's what's wrong. It only happens with my Mac Mini though, I can download stuff easily on my windows 10 laptop. Maybe I'll use that to code for now :(
