### ISSUE TITLE
--link option when add a plugin

### ISSUE THREAD

**Issue by ygModesto** [ionic-team/ionic-cli#2881]
Hi everybody,

I would like to use the option '--link' of Cordova for plugins.
Example: `cordova plugin add <path> --link`

With --link option, the plugin files inside app are symbolic links to <path> (where 'path' is a path in my local file system, it is not a url), so it is very useful for developing plugins, however ionic-cli erases that option and doesn't pass it to Cordova. 
Example: `ionic cordova plugin add <path> --link`

Could it be added to ionic-cli?

Thank you very much.

**Comment by timbru31** [comment]
You can use `ionic cordova plugin add <path> -- --link` (yes `-- --`)

**Comment by dwieeb** [comment]
Yes, to pass extra args or options to Cordova, separate them with `--`. We will not be adding the `--link` option to `ionic cordova plugin add` because it is out of scope for Ionic CLI users.

Plugin developers are encouraged to use the Cordova CLI directly.
