### ISSUE TITLE
I got error while install ionic. How can I solve that issue.

### ISSUE THREAD

**Issue by Anbarasan-321** [ionic-team/ionic-cli#2882]
C:\>npm install -g ionic cordova
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
C:\Users\123\AppData\Roaming\npm\cordova -> C:\Users\123\AppData\Roaming\npm\node_
modules\cordova\bin\cordova
C:\Users\123\AppData\Roaming\npm\ionic -> C:\Users\123\AppData\Roaming\npm\node_mo
dules\ionic\bin\ionic
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\ion
ic\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"
})

+ cordova@7.1.0
+ ionic@3.18.0
added 116 packages and updated 2 packages in 121.66s

**Comment by Vicky443** [comment]
Hi Anbarasan, 
Kindly let us know your **ionic info** or update your node package

**Comment by dwieeb** [comment]
@Anbarasan-321 There are no errors here, just warnings. These are the packages installed:
```
cordova@7.1.0
ionic@3.18.0
added 116 packages and updated 2 packages in 121.66s
```

**Comment by dhinakaranape** [comment]
How to fix this problem??? help mee

C:\Users\dhina>npm install -g cordova
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! path C:\Users\dhina\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\ansistyles
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\dhina\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\ansistyles' -> 'C:\Users\dhina\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dhina\AppData\Roaming\npm-cache\_logs\2017-12-15T12_46_06_571Z-debug.log

**Comment by dwieeb** [comment]
@dhinakaranape Looks like you may have cordova installed already. Try `npm uninstall -g cordova` and installing again.

**Comment by costa974** [comment]
I solved it downgrading npm:
npm install -g npm@5.3.0

**Comment by masyoudi** [comment]
@costa974 yeay thats work. thank you
