### ISSUE TITLE
Build failed error

### ISSUE THREAD

**Issue by Lahgigabyte** [ionic-team/ionic-cli#2883]
Hi,
I have Cordova 7.1
          Node v8.9.1
              Client.git 2.15.0
 
When i add platform with :
cordova platform add ios  
 
result 

> **OS project created with cordova-ios@4.5.3  
> Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project  
> Installing "cordova-plugin-statusbar" for ios  
> Saved plugin info for "cordova-plugin-statusbar" to config.xml  
> Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project  
> Installing "cordova-plugin-device" for ios  
> Saved plugin info for "cordova-plugin-device" to config.xml  
> Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project  
> Installing "cordova-plugin-splashscreen" for ios  
> Saved plugin info for "cordova-plugin-splashscreen" to config.xml  
> Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project  
> Installing "cordova-plugin-whitelist" for ios  
> Saved plugin info for "cordova-plugin-whitelist" to config.xml  
> Error: Path must be a string. Received undefined`
> OS project created with cordova-ios@4.5.3  
> Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project  
> Installing "cordova-plugin-statusbar" for ios  
> Saved plugin info for "cordova-plugin-statusbar" to config.xml  
> Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project  
> Installing "cordova-plugin-device" for ios  
> Saved plugin info for "cordova-plugin-device" to config.xml  
> Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project  
> Installing "cordova-plugin-splashscreen" for ios  
> Saved plugin info for "cordova-plugin-splashscreen" to config.xml  
> Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project  
> Installing "cordova-plugin-whitelist" for ios  
> Saved plugin info for "cordova-plugin-whitelist" to config.xml  
> Error: Path must be a string. Received undefined**
> 

 
I dont understand
 
so i check requirements for ios with :
 
**

> cordova requirements ios

**
 
result :
 
**

> Requirements check results for ios:  
> Apple macOS: installed darwin  
> Xcode: installed [object Object]  
> ios-deploy: installed [object Object]  
> CocoaPods: installed [object Object]

**  
 
So i try to build with
cordova build ios  
 
result :

> **Error: Path must be a string. Received undefined**

 
 
I try to open my project.xcodeproj
i select my Team on signing
and i try to build but error :
 

**> CordovaLib Group  
> Apple LLVM 9.0 Error Group  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_8_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-fea69857  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_a_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-a701c285  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_d_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-d46b04fa  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_3_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-6750c5f9  
> Failed writing record 'objc-auto.h-9LCKUCG3TEW2': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_2_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/W2/objc-auto.h-9LCKUCG3TEW2-temp-aba92a8f  
> Failed writing record 'object.h-2YC9SGVN0DCKI': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_1_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/KI/object.h-2YC9SGVN0DCKI-temp-d4f56eee  
> Failed writing record 'source.h-3VPBTKWOHD9DB': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_8_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/DB/source.h-3VPBTKWOHD9DB-temp-6de7f481  
> Failed writing record 'CFStringTokenizer.h-3KZAPEWGS2V8A': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_1_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/8A/CFStringTokenizer.h-3KZAPEWGS2V8A-temp-b96a4c40  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_f_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-5af52fa3  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_7_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-2cbd2c56  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_0_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-730821b9  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_7_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-9e4ca48b  
> Failed writing record 'objc-auto.h-9LCKUCG3TEW2': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_6_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/W2/objc-auto.h-9LCKUCG3TEW2-temp-47dbf4e9  
> Failed writing record 'object.h-2YC9SGVN0DCKI': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_1_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/KI/object.h-2YC9SGVN0DCKI-temp-a714c833  
> Failed writing record 'source.h-3VPBTKWOHD9DB': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_7_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/DB/source.h-3VPBTKWOHD9DB-temp-68d0d0e8  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_3_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-6f348d9e  
> Failed writing record 'objc-auto.h-9LCKUCG3TEW2': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_f_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/W2/objc-auto.h-9LCKUCG3TEW2-temp-7f0689cb  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_b_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-2b9ab6a0  
> Failed writing record 'dlfcn.h-3LULN766DQY5R': failed to create temporary file: /Users/Andyvie/Library/Developer/Xcode/DerivedData/100_c_papa-gezefuknqqrnjofojnvurvnfnuus/Index/DataStore/v5/records/5R/dlfcn.h-3LULN766DQY5R-temp-36c17ece  
> Too many errors emitted, stopping now**

  
Can u help me plz  Thanks.

**Comment by Vicky443** [comment]
Hi , 
could you pls send your complete **ionic info** details

**Comment by neojato** [comment]
@Vicky443 I'm getting the same error when I attempt either `cordova build ios` or `cordova build android`

Here is my Ionic Info:
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v6.11.1
    npm               : 2.15.12
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : ~/Library/Android/sdk/

Misc:

    backend : pro
```

**Comment by neojato** [comment]
I discovered after running `cordova build android --verbose` that the error **Error: Path must be a string. Received undefined** was actually coming from one of my custom Ionic Hooks. 

Not sure if this solves for everyone, but definitely more verbose error handling/messages would be appreciated within ionic-cli as Googling this error phrase leads down many, many rabbit holes.

**Comment by dwieeb** [comment]
I'm not sure if there's much we can do here. I assume you mean [Cordova hooks](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/), @neojato? 

The Ionic CLI has no code between Cordova and Cordova hooks. Feel free to open an issue with Cordova to provide improved error messaging if this is still an issue.

**Comment by neojato** [comment]
While yes you are "technically" correct @dwieeb that in the end it is Cordova hooks where these hooks are executed (and where this error stemmed from) but they were previously referred to in the Ionic docs/GitHub/etc. as [Ionic Package Hooks](https://github.com/ionic-team/ionic-package-hooks).

**Comment by dwieeb** [comment]
I think the repo you linked to explains what the Ionic Package hooks were pretty well.

> Cordova hooks that you can run in Ionic Package 

> The hooks in this repository are hooks that you can run during the packaging of your app. Ionic Package uses Cordova, so these are just standard Cordova Hooks that we've selected/accepted.

Ionic Package was a commercial service offered as part of Ionic Cloud, which is no longer a thing. In [Ionic Pro](https://ionicframework.com/pro), its successor, you can run any Cordova hooks you want.

**Comment by neojato** [comment]
Thanks for restating my comment, but you missed the whole thing entirely. At the time this issue was created, Ionic Cloud was still in use (albeit on it's way out) as well as the Ionic documentation still referring to it as well as Ionic Package Hooks. Which yes, are the same exact thing in the end as Cordova Hooks.

So yes, this whole back-and-forth stems from you trying to correct my terminology... which was correct at the time of the original posting of the issue. Thanks for showing up on a dead issue and trying to correct it 7 months later.

**Comment by dwieeb** [comment]
I wasn't correcting your terminology. I was trying to confirm where the error was coming from, as well as trying to explain why the Ionic CLI can't do much about this, re: this request:

> more verbose error handling/messages would be appreciated within ionic-cli

I was just confirming that it's alright to close this issue. I'm trying to clean up issues so they don't go unnoticed for 7 months. 😆
