### ISSUE TITLE
can't login with with ionic login command

### ISSUE THREAD

**Issue by brettatoms** [ionic-team/ionic-cli#2884]
**Description:**
When i try to `ionic login` from the cli i get the “No user found by that email”. When I then do `ionic signup` it opens the signup page in my browser which immediately redirects to `dashboard.ionicjs.com` where i’m signed in.

I reset my password just to double check I had the write password but that doesn’t help either.

**Steps to Reproduce:**
`> ionic login`

Response: 
```
Request: POST https://api.ionic.io/login
Response: 404
Body:
{ type: 'NotFound',
  message: 'No user found by that email',
  link: null }
```
`> ionic signup`

Opens  `https://dashboard.ionicjs.com/signup` but immediately redirects to `https://dashboard.ionicjs.com/apps` where I'm logged in.

**My `ionic info`:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 5.1.0
    Node              : v8.7.0
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : /Users/brett/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by dwieeb** [comment]
@brettatoms Looks like your CLI is configured for our legacy services. Please try this:

```
ionic config set -g backend pro
```

And login again.

**Comment by brettatoms** [comment]
That worked, thanks.
