### ISSUE TITLE
Erro Ionic Serve

### ISSUE THREAD

**Issue by joaovelozo** [ionic-team/ionic-cli#2888]
Running 'serve:before' npm script before serve
> ionic-hello-world@ watch C:\MoveFun
> ionic-app-scripts watch
C:\MoveFun\node_modules\node-sass\lib\index.js:13
    throw new Error(errors.unsupportedEnvironment());
    ^

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.9.3
    at Object.<anonymous> (C:\MoveFun\node_modules\node-sass\lib\index.js:13:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\MoveFun\node_modules\@ionic\app-scripts\dist\sass.js:7:16)
    at Module._compile (module.js:635:30)

npm
 ERR! code ELIFECYCLE
npm ERR! errno 1

npm
 ERR!
 ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1

npm
 ERR!
npm ERR! Failed at the ionic-hello-world@ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JoaoVelozo\AppData\Roaming\npm-cache\_logs\2017-11-19T20_11_09_833Z-debug.log

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by dwieeb** [comment]
@joaovelozo Need your `ionic info`. Please fill out the issue template.

**Comment by joaovelozo** [comment]
Your system information:

Cordova CLI: Not installed
Gulp version:  CLI version 1.4.0
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v8.9.1


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

**Comment by dwieeb** [comment]
@joaovelozo I recommend updating `node-sass` to the latest version, if you aren't already. Compatibility charts can be found here: https://github.com/sass/node-sass/releases

Also please update your Ionic CLI version. `npm i -g ionic@latest` The version you're on is very old.

**Comment by joaovelozo** [comment]
C:\>npm i -g ionic@latest
C:\Users\JoaoVelozo\AppData\Roaming\npm\ionic -> C:\Users\JoaoVelozo\AppData\Roaming\npm\node_modules\ionic\bin\ionic
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\ionic\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ionic@3.19.0
added 265 packages, removed 859 packages, updated 39 packages and moved 1 package in 296.968s

C:\>cd movefun

C:\MoveFun>ionic serve
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.9.3
    at Object.<anonymous> (C:\MoveFun\node_modules\node-sass\lib\index.js:13:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\MoveFun\node_modules\@ionic\app-scripts\dist\sass.js:7:16)
    at Module._compile (module.js:635:30)

**Comment by dwieeb** [comment]
3.9.3 was released on Sep 6, 2016. Look at releases to see the latest versions: https://github.com/sass/node-sass/releases
