### ISSUE TITLE
ionic ssh setup [error] no error message

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-cli#2891]
**Description:**

`ionic ssh setup` is showing an error which is called by `ionic link --pro-id IDHERE` and `ionic login`.

No error message is being produced though, just a line that says `[error]`.

Tried updating to `ionic@latest`. 

Tried logging out and in again. 

Checked user folder for `.ssh\` but that folder doesn't exist.

**Steps to Reproduce:**

In the app folder type any of these:

1. `ionic login`
2. `ionic link`
3. `ionic ssh setup`

**Output:**

```
λ ionic link --pro-id IDHERE
> ionic ssh setup
[ERROR]
```

```
λ ionic login MYUSERNAME MYPASSWORD
[WARN] You are already logged in as matthew@emailaddress! Attempting login.
Logging you out.
> ionic logout
[OK] You are logged out.
[OK] You are logged in!
> ionic ssh setup
[ERROR]
```

```
λ ionic ssh setup --verbose                                                                             
[DEBUG] Reason for not using local CLI: LOCAL_CLI_NOT_FOUND                                             
[DEBUG] CLI flags: { interactive: true, confirm: false }                                                
[DEBUG] { cwd: 'D:\\rtp\\Ionic\\AppNameHere', local: false, binPath:                        
        'C:\\Users\\rtpha\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:            
        'C:\\Users\\rtpha\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js' }                
[DEBUG] Daemon found (pid: 6736)                                                                        
[ERROR]                                                                                                 
```

**My `ionic info`:**

cli packages: (C:\Users\rtpha\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

local packages:

    @ionic/app-scripts : 3.1.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.2
    npm  : 3.10.10
    OS   : Windows 10, 64bit

Misc:

    backend : pro

**Other Information:**

**Comment by dwieeb** [comment]
@rtpHarry That's super weird... Could you try with Node 8?

**Comment by rtpHarry** [comment]
I didnt realise that was out of date, sorry. Updated to the current LTS package but still getting problems:

```
PS D:\rtp\rtpSoftware\Ionic\AppName> ionic ssh list
[ERROR]
PS D:\rtp\rtpSoftware\Ionic\AppName> node -v
v6.11.2
PS D:\rtp\rtpSoftware\Ionic\AppName> ionic ssh list
[ERROR]
PS D:\rtp\rtpSoftware\Ionic\AppName> node -v
v8.9.1
PS D:\rtp\rtpSoftware\Ionic\AppName> ionic ssh add

? Enter the location to your public key file to upload to Ionic:
PS D:\rtp\rtpSoftware\Ionic\AppName> ionic ssh setup
[ERROR]
PS D:\rtp\rtpSoftware\Ionic\AppName> ionic ssh setup --verbose
[DEBUG] Reason for not using local CLI: LOCAL_CLI_NOT_FOUND
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'D:\\rtp\\rtpSoftware\\Ionic\\AppName', local: false, binPath:
        'C:\\Users\\rtpha\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:
        'C:\\Users\\rtpha\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Daemon found (pid: 14700)
[ERROR]
```

**Comment by dwieeb** [comment]
@rtpHarry No worries--we support Node 6, I just wanted to see if upgrading would make a difference.

It looks like the error is happening for every `ionic ssh` command. Could you run this command: `DEBUG="*" ionic ssh list --verbose`

**Comment by rtpHarry** [comment]
Hi, i'm on Windows, that `debug="*"` isn't a valid command for me? Don't recognise it from anywhere?

I ran the rest of it though:

```
D:\rtp\rtpSoftware\Ionic
λ ionic ssh list --verbose
[DEBUG] Reason for not using local CLI: BASE_DIRECTORY_NOT_FOUND
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'D:\\rtp\\rtpSoftware\\Ionic', local: false, binPath:
        'C:\\Users\\rtpha\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:
        'C:\\Users\\rtpha\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Daemon found (pid: 13724)
[ERROR]
```

I really want to get this working as I'm halfway through developing an app which I have committed to launching. I'm ready to go nuclear with this if it means uninstalling stuff and delete cache folders or hidden config files?

One thing when I was researching is I don't have any directory in my users folder called `.\ssh` - I have just tried manually creating it and it hasn't fixed anything but I'm wondering where this comes from and if its indicative of something else having gone wrong further up the chain?

**Comment by rtpHarry** [comment]
Ok I have made progress. I looked through the cli source code to see what it was doing and saw it does this:

`ssh -v`

which did this on my system:

![image](https://user-images.githubusercontent.com/1038062/33252436-cb7cbe58-d370-11e7-90f3-ae9cfbc8910b.png)

So I hope I will have this solved shortly.

**Comment by dwieeb** [comment]
@rtpHarry 

`DEBUG` is an environment variable. I just wanted it set to `*` to enable debugging output of the libraries we use. Try to set the environment variable and run the command again.

`.ssh` is a folder where SSH config is stored for a library called OpenSSH. It is a dependency for git, and git is required for Ionic Pro. You can verify it's on your computer by typing the `ssh` command, which should display some help output if installed.

I'd like to know more about your environment, since without more information this issue is very difficult to debug.
* What terminal are you using? (Windows Command Prompt? Git Bash?)
* How was git installed?

Going nuclear means taking these steps:

1. Uninstall node & npm
1. Remove `C:\\Users\\rtpha\\AppData\\Roaming\\npm`
1. Remove project `node_modules` folder & `package-lock.json` file
1. Delete global Ionic CLI config: remove the `.ionic` folder in your home folder
1. Reinstall node & npm
1. Reinstall Ionic CLI

**Comment by dwieeb** [comment]
@rtpHarry Whoops, my last message was sent at the same time as yours 😆 

Okay, so you're using the cmder shell, which ships with git and OpenSSH. It is likely an issue with that installation. Perhaps try updating?

**Comment by dwieeb** [comment]
📝 Note to myself: Perhaps a timeout on `ssh` commands?

**Comment by rtpHarry** [comment]
## ionic ssh setup
@dwieeb thanks for your detailed replies with this issue. It's working for me now after I redownloaded the latest version of cmder and extracted a fresh copy to the install location.

I can see that you have taken over this issue now so I will leave it in your hands to close when ready but my problem is resolved.

## debug="*"
Side note: the `debug="*"` confusion in this and in the `contributing.md` update you made recently - it just be me being stupid but it wasn't clear in either case that you meant it was a env var. 

On Windows you would have to type `set debug="*"` to set this var, not sure about all platforms. 

The wording "prefix" the command is also confusing as it implied to me that it should go on the same line. Preceding would be a better word but I think explicitly stating you need to set the env var as a separate command would be best -- assuming everyone is as slow as I was haha.

**Comment by dwieeb** [comment]
@rtpHarry Great to hear it's working for you. Apologies for the initial rocky setup process.

The syntax I sent you for `DEBUG` is Mac/Linux (bash) syntax for setting environment variables for the session of that command. I sometimes forget how different Windows is sometimes, so thank you for the feedback. I will try to clear it up in `CONTRIBUTING.md`.
