### ISSUE TITLE
how can i run the demo  of ionic-cli online? 

### ISSUE THREAD

**Issue by gsons** [ionic-team/ionic-cli#2894]
**Description:**

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

**Other Information:**

**Description:**

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

**Other Information:**

**Comment by dwieeb** [comment]
The Ionic CLI runs in a NodeJS environment, not the browser. There are plenty of videos out there, but making a demo of it online isn't feasible for me right now.
