### ISSUE TITLE
Crosswalk issue with Google-map in ionic v3.19

### ISSUE THREAD

**Issue by shambhu-ray** [ionic-team/ionic-cli#2903]
When I'm using crosswalk plugin, googlemap not working on my android device and not produce any kind of error or warning in console and google map shows like white blank page, if i remove crosswalk plugin then google map working fine.

My `ionic info:
@ionic/cli-utils  : 1.19.0
ionic (Ionic CLI) : 3.19.0
cordova (Cordova CLI) : 7.1.0
@ionic/app-scripts : 3.1.2
Cordova Platforms  : android 6.3.0
Ionic Framework    : ionic-angular 3.9.2
ndroid SDK Tools : 26.1.1
Node              : v8.9.1
npm               : 5.5.1 
OS                : Windows 10
cordova-android": "6.3.0"
cordova-plugin-googlemaps": "^2.1.1"
@ionic-native/google-maps": "^4.4.2"

help me ......

**Comment by jcesarmobile** [comment]
crosswalk is deprecated, so closing
