### ISSUE TITLE
Execution failed for task ':CordovaLib:processDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by kapil019** [ionic-team/ionic-cli#2905]
IONIC BUID ISSUE

JAVA_HOME=/usr/lib/jvm/java-8-oracle
Subproject Path: CordovaLib
[12:13:52]  lint finished in 4.31 s 
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_9v4y3440rc9w7vvo7xz6swow6.run(/var/www/html/kapil/ionic3/ionic3-angular4-sample-app/platforms/android/build.gradle:141)

The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

:preBuild
 
UP-TO-DATE
:preDebugBuild
 UP-TO-DATE
:checkDebugManifest

:preReleaseBuild
 UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild
 UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies

:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders UP-TO-DATE
:CordovaLib:compileDebugShaders
 UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
 
UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
 UP-TO-DATE

:CordovaLib:generateDebugResValues
 UP-TO-DATE
:CordovaLib:generateDebugResources
 UP-TO-DATE
:CordovaLib:packageDebugResources
 UP-TO-DATE
:CordovaLib:processDebugManifest
 UP-TO-DATE
:CordovaLib:generateDebugBuildConfig
 UP-TO-DATE
:CordovaLib:processDebugResources
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':CordovaLib:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or 
--debug
 option to get more log output.

BUILD FAILED

Total time: 2.536 secs
Error: /var/www/html/kapil/ionic3/ionic3-angular4-sample-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':CordovaLib:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] An error occurred while running cordova build android (exit code 1).

**Comment by kapil019** [comment]
IONIC VERSION
CLI 3.19.0

**Comment by hervedevos** [comment]
Hi kapil,

I am encountering same issue than yours. Did you find a solution ?

**Comment by Trekkar** [comment]
Same issue here! Any help will be gratefully appreciated

**Comment by Trekkar** [comment]
Solved! Check this out
`https://forum.ionicframework.com/t/android-build-broken-after-gradle-dependencies-update-execution-failed-for-task-processdebugresources-com-android-ide-common-process-processexception-failed-to-execute-aapt/109982`

**Comment by vanukw** [comment]
Above link isn't work Trekkar. in my case same, first its success, then fails, i downgrade ionic version 3.15.0,
but same issue.

**Comment by nrsantos** [comment]
Try to update your plugins.
Remove and add by simply remove directory.

Since update the problem for me was cordova-plugin-compat. 
Simply remove and then `cordova run android `

**Comment by mhartington** [comment]
Closing this as this is not an Ionic issue, but a cordova/cordova 8 issue. Please open an issue on the cordova issue tracker. Thanks!

**Comment by kapil019** [comment]
Hi @hervedevos This was because of android version. I updated my android version and that works fine.
Thanks
Kapil

**Comment by c0478586** [comment]
Nobody knows how can we solve this issue?

**Comment by mhartington** [comment]
@c0478586 this is due to some changes in cordova upgrades and plugin versions, as others have mentioned. Please update the platforms/plugins that you have installed. If you're still having issues, please isolate the plugin causing the issue and open an on the plugins repository
