### ISSUE TITLE
Ionic not able to start server .After running command ionic serve it terminates .

### ISSUE THREAD

**Issue by ParagPallav** [ionic-team/ionic-cli#2906]
![ionic](https://user-images.githubusercontent.com/19725745/33516051-e0022c4e-d791-11e7-9fde-f1706a0c35aa.PNG)

It terminates by default without pressing Ctrl+C.

**Comment by vishuPPatel** [comment]
Same here!!!....give me suggestion hurry up .......

**Comment by dwieeb** [comment]
Consolidating -> https://github.com/ionic-team/ionic-cli/issues/2879

**Comment by ParagPallav** [comment]
Hi dwieeb when i use to run  this command echo %errorlevel% it gives me 1 as output.
![image](https://user-images.githubusercontent.com/19725745/34757439-2d47e948-f5f7-11e7-8de8-44c4cde10034.png)
