### ISSUE TITLE
DevApp (On Android) - Channel not fired: onFileSystemPathsReady

### ISSUE THREAD

**Issue by Ben1nBlack** [ionic-team/ionic-cli#2910]
**Description:**

ionic serve -l -c

in DevApp or Ionic VIew (on Android)

does nothing

`[19:29:05]  console.log: deviceready has not fired after 5 seconds. 
[19:29:05]  console.log: Channel not fired: onFileSystemPathsReady 
[19:29:05]  console.warn: Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an 
            inconsistent state. Try removing plugins from plugins/ and reinstalling them. 
`

**Steps to Reproduce:**

Example repo: 

1. ionic serve -l -c
2. open DevApp on Android
3. When you hit first platform.ready(). just stops

**Output:**

**My `ionic info`:**

`ionic info

cli packages: (/Users/benjohansen/WebstormProjects/DrugPricingTool/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0 browser 5.0.1 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v8.6.0
    npm               : 5.5.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : /Users/benjohansen/Library/Android/sdk

Misc:

    backend : pro

`

**Other Information:**

`cordova plugin ls
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 1.7.0 "AddSwiftSupport"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ionic 2.0.3 "IonicCordova"
cordova-plugin-ionic-webview 1.1.15 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.4-dev "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.6 "Cordova WKWebView Engine"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
`

**Comment by Ben1nBlack** [comment]
i found if i add the

`--prod `

flag, this issue goes away, and I am able to view on Ionic View.

I adjusted my package.json

 ```
 "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build --prod",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },


```

**Comment by Domvel** [comment]
This is NOT the solution! Only for production builds. Not for the development. *eyeroll*
