### ISSUE TITLE
How to keep my app set the app to ignore SSL certificate errors in IONIC 2

### ISSUE THREAD

**Issue by vinayak-dataman** [ionic-team/ionic-cli#2912]
**Description:**

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

**Other Information:**

**Comment by dwieeb** [comment]
Hi there! It appears this isn't really an issue, and more of a question. Please check out the [forum](https://forum.ionicframework.com) for any questions. Thanks!
