### ISSUE TITLE
Angular Material doesn't work on Ionic 3

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic-cli#2917]
Hello Ionic team.

Would you guys please make Angular Material compatible with Ionic?
I would love to use Angular Material components on Ionic but it doesn't seem to work at all on Ionic.
Please unlock this feature for us! 

material.angular.io

**Comment by SamaludheenCignes** [comment]
I am facing same issue, did you find a solution

**Comment by SamaludheenCignes** [comment]
I am facing same issue with data tables. Material theme not applied. I am using 
` import { MatTableModule } from '@angular/material/table'`

**Comment by janpio** [comment]
This is the repository for Ionic CLI. Your question has no connection to Ionic CLI at all. Please close this issue and ask it in a more appropriate place.

**Comment by dwieeb** [comment]
Please use the Ionic Framework repo: https://github.com/ionic-team/ionic

Thanks,
Dan
