### ISSUE TITLE
ion-textarea

### ISSUE THREAD

**Issue by Andionic** [ionic-team/ionic-cli#2918]
Wish to have an easy way to config ion-textarea:
a) attribute(s) to set an initial height and
b) attribute to set a flexible height (textarea grows automatically on every new line input)

In the community forum there are workarounds, I know. But in comparison to quality of all other components ion-textarea should be improved!

**Comment by dwieeb** [comment]
@Andionic I don't think this is related to the CLI. Please post this in the framework repo: https://github.com/ionic-team/ionic

Thanks,
Dan
