### ISSUE TITLE
chain verbose flag to cordova when used with ionic cordova

### ISSUE THREAD

**Issue by surajrao** [ionic-team/ionic-cli#2919]
**Description:**
I have come across an interesting behavior. When using `ionic cordova <command> --verbose`, the `verbose` flag only applies to the process done by `ionic` and not `cordova`.
For example:

```
ionic cordova build android --verbose
```
will provide debug logs of only the ionic process and not cordova.

Is it possible to chain the flag to cordova build when it is started by ionic? Or another flag in case we need to see cordova debug logs.

A real-life scenario can be seen [here](https://stackoverflow.com/questions/47763175/ionic-cordova-build-android-error-spawn-eacces)

**Comment by dwieeb** [comment]
Forgot to tag this issue, but the fix for this is in this commit: https://github.com/ionic-team/ionic-cli/commit/83f52e7784cc6aa105339e7ba08c29d111b0f314

Thank you for submitting the issue!
