### ISSUE TITLE
Ionic Pro API support in CLI

### ISSUE THREAD

**Issue by azakusilo** [ionic-team/ionic-cli#2920]
Hello.
We building a service to create app which is based on Ionic Pro. And we have got scripts to start create app. In older versions of Ionic services we had the "ionic package build" command to push to the server and start build automaticaly. But now it is in deprecated status. Do you have any flag or command to start native build after pushing to the server?

**Comment by dwieeb** [comment]
Hi @azakusilo!

We are looking at adding this functionality to the Ionic CLI soon. For now, there's no automated way of doing it. 

If you _absolutely_ need it right now, you can take a look at which network requests the Ionic Dashboard is making to our HTTP API and write a script.

**Comment by smzelek** [comment]
https://ionic.io/docs/appflow/cli/migration the new Appflow CLI offers this functionality and more.
