### ISSUE TITLE
events.js:183       throw er; // Unhandled 'error' event       ^  Error: read ECONNRESET     at _errnoException (util.js:1024:11)     at TCP.onread (net.js:615:25)

### ISSUE THREAD

**Issue by nigel-dewar** [ionic-team/ionic-cli#2922]
Brand new install of Ionic on Windows 10 Pro

npm i ionic cordova -g

versions
Node v 8.9.1
NPM v 5.5.1
Ionic -v 3.19.0
cordova -v 7.1.0

created app with ionic start todo blank

then run 
ionic lab

Browser loads, all is fine, then I go to make change to html file and get this error

![image](https://user-images.githubusercontent.com/9402456/34089016-0605e32c-e3f9-11e7-8f6c-3c8c9ac2e1fe.png)

Tried several different versions, like an older version on ionic cli. Doesnt work.

Also tried doing an npm i incase the ionic start thing didnt work. Doesnt work.

I also tried ionic serve. This works but then as soon as you change say your home.html file, boom it breaks.

Is ionic v3 working on Windows ??? Or should I be using a Mac only?  Buy the way I dont have a mac. So I cant test.

**Comment by nigel-dewar** [comment]
Update, Issue is resolved if use another browser. Just cannot use Google Chrome. Even if close chrome completely, restart and still no go

Using Internet Explorer Edge (the new one) for Windows 10 Pro

**Comment by wangjian1119** [comment]
I also met this problem and asked for a solution.

**Comment by nigel-dewar** [comment]
I can confirm that this was the same issue as https://github.com/ionic-team/ionic-cli/issues/2921

And it is now resolved by doing this

https://github.com/ionic-team/ionic-cli/issues/2921

Thank you to those who found the fixes.

**Comment by nigel-dewar** [comment]
@wangjian1119 , please find the fix

**Comment by Conny-PPA** [comment]
npm install ws@3.3.2 --save-dev --save-exact

this is not working for me, Chrome still crashes ionic serve after saving any html file

**Comment by hiuryoliveira** [comment]
@nigel-dewar You're right!
I did what you said and was able to solve my problem.

**Comment by nigel-dewar** [comment]
@hiuryoliveira  sweet dude glad it workd for you. :-)

**Comment by Riyaz0001** [comment]
@nigel-dewar Thank you, It's work for me.

**Comment by danielehrhardt** [comment]
Same here

**Comment by izart1994** [comment]
@nigel-dewar  Thank you very. Solved one of my problem

**Comment by pulamusic** [comment]
@nigel-dewar Your solution didn't work in my case - still getting error 183. I'll keep poking at it.

**Comment by PrudiviRaj** [comment]
Thq it Worked for me

**Comment by codyburleson** [comment]
I was getting the error just when I hit enter in the Chrome address bar to try to force a reload. `npm install ws@3.3.2 --save-dev --save-exact` worked for me also.

**Comment by jmmaguigad** [comment]
@nigel-dewar just did what you said and it works. Thank you.

**Comment by nigel-dewar** [comment]
No probs. Glad it works.


Sent from Samsung Mobile


-------- Original message --------
From: JM Maguigad
Date:11/01/2018 18:07 (GMT+10:00)
To: ionic-team/ionic-cli
Cc: Nigel Dewar , Mention
Subject: Re: [ionic-team/ionic-cli] events.js:183 throw er; // Unhandled 'error' event ^ Error: read ECONNRESET at _errnoException (util.js:1024:11) at TCP.onread (net.js:615:25) (#2922)


@nigel-dewar<https://github.com/nigel-dewar> just did what you said and it works. Thank you.

**Comment by nanirocks125** [comment]
Thank You 👍 👍

**Comment by simonbrazell** [comment]
Installing `"ws": "3.3.2"` as a dev dependency did not resolve the issue for me.

@nigel-dewar's fix is a workaround, this should not be closed, needs to be addressed with a new release.

**Comment by shenbagapandian** [comment]
I am trying to convert speech to text using voice base in nexmo. I have faced the issue in WebSocket client. My response error is: info: 
`Server listening on:8900 info: A client is connected! events.js:183 throw er; // Unhandled 'error' event Error: This socket is closed at Socket._writeGeneric (net.js:726:18) at Socket._write (net.js:786:8) at doWrite (_stream_writable.js:387:12) at writeOrBuffer (_stream_writable.js:373:5) at Socket.Writable.write (_stream_writable.js:290:11) at Socket.write (net.js:704:40) at WebSocketRequest.accept (/home/apptivo/Music/nexmoVoicebaseSample/Nexmo-RTS-Voicebase-master/WS-node/node_modules/websocket/lib/WebSocketRequest.js:450:21) at WebSocketServer.handleUpgrade (/home/apptivo/Music/nexmoVoicebaseSample/Nexmo-RTS-Voicebase-master/WS-node/node_modules/websocket/lib/WebSocketServer.js:216:19) at emitThree (events.js:141:20) at Server.emit (events.js:217:7)` 
How to resolved this issue ???``

**Comment by vidya47** [comment]
npm install @ionic/app-scripts@3.1.6 --save -dev did not work for me. I am still waiting for the solution.

**Comment by dwieeb** [comment]
This is an issue with a very general title, so likely the newer comments have similar but different issues. The `ws` issue was fixed in 3.1.6 by [pinning the version](https://github.com/ionic-team/ionic-app-scripts/commit/db0cc4de9194bbf9b825c4934ea48a7510a9f5fb). It continues to be pinned in later releases of app-scripts. Ensure you have the latest with these commands:

```
npm uninstall ws
npm install @ionic/app-scripts@latest
```

If you are getting an error, please create a new issue and fill out the issue template. Thanks!
