### ISSUE TITLE
Ionic Media Streaming App Issue?

### ISSUE THREAD

**Issue by Anbarasan-321** [ionic-team/ionic-cli#2923]
https://ionicacademy.com/ionic-media-streaming/
i followed this above tutorial but got error like this tslint: C:/mediaStreaming/src/pages/home/home.ts, line: 2
All imports are unused.
L1: import { Component } from '@angular/core';
L2: import { NavController } from 'ionic-angular';
L3: import { StreamingMedia, StreamingVideoOptions, StreamingAudioOption
s } from '@ionic-native/streaming-media';
Please check this and tell me how i get output for this?

**Description:**

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

**Other Information:**

**Comment by dwieeb** [comment]
Thanks for posting your issue. Unfortunately, this repo is reserved for bug reports and feature requests of the Ionic CLI. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).
