### ISSUE TITLE
Ionic native http post with withCredentials 

### ISSUE THREAD

**Issue by sirair** [ionic-team/ionic-cli#2925]
Hello,

I am using ionic native http (4.5.2) with cordova-plugin-advanced-http (1.9.0).
But how I can make a post Request with withCredentials.
In angular http it can be configured in the RequestOptions. But how I can make it when using native. Please help?

**Comment by dwieeb** [comment]
Thanks for posting your issue. Unfortunately, this repo is reserved for bug reports and feature requests of the Ionic CLI. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).
