### ISSUE TITLE
Ionic CLI does not generate correct resources for iPhone X launch images

### ISSUE THREAD

**Issue by matthewlloyd** [ionic-team/ionic-cli#2928]
Steps to reproduce:

1. Create a new ionic app project: ```ionic start testapp blank```
2. Add ios as a platform: ```ionic cordova platform add ios```
3. Open ```platforms/ios/testapp.xcworkspace``` in Xcode.
4. Navigate to ```Resources/Images.xcassets``` and select ```LaunchImage```.
5. Observe that the iPhone X portrait and landscape launch images are missing.

Package versions:

```
macbook-pro-2:testapp mil$ ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.3
    Node       : v6.10.2
    npm        : 3.10.10
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

<img width="915" alt="screen shot 2017-12-18 at 6 28 16 pm" src="https://user-images.githubusercontent.com/2041996/34133161-3f1c4250-e421-11e7-8866-5cb68730e8a9.png">

Related issue: https://github.com/ionic-team/ionic-cli/issues/2904

**Comment by matthewlloyd** [comment]
The missing images no longer seem to matter. In earlier testing, the app would show a white bar underneath the launch image. In my testing today, the launch storyboard (which is what the universal-anyany.png is for) now covers the bottom of the screen. I don't know what's changed. In any case, closing.

**Comment by mkimmet** [comment]
When I build my app in Xcode, I'm getting warnings that the 2 files for iPhone X that you picture above (portrait and landscape called: "Default-2436h.png" and "Default-Landscape-2436h.png"), do not exist.   Are these files not required for it to work on iphone X?  Should I ignore these warnings when submitting to the store?

**Comment by mubasshir** [comment]
any solution?

**Comment by dwieeb** [comment]
Tracking via: https://github.com/ionic-team/ionic-cli/issues/3319
