### ISSUE TITLE
Docs: `ionic build` docs redirect to general CLI docs page

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2934]
https://ionicframework.com/docs/cli/build/ redirects to https://ionicframework.com/docs/cli/ automatically.

**Comment by dwieeb** [comment]
@perrygovier Might you know why? Do we have some regex redirect in place?

**Comment by dwieeb** [comment]
This will be fixed in the next site deploy (but browser cache will need to be cleared/expired).
