### ISSUE TITLE
There are deprecated commands running inner script for "ionic cordova bulid android"

### ISSUE THREAD

**Issue by dunia-ramirez** [ionic-team/ionic-cli#2936]
**Description:**
Running the simple command in mac OS:

> ionic cordova build android

Build failed:
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

	at build_25spknfu6h22i4lcflbca3eu7.run(/Users/dumis/myIonicApps/cutePuppyPics/platforms/android/build.gradle:142)
org.xwalk:xwalk_core_library:22+

Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.

**Steps to Reproduce:**

I have these installed in my mac:
------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Mac OS X 10.12.6 x86_64

**My `ionic info`:**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.0
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/klaus/Library/Android/sdk

Misc:

    backend : pro

**Other Information:**
Full stacktrace:

# ionic cordova build android
Running app-scripts build: --platform android --target cordova
[09:02:57]  build dev started ... 
[09:02:57]  clean started ... 
[09:02:57]  clean finished in 3 ms 
[09:02:57]  copy started ... 
[09:02:57]  deeplinks started ... 
[09:02:58]  deeplinks finished in 21 ms 
[09:02:58]  transpile started ... 
[09:03:02]  transpile finished in 4.07 s 
[09:03:02]  preprocess started ... 
[09:03:02]  preprocess finished in less than 1 ms 
[09:03:02]  webpack started ... 
[09:03:02]  copy finished in 4.32 s 
[09:03:10]  webpack finished in 8.25 s 
[09:03:10]  sass started ... 
[09:03:12]  sass finished in 1.92 s 
[09:03:12]  postprocess started ... 
[09:03:12]  postprocess finished in 176 ms 
[09:03:12]  lint started ... 
[09:03:12]  build dev finished in 14.65 s 
> cordova build android
ANDROID_HOME=/Users/klaus/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
Subproject Path: CordovaLib
[09:03:15]  lint finished in 2.57 s 
null

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_25spknfu6h22i4lcflbca3eu7.run(/Users/klaus/myIonicApps/cutePuppyPics/platforms/android/build.gradle:142)
org.xwalk:xwalk_core_library:22+

Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
(node:2182) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /Users/dumis/myIonicApps/cutePuppyPics/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
(node:2182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mhartington** [comment]
Hi there! This isn't an issue with the CLI, but rather the native android build. Looks like the main cause is crosswalk here, which is not going to be updated anymore. You should probably remove crosswalk.

**Comment by dunia-ramirez** [comment]
Hi Mike,

I did not install Crosswalk, then it is not possible to remove it. I am
checking documentation about crosswalk, anyway I am sure it is not
installed. I'm trying with latest node.js 9.3.0

Thank you.

**Comment by mhartington** [comment]
>org.xwalk:xwalk_core_library:22+

This line in your error output indicates that crosswalk is present in your project.

```
ionic cordova plugin ls
```

should list it. All you'll need to do is remove it and you should be able to build without issues.

**Comment by dunia-ramirez** [comment]
Thank you so much, Mike.

**Comment by franzisk** [comment]
> Hi there! This isn't an issue with the CLI, but rather the native android build. Looks like the main cause is crosswalk here, which is not going to be updated anymore. You should probably remove crosswalk.

Hi Mike,

I am facing the same problem here but I can't remove Crosswalk because I need to cover also Android 4.1 in the app.

In my case after the building command it says:
```
* What went wrong:
A problem occurred configuring root project 'android'.
> Flavor 'armv7' has no flavor dimension.

```

Is there any any to make it work?

**Comment by dwieeb** [comment]
@franzisk We don't officially support Crosswalk at this time. It was abandoned [over a year ago](https://crosswalk-project.org/blog/crosswalk-final-release.html). I invite you to use the [Ionic Framework forum](https://forum.ionicframework.com/) for community support. I'll be locking this as it is not an Ionic CLI issue.
