### ISSUE TITLE
Wrong TypeRoot path in tsconfig.json

### ISSUE THREAD

**Issue by ildar-icoosoft** [ionic-team/ionic-cli#2940]
**Description:**

If I create an ionic project using command: `ionic create myproject` then tsconfig.json has lines:
```
"typeRoots": [
    "../node_modules/@types"
]
```

The path is wrong. It should be `"./node_modules/@types"`. I have many errors in real project because of this line. 

**Steps to Reproduce:**

1. run `ionic start myproject`
2. select blank
3. look at tsconfig.json

**Comment by dwieeb** [comment]
Good catch @ildar-icoosoft, thanks! I've fixed the issue for new starters.
