### ISSUE TITLE
Screen Overlay Detected was coming for Oneplus1 mobile 

### ISSUE THREAD

**Issue by muni-reddy** [ionic-team/ionic-cli#2943]
**Description:**

for taking picture i am using this code , but is not following code 
Camera.getPicture({
            sourceType : picture,
            destinationType: Camera.DestinationType.DATA_URL,
           // destinationType: Camera.DestinationType.FILE_URI,
            targetWidth:1200,
            targetHeight:1000,
            saveToPhotoAlbum: true,
            }).then((imageData) => {         
                       var index = this.images.length;
                       this.images[index]={'name': "data:image/jpeg;base64," + imageData, 'number': index +1};
                
                     console.log("this.images",this.images);
                }, (err) => {
                console.log(err);
            });
           //this.vehicle=true;
            //console.log("Image Value :",this.vehicle);
        }

1.When i am clicking on camera in my app it is not capturing image , but it is showing screen overlay detected for only one plus 1 mobile.
![screen shot 2018-01-04 at 2 26 31 pm](https://user-images.githubusercontent.com/28982058/34557603-dfb5d84c-f160-11e7-9bca-f70edf27a4b6.png)

2. Picking Image from the gallery also it is giving the same error. 
3. I am try to change overlay settings , but it is not allowing to change that option. 
![img-20171227-wa0005](https://user-images.githubusercontent.com/28982058/34558003-3d5d90f6-f162-11e7-9101-84bd56ccb301.jpg)

**Steps to Reproduce:**

Example repo: 

3.

**Output:**

**My `ionic info`:**

Ionic Cli : 3.1.9

**Other Information:**

**Comment by dwieeb** [comment]
Thanks for posting your issue. Unfortunately, this repo is reserved for bug reports and feature requests of the Ionic CLI. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).
