### ISSUE TITLE
Pass options to cordova commands

### ISSUE THREAD

**Issue by ajcrites** [ionic-team/ionic-cli#2946]
**Description:**
Currently there is no way to pass arguments to cordova commands run by `ionic cordova`. Thus, if you do `ionic cordova platform add ios` or `ionic cordova platform build ios` (with no `./platforms`) the `--save` option is called and there's no way to opt out of it. You also can't opt out `cordova-fetch` for cordova@7.

There should be a way to pass flags to underlying cordova commands run through `ionic cordova`.

**Steps to Reproduce:**
1. Create a new project `ionic start $PROJECT`. Choose to integrate with cordova
2. Try to build ios immediately, `ionic cordova build ios`

**Output:**
You will notice that the command immediately updates `config.xml`, `package.json`, and `package-lock.json`.  It will also fail initially with: `Error: Cannot find module 'graceful-fs'`, although running `ionic cordova build ios` a second time will work.

**My `ionic info`:**
```
cli packages: (/Users/acrites/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v9.3.0
    npm               : 5.5.1
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/acrites/Library/Android/sdk

Misc:

    backend : pro
```

**Other Information:**
Using `ionic cordova platform add ios --nosave` and `ionic cordova build ios --nosave` do not work.

**Comment by surajrao** [comment]
@ajcrites For `build` need to use an extra `--` to give cordova cli options. Check https://ionicframework.com/docs/cli/cordova/build/ .

 Also `build` command does not havw `--nosave`. Cordova cli docs: https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#cordova-build-command

`ionic cordova build ios -- -d`

**Comment by ajcrites** [comment]
@surajrao `cordova build` does not have `--nosave`, but if you run `ionic cordova build` without any `platforms` available it will automatically run `cordova platform add` first, but actually runs it with `--save` with no way to override that (seemingly).

Running `ionic cordova platform add ios -- --nosave` also does not work, this will simply call `cordova platform add ios --save`. You can't use `ionic cordova platform add -- --nosave ios` as this actually calls `cordova platform add --nosave --save`

**Comment by dwieeb** [comment]
@ajcrites Thanks for the issue report!

The `ionic cordova` commands are designed to make more assumptions about a project than the Cordova CLI. The actions these commands take, such as adding the platform with `--save` when `ionic cordova build` is invoked, is what we assume the dev will want. Indeed, if I recall correctly, this is the first issue asking for different behavior. I think the best solution is to invoke individual commands manually to get your desired outcome. It gets hairy trying to add flags for subcommands, especially when those commands wrap other subcommands themselves.

I'm marking the second part of this issue as a bug. `--nosave` should be a respected flag. I see the bug and will fix it for the next CLI version. The workaround is to just use the Cordova CLI for these operations.

**Comment by csabbey** [comment]
How would I pass the --nosave option? It doesn't seem to be working for me:

ionic cordova platform add ios -- --nosave
> cordova platform add ios --save

ionic --version
4.0.5

**Comment by AndrWeisR** [comment]
I get the error in 11.0.1-nightly.2022.7.4.f38e8eb3:

```
copy C:/Build/xxxx/stream-2.4-API31+/platforms/android/app/src/main/java/com/xxxx/app/xxxx/MainActivity.java to C:\Build\xxxx\stream-2.4-API31+\platforms\android\app\src\main\java\com\xxxx\app\xxxx\MainActivity.java
Source and destination must not be the same.
Error: Source and destination must not be the same.
    at Object.checkPathsSync (C:\Build\xxxx\stream-2.4-API31+\node_modules\cordova-android\node_modules\fs-extra\lib\util\stat.js:78:13)
    at Object.copySync (C:\Build\xxxx\stream-2.4-API31+\node_modules\cordova-android\node_modules\fs-extra\lib\copy\copy-sync.js:27:38)
    at updateProjectAccordingTo (C:\Build\xxxx\stream-2.4-API31+\node_modules\cordova-android\lib\prepare.js:314:12)
    at C:\Build\xxxx\stream-2.4-API31+\node_modules\cordova-android\lib\prepare.js:67:21
    at async Promise.all (index 0)
```
