### ISSUE TITLE
Android build failed due to “compileDebugJavaWithJavac FAILED”

### ISSUE THREAD

**Issue by gauravgupta0305** [ionic-team/ionic-cli#2949]
I'm trying to build APK for my project, but it fails without any error info.

**Version Info:**

- Ionic: 3.12.0
- Cordova: 8.0.0
- Node: 9.3.0
- npm: 5.6.0

**Notes:** 

- I had copied my codebase from my original one, renamed my project folder, removed .git folder, made app id changes in config.xml.
- I also have google plus sign in configured in my ionic application which is configured correctly, I believe.
- I tried removing, adding and preparing cordova android already.
- Please, help me in solving this.

**Console:**

> ionic cordova build android --debug 
> [INFO] Running app-scripts build: --platform android --target cordova
> 
> [15:24:01] build dev started ... [15:24:02] clean started ... [15:24:02] clean finished in 16 ms [15:24:02] copy started ... [15:24:02] transpile started ... [15:24:10] transpile finished in 8.44 s [15:24:10] preprocess started ... [15:24:10] deeplinks started ... [15:24:10] deeplinks finished in 249 ms [15:24:10] preprocess finished in 250 ms [15:24:10] webpack started ... [15:24:12] copy finished in 10.07 s [15:24:27] webpack finished in 16.78 s [15:24:27] sass started ... [15:24:30] sass finished in 3.06 s [15:24:30] postprocess started ... [15:24:30] removed unused font files [15:24:30] postprocess finished in 16 ms [15:24:30] lint started ... [15:24:30] build dev finished in 28.92 s
> 
> ionic cordova prepare android cordova prepare android
> 
> cordova build android --debug | Running command [15:24:45] tslint: ...:/Workspace/ai-guru-app/src/services/googletranslate/google.translate.service.ts, line: 2 'Headers' is declared but never used.
> 
>    L1:  import { Injectable } from '@angular/core';
>    L2:  import { Http, Headers, RequestOptionsArgs } from '@angular/http';
>    L3:  import { GoogleTranslateResponse } from '../../models/google-translate-response';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/services/faq/faq.service.ts, line: 3 'Headers' is declared but never used.
> 
>    L2:  import { faq_data } from '../../models/faq'
>    L3:  import { Http, Headers, RequestOptionsArgs } from '@angular/http';
>    L4:  import 'rxjs/add/operator/toPromise';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/guru/guru.ts, line: 18 Property 'plt' is declared but never used.
> 
>   L17:  constructor(public navCtrl: NavController, public navParams: NavParams, private tts: TextToSpeech,
>   L18:    private plt: Platform) {
>   L19:    this.userName = navParams.get('userName');
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/guru/guru.ts, line: 1 'Input' is declared but never used.
> 
>    L1:  import { Component, Input } from '@angular/core';
>    L2:  import { NavController, NavParams, Platform} from 'ionic-angular';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/pop-over-faq/pop-over-faq.ts, line: 68 'talkBackHandler' is declared but never used.
> 
>   L68:  private talkBackHandler(e) {
>   L69:    this.enableTalkBack = !this.enableTalkBack;
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/pop-over-faq/pop-over-faq.ts, line: 78 'tapTextHandler' is declared but never used.
> 
>   L78:  private tapTextHandler(text: string) {
>   L79:    if(this.enableTalkBack === true) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/list-faq/list-faq.ts, line: 43 Property 'faqService' is declared but never used.
> 
>   L43:  vCtrl: NavController, public navParams: NavParams, private faqService: FAQService, public loadingCtrl: Loadi
>   L44:      public popoverCtrl: PopoverController, private storage: NativeStorage, private translate: TranslateService, private
> ngZone: NgZone,
> 
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/list-faq/list-faq.ts, line: 45 Property 'alertCtrl' is declared but never used.
> 
>   L44:  public popoverCtrl: PopoverController, private storage: NativeStorage, private translate: TranslateService, private ngZone:
> NgZone, L45: private network: Network, private alertCtrl: AlertController, private tts: TextToSpeech) { L46: this.userName = navParams.get('userName');
> 
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/list-faq/list-faq.ts, line: 240 'talkBackHandler' is declared but never used.
> 
>  L240:  private talkBackHandler(e) {
>  L241:    this.enableTalkBack = !this.enableTalkBack;
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/list-faq/list-faq.ts, line: 2 'PopoverOptions' is declared but never used.
> 
>    L1:  import { Component, OnInit, NgZone } from '@angular/core';
>    L2:  r, AlertController, NavParams, LoadingController, PopoverController, PopoverOptions } from 'ionic-angular';
>    L3:  import { FAQService } from '../../services/faq/faq.service';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/list-faq/list-faq.ts, line: 4 All imports are unused.
> 
>    L3:  import { FAQService } from '../../services/faq/faq.service';
>    L4:  import { faq_data } from '../../models/faq';
>    L5:  import { GuruPage } from '../../pages/guru/guru';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/list-faq/list-faq.ts, line: 11 All imports are unused.
> 
>   L10:  import { Network } from '@ionic-native/network';
>   L11:  import { LearnPage } from '../../pages/learn/learn';
>   L12:  import { TextToSpeech } from '@ionic-native/text-to-speech';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/learn/learn.ts, line: 26 Property 'translate' is declared but never used.
> 
>   L26:  onstructor(public navCtrl: NavController, public navParams: NavParams, private translate: TranslateService,
>   L27:      private domain: DomainService, public loadingCtrl: LoadingController, private storage: NativeStorage,
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/learn/learn.ts, line: 27 Property 'domain' is declared but never used.
> 
>   L26:  constructor(public navCtrl: NavController, public navParams: NavParams, private translate: TranslateService,
>   L27:    private domain: DomainService, public loadingCtrl: LoadingController, private storage: NativeStorage,
>   L28:    private tts: TextToSpeech) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/learn/learn.ts, line: 111 'talkBackHandler' is declared but never used.
> 
>  L111:  private talkBackHandler(e) {
>  L112:    this.enableTalkBack = !this.enableTalkBack;
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/learn/learn.ts, line: 4 All imports are unused.
> 
> / Running command L3: import { DomainService } from '../../services/domain/domain.service' L4: import { Domain } from '../../models/domain'; L5: import { ListFaqPage } from '../../pages/list-faq/list-faq';
> 
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/services/api/api.service.ts, line: 27 Property 'plt' is declared but never used.
> 
>   L27:      constructor(private plt: Platform, private http: Http, private transfer: FileTransfer,
>   L28:          private storage: NativeStorage, private tokenService: UserService, private google: GooglePlus) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/services/api/api.service.ts, line: 239 'handleError' is declared but never used.
> 
>  L239:  private handleError(errorMsg: any) {
>  L240:      // Log error message in console
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/services/api/api.service.ts, line: 3 'RequestOptions' is declared but never used.
> 
>    L2:  import { Platform } from 'ionic-angular';
>    L3:  import { Http, Headers, RequestOptions, RequestOptionsArgs } from '@angular/http';
>    L4:  import { FileTransfer, FileUploadOptions, FileTransferObject, FileUploadResult } from
> '@ionic-native/file-transfer';
> 
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/services/api/api.service.ts, line: 6 All imports are unused.
> 
>    L5:  import 'rxjs/add/operator/toPromise';
>    L6:  import { User } from '../../models/user';
>    L7:  import { NativeStorage } from '@ionic-native/native-storage';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/services/api/api.service.ts, line: 9 'Prediction' is declared but never used.
> 
>    L8:  import { GooglePlus } from '@ionic-native/google-plus';
>    L9:  import { Prediction, PredictionResult } from '../../models/prediction'
>   L10:  import { AIResponse } from '../../models/airesponse';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/services/api/api.service.ts, line: 10 All imports are unused.
> 
>    L9:  import { Prediction, PredictionResult } from '../../models/prediction'
>   L10:  import { AIResponse } from '../../models/airesponse';
>   L11:  import { UserService } from '../../services/login/login.service';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/camera-preview/camera-preview.ts, line: 1 'ViewChild' is declared but never used.
> 
>    L1:  import { Component, ViewChild, ElementRef } from '@angular/core';
>    L2:  import { NavController, NavParams, AlertController, ModalController, Alert } from 'ionic-angular';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/camera-preview/camera-preview.ts, line: 1 'ElementRef' is declared but never used.
> 
>    L1:  import { Component, ViewChild, ElementRef } from '@angular/core';
>    L2:  import { NavController, NavParams, AlertController, ModalController, Alert } from 'ionic-angular';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/camera-preview/camera-preview.ts, line: 2 'Alert' is declared but never used.
> 
>    L1:  import { Component, ViewChild, ElementRef } from '@angular/core';
>    L2:  import { NavController, NavParams, AlertController, ModalController, Alert } from 'ionic-angular';
>    L3:  import { GuruPage } from '../../pages/guru/guru';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/camera-preview/camera-preview.ts, line: 14 All imports are unused.
> 
>   L13:  import { Subscription } from 'rxjs/Subscription';
>   L14:  import lodash from 'lodash';
>   L15:  import { ListFaqPage } from '../../pages/list-faq/list-faq';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/camera-preview/camera-preview.ts, line: 15 All imports are unused.
> 
>   L14:  import lodash from 'lodash';
>   L15:  import { ListFaqPage } from '../../pages/list-faq/list-faq';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/services/sync/sync.service.ts, line: 2 'RequestOptions' is declared but never used.
> 
>    L1:  import { Injectable } from '@angular/core';
>    L2:  import { Http, Headers, RequestOptions, RequestOptionsArgs } from '@angular/http';
>    L3:  import 'rxjs/add/operator/toPromise';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/home/home.ts, line: 156 'talkBackHandler' is declared but never used.
> 
>  L156:  private talkBackHandler(e) {
>  L157:    if(!this.toHighlightSpeaker) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/home/home.ts, line: 168 'appIntroHandler' is declared but never used.
> 
>  L168:  private appIntroHandler(e) {
>  L169:    if(this.isIntroInProgress) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/login/login.ts, line: 63 'talkBackHandler' is declared but never used.
> 
>   L63:  private talkBackHandler(e) {
>   L64:    this.enableTalkBack = !this.enableTalkBack;
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/login/login.ts, line: 73 'tapTextHandler' is declared but never used.
> 
>   L73:  private tapTextHandler() {
>   L74:    if (this.enableTalkBack === true) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/login/login.ts, line: 298 'reload' is declared but never used.
> 
>  L298:  private reload(): void {
>  L299:    if (this.enableTalkBack === false) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/settings/settings.ts, line: 32 Property 'menu' is declared but never used.
> 
>   L31:  constructor(public navCtrl: NavController, public navParams: NavParams, private tts: TextToSpeech, public events:
> Events, L32: e: NativeStorage, private translate: TranslateService, private plt: Platform, private menu: MenuController, L33: private alertCtrl: AlertController, private camera: CameraService, private appAvailability: AppAvailability, private market: Market) {
> 
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/settings/settings.ts, line: 451 'talkBackHandler' is declared but never used.
> 
>  L451:  private talkBackHandler(e) {
>  L452:    this.enableTalkBack = !this.enableTalkBack;
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/settings/settings.ts, line: 461 'talkBackTap' is declared but never used.
> 
>  L461:  private talkBackTap(option: string){
>  L462:    this.translate.get(['tts_settings_lang', 'tts_settings_cap', 'tts_settings_talk' , 'tts_settings_intro',
> 'tts_settings_sub']).subscribe((value) => {
> 
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/settings/settings.ts, line: 2 'ToastOptions' is declared but never used.
> 
>    L1:  import { Component, OnInit } from '@angular/core';
> - Running command L2: NavController, NavParams, AlertController, MenuController, ToastOptions, Platform, Events } from 'ionic-ang L3: import { NativeStorage } from '@ionic-native/native-storage';
> 
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/services/update/update.service.ts, line: 25 Property 'plt' is declared but never used.
> 
>   L24:    constructor(private deploy: Deploy, private storage: NativeStorage, private loadingCtrl: LoadingController,
>   L25:    private translate: TranslateService, private tts: TextToSpeech, private plt: Platform) {}
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/welcome/welcome.ts, line: 92 'talkBackHandler' is declared but never used.
> 
>   L92:  private talkBackHandler(e) {
>   L93:    // stop highlighting, if button touched in between TTS.
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/welcome/welcome.ts, line: 110 'tapTextHandler' is declared but never used.
> 
>  L110:  private tapTextHandler(text: string) {
>  L111:    if(this.enableTalkBack === true) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/welcome/welcome.ts, line: 2 'IonicPage' is declared but never used.
> 
>    L1:  import { Component } from '@angular/core';
>    L2:  import { IonicPage, NavController, NavParams, Platform, Events } from 'ionic-angular';
>    L3:  import { NativeStorage } from '@ionic-native/native-storage';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/disclaimer/disclaimer.ts, line: 65 'talkBackHandler' is declared but never used.
> 
>   L65:  private talkBackHandler(e) {
>   L66:    // switch enable-disable
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/disclaimer/disclaimer.ts, line: 76 'tapTextHandler' is declared but never used.
> 
>   L76:  private tapTextHandler(text: string) {
>   L77:    if(this.enableTalkBack === true) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/disclaimer/disclaimer.ts, line: 2 'IonicPage' is declared but never used.
> 
>    L1:  import { Component } from '@angular/core';
>    L2:  import { IonicPage, NavController, NavParams, Platform } from 'ionic-angular';
>    L3:  import { TextToSpeech } from '@ionic-native/text-to-speech';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/about-us/about-us.ts, line: 65 'talkBackHandler' is declared but never used.
> 
>   L65:  private talkBackHandler(e) {
>   L66:    // switch enable-disable
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/about-us/about-us.ts, line: 76 'tapTextHandler' is declared but never used.
> 
>   L76:  private tapTextHandler(text: string) {
>   L77:    if(this.enableTalkBack === true) {
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/pages/about-us/about-us.ts, line: 2 'IonicPage' is declared but never used.
> 
>    L1:  import { Component } from '@angular/core';
>    L2:  import { IonicPage, NavController, NavParams, Platform } from 'ionic-angular';
>    L3:  import { TextToSpeech } from '@ionic-native/text-to-speech';
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/app/app.component.ts, line: 336 'talkBackHandler' is declared but never used.
> 
>  L336:  private talkBackHandler(e) {
>  L337:    this.enableTalkBack = !this.enableTalkBack;
> [15:24:45] tslint: C:/Workspace/ai-guru-app/src/app/app.component.ts, line: 346 'tapTextHandler' is declared but never used.
> 
>  L346:  private tapTextHandler(text: string) {
>  L347:    if(this.enableTalkBack === true) {
> [15:24:45] lint finished in 14.88 s √ Running command - done! ANDROID_HOME=C:\Users\gaurav.q.gupta\AppData\Local\Android\Sdk JAVA_HOME=C:\Program Files\Java\jdk1.8.0_151 :wrapper
> 
> BUILD SUCCESSFUL in 2s 1 actionable task: 1 executed Subproject Path: CordovaLib The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead. at build_mxq2ksel8hq10p1rh0g2t3i7.run(C:\Workspace\ai-guru-app\platforms\android\build.gradle:137) The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0. Incremental java compilation is an incubating feature. The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead. :preBuild UP-TO-DATE :preDebugBuild UP-TO-DATE :checkDebugManifest :preReleaseBuild UP-TO-DATE :CordovaLib:preBuild UP-TO-DATE :CordovaLib:preDebugBuild UP-TO-DATE :CordovaLib:checkDebugManifest :CordovaLib:prepareDebugDependencies :CordovaLib:compileDebugAidl :CordovaLib:compileDebugNdk UP-TO-DATE :CordovaLib:compileLint :CordovaLib:copyDebugLint UP-TO-DATE :CordovaLib:mergeDebugShaders :CordovaLib:compileDebugShaders :CordovaLib:generateDebugAssets :CordovaLib:mergeDebugAssets :CordovaLib:mergeDebugProguardFiles :CordovaLib:packageDebugRenderscript UP-TO-DATE :CordovaLib:compileDebugRenderscript :CordovaLib:generateDebugResValues :CordovaLib:generateDebugResources :CordovaLib:packageDebugResources :CordovaLib:processDebugManifest :CordovaLib:generateDebugBuildConfig :CordovaLib:processDebugResources :CordovaLib:generateDebugSources :CordovaLib:incrementalDebugJavaCompilationSafeguard :CordovaLib:compileDebugJavaWithJavac :CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.). :CordovaLib:processDebugJavaRes UP-TO-DATE :CordovaLib:transformResourcesWithMergeJavaResForDebug :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug :CordovaLib:mergeDebugJniLibFolders :CordovaLib:transformNative_libsWithMergeJniLibsForDebug :CordovaLib:transformNative_libsWithSyncJniLibsForDebug :CordovaLib:bundleDebug :CordovaLib:preReleaseBuild UP-TO-DATE :CordovaLib:checkReleaseManifest :CordovaLib:prepareReleaseDependencies :CordovaLib:compileReleaseAidl :CordovaLib:compileReleaseNdk UP-TO-DATE :CordovaLib:copyReleaseLint UP-TO-DATE :CordovaLib:mergeReleaseShaders :CordovaLib:compileReleaseShaders :CordovaLib:generateReleaseAssets :CordovaLib:mergeReleaseAssets :CordovaLib:mergeReleaseProguardFiles :CordovaLib:packageReleaseRenderscript UP-TO-DATE :CordovaLib:compileReleaseRenderscript :CordovaLib:generateReleaseResValues :CordovaLib:generateReleaseResources :CordovaLib:packageReleaseResources :CordovaLib:processReleaseManifest :CordovaLib:generateReleaseBuildConfig :CordovaLib:processReleaseResources :CordovaLib:generateReleaseSources :CordovaLib:incrementalReleaseJavaCompilationSafeguard :CordovaLib:compileReleaseJavaWithJavac :CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.). :CordovaLib:processReleaseJavaRes UP-TO-DATE :CordovaLib:transformResourcesWithMergeJavaResForRelease :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease :CordovaLib:mergeReleaseJniLibFolders :CordovaLib:transformNative_libsWithMergeJniLibsForRelease :CordovaLib:transformNative_libsWithSyncJniLibsForRelease :CordovaLib:bundleRelease :prepareComAndroidSupportAnimatedVectorDrawable2600Alpha1Library :prepareComAndroidSupportAppcompatV72600Alpha1Library :prepareComAndroidSupportSupportCompat2600Alpha1Library :prepareComAndroidSupportSupportCoreUi2600Alpha1Library :prepareComAndroidSupportSupportCoreUtils2600Alpha1Library :prepareComAndroidSupportSupportFragment2600Alpha1Library :processDebugManifest :processDebugResources :generateDebugSources :incrementalDebugJavaCompilationSafeguard :compileDebugJavaWithJavac :compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.). :compileDebugJavaWithJavac FAILED
> 
> BUILD FAILED
> 
> Total time: 29.962 secs

**Comment by dwieeb** [comment]
Thanks for posting your issue. Unfortunately, this repo is reserved for bug reports and feature requests of the Ionic CLI. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).
