### ISSUE TITLE
weird livereload issues

### ISSUE THREAD

**Issue by GGalizzi** [ionic-team/ionic-cli#2950]
**Description:**

When saving a view (html) it seems to load an old version of a previously changed page.ts file.

**Steps to Reproduce:**

1. Have some FooPage

2. Edit `foo.html` with something that uses some function, example: `{{ bar() }}`

3. Correctly displays `bar is not a function` error.

4. Add the bar function to the corresponding `ts` file.

5. Stuff works as expected.

6. Make any other change in the html, or no change at all, a write to trigger the livereload. (or a change in app.html, or some component html)

7. Get the `bar is not a function` error.

8. Trigger a write on the `ts` file.

9. It finds the bar function.

**My `ionic info`:**

```
cli packages: (/home/ggalizzi/.npm-globals/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.3.0
    npm  : 5.6.0
    OS   : Linux 4.4

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Other Information:**

I'm on WSL Windows 10 (a.k.a Ubuntu on Windows)

Things I tried finding stuff around:

- Open related ports in windows firewall

- Downgrade cli (3.15.0)

- Change the ports server uses.

- Tried upping `max_user_watches` limit, but found out WSL supposedly [has no limit on it](https://github.com/Microsoft/WSL/issues/1705#issuecomment-280079472)

- I'm sorry if this is a duplicate, I found other issues regarding live reload, but I am unsure if they are related.

Any help or ideas would be greatly appreciated. 

Thank you.

**Comment by dwieeb** [comment]
@GGalizzi This sounds a lot like a service worker issue. Can you try disabling the service worker and see if the livereload issues clear up?

**Comment by GGalizzi** [comment]
@dwieeb Service Worker was already disabled.

**Comment by dwieeb** [comment]
@GGalizzi I am seeing this behavior after following your steps to reproduce. 😄 How weird! I'm going to move your issue to our `@ionic/app-scripts` repo, as it appears to be an issue with app-scripts: https://github.com/ionic-team/ionic-app-scripts/issues/1369
