### ISSUE TITLE
`ionic start` command throws npm 404 error when the global npm config has a private registry

### ISSUE THREAD

**Issue by dmitryshimkin** [ionic-team/ionic-cli#2952]
**Description:**

I cannot create a new ionic application with `ionic start` command

**Steps to Reproduce:**

1. Create a ~/.npmrc file with your custom npm registry. For example:

```
registry=https://mycompany.com/npm/
```

2. Run `ionic start --pro-id <app_id>` command

**Output:**

NPM throws 404 error

---

I guess to solve the issue the cli should add `--registry <path-to-global-registry>` parameter when installing dependencies.

**Comment by dwieeb** [comment]
I assume this is because of the `npm install` that occurs during `ionic start`. But there is no `--registry` flag for individual `npm install` invocations. How would you install these dependencies otherwise?

**Comment by dmitryshimkin** [comment]
I believe you can override any npm config parameter for individual `npm install` invocations using `--<config_property> <value>`. So `npm install --registry https://registry.npmjs.org/` will use the global registry instead of custom one.

**Comment by dwieeb** [comment]
@dmitryshimkin Ah, you're right! Today I learned. Do people usually set their default registry as their company registry? It would seem that one might want to keep the npm registry as the default and use `--registry` for their company's registry when they need to.

**Comment by dmitryshimkin** [comment]
Dunno, can't say for everyone. In my particular case on the laptop provided by employer it is more convenient (or even required by internal tools) to use the company registry by default, since I use it mostly for internal work.

**Comment by dmitryshimkin** [comment]
I just learnt that npm config properties can be set via environment variables. So there is a following workaround for such case:

```
npm_config_registry=https://registry.npmjs.org/ ionic start --pro-id <app_id>
```

**Comment by dwieeb** [comment]
@dmitryshimkin I think that's the best workaround for now. If this issue gets more attention, we'll revisit. Is that fair?
