### ISSUE TITLE
Error on install @ionic/v1-util

### ISSUE THREAD

**Issue by flastowizka** [ionic-team/ionic-cli#2953]
**Description:**
I need to configure sass in my ionic project v1. Checking the documentation in the last version need to install @ionic/v1-util

The folder node_modules\@ionic\v1-util is created, but the node_modules\@ionic\v1-util\bin\ionic-v1 no.
After the error the folder node_modules\@ionic\v1-util is deleted.

**Steps to Reproduce:**
1. npm install @ionic/v1-util

**Output:**
PS D:\git\app> npm install @ionic/v1-util --save-dev --save-exact
npm WARN epadoca.com@1.0.0 No repository field.
npm WARN epadoca.com@1.0.0 No license field.
npm WARN The package gulp-sass is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! path D:\git\app\node_modules\@ionic\v1-util\bin\ionic-v1
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\git\app\node_modules\@ionic\v1-util\bin\ionic-v1'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\felip\AppData\Roaming\npm-cache\_logs\2018-01-11T09_44_55_019Z-debug.log

**My `ionic info`:**
cli packages: (C:\Users\felip\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    Cordova Platforms : android 6.1.2 ios 4.3.1
    Ionic Framework   : ionic1 1.3.5

System:

    Android SDK Tools : 26.0.1
    Node              : v8.9.3
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\felip\AppData\Local\Android\Sdk

Misc:

    backend : pro

**Comment by dwieeb** [comment]
@flastowizka What documentation are you following? That package is for the upcoming CLI v4 release. You do not need it for CLI v3.

**Comment by flastowizka** [comment]
@dwieeb I checked and the CLI v4 not available yet :/ 
You know how i can compile sass in CLI v3 ?

**Comment by dwieeb** [comment]
@flastowizka CLI v3 has support for sass in Ionic 1. See https://ionicframework.com/docs/cli/projects.html#enabling-sass

The CLI is likely already compiling sass, you may just need to edit your `index.html` file.

Let me know if you encounter issues.
