### ISSUE TITLE
ionic generate component introduces code with improper styling

### ISSUE THREAD

**Issue by goleary** [ionic-team/ionic-cli#2960]
**Description:**
when i generate a new componenet it gets added to components.module.ts but the whitespace for the newly added component is not inline with the previous components.

is the original  formatting incorrect?

![image](https://user-images.githubusercontent.com/16123225/35071569-fcfb7972-fb95-11e7-9ed5-a632ca4fbab7.png)

**Steps to Reproduce:**

1.`ionic generate component test`
2. look in `src/components/compents.module.ts`

**My `ionic info`:**
![image](https://user-images.githubusercontent.com/16123225/35071609-262afbba-fb96-11e7-8012-c41e70f329dd.png)

**Comment by dwieeb** [comment]
Hi, thanks for creating the issue. If you don't mind, I've been merging issues with generators into a single issue: https://github.com/ionic-team/ionic-cli/issues/2407

I'll be taking a look at styling issues when the revamp happens. 👍
