### ISSUE TITLE
V1 I cannot emulate my app on a android emulator, causes [ERROR] Gulp is not installed! You can install it locally

### ISSUE THREAD

**Issue by JammiM** [ionic-team/ionic-cli#2964]
I cannot emulate my app on a android emulator / simulator

I created a sidemenu template called myApp2

**ionic cordova run android**
causes 
**[ERROR] Gulp is not installed! You can install it locally:**

When I try to emulate android I get this bug
![starting](https://user-images.githubusercontent.com/5257234/35196421-b54130e0-fec9-11e7-86fa-30dc2b1aa7c7.png)

When I run ionic cordova emulate android the subfolders within node_modules remain but their dissappear

Android SDK is installed fine, I created a seperate Cordova projject and emulated an android and it ran fine.

Ionic Info:
![info](https://user-images.githubusercontent.com/5257234/35196441-f405fd2e-fec9-11e7-8df3-a4804637040f.png)

I'm 99% sure the problem is the **ionic.config.json** file, but I don't know how to fix it
(original file)
![1](https://user-images.githubusercontent.com/5257234/35196572-cf7e1d36-fecb-11e7-8928-d00442adf94a.png)

But when I run the command:
**ionic cordova emulate android**
This change happens in the  **ionic.config.json** file,
![2](https://user-images.githubusercontent.com/5257234/35196571-c971b07e-fecb-11e7-87be-ae6fb0e80b8d.png)

**Comment by dwieeb** [comment]
@JammiM Please update your CLI to the latest version. If the problem persists, let me know.
