### ISSUE TITLE
Contributing guidelines - Branching strategy

### ISSUE THREAD

**Issue by Tiberriver256** [ionic-team/ionic-cli#2966]
I'm going to try and tackle one of the issues tagged **Help Wanted** and need a little clarification how to play nicely with the branching strategy.

Should I clone and submit PRs directly to the master branch? or to the 3.x branch which will then later get merged to the master?

Thanks in advance!

**Comment by Tiberriver256** [comment]
Also, if I have other quick questions, I looked in the IonicWorldwide slack channel for a CLI channel but didn't see one. Is there another spot to hang out for quick chats?

**Comment by dwieeb** [comment]
Yeah, sorry. I didn't write my strategies down. There's effectively a feature freeze on the `3.x` branch right now. Bug fixes can go in to `3.x`, but enhancements should go in `master`. It's up to you if you want to create a branch and then PR to master or just use _your_ master and PR to master. I don't really see the difference across forks.

Good idea about the slack channel. Mike just made it for us. We can use that from now on!
