### ISSUE TITLE
Ionic CLI changing package.json version spec from ~ to ^

### ISSUE THREAD

**Issue by seiyoungahn** [ionic-team/ionic-cli#2972]
**Description:**

Running `ionic cordova run` modifies version constraints of package.json so that all tilde (~) become caret (^)

**Steps to Reproduce:**

Run `ionic cordova run` (either android or ios) in your project directory

**Output:**

Version constraints on package.json are changed from ~ to ^

**My `ionic info`:**

    cli packages: (/Users/seiyoungahn/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

    global packages:

    cordova (Cordova CLI) : 7.1.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

    local packages:

    Cordova Platforms : android 6.1.1 ios 4.5.4
    Ionic Framework   : unknown

    System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v6.12.3
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

    Environment Variables:

    ANDROID_HOME : not set

    Misc:

    backend : pro

**Other Information:**

This issue is related to #2230.

**Comment by dwieeb** [comment]
This is a long-standing issue in the Cordova CLI when platforms and plugins are added to a project, which could happen during `cordova prepare`, `cordova run/emulate`, `cordova build`, etc but _only_ happens before the platforms and plugins are downloaded into the project. Once they're added, subsequent command invocations do not change the version ranges. Can you confirm this @seiyoungahn @zmoshansky ?

**Comment by seiyoungahn** [comment]
I can confirm that the version ranges change only when the plugins are added to the project via `cordova run` and not on subsequent command invocations.

**Comment by dwieeb** [comment]
@seiyoungahn Cool, thanks! I made an issue on the Cordova JIRA: https://issues.apache.org/jira/browse/CB-13847

**Comment by jcesarmobile** [comment]
What's your npm save prefix?
`npm config get save-prefix`

I created another issue a month ago about platforms being added with ~ in the config.xml but with the save-prefix in package.json (https://issues.apache.org/jira/browse/CB-13729) and at some point they sync the value changing it in the config.xml.

So, if you have `^` as save-prefix, you can set it to `~` as a workaround
`npm config set save-prefix='~'`

**Comment by seiyoungahn** [comment]
Thanks for the comment. I have tried again after changing npm save-prefix from `^` to `~` as you suggested, and the version constraints remain untouched after `ionic cordova run`. However, it is indeed only a workaround and an alternative solution will be required if you are using yarn elsewhere.

**Comment by jcesarmobile** [comment]
Yeah, that was from preventing the change from `~` to `^` on first place, but once it's changed it doesn't revert it.
