### ISSUE TITLE
`ionic doctor check` throws error after fixing some issues

### ISSUE THREAD

**Issue by CookieCookson** [ionic-team/ionic-cli#2974]
**Description:**

After doing `ionic doctor check` I removed the local ionic from the project, updated app-scripts and rejected to upgrade ionic-native libraries it returned `Error: Cannot find module 'lodash/isEqual'`

![screen shot 2018-02-05 at 13 57 16](https://user-images.githubusercontent.com/3473396/35808140-c8ca3486-0a7c-11e8-92b4-7cb2dfca470e.png)

**Steps to Reproduce:**
See description above

**Output:**
[ERROR] Error: Cannot find module 'lodash/isEqual'

             at Function.Module._resolveFilename (module.js:469:15)
             at Function.Module._load (module.js:417:25)
             at Module.require (module.js:497:17)
             at require (internal/module.js:20:19)
             at Promise.all.Promise.resolve.then
        (/Users/christiancook/Repositories/elixel-cuppa-web/node_modules/@ionic/cli-utils/lib/config.js:90:94)
             at process._tickCallback (internal/process/next_tick.js:109:7)

**My `ionic info`:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.2.3 ios 4.5.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.2
    Node              : v6.11.2
    npm               : 5.6.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/christiancook/Library/Android/sdk/

Misc:

    backend : legacy
```

**Comment by dwieeb** [comment]
@CookieCookson Can you run `npm ls lodash` and post the output?

**Comment by dwieeb** [comment]
@CookieCookson Oops, sorry, nevermind. It looks like it's still loading local CLI files, possibly through the proxy plugin.

`npm uninstall @ionic/cli-plugin-proxy`
`npm uninstall @ionic/cli-utils`

Make sure you have the proxy plugin installed globally.

**Comment by dwieeb** [comment]
📝 Note for myself: check for existence of CLI plugins locally w/o CLI installation

**Comment by CookieCookson** [comment]
Thanks for the fast response @dwieeb, I will give it a go tomorrow.

**Comment by CookieCookson** [comment]
Yep - looks like I still had `@ionic-cli-utils` present in my local repo.
