### ISSUE TITLE
Ionic 3.19.1 Error: tsconfig: Cannot read file

### ISSUE THREAD

**Issue by chriskwanmy** [ionic-team/ionic-cli#2975]
Hello all, I am new to Ionic. I have just installed ionic by 
`npm install -g cordova ionic`

and then I created a sub folder for my new app,
`ionic start myApp tabs`

After all, I wanted to test on the app so I run 
`ionic serve`

However I got some error:
![image](https://user-images.githubusercontent.com/31647046/35820510-bcfb4834-0ae0-11e8-92d4-2f3384c1dda8.png)

I have found some old post here and tried few solutions:
`npm install ionic@latest -g`
`npm run ionic:build`
However it doesn't work and got the similar error (cannot read file)

Below are the version of node and ionic:
![image](https://user-images.githubusercontent.com/31647046/35820619-182fdd6e-0ae1-11e8-9f88-6651de1126fb.png)

**Comment by dwieeb** [comment]
@chriskwanmy Not sure how, but perhaps the `tsconfig.json` file was deleted? You can get a fresh copy here: https://github.com/ionic-team/starters/blob/master/ionic-angular/base/tsconfig.json
