### ISSUE TITLE
No hooks Folder found in my root directory

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-cli#2977]
_From @noor07 on February 6, 2018 11:7_

hi guyz, my ionic version is=> 

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.6
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: Windows 10
Navigator Platform: Win32

I write a command ionic start appname, and there is no hooks folder, plz help, cause i have to use the onesignal plugin.

_Copied from original issue: ionic-team/ionic#13963_

**Comment by dwieeb** [comment]
@noor07 Not sure why you need a hooks folder. Are you getting an error?

In any case, please update your CLI to the latest version and print the output of `ionic info`.

**Comment by noor07** [comment]
I want to use the OneSignal plugin, for this plugin I have to make a js file in my hooks folder as per the https://ionicframework.com/docs/native/onesignal/ this docs link. I have the latest cli, I uninstall it and then install it again, but nothing happened.

cli packages: (C:\Users\hodan\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Misc:

    backend : pro

**Comment by dwieeb** [comment]
@noor07 Could you try adding the hook to `config.xml` instead of using the directory method. You don't need to `chmod +x` the file, either: https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/#configxml

That documentation may need updating.

**Comment by pkitatta** [comment]
OK. Figured it out. For all the lines of code in the `copy_android_notification_icons.js` in the `hook` folder, all it's doing is coping icons from one folder to another - should have guessed from the name! So basically it is as simple as copying the icon folder to the platforms res folder manually after generating the icons, in this case it will be coping icon resources from `resources/android/folder_name/` to `platforms/android/app/src/main/res/` as per the ionic documentation.

The second easy way to do this (The one I use in my project): I add 
```
<resource-file src="resources/android/notification/drawable-mdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-mdpi/ic_stat_onesignal_default.png" />
    <resource-file src="resources/android/notification/drawable-hdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-hdpi/ic_stat_onesignal_default.png" />
    <resource-file src="resources/android/notification/drawable-xhdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-xhdpi/ic_stat_onesignal_default.png" />
    <resource-file src="resources/android/notification/drawable-xxhdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-xxhdpi/ic_stat_onesignal_default.png" />
    <resource-file src="resources/android/notification/drawable-xxxhdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-xxxhdpi/ic_stat_onesignal_default.png" />
```
to the config.xml
Then I load the notification(you can name it anything) folder with the resources I generated from Android Asset Studio. I build the project again and all is good!
