### ISSUE TITLE
ionic g page 命令创建页面，能否将组件ts文件中的构造参数竖着排列？

### ISSUE THREAD

**Issue by 15380831711** [ionic-team/ionic-cli#2979]
//类似这样的
  constructor(
    public navCtrl: NavController, 
    public navParams: NavParams) {
  }

**Comment by dwieeb** [comment]
@15380831711 If you're asking if you can do that, you can. It's valid Javascript/Typescript syntax.

For future issues, please use English. Additionally, for general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).

**Comment by 15380831711** [comment]
Thank you for your reply.
That's what my Chinese translation means.
The ionic g page command creates the page. Can you arrange the configuration parameters in the component ts file vertically?

Now create a page structure like this:
`  constructor(public navCtrl: NavController, public navParams: NavParams) {`
`}`
Could it be:
`  constructor(`
    `public navCtrl: NavController, `
    `public navParams: NavParams) {`
  `}`
Too many parameters are injected, which makes it difficult to read.
`  constructor(
    public translate: TranslateService,public events: Events,public modalCtrl: ModalController,public actionSheetCtrl: ActionSheetController,public httpService: HttpService,public http: Http,public platform: Platform,public app: App
  ) {
  }`

![image](https://user-images.githubusercontent.com/33061032/36007801-f64b7334-0d7e-11e8-9f71-9ad0ebeb75ab.png)


I'm just going to mention it, because everyone's code writing habits are different.

**Comment by kensodemann** [comment]
@15380831711 - Just chiming in here, but I would suggest you (or your team, whatever the situation may be) use a tool like "prettier" to auto-format the code from within your favorite editor. I use it on all my own projects and it works great from within VSCode and while it is opinionated it is also fairly configurable. The default configuration is quite nice, though. The only parameter I override is the one to use single quotes over double quotes (`"prettier.singleQuote": true`)

The advantage with a tool like "prettier" is that it keeps all of your code nicely formatted regardless of how it was generated or how it was later written.

https://github.com/prettier/prettier

**Comment by 15380831711** [comment]
@kensodemann Thanks for the comment.

**Comment by 15380831711** [comment]
@kensodemann  "prettier" 这个插件太强大了！Thank you very much！

**Comment by kensodemann** [comment]
@15380831711 - glad to be of help!
