### ISSUE TITLE
minSdk/targetSdk/maxSdk not respected on Android build

### ISSUE THREAD

**Issue by t-ricci-molecle** [ionic-team/ionic-cli#2981]
**Description:**

I need to make different Android builds and APKs with different Sdk parameters (minSdk, targetSdk and maxSdk). If I use the command `ionic cordova build android --release -- --minSdkVersion={xx}` seems to be ignored. When I print the APK sdk it's different from the specified one.
If I do the same using only the cordova cli it works as intended (`cordova build android --release -- --minSdkVersion={xx}`).

**Steps to Reproduce:**

Make a build using the command `ionic cordova build android --release -- --minSdkVersion=21`.
Inspect the apk using the command `aapt list -a my.apk | grep SdkVersion` and convert the last hex number to decimal (ex. 0x10 equals decimal 16).

Example repo: 

0. N/A

**Output:**

No errors output.

**My `ionic info`:**

cli packages: (/Users/tommasoricci/.nvm/versions/node/v9.4.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v9.4.0
    npm  : 5.6.0
    OS   : macOS High Sierra

Misc:

    backend : pro

**Other Information:**

**Comment by dwieeb** [comment]
It's weird, but you need to include an additional `--` separator because the Cordova CLI is wrapped by the Ionic CLI in this instance. Try `ionic cordova build android --release -- -- --minSdkVersion=21`. See `ionic cordova build --help` for more examples.
