### ISSUE TITLE
Error building android version of ionic1 app from the new cli (... skipped because it has an unsupported size (undefinedxundefined): ...)

### ISSUE THREAD

**Issue by Austyns** [ionic-team/ionic-cli#2983]
**Description:**
I am unable to create a build if an ionic1 project with the new cli. It always shows this error 
``` The following image was skipped because it has an unsupported size (undefinedxundefined): resources/android/icon/drawable-xhdpi-icon.png ```

**Steps to Reproduce:**
When i run ``` ionic cordova build android ``` it throws Error

 ``` The following image was skipped because it has an unsupported size (undefinedxundefined): resources/android/icon/drawable-xhdpi-icon.png```

But when i generate a new project, i am able to successfully build. 

I have also replaced icons folder of the project with the icon folder from a new project but still the same 

**My `ionic info`:**
``` 
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 5.2.2 ios 4.2.0 windows 4.4.2
    Ionic Framework   : ionic1 1.3.1

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : Linux 4.4

Environment Variables:

    ANDROID_HOME : /home/austyns/Android/Sdk

Misc:

    backend : pro
```

**Comment by dwieeb** [comment]
@Austyns Can I get the full output from `ionic cordova build android`?
