### ISSUE TITLE
feature require: option of source directory

### ISSUE THREAD

**Issue by PoiScript** [ionic-team/ionic-cli#2985]
I'm trying to build an ionic app alongside with an existing project that also contains `src/`. In order not to mess up the original structure, I don't want to put my ionic code in `src/` but `ionic/`. 

However, there seems like not such option on ionic-cli that configures which directory to be the source code directory. :(

**Comment by dwieeb** [comment]
@PoiScript This becomes quite tough as Ionic integrates with a plethora of existing tools that expect a certain directory structure. For now, I highly recommend creating a new repo for your Ionic project.

**Comment by dwieeb** [comment]
@PoiScript Can you help me understand your use case a bit more? You want to basically share code from an existing non-Ionic project, correct?

**Comment by PoiScript** [comment]
@dwieeb yes, you're right. It was an angular-cli project. What I want to do it share some services (called provider in ionic) the website built with angular-cli and the app built with ionic-cli.  These services is used to connect with the back-end using `HttpClientModule`. If they works in angular, they should works with ionic.

Also maybe some components will be shared,  but I'm not sure if angular material can work properly in ionic.

**Comment by dwieeb** [comment]
@PoiScript Understood, thanks! I think this feature request relates to some others I've tied together in this mega issue: https://github.com/ionic-team/ionic-cli/issues/2232

Please let's continue the discussion there.
