### ISSUE TITLE
pro ssh doesn't use the public key but the private key!

### ISSUE THREAD

**Issue by dalu** [ionic-team/ionic-cli#2986]
**Description:**

I just tried ionic pro and picked that it should use my default key and allowed for it to make changes automatically to ~/.ssh/config
But the identityfile that was picked was the actual private key file (wtf!). id_rsa instead of id_rsa.pub

**Steps to Reproduce:**

create a new project with ionic pro under linux

**Output:**

**My `ionic info`:**
```
cli packages: (/home/darko/.nvm/versions/node/v9.3.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

System:

    Node : v9.3.0
    npm  : 5.6.0 
    OS   : Linux 4.15

Misc:

    backend : pro
```

I'm not sure what happens when the file that contains the private and public key is used, but I have to generate a new key now because of your maybe oversight, maybe not!

**Comment by dwieeb** [comment]
The `IdentityFile` that it picks for your SSH config must be a path to the private key. The private key is never read, only the existence of the file is checked. 

Here's a decent blog post that goes over some basics of the config file being modified on your computer: http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/
