### ISSUE TITLE
ionic cli not using the latest default .gitignore file

### ISSUE THREAD

**Issue by bholben** [ionic-team/ionic-cli#2993]
**Description:**
`ionic start myapp` is not scaffolding the app with the latest **.gitignore** file

**Steps to Reproduce:**
1. Run `ionic start myapp blank`
2. Notice that the **.gitignore** file does not contain **www/**

**Other Information:**
As of today, the ionic cli defaults to ionic-angular v 3.9.2.  Per Brian Mannings [helpful post](https://ionic.zendesk.com/hc/en-us/articles/360000139267-Restoring-the-default-gitignore-file), the **www/** folder is not needed ever since Ionic 2.  His post references the "default **.gitignore** file" located at https://github.com/ionic-team/ionic2-app-base/blob/master/.gitignore, however the cli does not seem to be using this "default file".

**Comment by dwieeb** [comment]
Not able to reproduce the issue:

```
$ ionic start myapp blank

...

$ cd myapp

$ cat .gitignore

# Specifies intentionally untracked files to ignore when using Git
# http://git-scm.com/docs/gitignore

*~
*.sw[mnpcod]
*.log
*.tmp
*.tmp.*
log.txt
*.sublime-project
*.sublime-workspace
.vscode/
npm-debug.log*

.idea/
.sourcemaps/
.sass-cache/
.tmp/
.versions/
coverage/
dist/
node_modules/
tmp/
temp/
hooks/
platforms/
plugins/
plugins/android.json
plugins/ios.json
www/
$RECYCLE.BIN/

.DS_Store
Thumbs.db
UserInterfaceState.xcuserstate
```

If this is a reproducible issue for you, please submit your `ionic info`.

**Comment by bholben** [comment]
Hmm.  I don't know what my issue was yesterday.  I just did this again a couple times with different answers to cli questions.  Each time worked correctly as you show.  Thanks for checking on this.  I'm closing this issue.
