### ISSUE TITLE
ionic-native/sms plugin not working on all android OS.

### ISSUE THREAD

**Issue by avaiskhatri** [ionic-team/ionic-cli#2999]
Hi, 
I have added **ionic-native/sms** plugin in my app using following commands in CLI

`ionic cordova plugin add cordova-sms-plugin@latest`
`npm install --save @ionic-native/sms`

Build is successful without any error, and app is working fine except that sms plugin. I have test the app in multiple devices having Android Versions 4.0,5.0,6.0,7.0 and there variants. 
The sms plugin is only working in **Android 6.0** and not working in remaining OS and resulting in error message **"ERROR"**.

It would be thankful if anyone help me out. Thanks.

**Comment by dwieeb** [comment]
@avaiskhatri Could you please fill out the issue template? In order to help, I need `ionic info` and full command output. Pictures help, too. I don't know where the message "ERROR" is even happening or if there's more details. 

If you believe this is not a CLI issue, a better spot for support requests is the [Ionic Forum](https://forum.ionicframework.com/).

**Comment by avaiskhatri** [comment]
![ionic info](https://user-images.githubusercontent.com/15321796/36639786-a4180758-1a35-11e8-958c-6ad6f8a81db8.png)

This is the ionic info image.

**Comment by avaiskhatri** [comment]
Hi, I have just tested the same app on other phones; and founds that its only failed to use sms plugin in dual sim phones and phone working on Android OS < 6.0.1.
Plugin work fines in single sim phone, whereas its not functioning in dual sim phones.

**Comment by avaiskhatri** [comment]
@dwieeb  Hi, I have just tested the same app on other phones; and founds that its only failed to use sms plugin in dual sim phones and phone working on Android OS < 6.0.1.
Plugin work fines in single sim phone, whereas its not functioning in dual sim phones.

**Comment by dwieeb** [comment]
I think this would be better suited for the Ionic Forum: https://forum.ionicframework.com

If there's a bug in the plugin, please create a bug report in the Ionic Native repo: https://github.com/ionic-team/ionic-native
