### ISSUE TITLE
[Project] Ionic Angular 4

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic-cli#3003]
- [x] Building for native platform includes all the native plugin code
- [ ] Browser opens up before webpack is ready (waiting on angular-cli) (see https://github.com/ionic-team/ionic-cli/issues/3357)

**Comment by dwieeb** [comment]
> Building for native platform includes all the native plugin code

@mhartington This has to happen for Cordova run w/ live-reload. We're explicitly telling the Angular CLI about the assets so `ng serve` can provide them. It doesn't need to be done for `ng build`, though... hmm.

**Comment by dwieeb** [comment]
See https://github.com/ionic-team/ionic-cli/issues/3357 for the second checkmark.
