### ISSUE TITLE
how to create ssh key in ionic pro create login in cmd how?

### ISSUE THREAD

**Issue by novan11** [ionic-team/ionic-cli#3011]
why i always fail login in cmd when told to enter ionic pro

**Comment by novan11** [comment]
help me

**Comment by dwieeb** [comment]
It could be your backend is still set to legacy. Try this:

```
ionic config set -g backend pro
ionic login
```

If you need more assistance, please see our [Support Page](https://ionicframework.com/support). This repo is reserved for bug reports and feature requests of the Ionic CLI. 

Thanks!
