### ISSUE TITLE
ENOENT for platforms/android/res/xml on building app for android with App Preferences plugin installed

### ISSUE THREAD

**Issue by Genarito** [ionic-team/ionic-cli#3014]
**Description:**

I having a problem bulding my app after installing [App Preferences plugin](https://ionicframework.com/docs/native/app-preferences/). 

To corroborate, I created a new Tab project, it was builded successfully, but then, I installed that plugin and problems came back again.

**Steps to Reproduce:**

1. ionic start beautiful_error
2. cd beautiful_error
3. ionic cordova plugin add cordova-plugin-app-preferences
4. npm install --save @ ionic-native/app-preferences
5. ionic cordova build android

**Output:**
Building terminates with this error:

> will push strings array {"name":"lang","titles":["English (US)","English (UK)"],"values":["en-us","en-gb"]}
unhandled exception { Error: ENOENT: no such file or directory, mkdir 'platforms/android/res/xml'
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'platforms/android/res/xml' }
(node:10363) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir 'platforms/android/res/xml'
(node:10363) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10363) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BenjaminGlusa** [comment]
Same here. It occurs when executing `ionic cordova platform add android`.

**Comment by dwieeb** [comment]
Does this happen with Cordova 7?

**Comment by BenjaminGlusa** [comment]
In my case it is Cordova 7.0.0.

**Comment by Genarito** [comment]
Me too
En 21 de marzo de 2018, en 18:32, Benjamin Glusa <notifications@github.com<mailto:notifications@github.com>> escribió:

In my case it is Cordova 7.0.0.

**Comment by Genarito** [comment]
Other detail: when I execute `ionic cordova plugin remove cordova-plugin-app-preferences` this happens:

> Settings.bundle is generated by external tool, skipping
unhandled exception { Error: ENOENT: no such file or directory, unlink 'platforms/android/res/xml/apppreferences.xml'
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'platforms/android/res/xml/apppreferences.xml' }
(node:27274) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink 'platforms/android/res/xml/apppreferences.xml'
(node:27274) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27274) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Genarito** [comment]
Same happens with Background Geolocation plugin!

**Comment by ichinnasamy** [comment]
Any body found a solution, I get the same error.

**Comment by ichinnasamy** [comment]
In my case it is cordova 8.0.0

**Comment by Genarito** [comment]
I have an old virtual machine with Cordova 6 and error doesn't happen. But I tried downgrading  versions in this project and got the same error

**Comment by dwieeb** [comment]
@Genarito I tried this out a little while ago and was getting it, too. I apologize I haven't had time to dig further. I've been busy with Ionic CLI 4. If you find out more, please update the issue. Otherwise I'll try to find some time at a later date.

**Comment by Genarito** [comment]
No problem! Thank you so much

**Comment by jqzhao** [comment]
Is there any update? We're seeing exactly the same error. Android build fails and so did removing app-preferences. I'm on cordova 8 and cordova android 7.1.0. Didn't see this problem before upgrade cordova android from 6.3.0 to 7.1.0

**Comment by Genarito** [comment]
I have discovered that it's an already issue in [the plugin's repo](https://github.com/apla/me.apla.cordova.app-preferences/issues/135). As one user said on it, it can be fixed with:

`cordova plugin add https://github.com/vash15/me.apla.cordova.app-preferences`

Note: perhaps you need to increase the minSdk parameter at your `config.xml` file to "19" to get it working

**Comment by looiwailung** [comment]
a poor version for this cordova 7.0.0, the root cause is the /res folder disappear. so only way is to downgrade to version 6.3.0

**Comment by Edison4mobile** [comment]
@Genarito  Thanks a lot.
You are awsome!!! +++++
