### ISSUE TITLE
Ionic 3.19.0 asks for CLI update but continues to ask for update after accepting.

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-cli#3021]
_From @bfontana on March 22, 2018 13:37_

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**

When running a "ionic serve" command CLI asks to upgrade. After enter Y it seems to upgrade but next time you run "ionic serve" (or any other ionic command) upgrade question appears again.

**Expected behavior:**

CLI updated after accepting update.

**Steps to reproduce:**

macOS Sierra with Ionic CLI 3.19.0. Issue any CLI command (except for "ionic cordova ..." commands) and you'll see this

> ionic serve --lab --locale

> The Ionic CLI has an update available (3.19.0 => 3.20.0)! Would you like to in
stall it? Yes
> npm i -g ionic@latest
✔ Running command - done!

[OK] Updated Ionic CLI to 3.20.0! 🎉

> Please re-run your command.

> Note: You can downgrade to your old version by running: npm i -g ionic@3.19.0
>$ ionic serve --lab --locale

> The Ionic CLI has an update available (3.19.0 => 3.20.0)! Would you like to in
stall it? 

and again, ...and again.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : browser 5.0.1 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.6.0
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

_Copied from original issue: ionic-team/ionic#14215_

**Comment by dwieeb** [comment]
@bfontana I see the CLI version is still 3.19.0 in `ionic info`: `ionic (Ionic CLI) : 3.19.0`

Could you post the output of `npm i -g ionic@latest` ?

**Comment by bfontana** [comment]
There you go. Command Line + ionic info + debug log file in .npm

### Command line
$ npm i -g ionic@
/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic
+ ionic@3.20.0
added 2 packages, removed 4 packages and updated 48 packages in 63.103s


### ionic info

[WARN] You are not in an Ionic project directory. Project context may be 
       missing.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.6.0
    npm  : 5.5.1 
    OS   : macOS Sierra

Misc:

    backend : pro


## debug file from $HOME/.npm/_logs

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'ionic@latest' ]
2 info using npm@5.5.1
3 info using node@v8.6.0
4 verbose npm-session 51c2c30b149e68a6
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/ionic 1617ms
8 silly pacote tag manifest for ionic@latest fetched in 2090ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule ionic@3.20.0 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/chalk 478ms (from cache)
15 silly pacote range manifest for chalk@^2.3.0 fetched in 519ms
16 silly resolveWithNewModule chalk@2.3.2 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/semver 530ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/opn 613ms (from cache)
19 silly pacote range manifest for semver@^5.3.0 fetched in 620ms
20 silly resolveWithNewModule semver@5.5.0 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/tslib 631ms (from cache)
22 silly pacote range manifest for opn@^5.1.0 fetched in 639ms
23 silly resolveWithNewModule opn@5.3.0 checking installable status
24 silly pacote range manifest for tslib@^1.8.0 fetched in 690ms
25 silly resolveWithNewModule tslib@1.9.0 checking installable status
26 http fetch GET 200 https://registry.npmjs.org/@ionic%2fcli-framework 1347ms
27 silly pacote version manifest for @ionic/cli-framework@0.1.3 fetched in 1402ms
28 silly resolveWithNewModule @ionic/cli-framework@0.1.3 checking installable status
29 http fetch GET 200 https://registry.npmjs.org/@ionic%2fcli-utils 1477ms
30 silly pacote version manifest for @ionic/cli-utils@1.19.2 fetched in 1536ms
31 silly resolveWithNewModule @ionic/cli-utils@1.19.2 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/rimraf 283ms (from cache)
33 http fetch GET 304 https://registry.npmjs.org/strip-ansi 283ms (from cache)
34 silly pacote range manifest for rimraf@^2.6.2 fetched in 321ms
35 silly resolveWithNewModule rimraf@2.6.2 checking installable status
36 silly pacote range manifest for strip-ansi@^4.0.0 fetched in 375ms
37 silly resolveWithNewModule strip-ansi@4.0.0 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/superagent 394ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/ncp 417ms (from cache)
40 silly pacote range manifest for superagent@^3.8.0 fetched in 434ms
41 silly resolveWithNewModule superagent@3.8.2 checking installable status
42 silly pacote range manifest for ncp@^2.0.0 fetched in 449ms
43 silly resolveWithNewModule ncp@2.0.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/supports-color 273ms (from cache)
45 silly pacote range manifest for supports-color@^5.3.0 fetched in 284ms
46 silly resolveWithNewModule supports-color@5.3.0 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 285ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/ansi-styles 317ms (from cache)
49 silly pacote range manifest for escape-string-regexp@^1.0.5 fetched in 344ms
50 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
51 silly pacote range manifest for ansi-styles@^3.2.1 fetched in 398ms
52 silly resolveWithNewModule ansi-styles@3.2.1 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/color-convert 242ms (from cache)
54 silly pacote range manifest for color-convert@^1.9.0 fetched in 290ms
55 silly resolveWithNewModule color-convert@1.9.1 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/color-name 188ms (from cache)
57 silly pacote range manifest for color-name@^1.1.1 fetched in 214ms
58 silly resolveWithNewModule color-name@1.1.3 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/has-flag 212ms (from cache)
60 silly pacote range manifest for has-flag@^3.0.0 fetched in 246ms
61 silly resolveWithNewModule has-flag@3.0.0 checking installable status
62 http fetch GET 304 https://registry.npmjs.org/glob 113ms (from cache)
63 silly pacote range manifest for glob@^7.0.5 fetched in 140ms
64 silly resolveWithNewModule glob@7.1.2 checking installable status
65 http fetch GET 304 https://registry.npmjs.org/inherits 377ms (from cache)
66 silly pacote range manifest for inherits@2 fetched in 407ms
67 silly resolveWithNewModule inherits@2.0.3 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/minimatch 409ms (from cache)
69 http fetch GET 304 https://registry.npmjs.org/inflight 413ms (from cache)
70 silly pacote range manifest for minimatch@^3.0.4 fetched in 415ms
71 silly resolveWithNewModule minimatch@3.0.4 checking installable status
72 silly pacote range manifest for inflight@^1.0.4 fetched in 416ms
73 silly resolveWithNewModule inflight@1.0.6 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/fs.realpath 419ms (from cache)
75 http fetch GET 304 https://registry.npmjs.org/path-is-absolute 417ms (from cache)
76 http fetch GET 304 https://registry.npmjs.org/once 419ms (from cache)
77 silly pacote range manifest for fs.realpath@^1.0.0 fetched in 422ms
78 silly resolveWithNewModule fs.realpath@1.0.0 checking installable status
79 silly pacote range manifest for once@^1.3.0 fetched in 421ms
80 silly resolveWithNewModule once@1.4.0 checking installable status
81 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 466ms
82 silly resolveWithNewModule path-is-absolute@1.0.1 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/wrappy 177ms (from cache)
84 silly pacote range manifest for wrappy@1 fetched in 232ms
85 silly resolveWithNewModule wrappy@1.0.2 checking installable status
86 http fetch GET 304 https://registry.npmjs.org/brace-expansion 146ms (from cache)
87 silly pacote range manifest for brace-expansion@^1.1.7 fetched in 185ms
88 silly resolveWithNewModule brace-expansion@1.1.11 checking installable status
89 http fetch GET 304 https://registry.npmjs.org/balanced-match 305ms (from cache)
90 http fetch GET 304 https://registry.npmjs.org/concat-map 331ms (from cache)
91 silly pacote version manifest for concat-map@0.0.1 fetched in 341ms
92 silly resolveWithNewModule concat-map@0.0.1 checking installable status
93 silly pacote range manifest for balanced-match@^1.0.0 fetched in 342ms
94 silly resolveWithNewModule balanced-match@1.0.0 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/ansi-regex 752ms (from cache)
96 silly pacote range manifest for ansi-regex@^3.0.0 fetched in 808ms
97 silly resolveWithNewModule ansi-regex@3.0.0 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/component-emitter 1690ms (from cache)
99 http fetch GET 304 https://registry.npmjs.org/debug 1691ms (from cache)
100 http fetch GET 304 https://registry.npmjs.org/extend 1718ms (from cache)
101 http fetch GET 304 https://registry.npmjs.org/form-data 1718ms (from cache)
102 http fetch GET 304 https://registry.npmjs.org/cookiejar 1908ms (from cache)
103 http fetch GET 304 https://registry.npmjs.org/methods 1907ms (from cache)
104 http fetch GET 304 https://registry.npmjs.org/formidable 1922ms (from cache)
105 silly pacote range manifest for component-emitter@^1.2.0 fetched in 1971ms
106 silly resolveWithNewModule component-emitter@1.2.1 checking installable status
107 silly pacote range manifest for debug@^3.1.0 fetched in 1997ms
108 silly resolveWithNewModule debug@3.1.0 checking installable status
109 silly pacote range manifest for extend@^3.0.0 fetched in 1998ms
110 silly resolveWithNewModule extend@3.0.1 checking installable status
111 silly pacote range manifest for form-data@^2.3.1 fetched in 2025ms
112 silly resolveWithNewModule form-data@2.3.2 checking installable status
113 silly pacote range manifest for cookiejar@^2.1.0 fetched in 2027ms
114 silly resolveWithNewModule cookiejar@2.1.1 checking installable status
115 http fetch GET 304 https://registry.npmjs.org/mime 2027ms (from cache)
116 http fetch GET 304 https://registry.npmjs.org/qs 2039ms (from cache)
117 silly pacote range manifest for methods@^1.1.1 fetched in 2042ms
118 silly resolveWithNewModule methods@1.1.2 checking installable status
119 silly pacote range manifest for formidable@^1.1.1 fetched in 2070ms
120 silly resolveWithNewModule formidable@1.2.1 checking installable status
121 silly pacote range manifest for qs@^6.5.1 fetched in 2182ms
122 silly resolveWithNewModule qs@6.5.1 checking installable status
123 http fetch GET 304 https://registry.npmjs.org/readable-stream 2208ms (from cache)
124 silly pacote range manifest for mime@^1.4.1 fetched in 2219ms
125 silly resolveWithNewModule mime@1.6.0 checking installable status
126 silly pacote range manifest for readable-stream@^2.0.5 fetched in 2248ms
127 silly resolveWithNewModule readable-stream@2.3.5 checking installable status
128 http fetch GET 304 https://registry.npmjs.org/ms 246ms (from cache)
129 silly pacote version manifest for ms@2.0.0 fetched in 247ms
130 silly resolveWithNewModule ms@2.0.0 checking installable status
131 http fetch GET 304 https://registry.npmjs.org/asynckit 385ms (from cache)
132 silly pacote range manifest for asynckit@^0.4.0 fetched in 428ms
133 silly resolveWithNewModule asynckit@0.4.0 checking installable status
134 http fetch GET 304 https://registry.npmjs.org/mime-types 682ms (from cache)
135 http fetch GET 304 https://registry.npmjs.org/combined-stream 723ms (from cache)
136 silly pacote range manifest for mime-types@^2.1.12 fetched in 743ms
137 silly resolveWithNewModule mime-types@2.1.18 checking installable status
138 silly pacote version manifest for combined-stream@1.0.6 fetched in 748ms
139 silly resolveWithNewModule combined-stream@1.0.6 checking installable status
140 http fetch GET 304 https://registry.npmjs.org/delayed-stream 309ms (from cache)
141 silly pacote range manifest for delayed-stream@~1.0.0 fetched in 323ms
142 silly resolveWithNewModule delayed-stream@1.0.0 checking installable status
143 error cb() never called!
144 error This is an error with npm itself. Please report this error at:
145 error <https://github.com/npm/npm/issues>

**Comment by dwieeb** [comment]
Okay so now `ionic info` is saying the CLI version is `3.20.0`, which is the latest. Is it still prompting you to update?

**Comment by bfontana** [comment]
Nop, it isn’t.

**Comment by dwieeb** [comment]
So I would guess the original update via npm failed somehow.

**Comment by bfontana** [comment]
Yap, likely, so issue can be closed.
I’ll report back if problem arises again.

Thanks!!!

Regards

**Comment by JuliaRakitina** [comment]
Have same issue 


```
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.1
   ios-sim           : 5.0.9
   NodeJS            : v8.9.4 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/julia/Library/Android/sdk
```
System continuously asks for update, I am updating it. NPM reports that everything ok, but Ionic cli does not updates

**Comment by dwieeb** [comment]
@JuliaRakitina I would manually uninstall and reinstall the Ionic CLI, making sure your npm environment is properly set up and that no other environments are conflicting with it.

**Comment by JuliaRakitina** [comment]
> I would manually uninstall and reinstall the Ionic CLI
manually? You mean delete folders?

**Comment by dwieeb** [comment]
Yeah, or ensure that `npm uninstall -g ionic` is removing the `/usr/local/lib/node_modules/ionic` folder and the bin file at `/usr/local/bin/ionic`.
