### ISSUE TITLE
@ionic/lab is required for Ionic Lab to work properly

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#3029]
**Description:**
Testing 4.0 RC

**Steps to Reproduce:**

**Output:**
```
[app-scripts] [21:10:42]  watch ready in 13.71 s
> ionic-lab http://localhost:8100 --host localhost --port 8200 --app-name aedh --app-version 0.2.9
[lab] 'ionic-lab' is not recognized as an internal or external command,
[lab] operable program or batch file.

[ERROR] @ionic/lab is required for Ionic Lab to work properly.

        Looks like @ionic/lab isn't installed in this project.
        This package is required for Ionic Lab as of CLI 4.0. For more details, please see the CHANGELOG:
        https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#4.0.0

Terminate batch job (Y/N)? y

```

**My `ionic info`:**
```
C:\ae\adaept.com\test-side-menu-content>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.0
   ionic (Ionic CLI) : 4.0.0-rc.0

local packages:

   @ionic/app-scripts : 2.1.3
   Ionic Framework    : ionic-angular 3.9.2

System:

   NodeJS : v8.9.4
   npm    : 5.6.0
   OS     : Windows 10
```

**Other Information:**
Referenced link does not seem to provide any useful information about installation of ionic/lab

**Comment by rdlabo** [comment]
I seem `ionic-app-scripts` is too old. ( recent version is ionic-app-scripts 3.1.8 )

You should do `ionic docker check`.

**Comment by dwieeb** [comment]
Thanks @peterennis, I launched RC.0 without the automatic installation due to some dependency issue I don't remember. 😆 I'll add it back for the next RC.

In the meantime, try this: `npm i @ionic/lab@rc` 🎉

**Comment by dwieeb** [comment]
@peterennis Please test the behavior in the latest RC release and let me know what you think. Thanks!

**Comment by Boyejay** [comment]
I had similar issues and solved it with the method of dwieeb.Thanks!

**Comment by franciscojsc** [comment]
It worked with the command ``npm i @ionic/lab@rc`` @dwieeb

**Comment by dwieeb** [comment]
Yep, but that was in March. The CLI is no longer in RC. Please make sure all packages are up to date.

```
npm i -g ionic
npm i @ionic/lab
```
