### ISSUE TITLE
[Question] Can CLI check version of local package now? 

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-cli#3049]
**Description:**
in a few months ago. when `$ionic serve` execute,  check version of local package.
ex) `? The Ionic CLI has an update available (3.19.1 => 3.20.0)! Would you like to install it? Yes`
This is one of my very favorite functions.

But today, I notice this is not check. and be able to check `$ionic doctor` only.

Did this function move? 

**Steps to Reproduce:**

I tried local version down `@ionic/app-scripts@3.1.0` and `@ionic/app-scripts@3.1.7`.
and execute `$ionic serve`.

**Output:**
none.

**My `ionic info`:**
```
cli packages: (/Users/sakakibara/dev/ionic-cli/packages)

   @ionic/cli-utils  : 2.0.0-rc.1
   ionic (Ionic CLI) : 4.0.0-rc.1

global packages:

   cordova (Cordova CLI) : 8.0.0 

local packages:

   @ionic/app-scripts : 3.1.0
   Cordova Platforms  : android 5.2.2 browser 4.1.0 ios 4.2.1
   Ionic Framework    : ionic-angular 3.9.0

System:

   Android SDK Tools : 25.2.3
   ios-deploy        : 1.9.2 
   ios-sim           : 3.1.1 
   NodeJS            : v8.9.3
   npm               : 5.7.1 
   OS                : macOS High Sierra
   Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

   ANDROID_HOME : /Users/sakakibara/Library/Android/sdk
```

**Other Information:**
If use`@ionic/app-scripts@2.1.4` , only errors are displayed and don'r encourage updating.
I noticed that automatic updates do not run with this.

```
> ionic-app-scripts serve --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
[app-scripts] module.js:538
[app-scripts]     throw err;
[app-scripts]     ^
[app-scripts] 
[app-scripts] Error: Cannot find module '@angular/tsc-wrapped/src/tsc'
[app-scripts]     at Function.Module._resolveFilename (module.js:536:15)
[app-scripts]     at Function.Module._load (module.js:466:25)
[app-scripts]     at Module.require (module.js:579:17)
[app-scripts]     at require (internal/module.js:11:18)
[app-scripts]     at Object.<anonymous> (/Users/sakakibara/dev/ionic-wpcom/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:7:13)
[app-scripts]     at Module._compile (module.js:635:30)
[app-scripts]     at Object.Module._extensions..js (module.js:646:10)
[app-scripts]     at Module.load (module.js:554:32)
[app-scripts]     at tryModuleLoad (module.js:497:12)
[app-scripts]     at Function.Module._load (module.js:489:3)
```

**Comment by dwieeb** [comment]
People don't want it, I guess: https://github.com/ionic-team/ionic-cli/issues/2517 ¯\\\_(ツ)\_/¯

It _does_ use update-notifier (which is what npm uses) to display a notification about an update. You'll see this as soon as 4.1.0/4.0.1 comes out.

I think it's a happy medium.

**Comment by rdlabo** [comment]
Oh... I see. I understand.I will use update-notifier and `$ionic doctor`. 
thanks.
