### ISSUE TITLE
android-maven-gradle-plugin-1.5.jar

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-cli#3056]
_From @huxiaozhong on March 29, 2018 10:22_

D:\code\PeiXunApp\app3>ionic info
[WARN] Error with .\www\lib\ionic\version.json file: FILE_NOT_FOUND, trying .\bower.json.

cli packages: (D:\code\PeiXunApp\app3\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 7.0.0
    Ionic Framework   : ionic1 1.3.4

System:

    Node : v6.10.3
    npm  : 3.10.10
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**when run  ionic cordova build android  get fllow error:**

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':CordovaLib'.
> Could not resolve all files for configuration ':CordovaLib:classpath'.
   > Could not find android-maven-gradle-plugin.jar (com.github.dcendents:android-maven-gradle-plugin:1.5).
     Searched in the following locations:

         https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.5/android-maven-gradle-plugin-1.5.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
 option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
(node:2924) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':CordovaLib'.
> Could not resolve all files for configuration ':CordovaLib:classpath'.
   > Could not find android-maven-gradle-plugin.jar (com.github.dcendents:android-maven-gradle-plugin:1.5).
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.5/android-maven-gradle-plugin-1.5.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

how to fix it? my ionic project is  ionic1 

_Copied from original issue: ionic-team/ionic#14252_

**Comment by dwieeb** [comment]
@huxiaozhong Let's reserve this repo for features/suggestions/bugs for the Ionic CLI. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).

Alternatively, to get more eyes on this issue, try searching/posting in the [Ionic Forum](https://forum.ionicframework.com/). 

Thanks!
