### ISSUE TITLE
npm warning when installing npm install -g ionic

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-cli#3059]
_From @themhz on April 4, 2018 16:53_

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

when I run npm install -g ionic I get 
PS C:\wamp64\www\ionic> npm install -g ionic
C:\Users\themhz\AppData\Roaming\npm\ionic -> C:\Users\themhz\AppData\Roaming\npm\node_modules\ionic\bin\ionic
npm WARN rollback Rolling back readable-stream@2.2.9 failed (this is probably harmless): EPERM: operation not permitted,
 lstat 'C:\Users\themhz\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back tar-pack@3.4.0 failed (this is probably harmless): EPERM: operation not permitted, lstat
'C:\Users\themhz\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back ajv@4.11.8 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\
Users\themhz\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\ionic\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})

+ ionic@3.20.0
added 253 packages from 152 contributors in 18.001s
**Expected behavior:**

I don't know
**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
PS C:\wamp64\www\ionic> ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (C:\Users\themhz\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.9.1
    npm  : 6.0.0-next.0
    OS   : Windows 10

Misc:

    backend : pro

_Copied from original issue: ionic-team/ionic#14279_

**Comment by dwieeb** [comment]
@themhz This doesn't look like a bug. The CLI was installed successfully.

**Comment by rdlabo** [comment]
> npm WARN rollback Rolling back readable-stream@2.2.9 failed (this is probably harmless): EPERM: operation not permitted,
`readable-stream` may be `fsevents`  > ` are-we-there-yet`  > ` chokidar-cli` dependencies package...

I think that it will not be a problem because the console alerts `this is probably harmless`.

**Comment by themhz** [comment]
Thank you, but it is annoying. Do I need fsevents? Why do I get prompted ? should I just ignore it? do others get the same message under windows 10?

**Comment by rdlabo** [comment]
@themhz `ionic` dependencies `chokidar-cli` .
https://github.com/ionic-team/ionic-cli/blob/master/package.json#L22

I think it is good to ignore it once.

**Comment by dwieeb** [comment]
@themhz `fsevents` will only work on macOS. It's an optional dependency that improves performance on macOS. The other warnings, I'm not sure. I haven't had a chance to use the beta 6 of npm cli.

There's not much we can do about npm warnings; it's a different program. We could offer a download option for our CLI which bundles node and the CLI code into one executable, but I don't see that happening any time soon.
