### ISSUE TITLE
Android builds with cordova-android 7.0.0 failing  [ With ionic ]

### ISSUE THREAD

**Issue by amjayesh07** [ionic-team/ionic-cli#3065]
**Description:**

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

**Comment by Jayesh07** [comment]
The latest version of the cordova-android platform (7.0.0) is not yet supported by Ionic Pro's Package service. If you are seeing Android build failures, and have this version of the platform installed, update your config.xml and package.json files to explicitly reference version 6.4.0 instead.

**Comment by dwieeb** [comment]
@Jayesh07 You didn't fill out the issue template and I'm not sure what issue you're actually reporting. If this is an issue with Ionic Pro, please fill out a [Support Request](https://ionicframework.com/support/request).
