### ISSUE TITLE
I cann't download and extracting blank starter

### ISSUE THREAD

**Issue by Mrsbetter** [ionic-team/ionic-cli#3073]
## **ionic Downloading falied**

**D:\>ionic start myapps blank --type3 --skip-npm**
√ Creating directory .\myapps - done!
× Downloading and extracting blank starter - failed!
**Error: read ECONNRESET
at TLSWrap.onread (net.js:602:25)**

**## open the PowerShell:(I have installed Python2.7.14 and vs2017)**

**PS C:\WINDOWS\system32> ionic info**
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (C:\Users\Administrator\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v9.11.1
    npm  : 5.8.0
    OS   : Windows 10

Misc:

    backend : pro

**Comment by dwieeb** [comment]
@Mrsbetter Are you able to download this file? https://d2ql0qc7j8u4b2.cloudfront.net/ionic-angular-official-blank.tar.gz

**Comment by tanbing2016** [comment]
@dwieeb I can download that file , but ionic start still make a error.

**Comment by dwieeb** [comment]
You are likely behind a proxy, which means you'll need to configure the Ionic CLI so it can use your proxy. https://ionicframework.com/docs/cli/configuring.html#using-a-proxy

**Comment by tanbing2016** [comment]
@dwieeb I'm sure I didn't use the proxy,I used ionic in my home,and I don't know the proxy's IP,thanks.

**Comment by dwieeb** [comment]
You likely need to configure your environment for your network proxy:

* Please carefully follow the docs: https://ionicframework.com/docs/cli/using-a-proxy
* Your organization needs to provide proxy details for you. If you don't know the details, talk with your network administrator.
* Remember to avoid disabling SSL verification. This can lead to prolonged insecure configuration with your computer.
