### ISSUE TITLE
Testing Ionic 4 - CLI Basic vs. Ionic Conference App

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#3083]
What is the standard project setup to be for angular cli?
Will there be a cli tabs/menu starter?

**Output:**
This:
https://github.com/ionic-team/starters/tree/angular-testing/angular/base/src/app

vs. This:
https://github.com/ionic-team/ionic-conference-app/tree/core-update/src/app

**Comment by dwieeb** [comment]
The project setup is the same between the conference app and our starters. Look at a project created with `ionic start`, not the contents of that folder in the starters repo.

We are working on a tabs and sidemenu starter right now.
