### ISSUE TITLE
ionic serve prints "try again later"

### ISSUE THREAD

**Issue by sarathkcm** [ionic-team/ionic-cli#3086]
**Description:**

A freshly generated app using tabs starter template fais to run. 
It gives the error: "Failed to load index.html"

**Steps to Reproduce:**

```
npm i ionic -g

npm i cordova -g

ionic start app tabs

cd app

ionic serve
```

**Output:**

**My `ionic info`:**

```
cli packages: (C:\Users\SarathKCM\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.3
    npm  : 5.8.0
    OS   : Windows 10

Misc:

    backend : pro
```

**Other Information:**

**Output from console:**

 ionic serve
Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser -
Ctrl+C to cancel
[16:06:42]  watch started ...
[16:06:42]  build dev started ...
[16:06:42]  clean started ...
[16:06:42]  clean finished in 3 ms
[16:06:42]  copy started ...
[16:06:42]  deeplinks started ...
[16:06:42]  copy finished in 10 ms
[16:06:42]  deeplinks finished in 10 ms
[16:06:42]  transpile started ...
[16:06:46]  transpile finished in 3.90 s
[16:06:46]  preprocess started ...
[16:06:46]  preprocess finished in less than 1 ms
[16:06:46]  webpack started ...
[16:06:53]  webpack finished in 6.79 s
[16:06:53]  sass started ...
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[16:06:54]  sass finished in 1.01 s
[16:06:54]  postprocess started ...
[16:06:54]  dev server running: http://localhost:8100/

[OK] Development server running!
     Local: http://localhost:8100
     External: http://192.168.43.190:8100
     DevApp: app@8100 on SARATHKCM

[16:06:55]  Failed to load index.html
[16:06:55]  watch ready in 12.65 s

**Comment by sarathkcm** [comment]
Same issue with the blank app as well.

**Comment by dwieeb** [comment]
Odd.. I'm not seeing this. What does the app look like in the browser? Is it broken?

**Comment by sarathkcm** [comment]
it says "try again later"

![image](https://user-images.githubusercontent.com/14143311/38843632-91cfa84e-420d-11e8-9e7c-45221f4cb238.png)

**Comment by sarathkcm** [comment]
To check if it is any environment-related issue, I tried the same steps using WSL-Ubuntu, and got the same error- and the browser says "try again later".

**ionic info**
cli packages: (/home/sarathkcm/.nvm/versions/node/v8.11.1/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.1
    npm  : 5.6.0
    OS   : Linux 4.4

Misc:

    backend : pro

**Comment by dwieeb** [comment]
Wow, that's weird. Can you verify that `www/index.html` file exists? If it does, can you tell me if the `IONIC_HTML_TO_SERVE` environment variable is set?

**Comment by sarathkcm** [comment]
> Wow, that's weird. Can you verify that www/index.html file exists?
It does not exist. Shouldn't this be generated by ionic serve command?

**Comment by sarathkcm** [comment]
> If it does, can you tell me if the IONIC_HTML_TO_SERVE environment variable is set?

Please let me know if you still need this, I am unaware of how to get this value. `node -p "process.env.IONIC_HTML_TO_SERVE"` gives undefined.

**Comment by dwieeb** [comment]
> It does not exist. Shouldn't this be generated by ionic serve command?

Only if `src/index.html` exists. Does it?

**Comment by sarathkcm** [comment]
`src/index.html` exists..

**Comment by sarathkcm** [comment]
[app.zip](https://github.com/ionic-team/ionic-cli/files/1925315/app.zip)

Here's the generated app folder minus the node_modules and .git folders, if it helps.

**Comment by GQBrendel** [comment]
Hey @sarathkcm were you able to solve it? I have the exactly same issue.

**Comment by sarathkcm** [comment]
@GQBrendel Sadly no. Spend a lot of time trying to resolve it, got demotivated and didn't pursue that project further.

**Comment by dwieeb** [comment]
@sarathkcm Sorry, I must've missed the notification for this issue. I downloaded your zip file but it runs for me. 

<img width="356" alt="image" src="https://user-images.githubusercontent.com/236501/42174214-1ed97fb6-7de7-11e8-907d-57e91ef93f52.png">

The error you're getting is coming from these lines of code: https://github.com/ionic-team/ionic-app-scripts/blob/master/src/dev-server/http-server.ts#L81-L85 (in the `@ionic/app-scripts` package). I noticed the `err` is being ignored, but you could add this line of code to print it: `console.error(err);` (the file would be `./node_modules/@ionic/app-scripts/dist/dev-server/http-server.js`)

Our tooling for Ionic v3 projects is falling behind because we've been focused so much on v4, which uses Angular 6 and the Angular CLI. If you're curious what's going on with that, please see https://github.com/ionic-team/ionic-cli/issues/3019

**Comment by sarathkcm** [comment]
@dwieeb Thank you for responding. Most strange thing happend when I tried your instructions to check the error. 'Ionic serve' woked without any issues for the same project folder and setup I had left in my hobbies folder 2 months ago!!!. It must have been some system settings or some other processes that caused the issue at the time. 

@GQBrendel  can probably try and see what error is shown.

**Comment by sa171** [comment]
I'm getting same error

**Comment by bradranks** [comment]
I get the same error with this repo:

https://bitbucket.org/apollorocks/pure-javascript/src/master/

Is this a version issue?

**Comment by eexe1** [comment]
In my case, I fixed it with sudo command

**Comment by Ultan-Kearns** [comment]
I tried "ionic cordova prepare" and it worked for me, I think it may just be missing dependencies.

**Comment by Ultan-Kearns** [comment]
"npm update" had the same error there and updating the packages worked for me.

**Comment by fagianijunior** [comment]
> "npm update" had the same error there and updating the packages worked for me.

This fixes for me.

**Comment by justinjoeph** [comment]
"npm update" had the same error there and updating the packages worked for me.

**Comment by serggio7** [comment]
I used sudo and fixed for me :)

**Comment by anchanadarsh** [comment]
npm update worked for me

**Comment by silviasecco** [comment]
+1

**Comment by kyubjn** [comment]
npm update this fix for me

**Comment by dwieeb** [comment]
Sounds like `npm update` is the fix. Perhaps the `node_modules` needs a refresh.

**Comment by nathaliaklan1** [comment]
npm update worked

**Comment by naveen-bhardwaj** [comment]
great, thanks @dwieeb This worked for me as well.
