### ISSUE TITLE
Plugin folder and config.xml are missing every time i create new project 

### ISSUE THREAD

**Issue by alkahtani** [ionic-team/ionic-cli#3088]
**Description:**

I  use **ionic start myapp blank --type=ionic1** CLI command to create ionic 1 project , the project created but config.xml and plugins folder are missing >

**Steps to Reproduce:**
`ionic start myapp blank --type=ionic1 `

**Output:**

> 84404 silly gentlyRm D:\Stylist\todo\node_modules\.staging\yargs-4e522506\node_modules is being purged
> 84405 verbose gentlyRm don't care about contents; nuking D:\Stylist\todo\node_modules\.staging\yargs-4e522506\node_modules
> 84406 silly gentlyRm D:\Stylist\todo\node_modules\.staging\lost-f6ee1a98\node_modules is being purged
> 84407 verbose gentlyRm don't care about contents; nuking D:\Stylist\todo\node_modules\.staging\lost-f6ee1a98\node_modules
> 84408 silly gentlyRm D:\Stylist\todo\node_modules\.staging\jshint-33bff94b\node_modules is being purged
> 84409 verbose gentlyRm don't care about contents; nuking D:\Stylist\todo\node_modules\.staging\jshint-33bff94b\node_modules
> 84410 silly gentlyRm D:\Stylist\todo\node_modules\.staging\browser-sync-ui-8a5bdeb9\node_modules is being purged
> 84411 verbose gentlyRm don't care about contents; nuking D:\Stylist\todo\node_modules\.staging\browser-sync-ui-8a5bdeb9\node_modules
> 84412 silly gentlyRm D:\Stylist\todo\node_modules\.staging\browser-sync-9b7b7949\node_modules is being purged
> 84413 verbose gentlyRm don't care about contents; nuking D:\Stylist\todo\node_modules\.staging\browser-sync-9b7b7949\node_modules
> 84414 silly gentlyRm D:\Stylist\todo\node_modules\.staging\node-sass-08c007bb\node_modules is being purged
> 84415 verbose gentlyRm don't care about contents; nuking D:\Stylist\todo\node_modules\.staging\node-sass-08c007bb\node_modules
> 84416 verbose unlock done using C:\Users\alkahtani\AppData\Roaming\npm-cache\_locks\staging-ebbdcf00d77e1f70.lock for D:\Stylist\todo\node_modules\.staging
> 84417 silly install printInstalled
> 84418 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
> 84419 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 84420 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> 84420 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> 84420 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
> 84420 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
> 84421 warn todo@0.0.1 No repository field.
> 84422 warn todo@0.0.1 No license field.
> 84423 verbose stack Error: EIO: i/o error, fsync
> 84424 verbose cwd D:\Stylist\todo
> 84425 verbose Windows_NT 6.1.7601
> 84426 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alkahtani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "glup"
> 84427 verbose node v8.11.1
> 84428 verbose npm  v4.6.1
> 84429 error code EIO
> 84430 error errno -4070
> 84431 error syscall fsync
> 84432 error EIO: i/o error, fsync
> 84433 verbose exit [ -4070, true ]
> 
> 

**My `ionic info`:**

   

```
 @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.11.1
    npm  : 4.6.1
    OS   : Windows 7

Misc:

    backend : pro

```

**Other Information:**

> 
I have been at the last step to finalize my app , my PC crashed , i re-install fresh windows , i am 
[2018-04-16T21_15_14_013Z-debug.log](https://github.com/ionic-team/ionic-cli/files/1917474/2018-04-16T21_15_14_013Z-debug.log)
struggling to get this project working again , i am trying to create new project and past my WWW folder and re-install my plugins manually " which is very hard " , if you can direct me the best approach how to get my app that i spent a lot of time to develop work again .

**Comment by dwieeb** [comment]
@alkahtani `config.xml` is part of the Cordova integration, which is installed during `ionic start` with the `--cordova` flag or by answering yes to this prompt:

> Would you like to integrate your new app with Cordova to target native iOS and Android? y/N

**Comment by dwieeb** [comment]
You can also add the integration to existing apps with the following command:

```
ionic integrations enable cordova
```

Or by running any of the `ionic cordova ...` commands. See `ionic cordova --help`.

**Comment by alkahtani** [comment]
Thank you @dwieeb  i got it , but the plugins folder still not showing

**Comment by alkahtani** [comment]
@dwieeb  the above error showing directly after i answer Yes , it seems the project not successfully created . do i need to downgrade , what is the best version to use with ionic v1

**Comment by dwieeb** [comment]
I would guess your issue is around here:
> 84426 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Users\alkahtani\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "i" "-D" "glup"

looks like it's trying to install "glup", not "gulp" 

The plugins folder doesn't show because you have to build your project first: `ionic cordova build`

But let's reserve this repo for features/suggestions/bugs for the Ionic CLI. You can see our [Support Page](https://ionicframework.com/support) for help from our community.

Thanks!

**Comment by ssj7** [comment]
Ionic missing config.xml or resources directory.
If this is a project you'd like to integrate with Ionic, create an ionic.config.json file.

The solution is:
 `ionic start MyApp blank --cordova`
[https://github.com/ionic-team/ionic-cli/issues/3088#issuecomment-381765890](url)
