### ISSUE TITLE
Testing Ionic 4 - Remove padding and set background color but there is still white space

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#3090]
**Description:**
Remove padding and set background color but there is still white space

**Steps to Reproduce:**

https://github.com/peterennis/aeion4/blob/master/src/app/pages/home/home.page.html

**Output:**
![capture280](https://user-images.githubusercontent.com/140737/38913606-77d43bfc-4290-11e8-9fc9-9da354c733ad.png)

**My `ionic info`:**
```
C:\ae\adaept.com\aeion4>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.4
   ionic (Ionic CLI) : 4.0.0-rc.4

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.6
   @angular-devkit/schematics : 0.5.6
   @angular/cli               : 6.0.0-rc.5
   @ionic/schematics-angular  : 1.0.0-rc.4
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.2

System:

   NodeJS : v8.11.1
   npm    : 5.8.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set


C:\ae\adaept.com\aeion4>
```

**Other Information:**
I want to set the background color of the whole page even if there
is padding or no padding.

**Comment by dwieeb** [comment]
@peterennis I'm guessing this is a framework issue, not a CLI issue?
