### ISSUE TITLE
Testing Ionic 4 - Default@2x~universal~anyany.png - IOS resource undocumented?

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#3093]
![capture282](https://user-images.githubusercontent.com/140737/39030853-81339cc6-4419-11e8-8a12-d97257be3eb4.png)

**Description:**
New ios resource file.
It does not exist in previous version.
Resources copied from previous version.

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**
```
C:\ae\adaept.com\aetabs>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.7
   @angular-devkit/schematics : 0.5.7
   @angular/cli               : 6.0.0-rc.5
   @ionic/schematics-angular  : 1.0.0-rc.5
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.2

System:

   NodeJS : v8.11.1
   npm    : 5.8.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set


C:\ae\adaept.com\aetabs>
```

**Other Information:**

**Comment by dwieeb** [comment]
@peterennis I'm not sure I'm following what the issue is?

**Comment by peterennis** [comment]
This file is new. Does it get autogenerated? It is the same size as splash but looks different.
I did not create resources but copied them from a previous system and could see
the change. Is it documented somewhere? Where does it get used? etc.

**Comment by dwieeb** [comment]
`ionic cordova resources --help` has a link to the reference documentation for splash screen: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/
