### ISSUE TITLE
Testing Ionic 4 - Tabs project - 'ion-navbar' is not a known element

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#3094]
**Description:**
'ion-navbar' is not a known element

**Steps to Reproduce:**
Tabs project. Add color="primary" to ion-navbar

**Output:**

![capture283](https://user-images.githubusercontent.com/140737/39031560-d5a6ec82-441d-11e8-91a3-340e97e1e572.png)

**My `ionic info`:**
```
C:\ae\adaept.com\aetabs>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.7
   @angular-devkit/schematics : 0.5.7
   @angular/cli               : 6.0.0-rc.5
   @ionic/schematics-angular  : 1.0.0-rc.5
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.2

System:

   NodeJS : v8.11.1
   npm    : 5.8.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set


C:\ae\adaept.com\aetabs>
```

**Other Information:**

**Comment by dwieeb** [comment]
@peterennis Yep, I made an internal note to add that to our breaking changes document: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md

Thanks for bringing it to our attention.
