### ISSUE TITLE
Testing Ionic 4 - Lab showing black flashing shadow on scroll

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#3095]
**Description:**

**Steps to Reproduce:**
Run lab and scroll.

**Output:**
![capture285](https://user-images.githubusercontent.com/140737/39032189-466bc368-4421-11e8-943c-7cb588a9bca1.png)

**Comment by dwieeb** [comment]
@peterennis I'm not seeing this in Chrome. Why is that white bar there? 

![image](https://user-images.githubusercontent.com/236501/39070305-859b0544-44a8-11e8-8b4e-36e45390a3bb.png)

**Comment by peterennis** [comment]
Screen size related? I will update details when I get back to the laptop.

**Comment by peterennis** [comment]
![capture286](https://user-images.githubusercontent.com/140737/39080188-94bf382a-44de-11e8-94b5-1e98f709396e.png)

**Comment by peterennis** [comment]
Fixed in newer version.
