### ISSUE TITLE
initialize the ionic project ETIMEDOUT

### ISSUE THREAD

**Issue by zwq8299174** [ionic-team/ionic-cli#3098]
**Description:**

When I initialize the ionic project. I use the command `ionic start myApp tabs`,but there are errors like this 

> Error: read ETIMEDOUT
    at _errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:606:25)

I try again many times, but still.

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

ionic -v 3.20.0

npm -v 6.0.0

macOs 10.13.4

**Comment by dwieeb** [comment]
@zwq8299174 Are you behind a network proxy?

**Comment by zwq8299174** [comment]
@dwieeb  Yes, I'm using Shadowscoks. this my rules

> ||ionicframework.com^
||github.io^
||vuejs.org^
||github.com^
||ionic.io^
||tympanus.net^
||npmjs.com^
||jsfiddle.net^
||steampowered.com^
||huangsw.com^
||jsfiddle.net^
||jshell.net^
||codepen.io^

**Comment by zwq8299174** [comment]
@dwieeb  I closed the Shadowscoks but the error was the same.

**Comment by dwieeb** [comment]
@zwq8299174 The Ionic CLI will need to be configured to use your proxy: https://ionicframework.com/docs/cli/configuring.html#using-a-proxy

Additionally, is there any configuration that needs to happen there on the proxy end for `cloudfront.net`?
