### ISSUE TITLE
Testing Ionic 4 - Tabs project sample 

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#3104]
**Description:**
Refresh page causes not found error

**Steps to Reproduce:**
![capture306](https://user-images.githubusercontent.com/140737/39228168-7a406024-4811-11e8-8875-24170efed5d5.png)
![capture307](https://user-images.githubusercontent.com/140737/39228170-7e1d6d04-4811-11e8-85db-1b4c69e5ce5c.png)

**Output:**

**My `ionic info`:**
```
C:\ae\adaept.com\aetabs>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.7
   @angular-devkit/schematics : 0.5.7
   @angular/cli               : 6.0.0-rc.5
   @ionic/schematics-angular  : 1.0.0-rc.5
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.3

System:

   NodeJS : v8.11.1
   npm    : 5.8.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set


C:\ae\adaept.com\aetabs>
```

**Other Information:**
https://aetabs.adaept.com
https://github.com/peterennis/aetabs

**Comment by rdlabo** [comment]
@peterennis You should set firebase.json. Angular require rewrite rule in server.

ex)
```
{
  "hosting": {
    "public": "dist",
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

**Comment by peterennis** [comment]
@rdlabo 
Fixed here: https://github.com/peterennis/aetabs/commit/a802dd3427e87865b7d19fe28c4260a3f1352782
Thanks!
