### ISSUE TITLE
Add NgModule for Pages

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3114]
Newly generated pages should have an NgModule and routing configured.

Example: https://github.com/ionic-team/starters/tree/master/angular/official/blank/src/app/pages/home

**Comment by DavidDudson** [comment]
I'm hitting this also.

**Comment by dwieeb** [comment]
Fixed in https://github.com/ionic-team/ionic-cli/commit/65dbcb6e96e7d4ffecd92b3616d40525e20df290
