### ISSUE TITLE
Help Wanted: Test Capacitor

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3129]
This is a mostly placeholder issue. The integration with Capacitor is still very much a work-in-progress.

If you want to help test anyway, make sure you have the latest CLI 4:

```
npm i -g ionic
```

Enable the Capacitor commands:

```
ionic config set -g features.capacitor-commands true
```

Add the `ios` or `android` platform:

```
ionic capacitor add ios
```

See more in help:

```
ionic cap --help
```

Found an issue? Please create a new issue in this repo (it may be moved). ❤️

**Comment by peterennis** [comment]
Create tabs starter and add capacitor.
"Not running Mac OS X, can't add ios platform"

![capture314](https://user-images.githubusercontent.com/140737/39964402-d3fab706-5638-11e8-88e9-0896b80e0c86.png)

```
C:\ae\adaept.com\aecap>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @capacitor/core            : 1.0.0-alpha.37
   @ionic/schematics-angular  : 1.0.0-rc.6
   capacitor (Capacitor CLI)  : 1.0.0-alpha.37
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.6

System:

   NodeJS : v8.11.1
   npm    : 6.0.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set


C:\ae\adaept.com\aecap>
```

**Comment by dwieeb** [comment]
@peterennis Let's track that issue here 👉 https://github.com/ionic-team/capacitor/issues/224

**Comment by dwieeb** [comment]
Capacitor is enabled for everyone as "experimental". Forgot to update this issue.
