### ISSUE TITLE
Provide live-reload functionality

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3130]
Like `ionic cordova run ios -l`, but for Capacitor!

📝 Set `appUrl` in `capacitor.config.json` for live-reload: https://github.com/ionic-team/capacitor/issues/366 & https://github.com/ionic-team/capacitor/commit/9b89f096e8eca1f7ef761c4f1cc3be2e7c16ab9b

**Comment by dwieeb** [comment]
Perhaps the "enhancement" label will help. 

It is not possible yet. Subscribe to this issue for updates.

**Comment by HoverBaum** [comment]
In the meantime here is the description we wrote for our project on how to use live-reload:

1. Create a Wifi hotspot from your laptop (iPhone and Laptop need to be on the same network)
2. Run `ionic serve` 
3. Find your IP (ifconfig on Mac)
4. Check that you can access the website from the phone in Safari
5. Add your Laptops IP as server in the `capacitor.config.json`
6. Run `cap sync ios` and tehn `cap open ios`
7. Start the project in XCode
8. Enjoy 😊

Server config for capacitor:
```javascript
"server": {
  "url": "http://[Your IP here]:8100"
}
```

Hopefully it helps someone while we are waiting for awesome cli support.

**Comment by dwieeb** [comment]
Thanks @HoverBaum! Those are the exact steps we hope to automate. I was working on this yesterday but ran into some issues with Capacitor misidentifying ios/android as web due to the livereload server. Hoping to resolve this shortly!

**Comment by darklinki** [comment]
Does it work now, the documentation still says no but github says closed :)

**Comment by dwieeb** [comment]
@darklinki Yes, it should work. Can you link to the documentation you're seeing?

**Comment by dwieeb** [comment]
Oops! Thanks @linus1412!!
