### ISSUE TITLE
Testing Ionic 4 - Stuck in a loop generating ios resources

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#3165]
**Description:**
Copied my existing resource files into the project
and it gets stuck in a generating loop for 20 hours.
That was how long till I looked at it again.

**Steps to Reproduce:**
Copy resources to new project.
Run command to add cordova.

**Output:**
![capture309](https://user-images.githubusercontent.com/140737/39953315-e80cf35c-555d-11e8-8268-b70cff1bf7b3.png)

**My `ionic info`:**
```
C:\ae\adaept.com\aemenu>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.0
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.4

System:

   NodeJS : v8.11.1
   npm    : 6.0.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set


C:\ae\adaept.com\aemenu>
```

**Other Information:**

**Comment by peterennis** [comment]
Recreate project from scratch.
Use only my icon and splash.
Stuck in a loop at 31 (vs. 27 above).

![capture310](https://user-images.githubusercontent.com/140737/39953549-2088538e-5563-11e8-9d5a-e03a876fee51.png)

**Comment by peterennis** [comment]
After some investigation I found that the wrong size splash is a killer.
![capture311](https://user-images.githubusercontent.com/140737/39953966-b0d1952a-556a-11e8-8040-f59733d3e7ad.png)

Recreate splash for the correct size and it works.
![capture312](https://user-images.githubusercontent.com/140737/39953969-c2a7a730-556a-11e8-85a3-0c4bfeb5a90f.png)

**Comment by himalayaahuja** [comment]
Upgraded to ionic 4 cli , stuck at same problem , was working fine before..with v 3.x.x..

**Comment by razmans** [comment]
Yeap same here

**Comment by cardeol** [comment]
is it possible to downgrade ?

**Comment by dwieeb** [comment]
This issue is a duplicate of https://github.com/ionic-team/ionic-cli/issues/3398 and is fixed in the latest CLI (4.0.6).

**Comment by iodev** [comment]
very much still prevalent in 4.1.1

**Comment by dwieeb** [comment]
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3540

Let's discuss there ^
