### ISSUE TITLE
Ionic 4 Application error (Connection to server was unsuccessfull error)

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ionic-team/ionic-cli#3173]
**Description:**

Ionic 4 app works in android/ios emulator but does not work on android/ios device with command `ionic cordova run android --prod`
It shows a white screen for long time and then says: Application Error (Connection to server was unsuccessfull (file:///android_asset/www/index.html)

**Steps to Reproduce:**

1. Clone ionic conference app (core update branch)
2. Try to run on device with command `ionic cordova run android --prod`

**Output:**

**My `ionic info`:**

```
cli packages: (C:\Users\apatwari\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

global packages:

   cordova (Cordova CLI) : 6.5.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.3
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : android 6.4.0
   Ionic Framework            : @ionic/angular 4.0.0-alpha.6

System:

   NodeJS : v9.11.1
   npm    : 5.6.0
   OS     : Windows 7
```

**Other Information:**

![image](https://user-images.githubusercontent.com/5632217/40164368-fe89d4d4-59c1-11e8-8983-c3f651fd6de6.png)

**Comment by dwieeb** [comment]
We're waiting on some changes to the webview plugin. Android device/emulator support isn't quite ready yet. See https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/104

**Comment by ASHFAQPATWARI** [comment]
But we have seen videos and screenshots from @mhartington in his tweets about ionic 4 performance which were on real devices. Thanks for the update though.

**Comment by ASHFAQPATWARI** [comment]
@mhartington I have tried to run the sidemenu starter/ ionic 4 conference app in IOS devices also and I am getting the same issue there also. So for me, even IOS is not working.

**Comment by dwieeb** [comment]
Let's track this here: https://github.com/ionic-team/ionic-cli/issues/3279
