### ISSUE TITLE
Failed to load resource "ionic/ionic.dtdxjdv4.js:1"

### ISSUE THREAD

**Issue by divanvb** [ionic-team/ionic-cli#3174]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behaviour:**

Created a new Ionic V4 Sidemenu starter and upgrade to alpha.4 as stated in the app.module if released then tried running the app and received this error 
```ionic/ionic.dtdxjdv4.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)```

**Expected behaviour:**

It should run without issues as it is a clean project

**Steps to reproduce:**

1. ionic start --type=angular myApp side menu
2. Upgrade ionic to alpha.4
3. Uncomment list route in app.module.ts
4. ionic serve

**Related code:**

```
ionic/ionic.dtdxjdv4.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
local packages:

   @angular-devkit/core       : 0.5.11
   @angular-devkit/schematics : 0.5.11
   @angular/cli               : 6.0.0-rc.8
   @ionic/schematics-angular  : 1.0.0-rc.5
   Ionic Framework            : @ionic/angular 4.0.0-alpha.4

System:

   NodeJS : v9.11.1
   npm    : 5.6.0
   OS     : Windows 10
```

**Comment by dwieeb** [comment]
@divanvb This is likely just a little hiccup with something from an old version of stencil. If this happens again with the latest stuff, let me know.
