### ISSUE TITLE
Sidemenu project not being generated

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-cli#3184]
**Description:**
Using ionic start myApp sidemenu will incorrectly use the tabs template. If I do NOT pass in a template type and use the prompt and select sidemenu, the template is correctly chosen

**Steps to Reproduce:**
ionic start myApp sidemenu

**Output:**
No errors reported

**My `ionic info`:**
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v8.11.1
   npm    : 6.0.1
   OS     : OS X El Capitan

**Other Information:**

**Comment by dwieeb** [comment]
Not seeing this:

```
❯ ionic start myApp sidemenu

What type of project would you like to create?

We recommend angular. To learn more about project types, see the CLI documentation[1]. To bypass this prompt next time,
supply the --type option.

[1]: https://ionicframework.com/docs/cli/starters.html

? Project type: angular
✔ Preparing directory ./myApp - done!
✔ Downloading and extracting sidemenu starter - done!
...
```

**Comment by chrisgriffith** [comment]
The browser was caching the last Ionic project. Also able to switch between the side menu items.
