### ISSUE TITLE
cordova-plugin-inappbrowser@^1.7.1 Caught exception:  undefined 

### ISSUE THREAD

**Issue by sivasankarp** [ionic-team/ionic-cli#3186]
**Description:**

cordova-plugin-inappbrowser@^1.7.1
Caught exception:
 undefined 

**Steps to Reproduce:**

When we restore  - ionic state restore

**Output:**

Attempting to restore your Ionic application from package.json

Restoring Platforms

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-inappbrowser@^1.7.1
Caught exception:
 undefined 

**My `ionic info`:**

```
Cordova CLI: 7.0.0 
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.2 
ios-sim version: 6.1.2 
OS: macOS Sierra
Node Version: v6.11.2
Xcode version: Xcode 9.2 Build version 9C40b
```

**Other Information:**

**Comment by dwieeb** [comment]
@sivasankarp Please update to the latest CLI. In CLI v3, `ionic state` has been removed. Please see the notes about it in [the changelog](https://github.com/ionic-team/ionic-cli/blob/3.x/CHANGELOG.md#300-2017-05-09). Cordova can now be used to manage plugins & platforms.
