### ISSUE TITLE
Got the below error running ionic in  CLI 

### ISSUE THREAD

**Issue by asrar7** [ionic-team/ionic-cli#3190]
**When i closed my project and rerun it got this error in the CLI . Please help me.**
**Thanks**

PS C:\Users\user\myApp> ionic serve -l
ionic : The term 'ionic' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ionic serve -l
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (ionic:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by zhangchri** [comment]
Ask for an answer， please

**Comment by dwieeb** [comment]
This looks like a standard error when PowerShell isn't aware of the `ionic` program. Perhaps reinstall the Ionic CLI, investigate pathing issues, try reinstalling Node if that doesn't work.

**Comment by Aniket242424** [comment]
please update us on it
