### ISSUE TITLE
UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch platform cordova-android@~7.0.0

### ISSUE THREAD

**Issue by yl847866341** [ionic-team/ionic-cli#3191]
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jack\AppData\Roaming\npm-cache\_logs\2018-05-24T06_41_22_044Z-debug.log
    at C:\Users\Jack\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\cordova\platform\addHelper.js:312:25
    at _rejected (C:\Users\Jack\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:797:24)
    at C:\Users\Jack\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:823:30
    at Promise.when (C:\Users\Jack\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.5.1@q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\Jack\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.5.1@q\q.js:808:41)
    at C:\Users\Jack\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.5.1@q\q.js:624:44
    at runSingle (C:\Users\Jack\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.5.1@q\q.js:137:13)
    at flush (C:\Users\Jack\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.5.1@q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:9964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What's the root cause about it? Net error? Version? T_T

**Comment by dwieeb** [comment]
@yl847866341 This issue is posted A LOT. Please go through the existing issues and attempt to troubleshoot. 

https://github.com/ionic-team/ionic-cli/issues/2412
https://github.com/ionic-team/ionic-cli/issues/2772

**Comment by SimoneMSR** [comment]
In my case, none of the solution above worked. My problem was the order of commands in which I was  using for building the project. This worked for me:
rm -R node_modules
cordova platform remove android
cordova platform add android
yarn

**Comment by harshkhandelwalcs** [comment]
Getting error
Using cordova-fetch for cordova-android@6.4.0

Error: Failed to fetch platform cordova-android@6.4.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code ENOENT

[ERROR] Exception:

while running ionic cordova platform add android
