### ISSUE TITLE
Ionic 4: Build for ios emulator missing files

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-cli#3218]
**Description:**
Running v4.0.0=alpha 7, when I do ionic cordova emulate ios, the build process appears to occur correctly. The emulator launches, the app is started, splash screen appear, then the white screen of doom.

Connecting Safari and reloading the app, the console reports missing files.

Ionic serve is working fine.

**Steps to Reproduce:**
ionic cordova emulate ios

The ios platform has been removed and readded.

**Output:**

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (runtime.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (cordova.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (polyfills.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (styles.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (vendor.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (main.js, line 0)

**My `ionic info`:**

```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : android 7.0.0 ios 4.5.4
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.1
   ios-sim           : 6.0.0
   NodeJS            : v8.11.1
   npm               : 6.0.1
   OS                : OS X El Capitan
   Xcode             : Xcode 8.0 Build version 8A218a

Environment Variables:

   ANDROID_HOME : /Users/chrisgriffith/Documents/android-sdk-macosx
```

**Other Information:**

**Comment by jmannau** [comment]
I can confirm the same thing happens for debug builds to iOS devices. See the screenshot
<img width="726" alt="screen shot 2018-05-29 at 2 14 33 pm" src="https://user-images.githubusercontent.com/175909/40637796-a86d7eb0-634a-11e8-85e7-a2c16c0f3a0d.png">


My Environment is 
```
cli packages: (/Users/james/Documents/Dev/whereabouts-mobile/app/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   Android SDK Tools : 25.2.3
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.11.2
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.3.1 Build version 9E501

Environment Variables:

   ANDROID_HOME : /usr/local/opt/android-sdk
```

**Comment by jmannau** [comment]
This is caused by an issue cordova-plugin-ionic-webview has loading resources for ionic v4 projects. This pull request for cordova-plugin-ionic-webview fixes the issue - https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/101

**Comment by dwieeb** [comment]
Let's track this here: https://github.com/ionic-team/ionic-cli/issues/3279

(thanks for clearing that up @jmannau!)

**Comment by tdorlus** [comment]
@parthnayak7448 I was having the same issue and scratching my head for 2 days. I ran `ionic info` and found out that the webview plugin never got updated. I had to remove it and add it again. 
Try `cordova plugin rm cordova-plugin-ionic-webview`
then `cordova plugin add cordova-plugin-ionic-webview@latest`. 
Run `cordova plugin ls` and make sure the webview is `2.X`

**Comment by OyebisiJemil** [comment]
Thanks this works for me

**Comment by harryt2** [comment]
jmannau's solution worked for me, been fighting this all day. Thanks!

**Comment by rL071** [comment]
Thank you very much !
