### ISSUE TITLE
[Ionic 4] How to build for prod?

### ISSUE THREAD

**Issue by RZR666** [ionic-team/ionic-cli#3258]
**Description:**

running **ionic build --prod** and the **www folder** builds with a lot of **.js and .js.map** files.  I don't know if that's correct, it looks different from v3.

So loading the index.html fails to show the project, the below errors appear in the console...

Failed to load resource: net::ERR_FILE_NOT_FOUND
polyfills.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
styles.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vendor.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/assets/icon/favicon.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND

**My `ionic info`:**

cli packages: (/usr/local/lib/node_modules)

   ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   angular-devkit/core       : 0.6.0
   angular-devkit/schematics : 0.6.0
   angular/cli               : 6.0.1
   ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v10.2.1
   npm    : 6.1.0
   OS     : macOS High Sierra

**Comment by dwieeb** [comment]
@RZR666 You won't be able to simply open `index.html` because Ionic Angular 4 uses HTML5 routing and you need a properly configured server.

Try this instead: `npx pushserve www`

**Comment by dwieeb** [comment]
📝 We should include this as a FAQ in the docs with the pushserve example

**Comment by RZR666** [comment]
nevermind, works on the root of my server.
