### ISSUE TITLE
ionic start <appname> command - Hangs

### ISSUE THREAD

**Issue by aero1508** [ionic-team/ionic-cli#3284]
**Version:** Ionic 3
**Short description of the problem:** I'm trying to create a new ionic project and unfortunately the ionic start command hangs as following.

`c:\ionic> ionic start mysampleapp <blank | sidemenu | blank>`

After running the `ionic start mysampleapp <any template option>`, This should create a new ionic project.

**Steps to reproduce:**   run the command `ionic start mysampleapp <blank | sidemenu | blank>`

**What I see in the console**

```
c:\ionic>ionic start mysampleapp blank
√ Creating directory .\aeroapp1 - done!
√ Downloading and extracting blank starter - done!

? Would you like to integrate your new app with Cordova to target native iOS and Android? Yes
>>>>>>>>>>>IN THIS STEP, IONIC HANGS
```
I get the same result if i write No in the integration question.

**Which version are you using?**:
```
cli packages: (C:\Users\XXXXX\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:
    Node : v10.3.0
    npm  : 6.1.0
    OS   : Windows 10

Misc:
    backend : pro

```
**Other information:** I tried using the parameter` --no-git` but the result is the same.

Thanks for your feedback, good day!

**Comment by dwieeb** [comment]
Please post the full output of `ionic start mysampleapp blank --verbose`

**Comment by dwieeb** [comment]
Also, Node 10 is super flaky. Try with Node 8 LTS.

**Comment by aero1508** [comment]
Hi dwieeb

The console screen with` ionic start mysampleapp blank --verbose` shows:


```
C:\ionic>ionic start mysampleapp blank --verbose
[DEBUG] Reason for not using local CLI: BASE_DIRECTORY_NOT_FOUND
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'C:\\ionic', local: false, binPath:
        'C:\\Users\\Izaid\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic',
        libPath:
        'C:\\Users\\Izaid\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js'
        }                                                                          [DEBUG] New daemon pid: 6324
√ Creating directory .\mysampleapp - done!
√ Downloading and extracting blank starter - done!

? Would you like to integrate your new app with Cordova to target native iOS and A
ndroid? Yes
```
.. and the result is the same....

Let me try downgrade node from 10 to 8...

**Comment by aero1508** [comment]
Hi again dwieeb

Of course, Node 10 have trobles in ionic! Thanks a lot for the support! Have a great day!
