### ISSUE TITLE
v4 - Sass change reloads with wrong platform (android/ios)

### ISSUE THREAD

**Issue by chrislow** [ionic-team/ionic-cli#3296]
**Description:**

When running `ionic serve --platform android` and changing sass files, the watcher reloads with the ios platform.

**Steps to Reproduce:**

1. `ionic serve --platform android`
2. Change sass files
3. Let the watcher reload
4. Now ios theme is showing

**My `ionic info`:**

```
$ ionic info
cli packages: (C:\Users\Christian\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : not installed

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.1
   npm               : 6.1.0
   OS                : Windows 10

Environment Variables:

   ANDROID_HOME : C:\android-sdk
```

**Comment by dwieeb** [comment]
Thanks @chrislow, I think I know why this is. Ionic may need to set session storage for configuration supplied by query parameters.

**Comment by dwieeb** [comment]
@chrislow I'm guessing this happens with any kind of livereload event, not just changing sass files. Right?

**Comment by chrislow** [comment]
@dwieeb tested it right now, yes -  you are right, it happens on any livereload event!

**Comment by dwieeb** [comment]
Apologies this took so long! Will be fixed in the next release.
