### ISSUE TITLE
(SOLVED) Error: Cannot find module 'C:\[...]\node_modules\cordova\bin\cordova'

### ISSUE THREAD

**Issue by kevinHernandez05** [ionic-team/ionic-cli#3301]
**Description:**
When I want to deploy my app on my Android with "Ionic cordova run(or build) android, Powershell Says 
That cordova module cannot be found.

**Steps to Reproduce:**

run "ionic cordova run android" 

**Output:**

PS C:\Users\smsma\Desktop\Prog. Stuff\ED2 Proyectos\Workbefy\App\Workbefy> ionic cordova run android --verbose
[DEBUG] Reason for not using local CLI: LOCAL_CLI_NOT_FOUND
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'C:\\Users\\smsma\\Desktop\\Prog. Stuff\\ED2 Proyectos\\Workbefy\\App\\Workbefy', local: false, binPath:
        'C:\\Users\\smsma\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:
        'C:\\Users\\smsma\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Daemon found (pid: 7400)
Running app-scripts build: --platform android --target cordova
[11:37:43]  build dev started ...
[11:37:43]  clean started ...
[11:37:43]  clean finished in 34 ms
[11:37:43]  copy started ...
[11:37:44]  deeplinks started ...
[11:37:44]  deeplinks finished in 361 ms
[11:37:44]  transpile started ...
[11:37:56]  transpile finished in 11.67 s
[11:37:56]  preprocess started ...
[11:37:56]  preprocess finished in 1 ms
[11:37:56]  webpack started ...
[11:37:56]  copy finished in 13.14 s
[11:38:16]  webpack finished in 20.55 s
[11:38:16]  sass started ...
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[11:38:20]  sass finished in 3.48 s
[11:38:20]  postprocess started ...
[11:38:20]  postprocess finished in 55 ms
[11:38:20]  lint started ...
[11:38:20]  build dev finished in 36.85 s
> cordova run android
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\smsma\Desktop\Prog. Stuff\ED2 Proyectos\Workbefy\App\Workbefy\node_modules\cordova\bin\cordova'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
[ERROR] An error occurred while running cordova run android (exit code 1).

[11:38:29]  tslint: ...og. Stuff/ED2 Proyectos/Workbefy/App/Workbefy/src/pages/categorias/categorias.ts, line: 303
            'menu' is declared but its value is never read.

     L303:      let menu: any;

[11:38:29]  tslint: ...og. Stuff/ED2 Proyectos/Workbefy/App/Workbefy/src/pages/categorias/categorias.ts, line: 5
            All imports are unused.

       L5:  import { TrabajadorPage } from '../trabajador/trabajador';
       L6:  import { ResultadoBusquedaPage } from '../resultado-busqueda/resultado-busqueda';

[11:38:29]  lint finished in 9.03 s
[DEBUG] registerShutdownFunction process.exit/normal shutdown

**My `ionic info`:**

```
cli packages: (C:\Users\smsma\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.1
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro```

**Comment by dwieeb** [comment]
> cordova (Cordova CLI) : not installed

Cordova is not installed. Run `npm install -g cordova`.

**Comment by kevinHernandez05** [comment]
I've run `npm install -g cordova` a lot of times
and yep, not working at all

**Comment by dwieeb** [comment]
`Error: Cannot find module 'C:\Users\smsma\Desktop\Prog. Stuff\ED2 Proyectos\Workbefy\App\Workbefy\node_modules\cordova\bin\cordova'`

I'm guessing your node_modules are messed up. Is `cordova` listed in `package.json`?

**Comment by kevinHernandez05** [comment]
just ` 'cordova'`?

This is my `package.json`:

```
{
  "name": "Workbefy",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.9",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@ionic-native/core": "4.5.3",
    "@ionic-native/native-storage": "^4.7.0",
    "@ionic-native/splash-screen": "4.5.3",
    "@ionic-native/status-bar": "4.5.3",
    "@ionic/storage": "2.1.3",
    "cordova-android": "~7.0.0",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-facebook4": "~1.9.1",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.3.2",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.7",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-facebook4": {
        "APP_ID": "453716605085801",
        "APP_NAME": "Workbefy"
      }
    },
    "platforms": [
      "android"
    ]
  }
}
```

What do I need to add here?
and thanks for helping me!

**Comment by dwieeb** [comment]
Nothing needs to be added. I think there are residual files in node_modules from a local Cordova installation. Can you check if the following file exists: `node_modules/.bin/cordova`

**Comment by kevinHernandez05** [comment]
`node_modules/.bin/cordova` does not exist!

**Comment by dwieeb** [comment]
Can you try the following anyway? 

```
rm -rf node_modules
npm install
```

**Comment by kevinHernandez05** [comment]
Yep, I tried that, but still not working. :/
is there any way for copying that file/folder manually there?

**Comment by dwieeb** [comment]
Yeah, sometimes local Cordova projects get in a weird state. When this happens, the following often fixes it:

```
rm -rf node_modules package-lock.json
rm -rf platforms/ plugins/
npm install
cordova prepare
```

**Comment by SanjanaTailor** [comment]
project directory>rm -rf node_modules
'rm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dwieeb** [comment]
`rm` is a tool to remove files and directories on every platform except Windows.
