### ISSUE TITLE
ionic cordova run with https livereload.

### ISSUE THREAD

**Issue by Domvel** [ionic-team/ionic-cli#3304]
Is there already a option to run a platform with livereload as https-server (ssl).
Command: `ionic cordova run android -lc`
ionic cli `3.20.0`

Use case: 
Be able to use `geolocation` in developer mode with live reload and console. Otherwise I always have to run the app in `prod` mode. Without any debugging features. 
Currently you get the error message on location request in `-lc` mode. 
`Only secure origins are allowed` (see https://goo.gl/Y0ZkNV)

**Comment by dwieeb** [comment]
Ionic apps using `@ionic/app-scripts` will likely not ever have SSL support. However, with Ionic Angular 4, apps use the Angular CLI for tooling and there's built-in support, so this will be quite easy. 

Please see the issue I just made: https://github.com/ionic-team/ionic-cli/issues/3305

**Comment by luisvt** [comment]
what should be the command to run `livereload` with `ssl`?

**Comment by Domvel** [comment]
@luisvt  For example `--ssl` and optional `--ssl-key`, `--ssl-cert` like in angular. Or more simplified like `--https` and / or setup in configuration files.

**Comment by luisvt** [comment]
so something like:

```
ionic cordova run android --livereload --ssl
```

should work?

or is it still in progress and we should wait?
