### ISSUE TITLE
ionic 4: ionic g page gives a scss file, ionic g component gives a css file

### ISSUE THREAD

**Issue by seiyria** [ionic-team/ionic-cli#3312]
**Description:** After generating a fresh ionic project (following [this](https://mhartington.io/post/ionic-4-alpha-test/)), I go to use the CLI as normal. When I generate a page, it gives me a scss file, but when I generate a component it gives me a plain css file. It seems inconsistent.

**Steps to Reproduce:**
`ionic g component menu-list` was the specific command I ran.

**Output:**
```
$ ionic g component menu-list
> ng generate component components/menu-list
CREATE src/app/components/menu-list/menu-list.component.html (28 bytes)
CREATE src/app/components/menu-list/menu-list.component.spec.ts (643 bytes)
CREATE src/app/components/menu-list/menu-list.component.ts (280 bytes)
CREATE src/app/components/menu-list/menu-list.component.css (0 bytes)
UPDATE src/app/app.module.ts (884 bytes)
[OK] Generated component!
```

**My `ionic info`:**
```
$ ionic info
cli packages: (C:\Users\seiyria\AppData\Roaming\nvm\v10.4.1\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : not installed

local packages:

   @angular-devkit/core       : 0.6.8
   @angular-devkit/schematics : 0.6.8
   @angular/cli               : 6.0.8
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v10.4.1
   npm    : 6.1.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set
```

**Comment by sdey0081** [comment]
It'd be an issue of `ionic-cli`, but it can be fixed with `angular-cli` solution:

> angular.json

```
  "schematics": {
      "@schematics/angular:component": {
          "styleext": "scss"
      }
   },
```

**Comment by seiyria** [comment]
Yes, my main reason for reporting this is that it's inconsistent, so ionic could change the default for projects it generates. That said, I don't know if it should be adjusted upstream or not but I wanted to get the issue in front of someone.

**Comment by dwieeb** [comment]
Thanks @seiyria, I'll take a look into this soon.
