### ISSUE TITLE
 ../../node_modules//index.d.ts(8,9): error TS2687: All declarations of 'observable' must have identical modifiers. [ERROR] Command not found: ng

### ISSUE THREAD

**Issue by vksgautam1** [ionic-team/ionic-cli#3316]
**Description:**
i made a new project so whenever i run a command 
"ionic cordova run android"
this is giving me  issue. so unable to run a build

 ../../node_modules//index.d.ts(8,9): error TS2687: All declarations of 'observable' must have identical modifiers. [ERROR] Command not found: ng

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```

Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.8 (C:\Users\DELL\AppData\Roaming\nvm\v8.9.0\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.8
   @ionic/schematics-angular  : 1.0.0-rc.8

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 25.2.5
   NodeJS            : v8.9.0 (C:\Program Files\nodejs\node.exe)
   npm               : 5.5.1
   OS                : Windows 10

```

**Other Information:**
my package json
`{
  "name": "v4alpha",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ionic serve",
    "build": "ionic build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "6.0.5",
    "@angular/core": "6.0.5",
    "@angular/forms": "6.0.5",
    "@angular/http": "6.0.5",
    "@angular/platform-browser": "6.0.5",
    "@angular/platform-browser-dynamic": "6.0.5",
    "@angular/router": "6.0.5",
    "@ionic-native/core": "5.0.0-beta.10",
    "@ionic-native/splash-screen": "5.0.0-beta.10",
    "@ionic-native/status-bar": "5.0.0-beta.10",
    "@ionic/angular": "4.0.0-alpha.7",
    "@ionic/ng-toolkit": "1.0.0-rc.8",
    "@ionic/schematics-angular": "1.0.0-rc.8",
    "cordova-android": "7.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.19",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.3",
    "rxjs": "6.2.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "6.0.8",
    "@angular/compiler": "6.0.5",
    "@angular/compiler-cli": "6.0.5",
    "@angular/language-service": "6.0.5",
    "@angular-devkit/architect": "0.7.0-rc.0",
    "@angular-devkit/build-angular": "0.7.0-rc.0",
    "@angular-devkit/core": "0.7.0-rc.0",
    "@angular-devkit/schematics": "0.7.0-rc.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.3.2",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~6.1.1",
    "tslint": "~5.10.0",
    "typescript": "~2.7.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
}
`

**Comment by dwieeb** [comment]
@vksgautam1 Can you paste the output of `npm ls @types/zen-observable` ?

**Comment by vksgautam1** [comment]
v4alpha@0.0.1 E:\Working Project\ionic4\v4alpha
`-- (empty)

**Comment by vksgautam1** [comment]
i made another testing project and same issue happened. is there any kind of setup or environment issues.
here is another project
`ionic start newProject

What type of project would you like to create?

We recommend angular. To learn more about project types, see the CLI documentation[1]. To bypass this prompt next time,
supply the --type option.

[1]: https://ionicframework.com/docs/cli/starters.html

? Project type: angular

Let's pick the perfect starter template!

Starter templates are ready-to-go Ionic apps that come packed with everything you need to build your app. To bypass this
prompt next time, supply template, the second argument to ionic start.

? Starter template: tabs
√ Preparing directory .\newProject - done!
√ Downloading and extracting tabs starter - done!
? Integrate your new app with Cordova to target native iOS and Android? Yes
> ionic integrations enable cordova --quiet
√ Downloading integration cordova - done!
√ Copying integrations files to project - done!
[OK] Integration cordova added!

Installing dependencies may take several minutes.

     *   IONIC  DEVAPP   *

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -     Test on iOS and Android without Native SDKs
  -     LiveReload for instant style and JS updates

 -->    Install DevApp: https://bit.ly/ionic-dev-app    <--

────────────────────────────────────────────────────────────

> npm i
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated buildmail@4.0.1: This project is unmaintained

> uws@9.14.0 install E:\Working Project\ionic4\newProject\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@4.9.0 install E:\Working Project\ionic4\newProject\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\DELL\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-x64-57_binding.node

> node-sass@4.9.0 postinstall E:\Working Project\ionic4\newProject\node_modules\node-sass
> node scripts/build.js

Binary found at E:\Working Project\ionic4\newProject\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine

> @angular/cli@6.0.8 postinstall E:\Working Project\ionic4\newProject\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1304 packages in 416.843s
> git init

     *   IONIC  PRO   *

 Supercharge your Ionic development with the Ionic Pro SDK

  -     Track runtime errors in real-time, back to your original TypeScript
  -    Push remote updates and skip the app store queue

 Learn more about Ionic Pro: https://ionicframework.com/pro

────────────────────────────────────────────────────────────

? Install the free Ionic Pro SDK and connect your app? No
> git add -A
> git commit -m "Initial commit" --no-gpg-sign

[INFO] Next Steps:

       - Go to your newly created project: cd .\newProject
       - Get Ionic DevApp for easy device testing: https://bit.ly/ionic-dev-app`

**Comment by vksgautam1** [comment]
for v3 projects it is working fine.

**Comment by vksgautam1** [comment]
`ERROR in ../../node_modules/@types/zen-observable/index.d.ts(8,9): error TS2687: All declarations of 'observable' must have identical modifiers.`
one related one to this is with rxjs.
[https://stackoverflow.com/questions/50639530/error-ts2687-all-declarations-of-observable-must-have-identical-modifiers/50639979#50639979](url)

**Comment by dwieeb** [comment]
Cool, looks like latest `rxjs` and `zen-observable`/`@types/zen-observable` fix this issue.
