### ISSUE TITLE
Generate Default-2436h.png and Default-Landscape-2436h.png images

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3319]
`ionic cordova resources` should generate `Default-2436h.png` and `Default-Landscape-2436h.png` for iOS

In general it's best to try to generate all the expected launch images: https://github.com/apache/cordova-ios/blob/master/bin/templates/project/__PROJECT_NAME__/Images.xcassets/LaunchImage.launchimage/Contents.json

Original issues:
- https://github.com/ionic-team/ionic-cli/issues/2904
- https://github.com/ionic-team/ionic-cli/issues/2928

**Comment by kinggolf** [comment]
I'll post this here but if this is just a support question, then I apologize. In running `ionic cordova resources ios` I found cases depending on the base splash.png image that the command would not complete and not all images were created properly. Here are the details:
1) Created a new Ionic V4 project.
2) Ran `ionic cordova resources ios` using the default ionic splash.png image - this ran successfully.
3) Replaced splash.png with a new image, just a solid color background - this ran successfully.
4) Added text to this splash.png image and reran - this ran successfully.
5) Added a small image to this same splash image and reran - not all files were created successfully!!
Here is a screen shot of the splash image with the image added and one of the files that resulted.

<img width="602" alt="splash_images" src="https://user-images.githubusercontent.com/9776423/41678268-7a219c58-747f-11e8-98d6-bdaa7f8bb5db.png">

Not sure what to try next. When this happens the command just sits idling w/out completing and w/out errors message.
```
ionic cordova resources ios
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations: 2 / 2 complete - done!
⠙ Generating platform resources: 10 / 13 complete 
```

**Comment by dwieeb** [comment]
@kinggolf The resources server is notoriously flakey. I just kicked it. Would you mind trying again? If it's generating the same images, try making a modification to the png and trying again.

**Comment by kinggolf** [comment]
@dwieeb Thanks. Just re-running still did work completely. I moved the photo of the muffin down in the overall splash.png image and it worked! I probably should be using LaunchStoryboard anyway. Appreciate the response.

**Comment by moldstadt** [comment]
Any update on this issue?  Not having the iPhone-X splash screens causes issues with in-app-browser: https://github.com/apache/cordova-plugin-inappbrowser/issues/306

**Comment by vespino** [comment]
Would love to see a solution for this issue. I guess this has been around since iPhone X which was released over a year ago.

**Comment by dwieeb** [comment]
This was resolved by this PR: https://github.com/ionic-team/cordova-res/pull/26

Available in latest `cordova-res`. 

- Make sure you're on the latest Ionic CLI: `npm i -g ionic@latest`
- Update `cordova-res`: `npm i -g cordova-res@latest`
- Run `ionic cordova resources`
