### ISSUE TITLE
Unable to create a page with a name like hello2

### ISSUE THREAD

**Issue by pastcompute** [ionic-team/ionic-cli#3322]
**Description:**
I decided to try out the ionic4 beta and created a hello world app. I hit this problem almost immediately, where I tried to create a page with the name 'hello2' and received an error message.

**Steps to Reproduce:**
1. ```ionic start hello blank --type=angular --cordova --no-link```
2. ```ionic generate page hello```   -- this worked
3. ```ionic generate page hello2```   -- this failed

**Output:**

Error message was
```
> ng generate page pages/hello2
Selector (hello-2) is invalid.
[ERROR] Could not generate page.
```

Expected output was a page called hello2

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.9 (C:\Users\demo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

Note same problem observed on MacOS and Linux

**Other Information:**

I had a look in the source and the problem appears to be with the schematic or Angular schematic validation rules.
https://github.com/ionic-team/ionic-cli/blob/master/packages/%40ionic/schematics-angular/page/index.ts#L154
hello2 is first turned into kebak case "hello-2", this then fails validation in @angular/schematic appears to not like names of the form "hello-2" 
As a developer end user, but noting I have primarily only used Angular through Ionic3, I find it somewhat strange that I am prevented from creating a page with the name "hello2".  If indeed this is a necessary restriction then the error message should perhaps make it clear why the selector is invalid, this will confuse new users of the framework no end.
I'm going to suggest this is a minor UX problem with ionic because it is impossible to specify a name that generates a valid selector if suffixed with a number, no matter what I tried the enforced kebab case inserts a hyphen at the last number

**Comment by dwieeb** [comment]
Thanks, good feedback. I'll take a look at how Angular builds their selectors and try to use what they do.

**Comment by dwieeb** [comment]
This fix will be in RC.11 (probably tomorrow)
