### ISSUE TITLE
Can't log in with the CLI - Incorrect email or password.

### ISSUE THREAD

**Issue by ahrherrera** [ionic-team/ionic-cli#3328]
**Description:**

Hi, I signed up my account yesterday but I can't login with CLI. My credentials are OK. My password is alphanumeric with uppercase and /.

I can log in successful on the dashboard.

**Steps to Reproduce:**
Just launch 
`ionic login`
and add type the credentials
**Output:**

`Log into your Ionic account
If you don't have one yet, create yours by running: ionic signup
[ERROR] Incorrect email or password.`

**My `ionic info`:**

```
cli packages: (C:\Users\ahrhe\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.2
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by techboycr** [comment]
Same issue here, but I can't change the password on ionic dashboard, even worst.

Any ideas?

**Comment by dwieeb** [comment]
@ahrherrera I will need to investigate that. The CLI should allow all characters that are valid in the dashboard.

@techboycr If you can't change your password in the dashboard, I definitely recommend contacting our support: https://ionicframework.com/support/request

**Comment by ahrherrera** [comment]
@dwieeb it only happens on Windows CMD and Powershell. I tried on Ubuntu terminal and is OK, no problems.

**Comment by tbhavik** [comment]
in windows run as administrator CMD

**Comment by aacassandra** [comment]
on my mac. im only login via browser. end then login with ionic cli like below
'ionic login'
ionic cli auto login with opening default brwoser
