### ISSUE TITLE
The order of the flags --prod and --release seem to matter

### ISSUE THREAD

**Issue by tomas-eklund** [ionic-team/ionic-cli#3329]
**Description:**

Using the below command (copied verbatim from https://ionicframework.com/docs/intro/deploying/) resulted in an `android-debug.apk` being generated. _That was unexpected_ as I was hoping to get a _release_ build out of it, and not a _debug_ build. This is also how the command appears when using `ionic cordova build --help`:

`> ionic cordova build android --prod --release`

Searching online for a solution to my problem of not being able to build a release APK, I stumbled upon a forum post suggesting reversing the flags `--prod` and `--release`. Although that user had a different problem, I tried it and got the intended `android-release-unsigned.apk` file.

`> ionic cordova build android --release --prod`

**Steps to Reproduce:**

I'm still on my very first Ionic project so I can't say for sure if this is a general problem or if there is something peculiar with my setup resulting in this unexpected and inconsistent behavior.

**Output:**

`ionic cordova build android --prod --release` results in `android-debug.apk`
`ionic cordova build android --release --prod` results in `android-release-unsigned.apk`

**My `ionic info`:**

```
cli packages: (C:\Users\{username}\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.9.4
    npm  : 3.10.10
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Other Information:**

The user **jamesharvey** suggested switching the order of the flags while researching a different issue. I don't know if he had the same problem I did.
 
https://forum.ionicframework.com/t/prod-version-android-debug-apk-for-release/113721/9

**Comment by dwieeb** [comment]
The Ionic CLI will print what command it invokes in green. Do you see this?

```
...
> cordova build android --release
...
```

For the record, I'm not getting this issue. Both `--prod --release` and `--release --prod` result in:

```
Built the following apk(s):
	...platforms/android/build/outputs/apk/android-release-unsigned.apk
```

**Comment by tomas-eklund** [comment]
I am terribly sorry. I just `diff`ed the console logs and apparently I had NOT copied the command from the tutorial/documentation. I had missed one dash typing `-release` instead of `--release`. Feeling very stupid for wasting people's (including my own) time. :-(
