### ISSUE TITLE
Cannot create a new project with Ionic

### ISSUE THREAD

**Issue by alim90** [ionic-team/ionic-cli#3347]
I am unable to create a new ionic project with cordova.

When the prompt ask me if I want to integrate cordova with the app and whatever my answer was (Yes or no), I have to wait hours and hours and nothing happens and just a folder with just single file (src) is created.

I am using the latest version of Node and NPM.

I tried to uninstall everything globally and re-install it again, but still having the same problem.

Any help would be appreciated. I can't provide any more details as this is what I got. I tried everything from removing/uninstalling all and then re-install. Restart computer, even change it. The internet speed is good (I don't think it has something to do with it).

**Comment by dwieeb** [comment]
The issue template helps provide more information, as I can't help you without provided details. If you run `ionic info` and paste the output, that will get us started.

**Comment by famojuro** [comment]
I cant start an ionic 4 project and this is my ionic info
 
Ionic:

   ionic (Ionic CLI) : 4.1.1

System:

    NodeJS : v8.11.3
   npm    : 6.4.0
   OS     : Windows 10

**Comment by dwieeb** [comment]
@famojuro Make a new issue please, be sure to post any errors and other helpful info.
