### ISSUE TITLE
"ionic build --prod" invokes "cordova prepare". How to skip cordova when building for web only?

### ISSUE THREAD

**Issue by raimaj** [ionic-team/ionic-cli#3359]
**Description:**
I use Ionic both for mobile and the web. I have 2 different build CI systems, one for mobile (android + ios) and one for the web.

In order to speed up the build process for the web, I tried to run "ionic build --prod" on a container with no cordova installed. This resulted in a error because the CLI invoked "cordova prepare".

Is there a way to just build for web bypassing the whole cordova part of the build?

Thanks

**Steps to Reproduce:**
Run `ionic build --prod` on a system where you haven't installed cordova.

**Output:**
```
...
[09:40:33]  sass finished in 1.60 s 
[09:40:33]  cleancss started ... 
[09:40:36]  cleancss finished in 2.21 s 
[09:40:59]  uglify finished in 27.53 s 
[09:40:59]  postprocess started ... 
[09:40:59]  postprocess finished in 17 ms 
[09:40:59]  lint started ... 
[09:40:59]  build prod finished in 118.19 s 
> ionic cordova prepare --no-build
> cordova prepare
[ERROR] The Cordova CLI was not found on your PATH. Please install Cordova globally:

        npm i -g cordova
```

**My `ionic info`:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.11.3
    npm  : 5.6.0 
    OS   : Linux 4.9
```

**Comment by dwieeb** [comment]
This is being fixed in CLI v4. `ionic build` will no longer run `ionic cordova prepare`.

**Comment by raimaj** [comment]
@dwieeb Thanks! But can I use CLI v4 with Ionic 3?

**Comment by dwieeb** [comment]
Yes.
