### ISSUE TITLE
Unable to find starter template for blank

### ISSUE THREAD

**Issue by imad-abdou** [ionic-team/ionic-cli#3360]
**Description:**

i try get started with ionic on Windows 10
node v8.11.3
npm v5.6.0

**Steps to Reproduce:**
ionic start velochat blank --type=ionic2

**Output:**
√ Creating directory .\velochat - done!
× Looking up starter - failed!
[ERROR] Unable to find starter template for blank

        If this is not a typo, please make sure it is a valid starter template within the starters repo:
        https://github.com/ionic-team/starters

**Other Information:**
i tried also install latist one but same problem occure
npm install -g ionic@latest

**Comment by dwieeb** [comment]
Try `--type=ionic-angular`. Use `ionic start --list` to list available starter templates.
