### ISSUE TITLE
ionic-cli ionic login can`t login in   error:410

### ISSUE THREAD

**Issue by fssgh** [ionic-team/ionic-cli#3364]
**Description:**

ionic-cli ionic login can`t login in  error:410
![qq 20180712111617](https://user-images.githubusercontent.com/14868289/42610635-15811434-85c5-11e8-87a4-a0c8a8d895fd.png)

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
ionic-cli v3.20.0
```

**Other Information:**

**Comment by dwieeb** [comment]
@fssgh Try `ionic config set -g backend pro` and then `ionic login` again. You are attempting to login to the old Ionic Cloud backend. This is a bit confusing, my apologies. CLI 4 removes the `legacy` backend.
