### ISSUE TITLE
v4: CLI generates pages (and components) inside src/app instead of src/app/pages (or src/app/components)

### ISSUE THREAD

**Issue by raimaj** [ionic-team/ionic-cli#3367]
**Description:**
When running `ionic g page`  inside a Angular 6 project, CLIv4 generates the new page folder inside `src/app` instead of `src/app/pages`.

Same thing with `ionic g component` inside a Angular 6 project, CLIv4 generates the new component folder inside `src/app` instead of `src/app/components`.

**Steps to Reproduce:**
Running `ionic g page`  or `ionic g component` inside a Angular 6 project.

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 
   Ionic Framework            : @ionic/angular 4.0.0-alpha.9
   @angular-devkit/core       : 0.7.0-rc.1
   @angular-devkit/schematics : 0.7.0-rc.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.10
   @ionic/schematics-angular  : 1.0.0-rc.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.0.2
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Comment by dwieeb** [comment]
@raimaj This is going to be a persistent point of confusion with the new v4 stuff. Generating pages inside the app root is what the Angular CLI does as well and we want to align our tooling for Angular as closely as possible.

We'll have documentation for this, but basically if you want pages in the `pages/` directory, you have to run this:

```
ionic g page pages/<page-name>
```

This works at any nested level, e.g. `ionic g page pages/tabs/tab1`

**Comment by raimaj** [comment]
@dwieeb Oh thanks, was not aware of that!

**Comment by dwieeb** [comment]
Closing, as I've addressed this in both CLI output and our documentation: https://beta.ionicframework.com/docs/building/scaffolding#generating-new-features
