### ISSUE TITLE
v4: ionic serve `Error: listen EADDRINUSE :::53703`

### ISSUE THREAD

**Issue by raimaj** [ionic-team/ionic-cli#3368]
**Description:**
When using CLI v4 with a Ionic 3 project, the `ionic serve` command only works the first time.

After stopping the command with CTRL+C, running `ionic serve` again results in a error.

Restarting the computer fixes the problem.

**Steps to Reproduce:**
1. Run `ionic serve` using CLI v4rc11 in a Ionic 3 Project
2. Stop the serve command (CTRL+C)
3. Run `ionic serve` again

**Output:**

```
> ionic-app-scripts serve --address 0.0.0.0 --port 8101 --livereload-port 35730 --dev-logger-port 53703 --nobrowser
[app-scripts] [12:31:03]  ionic-app-scripts 3.1.10
[app-scripts] [12:31:03]  watch started ...
[app-scripts] [12:31:03]  build dev started ...
[app-scripts] events.js:183
[app-scripts]       throw er; // Unhandled 'error' event
[app-scripts]       ^
[app-scripts]
[app-scripts] Error: listen EADDRINUSE :::53703
[app-scripts]     at Object._errnoException (util.js:992:11)
[app-scripts]     at _exceptionWithHostPort (util.js:1014:20)
[app-scripts]     at Server.setupListenHandle [as _listen2] (net.js:1355:14)
[app-scripts]     at listenInCluster (net.js:1396:12)
[app-scripts]     at Server.listen (net.js:1480:7)
[app-scripts]     at new WebSocketServer (C:\Users\***\node_modules\ws\lib\WebSocketServer.js:77:20)
[app-scripts]     at Object.createNotificationServer (C:\***\node_modules\@ionic\app-scripts\dist\dev-server\notification-server.js:66:15)
[app-scripts]     at C:\Users\***\node_modules\@ionic\app-scripts\dist\serve.js:58:31
[app-scripts]     at <anonymous>
[app-scripts]     at process._tickCallback (internal/process/next_tick.js:188:7)

[ERROR] A utility CLI has unexpectedly closed.

        The Ionic CLI will exit. Please check any output above for error details.
```

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)  : 4.0.0-rc.11 (C:\Users\***\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.7.1
   @ionic/app-scripts : 3.1.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.0.2
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Comment by dwieeb** [comment]
Thanks @raimaj I believe I've found the issue. The fix will be in app-scripts.

**Comment by dwieeb** [comment]
@raimaj Please update app-scripts: `npm install @ionic/app-scripts@latest` and see if that clears up the issue. 

There may be a second issue where the Ionic CLI is not cleaning up after a serve. See https://github.com/ionic-team/ionic-cli/issues/3022. It seems to happen only sometimes on Windows and I guess I haven't been able to track it down yet.

**Comment by raimaj** [comment]
@dwieeb Seems to work now but the browser fails to lunch, getting this error instead:
![image](https://user-images.githubusercontent.com/3295133/42646675-df268274-8601-11e8-81fd-61ea75670d59.png)

Also the port seems to be different at every `ionic serve` run (always incremented by one).

I should say I am on a different computer right now, this new issue could be totally unrelated. Will be back at the same computer on Monday and will test it then.

**Comment by Sami-Haroon-Khan** [comment]
Do I downgrade to 3.20 ?

**Comment by dwieeb** [comment]
No. This is the fix: `npm install @ionic/app-scripts@latest`

This issue is resolved. Please create new issues if necessary. @raimaj
