### ISSUE TITLE
Troubleshooting Guide for Livereload

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3370]
See following issues for potential problems:

- https://github.com/ionic-team/ionic-cli/issues/2719
- https://github.com/ionic-team/ionic-cli/issues/2757

**Comment by dwieeb** [comment]
Moved to https://github.com/ionic-team/ionic-docs/issues/84

**Comment by RohanBolusani** [comment]
hey! i dont face this issue in ionic 4 but i face it on  ionic 3
