### ISSUE TITLE
ionic cordova resources crashing (ERR_STREAM_DESTROYED)

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic-cli#3385]
**Description:**

When trying to generate the appropriate resources to build a project, `ionic cordova resources` does crash in the generation process.

**Steps to Reproduce:**

Call `ionic cordova resources` inside an Ionic 4 project.

**Output:**

```
ionic cordova resources                                                                                                                                                                      
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations: 2 / 2 complete - done!
✖ Generating platform resources: 3 / 25 complete - failed!
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

    at doWrite (_stream_writable.js:406:19)
    at clearBuffer (_stream_writable.js:540:7)
    at onwrite (_stream_writable.js:465:7)
    at fs.write (fs.js:2284:5)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:645:5)
⠏ Generating platform resources: 7 / 25 complete
```

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.11
   @angular-devkit/core       : 0.7.0-rc.1
   @angular-devkit/schematics : 0.7.0-rc.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.11
   @ionic/schematics-angular  : 1.0.0-rc.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0 ios 4.5.4

System:

   NodeJS : v10.4.1 (/usr/local/bin/node)
   npm    : 6.2.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Comment by dwieeb** [comment]
@carstenbaumhoegger I'm guessing the resources server was just a bit flaky. Please try again. I just restarted it.

**Comment by carstenbaumhoegger** [comment]
hey @dwieeb !

You're right, the error I mentioned was gone when I tried to generate the resources the first time!

Unfortunately the process didn't complete and hang up with 5 out of 25 generated.

```
ionic cordova resources
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations: 2 / 2 complete - done!
⠼ Generating platform resources: 5 / 25 complete
```

I re-ran the command and now I get the same error again.

```
ionic cordova resources
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations: 2 / 2 complete - done!
✖ Generating platform resources: 1 / 25 complete - failed!
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

    at doWrite (_stream_writable.js:406:19)
    at clearBuffer (_stream_writable.js:540:7)
    at onwrite (_stream_writable.js:465:7)
    at fs.write (fs.js:2284:5)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:645:5)
⠧ Generating platform resources: 4 / 25 complete
```
Sometimes the process get's to 4 or 5 generated or even 10, but it never made it to generating all 25 files.

**Comment by dwieeb** [comment]
@carstenbaumhoegger Well that's odd. I didn't change anything with the resource generation, and it's working fine for me. I'll keep this open, but I'm still convinced the server is fickle. 

You're not behind a network proxy or anything, right?

**Comment by iamsteeve** [comment]
The same thing happens to me with the version of cli ionic 4.0.1
I did the normal installation flow of an ionic project ` ionic start myApp sidemenu --type=angular` and without the type too. 
`  Generating platform resources: 2 / 18 complete - failed!
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

    at doWrite (_stream_writable.js:406:19)
    at clearBuffer (_stream_writable.js:540:7)
    at onwrite (_stream_writable.js:465:7)
    at fs.write (internal/fs/streams.js:281:5)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:509:5)
`

The only interesting thing is that with the new version of ionic 4 the error appears but when I use the normal one without adding the type = angular because the error does not appear and it freezes does not advance.

The temporary solution is to downgrade to version 3

**Comment by dwieeb** [comment]
@iamsteeve Are you behind a network proxy?

**Comment by iamsteeve** [comment]
@dwieeb No c:

**Comment by dwieeb** [comment]
@iamsteeve Mac OS or another operating system? 

@carstenbaumhoegger @iamsteeve are you trying to generate custom images? Could you upload them so I can try to debug with them?

**Comment by carstenbaumhoegger** [comment]
@dwieeb I'm not behind a proxy. Yes, it's a custom image, I'm going to upload it into the issue later this day!

**Comment by Holbanner** [comment]
Having the exact same problem.
Here is my setup.
iOS platform doesn't show because I can't add it again because of that error

Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.0
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.3.0, ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v10.4.1 (/usr/local/bin/node)
   npm               : 6.1.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.3.1 Build version 9E501

**Comment by troyanskiy** [comment]
I had the same problem with 4.0.0 or 4.0.1
Ionic v 3.20.0 - OK

**Comment by diegobcorrea** [comment]
same error here with last update on Ionic CLI

**Comment by mlynch** [comment]
Thanks, we are aware. No ETA on a fix

**Comment by jairdeon** [comment]
same error here with last update on Ionic CLI.

**Comment by dwieeb** [comment]
Out of curiosity, could someone try this CLI version and let me know if the error still occurs: `npm i -g ionic@4.1.0-testing.458303e0`

**Comment by stenioanibal** [comment]
Same error with latest Ionic CLI

**Comment by DatScreamer** [comment]
Had the same issue with v4.0.1 but when I ran `npm i -g ionic@4.1.0-testing.458303e0` it worked flawlessly.

**Comment by kckoerich** [comment]
following @dwieeb & @DatScreamer tips it worked like a charm for m!

**Comment by arjha** [comment]
Had same problem, but after running  @DatScreamer suggested command it worked fine.

**Comment by stenioanibal** [comment]
@dwieeb This works like a charm for me!!! Thanks life saver!

**Comment by camtera** [comment]
Thank you @DatScreamer, solution works above.     I've had issues for past 3 days.   Thank you @mlynch and ionic team for such a fabulous image generating tool.

**Comment by dwieeb** [comment]
Thank you all for testing the `4.1.0-testing.458303e0` version. 💪 The fix will be in `4.0.2` when this gets merged: https://github.com/ionic-team/ionic-cli/pull/3429

**Comment by OmkarFatale** [comment]
I was still having this issue with ionic cli 4.12.0, 

```
ionic cordova resources android --force
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
| Uploading source images to prepare for transformations
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
```

so I used this [NPM Cordova-Res package](https://www.npmjs.com/package/cordova-res) to generate resources

**Comment by kneeki** [comment]
@OmkarFatale Thanks for this!
