### ISSUE TITLE
Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.) iOS 9.*.* and iOS 10.*.* problem

### ISSUE THREAD

**Issue by SimBrunet** [ionic-team/ionic-cli#3400]
**Description:**
Hello everyone, 
I'm having an issue with my app, everything works fine on Android and iOS 11 and greater but on iOS 10 or 9 this problems come : 
I launch my app, the splash screen appears, the app updates, and when the splash screen disappear there is nothing but a blank page. 
I tried to reproduce the error on a simulator and got the following error in the console : 
`Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)`
I searched for solutions online and try several things as : 
- update the app in the background
- modifying the config.xml file 
- hide the splashscreen if and only if the platform is ready

But nothing worked.

**My `ionic info`:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.10.0
    npm  : 6.1.0
    OS   : Linux 4.4

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Other Information:**

Some things I've tried : 
https://forum.ionicframework.com/t/after-splash-screen-display-white-screen-long-time/80162/33
https://www.codingandclimbing.co.uk/blog/ionic-2-fix-splash-screen-white-screen-issue
https://github.com/ionic-team/ionic/issues/7052

Thank you for your time

**Comment by idrisalshikh** [comment]
I have the same problem did you find solution?

**Comment by ggalvez92** [comment]
Do you find any solution? because I have the same problem :(

**Comment by SimBrunet** [comment]
It was a plugin version problem, the thing is Ionic evoluates quickly and doesn't support the old iOS versions. I don't remember exactly what plugin was wrong but try in your config file to remove them all and add them one by one to see wich ones are bugging. 
Sorry it was a long time ago and I have abandoned my project since.
