### ISSUE TITLE
Can't build ionic v1 project (since ionic v4 update)

### ISSUE THREAD

**Issue by jacquesdev** [ionic-team/ionic-cli#3406]
**Description:**
I can't build my ionic v1 app

**Steps to Reproduce:**
```ionic cordova build ios

**Output:**
```
> ionic-v1 build
[ERROR] Command not found: ionic-v1
```


**My `ionic info`:**
<!--
Post the output of running `ionic info` (within your project, if applicable)
below. `ionic info` is a CLI command that prints out environment information.
-->

```
Ionic:

   ionic (Ionic CLI) : 4.0.1
   Ionic Framework   : ionic1 1.3.5
   @ionic/v1-toolkit : not installed

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.4

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.9.4 (/Users/user/.nvm/versions/node/v8.9.4/bin/node)
   npm        : 2.15.12
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4 Build version 9F1027a

Environment:

   ANDROID_HOME : /Library/Android/sdk

```


**Other Information:**
:(

**Comment by jacquesdev** [comment]
I guess this is because the new project @ionic/v1-toolkit is required, perhaps you can update the error to mention this?

**Comment by dwieeb** [comment]
Thanks @jacquesdev 

Yep, it's a bad error message.

**Comment by dave-k** [comment]
> $ ionic cordova build ios
> ionic-v1 build
[ERROR] Command not found: ionic-v1

I am getting the same error.
What is the fix for this error?

**Comment by dwieeb** [comment]
```
npm i -D @ionic/v1-toolkit
```

I am working on an auto-installer prompt at this moment.

**Comment by parthnayak7448** [comment]
After using

>  npm i -D @ionic/v1-toolkit

i was successfully able to build my ionic v1 app in ionic CLI 4.0.2 

thanks @dwieeb

**Comment by dave-k** [comment]
There is an issue with node and the 'internal contextify script' : Assertion `args[1]->IsString()' failed

macOS High Sierra v10.13.5

    $ npm -v
    6.2.0
    $ node -v
    v10.7.0
    $ ionic -v
    CLI 4.0.2

    $ ionic cordova build ios
    > ionic-v1 build
    ionic-v1[53011]: ../src/node_contextify.cc:635:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.

**Comment by dwieeb** [comment]
@dave-k That looks like a different issue. Please create a new issue.

**Comment by rodrigograca31** [comment]
I had version 4.0.0 (updated the moment it came out) and had that bad error message.
I've run `sudo npm i -g ionic@latest` and re run my build command and got:
```bash
> ionic-v1 build

[INFO] Looks like @ionic/v1-toolkit isn't installed in this project.
       
       This package is required for this command to work properly.

? Install @ionic/v1-toolkit? Yes
> npm i -D -E @ionic/v1-toolkit
```

AWESOME!

P.S. shouldnt it use `--save`? (so that it works in the future....)

**Comment by dwieeb** [comment]
@rodrigograca31 Good to hear the prompt is working for you. `--save` has been the default in npm for a while now! It should automatically save it to `package.json`.

**Comment by rodrigograca31** [comment]
Oh, didn't know that! Yes, it saved! (under `devDependencies`)
