### ISSUE TITLE
"ionic cordova prepare" does not work on a fresh project checkout

### ISSUE THREAD

**Issue by sachingarg05** [ionic-team/ionic-cli#3426]
**Description:**
On a fresh project checkout which does not have any platofrms or plugins folders, this command does not work anymore after 4.x cli update:

  ionic cordova prepare

It compains that it coudln't find any platforms. It used to work with previous ionic cli releases. Directly doing "cordova prepare" (without ionic) works.

Also, this still works:

  ionic cordova prepare ios android

"ionic cordova prepare" should work without having to specify any platforms (it should prepare all platforms by default).

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, ios 4.5.5

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v8.11.1 (/usr/local/bin/node)
   npm        : 6.1.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Comment by dwieeb** [comment]
Yes, this should be fixed. Platform detection appears to be done by listing the contents of `platforms/`, which is the safest way for `ionic cordova resources`, but should not be used for `ionic cordova prepare`.

Thanks for the issue!

**Comment by sachingarg05** [comment]
Why is ionic cli trying to do 'anything' here, like looking into contents of platforms etc... Shouldn't ionic cli should only look for its own parameters (like --prod etc), process them, and pass on the rest as-is to underlying cordova or angular cli?

Just feels like a case of ionic cli getting in the way where it doesn't need to. I am sure I am missing the details here, so trying to understand whats going on.

There would be way too many other similar use cases than what ionic team can test and fix for. Like ionic cli passing on stuff to angular cli which in turn passes parameters to webpack cli for serve (which has some really nice features we look forward to using), etc... best to stay out of the way as much as possible and do as little as needed, and pass on all the rest of the parameters as-is.

**Comment by dwieeb** [comment]
```
❯ cordova prepare ios
(node:18775) UnhandledPromiseRejectionWarning: CordovaError: No platforms added to this project. Please use `cordova platform add <platform>`.
    at Object.preProcessOptions (/Users/dan/.nvm/versions/node/v8.11.2/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:312:15)
    at /Users/dan/.nvm/versions/node/v8.11.2/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:51:40
    at _fulfilled (/Users/dan/.nvm/versions/node/v8.11.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/dan/.nvm/versions/node/v8.11.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/dan/.nvm/versions/node/v8.11.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/dan/.nvm/versions/node/v8.11.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:557:44
    at flush (/Users/dan/.nvm/versions/node/v8.11.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
(node:18775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18775) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

vs 

```
❯ ionic cordova prepare ios
? Platform ios is not installed! Would you like to install it? (Y/n)
```

I feel like it's Ionic's duty to make things as friendly as possible. While yes, it is challenging to keep up with all the possibilities, I think it's worth it to provide the best experience possible.

Regarding this:

> Shouldn't ionic cli only look for its own parameters (like --prod etc), process them, and pass on the rest as-is to underlying cordova or angular cli?

For some of the `ionic cordova` commands (`run`/`emulate`, `build`), we wrap both CLIs in a single command, so we need to figure out where each option goes. If we get it wrong, the Angular CLI exits immediately with this error:

```
❯ npx ng build --this-breaks-everything
Unknown option: '--thisBreaksEverything'
```

So we can't just pass arguments "as-is" because it would be a bad experience. We need to know which options go where.
