### ISSUE TITLE
After ionic cli v4 update, apk and ipa gained more than 1mb!

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-cli#3430]
**Description:**
I built a new version of my app and before submitting it to the store I had a look to the ipa and apk size and both gained more than 1mb size!

On my side I didn't changed or fetched any libs and just changed one or two lines of code. The only library update I did was upgrading the CLI to v4

My current app in store:

Android -> 5.9 Mb
iOS ipa -> 9.7 Mb

Build with the CLI v4:

Android -> 7.2 Mb
iOS ipa -> 10.9 Mb

**My `ionic info`:**

Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, ios 4.5.4, pwa

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 5.0.13
   NodeJS            : v10.4.0 (/usr/local/bin/node)
   npm               : 6.1.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/me/Library/Android/sdk

**Workaround**

Downgrading to Ionic CLI 3.20.0 solves the issue, my app size was back to its previous weight

**Comment by danielsogl** [comment]
I noticed the same with my ionic v3 projects build for production with cli v4

**Comment by dwieeb** [comment]
I believe the above commit will fix this issue. When I ran it with that commit, my `www/` directory went from 3.5M to 1.3M. 

The fix should be in 4.0.2. If it doesn't work, let me know! Thanks for the issue!

**Comment by peterpeterparker** [comment]
@dwieeb cool thx a lot, sure will test

**Comment by peterpeterparker** [comment]
@dwieeb it's not solved!

I've updated my global cli to v4.0.2 (not the local one) and just built a new version and again the result are too big apps

Plz reopen the issue

**Comment by peterpeterparker** [comment]
@dwieeb ignore my previous msg I just deleted, it works all good

I have updated my global cli v4.0.2 and could confirm my app size is back to normal 👍

**Comment by dwieeb** [comment]
Nice! Great to hear. 👍
