### ISSUE TITLE
[ERROR] Could not generate page

### ISSUE THREAD

**Issue by josephlodero** [ionic-team/ionic-cli#3433]
**Description:**
There's an error every time I generate a page.

**Output:**

![image](https://user-images.githubusercontent.com/11495107/43372537-627b337e-93d4-11e8-90fa-6d94249e9e5f.png)

**My `ionic info`:**

![image](https://user-images.githubusercontent.com/11495107/43372552-956fdb36-93d4-11e8-9301-54b2a882f6f1.png)

**Comment by rdlabo** [comment]
@josephlodero It is work in my environment. Maybe @angular.cli is too old.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/Users/sakakibara/dev/ionic-cli/packages/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

System:

   NodeJS : v8.11.3 (/usr/local/bin/node)
   npm    : 6.2.0
   OS     : macOS High Sierra
```

**Comment by josephlodero** [comment]
Hi @rdlabo, Thanks. I just updated my angular/cli to latest and now its working!
