### ISSUE TITLE
is `ionic-angular-v3-v4-migration` closed or moved?

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-cli#3463]
I found `cli-utils/src/lib/project/angular/ionic-angular-v3-v4-migration.ts` at 2018/05/07.
But today, I can't find.

this project is closed? or moved or change 'v4-migration-tslint'? 
thanks.

**Comment by dwieeb** [comment]
Yes, it was removed in favor of our [migration guide](https://beta.ionicframework.com/docs/building/migration) and the [`@ionic/v4-migration-tslint` project](https://github.com/ionic-team/v4-migration-tslint).

**Comment by rdlabo** [comment]
thanks for replay. sure, I watch @ionic/v4-migration-tslint project.
