### ISSUE TITLE
Shell Error on platform add

### ISSUE THREAD

**Issue by jayeshanandani** [ionic-team/ionic-cli#3484]
**Description:**

On upgrading to latest ionic cli not able to add platform.

**Steps to Reproduce:**

Clone fresh repo and keep cli version at 4.0.3. 

Try to add android platform@7.1.0

**Output:**

```
ShellCommandError: Non-zero exit from subprocess. { name: 'ShellCommandError', code:
        'ERR_ICF_SHELL_NON_ZERO_EXIT', exitCode: 1, signal: undefined } Error

             at new BaseError
        (/Users/jayesh/.nvm/versions/node/v8.9.3/lib/node_modules/ionic/node_modules/@ionic/cli-framework/errors.js:15:23)
             at new ShellCommandError
        (/Users/jayesh/.nvm/versions/node/v8.9.3/lib/node_modules/ionic/node_modules/@ionic/cli-framework/errors.js:47:9)
             at ChildProcess.p.on
        (/Users/jayesh/.nvm/versions/node/v8.9.3/lib/node_modules/ionic/node_modules/@ionic/cli-framework/utils/shell.js:99:33)
             at emitTwo (events.js:126:13)
             at ChildProcess.emit (events.js:214:7)
             at maybeClose (internal/child_process.js:925:16)
             at Socket.stream.socket.on (internal/child_process.js:346:11)
             at emitOne (events.js:116:13)
             at Socket.emit (events.js:211:7)
             at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**My `ionic info`:**

```
cli packages: (/Users/jayesh/.nvm/versions/node/v8.9.3/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 5.0.12
    Node       : v8.9.3
    npm        : 5.6.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Other Information:**

**Comment by dwieeb** [comment]
@jayeshanandani Can you please post the full command output?

**Comment by jayeshanandani** [comment]
Hi @dwieeb 

Above is the only output I get which I have pasted in description.

**Comment by rluckez** [comment]
Same problem here, just started a new project with "type--angular --cordova".

**Comment by reinerluke** [comment]
`Discovered plugin "cordova-plugin-ionic" in config.xml. Adding it to the project
Failed to restore plugin "cordova-plugin-ionic" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-ionic@^2.0.4 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...
[ERROR] ShellCommandError: Non-zero exit from subprocess. { name: 'ShellCommandError', code:
        'ERR_ICF_SHELL_NON_ZERO_EXIT', exitCode: 1, signal: undefined } Error

             at new BaseError
        (C:\Users\Lukas\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-framework\errors.js:15:23)
             at new ShellCommandError
        (C:\Users\Lukas\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-framework\errors.js:47:9)
             at ChildProcess.p.on
        (C:\Users\Lukas\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-framework\utils\shell.js:99:33)
             at emitTwo (events.js:126:13)
             at ChildProcess.emit (events.js:214:7)
             at ChildProcess.cp.emit
        (C:\Users\Lukas\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:40:29)
             at maybeClose (internal/child_process.js:925:16)
             at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
net.js:714
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:714:11)
    at process.<anonymous> (C:\Users\Lukas\AppData\Roaming\npm\node_modules\ionic\bin\ionic:9:63)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)`

same error...

**Comment by kurtiev** [comment]
@jayeshanandani 
Hi,
i had the same error message, but it's gone after i removed 'node_modules' and 'plugins' folders.

**Comment by bobtheowl** [comment]
I'm currently experiencing the same issue, but none of the suggestions posted so far have helped.

Here is my ionic info:

```
Ionic:

   ionic (Ionic CLI)  : 4.1.0 (C:\Users\jstair\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.5

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic-webview 2.0.3, (and 18 other plugins)

System:

   Android SDK Tools : 26.0.2
   NodeJS            : v6.9.5 (C:\Program Files (x86)\nodejs\node.exe)
   npm               : 5.5.1
   OS                : Windows 7

Environment:

   ANDROID_HOME : C:\Users\jstair\AppData\Local\Android\Sdk
```

And here is the last output I get when it errors out:

```
Saving android@~6.3.0 into config.xml file ...
[ERROR] ShellCommandError: Non-zero exit from subprocess. { name: 'ShellCommandError', code:
        'ERR_ICF_SHELL_NON_ZERO_EXIT', exitCode: 1, signal: undefined } Error

             at ShellCommandError.BaseError
        (C:\Users\jstair\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-framework\errors.js:15:23)
             at ShellCommandError
        (C:\Users\jstair\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-framework\errors.js:47:9)
             at ChildProcess.p.on
        (C:\Users\jstair\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-framework\utils\shell.js:99:33)
             at emitTwo (events.js:106:13)
             at ChildProcess.emit (events.js:191:7)
             at ChildProcess.cp.emit
        (C:\Users\jstair\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:40:29)
             at maybeClose (internal/child_process.js:877:16)
             at Socket.<anonymous> (internal/child_process.js:334:11)
             at emitOne (events.js:96:13)
             at Socket.emit (events.js:188:7)
net.js:655
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:655:11)
    at process.<anonymous> (C:\Users\jstair\AppData\Roaming\npm\node_modules\ionic\bin\ionic:9:63)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:56:22)
    at process._tickCallback (internal/process/next_tick.js:104:7)
```

**Comment by bobtheowl** [comment]
@kurtiev 
Good eye! Not sure how that disappeared after months of development.
`npm install -g cordova` did the trick.

**Comment by dwieeb** [comment]
@bobtheowl Apologies for the horrible error message. The code in CLI 4.1.1 (just released) should have a much better error message when Cordova CLI is missing.

**Comment by arcreative** [comment]
Looking forward to the day when I don't have to spend 2 hours troubleshooting things when I just want to build the same project I've always been building.  Sorry to rant, but this tool is an absolute nightmare  every time I use it.

**Comment by lasithds** [comment]
In my case **cordova-fetch** was trying to download _cordova-ios@0.0.1_. I check the **package.json** file which had listed _"ios": "0.0.01"_. Removed this line and installed the platform and it worked like a charm.

Hope this helps

**Comment by dwieeb** [comment]
Original issue has been fixed, so I'm closing this.
