### ISSUE TITLE
Option to not use lazy loading

### ISSUE THREAD

**Issue by mswilson4040** [ionic-team/ionic-cli#3490]
Currently when generating a new ionic angular app, it forces you to use lazy loading. When starting a new ionic angular project, you should have to option to not use lazy loading.

Maybe something like:

`ionic start myApp tabs --type=angular --lazy=false`

or better yet

`ionic start myApp tabs --type=angular --lazy=true`

I think the second option is more friendly towards angular developers who are used to the framework. When you go to generate a new angular app with their CLI, it does not default to lazy loading.

**Comment by dwieeb** [comment]
Agreed!

**Comment by mswilson4040** [comment]
@dwieeb any updates on this one? I kind of want to just kill the angular project that's generated by ionic and then just do an `ng new ...` within the ionic directory (to generate an angular project that isn't lazy loading). But, it's hard for me to tell how ionic-cli is actually using angular-cli since all the commands seem to be wrapped by ionic. Not to mention there seems to be quite a bit of ionic 'stuff' sprinkled within the angular project so I don't think just simply killing the angular stuff will suffice. It'd be nice if this was implemented as it's the primary thing that's holding me back with using ionic to build out our app.

**Comment by dwieeb** [comment]
Do whatever you need to do. Ionic 4 is in early beta, so we're trying to figure out the best way to sprinkle the Ionic stuff on top.

**Comment by dwieeb** [comment]
I'm going to merge this issue into an issue with a broader scope: https://github.com/ionic-team/ionic-cli/issues/3499

**Comment by mswilson4040** [comment]
Perfect, thanks @dwieeb!
