### ISSUE TITLE
Console logs don't appear with Ionic 3 projects and CLI v4

### ISSUE THREAD

**Issue by Borongaj** [ionic-team/ionic-cli#3501]
**Description:**
Console logs (and errors) don't appear with Ionic 3 projects and CLI v4

**Steps to Reproduce:**
Add `console.log('test');` in the component .TS file.
Run `ionic cordova emulate ios -l` (or `ionic cordova run ios -l`) in terminal

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)  : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.4.0, ios 4.5.4

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.0.0
   NodeJS     : v8.11.3 (/usr/local/bin/node)
   npm        : 6.2.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Comment by rdlabo** [comment]
@Borongaj Where did you confirm? (in Safari? or in Xcode?

**Comment by Borongaj** [comment]
Terminal

**Comment by rdlabo** [comment]
@Borongaj  maybe, this article help you.
https://geeklearning.io/apache-cordova-and-remote-debugging-on-ios/

**Comment by Borongaj** [comment]
I've just check with Ionic CLI v3.20.0 and console logs are shown.

**Comment by dwieeb** [comment]
@Borongaj Sorry it took a while to respond. It looks like you're not using the `-c` flag. See `ionic cordova run --help` for the list of options.

This works for me:

```
ionic cordova run ios -lc
```

**Comment by Borongaj** [comment]
If you install Ionic 3.20.0, you can access to  the`-c` option, but not with Ionic 4.0.6.

**Comment by dwieeb** [comment]
I see it in the help output. And the option works for me.

![image](https://user-images.githubusercontent.com/236501/43975961-e1ffef9e-9ca4-11e8-9f80-e566c7a76e89.png)

**Comment by dwieeb** [comment]
Am I missing something? With Ionic CLI 4.0.6 and an `ionic-angular` (v3) project, everything works as expected.

**Comment by dwieeb** [comment]
Oh! Yeah. The help output is different depending on which type of project you're in. For example, the `-c` option doesn't work for v4 projects yet (and can be tracked here: https://github.com/ionic-team/ionic-cli/issues/3169).
