### ISSUE TITLE
Log DEBUG for subprocesses

### ISSUE THREAD

**Issue by CheetahDev** [ionic-team/ionic-cli#3502]
**Description:**
Since we moved to Ionic CLI v4+, running `ionic serve --verbose` enables DEBUG logs for all subprocesses. As our projects (v1) run eslint tasks in realtime, using Ionic CLI v4+ and `ionic serve --verbose` command is unmanageable (too many outputs, server doesn't start)

**Steps to Reproduce:**
* Use a v1 project with several views, controllers, services...
* Add an eslint gulp task (.eslintrc > "extends": "eslint:recommended")
* Add this task to the "default" task
* Add the "default" task to the "ionic:serve:before" task
* `ionic serve --verbose`

**Output:**
Please see https://imgur.com/a/8O0rcys

**My `ionic info`:**
```
Ionic:

   ionic (Ionic CLI) : 4.0.5 (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   NodeJS : v8.9.4 (C:\dev\tools\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 7

Environment:

   ANDROID_HOME : not set
```

**Other Information:**
Related #3390

**Comment by dwieeb** [comment]
Hi @CheetahDev. Thanks for the issue. At this time we won't be changing the functionality here. `--verbose` is meant to be a convenience flag to obtain as many logs from as many processes as possible.

To fine-tune logging, please see the docs for the [debug](https://github.com/visionmedia/debug) module.
