### ISSUE TITLE
Appium automatically disconnects when running columns

### ISSUE THREAD

**Issue by zzjia** [ionic-team/ionic-cli#3504]
**Description:**

Appium automatically disconnects when running columns

**Steps to Reproduce:**

info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"49"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"49"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: click
info: [debug] Logcat terminated with code 0, signal null
info: [debug] UiAutomator exited
info: [debug] executing cmd: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 8e9a2086 shell "echo 'ping'"
info: error sending command, reconnecting device and retrying: shell "echo 'ping'"
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 8e9a2086 devices
info: [debug] 0 device(s) connected
info: [debug] Could not find devices, restarting adb server...
info: [debug] executing cmd: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 8e9a2086 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 8e9a2086 devices
info: [debug] 1 device(s) connected
info: [debug] executing cmd: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 8e9a2086 "shell \"echo 'ping'\""
info: [debug] Error: Command failed: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 8e9a2086 "shell \"echo 'ping'\""

**Output:**

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

**Comment by dwieeb** [comment]
@zzjia We aren't appium. Try this: https://github.com/appium/appium/issues

**Comment by dwieeb** [comment]
If this is an issue with the Ionic CLI, please fully fill out the issue template.
