### ISSUE TITLE
@ionic/cli-framework@0.1.3 not found when installing ionic@3.20.0

### ISSUE THREAD

**Issue by vruello** [ionic-team/ionic-cli#3532]
**Description:**

I'm using ionic@3.20.0 for my app. When trying to set up my development environment on a new laptop and then installing ionic on it, I get `404 Not Found: @ionic/cli-framework@0.1.3` error. 

**Steps to Reproduce:**

Run `npm install -g ionic@3.20.0`.

**Output:**

In verbose mode, I get the following output: 
```
admin$ npm install -g ionic@3.20.0 --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'ionic@3.20.0',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v8.11.4
npm verb npm-session 95fe9d9f4b6b387e
npm http fetch GET 200 https://registry.npmjs.org/ionic 79ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/chalk 133ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/opn 134ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/semver 136ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/tslib 145ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/@ionic%2fcli-utils 239ms (from cache)
npm http fetch GET 404 https://registry.npmjs.org/@ionic%2fcli-framework 1761ms
npm verb stack Error: 404 Not Found: @ionic/cli-framework@0.1.3
npm verb stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:810:20)
npm verb stack     at tryOnImmediate (timers.js:768:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
npm verb cwd ---
npm verb Darwin 17.5.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic@3.20.0" "--verbose"
npm verb node v8.11.4
npm verb npm  v5.6.0
npm ERR! code E404
npm ERR! 404 Not Found: @ionic/cli-framework@0.1.3
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2018-08-21T09_37_31_005Z-debug.log
```

**Comment by dwieeb** [comment]
I'm guessing you're being a proxy or are using a custom npm registry.

If not, what's the output of `npm info @ionic/cli-framework time`?

**Comment by dwieeb** [comment]
@vruello Is there a reason you're not using the latest CLI version?

**Comment by vruello** [comment]
Hi! Thanks for you answer!

I have resolved the issue by downloading version 3.9.2 (`npm install ionic @ 3.9.2`).

It's true that I was logged in on a custom npm registry, but it seems that npm was using the official one (`npm http fetch GET 404 https://registry.npmjs.org/@ionic%2fcli-framework 1761ms`).

> @vruello Is there a reason you're not using the latest CLI version?

I don't want to upgrade on version 4 for now. I've two reasons for that:
- I don't want to lose NavController :'(
- My codebase is shared with an angular 5 web app. For now it works and I fear to break this (for example with the upgrade of rxjs or of another dependency).

Btw if I've missed something, feel free to correct me.

**Comment by dwieeb** [comment]
CLI version !== Framework version 

You can use CLI 4 with Ionic 3 apps, and even Ionic 1 apps.

**Comment by dwieeb** [comment]
I don't know why npm isn't able to resolve that package, but it seems like an issue with npm, not the Ionic CLI. Try updating npm: `npm i -g npm`. Try cleaning npm cache: `npm cache clean -f`

**Comment by vruello** [comment]
> CLI version !== Framework version

I didn't know that! Thanks for the tip! 

npm was already up to date (I just installed it) and I had already tried the `npm cache clean -f` command.

I'll try 3.20.0 again tomorrow on another computer (this one is ok with 3.9.2) and I'll share the results here. Then, I'll upgrade to 4.1.0 👍

**Comment by vruello** [comment]
>CLI version !== Framework version

I just saw that it's written in big letters in the README of the repository. I'm getting blind 😢
