### ISSUE TITLE
ionic cordova resources failure

### ISSUE THREAD

**Issue by hwlcode** [ionic-team/ionic-cli#3533]
**Description:**

sudo ionic cordova resources

**Steps to Reproduce:**

**Output:**

✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations: 2 / 2 complete - done!
[ERROR] Encountered 50 error(s) during image transforms:

        1): Error: Error while generating drawable-ldpi-icon.png: the server marked a source image as invalid for this
        resource.

        Server: "Request: POST https://res.ionic.io/api/v1/transform
        Response: 403
        Body:
        '\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003�X[o�D\u0014~�_15\u0012���l[���F�\u0004���D+��j5kϮ\'�g�gv��"mB�\u001aH��\u0014z!�\r(%\\���Jöi~\f�w��\u0001�/\u001b�:\t�(yZ�s�oΜ��L�#o�w��G�O\u0003�;�^P���9\\\u00056\u0007����y\u001d��\u0001\f\u001b2�I��3\f`t\u0002P��H\u00026$5MBD>���\u0003��9DL\\=/˻P\t\u000e\u0000{CM�\u0018��\u0001P�/\u0000U�\t�0��<�,\u000f#Y\b�zA��H\u000f6��ō�Vxo�\b�\fto?\u000b:\u000f�ε����=U��\n��8\u0004�\u0005=��&�=�<)\u0001%uX��2���\u001b�t�\u0012�\b��̹H\u0002F��I\u001c]�{r\u0000s\u0010ʇ�ٷ�S�q!�\u0015;\u000btzZ�6kh̰<�
        ��\u0001
        �A���\n�,3�PLLta\f\u0010Z��M��!\r��.�xfP\u0013���L��\u0006���1L0�Ж�\u0001m���\u001cx\u0001;u\'��QmLf��lMb|�F�B�K\u0000��47�ʱM6\u0018��塪&)�Id���إT
        6�E�y�c�(�Ϲ(�_��
        \u0013CMb��\u0010\u0019s=:�\f�)��\u001fR�\u001b���\t��!�����a8a�ⴆ+0B\u001d\u001d�W�9��\u0003�\u001a&S�\']h��Ԧ�?Wc\u0016z��Q\u0001\u0012�+�\':P��a�g!g`\u0003�V\t0�Ȯ)�2�\u0013�rZt0)�0IW\u0013��\u0017�˜4ΤA\u001d��ۼ��R�G\n6\u001d�Ջ\u0003HŠ��kbw��㥉�xi<�Q�L\n\u0005UI\u001a�Ȼ^\u0000@5q#�S��A�E�$\u001c�+�2�\u000bm�q0�%G�\u0011}\u001b��b\u0014\u001b�O,Q�\u0004Lȡ�=H�\r9\u0012m\nVlT�����ڏåo�����wkAUL���H)Fs�&�\u0010�B��<#K�/&�G�EJ��1\bm
        O4��h��K�e\u0018\u0016�mDj�,\u0010lL��\u0007+�\u0006�7��V�p]U�R\u0016�h�\u0000�WvG�̅$�O\u001d�F\u001c�\u00192ʆ��YI�=�&X\\����k�w��?�\u001c���\'�ᣕ�ϗTE\u0000��C��)�F\u0011SU��\u000e�\u0010eU\u0014\u001dP�ɲ���;I,�r�$\\�l\\��\n0��\r\u000bʢqBL2��7ՙ�|�A�C\u0018�M:\u0014�_�HP>l@WƤ�<�"�U�92�ИEf\u000e\u0002\u0000U�S���F���\u001e��(?\u0019�ۊa͖����-jjR\r�h���=ҩE\u0003IJ%B!�s�-����9M:~�4��\'�cpܜ��NJ\u0000�9b�\u001dA�ЄL*�tO+��:Л\u001dRW�Ĥ����͝���p���ڣ��\u001f��q-\u0006�7���ރ��F;\\�\u00176�\u0007ф��F\u0004���^P\u0015��A\u001d\u000e�c�\t��^F��g\u0016�(߳��|�DR��\u0010�A�Z����0�/lԐh5Շ\u0010�#��G�yX��zX�\u001ej\u000fD\u000b\u001cmrMk.�K���[\u001d�I���R\\B#]�͸�\rc�\u0007B��B�����+��u9��\u000eW;��\r��y�t9�\f�^I\u001a읅��qiw��u�\u001d�Rn~�\n/#-\u001eb�n�=R\u0013<X����\u0004���?�w�T��A�q\u0003{u\u0016�?��\u0014l�tolt��;��G���\u0006����uo{;��\n��{�m�ɟ"A;��֖�ō���¥�\u0015�H�\u001fk�꒿�0l_Os��\b�M����\u0005��\u000b���z��bG��v7׺W�\f���w6Ç?�\u0017/w�7�����_���{��ҳ��Ű}=��\u001ev�{~\u000eI,U�\u0001�\u0012UJyr�ȪKM�͵�8^�\u001c9�>x���\u0006"\u001c�~{\n��{����&/n̑#ہ��gȅ\u001e�ԓ�W+u�>y�A1�ȫ����w.�~?\u00197\u0005J��ţ�N\u0014K�N\u0014\'^?\f��\u0000���x<�)E\u0019�\u0011[�v�\u0012�������2�����R|���+�}eqӖ\u0000�^M�n�\u0015\u001b\u0012Qq[��W��[\u000f��/T\u0005����.ed%�\u000b�Nf0d�}��\u001e�Y�Qy\u000f\u0015�PUF�[\u0018-�Wr�����\u0005���D\u0005\u0007_o\u0004B\u0013\u0013�6�e�\bM�/d��O??Y�����-��*�;EU����\u0003�Ӊ\u0014\u0002\u0012\u0000\u0000'"

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 5.2.2, ios 4.2.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 4 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v8.9.0 (/usr/local/bin/node)
   npm        : 6.1.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Other Information:**

**Comment by dwieeb** [comment]
> `the server marked a source image as invalid for this resource.`

What are your source images?

**Comment by hwlcode** [comment]
my source images is resources/icon.png(1024*1024, png-8) and resources/splash.png(2732*2732, png-8)

**Comment by hwlcode** [comment]
I try "sudo ionic cordova resources" just a minute ago, and now is ok, I think maybe the problem is the server last night. No matter what it is, thank you focus on my issue.
