### ISSUE TITLE
Possibility to skip resource building?

### ISSUE THREAD

**Issue by mpateck** [ionic-team/ionic-cli#3535]
Hi there, 

i happens so many times, that 'ionic cordova platform add xxx" fails with an unnamed exception. 
I could pin down the problem, and its the ionic cordova resources command. 
Since my apps always have the newest resources checked in, there is no need to update them. 
So i want to skip this process.
Is there any chance to do so?

Thanks

**Comment by dwieeb** [comment]
`ionic cordova platform add <platform> --no-resources`

see `ionic cordova platform add --help`
