### ISSUE TITLE
ionic serve doesn't support cordova browser plugins

### ISSUE THREAD

**Issue by Xeoncross** [ionic-team/ionic-cli#354]
Some (but not all) cordova plugins have Javascript proxies if the features they offer can also be used in a regular browser.

I'm using one such plugin and I need to access the `cordova.plugins.____` object. However, the cordova.js file is a 404 when using `ionic serve`. It's not a 404 when using `ionic build browser`.

How do you access the cordova object in javascript when using ionic serve? Or do you have to `ionic build browser` every single time you want to see your changes?

**Comment by AlexYankee** [comment]
Create stubbed version of service:
```javascript
Geo.service('Geolocation', function ($q){
  this.getCurrentLocation = function (){
    var d;
    if(window.cordova){
      d = $q.defer();
      navigator.geolocation.getCurrentPosition(function (position){
        d.resolve({
          lat: position.coords.latitude,
          lng: position.coords.longitude
        });
      }, function (){
        d.resolve(DEFAULT_LOCATION);
      }, {frequency:5000, maximumAge: 0, timeout: 5000});

      return d.promise;
    }

    return $q.when(DEFAULT_LOCATION);
  };
});
```

Make sure everything works fine in browser, run your app in live mode on emulator like
```bash
$ ionic emulate android -l -c -s
```
Use safari for iOS or Chrome for Android to debug app running on the device.

**Comment by Xeoncross** [comment]
That is certainly a solution for skipping certain features when not on a mobile device - but what if the cordova plugin contains code for a browser version as well? Then you still have to access it via `cordova.plugins` and the only way it seems to get that `cordova.js/cordova_plugins.js` code is to run `ionic build browser`.

Is there no way to develop without having to rebuild all the time?

**Comment by Xeoncross** [comment]
At the moment I'm trying to work around this by using the gulp file to process everything for me. I'm still surprised that you can't use a cordova plugin while developing in browser.

First I manually pulled the `./plugins/name/www/*.js` out and placed them inside `./www/pluginname`. This allows me to modify them as I work and `ionic serve` picks them up. From here, gulp takes over.


  gulp.task('plugin-overwrite', function() {

    // Step 1: Move the edited files back into the plugin folder
    gulp.src('./www/plugin/file.js')
      .pipe(gulp.dest('./plugins/com.plugin/src/browser/'));

    // Step 2: Build the project
    if (sh.exec('ionic build browser').code !== 0) {
      console.log('Failed to build for browser');
      process.exit(1);
    }

    // Step 3: Move built files back into webroot
    gulp.src(['./platforms/browser/www/cordova.js', './platforms/browser/www/cordova_plugins.js'])
      .pipe(gulp.dest('./www/build/'));

    gulp.src('./platforms/browser/www/plugins')
      .pipe(gulp.dest('./www/build/'));
  });

If anyone has any better ideas please let me know.

**Comment by aleclofabbro** [comment]
any news about it?

**Comment by orioniota** [comment]
any news about it? X2

**Comment by lrettig** [comment]
Hello,

I'm new to ionic and it's been a wonderful experience except for the fact that I lost several hours completely stuck thanks to this issue. The 'ionic serve' experience is great and it's not at all obvious that you don't have access to cordova plugins, nor to 'cordova' itself, in this environment.

Any news (X3) on fixing this? It has caused headaches for lots of people already (cf. https://github.com/Wizcorp/phonegap-facebook-plugin/issues/866, https://github.com/driftyco/ng-cordova/issues/446, http://stackoverflow.com/questions/27906239/facebookconnectplugin-is-not-defined-ngcordova-ionic-app, etc.) and fixing it will be critical to maintaining the otherwise high quality of the ionic experience.

Thank you.

**Comment by manucorporat** [comment]
any news about it? X4

**Comment by mark-veenstra** [comment]
+1

**Comment by Screeze** [comment]
+1

**Comment by liamzebedee** [comment]
+1

**Comment by mark-veenstra** [comment]
At this moment we solved this issue by generating a Gulp command that serves the `platforms/browser/www` directory. You should manually build for browser each time you make a change (`ionic build browser`):

```javascript
gulp.task('browser:serve', function() {
    gulp.src(paths.browser)
        .pipe(webserver({
            livereload: {enable: true, port: 35729},
            directoryListing: false,
            host: localhost,
            port: 8100,
            open: true
        }));
});
```

**Comment by derekdata** [comment]
+1

**Comment by fiunchinho** [comment]
+1

**Comment by sebastianovide** [comment]
+1

**Comment by sebastianovide** [comment]
workaround in https://github.com/driftyco/ionic-cli/issues/790

**Comment by dcanlas** [comment]
Having similar problems when using phonegap-facebook-plugin. Would also like to know if possible to resolve this when doing 'ionic serve'

**Comment by xinbenlv** [comment]
+1

**Comment by crazedcoding** [comment]
+1

**Comment by wow3065** [comment]
+1

**Comment by lordlothar99** [comment]
+1

**Comment by movrack** [comment]
+1

**Comment by schaergeek** [comment]
+1

**Comment by barlos23** [comment]
+1

**Comment by virtualit786** [comment]
+1

**Comment by renanbs** [comment]
+1

**Comment by valix85** [comment]
+1

**Comment by TheNuclearCat** [comment]
+1

**Comment by selvagsz** [comment]
Facing the same issue with `ionic serve`. Hope this gets resolved soon. `ionic run browser` works for me though

**Comment by vassallocarlo** [comment]
+ 1

**Comment by BradyLiles** [comment]
+1
I'm experiencing this issue as well, and it really sucks that `ionic run browser --livereload` does not work either.. 
Is there anyone on the Ionic team that is looking into this?? I haven't seen anyone from them comment on this yet.

**Comment by joshuaohana** [comment]
Throwing another +1 onto the heap

**Comment by marcusgraf** [comment]
+1

**Comment by rubimazaki** [comment]
This is really horrible... can you at least throw some log that that's the problem? 
Wasted a whole day on this...

**Comment by morrisonbrett** [comment]
If I do a `ionic build browser`, I noticed that the cordova.js and it's dependencies get built to `/platforms/browser/cordova/platform_www`.  The question is (maybe), how do we get that output via WebPack to get generated to /www?  Would LOVE to know the answer to that.

**Comment by rubimazaki** [comment]
as mark-veenstra already wrote - but let me fix the port from 8100 -> 8000 which is the port the "ionic run browser" works:

add this to your gulp file under the other tasks:

```
gulp.task('browser:serve', function() {
    gulp.src(paths.browser)
        .pipe(webserver({
            livereload: {enable: true, port: 35729},
            directoryListing: false,
            host: localhost,
            port: 8000,
            open: true
        }));
});
```

**Comment by LordPrettyFlacko** [comment]
ionic run browser --live-reload throws `Error loading cordova-browser` for me. Does anybody knows something about this

**Comment by joshuaohana** [comment]
@LordPrettyFlacko I get that as well but am able to build and serve for browser (pulling in all js and hooks) with `ionic build browser --desktop --testing && http-server platforms/browser/www/`

**Comment by LordPrettyFlacko** [comment]
@joshuaohana i tried this but my system cant find the http-server command. However it works for me now with ionic serve browser. I dont know why cause i tried so much thing but in the end it works.

**Comment by BradyLiles** [comment]
What I have actually done for a hacky workaround for the time being is just do an ionic build browser and then I copy the `platform_www` folder from the `platforms/browser` directory into my `www` folder and then I reference it inside my index.html with `<script src="platform_www/cordova.js"></script>`. After doing that my ionic serve will then load all my cordova browser plugins.. (Works 90% of the time, i usually just refresh my page if the plugins don't load on initial startup.)

**Comment by dgofman** [comment]
By using "ionic run browser --livereload" command I can see the trigger is active:
"HTML changed: www\index.html"

however we need to run a command to compile our changes:

**cordova prepare browser**

I hope someone can fix it ASAP.

**Comment by danielehrhardt** [comment]
+1 Same here

**Comment by petermetz** [comment]
After inspecting my **node_modules/@ionic/app-scripts/dist/serve.js**
 I've managed to come up with this change in the package.json's npm script for ionic:serve =>
```"ionic:serve": "ionic-app-scripts serve --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build"```

This makes my ionic serve use the browser platform as it's basis and all the good stuff is there provided by serve out of the box (all that I need anyway, didn't check everything).

My only issue at present is kind of unrelated, the splash screen plugin requests ```img/logo.png``` while this doesn't seem to exist under my root www of ```platforms/browser/www/```.

My logo.png is in the src/assets directory, it would be cool if that got copied over but this may very well be a splash screen plugin issue instead of something to be done on ionic's side.

**Comment by meirotstein** [comment]
At the meantime you can use the following in order to use cordova contacts plugin in ionic serve:
https://github.com/meirotstein/cordova-plugin-contacts-mock

**Comment by morrisonbrett** [comment]
@petermetz That is a GREAT solution. Working perfectly for me. Thank you!

Slight mod - I like having source maps built:

`"ionic:serve": "ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build"`

**Comment by stovmascript** [comment]
@petermetz Epic solution, thank you!

To the unrelated issue `img/logo.png` 404, I solved it by customizing the [ionic-app-scripts/config/copy.config.js](https://github.com/driftyco/ionic-app-scripts/blob/master/config/copy.config.js). You can provide your own `copy.config.js`:

```js
// <projectRoot>/copy.config.js
const defaultConfig = require('@ionic/app-scripts/config/copy.config');

module.exports = Object.assign({}, defaultConfig, {
	copyLogo: {
		src: 'platforms/browser/img/logo.png',
		dest: '{{WWW}}/img',
	},
});
```

So in your case, should be able to use `{{SRC}}/assets/logo.png` as the `src`.

If you're not already using and extended config like this, note that you also have to add:

```js
// ...
  "config": {
    "ionic_copy": "copy.config.js"
  }
// ...
```

to your `package.json` and it works properly from `@ionic/app-scripts": "^0.0.48` - other configs work, but a bug specific to copy.config was fixed in this version.

**Comment by pakbaz** [comment]
@petermetz your solution won't work when using azure mobile client plugin

**Comment by nharrer** [comment]
With ionic 4 this can be done with:

```
$ ionic cordova build browser
$ ionic serve --cordova --platform browser
```

see: https://github.com/ionic-team/ionic-cli/issues/3043

**Comment by dwieeb** [comment]
Yeah, I think we can close this issue. I think the original request is now fulfilled.

https://github.com/ionic-team/ionic-cli/issues/3043 is for a related feature request.
