### ISSUE TITLE
Can't host build output in subfolder

### ISSUE THREAD

**Issue by moldstadt** [ionic-team/ionic-cli#3555]
**Description:**

When building an ionic v3 project with `ionic build --prod`, I was able to copy the www folder to a subfolder on my server to host it.  With ionic v4 project this is not possible as it must sit in the root.

Similarly, I am not able to open the local `index.html` file on my computer to test it before uploading to the server, as I used to be in the past.

**Steps to Reproduce:**

```
ionic start test blank --type=angular
ionic build --prod
```
Try open `www/index.html` in browser.

**Output:**

**My `ionic info`:**

```
$ ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.1 (C:\Users\Brent.SST\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 8.1
```

**Other Information:**

See discussion here: https://forum.ionicframework.com/t/ionic-build-generates-a-blank-page/140366

**Comment by danieldugger** [comment]
Ran into this issue and learned that the base href must be set.

I have seen different answers as to how to resolve it. I went with /subdirectory/ and it worked. I have see that ./ also works.

If you are using IIS, you will have to configure an URL rewrite rule

**Comment by danieldugger** [comment]
FYI, I also had to address the base href within manifest.json

**Comment by stevencxr** [comment]
> FYI, I also had to address the base href within manifest.json

I build it with  ionic build --prod --  --base-href "/sub/"

it worked without updating ./ in the manifest

**Comment by derrickxiang** [comment]
Hi, I ran into the same issue, but I'm using Ionic React, I tried build with --base-href "/sub/" but it doesn't work for me, also tried change manifest also not working. 
while I saw there is message like below in the build output:

 `The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.
`
Is this "homepage" the right way to go?
I then tried add one entry like below in package.json and still no help.

`"homepage": "/sub/"`

I'm hosting my web app on IIS. Any help is appreciated.

**Comment by danieldugger** [comment]
I had to use the URL rewrite within IIS to get mine working. Don’t know if React requires that or not


Daniel Brittain Dugger
Founder
Bail Bond Software Solutions
615.405.4589 mobile
866.201.5079 toll-free

________________________________

**Comment by derrickxiang** [comment]
Hi Daniel, 
Thanks for the reply, I never use URL rewrite module in IIS before, can you share some sample rewrite rules?  thanks.

**Comment by danieldugger** [comment]
I don’t know if they will be the same for React. I did a Google Search.


Daniel Brittain Dugger
Founder
Bail Bond Software Solutions
615.405.4589 mobile
866.201.5079 toll-free

________________________________
