### ISSUE TITLE
Link an existing app on Ionic Pro

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-cli#3570]
![image](https://user-images.githubusercontent.com/5757359/45240485-87ccab80-b2f1-11e8-9145-1591c39eff2e.png)

I think this is because I was logged in to the old ionic pro, maybe, or because I changed my password.
This should run `ionic logout` and prompt `ionic login`

**Comment by dwieeb** [comment]
Thanks, we can certainly do a better job here handling an invalid session. 👍
