### ISSUE TITLE
Create Ionic project from Angular app

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ionic-team/ionic-cli#3583]
As Ionic (4) app seem to be even more similar to an Angular (6) app structure, would it be possible to integrate a project "transformer" command into the Ionic CLI?

I imagine it could be very helpful if one could generate an Ionic project just through a command that uses the source of an Angular app.

**Comment by dwieeb** [comment]
Yeah, this is the `ng add` stuff.

**Comment by dwieeb** [comment]
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3369

**Comment by andreas-aeschlimann** [comment]
Great, thank you!
