### ISSUE TITLE
Do not regularly prompt users to update to a major release

### ISSUE THREAD

**Issue by jayvdb** [ionic-team/ionic-cli#3594]
If I choose to not update, the update prompt should not re-appear regularly.

This is especially important for a *MAJOR* release, which with semver means stuff will break on doing that update.  Worse, the default to this prompt is Yes, so if the user presses enter, intentionally or accidentally without thinking about the repercussions, the CLI has just broken the app.

With a large dev team, and/or apps in production, the option to upgrade is not available to each developer to do on a whim of a CLI tool.

And devs should not need to add `--no-interactive` to every command to ensure that the command actually does what was requested instead of doing nothing.  "run command and go get coffee" is a fairly common workflow, and it is unproductive if they return to find the command did nothing while they were at the water cooler.

This sort of follows on from https://github.com/ionic-team/ionic-cli/issues/2517 which doesnt appear to have resolved the problem.

**Comment by dwieeb** [comment]
@jayvdb I can make a release of CLI v3 in which the update prompt is simply removed.

**Comment by jayvdb** [comment]
I am quite ok with having patch and minor level update notifications, but truly would like to be able to turn that off too, as I have a package manager which does that quite well.  But that is a personal choice, and I understand a CLI tool is most needed by the newbies and quickly init-ing a project.

But default yes to major upgrades is problematic, and will bite newbies the most.

Disabling all notifications in CLI v3 bumps the problem down the road.  It will happen again when v5 comes out.

Cant the notifier tool be told which semver level to report updates from?

**Comment by dwieeb** [comment]
Actually, this may not even work because I believe it just checks the latest version via `latest` dist-tag, so 4.x will always be shown in the prompt. So, I'm not sure this can ever be fixed for v3.

The prompt was probably overall not a net positive thing, despite many people saying they liked it. This is why in CLI v4 we just use `update-notifier` to print a box detailing the latest version. It's the same tool `npm` uses. It also shows **major** in red if it's a major upgrade. 

I think I'm going to close this. It can't be fixed for existing CLI v3 installations and CLI v4 uses a notification vs automatic update prompt.

**Comment by jayvdb** [comment]
Well it could be removed in v3, or updated to use `update-notifier` like v4.
This is still a valid issue for v3, and shouldnt be closed.
If I have direction on what solution would be accepted, I would provide a PR for it, as this prompt is a serious problem and the company I work for isnt going to be leaping to v4 in the immediate future, as we have only just got v3 working satisfactorily, and only a little resources allocated to investigate v4.

**Comment by dwieeb** [comment]
Sure, it could be fixed for those that manually install CLI v3, e.g. `npm i -g ionic@3`. But with the way the update prompt

**Comment by dwieeb** [comment]
Okay, `3.20.1` is published with the prompts removed.
