### ISSUE TITLE
`ionic repair` command

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3596]
We are seeing some project issues clear up when the following commands are executed:

```
rm -rf platforms/ plugins/
cordova prepare
rm -rf node_modules package-lock.json
npm install
```

We can provide a command for this: `ionic repair` (or maybe part of `ionic doctor`)

**Comment by janpio** [comment]
Interesting. Examples for problems this solves?

**Comment by dwieeb** [comment]
The reset appears to fix unknown weirdness with local npm/cordova installations. It's just a shortcut because I know I do this frequently enough myself

- https://github.com/ionic-team/ionic-cli/issues/3301#issuecomment-402259535
- https://github.com/ionic-team/ionic-cli/issues/3462#issuecomment-409675597
- https://github.com/ionic-team/ionic-cli/issues/3399#issuecomment-409279484
