### ISSUE TITLE
Add prompt about Ionic 4 to `ionic start`

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3597]
Ionic 4 beta is pretty stable now, so to promote it a bit more we can add a prompt to `ionic start` asking if the dev would like to give it a try.

**Comment by ClickerTech** [comment]
hi,

i have tried but it is not promoting for Ionic 4?

`C:\Users\Asus>ionic info
√ Gathering environment info - done!
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.1.2

System:

   NodeJS : v8.12.0
   npm    : 6.4.1
   OS     : Windows 10


C:\Users\Asus>


`

Thanks

**Comment by dwieeb** [comment]
@ClickerTech This will be in Ionic CLI 4.2.0.
