### ISSUE TITLE
My Ionic 4app cant deploy

### ISSUE THREAD

**Issue by stones4semper** [ionic-team/ionic-cli#3617]
Pls, an trying to deploy my ionic 4 app to apk but i cant find the apk, their is no build directory

below is what i got in the terminal

C:\xampp\htdocs\HoleeSheet>ionic cordova platform add android
> cordova platform add android --save

You have been opted out of telemetry. To change this, run: cordova telemetry on.

Using cordova-fetch for cordova-android@~7.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.ionic.starter
        Name: HoleeSheet
        Activity: MainActivity
        Android target: android-26
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.0.0
Android Studio project detected
Android Studio project detected
Installing "cordova-plugin-camera" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-file" for android

The Android Persistent storage location now defaults to "Internal". Please check
 this plugin's README to see if your application needs any changes in its config
.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "Android
PersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />
"

to config.xml in order for the application to find previously stored files.

Installing "cordova-plugin-file-transfer" for android
Plugin dependency "cordova-plugin-file@6.0.1" already fetched, using that versio
n.
Dependent plugin "cordova-plugin-file" already installed on android.
Installing "cordova-plugin-filepath" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-ionic-keyboard" for android
Installing "cordova-plugin-ionic-webview" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-splashscreen" for android
Installing "cordova-plugin-statusbar" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android gr
eater than 4.0. If you have a previous platform version, you do *not* need this
plugin since the whitelist will be built in.

--save flag or autosave detected
Saving android@~7.0.0 into config.xml file ...
> ionic cordova resources android --force
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
√ Uploading source images to prepare for transformations: 2 / 2 complete - done!

√ Generating platform resources: 18 / 18 complete - done!
√ Modifying config.xml to add new image resources - done!

C:\xampp\htdocs\HoleeSheet>

pls what did i miss

**Comment by dwieeb** [comment]
Can you run `ionic cordova resources` ?

**Comment by dwieeb** [comment]
The build didn't actually happen. The command stopped early.

**Comment by dwieeb** [comment]
Oops, I misread your original command. You ran `ionic cordova platform add android`, not `ionic cordova build android`.

**Comment by stones4semper** [comment]
Thanks
