### ISSUE TITLE
Im having error 183 when installing vue in centos 7

### ISSUE THREAD

**Issue by ebtesamcs** [ionic-team/ionic-cli#3639]
[eb@localhost ~]$ vue init webpack /var/www/bsmdmn.com/public_html

? Target directory exists. Continue? Yes
? Project name itcproject
? Project description A Vue.js project
? Author Ebtisam
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Standard
? Set up unit tests Yes
? Pick a test runner jest
? Setup e2e tests with Nightwatch? Yes
? Should we run `npm install` for you after the project has been created? (recommended)
 npm

   vue-cli · Generated "/var/www/bsmdmn.com/public_html".

# Installing project dependencies ...
# ========================

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by dwieeb** [comment]
This isn't the repo for the Vue CLI.
