### ISSUE TITLE
ionic doctor: viewport-fit-not-set looking at src/index.html for Ionic 1

### ISSUE THREAD

**Issue by deliverymanager** [ionic-team/ionic-cli#3665]
[ERROR] Error while checking viewport-fit-not-set:
        
        Error: ENOENT: no such file or directory, open 
        .../src/index.html'

ionic 1
cordova: 8.1.1

The problem seems to be the fact that it searches inside /src/index.html
when it should search .../www/index.html

**Comment by deliverymanager** [comment]
Now the ionic doctor check catches the issue but it does not detect it right.
I have the following code in my index.html
`
 <meta name="viewport"
        content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width, viewport-fit=cover">
`
and it still throws error.

**Comment by reajuria** [comment]
The same for me on v4-rc0

Look at [https://github.com/ionic-team/starters/blob/master/angular/base/src/index.html](https://github.com/ionic-team/starters/blob/master/angular/base/src/index.html)

```
    <meta
      name="viewport"
      content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
```

**Comment by dwieeb** [comment]
@reajuria Thanks, we fixed it in the starters... but the regex in `ionic doctor` still may need to be updated to handle newlines. I'd love a PR that fixes that 😄

**Comment by ppmag** [comment]
Looks like regression:

```
$ ionic -v
6.11.11

$ ionic doctor check

⠇ Detecting issues: 8 / 9 complete [ERROR] Error while checking viewport-fit-not-set:
        
        Error: ENOENT: no such file or directory, open 'xxxxxxxxxxxxxx/src/index.html'
✔ Detecting issues: 9 / 9 complete in 12.42ms
```

But, index.html is located as `public/index.html`,  this is result of React 'sidemenu' template.

**Comment by imhoffd** [comment]
@ppmag Care to make a new issue? This looks like a React issue, specifically. (not related to the original fix).

**Comment by jeffcjohnson** [comment]
Issue #4628, while being for Ionic Vue, might work for the React issue.
