### ISSUE TITLE
Ionic Lab - iOS view switches to material design on re-compile

### ISSUE THREAD

**Issue by nickstucko** [ionic-team/ionic-cli#3687]
Everything looks great when you first load up Ionic Lab (except for the known iOS statusbar issue - see #3069), however when you make a change in your code and press save - Ionic Lab recompiles/refreshes and the iOS view now shows the material design version. If you want to get the correct display again, you have to manually refresh the browser. Tested in the latest Firefox & Chrome. Anyone else seeing this behavior?

When Ionic Lab first loads up (looks great!):

![Image of Ionic Lab on first load](https://i.imgur.com/qLfYCAB.png)

After Ionic Lab re-compiles (iOS now shows MD view):

![Image of Ionic Lab after re-compile](https://i.imgur.com/yIHF4CN.png)

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.9.1 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000
```

**Comment by dwieeb** [comment]
This will be fixed at the same time as https://github.com/ionic-team/ionic-cli/issues/3069 (they both have the same root issue).

I'll just keep them together.

**Comment by dwieeb** [comment]
I lied, this is a different issue. 😆 Looking into this...

**Comment by nickstucko** [comment]
You are THE MAN.

**Comment by dwieeb** [comment]
Okay, we need a way to preserve query parameters in the Angular Router. (see https://github.com/angular/angular/issues/12664)

If we could turn this on globally, the configuration would be saved when first supplied by Lab.

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.
