### ISSUE TITLE
Encountering an error when trying to build an android app using ionic 4

### ISSUE THREAD

**Issue by Elvis254** [ionic-team/ionic-cli#3689]
Hi, am encountering a problem when trying to build an android app using ionic 4. The error report am getting is as shown below.

`C:\Users\pc\Documents\Entreida> ionic cordova build android --prod --release
> ng run app:ionic-cordova-build:production --platform=android

Date: 2018-10-15T12:34:00.477Z
Hash: 354a71be8f75d022e15b
Time: 30179ms
chunk {cordova} cordova.24be14f7eb59f2cab434.js (cordova) 24.6 kB  [rendered]
chunk {0} runtime.06daa30a2963fa413676.js (runtime) 1.44 kB [entry] [rendered]
chunk {1} main.9868d9b237c3a48c54da.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.d6b2aab6cf3602290b64.css (styles) 17.4 kB [initial] [rendered]

ERROR in Internal Error: The structure of the program changed during codegen.
[ERROR] An error occurred while running subprocess ng.

        ng run app:ionic-cordova-build:production --platform=android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.`

Please, help me out on how to solve this problem as soon as possible.

Elvis.

**Comment by Elvis254** [comment]
@dwieeb it happens when I try to build using this command `ionic cordova build android --prod --release` I haven't tried using `npx ng build` because its not included in the documentation. Any ideas would really help me solve this problem. As a result I have installed version 3 for now.

**Comment by dwieeb** [comment]
@Elvis254 I'm asking you to run it so we can debug your issue.

**Comment by Elvis254** [comment]
Okay @dwieeb I will try to run it and reply back as soon as possible.

**Comment by hostenvoy** [comment]
I am actually experiencing the same just recently. Any solution yet?

**Comment by dwieeb** [comment]
The error:

> ERROR in Internal Error: The structure of the program changed during codegen.

Is coming from the Angular CLI. Since this is not an Ionic CLI issue, I'm closing this. Here are some existing resources that may help with this issue:
* https://stackoverflow.com/questions/49757021/error-in-internal-error-the-structure-of-the-program-changed-during-codegen
* https://github.com/angular/angular/issues/26780

**Comment by ericdesa** [comment]
in my case, I had to replace the ```--release --prod``` flags by ```--release --aot --minifycss --optimizejs```

```
Ionic:

   ionic (Ionic CLI)             : 4.10.1
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.13.0
   @angular-devkit/schematics    : 7.3.0
   @angular/cli                  : 7.3.0
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.3, (and 5 other plugins)

System:

   Android SDK Tools : 26.0.1 (/opt/android-sdk)
   NodeJS            : v10.15.1 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.9
```
