### ISSUE TITLE
What's are the resizing rules

### ISSUE THREAD

**Issue by Sideral-Inc** [ionic-team/ionic-cli#3692]
Hi,

I use the CLI to generate the splash screens for my app and everything works well.

But in my app, I duplicate the splash screen image so that when I hide the splash, I can still see the same image but with some overlay on it.

But to make sure that both the splash and the duplicate image are the same size, I would like to know what's are the resizing ratio rules that the CLI use to generate all different sizes.

Where could I find those rules?

Thanks

**Comment by dwieeb** [comment]
https://github.com/ionic-team/ionic-cli/blob/6281ec8ae0fa5a198c64700ee4169b0b2d937b1a/packages/ionic/src/lib/integrations/cordova/resources.ts#L232-L327

**Comment by Sideral-Inc** [comment]
Hi,

Sorry, my question maybe wasn't clear enough.

For example, the iPhone X splash screen is 1125x2436 (@3x). So, what is the resizing/cropping rule to go from 2732x2732 to 1125x2436.

**Comment by Sideral-Inc** [comment]
Ok so as my understanding, to generate the iPhone SE splash (640x1136), the script does something like this:

- it first resizes the 2732x2732 file to 1136x1136;
- then it crops the resized result (with origin top/center) to 640x1136.

**Comment by dwieeb** [comment]
Ah, sorry. I misunderstood. Yes, it is a resize then crop. 

We use imagemagick on the server. I can provide the flags we use, if necessary.

**Comment by Sideral-Inc** [comment]
All good, thanks. I can now figured out how to set my CSS.

Thanks a lot.
