### ISSUE TITLE
 An error occurred while running subprocess cordova::

### ISSUE THREAD

**Issue by davidzongo** [ionic-team/ionic-cli#3698]
**Description:**

Error when adding platform 

**Steps to Reproduce:**

1.Create new ionic app without IOs or android
2. Ionic serve  work perfectly
3. run ionic cordova platform add android
You will get error:
this.config.delete is not a function
[ERROR] An error occurred while running subprocess cordova.

4. Then u run with --verbose

**Output:**

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 1 functions +1ms
  ionic:cli-framework:utils:process error while killing process tree for 7576: { Error: Command failed: taskkill /pid 7576 /T /F
  ionic:cli-framework:utils:process ERROR: The process "7576" not found.
  ionic:cli-framework:utils:process
  ionic:cli-framework:utils:process     at ChildProcess.exithandler (child_process.js:276:12)
  ionic:cli-framework:utils:process     at emitTwo (events.js:126:13)
  ionic:cli-framework:utils:process     at ChildProcess.emit (events.js:214:7)
  ionic:cli-framework:utils:process     at maybeClose (internal/child_process.js:915:16)
  ionic:cli-framework:utils:process     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  ionic:cli-framework:utils:process   killed: false,
  ionic:cli-framework:utils:process   code: 128,
  ionic:cli-framework:utils:process   signal: null,
  ionic:cli-framework:utils:process   cmd: 'taskkill /pid 7576 /T /F' } +494ms
  ionic:cli-framework:utils:process onBeforeExit handler: error from function: { Error: Command failed: taskkill /pid 7576 /T /F
  ionic:cli-framework:utils:process ERROR: The process "7576" not found.
  ionic:cli-framework:utils:process
  ionic:cli-framework:utils:process     at ChildProcess.exithandler (child_process.js:276:12)
  ionic:cli-framework:utils:process     at emitTwo (events.js:126:13)
  ionic:cli-framework:utils:process     at ChildProcess.emit (events.js:214:7)
  ionic:cli-framework:utils:process     at maybeClose (internal/child_process.js:915:16)
  ionic:cli-framework:utils:process     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  ionic:cli-framework:utils:process   killed: false,
  ionic:cli-framework:utils:process   code: 128,
  ionic:cli-framework:utils:process   signal: null,
  ionic:cli-framework:utils:process   cmd: 'taskkill /pid 7576 /T /F' } +5ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +1ms

**Comment by davidzongo** [comment]
Ionic version 3

**Comment by dwieeb** [comment]
@davidzongo Please fill in your `ionic info` output fully and post full error messages.

**Comment by brentrichison** [comment]
I'm having the same problem. I believe this started after updating Xcode, but I'm not 100% certain on that:

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : browser 5.0.4, ios 4.5.5
   Cordova Plugins       : no whitelisted plugins (2 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/brentrichison/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v10.8.0 (/usr/local/Cellar/node/10.8.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by brentrichison** [comment]
I fixed this using `-- --buildFlag="-UseModernBuildSystem=0"`

**Comment by dwieeb** [comment]
@brentrichison Yep, guessing your issue is different and related to Xcode 10. See https://github.com/apache/cordova-ios/issues/407

I'm closing this because it has a very general title. @davidzongo's issue is going to be different than everyone else that arrives here via a Google search. See my comment: https://github.com/ionic-team/ionic-cli/issues/3673#issuecomment-429364015
