### ISSUE TITLE
Blank Screen page on my android device when i ran my app

### ISSUE THREAD

**Issue by william1795** [ionic-team/ionic-cli#3699]
**Description:**

I see blank page on my android device when i ran my app.

**Steps to Reproduce:**

*Create new project : ionic start deployapp tabs --type=angular
*cd deployapp/
*ionic cordova platform add android@7.1.1
*ionic cordova run android

My device is conneted by debug usb mode
**Output:**

Blank Screen on my Android Device

**My `ionic info`:**

```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.13
   @angular-devkit/core       : 0.8.5
   @angular-devkit/schematics : 0.8.5
   @angular/cli               : 6.2.5
   @ionic/ng-toolkit          : 1.1.0
   @ionic/schematics-angular  : 1.0.7

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/william/android-sdk-linux)
   NodeJS            : v10.0.0 (/usr/local/bin/node)
   npm               : 5.6.0
   OS                : Linux 4.15


```

**Other Information:**

Android Version on my device 6.0

**Comment by dwieeb** [comment]
@william1795 Use the Chrome DevTools (via `chrome://inspect`) to connect to your device and view the console, looking for errors.

**Comment by jcesarmobile** [comment]
closing as there was no response

white screens are usually caused by javascript errors
