### ISSUE TITLE
Cannot find module "setimmediate" 

### ISSUE THREAD

**Issue by Thomas0921** [ionic-team/ionic-cli#3706]
**Description:**
Once I do ionic serve, I got this error. At my first serve, everything looks okay, and suddenly. this error pop up. The next time I do serve, I couldnt do it. Please help, I couldnt loss my whole project.What could go wrong. I did have settimmedia in my node_modules. No idea why it couldnt find it

**Steps to Reproduce:**
1. I deleted the node_modules folder outside IDE, and do a npm install
2. I got this error when 'ionic info' 
 Error loading @ionic/app-scripts package.json: Error: Cannot find module '@ionic/app-scripts/package'

**My `ionic info`:**

```
Ionic:


   ionic (Ionic CLI)  : 4.2.1 (C:\Users\thoma\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 4 other plugins)

System:

   NodeJS : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by Thomas0921** [comment]
I solved it with
npm install --only=dev

**Comment by dwieeb** [comment]
Maybe also try:

```
npm i -D @ionic/app-scripts
ionic repair
```

**Comment by Thomas0921** [comment]
> Maybe also try:
> 
> ```
> npm i -D @ionic/app-scripts
> ionic repair
> ```

Hi, I tried both of the lines, even though nothing feel changes in my project, but I feel better psychologically.

After a while, error pop up show ' invalid link HomePage', so I ran the 
npm install --only=dev, and the problem finally gone.

thanks anyway :)
