### ISSUE TITLE
Ionic 4 - ionic monitoring syncmaps not working with Ionic 4

### ISSUE THREAD

**Issue by fedme** [ionic-team/ionic-cli#3727]
**Description:**
The `ionic monitoring syncmaps` command does not work inside a Ionic 4 project because the `.sourcemaps` directory does not exist. The error returned is the following one:
```
[ERROR] Cannot find directory: .\.sourcemaps.

Make sure you have the latest @ionic/app-scripts. Then, re-run this command.
```

Manyally copying Angular's sourcemap files (from inside `www`) inside a newly created `.sourcemaps`  folder also does not work: it seems to be able to upload some files but then it returns the following error:
```
HTTP Error 400: POST https://pro-app-storage.s3.amazonaws.com/

<no buffered body>
```

**Steps to Reproduce:**
1. Create a new Ionic 4 project
2. Linck the project to Ionic Pro
2. Build it
3. Sync the sourcemaps to Ionic Pro Monitoring by running `ionic monitoring syncmaps`

**Output:**

```
[ERROR] Cannot find directory: .\.sourcemaps.

Make sure you have the latest @ionic/app-scripts. Then, re-run this command.
```

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.3.0 (C:\Users\fedem\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15-0
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Users\fedem\AppData\Local\Android\Sdk)
   NodeJS            : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Other Information:**

**Comment by MartineNavara** [comment]
I'm running into the same problem when executing the command ionic monitoring syncmaps.
Where you able to find a workaround?

**Comment by jesperbjerke** [comment]
It says [here](https://ionic.zendesk.com/hc/en-us/articles/360016174573-2019-01-23-Ionic-Framework-v4-0-0-Appflow-Support-Now-Available) that monitoring is not supported for v4, I hope they are planning to add support for it? Also saw a discussion [here](https://forum.ionicframework.com/t/ionic-pro-error-monitoring/148949/3) about it dissapearing from the dashboard even.

**Comment by MartineNavara** [comment]
@jesperbjerke , thank you for your response, that does explain why it is not working in the application.
I noticed monitoring this week for the first time in our AppFlow environment since the UI update

**Comment by scottieslg** [comment]
What the????

I would have never upgraded to V4 if I'd known monitoring isn't supported.  This is ridiculous!!

**Comment by ffMathy** [comment]
Same here.

**Comment by KasperAndersson** [comment]
@IonicProSupport Any news, on **monitoring** in v4 apps?

**Comment by ffMathy** [comment]
I ended up rewriting my app in React Native. Will come back once Capacitor comes out (maybe). Was able to rewrite 6 months of work in Ionic, in just 5 days in React Native.

The live-reload and debugger experience is also much better.

I find it disappointing that Ionic isn't responding, and isn't doing anything about critical issues. Version 4 shouldn't have been out if most of the critical infrastructure is not supported there!
