### ISSUE TITLE
ionic init command

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/ionic-cli#3732]
Create a command in the ionic cli to initialize the current working directory with an **ionic.config.json** file containing the name and type.  This command should also be referenced when you try to execute an ionic command in a directory that is not recognized as an ionic project.

I assume the following would work as the command. At which point you would ask for the name and type.

`ionic init`

**Comment by dwieeb** [comment]
Steps might include:
1. Create an `ionic.config.json`
1. Determine project type 
1. Run project-specific code to initialize with Ionic (e.g. `ng add @ionic/angular` for `angular` projects)

**Comment by dwieeb** [comment]
> This command should also be referenced when you try to execute an ionic command in a directory that is not recognized as an ionic project.

This could be done by using `git rev-parse --show-toplevel`, which locates a `.git` directory recursively back through paths of the current working directory. If a git directory is found, we're probably in a project. But if `ionic` runs within a home directory, for example, there shouldn't be a git directory and we probably can assume it's not a project.
