### ISSUE TITLE
[Suggest] Support `ionic update` (wrapping `ng update`)

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-cli#3746]
`ng update` is great functions.
But Ionic users use Ionic CLI. And beginner are not aware that Angular CLI can also be used in same project. So I think support `ionic update` (wrapping `ng update`) further improves Ionic CLI.

thanks.

**Comment by dwieeb** [comment]
Related: https://github.com/ionic-team/ionic-cli/issues/3686

**Comment by rdlabo** [comment]
Thanks. I missing confirm this topic. I will close this Issue.
