### ISSUE TITLE
ionic build - show progress

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic-cli#3750]
When running `ionic build` or `ionic build --prod`, there is not progress shown about the build process. Normally you will only see something like:
```
> ng run app:build
```

However when running `ng build` in a normal Angular site, the CLI shows a percentage of how the build process is doing, along with other information. 

Would it not be possible to change the ionic CLI to allow for this extra feedback?

**Comment by dwieeb** [comment]
@dylanvdmerwe Agreed. Apologies it took this long to turn it on! 

After updated to the latest CLI, one additional necessary change for this to take effect in your apps is to delete this line in `angular.json`:

```
         "progress": false,
```

See: https://github.com/ionic-team/starters/commit/02ddb18bb6c752e389e3c00e71e66a80ecfac2da
