### ISSUE TITLE
yarn kbn bootstrap failed. Command failed with exit code 1.

### ISSUE THREAD

**Issue by charliye** [ionic-team/ionic-cli#3751]
The command failed when I ran the yarn kbn bootstrap. Could you give some suggestion if you have?
Please find some info after ran the command.

[root@sbc-health kibana]# yarn kbn bootstrap
yarn run v1.12.3
$ node scripts/kbn bootstrap
Running [bootstrap] command from [/opt/kibana]:

Found [20] projects:

kibana
├── packages
│   ├── eslint-config-kibana (@elastic/eslint-config-kibana)
│   ├── eslint-plugin-kibana-custom (@elastic/eslint-plugin-kibana-custom)
│   ├── kbn-babel-preset (@kbn/babel-preset)
│   ├── kbn-config-schema (@kbn/config-schema)
│   ├── kbn-datemath (@kbn/datemath)
│   ├── kbn-dev-utils (@kbn/dev-utils)
│   ├── kbn-es (@kbn/es)
│   ├── kbn-eslint-import-resolver-kibana (@kbn/eslint-import-resolver-kibana)
│   ├── kbn-eslint-plugin-license-header (@kbn/eslint-plugin-license-header)
│   ├── kbn-i18n (@kbn/i18n)
│   ├── kbn-plugin-generator (@kbn/plugin-generator)
│   ├── kbn-plugin-helpers (@kbn/plugin-helpers)
│   ├── kbn-pm (@kbn/pm)
│   ├── kbn-system-loader (@kbn/system-loader)
│   ├── kbn-test-subj-selector (@kbn/test-subj-selector)
│   ├── kbn-test (@kbn/test)
│   └── kbn-ui-framework (@kbn/ui-framework)
└── x-pack (x-pack)
    └── plugins/infra

Running installs in topological order:

Installing dependencies in [kibana]:

$ node ./preinstall_check
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@types/node@8.10.21" is incompatible with requested version "@types/node@^9.4.7"
warning Resolution field "@types/node@8.10.21" is incompatible with requested version "@types/node@^9.4.6"
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @kbn/config-schema@1.0.0" has incorrect peer dependency "joi@10.4.1".
warning "x-pack > react-router-breadcrumbs-hoc@1.1.2" has unmet peer dependency "react-router@^4.2.0".
warning "x-pack > react-shortcuts@2.0.0" has incorrect peer dependency "react@^0.14.8 || ^15".
warning "x-pack > react-shortcuts@2.0.0" has incorrect peer dependency "react-dom@^0.14.8 || ^15".
warning "x-pack > react-sticky@6.0.1" has incorrect peer dependency "react@^15.3.0".
warning "x-pack > react-sticky@6.0.1" has incorrect peer dependency "react-dom@^15.3.0".
[5/5] Building fresh packages...
[11/12] ⠁ geckodriver
[-/12] ⠁ waiting...
[10/12] ⠁ chromedriver
[4/12] ⠁ node-sass
error /opt/kibana/node_modules/geckodriver: Command failed.
Exit code: 1
Command: node index.js
Arguments:
Directory: /opt/kibana/node_modules/geckodriver
Output:
Downloading geckodriver...
events.js:183
      throw er; // Unhandled 'error' event
      ^
RequestError: getaddrinfo ENOTFOUND github.com github.com:443
    at ClientRequest.<anonymous> (/opt/kibana/node_modules/geckodriver/node_modules/got/index.js:69:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
[bootstrap] failed:

Error: Command failed: yarn install --non-interactive --mutex=file
    at makeError (/opt/kibana/packages/kbn-pm/dist/index.js:19977:9)
    at Promise.all.then.arr (/opt/kibana/packages/kbn-pm/dist/index.js:20082:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dwieeb** [comment]
I don't think this has anything to do with the Ionic CLI.
