### ISSUE TITLE
Disable Watch in Serve

### ISSUE THREAD

**Issue by mariohmol** [ionic-team/ionic-cli#3768]
Hi!

Would be awesome to have a flag to say when I want them to watch my files or not.

The best would be if I could trigger a input in the console to start the build and refreshing the app.

This is useful for me because I have some watches that changes files in a period, so the watch keeps refreshing and restarting the building process a lot of times before it ends.

Just to remember that is not the livereload (that just refresh the browser)

Thanks!

**Comment by dwieeb** [comment]
I'm not understanding this:

> because I have some watches that changes files in a period

Can you elaborate?

---

> The best would be if I could trigger a input in the console to start the build and refreshing the app.

Isn't this just `ionic build`?

**Comment by mariohmol** [comment]
Yes... i'm trying to achieve this using watch aggregate timeout..

basicly.. from a change in source code to see the app running in browser this is taking minutes

The reason for that is that our project has a watch process that copy of files on top of another,  and this makes the ionic to trigger a lof of builds.. 

But you know what... i think that makes sense to be something like timeout on webpack.. will try to configure here using custo webpacks!! Thanks

**Comment by mariohmol** [comment]
This would be what i'm looking for but this is not respecting the timeout

``` 

var watch = require('@ionic/app-scripts/dist/watch');
var copy = require('@ionic/app-scripts/dist/copy');

module.exports = {
  srcFiles: {
    watchOptions: {
      aggregateTimeout: 30000,
    },
    paths: ['{{SRC}}/**/*.(ts|html|s(c|a)ss)'],
    options: { 
      aggregateTimeout: 30000,
      ignored: ['{{SRC}}/**/*.spec.ts', '{{SRC}}/**/*.e2e.ts', '**/*.DS_Store', '{{SRC}}/index.html'] 
    },
    // callback: function(event, filePath, context) {
    //     return new Promise(resolve => {
    //         console.log("DEBUG1");
    //         watch.buildUpdate(event, filePath, context).then(function() {
    //             console.log("DEBUG2");
    //             resolve();
    //         });
    //     });
    // }
  },
  copyConfig: copy.copyConfigToWatchConfig()
};

```

**Comment by mariohmol** [comment]
This seems not be working: `ionic_start_watch_timeout`

* https://github.com/ionic-team/ionic-app-scripts/blob/master/README.md

`ionic serve --startWatchTimeout 30000`

**Comment by mariohmol** [comment]
Should i open a bug for this?

**Comment by dwieeb** [comment]
@mariohmol Yes, if a documented option isn't working for app-scripts, please open a bug in the app-scripts repo: https://github.com/ionic-team/ionic-app-scripts

**Comment by mariohmol** [comment]
@dwieeb thanks!!

https://github.com/ionic-team/ionic-app-scripts/issues/1496
