### ISSUE TITLE
Error: spawn cmd enoent events.js:167

### ISSUE THREAD

**Issue by JamiresCosta** [ionic-team/ionic-cli#3770]
**Description:**

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

![erro](https://user-images.githubusercontent.com/13127565/49323804-022b5700-f500-11e8-96c4-7f72a72811bf.png)
Olá, iniciei os estudos de ionic, porém me deparei com um problema qdo executo o comando ionic serve. Crio minha pasta do projeto, mas qdo executo o ionic serve, ele me retorna o error:events.js:167 spawn cmd ENOENT. 
Alguém poderia me ajudar a resolver este problema? Desde já agradeço.

**Comment by lxmbetterman** [comment]
i meet the same problem,how to do ?

**Comment by lxmbetterman** [comment]
> i meet the same problem,how to do ?

use :ionic serve --no-open

**Comment by JamiresCosta** [comment]
Deu certo. Muito obrigado!

**Comment by dwieeb** [comment]
@JamiresCosta The CLI will no longer crash in the next version. I also added a debug statement so we can uncover the true error in the future. 

For now, @lxmbetterman is correct, `--no-open` is a good workaround.

Thanks!
