### ISSUE TITLE
Ionic resource generator generates splash with wrong colors

### ISSUE THREAD

**Issue by homer-jay** [ionic-team/ionic-cli#3778]
The resource generator generates splash images that are much darker than the original, and almost invisible. 

Input splash.png:
![splash](https://user-images.githubusercontent.com/5468827/49441662-86fbc680-f7c7-11e8-911a-221239b34200.png)

Output  drawable-port-hdpi-screen.png
![drawable-port-hdpi-screen](https://user-images.githubusercontent.com/5468827/49441680-8ebb6b00-f7c7-11e8-97b0-c46faec05688.png)

## Steps to reproduce:
1. Create a sample project
2. Replace splash with the one attached (splash.png)
3. Run the online generator: `ionic cordova resources --splash`

## Expected behavior: 
The generated splash images should have exactly the same colours, in this case #3a3a3a.

## Actual behavior:
Splash images generated with darkened colors, almost black : #0b0b0b
(see attached drawable-port-hdpi-screen.png)

## Hints:
* Same behavior observed with splash.psd instead of splash.png
* If I edit the splash with an image editor, and add a large pink blur in the center, the generator preserves the correct colors.
* If however, a small pink pixel is drawn on a corner, resulting colors are all wrong again (apparently the generator alters the colors based on some kind of average).

**Comment by angelo-italy** [comment]
the same for me. Grey color not respected

**Comment by dwieeb** [comment]
If there are color differences using Ionic CLI 5, please create a new issue here: https://github.com/ionic-team/cordova-res

The default image generator changed in CLI 5, so this is likely fixed or the bug belongs in the cordova-res repo, if it still exists.
