### ISSUE TITLE
'ionic-app-scripts' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by sau026** [ionic-team/ionic-cli#3785]
Guys, i have purchased ionic mobile template for woo commerce from (https://codecanyon.net/item/ionic-woocommerce-universal-ios-android-ecommerce-store-full-mobile-app/21561737), when i am trying to execute ionic serve if give the following error, 'ionic-app-scripts' is not recognized as an internal or external command, gys please help me out, i am very disturbed due to this.

**Comment by dwieeb** [comment]
You likely have to update `@ionic/app-scripts` to the latest version.

Related: https://github.com/ionic-team/ionic-cli/issues/3729
