### ISSUE TITLE
ionic start... not working on windows 8.1. Says cordova too old

### ISSUE THREAD

**Issue by xthukuh** [ionic-team/ionic-cli#38]
Am not behind a proxy and I was able to do this earlier. Now I upgrade to windows 8.1 and the command below wont work.

``` batch
ionic start myApp blank
```

I have updated cordova, re-installed windows and started again. But no change. If there is a workaround someone let me know. Here is my cmd output.

``` batch

C:\Users\Martin>ionic start myapp blank
Running start task...
Creating Ionic app in folder C:\Users\Martin\myapp based on blank project

DOWNLOADING: https://github.com/driftyco/ionic-app-base/archive/master.zip

DOWNLOADING: https://github.com/driftyco/ionic-starter-blank/archive/master.zip
Initializing cordova project.
Fetching plugin "org.apache.cordova.device" via plugin registry
Fetching plugin "org.apache.cordova.console" via plugin registry
ERROR: Unable to add plugins. Perhaps your version of Cordova is too old. Try up
dating (npm install -g cordova), removing this project folder, and trying again.

Exiting.

C:\Users\Martin>
```

**Comment by sidhant444** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7804380/6563474/6574bfba-c6c7-11e4-8b0c-b989a507384e.png)

**Comment by sidhant444** [comment]
i am having the above error on typing : ionic platform add android
OS: Windows 8.1

PLEASE HELP!

**Comment by jbavari** [comment]
@sidhant444 are you behind a proxy by chance?

**Comment by sidhant444** [comment]
yes i am behind a proxy of my college, i used gproxy for a while and got cordova and ionic somehow installed using the command line but now i am getting problem in adding android as a platform.

**Comment by sidhant444** [comment]
can you please suggest the best solution for windows 8.1 users who are running behind a proxy?

**Comment by jbavari** [comment]
Yep, it's in the [readme](https://github.com/driftyco/ionic-cli#working-around-proxies).

I'd also check out [how to set up proxy with npm](http://jjasonclark.com/how-to-setup-node-behind-web-proxy)

**Comment by sidhant444** [comment]
is it necesaary to write the npm/ionic commands in the git terminal windows or we can use default command prompt of windows?

**Comment by jbavari** [comment]
You should be able to use command prompt.

**Comment by sidhant444** [comment]
the solution you told above is for linux, i am not able to perform it in windows 8.1, PLEASE HELP

**Comment by sidhant444** [comment]
![screenshot from 2015-03-10 23 18 23](https://cloud.githubusercontent.com/assets/7804380/6581304/058d0bce-c77c-11e4-903e-c32fffc87d81.png)

**Comment by sidhant444** [comment]
i am now using linux on Ubuntu 14, i have installed all the necesary platform before intiating an ionic project but is now getting error in using( ionic start myApp ) with the above error as i am behind a proxy, i used the command (export http_proxy=internal.proxy.com ) to bypass my corporate proxy but it is still giving the above error. 

PLEASE HELP!
