### ISSUE TITLE
Allow package.json to define what "ionic build" and "ionic serve" do in custom projects

### ISSUE THREAD

**Issue by Giwayume** [ionic-team/ionic-cli#3819]
Looking at CLI 4.8.0, custom projects are hard-coded to always throw an error upon build/serve, without a way to define a custom build/serve process.

I would expect `ionic build` by default to run tasks that are not specific to Angular, such as auto-generating the app icon and splash screen assets, and allow a hook in the package.json of the project to run other custom build tasks if needed.

This is a small roadblock for Vue adoption.

**Comment by dwieeb** [comment]
Thanks, that makes sense. This was just an oversight.

**Comment by dwieeb** [comment]
Just pushed a commit that makes this work with projects generated by the Vue CLI.

Choose `custom` during `ionic init`:

```
$ ionic init
```

`ionic.config.json` is generated.

```
{
  "name": "test",
  "integrations": {},
  "type": "custom"
}
```

Make the following modifications to `package.json`:

```diff
   "scripts": {
+    "ionic:build": "vue-cli-service build",
+    "ionic:serve": "vue-cli-service serve",
     "serve": "vue-cli-service serve",
     "build": "vue-cli-service build",
     "lint": "vue-cli-service lint"
   },
```

This will be in Ionic CLI 4.9.0. Thanks!

**Comment by hiepxanh** [comment]
hello sir, I see that [angular HMR here](https://github.com/angular/angular-cli/wiki/stories-configure-hmr) angular hmr have custom code like `npm run hmr`. Can I use `ionic:build` to `npm run hmr`. So my `ionic cordova run android -l` will become `Hot module reload` instead of `live reload`????

**Comment by dwieeb** [comment]
`ionic:build` is not used with `ionic cordova run android` if that `-l` flag is used because that's for livereload.

**Comment by tomchiverton** [comment]
The main AppFlow Vue example project is missing these two lines :(
