### ISSUE TITLE
Prepare command support for buildConfig

### ISSUE THREAD

**Issue by l3ender** [ionic-team/ionic-cli#3821]
I'm using the latest beta version of Ionic and noticed that `ionic cordova prepare` was generating an XCode workspace without some of my `buildFlags` configured. For example, 

```
"ios": {
    "debug": {
      ...
      "buildFlag": [
        "-UseModernBuildSystem=0",
        "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES"
      ]
    }
}
```

When doing a normal build or run (`ionic cordova [build|run]`), the setting for "always embed swift standard libraries" (`ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES`) is working as expected. However, if I remove my XCode project (`platforms/ios` directory) and run `ionic cordova prepare`, the newly generated project does not have this setting configured correctly.

Looking at the [beta cli docs](https://beta.ionicframework.com/docs/cli/commands/cordova-prepare), I noticed that the `prepare` command doesn't take the ``--buildConfig`` option like `run` or `build`. It would be nice to have this so that it is a similar experience whether I run the app directly from ionic CLI or generate a workspace and run from there. This would avoid needing to manually configure these settings once a workspace is generated.

Thanks!

**Comment by dwieeb** [comment]
@l3ender My understanding is that `cordova prepare` doesn't do a Cordova build. It doesn't have the `--buildConfig` flag: https://cordova.apache.org/docs/en/latest/reference/cordova-cli/#cordova-prepare-command

`cordova compile`, however, does: https://cordova.apache.org/docs/en/latest/reference/cordova-cli/#cordova-compile-command

And `cordova build` is just `prepare` and `compile` combined.

**Comment by l3ender** [comment]
@dwieeb Correct, `prepare` command does not do a build. These commands (`prepare`, `build`, and `run`) all generate an XCode workspace though, and what's confusing is that the XCode workspace doesn't have the correct configuration settings (the ones that are specified by `buildConfig`).

My original post is a little misleading--I've realized it's not just prepare that does this, but all commands that generate the XCode workspace.

For example, take the following command:
```
ionic cordova run ios --livereload --buildConfig build.json
```
This command allows you to run the iOS app on device/simulator, and it will correctly build/compile based on properties in the `buildConfig` file. However, this same command will generate an XCode workspace that does **not** have the same workspace settings configured (the setting I've been using is `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES`)...this setting will need to be manually configured in XCode if I want to open the project in XCode and run the app from there.

I think expected behavior would be that if I run the app from `ionic` CLI OR have the CLI generate an XCode workspace and run the app from there, the app should react the same.

Hope that helps clarify. Thank you.

**Comment by dwieeb** [comment]
It does, thanks. I'm wondering if the request would be better suited in the `cordova-ios` project repo: https://github.com/apache/cordova-ios

The Ionic CLI doesn't really deal with this low-level detail, we just run the Cordova CLI.

**Comment by l3ender** [comment]
Will follow up in the other repo--thank you.
