### ISSUE TITLE
CLI Proxy not working on livereload on android

### ISSUE THREAD

**Issue by harshzalavadiya** [ionic-team/ionic-cli#3825]
**Description:**
Ionic 4 project created with latest CLI does not proxy requests
when running `ionic cordova run android --livereload`
but does proper proxying when running on `ionic serve`

**Steps to Reproduce:**
1. Create fresh ionic project with latest CLI
2. Download patch(diff) file and apply it [livereload.zip](https://github.com/ionic-team/ionic-cli/files/2791099/livereload.zip) 

**FYI**
patch files can be easily applied if you are using VSCode with this [extension](https://marketplace.visualstudio.com/items?itemName=paragdiwan.gitpatch)

**Output:**
`ionic serve`
![ionic-serve](https://user-images.githubusercontent.com/5774849/51670620-0d28d200-1fed-11e9-98df-012b94132afd.png)

`ionic cordova run android --livereload`
![ionic-run-android-livereload](https://user-images.githubusercontent.com/5774849/51670629-1023c280-1fed-11e9-95d4-1135e6eece6d.png)

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/harsh/Android/Sdk)
   NodeJS            : v10.15.0 (/usr/bin/node)
   npm               : 6.5.0
   OS                : Linux 4.15
```

**Other Information:**

**Comment by dwieeb** [comment]
Thanks, this will be fixed in `@ionic/angular-toolkit` 1.2.3.
