### ISSUE TITLE
Platform android adding failed because of resource error

### ISSUE THREAD

**Issue by pateldi1524** [ionic-team/ionic-cli#3826]
**Description:**
I am trying to add platform android in my ionic project but it fails because of resource error

![screenshot 2019-01-24 at 17 37 58](https://user-images.githubusercontent.com/28805399/51677205-d1970380-1ffe-11e9-956d-ac292080cbfe.png)

This is what i am getting
Before few hours everything was working fine.

**Comment by dwieeb** [comment]
@pateldi1524 Try now?

**Comment by pateldi1524** [comment]
It is working now.
Thanks
