### ISSUE TITLE
Since ionic cli 4.10.0 | TypeError: arg.includes is not a function

### ISSUE THREAD

**Issue by iCodr8** [ionic-team/ionic-cli#3834]
**Description:**

Since Ionic-cli 4.10.0 I get an error from the cli, when I am building the app for iOS.
With Ionic-cli 4.9.0 or older it is working without any problems.

**Steps to Reproduce:**

Run `ionic cordova run ios -lc --prod` 

**Output:**

```
TypeError: arg.includes is not a function

    at args.length.args.map.arg 
(/Users/user/.nvm/versions/node/v10.15.1/lib/node_modules/ionic/node_modules/@ionic/cli-framework/utils/shell.js:130:44)
    at Array.map (<anonymous>)
    at ShellCommand.bashify 
(/Users/user/.nvm/versions/node/v10.15.1/lib/node_modules/ionic/node_modules/@ionic/cli-framework/utils/shell.js:130:29)
    at Shell.<anonymous> (/Users/user/.nvm/versions/node/v10.15.1/lib/node_modules/ionic/lib/shell.js:27:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/.nvm/versions/node/v10.15.1/lib/node_modules/ionic/node_modules/tslib/tslib.js:104:62)

```

**Ionic info:**

Ionic 4.20.0

**Comment by dwieeb** [comment]
@iCodr8 Can you check if this is fixed in 4.10.1? Otherwise I may need more information: full command output and `ionic info`.

**Comment by dtaalbers** [comment]
@dwieeb It is fixed in 4.10.1 for me!

**Comment by iCodr8** [comment]
@dwieeb It works. Thank you!

**Comment by devsgtech** [comment]
> @iCodr8 Can you check if this is fixed in 4.10.1? Otherwise I may need more information: full command output and `ionic info`.

Ionic:

   ionic (Ionic CLI)  : 4.10.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/dr.mac/Library/Android/sdk)
   NodeJS            : v10.14.2 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.2 Build version 9C40b

*Not fixed. Still i'm getting same error.

**Comment by dtaalbers** [comment]
@devsgtech You are running on 

```
ionic (Ionic CLI)  : 4.10.0 (/usr/local/lib/node_modules/ionic)
```

Use `npm i -g ionic` to update **to 4.10.1** as @dwieeb mentioned in his post. Should be working again after the update.

**Comment by iCodr8** [comment]
It definitively works with **4.10.1**.

**Comment by devsgtech** [comment]
> It definitively works with **4.10.1**.

got it thnaks @iCodr8  @dwieeb
