### ISSUE TITLE
Could run live reload server

### ISSUE THREAD

**Issue by tgraj** [ionic-team/ionic-cli#3835]
**Description:**
Could not run live reload server, i'm a bit confused with the error message
**"The platform "53703" does not appear to have been added to this project."**

**Steps to Reproduce:**
I'm not sure how to reproduce, but running the command ionic cordova run android --device -livereload
always end up having the below error:

"The platform "53703" does not appear to have been added to this project."

This happen after below command:
**cordova run android --proxy --device --livereload-port --dev-logger-port 53703**

this seems like the livereload-port value becomes  platform value!!!

**Output:**

Below is my console log on what happened

 D:\MyProjects\Ionic\ynea>ionic cordova run android --device -livereload
> ionic-app-scripts serve --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser --iscordovaserve --platform android --target cordova
[app-scripts] [00:15:21]  ionic-app-scripts 3.2.2
[app-scripts] [00:15:21]  watch started ...
[app-scripts] [00:15:21]  build dev started ...
[app-scripts] [00:15:21]  clean started ...
[app-scripts] [00:15:21]  clean finished in less than 1 ms
[app-scripts] [00:15:21]  copy started ...
[app-scripts] [00:15:21]  deeplinks started ...
[app-scripts] [00:15:21]  deeplinks finished in 32 ms
[app-scripts] [00:15:21]  transpile started ...
[app-scripts] [00:15:24]  transpile finished in 2.70 s
[app-scripts] [00:15:24]  preprocess started ...
[app-scripts] [00:15:24]  preprocess finished in less than 1 ms
[app-scripts] [00:15:24]  webpack started ...
[app-scripts] [00:15:24]  copy finished in 2.87 s
[app-scripts] [00:15:27]  webpack finished in 2.97 s
[app-scripts] [00:15:27]  sass started ...
[app-scripts] [00:15:28]  sass finished in 844 ms
[app-scripts] [00:15:28]  postprocess started ...
[app-scripts] [00:15:28]  postprocess finished in less than 1 ms
[app-scripts] [00:15:28]  lint started ...
[app-scripts] [00:15:28]  build dev finished in 6.66 s
[app-scripts] [00:15:28]  watch ready in 6.74 s

[INFO] Development server running!

       Local: http://localhost:8100
       External: http://192.168.1.107:8100

       Use Ctrl+C to quit this process

> cordova run android --proxy --device --livereload-port --dev-logger-port 53703
[cordova]  Android Studio project detected
[cordova]  (node:29212) UnhandledPromiseRejectionWarning: Error: The platform "53703" does not appear to have been added to this project.
[cordova]      at Object.getPlatformApi (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:46:15)
[cordova]      at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:54:38
[cordova]      at Array.map (<anonymous>)
[cordova]      at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:52:47
[cordova]      at _fulfilled (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
[cordova]      at self.promiseDispatch.done (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
[cordova]      at Promise.promise.promiseDispatch (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
[cordova]      at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:557:44
[cordova]      at flush (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
[cordova]      at _combinedTickCallback (internal/process/next_tick.js:131:7)
[cordova]  (node:29212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[cordova]  (node:29212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[app-scripts] [00:15:31]  tslint: D:/MyProjects/Ionic/ynea/src/pages/setup2/setup2.ts, line: 2
[app-scripts]             'IonicPage' is declared but its value is never read.
[app-scripts]        L1:  import { Component } from '@angular/core';
[app-scripts] [00:15:31]  tslint: D:/MyProjects/Ionic/ynea/src/pages/setup/setup.ts, line: 3
[app-scripts]        L2:  import { IonicPage, NavController, NavParams } from 'ionic-angular';
[app-scripts]        L3:  import { Camera, CameraOptions } from '@ionic-native/camera';
[app-scripts]             'IonicPage' is declared but its value is never read.
[app-scripts]        L2:  import { Component } from '@angular/core';
[app-scripts]        L3:  import { IonicPage, NavController, NavParams } from 'ionic-angular';
[app-scripts]             'CameraOptions' is declared but its value is never read.
[app-scripts]       L12:  import { MyDb } from '../providers/mydb/mydb';
[app-scripts]       L13:  import { Camera, CameraOptions } from '@ionic-native/camera';
[app-scripts]       L14:  import { Common } from '../providers/common/common';
[app-scripts] [00:15:31]  tslint: D:/MyProjects/Ionic/

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)  : 4.10.0 (C:\Users\user\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\user\AppData\Local\Android\Sdk)
   NodeJS            : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Other Information:**

**Comment by tgraj** [comment]
Below is another piece of logs:

cordova run android --proxy --livereload-port 35729 --dev-logger-port 53703
Android Studio project detected
(node:1944) UnhandledPromiseRejectionWarning: Error: The platform "35729" does not appear to have been added to this project.
    at Object.getPlatformApi (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:46:15)
    at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:54:38
    at Array.map (<anonymous>)
    at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:52:47
    at _fulfilled (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
    at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:557:44
    at flush (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
(node:1944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The result is still same... could not run live reload server

**Comment by dwieeb** [comment]
Thanks... looks like we screwed up with the option groups in the last release. Should be fixed up soon!

**Comment by tgraj** [comment]
Thanks for the quick response @dwieeb , really appreciate it
