### ISSUE TITLE
"npm install -g ionic" fails

### ISSUE THREAD

**Issue by mowatermelon** [ionic-team/ionic-cli#3837]
**System:**

   NodeJS : v11.4.0 (D:\Program Files\nodejs\)
   npm    : 6.5.0
   OS     :  window 7

**Description:**

I am unable to install `ionic`. Running `npm install -g ionic` generates this error:

```sh
D:\Users\Administrator>npm i -g ionic
npm ERR! path D:\Program Files\nodejs\node_global\node_modules\ionic\node_module
s\inquirer
npm ERR! code EEXIST
npm ERR! errno -4075
npm ERR! syscall mkdir
npm ERR! EEXIST: file already exists, mkdir 'D:\Program Files\nodejs\node_global
\node_modules\ionic\node_modules\inquirer'
npm ERR! File exists: D:\Program Files\nodejs\node_global\node_modules\ionic\nod
e_modules\inquirer
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-01-31T0
2_22_32_040Z-debug.log
```

**Comment by dwieeb** [comment]
It looks like npm is giving you a suggestion:

```
npm ERR! File exists: D:\Program Files\nodejs\node_global\node_modules\ionic\nod
e_modules\inquirer
npm ERR! Move it away, and try again.
```

**Comment by hiepxanh** [comment]
I think his mean is: 
1) go `D:\Program Files\nodejs\node_global\node_modules\` there.
2) find `ionic` folder then delete it. and `npm i -g ionic` again.

**Comment by REDER82** [comment]
you just have to delete node_modules
`C:\Users\name_user\AppData\Roaming\npm`

then you run the command
```
npm install -g @ionic/cli
C:\Users\name_user>npm install -g @ionic/cli
```

now you go to environment variables 
in the path add the npm path
`C:\Users\jhenao\AppData\Roaming\npm`

now you can smile.
