### ISSUE TITLE
Ionic 4 Failed to compile, with ionic serve, after fresh installation

### ISSUE THREAD

**Issue by sirwentzelot** [ionic-team/ionic-cli#3842]
**Description:**
After a fresh install of ionic and cordova and a npm update, it is not possible to use the ionic serve command for me. Compilation is failing.

**Steps to Reproduce:**
Uninstall cordova and ionic.
Install cordova and ionic. 
Create a tabs project. 
Do ionic serve.

**Output:**
[ng] ERROR in ./src/global.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] TypeError: Instance of 'dy': type 'dy' is not a subtype of type 'n<String>'
[ng] ERROR in ./src/theme/variables.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/theme/variables.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] TypeError: Instance of 'dy': type 'dy' is not a subtype of type 'n<String>'
[ng] ERROR in ./src/app/tab1/tab1.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] TypeError: Instance of 'dy': type 'dy' is not a subtype of type 'n<String>'
[ng] Thu, 31 Jan 2019 20:23:35 GMT express:router <anonymous>  : /
[ng] Thu, 31 Jan 2019 20:23:35 GMT express:router middleware  : /
[ng] Thu, 31 Jan 2019 20:23:35 GMT finalhandler default 404
[ng] chunk {common} common.js, common.js.map (common) 18.5 kB  [rendered]
[ng] chunk {main} main.js, main.js.map (main) 33.4 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 8.9 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 18.8 kB [initial] [rendered]
[ng] chunk {tab1-tab1-module} tab1-tab1-module.js, tab1-tab1-module.js.map (tab1-tab1-module) 6.78 kB  [rendered]
[ng] chunk {tab2-tab2-module} tab2-tab2-module.js, tab2-tab2-module.js.map (tab2-tab2-module) 5.32 kB  [rendered]
[ng] chunk {tab3-tab3-module} tab3-tab3-module.js, tab3-tab3-module.js.map (tab3-tab3-module) 5.32 kB  [rendered]
[ng] chunk {tabs-tabs-module} tabs-tabs-module.js, tabs-tabs-module.js.map (tabs-tabs-module) 8.75 kB  [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 4.34 MB [initial] [rendered]
[ng] ℹ ｢wdm｣: Failed to compile.

**My `ionic info`:**
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

System:

   NodeJS : v10.7.0 (/usr/local/Cellar/node/10.7.0/bin/node)
   npm    : 6.7.0
   OS     : macOS Mojave

**Other Information:**

**Comment by sajanardha1990** [comment]
I m having the same issue 

> ng run app:serve --host=0.0.0.0 --port=8101
[ng] WARNING: This is a simple server for use in testing or debugging Angular applications
[ng] locally. It hasn't been reviewed for security issues.
[ng] Binding this server to an open connection can result in compromising your application or
[ng] computer. Using a different host than the one passed to the "--host" flag might result in
[ng] websocket connection issues. You might need to use "--disableHostCheck" if that's the
[ng] case.
[INFO] Waiting for connectivity with ng...

[INFO] Development server running!

       Local: http://localhost:8101
       External: http://192.168.0.155:8101, http://192.168.122.1:8101, http://192.168.140.1:8101

       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8101!

[ng] i ｢wdm｣: wait until bundle finished: /
[ng] Date: 2019-02-04T05:53:33.527Z
[ng] Hash: 1374546f98f7fa4bbfca
[ng] Time: 10319ms
[ng] chunk {main} main.js, main.js.map (main) 1.86 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 92.4 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 79.4 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]
[ng]
[ng] ERROR in Could not resolve module /E/
[ng] i ｢wdm｣: Failed to compile.

**Comment by dwieeb** [comment]
@sirwentzelot The Angular CLI is complaining about `./src/app/tab1/tab1.page.scss`. What's the content of the file?

@sajanardhan That doesn't look like the same issue. `[ng] ERROR in Could not resolve module /E/`

**Comment by sajanardhan** [comment]
@dwieeb  same issue meaning that it failed to compile on a fresh installation and its showing that error

**Comment by sirwentzelot** [comment]
@dwieeb 
this is the content: its from scratch

.welcome-card ion-img {
  max-height: 35vh;
  overflow: hidden;
}

i dont get it. a friend of mine did a fresh install a few days earlier and everything works like a charm for him. 
i thought about nodejs and npm, did also a fresh reinstall there, but still the same problem

**Comment by sirwentzelot** [comment]
got it!
brew did not remove nodejs completely. 
steps i did: 

uninstall ionic (sudo npm uninstall -g ionic cordova)
uninstall nodejs and npm (brew uninstall node)
check if brew removed all nodejs stuff in /usr/local/......

after i removed some folders manually i install node over brew again, install ionic and cordova et voila, everything works. 
thanks anyway @dwieeb :) 
can be closed now

**Comment by dwieeb** [comment]
How weird! I'm glad it's working for you now... 

@sajanardhan But you have a different root issue than the original post. If you want, create a new issue.

**Comment by SnowBases** [comment]
In my case, I have resolved the problem by using these command `ionic cordova platform add android` and then `ionic serve`

**Comment by johncris09** [comment]
I have the same problem too now

**Comment by MauroSalvadori** [comment]
Exactly the same problem, 1st time fresh install it works, after second time is dead impossible to use it

**Comment by sheanWinston** [comment]
I have the same issue

**Comment by utna** [comment]
seeing the same issue

**Comment by hrustad1017** [comment]
I am having the same issue without using cordova. I am just making a simple web app right now and all of my .scss files are failing to compile due to the sass modules in node modules failing to build. The error mentioned something about missing binaries. I did have an error of sorts while running ionic start. Basically the project never finished being created completely. I waited a couple hours, but all files seemed to be created appropriately but now i am having this error. should i open a separate issue?

**Comment by dwieeb** [comment]
Some googling revealed that this may be an issue with `node-sass`, a dependency of new Ionic apps. You can try the following troubleshooting options:

- run `npm rebuild`
- run `npm uninstall node-sass` and then `npm install node-sass`
- run `npm cache clean -f` and then try the previous option again
- Reinstall NodeJS (use the latest LTS version) and then run `ionic repair`
