### ISSUE TITLE
Ionic v1 build stops without errors

### ISSUE THREAD

**Issue by tharrington** [ionic-team/ionic-cli#3855]
**Description:**
My Ionic v1 project stops without errors. I have recently upgraded Ionic and node.

**Steps to Reproduce:**
I run ionic cordova build ios and there are no error messages

**Output:**
$ ionic cordova build ios
> ionic-v1 build
[10:15:37] Invoking sass gulp task.
> cordova build ios
Building for iPhone X Simulator
Building project: /Users/tylerharrington/Desktop/Projects/storage/platforms/ios/storage.xcworkspace
	Configuration: Debug
	Platform: emulator
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/tylerharrington/Desktop/Projects/storage/platforms/ios/build/emulator
    SDKROOT = iphonesimulator12.1
    SHARED_PRECOMPS_DIR = /Users/tylerharrington/Desktop/Projects/storage/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/tylerharrington/Desktop/Projects/storage/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

**My `ionic info`:**

```
$ ionic info

Ionic:

   ionic (Ionic CLI) : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.2.4
   @ionic/v1-toolkit : 1.0.14

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0, ios 4.5.5
   Cordova Plugins       : no whitelisted plugins (15 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/tylerharrington/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.15.1 (/usr/local/bin/node)
   npm               : 6.7.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

I have tried all removing the platform and re-adding, cleaning npm cache, and a few other commands. Nothing seems to resolve the issue.

**Comment by mluis** [comment]
I'm having the same issue.. Please append `--verbose` to this issue.
I'm getting:
```
No scripts found for hook "after_compile".
No scripts found for hook "after_build".
```

**Comment by dwieeb** [comment]
@tharrington Looks like the issue is with the Cordova build, not with Ionic's build. You can confirm this by just running `cordova build ios`.

@mluis Likely a different issue?

**Comment by mluis** [comment]
@dwieeb it's hard to say, since ionic cli is the developer's "entry point" to an ionic project. I was having the same behaviour as this issue states, although I had to open up the project in xcode check a related error with libicu4c while manually starting the build process inside xcode. After this I could continue building with ionic cli.

It seems to me that the ionic cli wasn't aware of what was happening.

**Comment by dwieeb** [comment]
This is a cordova-ios issue. You can update to version 5 to fix this. 

```
cordova platform rm ios
cordova platform add ios@5
```
