### ISSUE TITLE
Data path "" should have required property 'name' & @ionic/angular-toolkit

### ISSUE THREAD

**Issue by OCALAB** [ionic-team/ionic-cli#3864]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Data path "" should have required property 'name' when using --livereload and a custom webpack.config

**Expected behavior:**
Is it possible to use a custom "**webpack.config.js**" without loosing livereload option?

Using the following configuration with the command "**ionic cordova run browser --livereload**" I receive the error: [**ng] Schema validation failed with the following errors: [ng] Data path "" should NOT have additional properties(customWebpackConfig).**

**Steps to reproduce:**
"ionic-cordova-serve": {
   "builder": "@ionic/angular-toolkit:cordova-serve",
   "options": {
      "cordovaBuildTarget": "app:ionic-cordova-build",
      "devServerTarget": "app:serve",
      "customWebpackConfig": {
         "path": "./config/webpack.config.js"
      }
    },
   "configurations": {
      "production": {
         "cordovaBuildTarget": "app:ionic-cordova-build:production",
         "devServerTarget": "app:serve:production"
      }
   }
}

**Comment by OCALAB** [comment]
An extensive research shown that the problem maybe cause by missing supporto of customWebpackConfig in the "builder": "@ionic/angular-toolkit:cordova-serve". Can someone confirm this analysis? Is there a workaround for that?

I confirm that the problem presists only I we using the --livereload option.

**Comment by OCALAB** [comment]
Finally I've got the solution. No need to use the customWebpackConfig package. Just put the webpack.config in the root project directory to merge it during the compile/transpile task!

**Comment by dwieeb** [comment]
Let's just close this and keep https://github.com/ionic-team/angular-toolkit/issues/77
