### ISSUE TITLE
ionic cordova resources doesn't generate all required images for iOS

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic-cli#3865]
**Description:**

I've changed my AppIcon and re-generated the icons with `ionic cordova resources`.
Many icons were generated but there are some missing that are required by XCode to build the app.

The following icons are missing:
icon-20.png
AppIcon24x24@2x.png
AppIcon40x40@2x.png
AppIcon86x86@2x.png
AppIcon98x98@2x.png

**Steps to Reproduce:**

1. generate a set of icons with `ionic cordova resources`
2. try to build the app for the AppStore

**My `ionic info`:**

```

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.13.1
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.1, (and 11 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.7.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

```

**Comment by coachdesign** [comment]
Hi, the only one icon missed is 20x20.
40@2x was generate.
In Assets.xcassets there aren't 24@2x, 86@2x and 98@2x.

**Comment by sonicwong** [comment]
I found below image used the default cordova icon for IOS platform:

⁨Images.xcassets⁩ ▸ ⁨AppIcon.appiconset⁩
icon-20.png
icon-24@2x.png
icon-27.5@2x.png
icon-44@2x.png
icon-86@2x.png
icon-98@2x.png

**Comment by gabrielvisconti89** [comment]
I'm having the same problem

> **Description:**
> 
> I've changed my AppIcon and re-generated the icons with `ionic cordova resources`.
> Many icons were generated but there are some missing that are required by XCode to build the app.
> 
> The following icons are missing:
> icon-20.png
> [AppIcon24x24@2x.png](mailto:AppIcon24x24@2x.png)
> [AppIcon40x40@2x.png](mailto:AppIcon40x40@2x.png)
> [AppIcon86x86@2x.png](mailto:AppIcon86x86@2x.png)
> [AppIcon98x98@2x.png](mailto:AppIcon98x98@2x.png)
> 
> **Steps to Reproduce:**
> 
> 1. generate a set of icons with `ionic cordova resources`
> 2. try to build the app for the AppStore
> 
> **My `ionic info`:**
> 
> ```
> 
>    ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework               : @ionic/angular 4.0.1
>    @angular-devkit/build-angular : 0.13.1
>    @angular-devkit/schematics    : 7.3.1
>    @angular/cli                  : 7.3.1
>    @ionic/angular-toolkit        : 1.3.0
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : android 7.1.4, ios 4.5.5
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.1, (and 11 other plugins)
> 
> System:
> 
>    ios-deploy : 1.9.4
>    NodeJS     : v10.15.0 (/usr/local/bin/node)
>    npm        : 6.7.0
>    OS         : macOS Mojave
>    Xcode      : Xcode 10.1 Build version 10B61
> ```

**Comment by dwieeb** [comment]
This issue is pretty old, and I noticed you're still using Ionic CLI 4 @gabrielvisconti89 

For Ionic CLI 5, we switched to using a local, offline resource generator called [`cordova-res`](https://github.com/ionic-team/cordova-res) (more changes in the [CHANGELOG](https://github.com/ionic-team/ionic-cli/blob/develop/packages/ionic/CHANGELOG.md#500-2019-05-29)).

I think a lot of these were added in [this PR](https://github.com/ionic-team/cordova-res/pull/26), but if it's still missing sizes, please create an issue in the cordova-res repository.

I'm gonna close this.
