### ISSUE TITLE
Wrong update available message showed

### ISSUE THREAD

**Issue by satheshk385** [ionic-team/ionic-cli#3872]
**Description:**
I have updated ionic cli. But it showing update available

**Steps to Reproduce:**
open windows cmd, 
ionic -v
npm i -g ionic 
ionic -v

Output
![image](https://user-images.githubusercontent.com/29550859/53152103-bfe35480-35da-11e9-8019-7e74a95482a1.png)

**Comment by dwieeb** [comment]
Odd. We use `update-notifier` for that, same as npm. I've been meaning to replace it because it can act a bit funky when a proxy is required (it doesn't use the proxy settings from the CLI).

**Comment by dwieeb** [comment]
This can happen sometimes because update-notifier writes to a file and then reads it the next time a command runs.
