### ISSUE TITLE
ionic g component <name> generates `<name>.spec.ts`  that imports `<name>.page` instead of `<name>.component`

### ISSUE THREAD

**Issue by rappad** [ionic-team/ionic-cli#3877]
**Description:**

command `ionic g component test` generates all of the files correctly, but in the `test.component.spec.ts` file imports `import { TestPage } from './test.page';`  instead of  `import { TestComponent } from './test.component';`

**Steps to Reproduce:**

run `ionic g component <component-name>` on newly generated ionic project.

**Output:**

 `*.spec.ts` imports `*.page` instead of `*.component`

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v11.10.0
   npm    : v6.8.0
   OS     : Windows 10
```

**Comment by dwieeb** [comment]
Thanks @rappad! I have an open issue for this here: https://github.com/ionic-team/angular-toolkit/issues/78

Gonna close this as a duplicate. Thanks!
