### ISSUE TITLE
The term 'ionic' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by hasnainelahi** [ionic-team/ionic-cli#3878]
ionic : The term 'ionic' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ionic serve
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (ionic:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException @

**Comment by dwieeb** [comment]
@hasnainelahi This alone won't be enough to help you. It looks like a powershell error? In any case, it looks like an issue with installation. I think the forum or one of our other support channels would be a better resource to help you.
