### ISSUE TITLE
proxies do not work on ionic 4 lab

### ISSUE THREAD

**Issue by i4bis** [ionic-team/ionic-cli#3879]
**Description:**
I am upgrading an app from ionic v3 to v4 and am running into an issue with proxies. I have configured my angular.json and proxy.conf.js files which work great with ionic serve and ng serve. When I run ionic serve --lab however, the proxy configurations in the CLI show that they are begin created but the lab environment is still submitting all api requests to localhost.

**Steps to Reproduce:**
configure angular.json to point to a proxy.conf.js or proxy.conf.json file.
run ionic serve --lab -- --disableHostCheck true --ssl

**Output:**
ionic serve --lab -- --disableHostCheck true --ssl
> ng run app:serve --host=0.0.0.0 --port=8100 --disableHostCheck true --ssl
[ng] WARNING: This is a simple server for use in testing or debugging Angular applications
[ng] locally. It hasn't been reviewed for security issues.
[ng] Binding this server to an open connection can result in compromising your application or
[ng] computer. Using a different host than the one passed to the "--host" flag might result in
[ng] websocket connection issues. You might need to use "--disableHostCheck" if that's the
[ng] case.
[ng] WARNING: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
[ng] [HPM] Proxy created: [ '/api1', '/api2', '/api3', '/api4', '/api5' ]  ->  https://www.MYURL.com
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...
[ng] Date: 2019-02-28T15:28:37.143Z
[ng] Hash: 2a81b380da3200c9f0b1
[ng] Time: 11235ms
[ng] chunk {main} main.js, main.js.map (main) 1.86 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 93 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 489 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]
[ng] 
[ng] ERROR in No NgModule metadata found for 'ContactPrefsPageModule'.
[ng] ℹ ｢wdm｣: Failed to compile.
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...
> ionic-lab http://localhost:8100 --host localhost --port 8200 --project-type angular --app-name member-mobile --app-version 0.0.1

[INFO] Development server running!
       
       Lab: http://localhost:8200
       Local: http://localhost:8100
       External: http://172.30.19.144:8100
       
       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8200!

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/Users/myuser/.nvm/versions/node/v11.8.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios
   Cordova Plugins       : cordova-plugin-ionic-webview 3.1.2, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/myuser/Library/Android/sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v11.8.0 (/Users/myuser/.nvm/versions/node/v11.8.0/bin/node)
   npm               : 6.5.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```

**Other Information:**

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.
