### ISSUE TITLE
After clicking the jpush push notification, the page data binding mechanism is invalid.

### ISSUE THREAD

**Issue by bobo456123** [ionic-team/ionic-cli#3883]
**Description:**
I have been using ionic and jpush for notification, i get the notification on app and now i have 1 issues. i open a particular page of my app on notification click，After the page opens, it is found that the data binding is invalid. For example, the segment component sets [(ngModel)]="type", but I click segment-button and segment does not switch.
If I copy the code executed after the click notification, write a button on the page to trigger the execution of this code, then the segment can be switched normally.

**Steps to Reproduce:**
There are several pages, mainPage, aPage, bPage, cPage.

**The mainPage code is as follows:**
```
<ion-tabs selectedIndex="0">
    <ion-tab [root]="aPage" tabsHideOnSubPages="true" tabTitle="aPage" tabUrlPath="1" tabIcon="clock"></ion-tab>
    <ion-tab [root]="bPage" tabsHideOnSubPages="true" tabTitle="bPage" tabUrlPath="2" tabIcon="briefcase"></ion-tab>
    <ion-tab [root]="cPage" tabsHideOnSubPages="true" tabTitle="cPage" tabUrlPath="3" tabIcon="person"></ion-tab>
</ion-tabs>
```

**The aPage code is as follows:**
```
<ion-header>
  <ion-toolbar color="primary">
    <ion-title>title</ion-title>
  </ion-toolbar>
  <ion-toolbar color="dark" mode="md" class="exx-segment">
    <ion-segment color="light" mode="md" [(ngModel)]="type" (ionChange)="changeMode($event)">
      <ion-segment-button value="item1">item1</ion-segment-button>
      <ion-segment-button value="item2">item2</ion-segment-button>
    </ion-segment>
  </ion-toolbar>
</ion-header>
<ion-content no-padding [hidden]="type!='item1'">
...
</ion-content>
<ion-content no-padding [hidden]="type!='item2'">
...
</ion-content>
```

**When I receive the notification, click on the notification to execute the code (I want to refresh aPage):**
```
              Let currentTab = this.app.getActiveNavs()[0];
              Let rootNav = this.app.getRootNav()
              currentTab.parent.select(0);
              rootNav.push("main")
                .then(() => {
                  rootNav.remove(0, rootNav.getActive().index);
                });
```

After executing this code, the segment cannot be switched by clicking.

**Output:**
Packaged Android app in debug mode, debug operation did not find any error

**My `ionic info`:**

```
cli packages: (D:\Program Files\nodejs\node_global\node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.0.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.11.3
    npm               : 5.6.0
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : D:\Program Files\adt-bundle-windows-x86_64-20140702\sdk

Misc:

    backend : pro
```

**Comment by mhartington** [comment]
Hi there! This issue does not appear to be an issue with the framework itself, so it will be closed. Please review your issue and open a new ticket on the appropriate project repository, or feel free to post a question on the [Ionic Forum](http://forum.ionicframework.com). Thanks!
