### ISSUE TITLE
ionic4 --source-map and cordova issues

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-cli#3890]
**Description:**
running `ionic cordova build android --prod --release --source-map` does not clean the `www` folder and also the -`-source-map` advanced options is ignored, maps seems to not be created.

if we perform `ionic build --prod --source-map` the maps are created in the `www` folder. 

if we perform `ionic build --prod --source-map --engine=cordova --platform=android --release`
a) the www folder is not cleaned
b) the source map files are not created
c) the cordova app is not created, it stops after building the www files

**My `ionic info`:**
```
Ionic:
   ionic (Ionic CLI)             : 4.10.3 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:
   Android SDK Tools : 26.1.1 (/home/michi/software/android/sdk)
   NodeJS            : v10.15.2 (/usr/bin/node)
   npm               : 6.8.0
   OS                : Linux 4.15
```

**Comment by mburger81** [comment]
Hello @dwieeb, with `angular-toolkit@1.5.x` the `--source-map` issue is resolved but there is still the issue about the `www` folder which is not cleaned up on different commands.

**Comment by dwieeb** [comment]
Glad to hear `--source-map` is working.

We disable deleting the `www` before doing a build with `--engine=cordova`. By default, the Angular CLI _does_ delete the output directory before building.

If we do delete the output directory with each build, the Cordova CLI will occasionally forcefully error out saying "This is not a Cordova project."

Perhaps a flag to force delete the output directory?

**Comment by mburger81** [comment]
We did about 20 tests, we removed always the www folder before we created a cordova production build and had never a problem like described.

The problem is, if you don't polish www folder you can have several problems with wrong and unneeded files. 
Our Android production build is about 7mb but if the www folder isn't deleted we run also in about 22mb bundles, for example when we did test for source maps.
I think this is a bad thing not deleting the folder and I'm honestly wondering why this is not well documented, or did I miss something? 

Thx

**Comment by dwieeb** [comment]
@mburger81 Turning off output directory deletion was done here https://github.com/ionic-team/angular-toolkit/issues/51. Admittedly I could never reproduce that issue. I just knew the change would resolve the issue.

There's also https://github.com/ionic-team/ionic-cli/issues/3823 where not deleting it was causing issues for multi-app projects.

In any case, this needs more investigation. It's not good that artifacts from a dev build can end up in a prod build.

**Comment by dwieeb** [comment]
@mburger81 Gonna close this in favor of a more specific issue: https://github.com/ionic-team/ionic-cli/issues/3954
