### ISSUE TITLE
Could we have something like ionic serve --lab but with android/ios frames

### ISSUE THREAD

**Issue by FOStack** [ionic-team/ionic-cli#3897]
Purely for aesthetic reasons. I would like to make coding videos and have the view render within an android frame as i'm updating code.

Please and thank you 😃

**Comment by dwieeb** [comment]
With android/ios frames? What do you mean by that? That's what Ionic Lab is, right?

**Comment by FOStack** [comment]
Yes. But I never saw an option to wrap a specific device frame around the view. But No worries, this will work for me. 
![ss-ionic4-diective](https://user-images.githubusercontent.com/46578639/54384321-2ba46480-4651-11e9-924d-3c47e415331e.png)

**Comment by dwieeb** [comment]
Oh I see! For aesthetic reasons. Thanks for clarifying.
