### ISSUE TITLE
[V4.11] compiling and serving seem much slower

### ISSUE THREAD

**Issue by berchik** [ionic-team/ionic-cli#3903]
**Description:**
ionic serve works about twice as slow than earlier release.

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.11.0 (C:\Users\jo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.3.5
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v10.15.1 (A:\Program Files\nodejs\node.exe)
   npm    : 6.5.0
   OS     : Windows 10
```

**Comment by dwieeb** [comment]
@berchik What are the actual time differences between 4.11 and an earlier release?

**Comment by berchik** [comment]
Sorry for the late response. Its all quick, however for the project I was testing the time from saving to refresh and serving was about 0.5sec, and after the update to 4.11 it is about 1.5s which is 2-3 times slower, and after you get used to work really fast with testing different code options by quickly changing/saving/serving it is quite noticeable. Thanks.

**Comment by all43** [comment]
It's even worse with 4.12. Reload take 5-12 seconds with my app, 3-5 seconds with new project (blank template)
I've created separate issue here https://github.com/ionic-team/ionic-cli/issues/3967

**Comment by dwieeb** [comment]
Let's talk in https://github.com/ionic-team/ionic-cli/issues/3967
