### ISSUE TITLE
Ionic doctor reporting "add viewport-fix=cover", but already there

### ISSUE THREAD

**Issue by jungalwala** [ionic-team/ionic-cli#3907]
When I run `ionic doctor check` the following warning is reported:

> ✔ Detecting issues: 15 / 15 complete - done!
> [WARN] viewport-fit=cover not set in index.html
>        
>        iOS 11 introduces new "safe regions" for webviews, which can throw off component sizing, squish the header into 
>        the status bar, letterbox the app on iPhone X, etc. Fixing this issue will ensure the webview takes up the full 
>        size of the screen. See https://blog.ionicframework.com/ios-11-checklist for more information.
>        
>        To fix, take the following step(s):
>        
>          1) Add viewport-fit=cover to the <meta name="viewport"> tag in your index.html file
>        
>        $ ionic config set -g doctor.issues.viewport-fit-not-set.ignored true (ignore this issue in the future)
>        
> [INFO] Doctor Summary
>        
>        - Detected 1 issue.
>        - 0 issues can be fixed automatically

But my index.html already has the line in it:

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title>Ionic App</title>
    <meta name='viewport' content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <link rel="icon" type="image/x-icon" href="assets/icon/favicon.ico">
    <link rel="manifest" href="manifest.json">
    <meta name="theme-color" content="#4e8ef7">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <script src="cordova.js"></script>
    <link href="build/main.css" rel="stylesheet">
  </head>
  <body>
    <ion-app></ion-app>
    <script src="build/polyfills.js"></script>
    <script src="build/vendor.js"></script>
    <script src="build/main.js"></script>
  </body>
</html>
```

Here is my ionic info:

> Ionic:
> 
>    ionic (Ionic CLI)  : 4.12.0 (/Users/jfj/.nvm/versions/node/v7.10.1/lib/node_modules/ionic)
>    Ionic Framework    : ionic-angular 3.9.4
>    @ionic/app-scripts : 3.2.3
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : android 7.0.0, browser 5.0.3, ios 4.5.5
>    Cordova Plugins       : cordova-plugin-ionic 5.2.7, cordova-plugin-ionic-webview 2.3.1, (and 8 other plugins)
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (/Users/jfj/Library/Android/sdk)
>    NodeJS            : v7.10.1 (/Users/jfj/.nvm/versions/node/v7.10.1/bin/node)
>    npm               : 5.7.1
>    OS                : macOS Mojave
>    Xcode             : Xcode 10.1 Build version 10B61

**Comment by dwieeb** [comment]
It's likely the single quotes: `<meta name='viewport'`

**Comment by jungalwala** [comment]
> It's likely the single quotes: `<meta name='viewport'`

Tried the double-quote, didn't make a diference

**Comment by dwieeb** [comment]
Ah, it's because the end of the `<meta` tag should be `/>` not `>`. But I will relax the regex and fix this up. Thanks 👍
