### ISSUE TITLE
[V4.10.2] [ERROR] Unable to find starter template for "super"

### ISSUE THREAD

**Issue by rodrigograca31** [ionic-team/ionic-cli#3909]
**Description:**

Trying to create a new project based on the "super" starter template gives avoidable error...

**Steps to Reproduce:**

```bash
ionic start --list
#....
#super    | ionic-angular | A starting project complete with pre-built pages, providers and best practices for Ionic development.
#....
ionic start musicPlayer super
```

**Output:**

```
Preparing directory ./musicPlayer - done!
(node:7611) ExperimentalWarning: The http2 module is an experimental API.
⠴ Looking up starter 
[ERROR] Unable to find starter template for super
                                                                                                                     
        If this is not a typo, please make sure it is a valid starter template within the starters repo:             
        https://github.com/ionic-team/starters                                                      
```

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v8.10.0
   npm    : 6.9.0
   OS     : Linux 4.15
```

**Other Information:**

I was reading the V3 docs and also other docs give the idea that I should run `ionic start NAME tabs` and use `ionic start --list` to get a list, so I did it and decided to run `ionic start NAME super` but got the above error... 
[These docs](https://ionicframework.com/docs/cli/commands/start) actually show `ionic start myApp super --type=ionic-angular` and that works, but IMHO when running `ionic start --list` should tell us to use `--type=` otherwise when we [read these other docs](https://ionicframework.com/docs/building/starting) we don't know that we got to use `--type` and gives us that error...

Or don't require `--type=` since blank, tabs and sidemenu don't require it......

**Comment by dwieeb** [comment]
@rodrigograca31 

> when running `ionic start --list` should tell us to use `--type=`

Agreed. We should clear this up. 

> tabs and sidemenu don't require it......

Both Ionic 4 and Ionic 3 have a tabs and sidemenu starter. The `--type` flag differentiates the Ionic version each will use.

**Comment by Rattone** [comment]
So "ionic-angular" stay for Ionic v3 and "angular" stay for Ionic v4?
Correct?

**Comment by dwieeb** [comment]
@Rattone Essentially. It's less about Ionic version and more about project _type_, or _how_ to build your project. Ionic 2 & 3 apps will always be built with `@ionic/app-scripts`, but going forward Ionic apps will be built with the framework CLI for the framework you choose. For Angular, that means the Angular CLI, of course. 

* `ionic-angular` type means you're using the `ionic-angular` package (which was Ionic 2/3)
* `angular` type means you're using `@ionic/angular` package (Ionic 4+)

**Comment by dwieeb** [comment]
Just pushed a commit that prints this for `ionic start --list`:

![image](https://user-images.githubusercontent.com/236501/57870937-cb0ae280-77cd-11e9-891a-0ed8edfae647.png)

**Comment by ssossou** [comment]
so in short to clarify it for everyone coming to this page hoping top find a super template for ionic 4,
It simply does not exist right because ionic has not been able to create such template for ionic  4.

super templates shows the best practices for using certain features in the version of the framework, i don't understand why we don't have such template. 
Tabs and sidemenu have nothing useful to a mid level/senior javascript developer trying to pick this up.
we are back to year one every time a new framework version is overhauled.
Stop searching for this and start getting creative, Ionic should have said to us.
no to mention the documentation is worst than any other  of ionic creating massive confusion for all involved.
Thanks Ionic Team, i wonder if flutter or reactive native are not better alternative.

**Comment by rodrigograca31** [comment]
@ssossou Well said, starting to wonder the same!

1. No advanced template with "advanced" examples.
2. Confusing docs.
3. Always changing ways of doing things...
4. Adding other frameworks instead of focus on Angular... Why? 🤷

**Comment by dwieeb** [comment]
I can't speak much to the backwards compatibility of the framework and Angular, but if long-term stability is important in your company, Ionic offers some peace of mind for enterprise: https://ionicframework.com/enterprise. We're not going to do everything for free. 

Our example of best practices has never been the "super" template.. that's more of a one-off showcase. It has not been actively maintained. We have the [Ionic conference app](https://github.com/ionic-team/ionic-conference-app) to show best practices. It is actively maintained and contains numerous examples. In CLI 5, you will be able to use the conference app with `ionic start`.

If either of you could provide constructive feedback on how to improve the docs, we'd welcome it. We're pretty proud of the new docs, and haven't really heard many negative things, but we're always open to feedback.

> Adding other frameworks instead of focus on Angular... Why? 🤷

Supporting alternative frameworks was a huge goal for Ionic 4 and we have many blog posts and technical articles about why this is important, not just for developers that use the other frameworks, but for Angular developers as well.

**Comment by rodrigograca31** [comment]
> Ionic offers some peace of mind for enterprise:

how though? can't seem to find "how" in any of the pages, nor a price.....

[I have an open issue in the docs repo](https://github.com/ionic-team/ionic-docs/issues/698) :)

**Comment by mhartington** [comment]
To touch on a few points @ssossou has made...

>they have not being able to articulate angular backward compatibility*, anytime you as a question on the forum they will steer you down upgrade paths to higher angular versions....

I think you're misunderstanding the point of a Major version change. In Semver, a Major version change (3 => 4) indicates that there are incompatible API changes. Meaning that what worked in 3, will not work in 4. So saying that things are not backwards compatible is kind true. But it's the point of a Major version change. Meaning it's a chance to fix major issues that we could not fix without reworking things.


As far as the super starter not existing, it's just a matter of we have not made it yet. Simple as that. 

>not* to mention the documentation is worst than any other of ionic creating massive confusion for all involved.

What parts of the docs are confusing?  As @dwieeb has said, if there's constructive feedback on what could be improved, we'd gladly take a look.
