### ISSUE TITLE
Generating components with `ionic g component` assumes we're generating a page.

### ISSUE THREAD

**Issue by AugusDogus** [ionic-team/ionic-cli#3918]
**Description:**
When generating a new component with `ionic g component test-component` a component is generated called `test-component`. The test-component.component.ts file correctly exports the class as `TestComponentComponent`, but the spec file assumed that we're generating a page and as such the import fails and the `describe()` description is incorrect. 

**Steps to Reproduce:**
In any project use `ionic g component test-component` and look at test-component.component.spec.ts

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/Users/bluebbers/.nvm/versions/node/v10.15.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   NodeJS : v10.15.1 (/Users/bluebbers/.nvm/versions/node/v10.15.1/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61
```

**Other Information:**
<details>
  <summary>test-comp.component.ts</summary>

![test-comp component ts](https://user-images.githubusercontent.com/9794679/55030896-60160a00-4fdb-11e9-9fa5-e14f3c9a0eea.png)

</details>
<details>
  <summary>test-comp.component.spec.ts</summary>

![test-comp component spec ts](https://user-images.githubusercontent.com/9794679/55030923-6f955300-4fdb-11e9-9bf4-d7e1af0cfeb6.png)

</details>

**Comment by dwieeb** [comment]
This is fixed in `@ionic/angular-toolkit` 1.4.1: https://github.com/ionic-team/angular-toolkit/blob/master/CHANGELOG.md#141-2019-03-19

**Comment by dwieeb** [comment]
@AugusDogus I realize it's annoying to have to keep project dependencies up to date and in sync, which is why this issue exists: https://github.com/ionic-team/ionic-cli/issues/3686

If we hook into `ng update`, perhaps we can automatically keep the angular toolkit up to date.

**Comment by AugusDogus** [comment]
My mistake, thanks for the timely response @dwieeb. Looking forward to the changes in #3686
