### ISSUE TITLE
Error: ENOENT: no such file or directory, open './.ionic/ssl/cert.pem'

### ISSUE THREAD

**Issue by mswilson4040** [ionic-team/ionic-cli#3926]
**Description:**

Unable to create new iconic project

**Steps to Reproduce:**

ionic start mobile-project blank

**Output:**

Error: ENOENT: no such file or directory, open './.ionic/ssl/cert.pem'

**My `ionic info`:**

```
<paste here>
```
ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v10.15.3
   npm    : 6.4.1
   OS     : macOS Mojave

**Other Information:**

**Comment by dwieeb** [comment]
@mswilson4040 Please post the full command output.

**Comment by mswilson4040** [comment]
@dwieeb That is the exact output I get when I run `ionic info`. Should I run something else?

**Comment by dwieeb** [comment]
Maybe `ionic info --verbose`? I'm not sure why it would try to load that file w/ `ionic info`, or why it would error in such a way.

**Comment by mswilson4040** [comment]
There's a little more info:

`

  ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'info' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +3ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic', execPath: '/Users/marcwilson/dev/headset-mobile', version: '4.12.0' } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic info' [ '--verbose', '--interactive', '--color' ] +0ms
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v10.15.3
   npm    : 6.9.0
   OS     : macOS Mojave


`

**Comment by dwieeb** [comment]
`--verbose` works with every command. Maybe more will be revealed when running `ionic start` with it.

Can you post the contents of both these commands:

`ionic config get`

`ionic config get -g`

**Comment by mswilson4040** [comment]
Sure thing:

```
ionic config get -g
git.setup        | false
npmClient        | 'npm'
ssl.certfile     | './.ionic/ssl/cert.pem'
ssl.keyfile      | './.ionic/ssl/key.pem'
telemetry        | true
tokens.telemetry | '*****'
version          | '4.12.0'
```

And here is the `ionic start <project> --verbose` output:

```
ionic start myproj --verbose
  ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'start', 'myproj' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +4ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic', execPath: '/Users/marcwilson/dev', version: '4.12.0' } +0ms

Let's pick the perfect starter template! 💪

Starter templates are ready-to-go Ionic apps that come packed with everything 
you need to build your app. To bypass this prompt next time, supply template, 
the second argument to ionic start.

? Starter template: blank
  ionic:lib:telemetry Sending telemetry for command: 'ionic start' [ 'myproj',
  ionic:lib:telemetry   'blank',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--project-id=myproj' ] +0ms
✔ Preparing directory ./myproj - done!
  ionic:commands:start Tar extraction created for /Users/marcwilson/dev/myproj +0ms
Error: ENOENT: no such file or directory, open './.ionic/ssl/cert.pem'
  ionic Error: ENOENT: no such file or directory, open './.ionic/ssl/cert.pem' +15s
```

**Comment by dwieeb** [comment]
So yeah, I'm guessing this is the issue:

```
ssl.certfile     | './.ionic/ssl/cert.pem'
ssl.keyfile      | './.ionic/ssl/key.pem'
```

Not sure how those were set, but you can unset them with the following:

```
ionic config unset -g ssl.certfile
ionic config unset -g ssl.keyfile
```

**Comment by mswilson4040** [comment]
Hm. Maybe from some previous usage? Back (a couple of months ago) when this was in beta, I was doing prototyping. Maybe they were included during that? In any case, this can probably be closed. Unsetting those values allowed me to create a new project.

Thanks for your assistance, @dwieeb
