### ISSUE TITLE
Unable to use ionic build --configuration with --engine and --platform

### ISSUE THREAD

**Issue by shuppert** [ionic-team/ionic-cli#3930]
**Description:**

I'm unable to use ionic build with --configuration --engine and --platform.

**Steps to Reproduce:**

I need to target a specific Angular Application Environment file in my project at build time.  
If I use: `ionic build --configuration=MyEnvironment` I can build with the correct environment file.

However, I need to have cordova.js injected into the build and try to use: 
`ionic build --configuration=MyEnvironment --engine=cordova --platform=ios` I get an error: "Configuration 'MyEnvironment' could not be found in project 'app'".  

When used with the --engine=cordova the build command is trying to apply the --configuration parameter to the wrong place.  

Is there a different way to produce a Cordova-compatible build that injects cordova.js correctly when using a specific Environment file?

**Output:**

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/shuppert/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 7 other plugins)

System:

   Android SDK Tools : 26.0.2 (/Users/shuppert/Library/Android/sdk)
   ios-sim           : 7.0.0
   NodeJS            : v10.15.3 (/Users/shuppert/.nvm/versions/node/v10.15.3/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Other Information:**

**Comment by dwieeb** [comment]
@shuppert Using `--engine=cordova` will use `ionic-cordova-build`, not `build`. You can see this in the command output when `ng run` is invoked.

In other words, the configurations you have specified under `"build"` in `angular.json` aren't used with a Cordova build unless you also specify them under `"ionic-cordova-build"`. An example of this is already given: the `"production"` configuration.

More info: https://angular.io/guide/workspace-config#project-tool-configuration-options

**Comment by maxtacco** [comment]
Let me expand on @dwieeb's answer. 

1. Create `environments/environemnt.custom.ts` file with your custom Angular config.
2. Make sure to add new environment configuration to `angular.json` (I use "custom" in this example):
```json
      "ionic-cordova-build": {
          "builder": "@ionic/angular-toolkit:cordova-build",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "custom": {
              "browserTarget": "app:build:custom"
            },
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        },
       "ionic-cordova-serve": {
          "builder": "@ionic/angular-toolkit:cordova-serve",
          "options": {
            "cordovaBuildTarget": "app:ionic-cordova-build",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "custom": {
              "cordovaBuildTarget": "app:ionic-cordova-build:custom",
              "devServerTarget": "app:serve:custom"
            },
            "production": {
              "cordovaBuildTarget": "app:ionic-cordova-build:production",
              "devServerTarget": "app:serve:production"
            }
          }
        }
```
3. Run `ionic build --engine=cordova --platform=ios --configuration=custom` and then `cordova build ios` (you can also try `ionic cordova build ios --no-build`)

Hope this helps.

**Comment by maxtacco** [comment]
You can also add the following script to package.json's scripts:

```json
{
 ...
  "scripts": {
    ...
    "ionic:build:ios:custom": "ionic build --engine=cordova --platform=ios --configuration=custom && cordova build ios"
  },
```
