### ISSUE TITLE
Switch to import types

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#3937]
All over the CLI code base we use `ζ<word>` to signify that the import is meant to be a _type_ import only. [TypeScript 2.9 introduces import types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types). We can use them instead.

**Comment by rdlabo** [comment]
Great!! PhpStorm read ζ is typo. I look forward to this change.
