### ISSUE TITLE
How to reduce Ionic 4 compilation time

### ISSUE THREAD

**Issue by herquiloidehele** [ionic-team/ionic-cli#3944]
I created my new Ionic 4 project, when i run ionic serve, it takes about 40 seconds to compile and reload the application.

I tried to update my node.js version to 11.13.0 but nothing changed.

![Screenshot 2019-04-17 15 34 15](https://user-images.githubusercontent.com/23740775/56294170-ca2d5500-612a-11e9-9779-9870349b85eb.png)

**Comment by dwieeb** [comment]
I'm going to mark this as support. The Ionic CLI uses the Angular CLI to compile web assets and perform serve, so most of this is out of our hands. You may have better luck in the Ionic Forum. If there is something actionable we can do to improve compile times in the framework (such as decreasing bundle sizes, excluding unused code, etc), please open issues in the Framework repo.
