### ISSUE TITLE
Error in ionic serve

### ISSUE THREAD

**Issue by johncris09** [ionic-team/ionic-cli#3966]
After running 
  ionic serve
I got this error:

ERROR in ./src/global.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
[ng]     at getBinding (/home/johncris/Documents/Syntactics/devdacticFire/node_modules/node-sass/lib/index.js:22:11)
[ng]     at Object.<anonymous> (/home/johncris/Documents/Syntactics/devdacticFire/node_modules/node-sass/lib/index.js:188:23)
[ng]     at Module._compile (internal/modules/cjs/loader.js:701:30)
[ng]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
[ng]     at Module.load (internal/modules/cjs/loader.js:600:32)
[ng]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[ng]     at Module.require (internal/modules/cjs/loader.js:637:17)
[ng]     at require (internal/modules/cjs/helpers.js:22:18)
[ng]     at Object.sassLoader (/home/johncris/Documents/Syntactics/devdacticFire/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/theme/variables.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/theme/variables.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
[ng]     at getBinding (/home/johncris/Documents/Syntactics/devdacticFire/node_modules/node-sass/lib/index.js:22:11)
[ng]     at Object.<anonymous> (/home/johncris/Documents/Syntactics/devdacticFire/node_modules/node-sass/lib/index.js:188:23)
[ng]     at Module._compile (internal/modules/cjs/loader.js:701:30)
[ng]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
[ng]     at Module.load (internal/modules/cjs/loader.js:600:32)
[ng]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[ng]     at Module.require (internal/modules/cjs/loader.js:637:17)
[ng]     at require (internal/modules/cjs/helpers.js:22:18)
[ng]     at Object.sassLoader (/home/johncris/Documents/Syntactics/devdacticFire/node_modules/sass-loader/lib/loader.js:46:72)

how to fix this one?

**Comment by dwieeb** [comment]
It looks like your issue is here:

```
[ng] Error: libsass bindings not found. Try reinstalling node-sass?
```

I'm going to mark this as support. Please reserve the issues on Github for qualified bug reports.
