### ISSUE TITLE
Landscape splash image not generated when config.xml sets to portrait only

### ISSUE THREAD

**Issue by cxcxcxcx** [ionic-team/ionic-cli#397]
However, on my iPad Mini, only the landscape sized splash image is requested. I have to remove the "<preference name="orientation" value="portrait"/>" row to generate the proper splash image.

**Comment by jbavari** [comment]
Help me understand a bit more here.

Is this a problem with `ionic resources`?

**Comment by cxcxcxcx** [comment]
yes
