### ISSUE TITLE
[WARN] Command ran non-interactively due to --no-interactive flag, CI being detected, non-TTY, or a config setting.

### ISSUE THREAD

**Issue by Boussarhane** [ionic-team/ionic-cli#3977]
When I run this command `ionic start`, I encounter this Warning

[WARN] Command ran non-interactively due to --no-interactive flag, CI being detected, non-TTY, or a config setting.

Any idea on how to resolve this issue?
Im using Windows 7

**Comment by dwieeb** [comment]
If you're using git bash (the shell provided by Git for Windows), that's why. Git bash is a non-interactive terminal. Use PowerShell or command prompt.
