### ISSUE TITLE
New plugins not showing in config.xml

### ISSUE THREAD

**Issue by tmk1991** [ionic-team/ionic-cli#3979]
**Description:**
New plugins not showing in config.xml

**Steps to Reproduce:**
ionic cordova plugin add cordova-plugin-file --save 
Doesn't show up in config.xml but shows in package.json

ionic cli: 4.12.0
cordova: 9.0.0 (cordova-lib@9.0.1)

**Comment by dwieeb** [comment]
This is a change in Cordova CLI: https://github.com/apache/cordova-lib/pull/750

They are moving away from using `config.xml` for managing platforms and plugins.

**Comment by tmk1991** [comment]
@dwieeb does this mean we can eliminate a config.xml?

**Comment by dwieeb** [comment]
@tmk1991 No, it's still used for many other things. They just wanted to put the package management stuff in `package.json` with the rest of it. (AFAIK).

**Comment by Domvel** [comment]
Does this mean I can remove all `plugin` tags from the config.xml and only manage it in the `cordova` property in package.json? ([Even if it does not work.](https://github.com/apache/cordova/issues/156))

**Comment by dwieeb** [comment]
I believe so, with Cordova 9.
