### ISSUE TITLE
Ionic 4 - ionic generate page returns error after file generation.

### ISSUE THREAD

**Issue by MhmdKorhani** [ionic-team/ionic-cli#3980]
**Description:**
After generating a page: `ionic generate page pageName`. i get an error as if angular cannot see the module of the generate page.

**Steps to Reproduce:**
i tried to import the module into AppModule and i still get the error.

**Output:**
`[ng] ERROR in ./src/app/pages/introduction/introduction.module.ts`
`[ng] Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):`
`[ng] Error: F:\Projects\My Pets\Mobile\myPets\src\app\pages\introduction\introduction.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.`

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Other Information:**

**Comment by dwieeb** [comment]
@MhmdKorhani Use the [Ionic Forum](https://forum.ionicframework.com/) for these sorts of questions.
