### ISSUE TITLE
ionic cordova build android --prod does not produce a production build

### ISSUE THREAD

**Issue by masimplo** [ionic-team/ionic-cli#3985]
**Description:**

Running `ionic cordova build android --configuration=production --prod --release` should produce a production release apk but instead does not replace the environment file and does not run angular production build since the files do not have a hash attached to their names and the code is not uglified. 
Running `ionic build --prod --release --configuration=production` and then `cordova build android --prod --release` has the desired effect though.

**Steps to Reproduce:**

1. Have more than one environments defined in angular.json and have respective environment files
2. Build using ionic cordova build for the non default environment

**Output:**

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 31 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/michael/Library/Android/sdk)
   NodeJS            : v10.15.3 (/Users/michael/.nvm/versions/node/v10.15.3/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by mhartington** [comment]
Hey @masimplo 

So a few things stand out. Why are you running the build with both `--prod` and `--configuration=production`? `--prod` is setting the configuration for you, so if your configuration value is different, I'd assume that it's getting overwritten by the prod flag.

Could you try to build without?

**Comment by masimplo** [comment]
Hi Mike, 

thanks for looking into this. You are right about including both `--prod` and `--configuration` is redundant as it turns (found out by looking at angular cli source) out that --prod is just an alias for `--configuration=production` but I was just trying out things as I could not get the build to work.

For some reason I can no longer reproduce the behaviour I am describing today, although I tried it more than 10 times yesterday before opening this issue to make sure I am not imagining things. It is true that I clean everything and took it from the top, to make sure it is reproducible and turns out it is not.

I am closing this for now and if I stumble upon the same behaviour again, I will open another issue. Thanks for your time.
