### ISSUE TITLE
after updating ionic/cli to 5.0.0 - ionic cordova run android --device not working

### ISSUE THREAD

**Issue by ClickerTech** [ionic-team/ionic-cli#3997]
**Description:**
Not able to run apk on a real device after updating ionic/cli to 5.0.0 .
The device is connected and showing using adb devices
but always app running on the emulator

**Steps to Reproduce:**

`ionic cordova run android --device`

**Output:**
```
> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk
No hardare devices found, attempting emulator...
```

**My `ionic info`:**
```
Ionic:

   Ionic CLI : 5.0.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.0

System:

   NodeJS : v12.3.1
   npm    : 6.5.0
   OS     : Windows 10
```

**Comment by danielsogl** [comment]
Have you read the cli changeling before upgrading and followed the upgrading steps? You can read more about them here: https://github.com/ionic-team/ionic-cli/blob/develop/packages/ionic/CHANGELOG.md#500-2019-05-29

**Comment by ClickerTech** [comment]
thanks

BREAKING CHANGES
i

> onic cordova run/emulate

 no longer use Cordova to deploy apps by default. 

> cordova run

 is the new command

**Comment by ClickerTech** [comment]
thanks

BREAKING CHANGES
i

> onic cordova run/emulate

 no longer use Cordova to deploy apps by default. 

> cordova run

 is the new command
