### ISSUE TITLE
bug: Ionic Start on Ionic 5.0.0

### ISSUE THREAD

**Issue by light8822** [ionic-team/ionic-cli#4000]
# Bug Report

When executing the command : ionic start myApp tabs
brings the next message:

Error: Encountered bad status code (406) for https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-blank.tar.gz

This could mean the server is experiencing difficulties right now--please try again later.
at Request.req.on.res (C:\Users\Miguel\AppData\Roaming\npm\node_modules\ionic\lib\utils\http.js:64:24)
at Request.emit (events.js:198:13)
at Request._emitResponse
(C:\Users\Miguel\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:862:8)
at ClientRequest.req.once.res
(C:\Users\Miguel\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:412:10)
at Object.onceWrapper (events.js:286:20)
at ClientRequest.emit (events.js:203:15)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
at Socket.socketOnData (_http_client.js:442:20)

**Ionic version:**

Ionic:

   Ionic CLI : 5.0.0

Utility:

   cordova-res : 0.3.0
   native-run  : not installed

System:

   NodeJS : v10.16.0
   npm    : 6.9.0
   OS     : Windows 10*

**Comment by dwieeb** [comment]
@light8822 This may be a proxy issue. Are you behind a network proxy? If so, you need to configure your environment for your network proxy:

* Please carefully follow the docs: https://ionicframework.com/docs/cli/configuring.html#using-a-proxy
* Your organization needs to provide proxy details for you. If you don't know the details, talk with your network administrator.
* Remember to avoid disabling SSL verification. This can lead to prolonged insecure configuration with your computer.

**Comment by light8822** [comment]
I´m not using a proxy but this solved when I downgraded the Ionic CLI to 4.0.0
it is posible that the CLI is pointing to an error address? if it is, who I can solve it?

**Comment by dwieeb** [comment]
The issue is either an issue with your network or the server had a momentary hiccup.

Did you try this more than once?

**Comment by light8822** [comment]
yes I tried several times, this issue apeared two days ago.

**Comment by dwieeb** [comment]
Do you have the same issue with Ionic CLI 4.12.0?

**Comment by light8822** [comment]
Only with Ionic CLI 5.0.0

**Comment by light8822** [comment]
this issue have been solved the url now lets install in windows
