### ISSUE TITLE
Unknown option: '--consolelogs' and '--consolelogs-port'

### ISSUE THREAD

**Issue by nikvarma** [ionic-team/ionic-cli#4001]
Hi Guy, I am facing some issue after updating the Ionic cli to Ionic Cli 5.
I am getting below error, Can anybody help me please?.

![image](https://user-images.githubusercontent.com/3116497/58749174-677ce800-8450-11e9-9c04-34c41fa33b71.png)

**Comment by dwieeb** [comment]
You'll need to update `@ionic/angular-toolkit`:

```
npm i @ionic/angular-toolkit@latest
```

**Comment by ioclaudio** [comment]
> You'll need to update `@ionic/angular-toolkit`:
> 
> ```
> npm i @ionic/angular-toolkit@latest
> ```

Hi,
after upgrading angular-toolkit, launching "**ionic serve --devapp**" I have the error:

`C:\ProveElectron\bitsharingapp>ionic serve --devapp
> ng.cmd run app:ionic-cordova-serve --host=0.0.0.0 --port=8100 --cordova-mock --consolelogs --consolelogs-port=53703
[ng] Schema validation failed with the following errors:
[ng]   Data path ".builders['cordova-build']" should have required property 'class'.

[ERROR] ng has unexpectedly closed (exit code 1).

        The Ionic CLI will exit. Please check any output above for error details.`

**Comment by ioclaudio** [comment]
I've solved upgrading angular-toolkit not at the latest version but from 1.4.0 to 1.5.1 (latest was 2.0.0):

`-    "@ionic/angular-toolkit": "~1.4.0",
+    "@ionic/angular-toolkit": "~1.5.1",`

**Comment by dwieeb** [comment]
`@ionic/angular-toolkit` v2 is for Angular 8, as the [CHANGELOG.md](https://github.com/ionic-team/angular-toolkit/blob/master/CHANGELOG.md#200-2019-06-25) indicates.

**Comment by WinnersProx** [comment]
> I've solved upgrading angular-toolkit not at the latest version but from 1.4.0 to 1.5.1 (latest was 2.0.0):
> 
> `- "@ionic/angular-toolkit": "~1.4.0",
> 
> * "@ionic/angular-toolkit": "~1.5.1",`

So awesome it worked for me

**Comment by Gautammer** [comment]
> I've solved upgrading angular-toolkit not at the latest version but from 1.4.0 to 1.5.1 (latest was 2.0.0):
> 
> `- "@ionic/angular-toolkit": "~1.4.0",
> 
> * "@ionic/angular-toolkit": "~1.5.1",`

Thanks bro , it worked !!!!

**Comment by rmitchbr** [comment]
Its quite simple to solve this.

On terminal:

npm uninstall @ionic/angular-toolkit --save
npm install @ionic/angular-toolkit@1.5.1
ionic serve --devapp

Thats it.
