### ISSUE TITLE
Ionic Lab, CLI 5 - Menu icon different colors

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#4003]
**Description:**

Menu icon different colors 

**Steps to Reproduce:**

Create new menu starter
open in lab
looks at result

**Output:**

![Capture568](https://user-images.githubusercontent.com/140737/58770152-f9c0e100-8561-11e9-9391-7a4e79f62470.png)

![Capture567](https://user-images.githubusercontent.com/140737/58770159-fe859500-8561-11e9-9536-5ac369ccd338.png)

**My `ionic info`:**

```
C:\ae\adaept.com\labtest>ionic --version
5.0.0

C:\ae\adaept.com\labtest>ionic info

Ionic:

   Ionic CLI                     : 5.0.0 (C:\Users\peter\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10


C:\ae\adaept.com\labtest>
```

**Other Information:**

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.
