### ISSUE TITLE
Multi Project App

### ISSUE THREAD

**Issue by hhasenauer** [ionic-team/ionic-cli#4009]
**Description:**
I am having the exact same problem as described here: https://stackoverflow.com/questions/55760367/how-to-create-a-multi-apps-project-in-ionic-4
I did not find an open issue here where this problem is tracked. Is there any more information on this?

**Comment by dwieeb** [comment]
The error is from the Angular CLI:

```
[ng] Project 'app1' could not be found in workspace.
[ng] Error: Project 'app1' could not be found in workspace.
```

You have to also change your workspace (`angular.json`) to account for the project you want. Basically, change the references to the project key where necessary, as the answer to that SO question suggests. More info: https://angular.io/guide/workspace-config

**Comment by hhasenauer** [comment]
@dwieeb  So the second angular.json within the second project can be deleted after that right?

**Comment by dwieeb** [comment]
Yeah! You can have a single `angular.json` in the root of your monorepo. I apologize our docs aren't very good, but multi-app projects are pretty rare, and we're trying to prioritize.

**Comment by hhasenauer** [comment]
@dwieeb Okay thank you. I understand the solution, I just thought it was planned to maybe automate this and not create a second package.json and angular.json. Will this be not the case?

**Comment by dwieeb** [comment]
You'll probably need a `package.json` for each app. If you're using lerna, you can hoist dependencies, which I've found very useful. But a single `angular.json` should work. Angular supports monorepos out of the box.

Automating the creation of multi-app projects is not something on our "roadmap".
