### ISSUE TITLE
Ionic CLI overrides an Angular project architecture

### ISSUE THREAD

**Issue by Donil** [ionic-team/ionic-cli#4017]
For an Ionic project angular.json file contains architecture sections "ionic-cordova-build" and "ionic-cordova-serve", but during building Ionic CLI [overrides ](https://github.com/ionic-team/ionic/blob/10de1da9480896c58bedde06ee022c1456d68354/angular/src/schematics/add/index.ts#L72) them to hardcoded targets which names always start with "app:"

I expect that Ionic CLI will use architecture configuration specified in angular.json, because I have an Angular application with multiple projects inside where one of project is an Ionic project and I want to provide specific project name for it, instead of just "app".

**Comment by dwieeb** [comment]
@Donil This isn't well documented, but try using commands with the `--project` option. It looks like `--project` isn't working for Cordova commands, so I just pushed a fix: https://github.com/ionic-team/ionic-cli/commit/fb9ff0fd08364028d254f0ab7ca3739974fcf12f

**Comment by Donil** [comment]
@dwieeb , yes it works. Thank you!
