### ISSUE TITLE
Cannot disable gulp integration

### ISSUE THREAD

**Issue by 814k31** [ionic-team/ionic-cli#4021]
**Description:**

@ionic/toolkit-v1 doesn't respect ionic.config.json gulp option
```json
"gulp": {
    "enabled": false
}
```

**Steps to Reproduce:**
Affected commands:
`ionic cordova build  <platform>`
`ionic cordova run <platform>`

**Output:**
```
Error: Cannot find module '<project-root>/gulpfile.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at <project-root>/node_modules/@ionic/v1-toolkit/dist/lib/gulp.js:29:17
    at Generator.next (<anonymous>)
    at <project-root>/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (<project-root>/node_modules/tslib/tslib.js:106:16)
    at loadGulp (<project-root>/node_modules/@ionic/v1-toolkit/dist/lib/gulp.js:13:20)
```

**My `ionic info`:**

```
Ionic:

   Ionic CLI         : 5.0.2
   Ionic Framework   : unknown
   @ionic/v1-toolkit : 2.0.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : no whitelisted plugins (24 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.13.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

```

**Other Information:**
gulp also is not in my package.json at all as was researching:
https://stackoverflow.com/questions/45810520/ionic-cli-error-gulpfile-or-dependent-module-not-found-gulpfile-js

**Comment by dwieeb** [comment]
@814k31 You may have an issue with your gulpfile. Try running `gulp <task>` directly to see what's wrong.

**Comment by 814k31** [comment]
@dwieeb I am trying to disable gulp integration such that I don't need a gulpfile or gulp dependencies.

I can run cordova commands just find. but I cannot use the ionic cli cordova wrapper.

The ionic config gulp disable config is not respected by @ionic/toolkit-v1 which is why I have created this issue.

**Comment by dwieeb** [comment]
😂 Sorry, I skimmed this issue. 

You're using Ionic 1, correct?

**Comment by 814k31** [comment]
@dwieeb All good haha
yes... unfortunately 😂
haven't made the change just yet

**Comment by dwieeb** [comment]
I'm not sure v1-toolkit will be especially useful without gulp. What do you expect it to do? 

If you have a custom build process, you want to override build and serve using Ionic hooks with npm scripts: https://ionicframework.com/docs/cli/configuration#overriding-the-build

**Comment by 814k31** [comment]
@dwieeb ahh okay, I'm not familiar with what the toolkit actually does. I had changed my build process to use webpack instead of a gulp/browserify process.
I've swapped my commands to directly use cordova which seems to be suit just fine though so feel free to close the issue if you want.

I may have a play with the build overriding another time
Thanks!

**Comment by dwieeb** [comment]
Alright! Mind if I close this then?

**Comment by 814k31** [comment]
All good to close

thank for your time
