### ISSUE TITLE
'cordova-res' on 'ionic cordova platform add {platform}'

### ISSUE THREAD

**Issue by diegozuber** [ionic-team/ionic-cli#4026]
**Description:**
If I'm not logged into my Ionic Account in the CLI, the resources don't generating on `ionic cordova platform add {platform}`.

_Please ignore this issue if this behaviour is expected like this._

**Steps to Reproduce:**
1. Make sure you're not logged in (in the CLI)
2. `ionic cordova platform add {platform}`
3. No resources are generated
4. Login with your Ionic Account `ionic login`
5. `ionic cordova platform add {platform}`
6. Resources are generated as expected

**My `ionic info`:**
Ionic:
   Ionic CLI          : 5.0.1
   Ionic Framework    : ionic-angular 3.9.6
   @ionic/app-scripts : 3.2.3

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 14 other plugins)

Utility:
   cordova-res : 0.3.0
   native-run  : not installed

System:
   Android SDK Tools : 26.1.1
   NodeJS            : v10.16.0
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

**Comment by dwieeb** [comment]
Thanks @diegozuber ! Looks like some logic was leftover from when using Ionic servers for resource generation was the default. This will be fixed in the next version 👌
