### ISSUE TITLE
ERR_NO_DEVICE: No hardware devices found.

### ISSUE THREAD

**Issue by Incubbus** [ionic-team/ionic-cli#4031]
**Description:**

The command `ionic cordova run android --device` fails with

> ERR_NO_DEVICE: No hardware devices found. Not attempting emulator because --device was specified.
[ERROR] An error occurred while running subprocess native-run

**Steps to Reproduce:**

Just use the command above to test an app on an android device.

**Output:**

```
native-run Caught fatal error: { Error: No hardware devices found. Not attempting emulator because --device was specified.
    at selectDevice (C:\Users\\AppData\Roaming\npm\node_modules\native-run\dist\android\run.js:82:19) code: 'ERR_NO_DEVICE', exitCode: 1, data: undefined }
ERR_NO_DEVICE: No hardware devices found. Not attempting emulator because --device was specified.
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.
```

**My `ionic info`:**

```
Ionic:

   Ionic CLI          : 5.0.2 (C:\Users\jp\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.6
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-webview 1.2.1, (and 17 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.5

System:

   Android SDK Tools : 26.1.1 (C:\Users\\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Other Information:**

Seems related to https://github.com/ionic-team/native-run/issues/42. 

Temporarily downgrading back to ionic 4.x.x helps.

**Comment by dwieeb** [comment]
Tracking here: https://github.com/ionic-team/native-run/issues/42#issuecomment-502145573

**Comment by labmux** [comment]
I still cant find my connected android device using native-run --list

**Comment by dwieeb** [comment]
@labmux Can you make sure you're on the latest version of `native-run`? If it still doesn't recognize, please create a new issue in the native-run repo: https://github.com/ionic-team/native-run

**Comment by developbat** [comment]
> I still cant find my connected android device using native-run --list

checkdebug mod is on  android device

**Comment by harunme3** [comment]
may be your debug option is off
