### ISSUE TITLE
iOS Build Failed Xcode 10 Ionic 5.0.1

### ISSUE THREAD

**Issue by DMatt06** [ionic-team/ionic-cli#4032]
**Description:**

When trying to build an iOS release using ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0" I get xcodebuild: Command failed with exit code 65
**Steps to Reproduce:**

I have deleted node_modules, iOS platform folder and confirmed automatic signing is enabled.   

**Output:**

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/guru/Library/Developer/Xcode/DerivedData/Beaudentity-fhiqjrrphzbcmagcinigmhuqbeny/Build/Intermediates.noindex/Beaudentity.build/Debug-iphonesimulator/Beaudentity.build/Objects-normal/x86_64/CDVPlugin+APPAppEvent.o Beaudentity/Plugins/cordova-plugin-app-event/CDVPlugin+APPAppEvent.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.

        cordova build ios --buildFlag=-UseModernBuildSystem=0 exited with exit
        code 65.

**My `ionic info`:**

```
Ionic:

   Ionic CLI          : 5.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-webview 1.2.1, (and 19 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/guru/Library/Android/sdk)
   ios-deploy        : 1.8.4
   ios-sim           : 8.0.1
   NodeJS            : v10.16.0 (/usr/local/Cellar/node/8.8.1/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Other Information:**

**Comment by dwieeb** [comment]
@DMatt06 I would try asking this in the Ionic Forum: https://forum.ionicframework.com
