### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by rshyambabu** [ionic-team/ionic-cli#4038]
**Description:**
A spell check is missing

**Steps to Reproduce:**
While running the command: C:\Users\Shyam\AndroidStudioProjects\TGCFinal>ionic cordova run android -l -c --native-run

**Output:**
native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk --connect --forward 8100:8100
[native-run] No **hardare** devices found, attempting emulator...
[native-run] Selected emulator BH906DYT17
[native-run] Forwarded device port 8100 to host port 8100
[native-run] Installing platforms\android\app\build\outputs\apk\debug\app-debug.apk...
[native-run] Starting application activity io.ionic.starter/io.ionic.starter.MainActivity...
[native-run] Run Successful
[native-run] Waiting for app to close...

**My `ionic info`:**
Ionic CLI 5.0.1

**Comment by dwieeb** [comment]
Whoops, thanks!
