### ISSUE TITLE
Error ionic cordova run android (CLI 5.0.3) :app:transformDexArchiveWithExternalLibsDexMergerForDebug

### ISSUE THREAD

**Issue by NurGuz** [ionic-team/ionic-cli#4041]
Now I have an error, and yesterday works correctly:

> D8: Program type already present: android.support.v4.os.ResultReceiver$1
> 
> FAILURE: Build failed with an exception.
> 
>  What went wrong:
> Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
>  com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
>   Program type already present: android.support.v4.os.ResultReceiver$1
>   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
> 
>  Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
>  Get more help at https://help.gradle.org
> 
> BUILD FAILED in 11s
>  Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
> 35 actionable tasks: 2 executed, 33 up-to-date
> C:\Users\nuria.guzman.tenorio\Desktop\Accenture\Proyectos\apa\platforms\android\gradlew: Command failed with exit code 1 Error output:
> D8: Program type already present: android.support.v4.os.ResultReceiver$1
> 
> FAILURE: Build failed with an exception.
> 
>  What went wrong:
> Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
>  com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
>   Program type already present: android.support.v4.os.ResultReceiver$1
>   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

Ionic info:

> Ionic:
> 
>    Ionic CLI                     : 5.0.3 
>    Ionic Framework               : @ionic/angular 4.5.0
>    @angular-devkit/build-angular : 0.12.4
>    @angular-devkit/schematics    : 7.2.4
>    @angular/cli                  : 7.2.4
>    @ionic/angular-toolkit        : 1.3.0
> 
> Cordova:
> 
>    Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
>    Cordova Platforms : android 8.0.0
>    Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 6 other plugins)
> 
> Utility:
> 
>    cordova-res : 0.3.0
>    native-run  : 0.2.6
> 
> System:
> 
>    Android SDK Tools : 26.1.1
>    NodeJS            : v11.10.1 (C:\Program Files\nodejs\node.exe)
>    npm               : 6.7.0
>    OS                : Windows 10

**Comment by VIMHaos** [comment]
Same problem today ,(
Tried recovery previous versions ionic@5.0.2 or ionic@5.0.1, but not fixes that problem ..

**Comment by dwieeb** [comment]
Changing your Ionic CLI version will not solve this problem. It is related to Cordova. You may have better luck posting this in the Ionic Forums.
