### ISSUE TITLE
Notify about updates for native-run and cordova-res

### ISSUE THREAD

**Issue by luciojb** [ionic-team/ionic-cli#4043]
Hello. I've been updating ionic but, as it uses native-run to run on my android device, i don't have seen it update it. Like, i run `npm i -g ionic` and it updates ionic, but i have to update native-run manually. It is a very hard thing to remember, as i only have the time to update it if i stick a note somewhere or if i'm updating everything on my project. It's a bad behavior to have this tools separated, as it excludes the idea of transparency. If you change the tool to run on devices as a separated tool/dependency, like you first did with the 5.0.0 update (i had to run with the flag --no-native-run for a time before the bugs were fixed), then i think is best if you actually manage this dependency and update it to a better user experience. Same thing with cordova-res.

**Comment by dwieeb** [comment]
It'd be ideal, but these tools are installed globally, so we can never truly trust the permissions. The Ionic CLI used to update itself but it was a nightmare because most global `node_modules` were owned by root and it couldn't write to the folder.

The most we can do is provide update notifications for tools we rely on.

**Comment by luciojb** [comment]
This was a great fast response. Exactly what i needed to hear, thank you very much. I'm closing this now, maybe in the future we'll have better tools. Some day i'll see if it happens with projects on the new capacitor and ionic 4. Cheers and good work, thanks for the work on Ionic until now!

**Comment by dwieeb** [comment]
I figured we'd keep it open to add that update notification for tools we rely on 💪
