### ISSUE TITLE
Add generate web-worker support (Angular 8)

### ISSUE THREAD

**Issue by ralscha** [ionic-team/ionic-cli#4044]
The current version of `ionic generate` does not support `web-worker`

#### Plain Angular 8 app
```
ng new myAngularApp
cd myAngularApp
ng generate web-worker my-worker
```

#### Ionic App
```
ionic start myIonicApp blank
cd myIonicApp
# Upgrade to Angular 8
ng update @angular/cli @angular/core @angular-devkit/architect @angular-devkit/core @angular-devkit/schematics --force

ionic generate web-worker my-worker
# ERROR] web-worker is not a known feature.

ng generate web-worker my-worker
# Schematic "web-worker" not found in collection "@ionic/angular-toolkit".
```

#### Workaround
   - Open angular.json
   - Remove
      ```
      "cli": {
         "defaultCollection": "@ionic/angular-toolkit"
      },
      ```
 - Run `ng generate web-worker my-worker`
 - Re-add `"cli"` to angular.json

**Comment by mhartington** [comment]
Will be part of https://github.com/ionic-team/angular-toolkit/pull/132

**Comment by ralscha** [comment]
`ng generate web-worker TestWorker` works now after an upgrade to 
`"@ionic/angular-toolkit": "2.0.0"`

Thanks.

**Comment by tyliggity** [comment]
This is broken again.  Had to do the workaround.  I am using `@ionic/angular-toolkit": "^6.0.0"`

**Comment by ralscha** [comment]
Also broken in @ionic/angular-toolkit version 7.0.0 
Also `ng generate service-worker` does not work.

**Comment by tyliggity** [comment]
This is broken again.  Had to do the workaround.  I am using `@ionic/angular-toolkit": "^6.0.0"`
