### ISSUE TITLE
Feature Request: Make `ionic repair` only remove `package-lock.json` with an option

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-cli#4048]
Currently `ionic repair` will:

1. rm -rf node_modules/ plugins/ platforms/
1. rm package-lock.json
1. npm i
1. re-add the platforms

Or some variant thereof.

The problem I have with it is the removal of the `package-lock.json` file, which I believe should only be done under extreme circumstances where-as the rebuilding of `plugins/` and `platforms/` is basically always safe and is often necessary when upgrading plugins due to Cordova's aggressive caching.

We have run into issues with some enterprise customers where they have used `ionic repair` in order to fix issues with the plugins only to also accidentally upgrade all of their dependencies at the same time (luckily, in most cases they were using `~`, but a few were using `^`, which we have coached them not to do, but still... 

Given that the most common use case here is the plugins having gotten out of whack, I believe the removal of the `package-lock.json` file is a bit too aggressive with the exception of very odd cases, and thus should be controlled via an argument to the command.

**Comment by dwieeb** [comment]
There are plenty of cases where removing the lock file resolves issues caused by an adverse installation of `node_modules`. Since the lock file represents a `node_modules` installation 1:1, people would `rm -rf node_modules && npm install` with no change in behavior, yet doing `rm -fr node_modules package-lock.json && npm install` fixed their issue.

There should be an option for it, but I'm not convinced the default should change.

**Comment by kensodemann** [comment]
I guess which one makes sense would mostly be based on which is more common, `node_modules` having some sort of adverse install or the need to rebuild `plugins` and `platforms` after upgrading a plugin.

I have run into the latter far more often than the former, very rarely having to blow away the lock file but often needing to rebuild the `plugins` and `platforms` due to Cordova's over-aggressive caching... 🤷🏻‍♂️

Maybe an `ionic repair --cordova` option that _just_ does that bit?

**Comment by dwieeb** [comment]
Perfect!

**Comment by bryplano** [comment]
So just for reference, `ionic repair --cordova` will do:

1. rm -rf node_modules/ plugins/ platforms/
2. npm i
3. re-add the platforms

Correct?

**Comment by dwieeb** [comment]
I took it to mean _only_ work with Cordova.

1. `rm -rf plugins/ platforms/` 
1. `cordova prepare`

**Comment by bryplano** [comment]
Ah I see. So there would not be any option for `node_modules` to be deleted & reinstalled because

> Since the lock file represents a node_modules installation 1:1, people would rm -rf node_modules && npm install with no change in behavior
