### ISSUE TITLE
Don't exit process when app is closed

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/ionic-cli#4060]
When I'm running my app in livereload mode I sometimes want to do a full restart of the app. Unfortunately native-run and the Angular Livereload server process are exited when I close the app and I have to rerun the livereload command.

**Comment by dwieeb** [comment]
@RafaelKr For now you can use `--no-connect` to disable that behavior. The default changed in CLI 5 to make it easier for beginners. Looks like we have some interest in switching that default back.

**Comment by RafaelKr** [comment]
Thank you very much, `--no-connect` leads to the expected behavior.

I definitely think this would make sense as default.
What are your thoughts about "make it easier for beginners"? I can't really see an advantage.

**Comment by dwieeb** [comment]
There's a lot of confusion about livereload and how it works. The idea is that if the app and the process were connected (i.e. one would die if the other dies), then it would give the impression that they were codependent, as opposed to _without_ the `--livereload` flag, where the command simply builds and deploys the app and it can be used without any running processes.

I think overall you're right, it's probably not a good default. It's annoying to have to restart the server if the app is closed.

**Comment by RafaelKr** [comment]
My thought about that is that `--livereload` implicates, that the server should be running until I close it.

Thank you for bringing back the previous default behaviour!

**Comment by dwieeb** [comment]
5.2.2 is out with the default behavior reverted!
