### ISSUE TITLE
Support cordova-android < 7

### ISSUE THREAD

**Issue by rodrigograca31** [ionic-team/ionic-cli#4061]
**Version:**

0.2.6

**Description:**

If a project is using for example cordova-android 6.4.0 the .apk location is different and it fails to find the .apk....

**Command Output:**

```
BUILD SUCCESSFUL

Total time: 7.208 secs
Built the following apk(s): 
        /home/unknown/git/PROJECT/platforms/android/build/outputs/apk/android-debug.apk
> native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk --device
Selected hardware device 566ac2eb0704
Error: ENOENT: no such file or directory, open 'platforms/android/app/build/outputs/apk/debug/app-debug.apk'
[ERROR] An error occurred while running subprocess native-run.
        
        native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug... exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

after using cordova-android 8:
```
ionic cordova platform rm android
ionic cordova platform add android@^8.0.0
ionic cordova run android --device
```
works flawlessly:

```
BUILD SUCCESSFUL in 39s
42 actionable tasks: 42 executed
Built the following apk(s): 
        /home/unknown/git/PROJECT/platforms/android/app/build/outputs/apk/debug/app-debug.apk
> native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk --device
Selected hardware device 566ac2eb0704
Installing platforms/android/app/build/outputs/apk/debug/app-debug.apk...
```

**SDK Info:**

~~too much unnecessary info~~

**Comment by dwieeb** [comment]
@rodrigograca31 This is actually an Ionic CLI issue. `native-run` itself is compatible, but we're just looking in the wrong place in the CLI for earlier versions of `cordova-android`.

**Comment by dwieeb** [comment]
I don't think `cordova-android` < 7 will be supported. It's just not a priority for us. Luckily, there's a workaround that opts you into the old flow. Use the `--no-native-run` option to switch back to relying solely on Cordova:

```
ionic cordova run android -l --no-native-run
```

**Comment by rodrigograca31** [comment]
Meh.... I also wont be using older versions of `cordova-android` but I thought it would be a simple fix like: there's no .apk here lets check there, done.
