### ISSUE TITLE
Misleading `cli generate --help` output

### ISSUE THREAD

**Issue by ZaLiTHkA** [ionic-team/ionic-cli#4063]
**Description:**

The output of `ionic generate --help` states that:

>--no-module ..................... Do not generate an NgModule for the component

The `ionic generate component` command seems to always create or update a `src/components/components.module.ts` file.

I realise that a `page` is for all intensive purposes a `component`, this is rather confusing because the `--no-module` option appears to only affect the `ionic generate page` command.

Most of my own apps are really small and simple, so I don't use a separate module to import my components, which means I have to constantly remove this file and manually update my main `src/app/app-module.ts` file instead.

Is this intended behaviour with the `generate` command?

**Steps to Reproduce:**

1. open a terminal inside an existing Ionic app
1. run the command `ionic generate component my-awesome-component --no-module`
1. check contents of `src/components/`

**Output:**

n/a

**My `ionic info`:**

```
Ionic:

   Ionic CLI          : 5.2.1 (C:\Users\agreeff\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.6
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.0, (and 20 other
plugins)

Utility:

   cordova-res : 0.5.1
   native-run  : 0.2.7

System:

   Android SDK Tools : 26.1.1 (C:\android-sdk)
   NodeJS            : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Other Information:**

n/a

**Comment by dwieeb** [comment]
I'm not sure what happened here. Looking at the code, there doesn't seem to be a way to configure this: ﻿https://github.com/ionic-team/ionic-app-scripts/blob/master/src/generators/util.ts#L197-L199

I'm going to remove both these options. I don't think we'll be adding this functionality, as we're focused on Ionic 4 now.
