### ISSUE TITLE
run ios runs only on one device in the new CLI 5.2.1

### ISSUE THREAD

**Issue by tareqdayya** [ionic-team/ionic-cli#4070]
Hi, everyone.
Ever since i updated my cli to version 5, currently at 5.2.1, the ionic cordova run ios command refuses to run on more than one device at a time. In the 4 version, i used to connect multiple devices and simulators and it would serve them all simultaneously. That's no longer the case. Now it either runs a device or a simulator, and i it no longer serves multiple devices.

The usual command that i run now is: ionic cordova run ios -l --consolelogs --address=0.0.0.0 --no-native-run.
I have tried without the --consolelogs, without the --address, and without the --no-native-run, but to no avail. Whenever i plug a new device while the application is being served, it says "skipping MY_DEVICE_NAME MY_DEVICE_ID." And if i open the simulator, nothing happens.

In Ionic CLI 4, i used to run the command: ionic cordova run ios -l. And it would just run on any device that was connected, and any simulator that had the app installed.

Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.800.4
   @angular-devkit/schematics    : 8.0.4
   @angular/cli                  : 8.0.4
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 12 other plugins)

Utility:

   cordova-res : 0.5.1 (update available: 0.5.2)
   native-run  : 0.2.7 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.10.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by dwieeb** [comment]
Have you verified that reverting to Ionic CLI 4 yields the correct behavior again? 

`npm uninstall -g ionic`
`npm install -g ionic@4`

**Comment by tareqdayya** [comment]
I did, and i think i figured out what the problem is. It's got nothing to do with the ionic version.

The run command, on both CLI versions, installs the app on only one device, and it favors actual devices to simulators. In order to run the app simultaneously on more than one device you need to prepare then install the app on each device via xcode ALL WHILE the ionic server is running and serving the app. You can then quit xcode and the server will be running the app on all devices where the app was installed in this manner. This has to be done just once, unless you uninstall the app. You can close and open the app and it will connect to the server each time without any issues.

 My mistake was that i was not running the ionic server when i was installing the app via xcode.
