### ISSUE TITLE
ionic build with @ionic/lab 

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic-cli#4078]
hey!
We really love @ionic/lab to quickly get a response of the two App versions (we ship iOS and Android variants of our App).
This is nice for developers but for the designers, Q&A etc. we can't provide this experience because we need to build the App and there's no possibility to build the App within @ionic/lab.

If it is not that much effort for you to provide this kind of feature, we would be really happy if you could consider to implement this in future CLI versions! :)

**Comment by dwieeb** [comment]
This isn't really what Ionic Lab is for. 

This would be possible, however, with multiple seats of [Ionic Studio](https://ionicframework.com/studio).

**Comment by carstenbaumhoegger** [comment]
alright, thanks for your response! I'll take a look at Ionic Studio.
