### ISSUE TITLE
`--livereload` should not edit root config files

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/ionic-cli#4089]
**Description:**

ionic capacitor run [platform] --livereload should not edit root capacitor.config.json file, but the platform one (`ios/App/App/capacitor.config.json`  or `android/app/src/main/assets/capacitor.config.json`) and restore them after stopping the server. 

Right now it edits the root capacitor.config.json file and it gets restored when stopping the server, but as the file has been copied to the platforms files, the server values remain in them.

Or alternatively, run npx cap copy after restoring the root capacitor.config.json to also restore the platform files.

**Comment by dwieeb** [comment]
Why this isn't an issue for Cordova?

**Comment by jcesarmobile** [comment]
Cordova doesn't have a capacitor.config.json file, so not sure if I understand the question

But in Cordova the CLI doesn't modify the root config.xml, just the ones in platforms, change them to something like `<content original-src="index.html" src="http://localhost:8100" />` and don't change it back when stopping the web server, so should be fixed too.

**Comment by dwieeb** [comment]
The Ionic CLI does change the root `config.xml` for Cordova during `ionic cordova run` in the exact same way that it changes the root `capacitor.config.json` for Capacitor during `ionic capacitor run`.

Inspecting `platforms/ios/MyApp/config.xml` reveals that this issue also exists for `ionic cordova run`.

**Comment by jcesarmobile** [comment]
Now that we added the cleartext option, that needs to be on the root file since cleartext is read by the CLI, not by the platforms, so not sure if this issue is still relevant

**Comment by dwieeb** [comment]
We could still run `copy` after restoring the root config.

**Comment by jcesarmobile** [comment]
Yeah, that sounds good
