### ISSUE TITLE
Feature components imported as 'FeaturePage' in spec.ts

### ISSUE THREAD

**Issue by noellethenerd** [ionic-team/ionic-cli#4090]
**Description:**
When using CLI to generate components, feature.spec.ts automatically looks for a page version instead of a component version. This has happened every time I've tried it so far, and it is more annoying than actually necessary required to be fixed because it can just be changed manually once you realise it, but thought y'all might want to know. Thanks :)

**Steps to Reproduce:**
`ionic g c feature`

**Output:**
```
CREATE src/app/feature/feature.component.scss (0 bytes)
CREATE src/app/feature/feature.component.html (26 bytes)
CREATE src/app/feature/feature.component.spec.ts (698 bytes)
CREATE src/app/feature/feature.component.ts (272 bytes)
```
In `...feature.component.spec.ts` it always does `import { FeaturePage } from './feature.component';` and needs to be changed to ` { FeatureComponent }`

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v11.4.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Other Information:**

**Comment by dwieeb** [comment]
This was fixed in `@ionic/angular-toolkit` 1.4.1. Please update to the latest:

```
npm i @ionic/angular-toolkit@1
```

We are looking into having this update automatically with `ng update` in this issue: https://github.com/ionic-team/ionic-cli/issues/3686

Thanks!
