### ISSUE TITLE
ionic cordova plugin add cordova-plugin-app-preferences Not installing in latest cordova 9.

### ISSUE THREAD

**Issue by amitgandole** [ionic-team/ionic-cli#4091]
Here is the response of "ionic cordova plugin add cordova-plugin-app-preferences" :

`Installing "cordova-plugin-app-preferences" for android
Failed to install 'cordova-plugin-app-preferences': CordovaError: Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (C:\pathTo\node_modules\cordova-lib\src\hooks\Context.js:57:15)
    at module.exports (C:\pathTo\plugins\cordova-plugin-app-preferences\bin\before_plugin_install.js:6:14)
    at runScriptViaModuleLoader (C:\pathTo\node_modules\cordova-lib\src\hooks\HooksRunner.js:181:32)
    at runScript (C:\pathTo\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:16)
    at C:\pathTo\node_modules\cordova-lib\src\hooks\HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd plugin add cordova-plugin-app-preferences exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.`

Its working when I use this : "cordova plugin add cordova-plugin-app-preferences" but not with "ionic cordova plugin add cordova-plugin-app-preferences

**Comment by jcesarmobile** [comment]
This is a bug in the plugin, has to be fixed there, cordova 9 removed requireCordovaModule and plugins need to be updated to not use it. 
It's already reported in their repo https://github.com/apla/me.apla.cordova.app-preferences/issues/147
