### ISSUE TITLE
`ionic start` should ask for the framework

### ISSUE THREAD

**Issue by lcswillems** [ionic-team/ionic-cli#4118]
It would be nice if `ionic start` asks for the framework we want to use (angular, react or vue)

**Comment by dwieeb** [comment]
@lcswillems We had planned on this when Ionic React reaches 1.0 final, but I see no reason why we can't do something like:

Choose your framework:
- Angular (stable)
- React (RC)
- Vue (experimental)

**Comment by lcswillems** [comment]
I think it would be a good idea! It would make creation of projects easier, because every time, I have to search the doc to know the good parameter name and value.
