### ISSUE TITLE
Support Angular CLI prompts for generators

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#4122]
ref: https://github.com/ionic-team/ionic-cli/issues/4058

**Comment by dwieeb** [comment]
We should probably solve this by removing the prompts from the Ionic CLI and relying entirely on the Angular CLI for input to the schematics. This means we'll need to change how we run the Angular CLI for the `ionic generate` command to inherit the stdio streams so that its interactive prompts can be used.

**Comment by mhartington** [comment]
I dont think we should remove our prompts all together. Not all the ng schematics actually have prompts, so in some cases it's nice to have an extra guard there to make sure things are working correctly. 

If that ever becomes the case where everything has a prompt/check on angular's end, then yeah, we could remove the prompts all together for angular.

**Comment by dwieeb** [comment]
Closed by https://github.com/ionic-team/ionic-cli/pull/4123
