### ISSUE TITLE
Cannot build android

### ISSUE THREAD

**Issue by PunkHaz4rd** [ionic-team/ionic-cli#4128]
**Description:**
I'm having trouble getting anything built even though in the browser the app is working fine.

**Steps to Reproduce:**
$> ionic start Presto sidemenu --type=angular
added angular sources to src/
$> ionic cordova platform add android
also added resources with cordova-res

**Output:**
resources/android/xml/network_security_config.xml was not created.
$> ionic cordova prepare android
project 'app' was not found in workspace
 
$> ionic cordova build android --project Presto
project 'Presto' was not found in workspace

$> ionic cordova build android --project presto
project 'presto' was not found in workspace

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\romai\nvm\v12.4.0\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   NodeJS : v12.4.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Other Information:**
In every files concerned, the name of the app is either Presto or presto:
package,json, config.xml, ionic.config.json, angular.json

Now is there something I'm missing ?

**Comment by dwieeb** [comment]
The `--project` flag is for multi-app projects. You won't need it for regular projects.

The biggest issue here is this:
> project 'app' was not found in workspace

Did you modify `angular.json`? What is the project key? Look for `projects` -> `<key>` in the JSON
