### ISSUE TITLE
[native-run] ERR_UNKNOWN: Path 'platforms/ios/build/device/

### ISSUE THREAD

**Issue by MarkAMcCorkle** [ionic-team/ionic-cli#4131]
Version:

0.2.8

Description:

Cannot install to device using `ionic cordova run ios --device`. Standard command from native-run works fine. Appears to be a pathing issue.

This works.
`native-run ios --app platforms/ios/build/device/myapp.ipa`

This does not work.
`ionic cordova run ios --device`

Command Output:

native-run ios --app platforms/ios/build/device/
myapp
.ipa --device
[native-run] ERR_UNKNOWN: Path 'platforms/ios/build/device/
[native-run] myapp
[native-run] .ipa' not found
[ERROR] An error occurred while running subprocess native-run.

    native-run ios --app platforms/ios/build/device/
    		myapp
    	.ipa --device exited with exit code 1.
Environment Info:

Ionic:

Ionic CLI : 5.2.5 (/usr/local/lib/node_modules/ionic)
Ionic Framework : @ionic/angular 4.7.4
@angular-devkit/build-angular : 0.13.9
@angular-devkit/schematics : 7.3.9
@angular/cli : 7.3.9
@ionic/angular-toolkit : 1.5.1

Cordova:

Cordova CLI : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 8.0.0, ios 5.0.1
Cordova Plugins : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 21 other plugins)

Utility:

cordova-res : 0.3.0 (update available: 0.6.0)
native-run : 0.2.8

System:

Android SDK Tools : 26.1.1 (/Users/markmccorkle/Library/Android/sdk/)
ios-deploy : 1.9.4
ios-sim : 8.0.1
NodeJS : v10.16.2 (/usr/local/Cellar/node@10/10.16.2/bin/node)
npm : 6.9.0
OS : macOS Mojave
Xcode : Xcode 10.3 Build version 10G8
macOS version:

Xcode version:

**Comment by dwieeb** [comment]
For some reason there are newlines in the binary name?

**Comment by dwieeb** [comment]
Haha, I see the issue.

**Comment by MarkAMcCorkle** [comment]
Correct, no idea where they are coming from but I would imagine filtering them out would be a good consistency check on this side in case the Ionic CLI makes this happen again.

**Comment by dwieeb** [comment]
@MarkAMcCorkle As a workaround, in `config.xml`, change `<name>(whitespace)NAME(whitespace)</name>` to `<name>NAME</name>`. We just need to trim the whitespace.

**Comment by MarkAMcCorkle** [comment]
I see where it's coming from... Using an XML formatter brings that down to a newline. 
(ie)
`<name>myapp</name>`
Gets converted to the following after an XML formatter parses it.
```
	<name>
		myapp
	</name>
```
