### ISSUE TITLE
cannot add android platform 

### ISSUE THREAD

**Issue by Sevensnake** [ionic-team/ionic-cli#4134]
**Description:**

[cordova-res] internal/modules/cjs/loader.js:584
[cordova-res]     throw err;
[cordova-res]     ^                                                               odules\cordova-res\bin\cordova-res'
[cordova-res]                                                                     .js:582:15)
[cordova-res] Error: Cannot find module 'C:\Users\Seven\AppData\Roaming\npm\node_modules\cordova-res\bin\cordova-res'                                               2)
[cordova-res]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
[cordova-res]     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
[cordova-res]     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
[cordova-res]     at startup (internal/bootstrap/node.js:283:19)                  on.
[cordova-res]     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[ERROR] An error occurred while running subprocess cordova-res.

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
Ionic4 
"cordova-android": "^8.0.0
```

**Other Information:**
This can be a new application and it still does it.

**Comment by silver-software** [comment]
I also have this error.

npm i -g cordova-res

C:\Program Files\nodejs\cordova-res -> C:\Program Files\nodejs\node_modules\cordova-res\bin\cordova-res

> sharp@0.23.4 install C:\Program Files\nodejs\node_modules\cordova-res\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\Shadow\AppData\Roaming\npm-cache\_libvips\libvips-8.8.1-win32-x64.tar.gz
info sharp Creating C:\Users\Shadow\AppData\Roaming\nvm\v11.11.0\node_modules\cordova-res\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\Shadow\AppData\Roaming\nvm\v11.11.0\node_modules\cordova-res\node_modules\sharp\vendor\lib to C:\Users\Shadow\AppData\Roaming\nvm\v11.11.0\node_modules\cordova-res\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=11.11.0 runtime=node arch=x64 libc= platform=win32)

C:\Program Files\nodejs\node_modules\cordova-res\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\Shadow\AppData\Roaming\nvm\v11.11.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Shadow\AppData\Roaming\nvm\v11.11.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: c:\Users\Shadow\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:984:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shadow\\AppData\\Roaming\\nvm\\v11.11.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\cordova-res\node_modules\sharp
gyp ERR! node -v v11.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.23.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shadow\AppData\Roaming\npm-cache\_logs\2019-12-11T12_38_34_767Z-debug.log

My Nodejs version : 11.11.0
Cordova version : 9.0.0
Ionic version : 5.4.9

**Comment by dwieeb** [comment]
@silver-software That looks like a different issue. Please post installation issues to the cordova-res repo: https://github.com/ionic-team/cordova-res
