### ISSUE TITLE
`ionic serve` isn't copying contents into www

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-cli#4153]
**Description:**

I want to debug my app ATM to solve an issue with my layout and the native keyboard with capacitor plugin keyboard. To do this I often need to change some code. The problem is that I need to run `npx cap build` every time I change something and restart the Simulator with Xcode. I tried to `ionic serve --no-livereload --no-open` and expected that on every change it would update the www folder, so I just need to do `npx cap copy` but it seems it is not changing any file in www.

**Steps to Reproduce:**

1. run `ionic build --source-map --platform ios`
2. open the app in Xcode and run it in the simulator
3. run `ionic serve --no-livereload --no-open`
4. make change in the code
5. in Xcode click on start so it copies the changed code to the simulator 

**Output:**

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/Users/marvinheilemann/.nvm/versions/node/v10.16.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.803.3
   @angular-devkit/schematics    : 8.3.3
   @angular/cli                  : 8.3.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.2.0
   @capacitor/core : 1.2.0

Cordova:

   Cordova CLI       : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.16.0 (/Users/marvinheilemann/.nvm/versions/node/v10.16.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8
```

**Other Information:**

I would love to hear from other developers how their workflow is in cases like this and if it is possible or would be possible for the ionic-team to provide a cli command that does this automatically; build, serve, copy, run in simulator.

**Comment by dwieeb** [comment]
@muuvmuuv This is intended behavior and aligned with what the Angular CLI does. There's nothing actionable for the Ionic team. 

I think what you want is to run a build, but watch for changes:

```
ionic build -- --watch
```

A better place for asking about workflows is the [Ionic Forum](https://forum.ionicframework.com/). If there's a feature you'd like or behavior that you think should change, please open a new issue.

**Comment by muuvmuuv** [comment]
Thank you! That solved it. My solution:

package.json
```json
    "ios:run": "npm run ios:build-watch",
    "ios:copy": "ionic capacitor copy ios",
    "ios:copy-watch": "nodemon --exec npm run ios:copy",
    "ios:build-watch": "ionic build --source-map --platform ios -- --watch",
```

Run in two terminal tabs:

1. `npm run ios:build-watch`
2. `npm run ios:copy-watch`

**Comment by dwieeb** [comment]
@muuvmuuv This commit will allow you to use `ionic build --watch`: https://github.com/ionic-team/ionic-cli/commit/1444212f60f6ad71042caca740404587f0076e46

Should be in CLI 5.3!

**Comment by muuvmuuv** [comment]
Amazing, thanks @dwieeb !
