### ISSUE TITLE
"ionic start" gets stuck at 100% downloading starter

### ISSUE THREAD

**Issue by ZaLiTHkA** [ionic-team/ionic-cli#4158]
**Description:**

When I try generate a new Ionic project, my CLI command gets to "Downloading and extracting <template> starter (100%)" and then just sits there, the spinner endlessly spinning and nothing else happening.

I noticed this issue a few days back, and I've tried numerous things to try get around it, including force clearing NPM cache, uninstalling/reinstalling packages and even NodeJS itself, but the same problem persists.

I've also tried this in multiple different CLI environments (I use Terminus with Git Bash by default, but I get the same issue directly in CMD and PowerShell).

In each case, I've left the command to run for well over 30 minutes, but absolutely nothing changes.

**Steps to Reproduce:**

Run the command `ionic start`, 

**Output:**

```bash
$ ionic start hello-world sidemenu --verbose
  ionic:lib Terminal info: { ci: false, shell: 'C:\\Program Files\\Git\\usr\\bin\\bash.exe', tty: true, windows: true } +0ms
  ionic:lib CLI global options: { _: [ 'start', 'hello-world', 'sidemenu' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +10ms
  ionic Context: { binPath: 'C:\\Users\\agreeff\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath: 'C:\\Users\\agreeff\\AppData\\Roaming\\npm\\node_modules\\ionic', execPath: 'D:\\workspace\\sandbox', version: '5.2.8' } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic start' [ 'hello-world',
  ionic:lib:telemetry   'sidemenu',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--project-id=hello-world' ] +0ms
√ Preparing directory .\hello-world - done!
  ionic:commands:start Tar extraction created for D:\workspace\sandbox\hello-world +0ms
  superagent GET https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-sidemenu.tar.gz +0ms
/ Downloading and extracting sidemenu starter
/ Downloading and extracting sidemenu starter (100.00%)
```

**My `ionic info`:**

**Note:** this only shows global info because I'm obviously not *in* a project here..

```
Ionic:

   Ionic CLI : 5.2.8

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.7 (update available: 0.2.8)

System:

   NodeJS : v10.15.1
   npm    : 6.11.3
   OS     : Windows 10
```

**Other Information:**

Any requests for more info?

**Comment by sterichards** [comment]
I am having the same issue

macOS Mojave

Node v10.16.3

**Comment by MuhammadTanveerAshraf** [comment]
I am having the same issue
The versions I have are 
Node: 10.16.0
Ionic: 5.2.8
npm: 6.10.2

![ionic issue](https://user-images.githubusercontent.com/28089279/65029820-d7f43a00-d957-11e9-80a6-fdf6565549ab.png)

**Comment by ghenry22** [comment]
also just hit this same thing today on a new mac install.  Wasted hours and have no idea what is happening, it does extract files into the new project dir and says it's at 100% but then does nothing.

**Comment by MuhammadTanveerAshraf** [comment]
@IonicProSupport

**Comment by ghenry22** [comment]
Ionic:

   Ionic CLI : 5.2.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3
   npm    : 6.11.3
   OS     : macOS Mojave

tried updating to 5.2.8 cli, same problem

**Comment by sterichards** [comment]
It seems this is related to only `tabs`, `sidemenu` and `blank`

If you run `ionic start new-app my-first-app` or `ionic start new-app conference` then the clone completes successfully

**Comment by winterblizzara** [comment]
Same problem stuck at Downloading and extracting tabs starter (100.00%)
Tried LTE and latest Node JS but still stuck.
Did this problem only happened today?

**Comment by ZaLiTHkA** [comment]
> It seems this is related to only `tabs`, `sidemenu` and `blank`
> 
> If you run `ionic start new-app my-first-app` or `ionic start new-app conference` then the clone completes successfully

nice catch, I hadn't noticed that specifically.. perhaps this is related to the source for the app template then? `tabs`, `sidemenu` and `blank` seem to download an archive, while `my-first-app` and `conference` clone a remote Git repo.

**Comment by ZaLiTHkA** [comment]
> Same problem stuck at Downloading and extracting tabs starter (100.00%)
> Tried LTE and latest Node JS but still stuck.
> Did this problem only happened today?

I noticed this last night when trying to start a new project on my personal laptop, then I reproduced it this morning on my work desktop. last time I created a new project was a few weeks back, so I'm honestly not sure *when* this started..

I can't find many people asking about it online though, so gauging by the responses here, I'd say this is a rather fresh issue.

**Comment by sterichards** [comment]
> > It seems this is related to only `tabs`, `sidemenu` and `blank`
> > If you run `ionic start new-app my-first-app` or `ionic start new-app conference` then the clone completes successfully
> 
> nice catch, I hadn't noticed that specifically.. perhaps this is related to the source for the app template then? `tabs`, `sidemenu` and `blank` seem to download an archive, while `my-first-app` and `conference` clone a remote Git repo.

I had noticed this also. Seems strange to me that some example projects use a git clone command but others (which aren't working) use something else

**Comment by kyawswarthwin** [comment]
Win 10 x64 same issue.

**Comment by harveysingh1** [comment]
Similar issue here too. Seems to be a very recent issue considering all the mentions on this thread today. Doesn't look like there's any answer so far other than making a 'my-first-app' project and refactoring it as needed.

**Comment by sterichards** [comment]
The solution for me was to use --type ionic1

IE - ionic start appname sidemenu --type ionic1

**Comment by andreasbhansen** [comment]
> The solution for me was to use --type ionic1
> 
> IE - `ionic start appname sidemenu --type ionic1`

Not really a solution, sadly, unless you intentionally would want to use an old version of Ionic.

**Comment by mhartington** [comment]
Hello everyone, looking into this.

**Comment by mhartington** [comment]
So far I have not been able to replicate this on my machine/my network. @ZaLiTHkA can you confirm that you are not behind a firewall?

**Comment by ZaLiTHkA** [comment]
> So far I have not been able to replicate this on my machine/my network. @ZaLiTHkA can you confirm that you are not behind a firewall?

We do have a hardware firewall here at work (typical corporate network story), but I have nothing like that at home.

We've been running with NPM-based projects for a few years now, so I've been back and forth with our IT department to allow our dev tools access to what they need... Haven't needed to ask them to add any exceptions to the firewall rules for ages now.

If you like, I can do some more digging this evening from my personal connection? I do have family visiting from overseas at the moment though, so tonight I'll only be able to get to this later on (probably around 10pm GMT+2).

**Comment by sterichards** [comment]
@mhartington Are you able to provide the URL location that `ionic start hello-world sidemenu` would pull data from so I can debug the network responses?

**Comment by ZaLiTHkA** [comment]
> @mhartington Are you able to provide the URL location that `ionic start hello-world sidemenu` would pull data from so I can debug the network responses?

Is that not the `https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-sidemenu.tar.gz` URL from the verbose CLI output in my first post?

For what it's worth, I *can* download that 12.6KB file directly without any problems...

**Comment by andreasbhansen** [comment]
> So far I have not been able to replicate this on my machine/my network. @ZaLiTHkA can you confirm that you are not behind a firewall?
> 
> Same for others, can you confirm if you're behind a firewall and your OS.

Probably a firewall here at work, indeed. I'll double check when I get home in an hours or so if I can successfully start a new Ionic project there. Have been using npm for other packages today without issues. Using another install `type` (e.g. `ionic-angular`) does work for starting new Ionic projects.

My OS is macOS Mojave (10.14.5).

**Comment by mhartington** [comment]
The url is in fact `https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-sidemenu.tar.gz`. So you could test locally by doing 


```
curl https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-sidemenu.tar.gz --output sidemenu.tar.gz`

**Comment by sterichards** [comment]
> curl https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-sidemenu.tar.gz --output sidemenu.tar.gz`

Download of 13Kb successful

**Comment by mhartington** [comment]
if there was a hang up on npm install a lot more people would be seeing this.

Going to get a few more eyes from the team

**Comment by ZaLiTHkA** [comment]
> Going to get a few more eyes from the team

Cool beans. Let me know if you need any specific details from me then.

**Comment by Adriiad** [comment]
Hi, same problem here. I successfully generated an app yesterday. I try to generate another app today, but ionic is stuck.

![image](https://user-images.githubusercontent.com/40627664/65048379-48a15380-d964-11e9-9826-8351e39ba35e.png)

**Comment by ugurcagridogan** [comment]
Hi, I'm having the same issue right now.

**Comment by Chardine** [comment]
Same here. I'm at home, and definitely no proxy. 
Ionic:

   Ionic CLI : 5.2.8

Utility:

   cordova-res : 0.6.0 
   native-run  : not installed

System:

   NodeJS : v12.7.0
   npm    : 6.10.3
   OS     : macOS Mojave

**Comment by mhartington** [comment]
Hey everyone, we are aware of the issue and are working on it. 

Please refrain from any additional noise.

**Comment by mhartington** [comment]
Hey everyone, looks like the issue was in a dep of a dep, minipass.

https://github.com/isaacs/minipass/commit/1d5623a62ba8f64753a5d5ec9a665789000db858

They've released a fix, so you should be able to do 

```
npm uninstall -g ionic
npm install -g ionic
```

This will update you to the latest minipass release.

**Comment by sterichards** [comment]
Works for me now

**Comment by michaelromero128** [comment]
Worked for me

**Comment by mhartington** [comment]
Going to close for now. Thanks!

**Comment by rafaband** [comment]
same problem here. I did the npm uinstall and install and NOT working

**Comment by ZaLiTHkA** [comment]
> This will update you to the latest minipass release.

Yup, that sorted it out..

Thanks @mhartington. 🖖

**Comment by tristanpgraham** [comment]
Still getting this error:  "Downloading and extracting blank starter (100.00%)" 
After running:

npm uninstall -g ionic
npm install -g ionic

**Comment by tristanpgraham** [comment]
Still getting this error: "Downloading and extracting blank starter (100.00%)"
After running:

npm uninstall -g ionic
npm install -g ionic

**Comment by Rsvend17** [comment]
I am also getting this error, after trying the solution. Also tried reinstalling Node and ionic.

**Comment by mhartington** [comment]
@tristanpgraham and @Rsvend17 Please make sure you clear our the ionic CLI and then reinstall again with 

```
npm install -g ionic@latest
```

**Comment by JocPelletier** [comment]
Same issue, tried:
npm uninstall -g ionic
npm install -g ionic@latest

**Comment by Rsvend17** [comment]
@mhartington tried it. It did not fix the issue for me

**Comment by tristanpgraham** [comment]
Same for me 

Using
Ionic:

   Ionic CLI : 5.4.1

System:

   NodeJS : v12.10.0
   npm    : 6.11.3
   OS     : macOS Catalina 10.15 Beta (19A573a)

**Comment by mhartington** [comment]
_sigh_ looks like minpass broke things again. Looking into stuff, hang tight.

**Comment by evallgar** [comment]
As of today, I cannot start a template project but conference one.

**Comment by evallgar** [comment]
@mhartington 
I will try this workaround for now:
[https://github.com/lovell/sharp/issues/1882](https://github.com/lovell/sharp/issues/1882)

**Comment by RoberCastro** [comment]
Same issue than all the rest:
- Mojave
-Fresh npm install
-Able to create a project only with conference template 

Thanks in advance for your help @mhartington

**Comment by mhartington** [comment]
We're following things over here 

https://github.com/isaacs/minipass/issues/9

We need minipass to update

**Comment by MWLBear** [comment]
Same issue, tried:
npm uninstall -g ionic
npm install -g ionic@latest
![屏幕快照 2019-09-24 下午1 50 35](https://user-images.githubusercontent.com/17424537/65484771-79d4d300-ded2-11e9-8a5f-8288a9fc01a5.png)

**Comment by kevinkellyyyy** [comment]
have you guys tried to downgrade/install previous ionic version? it's works for me.

i just uninstalled the latest version, then install ionic 5.2.0
npm install -g ionic@5.2.0

try different version below 5.4.1 maybe it will work too

**Comment by jbakoume** [comment]
> have you guys tried to downgrade/install previous ionic version? it's works for me.
> 
> i just uninstalled the latest version, then install ionic 5.2.0
> npm install -g ionic@5.2.0
> 
> try different version below 5.4.1 maybe it will work too

not still working for me
MAC OS Mokave 10.14.5

**Comment by jbakoume** [comment]
must i need xcode installed in my mac before ?

**Comment by jbakoume** [comment]
> npm install -g ionic

not working for me either

**Comment by mhartington** [comment]
Hey everyone, this should be fixed again. All you should need to do is 

```
npm uninstall -g ionic
npm install -g ionic```

**Comment by jccastro87** [comment]
Resolved the problems now.

**Comment by jbakoume** [comment]
I also suggest installing npm mirrors
that worked for me

npm install npm-mirrors

**Comment by hfournier** [comment]
> Hey everyone, this should be fixed again. All you should need to do is
> npm uninstall -g ionic
> npm install -g ionic```

Worked for me. Thank you. However, you might want to edit your answer and remove the trailing triple backtick.

**Comment by mujica93** [comment]
https://github.com/ionic-team/ionic-cli/issues/4158#issuecomment-534498792

workked for me

**Comment by Kensed** [comment]
The problem is persisting 

```
⠴ Downloading and extracting tabs starter

Error: connect ETIMEDOUT 52.142.209.23:8100
```

**Comment by dwieeb** [comment]
@Kensed Please make a new issue with `ionic info`.
