### ISSUE TITLE
ionic start" gets stuck at 100% downloading starter  in linux 

### ISSUE THREAD

**Issue by spyderp** [ionic-team/ionic-cli#4163]
**Description:**
this same problem for issue #4158 

**Steps to Reproduce:**
Run the command ionic start,

**Output:**
```
ionic start myApps tabs --type=angular
Downloading and extracting sidemenu starter (100.00%)
```
**My `ionic info`:**

```
Ionic:

   Ionic CLI : 5.4.1

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   NodeJS : v10.16.3
   npm    : 6.11.3
   OS     : Linux 4.15

```
**Other Information:**
Any requests for more info?

**Comment by YanYuanFE** [comment]
I have the same problem.

**Comment by kevindanielr** [comment]
I have the same problem, I am waiting for an update

**Comment by luck3r** [comment]
I have the same problem. 
Ionic CLI: 5.4.1
Windows 10

**Comment by spyderp** [comment]
resolve problem downgrad version 5.4.1 to 5.2.0

**Comment by RubenVillamizar** [comment]
I have the same problem under a corporate proxy

**Comment by deniscpaula** [comment]
I have the same problem

**Comment by facundobrondo** [comment]
Tengo el mismo problema, se ha encontrado alguna solucion?

**Comment by dwieeb** [comment]
This is likely the minipass issue that broke the world.

Try this, even if you have the latest version: https://github.com/ionic-team/ionic-cli/issues/4158#issuecomment-534498792

**Comment by spyderp** [comment]
the problem solve
