### ISSUE TITLE
CHAT APP: unable to connect to socket.io in the server from devapp

### ISSUE THREAD

**Issue by chesiri** [ionic-team/ionic-cli#4177]
**Description:**

**CHAT APP**:
Unable to connect to socket.io in the server from devapp.
I can connect in the browser but not in devapp.
the server whit the socket io is run in http://localhost:8101
Any idea?

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 5.4.2 (/usr/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.9.0-rc.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/usr/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.15
```

**Other Information:**

**Comment by MLHeimann** [comment]
I bumped into the same problem. 

You need to use your IP address instead of localhost when you set socket io

**Comment by dwieeb** [comment]
Just as a fair warning, we're not supporting the DevApp anymore.
