### ISSUE TITLE
ionic cordova run android --device -l gives ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by jalle007** [ionic-team/ionic-cli#4181]
And here it is again. Another bullshit error that SHOULD NOT be there

command: ionic cordova run android --device -l 

error ERR_CLEARTEXT_NOT_PERMITTED

info

Ionic:

   ```
Ionic CLI          : 5.4.2 (C:\Users\xxx\AppData\Roaming\nvm\v10.15.3\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.1.11

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 25 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (e:\Android\SDK)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

```

**Comment by jalle007** [comment]
none of solutions i [found ](https://forum.ionicframework.com/t/livereload-err-cleartext-not-permitted/163487)is working any more

**Comment by dwieeb** [comment]
@jalle007 Please read our [code of conduct](https://github.com/ionic-team/ionic/blob/master/CODE_OF_CONDUCT.md) and remember to remain constructive.

This is a very common issue with all Android apps, not just Ionic. I recommend reading [the last post in #3759](https://github.com/ionic-team/ionic-cli/issues/3759#issuecomment-497830717). Until this issue yields something actionable, I am closing it as a duplicate.
