### ISSUE TITLE
devApp not working for Capacitor Ionic 4 Project

### ISSUE THREAD

**Issue by JerryGoyal** [ionic-team/ionic-cli#4182]
Is it not supported yet or is it a bug?
I've created project with  Ionic4+Angular+Capacitor and when I try `ionic serve --devapp` it throws me the error `[ERROR] Could not find cordova integration in the default project.`

If it's not yet supported then what are the possible options? Can I also install the cordova parallely and run in devapp? would it cause any performance issue in my deployed pwa/app/site ?

**Comment by dotNetkow** [comment]
Capacitor and DevApp do not work together. Capacitor embraces the native tooling more than Cordova ([see here](https://capacitor.ionicframework.com/docs/cordova
) for why), so in this case, you'll use [Xcode and/or Android Studio](https://capacitor.ionicframework.com/docs/getting-started/dependencies
) to build, run, and test your app.
