### ISSUE TITLE
CLI doesn't follow the Angular 8 syntax

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-cli#4186]
CLI: 

> ionic g page pages/SignUp 

Current behavior:

`  { path: 'sign-up', loadChildren: './pages/sign-up/sign-up.module#SignUpPageModule' },`

It should be: i.e. Angular 8 syntax

`{ path: 'sign-up', loadChildren: () => import('./pages/sign-up/sign-up.module').then(m => m.SignUpPageModule) },`

> Ionic:
> 
>    Ionic CLI                     : 5.4.4
>    Ionic Framework               : @ionic/angular 4.11.1
>    @angular-devkit/build-angular : 0.801.3
>    @angular-devkit/schematics    : 8.1.3
>    @angular/cli                  : 8.1.3
>    @ionic/angular-toolkit        : 2.0.0
> 
> Cordova:
> 
>    Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
>    Cordova Platforms : not available
>    Cordova Plugins   : not available
> 
> Utility:
> 
>    cordova-res : not installed
>    native-run  : 0.2.5 (update available: 0.2.8)
> 
> System:
> 
>    NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
>    npm    : 6.9.0
>    OS     : Windows 10

**Comment by dwieeb** [comment]
Fixed with 2.1.0 of `@ionic/angular-toolkit`: https://github.com/ionic-team/angular-toolkit/pull/176

**Comment by Sampath-Lokuge** [comment]
@dwieeb Excellent! Thank you!
