### ISSUE TITLE
ionic serve: does not start/reload react project if compilation warnings

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/ionic-cli#4205]
**Description:**

`ionic serve` (and other commands) does not start (or livereload on change if already running) if there are any compilation warnings in the code.

I believe that's because `react-scripts` in that case outputs [Compiled with warnings](https://github.com/facebook/create-react-app/blob/v3.2.0/packages/react-dev-utils/WebpackDevServerUtils.js#L249) but the Ionic CLI is always expecting [Compiled successfully](https://github.com/ionic-team/ionic-cli/blob/ionic%405.4.5/packages/ionic/src/lib/project/angular/serve.ts#L189).

**Steps to Reproduce:**

Create a new Ionic React app with

```ionic start my-app blank --type=react```

Change the code and add something that results in a warning, e.g. an unused variable or import, or an `img` tag without `alt` attribute.

Run `ionic serve` and it'll be stuck "Starting the development server..." forever.

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 5.4.5 (/Users/mirko/.config/yarn/global/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.0 (/Users/mirko/.nvm/versions/node/v12.13.0/bin/node)
   npm    : 6.12.0
   OS     : macOS Catalina

```

**Comment by mirkonasato** [comment]
I can see this has been fixed in [5.4.15](https://github.com/ionic-team/ionic-cli/blob/develop/packages/%40ionic/cli/CHANGELOG.md#5415-2020-01-15), and can confirm it works fine now.

**Comment by dwieeb** [comment]
Thanks for following up @mirkonasato! And thanks for the bug report.

**Comment by saurabhgupta050890** [comment]
I am having the same problem with Ionic CLI 6.10.1 on windows

```Ionic:

   Ionic CLI       : 6.10.1 (C:\Users\s0508\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.2.2

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

Running `npm start`  works fine
