### ISSUE TITLE
Visual Studio Code -->Cordova Tools Not Hitting the breakpoint

### ISSUE THREAD

**Issue by navs007** [ionic-team/ionic-cli#4206]
**Not Able to debug using**
Attach to running android on emulator-->DOes not stop at the breakpoint totally
Attach to running android on device -->Using Device the break point hits occationally

Cordova tools 1.9. version
ionic 4 version 
trying to hit .ts code

 "name": "Attach to running android on emulator",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },

**Comment by dwieeb** [comment]
@navs007 Unless I'm misunderstanding, this doesn't look like a CLI issue. Please use the Ionic Forum for stuff like this.
