### ISSUE TITLE
Still, no Type safe module loader feature which came with Angular 8

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-cli#4216]
Hi,

Still, no Type safe module loader feature which came with Angular 8

> ionic g page pages/Checkout

_app.routing.module.ts_

`{ path: 'checkout', loadChildren: './pages/checkout/checkout.module#CheckoutPageModule' },`

We need this way:

` { path: 'checkout', loadChildren: () => import('./pages/checkout/checkout.module').then(m => m.CheckoutPageModule) },`

Ionic info:

Ionic:

   Ionic CLI                     : 5.4.6
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 12 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.5

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

**Comment by mhartington** [comment]
Please install `npm i @ionic/angular-toolkit@2.1.1`

This was part of the 2.1 release.

**Comment by Sampath-Lokuge** [comment]
Thanks, Mike. This is working fine now.
