### ISSUE TITLE
ionic-5.4.7 breaks command options

### ISSUE THREAD

**Issue by Dieken** [ionic-team/ionic-cli#4222]
**Description:**

```
$ npm install -g ionic@5.4.6
$  ionic serve --devapp
> ng run app:ionic-cordova-serve --host=0.0.0.0 --port=8100 --cordova-mock --consolelogs --consolelogs-port=53703

$ npm install -g ionic@5.4.7
$ ionic serve --devapp
> ng run app:serve --host=localhost --port=8100
```

```
$ ionic info

Ionic:

   Ionic CLI                     : 5.4.7 (/Users/liuyb/homebrew/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : not installed

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.12.0 (/Users/liuyb/homebrew/Cellar/node/12.12.0/bin/node)
   npm        : 6.13.1
   OS         : macOS Catalina
   Xcode      : Xcode 11.0 Build version 11A420a

```

**Comment by JDuqn** [comment]
Same here.
I was wondering why the livereload flag didn't work anymore.

**Comment by SergioSuarezDev** [comment]
me too! downgrade to 5.4.6 solve the problem

**Comment by kensodemann** [comment]
Noticed the same thing with `--dryRun` and was going to write it up, then saw we have at least three issues on this already... It seems something is seriously broken with the argument processing.

**Comment by Jahrenski** [comment]
-b doesn't work either so i'm going to go ahead and guess no args work with 5.4.7

**Comment by jbw716** [comment]
I'll throw another "confirmed" in here.

**Comment by dwieeb** [comment]
Thanks all. 5.4.7 was a bad release. I missed a test case while doing a refactor. I am shipping a new release now.

**Comment by RZR666** [comment]
Just spent half a day thinking I was going crazy, ha

**Comment by dwieeb** [comment]
I am trying to get a release out there, but npm is having issues: https://status.npmjs.org/

**Comment by patrickbussmann** [comment]
@dwieeb Can you please close this issue only when you was able to publish the 5.4.8 to NPM?
Thank you.

**Comment by dwieeb** [comment]
Yeah, sorry if it's confusing. Github doesn't differentiate between a "stable" branch and the default branch. If a commit or PR "[fixes](https://github.com/ionic-team/ionic-cli/commit/060f67cf63d37662ae44c4ae952161464a5d553c)" an issue, it automatically closes it even if it's not released.

Anyway, 5.4.8 is out! Let me know if there are any issues. Thanks for your patience.

**Comment by dkrahn** [comment]
I don't know if it is related.
But running `ionic cordova build android --prod --release -- -- --keystore=KEYSTORE_FILE.jks --storePassword=STORE_PASS --alias=ALIAS --password=KEY_PASS` doesn't sign the APK.

**Comment by patrickbussmann** [comment]
@dkrahn It's not related to this issue. Open a new one please 🙂

And we need the output of your build. maybe there is a warning or something like this.

**Comment by dkrahn** [comment]
Thank you @patrickbussmann.
I found the error. It was not related to Ionic. It's a PowerShell error. From CMD or Linux shell, the commands are passed ok. But for some reason PowerShell , since last windows defenders intelligence security update, ignores one of the `--`. So to run it in PowerShell just have to add one more `--`.
So for CMD/Linux Shell:
```
ionic cordova build android --prod --release -- -- --keystore=KEYSTORE_FILE.jks --storePassword=STORE_PASS --alias=ALIAS --password=KEY_PASS
```
And for PowerShell:
```
ionic cordova build android --prod --release -- -- -- --keystore=KEYSTORE_FILE.jks --storePassword=STORE_PASS --alias=ALIAS --password=KEY_PASS
```
