### ISSUE TITLE
ionic cordova build command doesn't pass flags to cordova build

### ISSUE THREAD

**Issue by cabaird** [ionic-team/ionic-cli#4227]
In this latest release, when running `ionic cordova build` with flags (in my case, `--device` and `--release`), those flags are not passed into the `cordova build` command, and the build is always made for emulator and with Debug Configuration.  Seems this was introduced in 5.4.7 as the previous patch version 5.4.6 does not have it.  I have downgraded as a workaround for the time being.

**Comment by battika** [comment]
Same here, my automated builds are failing since then. Downgrading to Ionic CLI 5.4.6 fixes the issue.

**Comment by jbw716** [comment]
Duplicate #4222

**Comment by patrickbussmann** [comment]
Yes but it's not released yet to NPM so we still have a problem with `latest` version 😥

**Comment by dwieeb** [comment]
Fixed in 5.4.8. Thanks!
