### ISSUE TITLE
ionic serve / build fails with latest @typescript-eslint/eslint-plugin@2.10.0

### ISSUE THREAD

**Issue by davidtiede** [ionic-team/ionic-cli#4233]
The latest version of @typescript-eslint/eslint-plugin@2.10.0. Explicitly specifying 2.9.0 as a dev dependency is a temporary work around..

Steps to recreate:
> ionic start myApp --type=react
> ionic serve

Output:
> react-scripts start
[react-scripts] Starting the development server...
[react-scripts] 
[react-scripts] Failed to compile.
[react-scripts] 
[react-scripts] ./node_modules/react-dev-utils/webpackHotDevClient.js
[react-scripts] Error: [BABEL] ./node_modules/react-dev-utils/webpackHotDevClient.js: Cannot find module './src/data'
[react-scripts] Require stack:
[react-scripts] - ./node_modules/core-js-compat/helpers.js
[react-scripts] - ./node_modules/core-js-compat/get-modules-list-for-target-version.js
[react-scripts] - ./node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/polyfills/corejs3/entry-plugin.js
[react-scripts] - ./node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/index.js
[react-scripts] - ./node_modules/babel-preset-react-app/dependencies.js
[react-scripts] - ./node_modules/@babel/core/lib/config/files/plugins.js
[react-scripts] - ./node_modules/@babel/core/lib/config/files/index.js
[react-scripts] - ./node_modules/@babel/core/lib/index.js
[react-scripts] - ./node_modules/babel-loader/lib/index.js
[react-scripts] - ./node_modules/loader-runner/lib/loadLoader.js
[react-scripts] - ./node_modules/loader-runner/lib/LoaderRunner.js
[react-scripts] - ./node_modules/webpack/lib/NormalModule.js
[react-scripts] - ./node_modules/webpack/lib/NormalModuleFactory.js
[react-scripts] - ./node_modules/webpack/lib/Compiler.js
[react-scripts] - ./node_modules/webpack/lib/webpack.js
[react-scripts] - ./node_modules/react-scripts/scripts/start.js (While processing: "./node_modules/babel-preset-react-app/dependencies.js$0$9")

**Comment by dwieeb** [comment]
I believe this is the core-js issue we were seeing in React starters: https://github.com/zloirock/core-js/issues/712
