### ISSUE TITLE
How to skip unit test

### ISSUE THREAD

**Issue by sid-ihycq** [ionic-team/ionic-cli#4236]
i upgrade to ionic4 recently, but i found there is no options in the doc pointed out how to close unit test.  i don't need it, it's just way too much trouble. 
angular project can use "ng new my-app --skipTests=true", anyone can tell me how to skip the unit test like this?

**Comment by dwieeb** [comment]
Gonna lump this in with this issue: https://github.com/ionic-team/ionic-cli/issues/3499
