### ISSUE TITLE
ionic cordova plugin add ../plugin --link flag is missing

### ISSUE THREAD

**Issue by shamilovtim** [ionic-team/ionic-cli#4260]
this flag is useful for local development of new plugins and is curiously missing from ionic even though it exists in vanilla cordova

**Comment by jcesarmobile** [comment]
for additional params you have to use `--`

so you can use `ionic cordova plugin add ../plugin -- --link`
or you can just directly use cordova command `cordova plugin add ../plugin --link`

**Comment by shamilovtim** [comment]
Excellent, thanks! 

Now just waiting for them to fix symlinking in Gradle
