### ISSUE TITLE
[Feature request] Add support for pnpm

### ISSUE THREAD

**Issue by duong755** [ionic-team/ionic-cli#4285]
Hi,
I wonder will ionic-cli support the third `npmClient` - pnpm?

**Comment by dwieeb** [comment]
I am happy to look at pull requests that add pnpm to the `pkgManagerArgs` function: https://github.com/ionic-team/ionic-cli/blob/develop/packages/ionic/src/lib/utils/npm.ts#L44 

But, as of now this is low priority for us. Thanks for understanding!
