### ISSUE TITLE
Warn about server.url when not using --livereload

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-cli#4305]
When doing `ionic cap build` without `--livereload`, `server.url` might exist in `capacitor.config.json` from a previously run command with `--livereload` that was forcibly killed.

We can warn about the existence of the URL. It shouldn't exist for non-livereload.

**Comment by jcesarmobile** [comment]
There are a few users using the url to point to an online version of the app, so it can exist for non-livereload. 
But yeah, better warn just in case.

**Comment by dwieeb** [comment]
With the new Apple guidelines, I think that's frowned upon as well, right?

**Comment by jcesarmobile** [comment]
It always depends on how you interpret it, but people is using it without trouble and also Google play also seem to allow it

**Comment by dwieeb** [comment]
Sounds good. We could have an option to disable the warning.
