### ISSUE TITLE
live reload not working

### ISSUE THREAD

**Issue by KMuthusamyms** [ionic-team/ionic-cli#4312]
**Description:**
while I am executing my project with ```ionic serve``` or ```ionic cordova run browser``` , live reload doesn't work.

**My `ionic info`:**
```
muthusamy@muthusamyms:~/gps$ ionic info

Ionic:

   Ionic CLI                     : 6.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.1.4, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 9 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : 0.3.0

System:

   Android SDK Tools : 25.0.0 (/usr/lib/android-sdk)
   NodeJS            : v12.14.1 (/usr/local/bin/node)
   npm               : 2.15.12
   OS                : Linux 4.15
```

**Comment by joselevelsup** [comment]
Same happens with Ionic React.

Ionic:

   Ionic CLI       : 6.1.0 (~/.nvm/versions/node/v10.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.0.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.19.0 (~/.nvm/versions/node/v10.19.0/bin/node)
   npm    : 6.13.4
   OS     : Linux 5.3

**Comment by Defcon0** [comment]
Same here :-( Some days ago it has been working though.

```
Ionic:

   Ionic CLI                     : 6.1.0 (/home/dev/.nvm/versions/node/v12.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 9 other plugins)

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/home/dev/Android/Sdk)
   NodeJS            : v12.16.0 (/home/dev/.nvm/versions/node/v12.16.0/bin/node)
   npm               : 6.13.4
   OS                : Linux 5.3
```

**Comment by Defcon0** [comment]
In my case it has been no error. I just used the "http://localhost:8100"-tab already opened by a previous `ionic serve` session. After I closed it and used the one directly opened by the command line, it worked again :-)

**Comment by Defcon0** [comment]
Mhm, the problem reappeared, but persists now :-( Is it possible that structural errors lead to the live reload not working anymore?

**Comment by Defcon0** [comment]
Could be helpful. My Chrome devtools show up the following issues:

```
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map
```

But the files are valid json files (at least json lint doesn't complain).

**Comment by dwieeb** [comment]
See this issue for livereload support with the Cordova browser platform: https://github.com/ionic-team/ionic-cli/issues/3043

I'm seeing that everyone is on Linux. Perhaps there's an issue in the file watcher for Linux?

**Comment by KMuthusamyms** [comment]
I solved this issue by running the `ionic serve` or `ionic cordova run browser -l` in sudo mode.

**Comment by joselevelsup** [comment]
@KMuthusamyms i don't think that's a problem solved. All because it worked in `sudo` doesn't mean its a good thing. For me, (as @dwieeb said), it was a file watcher error. I don't remember the command since I copied the command via a different issue. I'll post it later on.
