### ISSUE TITLE
bug: Cannot create a Ionic 5 project

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-cli#4317]
Hi,

Ver: Ionic 5

I have tried many ways. But none of them worked.

`ionic start`

and 

`ionic start ngrx sidemenu --type=ionic-angular`

**Error:**

> npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version 
> of core-js@3.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
> npm ERR! 404
> npm ERR! 404  'error-ex@^1.3.1' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 It was specified as a dependency of 'parse-json'
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Sampath\AppData\Roaming\npm-cache\_logs\2020-02-12T11_34_09_140Z-debug.log

**CLI:**

> $ ionic version
> 6.0.2

**Comment by Sampath-Lokuge** [comment]
Now it's around 5 H. But still the same error.

**Comment by elylucas** [comment]
Hi @Sampath-Lokuge,

To start a v5 app, use `--type=angular`. the `ionic-angular` type is for v1 projects that use AngularJS, which it looks like there is a dependency that needs to be updated for those older starters.

**Comment by Sampath-Lokuge** [comment]
Hi @elylucas 

Still the same issue. This is not working with the `ionic start` too.

![3](https://user-images.githubusercontent.com/5206526/74352843-1e52a580-4ddf-11ea-97d1-993629c02a45.png)

**Comment by elylucas** [comment]
Hmm, weird because error-ex@1.3.1 definitely exists: https://www.npmjs.com/package/error-ex/v/1.3.1

Can you make a request to https://registry.npmjs.org/error-ex/-/error-ex-1.3.1.tgz and see if it downloads the file?

Do you have any custom npm setup through a .npmrc file or anything similar?

**Comment by Sampath-Lokuge** [comment]
> Do you have any custom npm setup through a .npmrc file or anything similar?

No. 

![1](https://user-images.githubusercontent.com/5206526/74355400-d766af00-4de2-11ea-90dd-cad23ec08b5e.png)

**Comment by elylucas** [comment]
Looks like there is a problem with npm serving up 404s for some packages right now, including error-ex:

https://status.npmjs.org/

Looks like they discovered the issue and fixed it, but it might take some time to propagate. Let us know if its still having issues after awhile.

**Comment by Sampath-Lokuge** [comment]
Sure. I'll try it few hours later and update this post. Thanks.

**Comment by erikyuzwa** [comment]
just a +1 for encountering this same issue as well. Thanks for the mention of npm status @elylucas

**Comment by Sampath-Lokuge** [comment]
Still this is not working. NPM says all are working fine on the above URL. But it is not. I'll try again later.

**Comment by amanuppalhp** [comment]
Same situation here!
`npm ERR! 404 Not Found: error-ex@^1.3.1`

**Comment by amanuppalhp** [comment]
Here is a temporary solution:
```
npm i https://github.com/Qix-/node-error-ex
npm install
```
Found here: [(https://github.com/facebook/create-react-app/issues/8465)]

**Comment by Sampath-Lokuge** [comment]
I close this since now it is working fine.
