### ISSUE TITLE
Ionic Init not working (Just creates a ionic.config.json file)

### ISSUE THREAD

**Issue by ashutoshpw** [ionic-team/ionic-cli#4320]
- I am trying to create a new project with command "ionic init" but after asking the platform, it just creates and single file "ionic.config.json" and exits.

After that, I am not able to do anything.

Operating System:
- Windows 10
- Tried on Git Bash, CMD, Powershell, Powershell with elevated access.

Note:
It's working fine for project already built on ionic.

**Comment by dwieeb** [comment]
I think you're looking for `ionic start`.
