### ISSUE TITLE
config.xml get's overwritten

### ISSUE THREAD

**Issue by vishal38-isharani** [ionic-team/ionic-cli#4342]
**Description:**

when i run `ionic cordova run android --livereload` my config.xml get's overwritten with the default one settings.

**Steps to Reproduce:**

create new ionic project add some permission to config.xml and run `ionic cordova run android --livereload`

**Output:**

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.2.0 (/Users/vishalisharani/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   NodeJS : v12.16.1 (/Users/vishalisharani/.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
```

**Other Information:**

**Comment by dwieeb** [comment]
@vishal38-isharani I'm unable to reproduce the issue. Please include **exact** replication steps for the issue you're experiencing.

**Comment by vishal38-isharani** [comment]
@dwieeb I will create a repo for this and give you url of that.

**Comment by vishal38-isharani** [comment]
@dwieeb i have tried to reproduce it but i'm not able to do so, closing this issue
