### ISSUE TITLE
could not find plugin "proposal-numeric-separator"

### ISSUE THREAD

**Issue by R-obert** [ionic-team/ionic-cli#4368]
Hello,

I think there is an issue with the new package @ionic/CLI.
I did a fresh install of node.js, I installed npm packages `@ionic/CLI` and `cordova`.
Before that I had the deprecated `ionic` package and `cordova`.

After the install (haven't reinstalled Android-SDK and Gradle, they're still the same):
`ionic start mytestproject blank --type=angular`
Then:
`ionic cordova build android`

That results in the error from the title. If you google it you will find many people with that problem from the last couple of days (march 2020):

![Screenshot from 2020-03-29 15-57-56](https://user-images.githubusercontent.com/62835651/77851073-10ae7f00-71d7-11ea-94a9-015ba6d9976e.png)

Does the ionic team know about this and will there be an official fix soon?

Best regards,
Robert

**Comment by dwieeb** [comment]
This is an Angular issue. See https://github.com/angular/angular-cli/issues/17262
