### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'platforms/android/app/build/outputs/apk/debug/app-debug.apk

### ISSUE THREAD

**Issue by hanibhat** [ionic-team/ionic-cli#4372]
**Description:**
I'm receiving the following warning after running my Ionic project:

> Error: ENOENT: no such file or directory, open 'platforms/android/app/build/outputs/apk/debug/app-debug.apk'

After that, the build fails.
Other Ionic projects are working fine. For this project specifically, the directory `platforms/android/app/build` is never being created.

**Steps to Reproduce:**
Run `ionic cordova run android -l`

**Output:**
> [INFO] Hardware device(s) found for android. Using --device.
> ng run app:ionic-cordova-serve --host=localhost --port=8100 --platform=android
[ng] ℹ ｢wds｣: Project is running at http://localhost:8100/webpack-dev-server/
[ng] ℹ ｢wds｣: webpack output is served from /
[ng] ℹ ｢wds｣: 404s will fallback to //index.html
[ng] chunk {common} common.js, common.js.map (common) 35.6 kB  [rendered]
[ng] chunk {cordova} cordova.js, cordova.js.map (cordova) 63.5 kB [entry] [rendered]
[ng] chunk {core-js-js} core-js-js.js, core-js-js.js.map (core-js-js) 78.7 kB  [rendered]
[ng] chunk {css-shim-206ea950-3169f23e-js} css-shim-206ea950-3169f23e-js.js, css-shim-206ea950-3169f23e-js.js.map (css-shim-206ea950-3169f23e-js) 21.9 kB  [rendered]
[ng] chunk {dom-96781eef-a2fb04dd-js} dom-96781eef-a2fb04dd-js.js, dom-96781eef-a2fb04dd-js.js.map (dom-96781eef-a2fb04dd-js) 19.8 kB  [rendered]
[ng] chunk {dom-js} dom-js.js, dom-js.js.map (dom-js) 20.2 kB  [rendered]
[ng] chunk {focus-visible-70713a0c-js} focus-visible-70713a0c-js.js, focus-visible-70713a0c-js.js.map (focus-visible-70713a0c-js) 2.15 kB  [rendered]
[ng] chunk {hardware-back-button-5afe3cb0-js} hardware-back-button-5afe3cb0-js.js, hardware-back-button-5afe3cb0-js.js.map (hardware-back-button-5afe3cb0-js) 2.06 kB  [rendered]
[ng] chunk {index-69c37885-js} index-69c37885-js.js, index-69c37885-js.js.map (index-69c37885-js) 37.7 kB  [rendered]
[ng] chunk {input-shims-a4fc53ac-js} input-shims-a4fc53ac-js.js, input-shims-a4fc53ac-js.js.map (input-shims-a4fc53ac-js) 13.5 kB  [rendered]
[ng] chunk {ios-transition-071bd421-js} ios-transition-071bd421-js.js, ios-transition-071bd421-js.js.map (ios-transition-071bd421-js) 26.4 kB  [rendered]
[ng] chunk {main} main.js, main.js.map (main) 130 kB [initial] [rendered]
[ng] chunk {md-transition-15a81b08-js} md-transition-15a81b08-js.js, md-transition-15a81b08-js.js.map (md-transition-15a81b08-js) 3.91 kB  [rendered]
[ng] chunk {pages-contacts-contacts-module-ngfactory} pages-contacts-contacts-module-ngfactory.js, pages-contacts-contacts-module-ngfactory.js.map (pages-contacts-contacts-module-ngfactory) 40.7 kB  [rendered]
[ng] chunk {pages-home-home-module-ngfactory} pages-home-home-module-ngfactory.js, pages-home-home-module-ngfactory.js.map (pages-home-home-module-ngfactory) 2.67 MB  [rendered]
[ng] chunk {pages-privacy-policy-privacy-policy-module-ngfactory} pages-privacy-policy-privacy-policy-module-ngfactory.js, pages-privacy-policy-privacy-policy-module-ngfactory.js.map (pages-privacy-policy-privacy-policy-module-ngfactory) 20.3 kB  [rendered]
[ng] chunk {pages-terms-conditions-terms-conditions-module-ngfactory} pages-terms-conditions-terms-conditions-module-ngfactory.js, pages-terms-conditions-terms-conditions-module-ngfactory.js.map (pages-terms-conditions-terms-conditions-module-ngfactory) 20.5 kB  [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 130 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 10.1 kB [entry] [rendered]
[ng] chunk {shadow-css-4889ae62-23996f3f-js} shadow-css-4889ae62-23996f3f-js.js, shadow-css-4889ae62-23996f3f-js.js.map (shadow-css-4889ae62-23996f3f-js) 14.8 kB  [rendered]
[ng] chunk {status-tap-a0df8284-js} status-tap-a0df8284-js.js, status-tap-a0df8284-js.js.map (status-tap-a0df8284-js) 1.79 kB  [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 461 kB [initial] [rendered]
[ng] chunk {swipe-back-35ad8e37-js} swipe-back-35ad8e37-js.js, swipe-back-35ad8e37-js.js.map (swipe-back-35ad8e37-js) 2.68 kB  [rendered]
[ng] chunk {swiper-bundle-ccdaac54-js} swiper-bundle-ccdaac54-js.js, swiper-bundle-ccdaac54-js.js.map (swiper-bundle-ccdaac54-js) 176 kB  [rendered]
[ng] chunk {tap-click-ca00ce7f-js} tap-click-ca00ce7f-js.js, tap-click-ca00ce7f-js.js.map (tap-click-ca00ce7f-js) 6.37 kB  [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 5.91 MB [initial] [rendered]
[ng] Date: 2020-03-31T13:32:06.335Z - Hash: c1d17ac421a93050c7f9 - Time: 31564ms
[INFO] Development server running!       
Local: http://localhost:8100
Use Ctrl+C to quit this process
> cordova build android --device
[INFO] ... and 78 additional chunks
[ng] ℹ ｢wdm｣: Compiled successfully.
[cordova] The "path" argument must be of type string. Received type undefined
> native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk --device --forward 8100:8100
[native-run] Selected hardware device 988626425743314c44
[native-run] Error: ENOENT: no such file or directory, open 'platforms/android/app/build/outputs/apk/debug/app-debug.apk'
[ERROR] An error occurred while running subprocess native-run.
native-run android --app
platforms/android/app/build/outputs/apk/debug/app-debug... exited with
exit code 1.
        
Re-running this command with the --verbose flag may provide more
information.

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.3.0 (/home/hbhat/.nvm/versions/node/v12.14.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.0
   @angular-devkit/schematics    : 9.1.0
   @angular/cli                  : 9.1.0
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 2.5.3, (and 27 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : 0.3.0

System:

   NodeJS : v12.14.1 (/home/hbhat/.nvm/versions/node/v12.14.1/bin/node)
   npm    : 6.13.7
   OS     : Linux 5.3
```

**Other Information:**

**Comment by dwieeb** [comment]
It's because Cordova is printing an error but for some reason the Ionic CLI isn't recognizing that it failed (perhaps it's exiting incorrectly).

```
[cordova] The "path" argument must be of type string. Received type undefined
```

Can you try running the following and copy/paste the output:

```
$ cordova run android
$ echo $?
```

**Comment by hanibhat** [comment]
Here is the output:


```
$ cordova run android
Discovered saved plugin "mx.ferreyra.callnumber". Adding it to the project
Plugin "call-number" already installed on android.
config file undefined requested for changes not found at /home/hbhat/Projects/Ionic/Kalimny/platforms/android/undefined, ignoring
The "path" argument must be of type string. Received type undefined
hbhat@hbhat-HP:~/Projects/Ionic/Kalimny$ echo $?
0
```

**Comment by dwieeb** [comment]
So Cordova is exiting incorrectly with exit code 0. I've seen the `The "path" argument must be of type string. Received type undefined` error before. It's an issue with one of the installed plugins. Can you try removing them until the Android build works?

**Comment by hanibhat** [comment]
The issue was that I had custom configuration for android on the project level: `/platforms/android/...` and the project was deleted at one point and regenerated later when `ionic cordova run android` was executed. Since the new generated project did not have the custom configuration, while it was referenced in `config.xml`, the build was failing.
@dwieeb Thank you! Your suggestion helped a lot. After removing all the plugins I released that the configuration was the only thing causing the failure.
