### ISSUE TITLE
ionic cordova resources gives 503 error

### ISSUE THREAD

**Issue by SebastianSchirmer** [ionic-team/ionic-cli#4384]
**Description:**
when calling ionic cordova resources I am getting a 503 error

**Steps to Reproduce:**
Call ionic cordova resources

**Output:**
$ ionic cordova resources
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
⠋ Uploading source images to prepare for transformations
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>

**My `ionic info`:**
```
Ionic:

   ionic (Ionic CLI) : 4.11.0 (/Users/schirmeur/.config/yarn/global/node_modules/ionic)
   Ionic Framework   : unknown
   @ionic/v1-toolkit : 1.0.5

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0, ios 5.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 2.5.3, (and 41 other plugins)

System:

   Android SDK Tools : 25.2.5 (/Users/schirmeur/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v8.16.1 (/usr/local/bin/node)
   npm               : 5.7.1
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by jcesarmobile** [comment]
The resources server has been deprecated for a long time (almost a year).
The Ionic CLI 5.xx introduced an offline alternative that was made default, but still had an option to use the online server. Then the online resources option was removed on CLI 6.x.x, and the server was shut down a few days ago.

**Comment by SebastianSchirmer** [comment]
@jcesarmobile Thanks very much for your reply and for pointing me towards the solution. Awesome!
