### ISSUE TITLE
Ionic Serve is stuck on "Files successfully emitted, waiting for typecheck results..."

### ISSUE THREAD

**Issue by Remling97** [ionic-team/ionic-cli#4392]
**Description:**
When i execute "ionic serve" in my project, the output looks as follows:

> react-scripts.cmd start
[react-scripts] i ｢wds｣: Project is running at http://192.168.1.114/
[react-scripts] i ｢wds｣: webpack output is served from
[react-scripts] i ｢wds｣: Content not from webpack is served from C:\Users\Remling\Desktop\Code\hello\public
[react-scripts] i ｢wds｣: 404s will fallback to /
[react-scripts] Starting the development server...
[react-scripts]
[react-scripts] Files successfully emitted, waiting for typecheck results...

But thats where it stops, no site is opening, no error message, nothing.

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 6.5.0 (C:\Users\Remling\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   NodeJS : v13.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

**Comment by RichardPragnell** [comment]
I had the same problem (perhaps something already running on port 8000?) try using a different port:
ionic serve --port=8080

**Comment by Remling97** [comment]
Hey, 
Thanks for the tip. tried it out, but it didnt work. 
I also tried a few different ports with the same results. 
Then i checked if something is already running on port 8000, but nothing is. 

If i start ionic serve, and check for the port again, the node process shows up as listening. So that should be fine, i dont understand why its not working

**Comment by Remling97** [comment]
ok, i got some new insights to the error.
everything is working as it should. I can just open the page with localhost:8100 and it works just find, even the live reload. ionic serve just doesnt open the browser window by itself for some reason

**Comment by WaelRabah** [comment]
Hey it seems to be a problem on Windows , same app on linux works fine but on windows I get this problem

**Comment by stolenng** [comment]
I'm having the same on mac,
First compilation works good, after i change line of code it either stuck on:
`[react-scripts] Compiling...` or `[react-scripts] Files successfully emitted, waiting for typecheck results...`

Then my css is not reflected on browser and can't work like this at all :/

**Comment by jokeane** [comment]
I'm having same problem on Windows. Also cannot get the lab feature to work either.

**Comment by unski11ed** [comment]
Had the same problem, resolved by downgrading `react-scripts` from `3.4.1` to `3.4.0`.

**Comment by h-morales** [comment]
To downgrade the react-scripts do the ff:

npm uninstall react-scripts -S
npm i react-scripts@3.4.0

ionic serve

**Comment by imhoffd** [comment]
With a workaround in place, I'm closing this as it isn't an issue w/ Ionic CLI.

**Comment by shide1989** [comment]
I have the same issue with ionic @3.4.0

**Comment by HatemSat** [comment]
Same here.

**Comment by Mixermachine** [comment]
The install guide with
`ionic start myApp tabs`
installs react-scripts with version ^3.4.1 and thus hangs for ever at the 
` [react-scripts] Files successfully emitted, waiting for typecheck results...`
dialog.
A normal npm start works.

For somebody just starting out with Ionic, this might be a bad experience.

Hope it is ok if I link you @dwieeb

**Comment by rvion** [comment]
@dwieeb Please, could you reopen this issue ?

This is a major bug affecting all new projects and making hot reload non-functional.

This should be a major issue IMO.

All newcomers will encounter this issue.

** Also, I doubt this is only a react issue, as manually updating the `capacitor.config.json` work**
indeed, manually tweaking the server entry of `capacitor.config.json` will make capacitor hot reload work

```
 "server": {
    "url": "http://192.168.2.102:8100",
    "cleartext": true
  }
```

**Comment by imhoffd** [comment]
Sure, I just [updated the starters](https://github.com/ionic-team/starters/commit/7558ec904814b0ef963b6ffab7311b3e8b25d030) to revert to using 3.4.0 for now.
