### ISSUE TITLE
Option to create CSS only Ionic apps

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-cli#4394]
Hi,

We need an option to create an Ionic app only using CSS. But now it gives SCSS files by default. We cannot change this to support only for CSS.

Link: https://ionicframework.com/docs/cli/commands/start

**Comment by dwieeb** [comment]
Thanks for the issue. I'm going to merge it into https://github.com/ionic-team/ionic-cli/issues/3499
