### ISSUE TITLE
installing sample app, by wizard or manually always fails.

### ISSUE THREAD

**Issue by ccmpuravida** [ionic-team/ionic-cli#4395]
**Describe the bug**
With wizard or manually always fail to install the sample app.

**To Reproduce**
Go to create your Ionic App, any method, 
after ionic start myApp tabs 

**Expected behavior**
success start.

Log
5025 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...R79pl3w5OTMxVN2YkM1zA'
5025 verbose stack     at JSON.parse (<anonymous>)
5025 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
5025 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
5025 verbose stack     at runMicrotasks (<anonymous>)
5025 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
5026 verbose cwd C:\Users\Christian\connected
5027 verbose Windows_NT 10.0.18362
5028 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
5029 verbose node v12.16.2
5030 verbose npm  v6.14.4
5031 error Unexpected end of JSON input while parsing near '...R79pl3w5OTMxVN2YkM1zA'
5032 verbose exit [ 1, true ]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Comment by mlynch** [comment]
Moved from the wizard issues repo as it's not about the wizard start command

**Comment by dwieeb** [comment]
This is a common issue with npm. It is unrelated to the Ionic CLI. I know people have solved this issue a number of different ways, primarily by using `npm cache clean -f` or properly configuring the proxy for their network. These resources may help:

- https://github.com/npm/npm/issues/19072
- https://github.com/ionic-team/ionic-cli/issues/3298
- https://ionicframework.com/docs/cli/using-a-proxy
