### ISSUE TITLE
Error while installing npm dependencies for 'List' starter template #4316

### ISSUE THREAD

**Issue by barzotto** [ionic-team/ionic-cli#4401]
**Description:**

hi guy i'm Luca, i'm installing Angular cli but i have this problem , i haven't a proxy at my home:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lucagiffi/.npm/_logs/2020-04-25T10_49_46_355Z-debug.log

all rum on my macbook pro.
can you help me?

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

**Comment by barzotto** [comment]
UPDATE:
I HAD RESOLVE the permission issue 
but i have this problem again:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
help me

**Comment by dwieeb** [comment]
That's just a warning. You can ignore it.
