### ISSUE TITLE
React .env variable access

### ISSUE THREAD

**Issue by dahalsantosh007** [ionic-team/ionic-cli#4402]
I am trying to use .env in my Ionic/react project. I have a .env file with REACT_APP prefix added to the variable and it isn't working for me. There is no proper documentation on how to overcome such a problem. I have poured through documentation and one of the solutions was to get Ionic CLI 6.2.1, however, I wasn't able to get that either. I get an error saying it is not a valid version. Is there any way to solve this problem. I have ionic 6.6.0 and I am using react js not tsx for my project. One more thing I wasn't able to uninstall ionic CLI. Every time I tried to uninstall I get message saying up to date. Please help me out here guys.

**Comment by dwieeb** [comment]
This isn't really a support room. If there are specific, reproducible bugs for the Ionic CLI, please create separate issues and fill out the issue template.

**Comment by dwieeb** [comment]
FWIW I tested this with an `.env` file as per the [React Scripts docs](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env) and it worked. You are welcome to use the [Ionic Forum](https://forum.ionicframework.com/) for community support.
