### ISSUE TITLE
ionic cordova run browser showing Cannot GET /login

### ISSUE THREAD

**Issue by manojbharti** [ionic-team/ionic-cli#4405]
When I am running my ionic4 app on browser by command ionic cordova run browser it is showing Cannot GET /login on browser. It works only first time when I run localhost:8000/index.html but when I change url it shows Cannot GET /home. Please provide any solution

**Comment by dwieeb** [comment]
The solution is to not use the Cordova browser platform. We don't support it. See https://github.com/ionic-team/ionic-cli/issues/2312#issuecomment-365732607 and https://github.com/ionic-team/ionic-cli/issues/3043

**Comment by manojbharti** [comment]
@dwieeb I want to use my ionic-5 app for all three platforms like ios, android, and web.
I am able to use for android and ios, but how can I use it for web. Please guide me if I'm wrong.

**Comment by dwieeb** [comment]
@manojbharti We have [docs](https://ionicframework.com/docs/core-concepts/cross-platform) on cross-platform development. Please use community resources for additional questions.
