### ISSUE TITLE
ionic start myApp --type=angular failure

### ISSUE THREAD

**Issue by wangli1992** [ionic-team/ionic-cli#4412]
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's 
altnames: Host: registry.npm.taobao.org. is not in the cert's altnames: 
DNS:img.ucdl.pp.uc.cn, DNS:iscsi.ucdl.pp.uc.cn, DNS:slient.ucdl.pp.uc.cn, 
DNS:alissl.ucdl.pp.uc.cn, DNS:cdn.osupdateservice.yunos.com, 
DNS:oss.ucdl.pp.uc.cn

    at Object.checkServerIdentity (tls.js:228:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1059:27)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)

npm config ls
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.4.1 node/v10.13.0 darwin x64"

; userconfig /Users/XXX/.npmrc
registry = "https://registry.npmjs.org/"
strict-ssl = false

; node bin location = /Users/XXX/.nvm/versions/node/v10.13.0/bin/node
; cwd = /Users/XXX/Documents/workspace
; HOME = /Users/XXX
; "npm config ls -l" to show all defaults.

node -v 
10.13.0
ionic -v
4.1.2
npm -v
6.4.1

**Comment by dwieeb** [comment]
You likely need to configure your environment for your network proxy:

* Please carefully follow the docs: https://ionicframework.com/docs/cli/using-a-proxy
* Your organization needs to provide proxy details for you. If you don't know the details, talk with your network administrator.
* Remember to avoid disabling SSL verification. This can lead to prolonged insecure configuration with your computer.
