### ISSUE TITLE
unable to use ng-add in ionic 5 (--type=ionic-angular) super starter

### ISSUE THREAD

**Issue by unclemaths** [ionic-team/ionic-cli#4415]
I am unable to use angular commands with the super starter.
I could not use NgbModules at all because it needed **ng add** in the program.
I love the super starter for the slides and the translate feature. But I also need a landing page with cool Material designs or bootstrap 4 capabilities

**Comment by dwieeb** [comment]
`ionic-angular` is not Ionic 5. The super starter hasn't been updated in a long time. Please use `--type=angular` or pick from the dropdown.

**Comment by unclemaths** [comment]
@dwieeb Thank you for your response. 
I need to combine the slider (found on the opening pages of the super starter) with a regular angular bootstrap page or material design page.
The problem is: it is not accepting ng add.

Please, is there a way around this challenge?
I mean starting my app with the super starter and using ng add @ng bootstrap/schematics to develop any other page in the app?

**Comment by dwieeb** [comment]
Might be worth asking in the [Ionic Forum](https://forum.ionicframework.com/). I honestly don't know the best approach.

**Comment by unclemaths** [comment]
Thank you, boss..
