### ISSUE TITLE
It is not possible to configure angular version associated to ionic start

### ISSUE THREAD

**Issue by juanico18** [ionic-team/ionic-cli#4424]
I am going to migrate a project from ionic 3/angular 5 to Ionic4/Angular 7. Is there a way to the cli generate angular7 dependencies instead angular8 on ionic start as first step of migration?
Thanks

**Comment by dwieeb** [comment]
Not really, unfortunately. You may be able to start an Angular 7 project with the Angular CLI and then use `ng add @ionic/angular`, but I can't promise it works.

**Comment by dwieeb** [comment]
Merging this into https://github.com/ionic-team/ionic-cli/issues/3499 as a reminder to support previous versions.
