### ISSUE TITLE
ionic cordova run ios doesn't work with livereload

### ISSUE THREAD

**Issue by hemangshah** [ionic-team/ionic-cli#4428]
**Description:**

I want to run ionic project to iOS simulator so I can see how my app look like in iOS. Here if I can simply run this command `ionic cordova prepare ios` then I can open the project with XCode IDE and can run it, but when if execute with this command `ionic cordova run ios --livereload` it fails and get stuck. See the screenshot attached.

**Steps to Reproduce:**

This command I execute to run my ionic project into an iOS simulator with livereload.

```
ionic cordova run ios --livereload
```

**Output:**

![Simulator Screen Shot - iPhone XS Max - 2020-05-08 at 16 11 14](https://user-images.githubusercontent.com/3313412/81466810-09c15600-91f2-11ea-95ae-27fe4a133e21.png)

**My `ionic info`:**

```
Ionic:

   Ionic CLI          : 6.8.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 28 other plugins)

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.1 (/usr/local/bin/node)
   npm        : 6.14.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4.1 Build version 11E503a
```

**Other Information:**

I'm new ionic platform and my app source code as well, if you thinks the attached screenshot is showing some custom component that should be fine because even if I close this custom error popup nothing will happen my app will get stuck forever. I can't do anything further.

_Here I want to add that the same app runs well on my team mates system so I'm sure that there's no error in code which is stopping me to do a livereload._

Please let me know if I can provide more information to help you understand the problem.

**Comment by dwieeb** [comment]
I would recommend posing this as a question for the community. It looks like your app has a runtime error. This isn't a bug with the Ionic CLI.
