### ISSUE TITLE
It looks like your app isn't integrated with Capacitor or Cordova

### ISSUE THREAD

**Issue by alexcroox** [ionic-team/ionic-cli#4461]
**Description:**
I have a Capacitor app running fine in iOS and Android stores. I am trying to integration App Flow live deployments but the cli refuses to see my project as a Capacitor project and I'm not sure why. Can you tell me what files/directories it looks for to determine this?

**Steps to Reproduce:**

```
➜  sml git:(master) ✗ ionic init
? Project name: testing
[WARN] Could not determine project type.

       Please choose a project type from the list.

? Project type: Custom (custom)
[OK] Your Ionic project has been initialized!
➜  sml git:(master) ✗ ionic deploy configure
[ERROR] Deploy (cordova-plugin-ionic) not yet installed.

        Please run ionic deploy add
➜  sml git:(master) ✗ ionic deploy add
[ERROR] It looks like your app isn't integrated with Capacitor or Cordova.
```

I'm using Vue but not @ionic/vue

**Output:**

[ERROR] It looks like your app isn't integrated with Capacitor or Cordova.

        In order to use the Appflow Deploy plugin, you will need to integrate your app with Capacitor or Cordova. See
        the docs for setting up native projects:

        iOS: https://ionicframework.com/docs/building/ios
        Android: https://ionicframework.com/docs/building/android

**My `ionic info`:**

```
Ionic:

   Ionic CLI : 6.10.0 (/Users/alex/.nvm/versions/node/v10.15.3/lib/node_modules/@ionic/cli)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (/Users/alex/.nvm/versions/node/v10.15.3/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by dwieeb** [comment]
Try running `ionic integrations enable capacitor`.

**Comment by alexcroox** [comment]
That worked thanks, added

```
"integrations": {
    "capacitor": {}
  },
```

which is what ionic-cli must have been looking for
