### ISSUE TITLE
"ionic cordova run android" with nightly cordova-android builds the apk but fails to run

### ISSUE THREAD

**Issue by avidan-chen** [ionic-team/ionic-cli#4464]
**Description:**
Running "ionic cordova run android" with latest nightly cordova-android builds the apk but fails to run it with the message (in verbose mode):
ionic:lib:cordova:project Output file does not match expected format

**Steps to Reproduce:**
Upgrade to latest cordova-android nightly (latest commit updated to Gradle 6.5 & Android Gradle plugin 4.0.0).
Run "ionic cordova run android".

**Output:**
ionic:lib:cordova:project Output file does not match expected format

[ERROR] Could not parse build output file:
        /Users/Avidan/Documents/my-app/platforms/android/app/build/outputs/apk/debug/output.json

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : android 9.0.0-nightly.2020.6.9.305cb2cd
   Cordova Plugins   : cordova-plugin-ionic-webview 5.0.0, (and 8 other plugins)

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/Avidan/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.15.0 (/usr/local/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c```

**Comment by dwieeb** [comment]
I think the format of the file may have changed in Gradle 6. See https://github.com/ionic-team/ionic-cli/issues/4467.

Can you post the contents of `platforms/android/app/build/outputs/apk/debug/output.json`?

**Comment by imhoffd** [comment]
6.10.1 should work. Thanks!

**Comment by avidan-chen** [comment]
Thanks! The new version solved the issue.
