### ISSUE TITLE
bug: "ionic deploy" does not save app-id, channel-name, or update-method for Capacitor project

### ISSUE THREAD

**Issue by danielzen** [ionic-team/ionic-cli#4465]
# Bug Report
Integrating with Capacitor & AppFlow before adding a Platform does not save AppFlow's AppId, ChannelName, or UpdateMethod to either `ionic.config.json` or `capacitor.config.json`

**Ionic version:**

[x] **4.x**

**Current behavior:**

Adding a Capacitor platform does not add any existing AppFlow deploy configuration.
Also, if you remove a Capacitor Platform (ios, android, electron) and add it back in, AppFlow settings are lost.

**Expected behavior:**

Adding a Capacitor Platform should also add any existing AppFlow deploy settings

**Steps to reproduce:**

  1. Create an Ionic App
  2. When asked to integrate with Capacitor, say YES
  3. run `ionic deploy add --app-id="XX" --channel-name="XX" --update-method="XX"
  4. `npx cap add XX`

All ionic deploy settings are lost. None are saved to the platform specified

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/Users/zen/.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.2
   @capacitor/core : 2.1.2

Utility:

   cordova-res (update available: 0.14.0) : 0.12.1
   native-run                             : 1.0.0

System:

   NodeJS : v12.16.1 (/Users/zen/.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.14.5
   OS     : macOS Mojave
```

**Comment by danielzen** [comment]
One other thing. Occasionally, the ionic-cli will recommend using variables in your Info.plist such as 
```
        <key>IonApi</key>
        <string>$UPDATE_API</string>
        <key>IonMinBackgroundDuration</key>
        <string>$MIN_BACKGROUND_DURATION</string>
        <key>IonMaxVersions</key>
        <string>$MAX_STORE</string>
        <key>IonChannelName</key>
        <string>$CHANNEL_NAME</string>
```
But when integrating with Capacitor, these appear to be red herrings.

**Comment by smzelek** [comment]
This is a known issue. In order to workaround it: simply run `ionic deploy configure` _after_ adding the platform for Capacitor instead of beforehand.
