### ISSUE TITLE
Output file does not match expected format:

### ISSUE THREAD

**Issue by gireeshspr** [ionic-team/ionic-cli#4467]
**Description**

First time configuring and running android application on a mac.
When running the command, ionic cordova run android --verbose, build is successful but fail to parse the output file and run simulator. Please provide an insight to resolve this issue.

**Steps to Reproduce:**
run command 
ionic cordova run android --verbose

**Output:**
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 1s
39 actionable tasks: 39 up-to-date
Command finished with error code 0: /Users/xy/devproj/platforms/android/gradlew cdvBuildDebug,-b,/Users/xy/devproj/platforms/android/build.gradle
Built the following apk(s): 
	/Users/xy/devproj/platforms/android/app/build/outputs/apk/debug/app-debug.apk
No scripts found for hook "after_compile".
No scripts found for hook "after_build".
  ionic:lib:cordova:project Output file does not match expected format: {
  ionic:lib:cordova:project   version: 1,
  ionic:lib:cordova:project   artifactType: { type: 'APK', kind: 'Directory' },
  ionic:lib:cordova:project   applicationId: 'io.ionic.starter',
  ionic:lib:cordova:project   variantName: 'debug',
  ionic:lib:cordova:project   elements: [
  ionic:lib:cordova:project     {
  ionic:lib:cordova:project       type: 'SINGLE',
  ionic:lib:cordova:project       filters: [],
  ionic:lib:cordova:project       properties: [],
  ionic:lib:cordova:project       versionCode: 1,
  ionic:lib:cordova:project       versionName: '1',
  ionic:lib:cordova:project       enabled: true,
  ionic:lib:cordova:project       outputFile: 'app-debug.apk'
  ionic:lib:cordova:project     }
  ionic:lib:cordova:project   ]
  ionic:lib:cordova:project } +0ms
[ERROR] Could not parse build output file:
/Users/xy/devproj/platforms/android/app/build/outputs/apk/debug/output.json
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 2 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +19ms

**My `ionic info`:**
Ionic:
   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:
   cordova-res : 0.14.0
   native-run  : 1.0.0

System:
   Android SDK Tools : 26.1.1 (/Users/xx/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.0 (/usr/local/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c

**Other Information:**

**Comment by renatop7** [comment]
Any solutions to this problem? I'm facing the same issue.

```
Ionic:

   Ionic CLI                     : 6.10.0 (C:\Users\parre\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 25 other plugins)

Utility:

   cordova-res                          : not installed
   native-run: 1.0.0

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v12.15.0
   npm               : 6.14.5
   OS                : Windows 10
```

**Comment by dwieeb** [comment]
What are the contents of `platforms/android/app/build/outputs/apk/debug/output.json`?

**Comment by zrev2220** [comment]
@dwieeb 

```json
{
  "version": 1,
  "artifactType": {
    "type": "APK",
    "kind": "Directory"
  },
  "applicationId": "REDACTED",
  "variantName": "debug",
  "elements": [
    {
      "type": "SINGLE",
      "filters": [],
      "properties": [],
      "versionCode": 104,
      "versionName": "104",
      "enabled": true,
      "outputFile": "app-debug.apk"
    }
  ]
}
```

**Comment by dwieeb** [comment]
Weird, that's totally unlike mine and I have the same versions of everything.

```json
[
  {
    "outputType": {
      "type": "APK"
    },
    "apkData": {
      "type": "MAIN",
      "splits": [],
      "versionCode": 1,
      "versionName": "1.0",
      "enabled": true,
      "outputFile": "app-debug.apk",
      "fullName": "debug",
      "baseName": "debug",
      "dirName": ""
    },
    "path": "app-debug.apk",
    "properties": {}
  }
]
```

**Comment by zrev2220** [comment]
@dwieeb I think it's Gralde 6.2.2? Below is output from `gradle -v` if that's what you're after.

```
------------------------------------------------------------
Gradle 6.2.2
------------------------------------------------------------

Build time:   2020-03-04 08:49:31 UTC
Revision:     7d0bf6dcb46c143bcc3b7a0fa40a8e5ca28e5856

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_251 (Oracle Corporation 25.251-b08)
OS:           Windows 10 10.0 amd64
```

I recall when first setting up the project (first adding the `android` platform, I think), I had to do something janky with something Android- or Gradle-related to fix an issue. I can try to reproduce that after the weekend and see if I tweaked something to make our versions diverge.

**Comment by zrev2220** [comment]
@gireeshspr Don't let me commandeer your issue if you have details different from mine. I can start a new one to separate concerns if necessary.

**Comment by dwieeb** [comment]
@zrev2220 Based on the output of the file in the output provided by @gireeshspr, I can confirm you have the same issue, so no worries.

I think this is what I'm after:

```
./platforms/android/gradlew --version
```

**Comment by zrev2220** [comment]
@dwieeb Ran that command, identical output:

```
$ platforms\android\gradlew --version

------------------------------------------------------------
Gradle 6.2.2
------------------------------------------------------------

Build time:   2020-03-04 08:49:31 UTC
Revision:     7d0bf6dcb46c143bcc3b7a0fa40a8e5ca28e5856

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_251 (Oracle Corporation 25.251-b08)
OS:           Windows 10 10.0 amd64
```

**Comment by gireeshspr** [comment]
Sorry for the delay in response, problem still exists. My output json is already there in the request but its not well formatted in the copy paste. Yes my output resembles exactly the same. @dwieeb is correct. 
{
  "version": 1,
  "artifactType": {
    "type": "APK",
    "kind": "Directory"
  },
  "applicationId": "io.ionic.starter",
  "variantName": "debug",
  "elements": [
    {
      "type": "SINGLE",
      "filters": [],
      "properties": [],
      "versionCode": 1,
      "versionName": "1",
      "enabled": true,
      "outputFile": "app-debug.apk"
    }
  ]
}

**Comment by dwieeb** [comment]
This appears to be related to the Gradle version used. I wasn't able to narrow down exactly where `output.json` is generated. If anyone has insight into this it would be greatly appreciated!

I am making a release with this fix now.

**Comment by imhoffd** [comment]
Okay, 6.10.1 is out! Please let me know if you run into any more issues. Thanks! 💙

**Comment by gireeshspr** [comment]
Excellent @dwieeb! Your changes on the latest Ionic CLI build 6.10.1 works. Thanks

**Comment by MarioC3** [comment]
I'm still seeing this problem when running: `ionic cordova run android -lc --release --prod --device`

This is my ionic info:

```
Ionic:

   Ionic CLI                     : 6.11.7 (/Users/marioacarlos/.nvm/versions/node/v12.16.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 10.0.0
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.15.1) : 0.14.0
   native-run                             : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/marioacarlos/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : ios-sim/9.0.0 darwin-x64 node-v12.16.2
   NodeJS            : v12.16.2 (/Users/marioacarlos/.nvm/versions/node/v12.16.2/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708
```

Any ideas?

**Comment by imhoffd** [comment]
@MarioC3 Can you supply all the information I asked for in this issue? `ionic info` isn't enough.

**Comment by AhmedBenyahia** [comment]
I have the same issue with cli 6.11.8, I've created a new issue  #4546
