### ISSUE TITLE
feat: support react environment variables REACT_APP_ at build time

### ISSUE THREAD

**Issue by Toub** [ionic-team/ionic-cli#4469]
Create react app support `Adding Custom Environment Variables` at build time: <https://create-react-app.dev/docs/adding-custom-environment-variables/>

It looks it is not supported by build commands such as `ionic cap sync`.

Is there a way to configure my react environment?

**Comment by dwieeb** [comment]
It works for me. I added the following to `Home.tsx`:

```diff
 const HomePage: React.FC = () => {
+  console.log(process.env.REACT_APP_MYVAR);
```

Then ran the following:

`REACT_APP_MYVAR=test ionic cap sync android`

Is there something specific and actionable that is not working?

**Comment by Toub** [comment]
Right, my bad. Thanks.
