### ISSUE TITLE
ionic cordova platform add android

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-cli#4474]
**Description:**

I have created and tested on ionic 3 and ionic 5 both are having same behaviour
earlier we used to have all cordova plugin in dependencies

**Steps to Reproduce:**

![image](https://user-images.githubusercontent.com/23274631/85417784-a450db00-b58d-11ea-9267-c10742e26ddc.png)

**Output:**

**My `ionic info`:**

```
ionic info

Ionic:

   Ionic CLI          : 5.4.4 (C:\Users\indra26\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.9

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Other Information:**

**Comment by imhoffd** [comment]
I'm not really understanding what's wrong here.

**Comment by indraraj26** [comment]
earlier when we used to add ionic cordova platform add android on newly created project all the cordova plugin gets added in dependencies object of package.json, Now CLI is adding in devDependencies object. Is it okay? When you visit ionic native docs example camera cordova when you add with ionic cordova plugin add cordova-plugin-camera its get added in dependencies.

Step to reproduce: 
1. ionic start  (any name of your project and choose angular framework)
2. ionic cordova platform add android

and see the package.json

**Comment by imhoffd** [comment]
Thanks for explaining! I believe the Cordova CLI is doing this when adding the platform:

```
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-statusbar' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-device' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-splashscreen' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-ionic-webview' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-ionic-keyboard' found in config.xml... Migrating it to package.json
```

This is fine for now, it doesn't actually matter if they're in dependencies or devDependencies for apps (only libraries). We won't be changing this at this time. Thanks for the issue!

**Comment by indraraj26** [comment]
If they are in devDependencies then how these binary can be available in final bundle ?

**Comment by imhoffd** [comment]
The dependencies/devDependencies configuration is only for npm packages.

**Comment by indraraj26** [comment]
these cordova plugin is also part of npm ecosystem, I dont know anyway It is working that's it what we want whether it will be in devDependencies or dependencies.
