### ISSUE TITLE
project structure of `ionic start` projects has changed in bad way

### ISSUE THREAD

**Issue by ibes** [ionic-team/ionic-cli#45]
Hi, 

seems like there have been some changes how projects are initialized. 

Why this https://github.com/driftyco/ionic-cli/blob/master/lib/ionic/start.js#L168?

I really don't care what name the boilerplate had, I used. 
Why force me to have such ugly folder names like `ionic-app-base-master` - just call it "app" or something. 

But where does the "ionic.project" file comes from? What is it for?
Why not put it beside the rest of the app?

Seems ugly this way and forces me to make another `cd ugly-folder-name` to be able to do some `gulp`, `ionic` etc stuff.

This also crashs your documentation as it needs the info to have another `cd`.

Seems like a mistake and doesn't seems like fun.

**Comment by h4harish** [comment]
if am writing on command prompt npm start myApp sidemenu this command is throwing a module.js:328
throw err;

Error: Cannot find module 'C:\Users\harish\AppData\Roaming\npm\node_modules\ionic\bin\ionic'
how to solve this..please solve IT

**Comment by h4harish** [comment]
am using node --version v5.4.0,please solve this .

**Comment by ibes** [comment]
Maybe you haven't install the dependicies of ionic. 
I guess it will work through `npm install` (but I haven't created something with npm in some month)

Your question is most likely not related to this ticket so this is not the right place to ask.

**Comment by h4harish** [comment]
ok thanks for reply dude.
