### ISSUE TITLE
Ionic CLI Not found (Node v12.16.1 lts - Npm v6.14.7)

### ISSUE THREAD

**Issue by shide1989** [ionic-team/ionic-cli#4506]
**Description:**
hi guys,

It looks like your package @ionic/cli cannot be found with the LTS version of NodeJS (which we want ot use)

**Steps to Reproduce:**
Install Node LTS v12.16.1
install npm v6.14.7

**Output:**
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ionic%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@ionic/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shide/.npm/_logs/2020-08-06T11_13_58_097Z-debug.log

node -v
v12.16.1
npm -v
6.14.7

**My `ionic info`:**

```

Ionic:

   ionic (Ionic CLI)  : 4.1.1
   Ionic Framework    : ionic-angular 3.9.10
   @ionic/app-scripts : 3.2.4

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (/Users/shide/Library/Android/sdk)
   NodeJS            : v12.16.1 (/Users/shide/.nvm/versions/node/v12.16.1/bin/node)
   npm               : 6.14.7
   OS                : macOS


```

That's it !
Any other recommandations about the NodeJS versions is welcome

**Comment by shide1989** [comment]
you can use nvm to switch to Node LTS version : `nvm install --lts && nvm use --lts`

**Comment by imhoffd** [comment]
It 100% exists. It has over 60k weekly downloads. Also, node version doesn't matter when installing packages, only when using them.

What's more likely is you're behind a firewall or proxy server that is messing with your connection: https://ionicframework.com/docs/cli/using-a-proxy

Here's a comment from a similar issue that may help: https://github.com/ionic-team/ionic-cli/issues/3656#issuecomment-439976578

**Comment by shide1989** [comment]
I think NPM might have had some troubles this afternoon... 
Because it effectively worked just fine a few hours later (I didn't change wifi..)
