### ISSUE TITLE
Capacitor commands don't respect integration root directory override

### ISSUE THREAD

**Issue by eweap** [ionic-team/ionic-cli#4526]
Hello,

I've tried to run `ionic capacitor run android -l --external` but found out that it calls `capacitor add android` even if `android` platform is already installed and configured (and it fails because, android in already installed).

Then I found that there is a `checkForPlatformInstallation(platform: string)` call that happens in the command pre-run

The problem is at this line, when we try to retrieve the capacitor integration root:
https://github.com/ionic-team/ionic-cli/blob/28d854041d418fdd4c36233eb47af177506fdbaf/packages/%40ionic/cli/src/commands/capacitor/base.ts#L120

in my case the capacitor integration root was overrided to point in a another subdirectory in `ionic.config.json`:
```
{
    "defaultProject": "app-mobile",
    "projects": {
        "app-mobile": {
            "name": "App mobile",
            "type": "angular",
            "id": "MY_ID",
            "npmClient": "yarn",
            "root": "apps/app-mobile",
            "integrations": {
                "capacitor": {
                    "root": "integrations/app-mobile/capacitor"
                }
            }
        }
    }
}
```

I think that the capacitor integration root should be retrieve this way:
```
const integrationRoot = this.project.getIntegration('capacitor').root;
```

It looks like to work in both case, when root is overrided or not.

I don't know if we must replace the others calls to `this.project.directory` in the `ionic-cli/packages/@ionic/cli/src/commands/capacitor/base.ts` file ?

Let me know if you're interrested in a pull request with a fix.

Thanks !

**Comment by imhoffd** [comment]
@eweap Thanks for digging into this issue! It looks like you're on the right track, those should use `this.integration.root`. If you want to make a PR, I'd be happy to look at it.

**Comment by eweap** [comment]
I don't have to much time to push investigations further, I'm now placing my integration folders in `root` directory and I'm fine with it.

I'm closing this issue. Thanks !
