### ISSUE TITLE
crosswalk-lite apk size issue

### ISSUE THREAD

**Issue by groggy84** [ionic-team/ionic-cli#454]
non crosswalk build size 2.3Mb
crosswalk build size 20Mb
crosswalk-lite buid size 32Mb

why lite size to big non lite?

My ionic Info---------------------------------------
Cordova CLI: 4.2.0
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.0
Xcode version: Xcode 6.1.1 Build version 6A2008a

**Comment by jbavari** [comment]
Not sure. The build the crosswalk team releases is marked as experimental. 

I can't give much insight to that.

**Comment by vasumahesh1** [comment]
I have a similar Issue, Crosswalk & Crosswalk Lite both are giving me Identical sizes. (26MB approx) ... Is this normal? or just that Ionic is not yet configured with crosswalk-lite ...  I was expecting a size reduction but that just killed my hopes ... 



Your system information:
My Info:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
OS: Windows 8.1
Node Version: v0.12.4

**Comment by MrPro100** [comment]
+1

**Comment by ffabreti** [comment]
+1

**Comment by baleboy** [comment]
I don't know how importing crosswalk lite in ionic works, but the latest version we have published is 10 (https://download.01.org/crosswalk/releases/crosswalk-lite/android/canary/) so I wonder what "version": "12.41.296.5" above means.

**Comment by baleboy** [comment]
Also, is the crosswalk-lite build split in arm and x86 packages?

**Comment by vasumahesh1** [comment]
Yes its split into ARM and x86 Builds. You ll need to sign those APKs both of them at the time of Release.

**Comment by vasumahesh1** [comment]
I finally gave up on this, Published the Crosswalk builds for SDK Level Below 18 (4.3 and Below), for 19 and Above I had published the regular one.

But It would be great to know why Crosswalk vs Crosswalk Lite is not giving any size reduction difference?

**Comment by vection** [comment]
+1

**Comment by rodrigodrds** [comment]
I have a problem that seems different.
 I did release crosswalk, separate x86 and ARMv7, but when risen to Google Play.
 The version 104 022 is not available for any device configuration: all devices that can receive 104,022 would receive a version of the versions 104,024.
 Theoretically the ARMv7 was 104,022, and 104,024 is x86, but the two in detail shows in native platforms like arm64-V8A, armeabi, armeabi-v7a, x86, x86_64.
I will try reinstalling the crosswalk to rebuild

**Comment by cihadhoruzoglu** [comment]
+1

**Comment by AhsanAyaz** [comment]
+1

**Comment by gaguirre** [comment]
+1

**Comment by floatin** [comment]
+1

**Comment by nicon-dev** [comment]
+1

problem still exists. Crosswalk-lite build is the same size that the normal crosswalk build.

Cordova CLI: 5.3.3
Gulp version: CLI version 3.9.0
Gulp local: Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.7.10
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.7.0 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.1.1 Build version 7B1005

**Comment by Requiescat** [comment]
+1 I got an apk from 3mo to 30 mo ! with crosswalk

**Comment by venu1412** [comment]
+1

**Comment by ivks** [comment]
+1

**Comment by tinchoforever** [comment]
+1

**Comment by asimmon** [comment]
+1

**Comment by princefr** [comment]
+1

**Comment by abdoutelb** [comment]
+1 
always  above 20 Mb even with latest version
ionic browser add crosswalk-lite@17.46.449.1

**Comment by ljcljc** [comment]
+1

**Comment by fgilio** [comment]
+1

**Comment by altmind** [comment]
+1

**Comment by manu2504** [comment]
+1

**Comment by dwieeb** [comment]
Crosswalk is no longer maintained (see https://github.com/crosswalk-project/crosswalk), so we can't support it.
