### ISSUE TITLE
Current working directory is not a Cordova-based project.

### ISSUE THREAD

**Issue by spandey1296** [ionic-team/ionic-cli#4548]
I created a Phonegap project according to instructions, checked it into SVN, checked it out, and then discovered I could no longer run the build command--necessary to have changes to www be replicated to each platform and I am getting the current working directory is not a Cordova-based project.
Even though I have imported all libraries and run the command
$Cordova create mobile
Then I tried to run
$Cordova platform add android
Which gave me the same error 'Current working directory is not a Cordova-based project'.

**Comment by imhoffd** [comment]
It looks like you're not using the Ionic CLI, so this isn't an issue that should be reported in the Ionic CLI repo.
