### ISSUE TITLE
ionic serve script doesn't work on PC but npm run start works

### ISSUE THREAD

**Issue by dstN** [ionic-team/ionic-cli#4552]
I just started with "[Your first ionic App: react](https://ionicframework.com/docs/react/your-first-app)"

Went through all install-steps and typed in "ionic serve" but only this happens:

![image](https://user-images.githubusercontent.com/960879/92957795-6fa43f80-f469-11ea-9c80-5c80504d791d.png)

If I check on that URL it just says "Connection refused."

If I try with `npm run start` instead, it works fine.

**Steps to Reproduce:**
Well... I just took VSC, and followed the steps on the link above.

**Output:**
Look at the screen above.

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 6.11.8 (C:\Users\webma\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.3.2

Capacitor:

   Capacitor CLI   : 2.4.1
   @capacitor/core : 2.4.1

Utility:

   cordova-res : 0.15.1
   native-run  : 1.1.0

System:

   NodeJS : v12.18.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Comment by dstN** [comment]
Same problem if I want to do this: [https://ionicframework.com/docs/react/your-first-app/7-live-reload](https://ionicframework.com/docs/react/your-first-app/7-live-reload)

Nothing happens, Android Studio never opens, I can't do anything... console looks the same:
![image](https://user-images.githubusercontent.com/960879/93151307-de98c700-f6fb-11ea-85f2-a982df945655.png)

**Comment by imhoffd** [comment]
Can you run with the `--verbose` flag in your terminal?

**Comment by dstN** [comment]
> Can you run with the `--verbose` flag in your terminal?

![image](https://user-images.githubusercontent.com/960879/93387635-d8c0f400-f869-11ea-9db0-75bc707de1ed.png)

after this: 

more than 100 "express:router:layer" entries 

after that:

![image](https://user-images.githubusercontent.com/960879/93387941-466d2000-f86a-11ea-9ee3-1394642f6a43.png)

![image](https://user-images.githubusercontent.com/960879/93387996-584ec300-f86a-11ea-9349-2133162ab008.png)

Thats all.

**Comment by imhoffd** [comment]
What react-scripts version are you using? This could be a duplicate of https://github.com/ionic-team/ionic-cli/issues/4392

**Comment by dstN** [comment]
> What react-scripts version are you using? This could be a duplicate of #4392

This did the trick. Thank you! 

But I got some audit fixes open now because of vulnerabilities
