### ISSUE TITLE
ionic serve --ssl does not take effect for react based projects

### ISSUE THREAD

**Issue by dellagustin** [ionic-team/ionic-cli#4569]
**Description:**
I have created a react based ionic project.
Serving it with the option --ssl does not take any effect, the website is served and opened still with http, not with https.

**Steps to Reproduce:**

Create a react based ionic project, serve it with `ionic serve --ssl`

**Output:**

Not applicable

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 6.11.1 (C:\Users\guilh\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.3.1

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Other Information:**

A workaround is to serve the site with `HTTPS=true npm start`, which will run react-scripts start with https. See https://create-react-app.dev/docs/using-https-in-development/.

Here is how to create a self signed certificate in case you need to access it from an address that is not localhost (i.e. serve on your PC, access from your mobile through the PC's IP): https://stackoverflow.com/a/10176685/4274827

**Comment by imhoffd** [comment]
I'm guessing you saw the `--ssl` option on the [online documentation](https://ionicframework.com/docs/cli/commands/serve), but the online documentation is for Angular, not React. We're still working on that.

Use `ionic serve --help` for Ionic CLI documentation for React projects. You're looking for this: `ionic serve --https`.

**Comment by dellagustin** [comment]
thanks, that worked
