### ISSUE TITLE
bug: ionic cli does not leverage package json scripts

### ISSUE THREAD

**Issue by raveenakothapally** [ionic-team/ionic-cli#4630]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
It is quite common to rewire create react app to adjust webpack or babel configurations. For example, I want to use `tailwindcss` or `@emotion/react`. Take a look at the package.json changes mentioned here ~ [link](https://tailwindcss.com/docs/guides/create-react-app).

**Expected behavior:**
`ionic serve` or `ionic capacitor build` does not leverage `start`, `build` scripts inside `package.json` and thereby none of what we rewired takes into effect.

**Steps to reproduce:**
```
ionic start new-app
```
Follow instructions in [link](https://tailwindcss.com/docs/guides/create-react-app) in order to onboard `tailwindcss`.

```
ionic serve
```

**Comment by m-apsolon** [comment]
any possible workaround solutions for this?

**Comment by raveenakothapally** [comment]
@m-apsolon I just realized that overriding `ionic:build` and `ionic:serve` achieves what we want:
```
    "start": "craco start",
    "build": "craco build",
    "ionic:build": "craco build",
    "ionic:serve": "craco start",
```

**Comment by jcesarmobile** [comment]
Yeah, that’s the way of overriding ionic commands
https://ionicframework.com/docs/cli/configuration#overriding-the-build
