### ISSUE TITLE
Creating a React project fails with npm 7

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/ionic-cli#4637]
**Description:**

npm 7 became [generally available](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) the other day and it handles peer dependencies more strictly.

As a result creating an Ionic React project with the CLI fails due to incompatible dependency versions between `react-scripts` and `typescript`.

**Steps to Reproduce:**

Upgrade to the latest `npm` version:

```
npm install -g npm
```

then try creating an Ionic React project:

```
ionic start my-app blank --type=react
```

**Output:**

The command fails with

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@0.0.1
npm ERR! Found: typescript@4.1.3
npm ERR! node_modules/typescript
npm ERR!   typescript@"^4.1.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"4.0.1" from the root project
```

That's because `react-scripts` v4.0.1 expects a `typescript` 3.x version, not 4.x:

```
% npm view react-scripts@4.0.1 peerDependencies
{ typescript: '^3.2.1' }
```

**My `ionic info`:**

```
% ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.
Ionic:
   Ionic CLI : 6.12.4
Utility:
   cordova-res : not installed
   native-run  : not installed
System:
   NodeJS : v14.15.4
   npm    : 7.5.2
   OS     : macOS Big Sur
```

**Other Information:**

A simple fix would be changing the `react-scripts` version to `4.0.2` in the [starter projects](https://github.com/ionic-team/starters/blob/master/react/base/package.json), because that version accepts `typescript` 4.x as well.

```
% npm view react-scripts@4.0.2 peerDependencies
{ react: '>= 16', typescript: '^3.2.1 || ^4' }
```

**Comment by jcesarmobile** [comment]
We were aware of the problem, but were waiting for the 4.0.2 release
Updated the starters
https://github.com/ionic-team/starters/pull/1666

**Comment by jcesarmobile** [comment]
The PR is merged and the template changes deployed, I no longer get the error on react app creation.
