### ISSUE TITLE
Start Page at 'www/index.html' was not found. In Ionic 5 xcode build

### ISSUE THREAD

**Issue by ivizzz** [ionic-team/ionic-cli#4655]
hi, my project runs on local browser fine but when i take build using xcode to my device it shows me an error that ,
[CDVTimer][TotalPluginStartup] 6.482959ms
2021-03-14 18:06:51.520272+0530 MyApp[3203:1048154] ERROR: Start Page at 'www/index.html' was not found.
2021-03-14 18:06:51.599734+0530 MyApp[3203:1048154] WF: === Starting WebFilter logging for process MyApp.

and my  ionic info is:
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.2.2

System:

   Android SDK Tools : 26.1.1 (/Users/ivinantony/Library/Android/sdk)
   ios-deploy        : 1.11.2
   ios-sim           : 8.0.2
   NodeJS            : v14.15.4 (/usr/local/bin/node)
   npm               : 6.14.10
   OS                : macOS Big Sur
   Xcode             : Xcode 12.4 Build version 12D4e

<img width="903" alt="Screenshot 2021-03-14 at 6 12 50 PM" src="https://user-images.githubusercontent.com/68975980/111068988-f6a5a380-84f0-11eb-97fa-7cb107d5cfb0.png">

**Comment by jarridlima** [comment]
@ivizzz How did you solve it?
