### ISSUE TITLE
Ionic cordova resources, got 410

### ISSUE THREAD

**Issue by gAllegr** [ionic-team/ionic-cli#4686]
**Description:**

I'm trying to regenerate splash screens, but I see the following in my console:

````
$ ionic cordova resources --splash --force    
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
| Uploading source images to prepare for transformations
Request: POST https://res.ionic.io/api/v1/upload
Response: 410
Body:
| Uploading source images to prepare for transformations
````

**Steps to Reproduce:**

Launch `ionic login`, then `ionic cordova resource --splash --force

**Output:**

Wrote at the start of the issue.

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.13.10
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 10.0.0
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\g.allegretta\AppData\Local\Android\Sdk)
   NodeJS            : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.13.4
   OS                : Windows 10
```

**Other Information:**

I found similar issues, [this](https://github.com/ionic-team/ionic-cli/issues/3719) and [this one](https://github.com/ionic-team/ionic-cli/issues/3259).

In the latter, the suggestion was to execute `ionic config set -g backend pro`, should I use it? What happens when launching it? I couldn't find any reference about that.

**Comment by jcesarmobile** [comment]
The resources Sever was sunset long long ago, it was replaced by a local alternative, but you are using a ver old CLI.
Also ionic CLI package was replaced by @ionic/cli.

Run
```
npm uninstall -g ionic
npm install -g @ionic/cli
```
