### ISSUE TITLE
error: unknown option '--npm-client' while integrating with Capacitor

### ISSUE THREAD

**Issue by BossR8** [ionic-team/ionic-cli#4702]
I have installed all the necessary libraries, created an application, and ran it successfully with the 'ionic server'. 
But while calling 'ionic capacitor add android' for mobile application, I encountered as follows:
error: unknown option'--npm-client'
Calling the 'ionic integrations enable capacitor' also gives the same error.

**Steps to Reproduce:**
npm install -g ionic
npm install --save @capacitor/core @capacitor/cli
ionic start appname
cd appname
ionic build (or ng build)
ionic capacitor add android --> error: unknown option'--npm-client'

My ionic info is as follows: 

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.1
   npm    : 6.14.12
   OS     : Windows 10

It worked fine on the same machine several days ago. I also tested another system, but the result was the same.
What has changed in the Ionic templates over the next few days?

**Comment by jcesarmobile** [comment]
please, uninstall ionic, it was renamed to @ionic/cli long ago

```
npm uninstall -g ionic
npm install -g @ionic/cli
```
latest version is 6.16.1, it should work with Capacitor 3
