### ISSUE TITLE
Ionic Lab is not working from different serving machine. (browser)

### ISSUE THREAD

**Issue by phyr0s** [ionic-team/ionic-cli#4705]
**Description:**
It is not possible to do an external serve lab. If you turn on the server in one machine with ionic serve --lab and want to see that application running in other browser machine connecting to that ip is not working. (Only happen with lab)

**Steps to Reproduce:**
Just run 
`ionic serve  --external --lab --lab-host='hostIp' --host='hostip' --public-host='hostip'`

**Output:**
Open browser OK in the machine that do the ionic serve normal and lab 8100 and 8200 port (default ports)

Connecting to different machine to that server 
http://hostIp:8100/#/  is working fine
http://hostIp:8200/#/  is not working

I attach one screenshot what happen with lab

--> https://ibb.co/dpQr9Y8

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.16.1 
   Ionic Framework               : @ionic/angular 5.6.6
   @angular-devkit/build-angular : 0.1102.12
   @angular-devkit/schematics    : 11.2.5
   @angular/cli                  : 11.2.5
   @ionic/angular-toolkit        : 3.1.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 23 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v14.15.4
   npm               : 6.14.10
   OS                : macOS Big Sur
   Xcode             : Xcode 12.5 Build version 12E262```

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.
