### ISSUE TITLE
bug: header changing style and tabs become scaled when serving via labs

### ISSUE THREAD

**Issue by dtaalbers** [ionic-team/ionic-cli#4707]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When I generate a fresh ionic app setup (angular), the styling of the header gets all messed up after refreshing the page whilst running the app in ionic labs. When I run the app on an iOS emulator device, the header is also without the proper styling (event turns grey at one point). See the below image and video. I have this problems in all the browsers (Chrome, Safari, Firefox and Edge).

EDIT: I just noticed it also messes with the styling of the tab bar. It's harder to see, but the icons and text increase in size (or the tab bar has less padding) when the page is refreshed.

**Expected behavior:**

The header remaining the same after a refresh.

**Steps to reproduce:**
1) Generate a  new angular tabs project.
2) Install `@ionic/lab` and serve via `ionic serve --lab`.
3) Refresh the page and start changing the tabs.

**Related code:**

```
N/A
```

**Other information:**

Note the header and tab bar on the iOS device.

https://user-images.githubusercontent.com/6512556/119985127-8b814e80-bfc2-11eb-8fbf-0c9887c01e48.mov

When deploying the app to a iOS emulator device, the styling is also messed up.

![image](https://user-images.githubusercontent.com/6512556/119983447-760b2500-bfc0-11eb-9adf-a3432e4365f9.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.14.1 (/Users/myname/.nvm/versions/node/v15.12.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.8
   @angular-devkit/build-angular : 12.0.2
   @angular-devkit/schematics    : 12.0.2
   @angular/cli                  : 12.0.2
   @ionic/angular-toolkit        : 4.0.0

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v15.12.0 (/Users/myname/.nvm/versions/node/v15.12.0/bin/node)
   npm    : 7.6.3
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.
