### ISSUE TITLE
Allow base-href to be set in build commands

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-cli#4737]
We are deploying a web version of our app for each branch that has been opened to provide better testing in each case. At the moment we using regex to replace the base href in each index.html to the proper server route.

If it would be possible to use `--base-href='./'` with `ionic build` it would be much more integrated.

There has been a thread about it already here but neither of those mentioned solutions worked for us: https://github.com/ionic-team/ionic-cli/issues/3600

We are building with cordova but recently trying new steps:

```
ionic build --engine cordova --platform windows --prod --base-href='./'
```

Or maybe add it cordova command itself:

```
ionic cordova build windows --no-build --prod --release --base-href='./' -- --arch=\"x86 x64 arm\"
```

**Comment by jcesarmobile** [comment]
`ionic build -- --base-href="./"` worked fine for me, the extra `--` means that anything after that is passed to the command that `ionic build` runs (which is `ng build` for angular apps). 
So doing `ionic build -- --base-href="./"` and `ng build --base-href="./"` are the same.
