### ISSUE TITLE
Ionic 4+ android build error: package android.support.annotation does not exist; import android.support.annotation.RequiresApi;

### ISSUE THREAD

**Issue by bhargavas12** [ionic-team/ionic-cli#4753]
Ionic 4+ app fails to build after adding the firebasex package

Steps to Reproduce:
Step 1: Create a latest blank ionic project
Step 2: Added the firebasex package onto the Ionic 4+ project

       ionic cordova plugin add cordova-plugin-firebasex
       npm install @ionic-native/firebase-x

Step 3: Generate google-services.json from firebase project and add to the project folder
Step 4: Add android platform and build for android
**Error received: Getting the following error when build for android**

C:\user\test\mobile\platforms\android\app\src\main\java\com\ionicframework\cordova\webview\IonicWebViewEngine.java:11: error: package android.support.annotation does not exist
import android.support.annotation.RequiresApi;
                                 ^

C:\user\test\mobile\platforms\android\app\src\main\java\com\ionicframework\cordova\webview\IonicWebViewEngine.java:121: error: cannot find symbol
    @RequiresApi(Build.VERSION_CODES.LOLLIPOP)
     ^
  symbol:   class RequiresApi
  location: class IonicWebViewEngine.ServerClient

**Configuration**

cordova-Android: 10.1.0

**gradle.properties contains the below:**

org.gradle.jvmargs=-Xmx2048m
android.useAndroidX=true
android.enableJetifier=true

**Added the below line in config.xml**
        <preference name="AndroidXEnabled" value="true" />

checked the issue already on https://github.com/ionic-team/ionic-cli/issues/4562 but it isnt working

Thanks,
Bhargav

**Comment by bhargavas12** [comment]
@gireeshspr / @andmar8 How did the issue got resolve? could you please tell me?

**Comment by jcesarmobile** [comment]
update cordova-plugin-ionic-webview to latest version, latest version doesn't use RequiresApi anymore
