### ISSUE TITLE
New project setup fails

### ISSUE THREAD

**Issue by jbburf** [ionic-team/ionic-cli#4771]
Hi, I'm trying to setup a new project but when I go through the process with:

1.  ```ionic start```
2. Select "No" to not use the app creation wizard
3. Select React
4. Select ```conference```

It fails during the ```npm i``` phase. I've tried going back and building with a different template option and have confirmed that the ```tabs``` template works.

System info:
Ionic v6.17.1
Node v16.9.1
NPM v7.23
System: MacOS 11.6 on Arm64 (Apple Silicon)

**Comment by jcesarmobile** [comment]
I can't reproduce at the moment.
Since you are using npm 7 it was probably a peer dependency problem on some dependency of the template that has been fixed since you reported the issue.
