### ISSUE TITLE
@ionic/cli uses deprecated version of formidable

### ISSUE THREAD

**Issue by bpred754** [ionic-team/ionic-cli#4782]
**Description:**
When installing @ionic/cli globally with `npm install @ionic/cli@6.18.0 -g`, it generates the following warning and writes to Standard Error:

```
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
```

This is causing our build system to fail. In the meantime, we are turning off `failOnStderr`, but this is not ideal.

**Comment by jcesarmobile** [comment]
this is a problem in one of the cli dependencies, we can't really do anything about it

https://github.com/visionmedia/superagent/issues/1609

**Comment by piotr-cz** [comment]
> this is a problem in one of the cli dependencies, we can't really do anything about it
> 
> [visionmedia/superagent#1609](https://github.com/visionmedia/superagent/issues/1609)

Apparently this dependency has been updated in supergent@7
