### ISSUE TITLE
vite support

### ISSUE THREAD

**Issue by reslear** [ionic-team/ionic-cli#4783]
add support `vite` builder with vue for live reloading, or how to use solution temporally ?

**Comment by reslear** [comment]
@jcesarmobile
@aperron @mhartington
@smzelek

**Comment by jcesarmobile** [comment]
Please, don’t do that

**Comment by reslear** [comment]
any news?

**Comment by reslear** [comment]
any news about support vite?

**Comment by mhartington** [comment]
We will update the issue when we have something. Please refrain from asking for updates.

**Comment by kuka-radovan** [comment]
Please, let us at least know if support of Vite is being considered or not.

**Comment by piotr-cz** [comment]
Integration with Vite requires tweaks to config files:

*capacitor.config.ts*

```ts
const config: CapacitorConfig = {
  webDir: 'dist',
}
```

*ionic.config.json*

```json
{
  "type": "custom"
}
```

*package.json*

```json
{
  "scripts": {
    "ionic:serve": "vite",
    "ionic:build": "tsc && vite build"
  }
}
```

Now both `ionic build` and `ionic serve` commands work properly

References:
- [New Capacitor Templates: SolidJS + Vite](https://ionic.io/blog/new-capacitor-templates-solidjs-vite)
- [Getting Started with ViteJS, Ionic Framework Beta v6 And VueJS](https://dev.to/aaronksaunders/getting-started-with-vitejs-ionic-framework-beta-v6-and-vuejs-2o8l)

**Comment by reslear** [comment]
@piotr-cz but without native-run :)

**Comment by piotr-cz** [comment]
@reslear 
I must say I haven't tried it yet.

You do you use it?
The [docs mention it](https://ionicframework.com/docs/cli/commands/cordova-run) only in context of `ionic cordova run` command.

**Comment by reslear** [comment]
I used it, then I had to write my own sh script :)
https://capacitorjs.com/docs/guides/live-reload#using-with-framework-clis

this is just for convenience, ideally it should be out of the box

**Comment by mhartington** [comment]
Locking this for now. This is planned for, and we have some branches which includes the work for it. But it will be part of a major version, since it does change how the CLI works internally.

**Comment by jcesarmobile** [comment]
version 7.x of the CLI already supports vite for react and vue, and pretty sure angular also uses vite under the hood
