### ISSUE TITLE
The target entry-point "@ionic-native/in-app-browser" has missing dependencies:

### ISSUE THREAD

**Issue by yangjunfocus** [ionic-team/ionic-cli#4785]
**Description:**

when I enter CLI `ionic serve`,output following error.

] F:\App\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40
[ng]                 throw new Error("The target entry-point \"" + invalidTarget.entryPoint.name + "\" has missing dependencies:\n" +
[ng]                 ^
[ng] Error: The target entry-point "@ionic-native/in-app-browser" has missing dependencies:
[ng]  - @ionic-native/core
[ng]     at TargetedEntryPointFinder.findEntryPoints (F:\App\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
[ng]     at F:\App\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
[ng]     at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (F:\App\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
[ng]     at F:\App\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
[ng]     at SyncLocker.lock (F:\App\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
[ng]     at SingleProcessExecutorSync.execute (F:\UtApp\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
[ng]     at Object.mainNgcc (F:\App\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
[ng]     at Object.process (F:\App\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
[ng]     at NgccProcessor.processModule (F:\App\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:16)
[ng]     at F:\App\node_modules\@ngtools\webpack\src\ivy\host.js:146:18

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

**Comment by jcesarmobile** [comment]
@ionic-native plugins require @ionic-native/core to be installed and looks like you don't have it, install it and everything should work.

They are now called @awesome-cordova-plugins
https://github.com/danielsogl/awesome-cordova-plugins
