### ISSUE TITLE
A flag to not install platform packages when doing `add platform` or `update platform`

### ISSUE THREAD

**Issue by borasemiz** [ionic-team/ionic-cli#4786]
Hello. I am experiencing something rather annoying when I try to add a platform using ionic capacitor command line. When I execute either of these commands:

```
$ ionic capacitor add android
```
or
```
$ ionic capacitor update android
```

The `@capacitor/android` package is installed every time, with its `latest` version. It doesn't matter whether I have the package already in my `package.json` or in my `node_modules`. Is there any way not to install a platform dependency every time I run either of these commands? Preferably, these commands should try to load the platform package from the `node_modules`. If it finds it, it should use that package. It shouldn't mess with my dependency structure in my project.

At least, if it really needs to re-install these platform packages, it should use the version that is defined for it in the `package.json`, not install a version as it "pleases". Due to version mismatch, it might actually broke my other packages in my project.

Kind regards.

**Comment by kensodemann** [comment]
The easy way around this at this point is to do `npx cap add android` or `npx cap add ios`

That uses the Capacitor CLI direction without wrapping it with the Ionic CLI. It will not do the install of the package and will expected that you had already done it and as such will use whatever you currently have in the `package.json`.

However, the more important question I have is why you need to add the `ios` or `android` platforms with any degree of regularity. This goes against the general design of Capacitor where the `ios` and `android` platforms are source artifacts. You generate them once and put them under version control. You should never need to add the platforms to the project again. As such, whatever you are currently doing goes against the general design philosophy of Capacitor.
