### ISSUE TITLE
v6 CLI doesn't start/create v6 app/project

### ISSUE THREAD

**Issue by strarsis** [ionic-team/ionic-cli#4792]
**Description:**
The `6.x` release of `ionic` CLI `start` doesn't create a project/app that uses `ionic` `v6`, but rather it still uses `v5` instead.
Manually updating the dependencies to `v6` results in a blank page, as the boilerplate is not compatible/running with `ionic` `v6`.

**Steps to Reproduce:**
1. Install the (latest) `v6` release of the `ionic` CLI (`npm install -g @ionic/cli@6`)
2. Invoke the `ionic` CLI to start/create a new app/project.
3. (I selected react as underlying app framework).
Note that the newly created app/project still uses `ionic` `v5` instead of `v6` (see the generated `package.json`):
```json
    "@ionic/react": "^5.5.0",
    "@ionic/react-router": "^5.5.0",

    "ionicons": "^5.4.0",
````
Just manually updating these packages to `6.x` results in no build/watch or JavaScript console errors, 
but a blank page when loading in browser (react), as the generated boilerplate is incompatible with `ionic` `v6`.

**Output:**
(Not applicable)

**My `ionic info`:**
```
ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /home/build/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/build/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli/lib/index.js
       - /home/build/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli/index.js
       - /home/build/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /home/build/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/build/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli/lib/index.js
       - /home/build/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli/index.js
       - /home/build/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.18.1 (/home/build/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.9.2

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.17.6 (/home/build/.nvm/versions/node/v14.17.6/bin/node)
   npm    : 8.3.0
   OS     : Linux 5.10
```

## Additional information
The app builder (Ionic Dashboard) creates `v5` apps, too, and not `v6` apps either.

**Comment by jcesarmobile** [comment]
You were a bit early, the official launch of ionic 6 was today, shortly after you created the issue.
Templates are now updated
https://github.com/ionic-team/starters/pull/1705

**Comment by strarsis** [comment]
@jcesarmobile. After installing the latest `ionic` `cli` package, version `6` is used.
However, `ionicons` still uses version `5.4.0` in the generated `package.json` albeit ´6.0.0´ is available now on ´npm´,
shouldn't this be updated, too?

The TypeScript related packages also seem to need bumping as the build generates a warning that the versions may be incompatible:
````
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.4

Please only submit bug reports when using the officially supported version.
````

**Comment by jcesarmobile** [comment]
Sorry, I have no idea about that, you should probably report it on https://github.com/ionic-team/starters/issues
