### ISSUE TITLE
50 Vulnerabilities (2 Low, 43 moderate, 5 high)

### ISSUE THREAD

**Issue by manoharmohanta** [ionic-team/ionic-cli#4801]
**Description:**

I have new pc just now installed NodeJs and then installed ionic with below command
npm install -g @ionic/cli
Then I have created new project with below command
ionic start
selected Angular , cordova and selected tabs as theme. Then I have got below error
https://ibb.co/QCGqd2J
50 Vulnerabilities (2 Low, 43 moderate, 5 high)

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

**Comment by jcesarmobile** [comment]
getting 0 vulnerabilities now
