### ISSUE TITLE
ionic start fails when creating angular app

### ISSUE THREAD

**Issue by wernerva** [ionic-team/ionic-cli#4815]
**Description:**
The ionic start process errors out when I choose angular as the framework.

**Steps to Reproduce:**
Install Node 16.4 (current LTS) and select "Automatically install the necessary tools..."
run: npm i -g @ionic/cli
run: ionic start myApp blank --type=ionic-angular --capacitor

**Output:**
  For brevity I include only the error here. The full logs are attached
  3891 error code 1
3892 error path C:\apps\myApp\node_modules\node-sass
3893 error command failed
3894 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
3895 error Building: C:\Program Files\nodejs\node.exe C:\apps\myApp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
3896 error gyp info it worked if it ends with ok
3896 error gyp verb cli [
3896 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
3896 error gyp verb cli   'C:\\apps\\myApp\\node_modules\\node-gyp\\bin\\node-gyp.js',
3896 error gyp verb cli   'rebuild',
3896 error gyp verb cli   '--verbose',
3896 error gyp verb cli   '--libsass_ext=',
3896 error gyp verb cli   '--libsass_cflags=',
3896 error gyp verb cli   '--libsass_ldflags=',
3896 error gyp verb cli   '--libsass_library='
3896 error gyp verb cli ]
3896 error gyp info using node-gyp@3.8.0
3896 error gyp info using node@16.14.0 | win32 | x64
3896 error gyp verb command rebuild []
3896 error gyp verb command clean []
3896 error gyp verb clean removing "build" directory
3896 error gyp verb command configure []
3896 error gyp verb check python checking for Python executable "python2" in the PATH
3896 error gyp verb `which` failed Error: not found: python2
3896 error gyp verb `which` failed     at getNotFoundError (C:\apps\myApp\node_modules\which\which.js:13:12)
3896 error gyp verb `which` failed     at F (C:\apps\myApp\node_modules\which\which.js:68:19)
3896 error gyp verb `which` failed     at E (C:\apps\myApp\node_modules\which\which.js:80:29)
3896 error gyp verb `which` failed     at C:\apps\myApp\node_modules\which\which.js:89:16
3896 error gyp verb `which` failed     at C:\apps\myApp\node_modules\isexe\index.js:42:5
3896 error gyp verb `which` failed     at C:\apps\myApp\node_modules\isexe\windows.js:36:5
3896 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
3896 error gyp verb `which` failed  python2 Error: not found: python2
3896 error gyp verb `which` failed     at getNotFoundError (C:\apps\myApp\node_modules\which\which.js:13:12)
3896 error gyp verb `which` failed     at F (C:\apps\myApp\node_modules\which\which.js:68:19)
3896 error gyp verb `which` failed     at E (C:\apps\myApp\node_modules\which\which.js:80:29)
3896 error gyp verb `which` failed     at C:\apps\myApp\node_modules\which\which.js:89:16
3896 error gyp verb `which` failed     at C:\apps\myApp\node_modules\isexe\index.js:42:5
3896 error gyp verb `which` failed     at C:\apps\myApp\node_modules\isexe\windows.js:36:5
3896 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
3896 error gyp verb `which` failed   code: 'ENOENT'
3896 error gyp verb `which` failed }
3896 error gyp verb check python checking for Python executable "python" in the PATH
3896 error gyp verb `which` succeeded python C:\Python310\python.EXE
3896 error gyp ERR! configure error 
3896 error gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
3896 error gyp ERR! stack   File "<string>", line 1
3896 error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
3896 error gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3896 error gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
3896 error gyp ERR! stack 
3896 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:399:12)
3896 error gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
3896 error gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
3896 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
3896 error gyp ERR! System Windows_NT 10.0.19044
3896 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\apps\\myApp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
3896 error gyp ERR! cwd C:\apps\myApp\node_modules\node-sass
3896 error gyp ERR! node -v v16.14.0
3896 error gyp ERR! node-gyp -v v3.8.0
3896 error gyp ERR! not ok 
3896 error Build failed with error code: 1
3897 verbose exit 1
3898 timing npm Completed in 36862ms
3899 verbose unfinished npm timer reify 1645208828907
3900 verbose unfinished npm timer reify:build 1645208861825
3901 verbose unfinished npm timer build 1645208861826
3902 verbose unfinished npm timer build:deps 1645208861826
3903 verbose unfinished npm timer build:run:postinstall 1645208862651
3904 verbose unfinished npm timer build:run:postinstall:node_modules/node-sass 1645208862651
3905 verbose code 1

**My `ionic info`:**
Ionic:

   Ionic CLI          : 6.18.1 (C:\Users\Calian\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework    : not installed
   @ionic/app-scripts : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.1
   OS     : Windows 10
[2022-02-18T18_27_08_513Z-debug-0.log](https://github.com/ionic-team/ionic-cli/files/8099576/2022-02-18T18_27_08_513Z-debug-0.log)
[2022-02-18T18_27_46_079Z-debug-0.log](https://github.com/ionic-team/ionic-cli/files/8099583/2022-02-18T18_27_46_079Z-debug-0.log)

**Comment by jcesarmobile** [comment]
ionic-angular is very old, so if you want to work with it you have to use old versions of node/npm, according to this comment, using node 10 or 12 with npm 6 should work, but I tested on macOS, not on Windows
https://github.com/ionic-team/ionic-cli/issues/4901#issuecomment-1220600914
