### ISSUE TITLE
npm i -E @capacitor/ios@latest exited with exit code 1.

### ISSUE THREAD

**Issue by chengpengvb** [ionic-team/ionic-cli#4816]
The following is the error I get when I execute ios packaging:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/28288567/154875112-1d327a28-da9f-421c-8af8-6fc1dd0c1931.png">

View log file:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/28288567/154875356-ec79d8d4-8f7a-4a0a-805f-72dd9e7f5759.png">
It seems to be a version conflict problem, can anyone answer my question?

**Comment by jcesarmobile** [comment]
@capacitor/ios 3.4.x requires @capacitor/core 3.4.x, but you have 3.3.1, so you need to update @capacitor/core to latest first.
