### ISSUE TITLE
Can't finish update using ionic capacitor update ios

### ISSUE THREAD

**Issue by lulmichal** [ionic-team/ionic-cli#4828]
**Description:**
Hello Everyone,

I'm having issue with updating the project using CLI. When using `ionic capacitor update ios`, the update doesn't fulfil. The example is in attached screenshot . 

I don't have this issue when updating Android.

**Output:**

<img width="488" alt="Screenshot 2022-03-18 at 13 17 14" src="https://user-images.githubusercontent.com/77002919/159001571-005c8dbb-252f-4adc-a5ff-44614a0cc883.png">

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 5.4.16


   Ionic Framework : @ionic/react 4.11.13

Capacitor:

   Capacitor CLI   : 2.1.2
   @capacitor/core : 2.5.0

Utility:

   cordova-res : not installed
   native-run  : not installed


System:

   NodeJS : v14.18.0 (/Users/michallul/.nvm/versions/node/v14.18.0/bin/node)
   npm    : 6.14.16
   OS     : macOS Big Sur


```

If any additional info is needed I'd be happy to provide it but I don't work with Ionic on daily basis so I'm really sorry if something significant wasn't provided this time.

Best regards!

**Comment by jcesarmobile** [comment]
You are using the old CLI, it was deprecated years ago. Run

```
npm uninstall -g ionic
npm install -g @ionic/cli
```
