### ISSUE TITLE
@ionic/cli: Fixed 404 error for lab-logo.png

### ISSUE THREAD

**Issue by charliejlevine** [ionic-team/ionic-cli#4833]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@ionic/lab@3.2.11` for the project I'm working on.

Description: Fixed 404 error for lab-logo.png

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@ionic/lab/www/assets/app.css b/node_modules/@ionic/lab/www/assets/app.css
index 620a151..4774166 100644
--- a/node_modules/@ionic/lab/www/assets/app.css
+++ b/node_modules/@ionic/lab/www/assets/app.css
@@ -52,7 +52,7 @@ header .icon {
 #logo {
   display: inline-block;
   vertical-align: middle;
-  background: url('lab-logo.png');
+  background: url('assets/lab-logo.png');
   background-size: 100%;
   background-repeat: no-repeat;
   margin-top: -2px;
diff --git a/node_modules/@ionic/lab/www/index.html b/node_modules/@ionic/lab/www/index.html
index 2be9e0a..4a6bec4 100644
--- a/node_modules/@ionic/lab/www/index.html
+++ b/node_modules/@ionic/lab/www/index.html
@@ -92,7 +92,7 @@ header .icon {
 #logo {
   display: inline-block;
   vertical-align: middle;
-  background: url('lab-logo.png');
+  background: url('assets/lab-logo.png');
   background-size: 100%;
   background-repeat: no-repeat;
   margin-top: -2px;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.
