### ISSUE TITLE
Ionic capacitor copy runs build command

### ISSUE THREAD

**Issue by jsBiztech** [ionic-team/ionic-cli#4855]
**Description:**

In ionic 6 CLI, the ionic capacitor copy ios run the `ionic build` command by default.
This was not happening on Ionic 5/4.

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.19.1 
   Ionic Framework               : @ionic/angular 6.1.6
   @angular-devkit/build-angular : 12.2.17
   @angular-devkit/schematics    : 12.2.17
   @angular/cli                  : 12.2.17
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI      : 2.4.4
   @capacitor/android : 2.4.5
   @capacitor/core    : 2.4.4
   @capacitor/ios     : 2.4.5

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v14.17.5 
   npm               : 6.14.14
   OS                : macOS Monterey
   Xcode             : Xcode 13.3 Build version 13E113
```

**Comment by jcesarmobile** [comment]
I think you are confusing the @ionic/cli version with the @ionic/angular version.
@ionic/cli 4/5 didn't have capacitor support, @ionic/cli 6 has always run build with ionic cap copy command.
Changing your @ionic/angular version to 4, 5 or 6 should have no effect on the command building first.
If you don't want to do the build you can use `npx cap copy` command or use the `--no-build` parameter `ionic cap copy --no-build`
