### ISSUE TITLE
gulpfile.s not found- ionic 3,4+

### ISSUE THREAD

**Issue by anupama58** [ionic-team/ionic-cli#4874]
**Description:**
I am trying to create a wrapper for a custom plugin, so for the same i have used the below command
gulp plugin:create -n "helloWorld".
But this command rans into error saying : "no gulp file found".
Even after installing gulp-cli globally as well as installing gulp too.

**Steps to Reproduce:**
npm install
gulp plugin:create -n PluginName

**Note: Have previously created a plugin using plugman tool and have placed it on github.

**Output:**
Simply returns an error stating : no gulp file found 
![Screenshot 2022-06-10 at 11 22 26 AM](https://user-images.githubusercontent.com/88892656/173003120-8b175d1e-843b-4047-93ff-340769229069.png)

**My `ionic info`:**

```
ionic 6 -Ionic Info:
Ionic:
   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.1.9
   @angular-devkit/build-angular : 14.0.1
   @angular-devkit/schematics    : 14.0.1
   @angular/cli                  : 14.0.1
   @ionic/angular-toolkit        : 6.1.0
Cordova:
   Cordova CLI       : 11.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (1 plugins total)
Utility:
   cordova-res : 0.15.4
   native-run  : 1.6.0
System:
   ios-deploy : 1.11.4
   NodeJS     : v14.17.3 (/usr/local/bin/node)
   npm        : 6.14.13
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146

ionic 3 -Ionic Info:
Ionic:
   Ionic CLI          : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4
Cordova:
   Cordova CLI       : 11.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (1 plugins total)
Utility:
   cordova-res : 0.15.4
   native-run  : 1.6.0
System:
   ios-deploy : 1.11.4
   NodeJS     : v14.17.3 (/usr/local/bin/node)
   npm        : 6.14.13
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146
```

**Other Information:**
Referred this below blog to create plugin and its wrapper:
https://medium.com/@durgavundavalli/ionic5-cordova-custom-plugin-for-objective-c-e4e82c5fbc3b

**Comment by jcesarmobile** [comment]
Sorry, I don't see how this could be related to Ionic CLI.
Also the blog post you linked doesn't use gulp, so it's not clear what are you trying to do.

**Comment by anupama58** [comment]
Can you check this below link:
https://medium.com/@durgavundavalli/cordova-create-a-native-wrapper-with-ionic-native-d88fbc6742a2
i missed adding this link on the issue.

Short description, to explain what i want to achieve.
I am trying to create a custom plugin for ionic, and create a wrapper for the same so that i can use it in ionic applications.

**Comment by jcesarmobile** [comment]
You have to clone ionic-native repository, run npm install on the root and then run the gulp command in the root too.

ionic-native was renamed to awesome-cordova-plugins, the new repository is here https://github.com/danielsogl/awesome-cordova-plugins.

If you are finding any issues you should report it there.
