### ISSUE TITLE
bug: Error: Unknown argument: platform [ERROR] An error occurred while running subprocess ng.

### ISSUE THREAD

**Issue by emilkitua** [ionic-team/ionic-cli#4875]
**Description:**
Whenever I am compiling an Ionic app for android devices I am getting an error:
Error: Unknown argument: platform [ERROR] An error occurred while running subprocess ng.
![image](https://user-images.githubusercontent.com/10283136/173437005-835b750d-6d8b-42a1-9a41-b54908aa9151.png)

**Expected Behavior**
I expected the app to build to the desired platform

**Steps to Reproduce:**
Current Ionic version is 5.4.16
Angular CLI version: 14.0.1
Node: 16.14.2

run `ionic cordova platform build android`

**Output:**
```
> ng.cmd run app:ionic-cordova-build --platform=android
Error: Unknown argument: platform
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

**My `ionic info`:**
Ionic:
Ionic CLI: 5.4.16 (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 6.1.9
@angular-devkit/build-angular : 14.0.1
@angular-devkit/schematics : 14.0.1
@angular/cli : 14.0.1
@ionic/angular-toolkit : 6.1.0
Cordova:
Cordova CLI : 11.0.0
Cordova Platforms : android 10.1.2
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 4 other plugins)
Utility:
cordova-res : 0.15.4
native-run : 1.5.0
System:
Android SDK Tools : 26.1.1 (C:\Users\Lenovo\AppData\Local\Android\Sdk)
NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
npm : 8.5.0
OS : Windows 10

**Comment by jcesarmobile** [comment]
Looks like you are still using the old deprecated ionic package. It was renamed to `@ionic/cli` long ago.
Latest release of @ionic/cli is 6.20.0.

Remove ionic package and install @ionic/cli 
```
npm -g uninstall ionic
npm -g install @ionic/cli 
```
