### ISSUE TITLE
"ionic serve" command does not work in Windows environment 

### ISSUE THREAD

**Issue by festusmwambu** [ionic-team/ionic-cli#4883]
- I am having an error running the simple command of **ionic serve** natively in Windows using Git Bash. This is the error I get:

$ ionic serve
> ng.cmd run app:serve --host=localhost --port=8100
[ng] Error: Schema validation failed with the following errors:
[ng]   Data path "" must NOT have additional properties(es5BrowserSupport).

[ERROR] ng has unexpectedly closed (exit code 1).

        The Ionic CLI will exit. Please check any output above for error details.

- This is the solution that I found and I thought it was good to share:
On *angular.json* file if you have an empty "scripts": [] and "es5BrowserSupport": true , just remove it ! and then run _ionic serve_

```
 "build": {
      "options": {
       ...,
        "scripts": [],                <-- Remove this line
        "es5BrowserSupport": true     <-- Remove this line
       ...

**Comment by jcesarmobile** [comment]
There isn't enough information to reproduce, but `"es5BrowserSupport": true` was removed long ago from the templates when they added angular 8 support 

https://github.com/ionic-team/starters/commit/ed5c44ee837671642a7a40a2613db09dd688a779

`"scripts": []` is still there, so you shouldn't need to remove it
