### ISSUE TITLE
installing so old angular and ionic versions

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic-cli#4893]
**Description:**

when i tried ionic start appName tabs --type=ionic-angular and ionic start appName tabs --type=ionic-angular it installed angular 5.2.11 and ionic 3.9.9

**Steps to Reproduce:**

ionic start appName tabs --type=ionic-angular or ionic start appName tabs --type=ionic-angular in cmd

**Output:**

**My `ionic info`:**

```
Ionic:

   Ionic CLI : 6.20.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.20.0
   npm    : 8.15.0
   OS     : Linux 5.4

```

**Other Information:**

**Comment by jcesarmobile** [comment]
type ionic-angular uses Ionic 3
Ionic 4+ supports multiple frameworks, so there are several packages, such as @ionic/core, @ionic/angular, @ionic/react, @ionic/vue.
Use type angular if you want latest angular packages with latest @ionic/angular
