### ISSUE TITLE
Unable to create ionic 3 project with ionic 6 cli

### ISSUE THREAD

**Issue by wasimbakali** [ionic-team/ionic-cli#4901]
**Description:**
I have old ionic 3 project which i want into in my machine but its not working here i am creating simple ionic 3 project using below command

`ionic start Ionic3Project blank --type=ionic-angular`

It throws lot of error

![](https://i.stack.imgur.com/EmZMy.jpg)

**Steps to Reproduce:**

Create or clone ionic 3 demo project with ionic-cli : 6.x.x

**Output:**

**My `ionic info`:**

```
Ionic:

   Ionic CLI : 6.19.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.14.2
   npm    : 8.5.0
   OS     : macOS Monterey

```

**Other Information:**

**Comment by jcesarmobile** [comment]
You are trying to install ancient dependencies in latest node/npm, that's not going to work.
I've tried with node 10/12 and npm 6 and it works fine, try downgrading them or use some node manager such as nvm so you can easily switch between versions when needed.

**Comment by wasimbakali** [comment]
Yeah! I installed NVM and It worked with node 12. Thanks!
