### ISSUE TITLE
[ERROR] ng has unexpectedly closed (exit code 127).

### ISSUE THREAD

**Issue by engalaqrabi** [ionic-team/ionic-cli#4910]
Hello , i have a problem maybe you help me to solve it ,i am new in ionic so when i follow the instructions of opening new ionic cordova  
ı saw this error .How can ı solve this thing i try every thing on internet for 2 days and nothing help so maybe iam doing some thing wrong

Soo@DELL-LATITUDE MINGW64 ~/gomart-ui
$ ionic build
> ng.cmd run app:build
Unknown error: SyntaxError: Invalid or unexpected token
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build exited with exit code 127.

        Re-running this command with the --verbose flag may provide more informa

**Comment by Jbranadev** [comment]
Lograste solucionar el problema?

Estoy teniendo un problema similar
