### ISSUE TITLE
Capacitor run android not working in 6.20.2

### ISSUE THREAD

**Issue by ipanamski** [ionic-team/ionic-cli#4912]
**Description:**

After upgrading to 6.20.2 from 6.20.1, the command "ionic capacitor run android" stopped working. Does not show devices, just quits.
Running "npx cap run android" works as expected.
Downgrading to 6.20.1 solves the problem

**Steps to Reproduce:**

Upgrade to 6.20.2 and run "ionic capacitor run android"

**Comment by ken2k** [comment]
I can confirm this is broken. Currently the following command

`ionic cap build android
`

just returns immediately without doing anything nor displaying any error message. All of our build pipelines were broken since yesterday because of this.

Solution:
Back to the previous version. In our build pipelines, now we're using

`npm install -g @ionic/cli@6.20.1
`

instead of 

`npm install -g @ionic/cli`

**Comment by xyboox** [comment]
Actually, it seems like `ionic cap *` is broken.

**Comment by IT-MikeS** [comment]
@ipanamski Could we get some more information on your environment?

- OS? 
- Node/NPM version?
- Output with `verbose` flag

**Comment by ipanamski** [comment]
> @ipanamski Could we get some more information on your environment?
> 
> * OS?
> * Node/NPM version?

- Os - Fedora Linux 37
- Node - v18.9.0
- NPM - 8.19.2

Running the command
`ionic cap run android --verbose`
Outputs
`ionic:lib Terminal info: { ci: false, shell: '/bin/bash', tty: true, windows: false } +0ms`
`ionic:lib CLI global options: { _: [ 'cap', 'run', 'android' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +2ms`
`ionic:lib:project Project type from config: @ionic/vue (vue) +0ms`
`ionic:lib:project Project details: { context: 'app', type: 'vue', errors: [], configPath: '/home/ivailo/Documents/vortex-app/ionic.config.json' } +0ms`
`ionic Context: { binPath: '/usr/local/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/usr/local/lib/node_modules/@ionic/cli', execPath: '/home/ivailo/Documents/vortex-app', version: '6.20.2' } +0ms`
`ionic:lib:integrations:capacitor Getting config with Capacitor CLI: [ 'config', '--json' ] +0ms`

**Comment by xyboox** [comment]
Issue manifests itself also on Macos:

```
 NodeJS : v14.20.0 (/opt/homebrew/Cellar/node@14/14.20.0/bin/node)
   npm    : 6.14.17
   OS     : macOS Monterey
```

**Comment by Lucas-knut** [comment]
I can confirm too.
There is not only `ionic cap *` but also `ionic info`, surely other commands too

Os - macOS Monterey - 12.6
Node - v16.17.1
NPM - 8.15.0

Running the command
`ionic info --verbose`

Outputs
```
  ionic:lib Terminal info: { ci: false, shell: '/bin/zsh', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'info' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +3ms
  ionic:lib:project Project type from config: @ionic/react (react) +0ms
  ionic:lib:project Project details: { context: 'app', type: 'react', errors: [], configPath: '/Users/lucassteichen/Documents/dev/janvier/opadd-app-v2/ionic.config.json' } +0ms
  ionic Context: { binPath: '/Users/lucassteichen/.nvm/versions/node/v16.17.1/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/Users/lucassteichen/.nvm/versions/node/v16.17.1/lib/node_modules/@ionic/cli', execPath: '/Users/lucassteichen/Documents/dev/janvier/opadd-app-v2', version: '6.20.2' } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic info' [ '--verbose', '--interactive', '--color' ] +0ms
  ionic:lib:integrations:capacitor Getting config with Capacitor CLI: [ 'config', '--json' ] +0ms
```

**Comment by felixqueisler** [comment]
Also for us 6.20.2 broke `ionic cap *` except `ionic cap update`. Both iOS and Android.
macOS 12.6 on M1 Pro MacBooks.
I switched between multiple node versions from 16.17.1 to a 18.10.0 and it didn't have a noticeable effect.

For the affected: You can rollback with `npm i -g @ionic/cli@6.20.1`

**Comment by IT-MikeS** [comment]
Issue has identified and is being worked on

**Comment by IT-MikeS** [comment]
Please give [6.20.3-testing.0](https://www.npmjs.com/package/@ionic/cli/v/6.20.3-testing.0) a shot if you like to test the fix before its publish

**Comment by felixqueisler** [comment]
[6.20.3-testing.0](https://www.npmjs.com/package/@ionic/cli/v/6.20.3-testing.0) seems to be working. 👍

**Comment by xyboox** [comment]
I can confirm also on my side. While we're here, any chance for a `--inline` flag addition for the cap copy/sync ? ( like `npx cap copy --inline` does ). Would help big time for debugging. Thanks!

**Comment by IT-MikeS** [comment]
@xyboox I can't guarantee it but I will look into it

**Comment by studentrk** [comment]
You also have to have node version v16.14.2. With node version v17.7.2 or v18.10.0, the error also occurs with ionic/cli version 6.20.1

**Comment by servusdei2018** [comment]
I am having this issue as well. After upgrading to ionic-cli 6.20.2, `ionic cap copy ios` returns without error immediately, and so does `ionic cap open ios`. Neither works as expected.

**However,** `npx cap copy ios` and `npx cap open ios` seem to work fine, and is the workaround I am using in the meantime.

```shell
$ uname -a
Darwin MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64
$ npm --version
6.20.2
$ node --version
v16.16.0
$ ionic --version
6.20.2
$ npx cap -V
4.0.1
```

**Comment by jcesarmobile** [comment]
version 6.20.3 has been released reverting the commit that caused this issue, should be working now.
