### ISSUE TITLE
Capacitor commands fail silently when getting the capacitor config fails

### ISSUE THREAD

**Issue by jsw800** [ionic-team/ionic-cli#4917]
**Description:**

I upgraded from capacitor 3 to 4 recently and suddenly all the `ionic capacitor <...>` commands were failing silently - even with the verbose flag, I got no error message, the process just exited silently after this debug message:

```
Getting config with Capacitor CLI: ['config', '--json']
```

**Steps to Reproduce:**

I tracked down the issue to needing the capacitor CLI installed globally in order for this child process Promise to resolve correctly: https://github.com/ionic-team/ionic-cli/blob/faaf6c6a79f8c6394f40a5610fbcf5ae98b8344b/packages/%40ionic/cli/src/lib/integrations/capacitor/index.ts#L195

I did not have the capacitor CLI installed globally previously. Once installing it works correctly. The bug I am reporting is not that I need that installed, but rather the silent failure - it would have saved me hours if that error had been properly logged by the framework rather than ignored.

**Output:**

The output was the normal debug statements up to the one posted above: 

```
Getting config with Capacitor CLI: ['config', '--json']
```

Followed by nothing and the program exiting silently with exit code 0.

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 6.18.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.15

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : 4.3.0
   @capacitor/core    : 4.3.0
   @capacitor/ios     : 4.3.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v14.19.0 (/Users/jessew/.nvm/versions/node/v14.19.0/bin/node)
   npm    : 8.9.0
   OS     : macOS Monterey
```

I had this issue on an ubuntu CI runner and not my local MacBook - I think I may have had capacitor installed on my Mac although it's hard to check now. This ionic info was from my Mac ^

**Other Information:**

**Comment by jcesarmobile** [comment]
Capacitor shouldn't be installed globally, but there seem to be having problems finding the locally installed one in some cases.

We are already tracking the issue here https://github.com/ionic-team/ionic-cli/issues/4912, but it was supposed to only affect latest version (6.20.2), but you are in 6.18.2 according to your ionic info output. It's starting to look like a npm issue to me, it's not the first time a npm/node update breaks executing commands. Last time it was affecting homebrew installed node, but in your case you are using nvm.

**Comment by jsw800** [comment]
@jcesarmobile I believe I could have been on 6.20.2 in my CI environment where the issue was happening, because I install the ionic CLI globally into the fresh CI environment each time the CI build runs - in that case, I assume it is the same issue being tracked by #4912. I gave the ionic info from my local macbook which may not be as up to date as the CI environment is which is probably part of the confusion.

Thanks for your help, I will assume this is the same as #4912 and keep an eye on that issue.
