### ISSUE TITLE
White screen on android 5.0

### ISSUE THREAD

**Issue by GuoJieLun** [ionic-team/ionic-cli#4933]
**Description:**
please,help me!,when I build ionic tabs example for android apk . I put on my TV system(android 5.0+) and after installing and staring it ,it show a white screen . Is it incompatible with ionic 6?

**Steps to Reproduce:**

1、ionic start myApp tabs 
2、npm install 
3、ionic capacitor add android 
4、ionic capacitor build android 

**My `ionic info`:**

```
Ionic:

   Ionic CLI : 6.20.4

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v14.18.1
   npm    : 6.14.15
   OS     : macOS Monterey
```

**Other Information:**

**Comment by jcesarmobile** [comment]
Capacitor 4 supports Android 5.1+, not 5.0.

Also, it requires Chrome/System WebView 60+.

But, if you are using angular 15, it requires a way newer Chrome/WebView version than the required by Capacitor and causes those white screens if you are running in an older version than the supported one. Don't know which exact version they require, but it's something like last 2 Chrome versions.
