### ISSUE TITLE
Support creating standalone pages, components, directives, ...

### ISSUE THREAD

**Issue by arturober** [ionic-team/ionic-cli#4941]
**Description:**
Latest version of Ionic CLI creates projects with Angular 15 by default. In Angular 15, standalone components are considered stable now, but Ionic CLI doesn't support **--standalone** option when using ionic generate (this option also doesn't work with ng generate, I don't know why).

**Request:**
Add support for generating components, directives or pipes with **--standalone** option when using Angular 15+. Also, it would be very nice to be able to generate pages (`ionic generate page my-page --standalone`). They're simpler now, just the component with the template skeleton, and no need for a module, route, etc. I know I could create a component, and add the template manually, but this would be much faster.

In the future, when Angular CLI supports creating projects with _--standalone_ option (no AppModule), i'd love to have this possibility also with Ionic, so I don't need to delete manually the created modules and modify _main.ts_ file. But I guess that will have to wait a bit more.

**Comment by amjadyahya1** [comment]
+1

**Comment by Joep-DDQ** [comment]
seems that pages are created standalone by default now?

**Comment by ghost** [comment]
Hi there!

Any updates on this issue?

TIA

**Comment by amjadyahya1** [comment]
> Hi there!
> 
> Any updates on this issue?
> 
> TIA

It's fixed, use the latest CLI and it will create standalone pages for you

**Comment by ghost** [comment]
Thanks @amjadyahya1!

**Comment by arturober** [comment]
Solved
