### ISSUE TITLE
ERR: Your Node.js version is v14.21.3. Node.js 14 reached end-of-life on 2023-04-30 and is no longer supported. Please update to the latest Node LTS version.

### ISSUE THREAD

**Issue by fabriciovasc** [ionic-team/ionic-cli#4993]
**Description:**
After updating my cli to the latest version, I can't run commands in an old node version for ionic projects with node 14 or below

**Steps to Reproduce:**
- Update @ionic/cli to 7
- Run ```ionic <command>``` within a project with ionic that uses node 14

**Output:**
```shell
ERR: Your Node.js version is v14.21.3. Node.js 14 reached end-of-life on 2023-04-30 and is no longer supported. Please update to the latest Node LTS version.
```

**My `ionic info`:**
```shell
ERR: Your Node.js version is v14.21.3. Node.js 14 reached end-of-life on 2023-04-30 and is no longer supported. Please update to the latest Node LTS version.
```

**Other Information:**
If you downgrade the version to 6, the commands work again

**Comment by sean-perkins** [comment]
The minimum required version is Node 16: https://github.com/ionic-team/ionic-cli/pull/4972
