### ISSUE TITLE
Bad project type: ionic1

### ISSUE THREAD

**Issue by kadun** [ionic-team/ionic-cli#5000]
**Description:**
When trying to serve old (v1) ionic projects and error occour: Bad project type: ionic1

**Steps to Reproduce:**
ionic start myApp blank --type=ionic1
ionic serve

**Output:**
Bad project type: ionic1

**Other Information:**
When downgrade to ionic-cli@6 it works as always. The error only occours in this new version 7.

**Comment by maxfloden** [comment]
@kadun What version of ionic-cli@6 do you get this to work in? I have a possibly related error #5002 but cannot get it to work using cli 6 (ionic3 / Angular6 project)

**Comment by kadun** [comment]
@maxfloden I have to downgrade to ionic-cli@6.20.9 to get it working again. For me, the error only occours in ionic-cli@7+

**Comment by maxfloden** [comment]
> @maxfloden I have to downgrade to ionic-cli@6.20.9 to get it working again. For me, the error only occours in ionic-cli@7+

Thanks. It works for me too now with v6 (updated my issue with more info). 
Note that this is behaviour is as expected: from v7 release notes it is clear that Ionic v1 and v3 is no longer supported.

**Comment by kadun** [comment]
@maxfloden thanks for this info. I hadn't paid attention to this change in the documentation...
