### ISSUE TITLE
Ionic lab not working for ionic react projects

### ISSUE THREAD

**Issue by michaelnjuguna** [ionic-team/ionic-cli#5003]
**Description:**

Ionic lab Not working for ionic react projects

**Steps to Reproduce:**

After creating ionic react project
npm i -g  @ionic/lab
ionic serve --lab

**My `ionic info`:**

```
ionic v7
capacitor v4
node v18.16.0
```

**Comment by MDecker-MobileComputing** [comment]
Same for an Angular-based Ionic project. For `ionic serve --lab` just the ordinary browser preview (like for `ionic serve`) is shown.

Ionic CLI: 7.1.1
Ionic Framework: @ionic/angular 7.0
NodeJS: v18.16.0

**Comment by lassespilling** [comment]
Same issue here

**Comment by michaelnjuguna** [comment]
After running your app on say http://localhost:4200 using ionic serve and it is running properly.
Run ionic-lab http://localhost:4200 on a new terminal and your app will now work well with ionic lab
Step 1: ionic serve 
Step 2: ionic-lab <the port your app is running on>
