### ISSUE TITLE
ionic deploy add: error "unable to find command"

### ISSUE THREAD

**Issue by NLegendre** [ionic-team/ionic-cli#5008]
**Description:**
Hello,
I have a Capacitor project (with VueJS). I would like to use Appflow to live update my application.
I am following the documentation on Appflow website. The first step is to install the SDK with this command :

```
ionic deploy add  \
    --app-id="YOUR_APP_ID" \
    --channel-name="YOUR_CHANNEL_NAME" \
    --update-method="background|auto|none" \
```

When I run this command I have the error: `Unable to find command: deploy add`

**Steps to Reproduce:**
I have created a Vue project first, with Vite.
I have added Capacitor next.
Currently I manually compile the iOS and Android app, and publish it on the stores. It works well.
I then installed Ionic CLI to configure Appflow.
I launched `ionic init` in the project folder.
I tried to add @ionic/vue but it doesn't fix the error.

**My `ionic info`:**
```
Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.0.5

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v16.17.0 (/usr/local/bin/node)
   npm    : 8.15.0
   OS     : macOS Monterey
```

Thank you for your help :)

**Comment by ShaneK** [comment]
The `ionic deploy` commands were renamed `ionic live-update` in CLI v7:
https://ionicframework.com/docs/cli/commands/live-update-add

We still need to update our documentation around this, sorry about that.

**Comment by NLegendre** [comment]
Hello,
Ok, thank you for your answer!
When I run the command `ionic live-update add` I have this error:
```
[ERROR] It looks like your app isn't integrated with Capacitor or Cordova.

        In order to use the Ionic Live Updates plugin, you will need to integrate your app with Capacitor or Cordova.
        See the docs for setting up native projects:

        iOS: https://ionicframework.com/docs/building/ios
        Android: https://ionicframework.com/docs/building/android
```

Maybe I need to add information in the ionic.config.json file, but I am not sure what to add...

**Comment by NLegendre** [comment]
After some tests, I can answer to myself:
I have added the Capacitor configuration data (from capacitor.config.ts) in the ionic.config.json file.
Here is an example: 
```
{
  "name": "MY APP NAME",
  "integrations": {
    "capacitor": {
        "appId": "com.COMPANY.APPLICATION",
        "appName": "MY APP NAME",
        "bundledWebRuntime": false,
        "webDir": "dist",
        "plugins": {
            "PushNotifications": {
                "presentationOptions": ["badge", "sound", "alert"]
            }
        }
    }
  },
  "type": "vue"
}
```

Then the command `ionic live-update add` worked and added the 2 dependencies:
- cordova-plugin-ionic
- @vue/cli-service

I will now try the live update :)

**Comment by dotNetkow** [comment]
Thanks again for reporting this. As Shane mentions we did rename the command recently but unfortunately missed updating some docs and the Appflow dashboard itself. Fixes are on the way. Cheers.
