### ISSUE TITLE
ionic state restore is giving error

### ISSUE THREAD

**Issue by PurvaShah2020** [ionic-team/ionic-cli#5054]
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios
cordova platform add android
cordova platform add android
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

My Ionic info:

Your system information:

Cordova CLI: Not installed
Gulp version: CLI version: 2.3.0
Gulp local:  Local version: 3.9.1
Ionic Framework Version: 1.3.5
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.12.2 
ios-sim version: ios-sim/9.0.0 darwin-x64 node-v12.11.0 
OS: Mac OS X El Capitan
Node Version: v12.11.0
Xcode version: Xcode 14.3 Build version 14E222b

**Comment by jcesarmobile** [comment]
You are using an unsupported Ionic CLI version and you don't have Cordova CLI installed, which is required if working in Cordova projects. Update your Ionic CLI to 7.x and install Cordova CLI 12.x.
