### ISSUE TITLE
Load issue with Ionic upload? Frequently getting "nan undefined" in Ionic view app

### ISSUE THREAD

**Issue by style-x7** [ionic-team/ionic-cli#506]
Hi Ionic Team and fellow developers,

Tried CLI versions 1.4 to 1.5 etc, Mac or Windows, Android or iOS. From time to time, I will get "nan undefined" in Ionic view app even when Ionic upload indicates successful upload with the app id. When I try to view app, I'll get error 404. Tried also clearing the app id etc ...

Will there be any plan to improve the load situation or anything I can still try to overcome the "nan undefined"/404 issue? 

p.s. I really want to use Ionic view and many ionic.io services and will be willing to pay for it, really hoping the situation will improve.

**Comment by jbavari** [comment]
Does the app only have issues with ionic view? Or does it have errors on a local simulator or attached device?

**Comment by kwektuanze** [comment]
Hi @jbavari , no error with local simulator or attached device, I usually only upload to Ionic View when I'm  ready to test my app with users (I would wish to do more app debugging on Ionic View but the uploading and "nan undefined" just keep slowing me down.

Right now Ionic View is working for me. There's also other developers facing the issue at https://gitter.im/driftyco/ionic-io-testers. Someone (perhaps within Ionic) mentioned that the upload connection will terminate after a short while but my app is not huge, ~ 5 MB.

**Comment by wilsonmiz** [comment]
And my app is only ~2 MB

**Comment by ln206** [comment]
any update on this? My app is successfully uploaded but the size is nan undefined on Ionic View app. Get 404 error when try to sync the app with my phone.

**Comment by IvanMiiranda** [comment]
the same here!!! u_u

**Comment by isaiahgrey93** [comment]
I am having the same issue here.

**Comment by llvc** [comment]
My uploaded size is also NAN UNDEFINED. 
what's the reason?

**Comment by jsanta** [comment]
Also getting it here. Don't know if it's because of Ionic View, my App or my faulty internet connection.
NaN Undefined and Sync failed Status 404

**Comment by sirajea** [comment]
I have the same issue.

**Comment by vijaemanlapaz** [comment]
same here im getting 404 when i try to sync

**Comment by sirajea** [comment]
@vijaemanlapaz I don't remember what I did to solve it. The issue may have solved itself or I reuploaded the app.

**Comment by badrihippo** [comment]
I'm getting the problem with the *sample* app, so it's very likely to be a connection problem (my connection is quite slow). Will retry a few times and see if I get it...

**Comment by allen8300** [comment]
The same!  Come on, anybody there to update on this issue?

**Comment by badrihippo** [comment]
OK...my strategy is to keep re-uploading the app till the proper size comes (instead of `NaN undefined`). No idea what the problem is, but I'm guessing it's something to do with the connection, or with the connection error not being reported. When it eventually shows a proper size, then I can download the app and it runs properly.

To reiterate: Keep retrying the upload. Re-check the size after each upload; if you get a proper size then the app will run properly. If not, try again till it works.

**Comment by wilsonmiz** [comment]
Seems the problem is still there even Ionic Cli is up to date. I guess it's a connection issue between my computer and Amz S3. For anyone else who meet this problem, try switch to another network or use a vpn, sometimes it work for me.

**Comment by wbhob** [comment]
Fixed? Close?
