### ISSUE TITLE
ionic 7.2.0 depends on superagent@8.1.2 :: but this has a vulnerability

### ISSUE THREAD

**Issue by Hyphaed** [ionic-team/ionic-cli#5089]
npm warn deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net

**Comment by SVidu96** [comment]
i have run `npm install -g superagent@latest` and then re-installed ionic but it does not fix the warning. Is it bad? Any method to fix this?

**Comment by Benjamin93270** [comment]
tu as réussis a résoudre le pb ?

**Comment by GR3YH4TT3R93** [comment]
@sean-perkins could a release for this be made?

**Comment by sean-perkins** [comment]
@GR3YH4TT3R93 I no longer work for OutSystems (the company that owns Ionic's projects). You will need to wait for the team to perform a new release.

Ionic CLI's value has decreased significantly with other CLIs improving (it is a CLI wrapping other CLIs). You may find that using the Capacitor CLI directly or your framework of choice, gives you all the functionality you need for development and bundling.
