### ISSUE TITLE
Cannot update global Ionic CLI v7.x to latest v8.2.x on mac (sudo npm install -g @ionic/cli )

### ISSUE THREAD

**Issue by edocbuhtig** [ionic-team/ionic-cli#5092]
**Description:**

**Steps to Reproduce:**

sudo npm install -g @ionic/cli 

**Output:**

Password:
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net

added 204 packages in 11s

33 packages are looking for funding
  run `npm fund` for details
\W $ionic --version
7.2.0

**My `ionic info`:**

```
Ionic:

   Ionic CLI : 7.2.0

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 2.0.1)   : 1.7.2

System:

   NodeJS : v20.13.1
   npm    : 10.5.2
   OS     : macOS Monterey
```

**Other Information:**

**Comment by jcesarmobile** [comment]
Ionic CLI and Ionic Framework are different things and have different versions, latest Ionic CLI is 7.2.0.

P.S. Don't use sudo to install npm packages, if you have permission problems installing npm packages, fix them, but using sudo will only create more future problems.
