### ISSUE TITLE
ionic cap sync fails on non OSX

### ISSUE THREAD

**Issue by mueggi** [ionic-team/ionic-cli#5095]
**Description:**
After upgrading from Capacitor 5 to 6, ionic cap sync fails on linux because it tries to run bundle exec pod install.

[capacitor] ✔ copy ios in 368.39ms
[capacitor] ✔ Updating iOS plugins in 7.48ms
[capacitor] ✖ Updating iOS native dependencies with bundle exec pod install - failed!
[capacitor] ✖ update ios - failed!
[capacitor] [error] ERR_SUBPROCESS_COMMAND_NOT_FOUND
[ERROR] An error occurred while running subprocess capacitor.

Compared to:
[capacitor] ✔ copy ios in 296.50ms
[capacitor] ✔ Updating iOS plugins in 7.73ms
[capacitor] [info] Found 16 Capacitor plugins for ios:
[capacitor]        @capacitor-community/background-geolocation@1.2.18
[capacitor]        @capacitor-community/keep-awake@4.0.0
[capacitor]        @capacitor-community/sqlite@5.7.4
[capacitor]        @capacitor/app@5.0.8
[capacitor]        @capacitor/clipboard@5.0.8
[capacitor]        @capacitor/device@5.0.8
[capacitor]        @capacitor/filesystem@5.2.2
[capacitor]        @capacitor/haptics@5.0.8
[capacitor]        @capacitor/keyboard@5.0.9
[capacitor]        @capacitor/network@5.0.8
[capacitor]        @capacitor/splash-screen@5.0.8
[capacitor]        @capacitor/status-bar@5.0.8
[capacitor]        @newaydata/capacitor-zip@1.0.4-nwy12
[capacitor]        @sentry/capacitor@0.12.1
[capacitor]        capacitor-email-composer@2.0.1
[capacitor]        @newaydata/firebase-appdistribution@0.0.4
[capacitor] [warn] Skipping pod install because CocoaPods is not installed
[capacitor] [warn] Unable to find "xcodebuild". Skipping xcodebuild clean step...
[capacitor] ✔ Updating iOS native dependencies with pod install in 4.18ms
[capacitor] ✔ update ios in 17.48ms
[capacitor] ✔ copy web in 6.86ms
[capacitor] ✔ update web in 221.97μs
[capacitor] [info] Sync finished in 0.775s

**Steps to Reproduce:**
Run ionic cap sync on a non OSX system.

**Output:**
[capacitor] ✔ copy ios in 368.39ms
[capacitor] ✔ Updating iOS plugins in 7.48ms
[capacitor] ✖ Updating iOS native dependencies with bundle exec pod install - failed!
[capacitor] ✖ update ios - failed!
[capacitor] [error] ERR_SUBPROCESS_COMMAND_NOT_FOUND
[ERROR] An error occurred while running subprocess capacitor.

**My `ionic info`:**
Ionic:

   Ionic CLI                     : 7.2.0
   Ionic Framework               : @ionic/angular 8.2.6
   @angular-devkit/build-angular : 17.3.8
   @angular-devkit/schematics    : 17.3.8
   @angular/cli                  : 17.3.8
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : 6.1.2
   @capacitor/core    : 6.1.2
   @capacitor/ios     : 6.1.2

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   Android SDK Tools : 26.1.1 (/home/mueggler/Android/Sdk)
   NodeJS            : v20.16.0 (/home/mueggler/.nvm/versions/node/v20.16.0/bin/node)
   npm               : 10.8.1
   OS                : Linux 6.9

**Comment by mueggi** [comment]
Apparently, it is caused by the cocoapods dependency in the Gemfile. Why, there is a change of behaviour after the upgrade, I don't know.

**Comment by chiemekailo** [comment]
can one bypass the call to `pod install` completely using a flag?
