### ISSUE TITLE
Possible to delay livereload

### ISSUE THREAD

**Issue by tobbbe** [ionic-team/ionic-cli#581]
Is it possible to delay livereload? I often (1/3 times) have to reload the page after the page has been refreshed with livereload. Maybe its because gulp isnt done?

**Comment by jbavari** [comment]
Currently, no. 

Do you have the serve watch directories set up correctly?

[See this](https://github.com/driftyco/ionic-cli#serving-an-alternate-document-root) about setting the watchPatterns to trigger a live reload after whatever file you are waiting on to change, to change.

**Comment by tobbbe** [comment]
Ive tried both the default "watchPatterns": ["www/**/*"] and "watchPatterns": ["www/js/**/*"]. I have the default directory structure from ionic. The watch gets triggered every time.

**Comment by jbavari** [comment]
What files are being changed that trigger the live reload? Maybe you just watch those files instead?

**Comment by tobbbe** [comment]
Well all of my JS files triggers the live reload. But isnt that the whole point of the live reload? :)
My project has a total of 413 lines (dont know if the size should matter..), and currently I have to reload the page manually almost every time :(

Here's my gulpfile
``
/// <vs SolutionOpened='serve' />
var gulp = require('gulp');
var gutil = require('gulp-util');
var concat = require('gulp-concat');
var sass = require('gulp-sass');
var minifyCss = require('gulp-minify-css');
var rename = require('gulp-rename');
var wrap = require("gulp-wrap");
var sh = require('shelljs');
var babel = require('gulp-babel');

var paths = {
    sass: ['./scss/**/*.scss'],
    js: ['./www/js/**/*.js'],
    jsstart: ['./www/js/']
};

gulp.task('default', ['sass']);

gulp.task('js', function () {
    gulp.src([
        paths.jsstart + 'config.app.js',
        paths.jsstart + 'services/*.js',
        paths.jsstart + 'directives/**/*.js',
        paths.jsstart + 'controllers/*.js'
    ])
    .pipe(babel())
    .pipe(concat('all.min.js'))
    .pipe(wrap("(function(){\n'use strict';\n<%= contents %>\n}());"))    
    .pipe(gulp.dest('./www/'));
});

gulp.task('sass', function(done) {
  gulp.src('./scss/ionic.app.scss')
    .pipe(sass({
      errLogToConsole: true
    }))
    .pipe(gulp.dest('./www/'))
    .on('end', done);
});

gulp.task('watch', function() {
    gulp.watch(paths.js, ['js']);
    gulp.watch(paths.sass, ['sass']);
});

gulp.task('serve', function (done) {
    sh.exec('ionic serve');
    done();
});

gulp.task('livereload android', function (done) {
    sh.exec('ionic run android -l');
    done();
});

gulp.task('android', function (done) {
    sh.exec('ionic run android');
    done();
});``

**Comment by AgDude** [comment]
I will second this request. With a marginally complex gulp file, if multiple files change, the livereload might occur before all of the required changes are written to disk.

**Comment by barocsi** [comment]
+1 this, for instance even with watchify you must wait with livereload or call it manually after browserify tasks finished but that would result 2-3 reloads in the browser since files are changing continuously. There must be a more elegant way to solve.

**Comment by edgahan** [comment]
I've written a comment on how I deal with livereload https://github.com/driftyco/ionic-cli/issues/393#issuecomment-242353230 that might help others.
