### ISSUE TITLE
ionic package upload fails when using a custom documentRoot

### ISSUE THREAD

**Issue by lewisl9029** [ionic-team/ionic-cli#620]
`ionic package` simply doesn't work when using any custom documentRoot other than 'www', because it looks like the expected filename is hardcoded to 'www.zip' (https://github.com/driftyco/ionic-app-lib/blob/master/lib/upload.js#L17), while the generated zip uses documentRoot for the filename (https://github.com/driftyco/ionic-app-lib/blob/master/lib/upload.js#L36).

Here's the full error I received:

```
An error occurred uploading the build: Error: ENOENT: no such file or directory, open '/toc/www.zip'

Error: ENOENT: no such file or directory, open '/toc/www.zip'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.uploadToS3 (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:112:14)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:56:21
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

ENOENT: no such file or directory, open '/toc/www.zip' (CLI v1.7.1)
```

Since `ionic build` builds from the 'www' folder regardless of what documentRoot is set to, I think that should be the default behavior for `ionic package` as well. The whole point of specifying a documentRoot other than 'www' for our project was so that we can run our raw source files in documentRoot through a build process, pipe the results into 'www', and use that for our actual app builds.

**Comment by agustinhaller** [comment]
I'm experiencing the same with `ionic upload` command.
I'm using Ionic CLI Version: 1.7.6

@mlynch @Ionitron any updates on this?

**Comment by nahankid** [comment]
Facing same issue

**Comment by DHFW** [comment]
+1

**Comment by rweindl** [comment]
+1 Having the same issue.

**Comment by engular** [comment]
+1

**Comment by henriquesacramento** [comment]
+1

**Comment by casparss** [comment]
+1

**Comment by AdrienDC** [comment]
+1 also with ionic build

**Comment by marcusvas** [comment]
+1 
as workaround i created a link symbolic.

**Comment by waldeilton** [comment]
+1

**Comment by tlkiong** [comment]
@marcusvas Could you be more specific on the steps when you say you `created a link symbolic`?
Where did you link from and where did you link it to?
