### ISSUE TITLE
Feature Request: `ionic upload` could be able to set versioning data for Ionic deploy

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#660]
The ionic.io web UI is nice, but it would be really nice if we could set the versioning values and metadata on the CLI too, so it can easier be used in an automated way.

**Comment by yleflour** [comment]
Greatly aggree on this!

We are trying to automatize our build and deployment process. Right now our biggest pain point is not being able to add the versioning and metadata when uploading from the CLI.

This breaks the deployment workflow and leaves a time window between the moment we deploy and the moment we change these informations.

So using a json or data within the config.xml file to automatically set these values would be really useful.

**Comment by ArjenBroeze** [comment]
+1. Would love to see this feature as well.

**Comment by coderroggie** [comment]
+5.  Me and 4 of my co-workers would love this.

**Comment by martyzz1** [comment]
+1

**Comment by johnfakeacc** [comment]
+1 Absolutely necessary

**Comment by amaccann** [comment]
+1 on this: currently our deployment process is more manual than it should be - the lack of CLI tools to set versioning and metadata on each upload is a big minus for us.

**Comment by baffleinc** [comment]
+1!

**Comment by AgDude** [comment]
Here is my gulp task that accomplishes this (using the referenced undocumented api endpoint.

https://gist.github.com/AgDude/b64c33089c84b257100208eae1067902

**Comment by janpio** [comment]
`ionic upload --metadata='{"livereload":true, "version":".170625"}' --note="test metadata"` is now implemented via #2430. Versioning data is still missing though.

**Comment by digaus** [comment]
@janpio 
Could not get it to work... metadata is not uploaded :/ any ideas ?

**Comment by janpio** [comment]
No,

Please create a new issue for this or even better a topic at the Ionic community: https://forum.ionicframework.com/ Here is not the right place. Thanks.
