### ISSUE TITLE
ionic package build --release failing

### ISSUE THREAD

**Issue by danielfpedro** [ionic-team/ionic-cli#703]
I'm building iOS for `release` and is failing but when I try build `debug mode` the same project is working.
It could make sense if the error was about the `security profile` but when I run `ionic package info` I got a big error description talking about plugins:

```
ix.pch -MMD -MT dependencies -MF /Users/package/workspace/ionic_dash-80134a1c-94
/cordova/platforms/ios/build/Lamartine\ Posella.build/Release-iphoneos/Lamartine
\ Posella.build/Objects-normal/arm64/PushPlugin.d --serialize-diagnostics /Users
/package/workspace/ionic_dash-80134a1c-94/cordova/platforms/ios/build/Lamartine\
 Posella.build/Release-iphoneos/Lamartine\ Posella.build/Objects-normal/arm64/Pu
shPlugin.dia -c /Users/package/workspace/ionic_dash-80134a1c-94/cordova/platform
s/ios/Lamartine\ Posella/Plugins/phonegap-plugin-push/PushPlugin.m -o /Users/pac
kage/workspace/ionic_dash-80134a1c-94/cordova/platforms/ios/build/Lamartine\ Pos
ella.build/Release-iphoneos/Lamartine\ Posella.build/Objects-normal/arm64/PushPl
ugin.o
In file included from /Users/package/workspace/ionic_dash-80134a1c-94/cordova/pl
atforms/ios/Lamartine Posella/Plugins/phonegap-plugin-push/PushPlugin.m:29:
/Users/package/workspace/ionic_dash-80134a1c-94/cordova/platforms/ios/Lamartine
Posella/Plugins/phonegap-plugin-push/PushPlugin.h:31:35: warning: cannot find pr
otocol definition for 'GGLInstanceIDDelegate'
@interface PushPlugin : CDVPlugin<GGLInstanceIDDelegate>
                                  ^
/Users/package/workspace/ionic_dash-80134a1c-94/cordova/platforms/ios/Lamartine
Posella/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note: protocol 'GGLInst
anceIDDelegate' has no definition
@protocol GGLInstanceIDDelegate;
          ^
/Users/package/workspace/ionic_dash-80134a1c-94/cordova/platforms/ios/Lamartine
Posella/Plugins/phonegap-plugin-push/PushPlugin.m:451:42: warning: undeclared se
lector 'userHasRemoteNotificationsEnabled' [-Wundeclared-selector]
    if ([appDelegate respondsToSelector:@selector(userHasRemoteNotificationsEnab
led)]) {
```

Note: Thats a piece of the output, theres much more.

**Comment by danielfpedro** [comment]
thats the command that I'm trying

`ionic package build ios --release --profile distribution`

**Comment by danielfpedro** [comment]
Other fact: I tried build with Adobe Build and worked, same project same credentials.

**Comment by Elyahou** [comment]
I have this issue too.
It seem it is caused by the phonegap-push-plugin.
I think it is because an old version of Xcode use by ionic package

see https://github.com/phonegap/phonegap-plugin-push/issues/458

**Comment by danielfpedro** [comment]
@Elyahou make a lot of sense.

**Comment by danielfpedro** [comment]
After a lot of investigation the problem could be:
1 - The xcode is below 7 and is conflicting with push plugin the requires 7 or above
2 - The xcode is above 7 and is with bitcode = on.

**Comment by divyekhanna** [comment]
Hi @danielfpedro @Elyahou was this resolved for any of you? Release build using ionic package on iOS is failing for me as well whereas debug build has no errors.

I'm getting the same long error message citing the following Cordova plugins: ionic push, Cordova geolocation, Cordova facebook4, Cordova toast.

Is the any way we can pass a param to the ionic package server instructing to use xcode > 7?

**Comment by danielfpedro** [comment]
hi @divyekhanna, nothing changed since this issue was created. I think the only way to solve this is ionic server side guys do something. I already talked to Mike on slack, he said that was talk to server side guys but nothing.

**Comment by divyekhanna** [comment]
@danielfpedro thanks for the prompt response! I'll try to get in touch with the devs over slack as well.

**Comment by williamslr** [comment]
Hi all,

I think I can solve your issue for you. Following the guidelines outlined here:  [https://github.com/phonegap/phonegap-plugin-push/issues/458] this will work, however you may need to add in an extra few steps in regards to adding the push plugin. 

1. Make sure you delete the phonegap-plugin-push folder from your project directory (I manually do this by going to my plugins folder and hitting delete on it). I also tend to delete the ios, fetch and remote_ios files in this folder too if they've been generated.

2. Make sure you delete your platforms folder from your project root directory.

3. MANUALLY add in the push plugin via a CLI, I use the cordova CLI via: cordova plugin add phonegap-plugin-push@1.2.3 - this will need to match what you have in your config file, as a personal preference I'm using 1.2.3 because it's the latest version I've found that works.

4. Rebuild and enjoy.

In addition: If you want to follow issue #458 to the nth degree, you add:   `<preference name="deployment-target" value="7.0" />` to your config file.

Note: I don't know why plugins act like this but if you get similar errors for other plugins, you can try this fix too - I hope this works for you :)

**Comment by alamops** [comment]
@williamslr 
well, this didn't work form me.
The problem persists.

**Comment by emmychen** [comment]
I cannot build ios with ng-cordova push notification plugin.   I spent whole day try to figure out how to make it work.   Anyone has the solution?

/Users/emmychen/Downloads/mathwp/platforms/ios/mathWordProblem/Plugins/phonegap-plugin-push/PushPlugin.h:30:11: note: protocol 'GGLInstanceIDDelegate' has no definition
@protocol GGLInstanceIDDelegate;
          ^

** BUILD FAILED **


The following build commands failed:
	CompileC build/mathWordProblem.build/Debug-iphonesimulator/mathWordProblem.build/Objects-normal/i386/PushPlugin-6DDBE1605A8AD998.o mathWordProblem/Plugins/com.phonegap.plugins.PushPlugin/PushPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/emmychen/Downloads/mathwp/platforms/ios/cordova/build-debug.xcconfig,-project,mathWordProblem.xcodeproj,ARCHS=i386,-target,mathWordProblem,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/emmychen/Downloads/mathwp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/emmychen/Downloads/mathwp/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/emmychen/Downloads/mathwp/platforms/ios/cordova/build-debug.xcconfig,-project,mathWordProblem.xcodeproj,ARCHS=i386,-target,mathWordProblem,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/emmychen/Downloads/mathwp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/emmychen/Downloads/mathwp/platforms/ios/build/sharedpch

**Comment by nzamani** [comment]
After upgrading to Xcode 8.2.1 I suddenly had the same issue. A state reset solved the issue for me ():

```
ionic state reset
ionic build ios
ionic build ios --release
```

**Comment by wbhob** [comment]
So not failing anymore? Please close
