### ISSUE TITLE
ionic login fails with correct details

### ISSUE THREAD

**Issue by arunreddyark** [ionic-team/ionic-cli#705]
When I execute any of the following commands:

```
ionic login
ionic upload
ionic io init
```

it gives me:

```
Error logging in
Error Email or Password incorrect. Please visit https://apps.ionic.io for help. undefined
```

I've tried all versions of ionic-cli.
My system info:

```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68
```

**Comment by kaqfa** [comment]
I have the same error while using CLI v1.7.15

**Comment by abhaypokharkar** [comment]
I am also facing same issue. 
I can login to ionic apps on browser but cant login to CLI with same details.
Tried with 2-3 more accounts.

**Comment by kaqfa** [comment]
It looks like, some networks blocking port that is used by ionic.io.
I failed to use ionic init in my University, but it works on other network.
Just try to use other internet connection.
