### ISSUE TITLE
error while running crosswalk with ionic 

### ISSUE THREAD

**Issue by trygonian** [ionic-team/ionic-cli#719]
emulator: device fd:604

emulator: The memory needed by this AVD exceeds the max specified in your HAXM c
onfiguration.
emulator: AVD      RAM size = 1907 MB
emulator: HAXM max RAM size = 512 MB
emulator: You might want to adjust your HAXM is not working and emulator runs in
 emulation mode
AVD RAM size and/or HAXM configuration to run in fast virt mode.

Cannot set up guest memory 'pc.ram': Invalid argument

C:\Users\xxxxxxxx\Ionic\my_app>ionic info

Your system information:

Cordova CLI: 5.4.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
OS: Windows 7 SP1
Node Version: v4.2.4

**Comment by ArnabBir** [comment]
You need to reduce the RAM size of your emulator. Open AVD Manager and select your device and click "Edit" button. Then in "Memory Options" find the RAM parameter and set it to 512 or 1024 for (according to HAXM). Save the current configuration and restart your application or AVD
