### ISSUE TITLE
Cordova CLI not detected with newer versions

### ISSUE THREAD

**Issue by anishone** [ionic-team/ionic-cli#731]
I installed cordova using `sudo npm install -g cordova` and can see that its installed:
`sudo npm -g list | grep cordova`

```
├─┬ cordova@6.0.0
│ ├─┬ cordova-lib@6.0.0
│ │ ├── cordova-app-hello-world@3.10.0
│ │ ├─┬ cordova-common@1.0.0
│ │ ├─┬ cordova-js@4.1.3
│ │ ├── cordova-registry-mapper@1.1.14
│ │ ├─┬ cordova-serve@1.0.0

│ │ ├─┬ ionic-cordova-lib@5.1.10
│ │ │ ├── cordova-app-hello-world@3.9.0
│ │ │ ├─┬ cordova-js@4.0.0
│ │ │ ├── cordova-registry-mapper@1.1.14
│ │ │ ├─┬ cordova-serve@0.1.3
```

But, `ionic info` shows that Cordova CLI is not installed.

```
$ sudo ionic info
Your system information:

Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.53
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 6.4 Build version 6E35b
```

However, if I install cordova@4.2.0, then `ionic info` identifies that its installed. 

I tried uninstalling and reinstalling ionic, ionic@beta.. but still it shows the same error. Am I missing something? Is there any way to let ionic know the path of Cordova? I want to use newer versions of cordova.

Thanks!

**Comment by jasoncopp** [comment]
I'm getting this problem to. I'm also on a mac. Here's my ionic info:

Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.54
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.2.1 Build version 7C1002 

This broken when I updated from Cordova 5.x to 6 last week, and I haven't been able to get anything but 4.x to install and work now.

**Comment by jasoncopp** [comment]
Perhaps related: when I install Cordova@4 (4.3.1), Ionic can see the CLI installed. Also, cordova -v reports properly. Then, after a sudo npm install -g cordova, issuing "cordova -v" reports this:

iMac:Source jason$ cordova -v
/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/Users/jason/.config/configstore/update-notifier-cordova.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:27:44)
    at new UpdateNotifier (/usr/local/lib/node_modules/cordova/node_modules/update-notifier/index.js:34:17)
    at module.exports (/usr/local/lib/node_modules/cordova/node_modules/update-notifier/index.js:123:23)
    at checkForUpdates (/usr/local/lib/node_modules/cordova/src/cli.js:64:20)
    at cli (/usr/local/lib/node_modules/cordova/src/cli.js:116:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/bin/cordova:41:1)

Sudo fixes it, but it looks like a permission problem.

**Comment by jimbojw** [comment]
The root cause of this issue (and many like it) is https://github.com/npm/write-file-atomic/issues/11.

There is an outstanding patch which will fix this for everyone. We're all waiting for someone from npm to accept it: https://github.com/npm/write-file-atomic/pull/13
