### ISSUE TITLE
error after installing ionic start sass

### ISSUE THREAD

**Issue by dm0n** [ionic-team/ionic-cli#76]
After installing **ionic start sass**
then running **ionic serve**
I get the following error:
`
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
`

**Comment by adaptivedev** [comment]
@MarcSallent, ok, to what should I set my SASS_PATH? Thanks!

**Comment by MarcSallent** [comment]
@adaptivedev to . (dot)

if you are in a mac you should just type

>export SASS_PATH=.

when you are in your app folder in the terminal

**Comment by ivancamilov** [comment]
In case anyone comes through Google, I'm using Node v0.12.0 and this worked for me: Just change the `gulp-sass` version to the most recent once, which at the time of this writing is `2.0.1`. Thus, you would have this in your `package.json`:

```
"dependencies": {
    "gulp": "^3.5.6",
    "gulp-sass": "^2.0.1",
    // [...] bunch other ones [...]
  },
```

**Comment by ArthurGevorkyan** [comment]
I've been struggling with that for an hour until I realized that I forgot to do `bower install` in the project root. Such a silly thing, yet such an important one.

**Comment by sufyanshoaib** [comment]
thanks @ArthurGevorkyan ... how can we forget to do this... `bower install`

**Comment by noor07** [comment]
i got a error like

Error in plugin 'sass'
Message:
    scss\ionic.app.scss
Error: File to import not found or unreadable: ../www/lib/ionic/scss.
       Parent style sheet: C:/Users/hodan/myapp/scss/ionic.app.scss
        on line 4 of scss/ionic.app.scss
>> @import "../www/lib/ionic/scss";
       ^

**Comment by dwieeb** [comment]
@noor07 You may want to use our [Support Page](https://ionicframework.com/support) for that.

I'm locking this issue because it is ancient.
