### ISSUE TITLE
ionic serve custom gulp commands

### ISSUE THREAD

**Issue by danhowitt** [ionic-team/ionic-cli#77]
So I really like the mechanism to execute the sass and watch gulp tasks when serving the application. I was wondering if this could be expanded so any gulp task could be executed as a prerequisite to running the `ionic serve` command?

Maybe the sass flag in the ionic project file needs to be called something more generic like `preserve`or `build` giving the user the option of referencing multiple gulp tasks in their gulpfile?

```
{
  "name": "myApp",
  "app_id": "",
  "preserve": true
}
```

``` javascript
gulp.task('preserve', ['sass', 'angular-templates'])
```

In most use-cases it's not just sass which needs a preprocessing step, images, templates etc sometimes need to be passed through a gulp task. At present my work around is to declare `sass: true` in the ionic project file and amend the watch task to run:

``` javascript
gulp.task('watch', ['angular-templates'], function() {
  gulp.watch(paths.sass, ['sass']);
  gulp.watch(paths.templates, ['angular-templates']);
});
```

Of course this means in order for the watch task to be executed the `sass: true` flag is required.

On feedback, i'd be happy to submit a pull req.

**Comment by streetkid** [comment]
Does the gulp integration work for ionic build commands?
