### ISSUE TITLE
Bug - ionic resources - not generating xxxhdpi splash

### ISSUE THREAD

**Issue by JerryBels** [ionic-team/ionic-cli#798]
Hello,

I'm using Ionic resources to generate my icons and splashscreens. It does generate the icon in xxxhdpi, but not the splash screen - which I realised by testing my app on a Galaxy S6. The splash screen used is then xhdpi, which looks bad on that resolution type of screen.

anything I could do besides generating myself the missing images ?

Thanks

**Comment by JerryBels** [comment]
Update : I finally succeeded into generating the xxxhdpi version of the splash screen, but ... It still looks bad on the Galaxy S6, stretched and globally "zoomed". Does anyone knows how to handle this bug ?

**Comment by tlancina** [comment]
Hey @JerryBels sounds like we'll need to update the server that resources uses to generate images to also do the xxxhdpi splash screen.

**Comment by JerryBels** [comment]
Hey @tlancina ! I think this has been done already, because last time I tried after updating my CLI it generated it, as I said. Now the issue is not that it's not here, but more that it's not used by the app and I don't know why.

**Comment by tlancina** [comment]
Hmm based on https://github.com/driftyco/ionic-cli/issues/540 sounds like we may need to generate different dimensions for xxxhdpi devices!

**Comment by JerryBels** [comment]
Okay, I will follow the progress on that topic, thanks :)
