### ISSUE TITLE
Remove default adding of IOS platform

### ISSUE THREAD

**Issue by redfox05** [ionic-team/ionic-cli#799]
By default there should be no platforms added.
It's not hard to run ionic platforms add ios

And then it begs the question, why ios and not android. Surely there should be no favoritism.

In the meantime, am I ok to just run 'ionic platforms remove ios'
Is that all thats needed to do to complete remove ios 'stuff'?

**Comment by tlancina** [comment]
Hey agreed, definitely something we should reevaluate if it's actually helpful or more of a hinderance.  At the minimum there should be a flag allowing you to disable it.

**Comment by tlancina** [comment]
Oh and to your last question you should be fine running `ionic platform remove`, there is no special logic on install as far as I know.

**Comment by dwieeb** [comment]
This no longer happens, so closing this. Thanks!
