### ISSUE TITLE
Enabling live reload option in CLI results with black screen on Android Nexus 4

### ISSUE THREAD

**Issue by mostr** [ionic-team/ionic-cli#81]
I've upgraded to newest CLI to test drive live reload. Sadly when enabled, I'm getting black screen on my Nexus 4. Application works fine when `-l` is not passed. I've used sample app built with `ionic start myapp sidemenu`. There is nothing in the logs (even if `-c` and `-s` are provided)

Console output tail:

```
Installing app on device...
Launching application...
LAUNCH SUCCESS
```

**Comment by westonganger** [comment]
If Wifi is turned off livereload results in black screen. Turn your Wifi on!

**Comment by leschirmeur** [comment]
@westonganger you just saved my day with your hint regarding wifi...

**Comment by DevonteDC** [comment]
@gabrielmuresan I have been up for hours trying to figure out what was wrong with the livereload!! it works totally fine on my other computer, but fails on my new one....of course the answer was McAfee blocking my phone's access to the server!...omg you are a hero. thank you so much! freaking McAfee man...

**Comment by supaheckafresh** [comment]
@westonganger thanks. Definitely the correct answer!

**Comment by ofergoz** [comment]
Thank you so much!! Turning off Avast's shields solved my problem!!
