### ISSUE TITLE
ionic run --livereload <PLATFORM> does not work for a connected device

### ISSUE THREAD

**Issue by zarko-tg** [ionic-team/ionic-cli#82]
ionic run -l --device android
while having a ( Android Nexus 5 ) device attached over USB to the host PC.

> Setup Live Reload
> Running dev server: http://localhost:8100
> Running live reload server: http://localhost:35729
> add to body class: platform-android
> ...
> BUILD SUCCESSFUL
> Total time: 8 seconds
> WARNING : No target specified, deploying to device '04cb950a8291ddab'.
> Using apk: C:\live\platforms\android\ant-build\live-debug-unaligned.apk
> Installing app on device...
> Launching application...
> LAUNCH SUCCESS

is fine but the application shows the following right after being installed and started up:

![image](https://cloud.githubusercontent.com/assets/6142411/4145919/b9b7b88c-3402-11e4-9912-37140106db35.png)

The app itself was created from one of the inbuilt templates with ionic-cli 1.2.0

Both host PC and device are connected to the same wireless network, and the application is trying to talk to localhost for live (re)loading. It should instead connect to the actual assigned IP address of the host PC. Isn't it so?

**Comment by igorprado** [comment]
I've selected a wrong network IP Address and now when I use livereload it point to a IP that my webview cannot access. How can I change it easly? I changed platforms\android\res\xml\config.xml to the correct IP address but it still getting to get the wrong IP. How can I change the default IP addess used on livereload?

**Comment by IamAdamJowett** [comment]
@igorprado `ionic address` is what you need

**Comment by qintengfei** [comment]
额，finally can liveload on my ip6, step by step
1.i change the xcode seting
<img width="421" alt="2015-09-30 8 51 30" src="https://cloud.githubusercontent.com/assets/2504160/10193348/146fc314-67b5-11e5-8e28-1ea00a892ac8.png">
2.then i run `run ios -l`
3.in xcode i `cmd+r`
4.but i don't know why?

**Comment by westonganger** [comment]
If Wifi is turned off livereload results in black screen. Turn your Wifi on!

**Comment by cooervo** [comment]
Livereload doesn't work without wifi if you need to test your ionic app without internet then run without live reload

**Comment by sushruth** [comment]
I am trying to use `ionic run -l` using a guest OS and I have an android device connected through USB which is routed to the guest OS. I get a blank screen when I try to run the app with live reload. The output looks like so :

<pre>
Setup Live Reload
<b>Running live reload server: undefined</b>
Watching: 0=www/**/*, 1=!www/lib/**/*
Running dev server:  http://10.0.2.15:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
</pre>

Any thoughts on this would help. Thanks.

**Comment by marioidival** [comment]
How to remove this 
```
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

I want use Ionic with docker-compose and that broken the docker-compose

**Comment by chamaraonline** [comment]
Install this plugin to cordova
https://github.com/apache/cordova-plugin-whitelist

**Comment by askalia** [comment]
+1 for --livereload-host in CLI command
putting IP of my dev machine.
Then ionic asks for the correct IP it must use for livereload, and it works fine.

**Comment by douglasjam** [comment]
+1

**Comment by cardeol** [comment]
I've got this message when I run C:\project>ionic run android -l 
Ionic: 2.1.0
Ionic-cli: 3.10.8

TypeError: Can't call method on  undefined
   at TypeError (native)
   at module.exports (C:\...node_modu
es\core-js\modules\_defined.js:3:28)
   at createHTML (C:\project\node_modules\
ore-js\modules\_string-html.js:7:19)
   at bold (C:\...\node_modules\core-j
\modules\es6.string.bold.js:5:12)
   at cb (C:\...\AppData\Roaming\npm\node_modules\ionic\nod
_modules\winston\lib\winston\logger.js:206:7)
   at done (C:\Users\carlos.deoliveira\AppData\Roaming\npm\node_modules\ionic\n
de_modules\async\lib\async.js:167:19)
   at C:\Users\carlos.deoliveira\AppData\Roaming\npm\node_modules\ionic\node_mo
ules\async\lib\async.js:40:16
   at C:\Users\carlos.deoliveira\AppData\Roaming\npm\node_modules\ionic\node_mo
ules\winston\lib\winston\logger.js:193:9
   at Console.log (C:\Users\carlos.deoliveira\AppData\Roaming\npm\node_modules\
onic\node_modules\winston\lib\winston\transports\console.js:127:3)
   at emit (C:\Users\carlos.deoliveira\AppData\Roaming\npm\node_modules\ionic\n
de_modules\winston\lib\winston\logger.js:186:17)
   at C:\Users\carlos.deoliveira\AppData\Roaming\npm\node_modules\ionic\node_mo
ules\async\lib\async.js:157:13
   at _each (C:\Users\carlos.deoliveira\AppData\Roaming\npm\node_modules\ionic\
ode_modules\async\lib\async.js:57:9)
   at Object.async.each (C:\...\AppData\Roaming\npm\node_mo
ules\ionic\node_modules\async\lib\async.js:156:9)
   at Logger.log (C:\...npm\node_modules\i
nic\node_modules\winston\lib\winston\logger.js:214:9)
   at target.(anonymous function) [as info] (C:\Users\carlos.deoliveira\AppData
Roaming\npm\node_modules\ionic\node_modules\winston\lib\winston\common.js:54:18

   at Object.setupLiveReload (C:\Users\carlos.deoliveira\AppData\Roaming\npm\no
e_modules\ionic\lib\utils\cordova.js:213:7)

**Comment by fruitangdan** [comment]
I managed to get Live Reload working on the device, though it's not the most elegant solution:

- Get your computer's IP address e.g.
   `192.168.1.103`
- Add the following script tag to index.html, directly after cordova.js, replacing the ip address and port:

```
<script>
	// device live reload
	var deviceLiveReload = {
		enabled: 	true,
		ipAddress: 	'192.168.1.103',
		port: 		'8100'
	}
	if (deviceLiveReload.enabled) {
		if (window.location.href.indexOf('http://' + deviceLiveReload.ipAddress) === -1) {
			window.location.href='http://' + deviceLiveReload.ipAddress + ':' + deviceLiveReload.port;
		}
		// if ios device, include cordova files 
		var iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
		if (iOS) {
			document.write('<script src="cordova-files/cordova.js"></scr' + 'ipt>');
		}
	}
</script>
```

- Run ionic serve using the computer's current IP address, e.g.
```
ionic serve --address 192.168.1.103
```
- Copy the items cordova_plugins.js, cordova-files, cordova-js-src and cordova.js from platforms/ios/www/ to /www/cordova-files/ (cordova-files is a new folder)
- Build and run the project
- Now when you make code changes, you should see the app on the iOS device refresh straight away
- Note: set enabled to false when not in development
- Note: remember to change your ip address if your computer's ip changes and rerun ionic serve with the new ip address

All this is doing is redirecting the app on your device to your local address, and appending the the cordova js files. This only works for iOS so will need tweaking for Android.

**Comment by Anujmoglix** [comment]
When i am doing **ionic run andoid -lcs** then it is working fine but on i**onic run android** i am facing 403 issue on my api. I want to test on different wifi on client side then it is not working , What to do ?

**Comment by AtoianAvetik** [comment]
I had the same problem, and I fixed it when adding port 8100 to firewall exceptions.
.

**Comment by mwddevcenter** [comment]
Add this code to your "index.html", Then use
ionic cordova run android --livereload-host --livereload -c
It should work.
  <meta http-equiv="Content-Security-Policy" content="font-src 'self' data:; img-src * data:; default-src gap://ready file://* *; script-src 'self'  'unsafe-inline' 'unsafe-eval' * ; style-src 'self' 'unsafe-inline' *">

**Comment by PradeepThite** [comment]
> Sure.
> An CLI option aside --livereload-port (--livereload-host ? ) could also be easy quick fix

Worked for ionic 3 app
Thanks
