### ISSUE TITLE
Cannot re-export name that is not defined in the module.

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#849]
_From @fairsayan on March 18, 2016 12:8_
#### Short description of the problem:

I just created a new project in Ionic 2 typescript and sidemenu as template
Everytime I run `ionic serve` I receive this not blocking error:

> ERROR in [default] /.../scaffold-ionic/node_modules/angular2/src/facade/promise.d.ts:1:9 
> Cannot re-export name that is not defined in the module.

**Steps to reproduce:**
1. ionic start scaffold-ionic sidemenu --v2 --ts
2. ionic serve

**Here the complete flow**

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file

∆ Compiling Sass to CSS
√ Matching patterns: app/theme/app.+(ios|md|wp).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-angular/fonts/*_/_.+(ttf|woff|woff2)

∆ Copying HTML
√ Matching patterns: app/*_/_.html

√ HTML copied to www/build
√ Sass compilation complete
√ Fonts copied to www/build/fonts

Hash: 4d8afbdec4626d5a657f
Version: webpack 1.12.11
Time: 5935ms
        Asset     Size  Chunks             Chunk Names
app.bundle.js  2.73 MB       0  [emitted]  main
   [0] multi main 64 bytes {0} [built]
    + 363 hidden modules

ERROR in [default] /.../scaffold-ionic/node_modules/angular2/src/facade/promise.d.ts:1:9 
Cannot re-export name that is not defined in the module.

√ Webpack complete

∆ Starting dev server.

√ Running live reload server: http://localhost:35729
√ Running dev server:  http://localhost:8100
√ Watching: 0=www/build/**/*.html, 1=www/build/**/_.js, 2=www/build/__/_.css
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ 

_Copied from original issue: driftyco/ionic#5876_

**Comment by jgw96** [comment]
Thanks for opening this issue with us! As this issue has more to do with our CLI than the actual framework I will be moving this issue over to that repo. Please feel free to continue the conversation there! Thanks again!

**Comment by MrBokeh** [comment]
Add this line below at the top of **promise.d.ts** to declare the Promise variable will fix the problem:
`declare var Promise: PromiseConstructor; `

**Comment by fairsayan** [comment]
Is this an issue related with ionic or angular2? What is the best way to have this fix included in the core (without the necessity to manually add this line everytime I create a new project)?

**Comment by MrBokeh** [comment]
angular2 module

**Comment by twysto** [comment]
I also encounter this issue today.
But in addition to the fix mentioned by @MrBokeh in the **promise.d.ts** file, I also had to add this on top of my **gulpfile.js** : `require('es6-promise').polyfill();`

**Comment by skol-pro** [comment]
Hi !

I have the same issue, however there is no **promise.d.ts** file on my side, how is this possible ? :-/
I used the _ionic start --v2 --ts_ command.

**Comment by GaneshPediredla** [comment]
Where I should add declare var Promise: PromiseConstructor;?

**Comment by fairsayan** [comment]
@GaneshPediredla as described by @MrBokeh : at the top of promise.d.ts

**Comment by GaneshPediredla** [comment]
yes got it. But every project i should do like this. Its bit  difficult to for every project. Any otherway to solve this problem permanently?

**Comment by veswanthRaju** [comment]
yes its working:)
