### ISSUE TITLE
iOS cordova platform and cordova plugins not saved in package.json

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/ionic-cli#862]
So it appears that the iOS platform is added by default now. Correct?
<img width="697" alt="screen shot 2016-03-25 at 11 51 37" src="https://cloud.githubusercontent.com/assets/1189149/14037540/472b8274-f280-11e5-8ddc-ba36372d908a.png">
Because after initialising an Ionic app and trying to add the iOS platform it says its already added:
<img width="697" alt="screen shot 2016-03-25 at 11 57 38" src="https://cloud.githubusercontent.com/assets/1189149/14037587/d23eaf44-f280-11e5-9593-9db22d03c77e.png">
But... there's no reference to it on package.json:
<img width="426" alt="screen shot 2016-03-25 at 12 00 38" src="https://cloud.githubusercontent.com/assets/1189149/14037624/3e7b057c-f281-11e5-9712-cc3b7d44bded.png">

Adding the android platform does create a reference to it on package.json but not the plugins:
<img width="697" alt="screen shot 2016-03-25 at 12 02 34" src="https://cloud.githubusercontent.com/assets/1189149/14037678/cdb04f72-f281-11e5-9089-372d91e0323e.png">
<img width="274" alt="screen shot 2016-03-25 at 12 03 23" src="https://cloud.githubusercontent.com/assets/1189149/14037681/d65b674c-f281-11e5-88f6-ac132ee10a11.png">
Shouldn't the package.json be something like the following? (package.json from a project using an older beta version of the CLI)
<img width="349" alt="screen shot 2016-03-25 at 12 06 31" src="https://cloud.githubusercontent.com/assets/1189149/14037722/41d909b6-f282-11e5-8a17-0b143703475d.png">
Here's my current Ionic info:
<img width="697" alt="screen shot 2016-03-25 at 12 08 45" src="https://cloud.githubusercontent.com/assets/1189149/14037734/59e58534-f282-11e5-9fc0-db6b63d39233.png">

**Comment by lordgreg** [comment]
I am having exactly the same issue. The only way to save them (in config.xml) is using the `--save` suffix.

I'd rate this as high priority but judging on responses form officials, I'd say its pretty low priority.

**Comment by dwieeb** [comment]
This has been fixed by Cordova. Shouldn't be an issue in the latest version.
