### ISSUE TITLE
ionic resources ignores windows platform

### ISSUE THREAD

**Issue by napcat** [ionic-team/ionic-cli#913]
Ionic resource command ignores the platform windows.

With the following folder structure all assets are created to iOS and Android, but not to windows. _(note: all platforms were correctly added with the command: ionic platform add xxxxx)._

```
/resources/android/icon.png
/resources/ios/icon.png
/resources/windows/icon.png
/resources/splash.png
```

Since ionic 1.2, we have suporte for windows 10 (http://blog.ionic.io/announcing-ionic-1-2/).
I think it would be nice to suporte this feature for this platform.

Can we expect an update soon?

**EDIT**
I also noticed that when the windows platform is added the assets inside the config.xml are from the Android platform...

**Comment by Zorgatone** [comment]
+1 :+1:

**Comment by dirkpostma** [comment]
There is a Visual Studio extension that can generate resources:
https://visualstudiogallery.msdn.microsoft.com/09611e90-f3e8-44b7-9c83-18dba8275bb2

In case link doesn't work anymore, search for "UWP Tile Generator"

**Comment by Zorgatone** [comment]
@dirkpostma yeah but that won't integrate nicely with cordova. You'll still have to modify your config.xml for all the generated resources, and it's a pain to do :unamused:

**Comment by dirkpostma** [comment]
@Zorgatone I don't say ionic shouldn't support generation, I think they should definately! But as a temporary workaround, you could use the tool I mentioned ;-)

**Comment by Thomodachi** [comment]
I am currently facing this problem. Are there any plans to realize icon/splashscreen generation für Windows UWP?

**Comment by maximumver** [comment]
Hello, any news about this feature?

**Comment by cassioscofield** [comment]
+1

**Comment by glat** [comment]
+1

**Comment by digaus** [comment]
Still no update!?

**Comment by ivaro18** [comment]
So does this mean we can't generate a splashscreen and icon for the windows platform? Must we use the default cordova ones?

**Comment by dwieeb** [comment]
Hey all, just to clarify: we're talking about the `windows` platform (https://cordova.apache.org/docs/en/latest/guide/platforms/win8/), not `wp8`, right?

**Comment by dwieeb** [comment]
Duplicate of https://github.com/ionic-team/ionic-cli/issues/2174

**Comment by MrIonic** [comment]
+1

**Comment by pjc2007** [comment]
Also same issue (for Windows 10 UWP). All images under platforms\windows\images are the Cordova defaults.
