### ISSUE TITLE
Interactive Start

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic-cli#934]
It would be cool if we had an interactive `ionic start` that prompted the user for some info about their app to make it easier to start projects and get them pre-configured:

Example output:

``` bash
$ ionic start
Hello! Let's get you started with a new Ionic app.

Hint: try the beta of Ionic 2 by entering "2" for Ionic version.

name: (My App) 
app id: (com.example.myapp) 
ionic version: (1) 
template: (tabs)
```

**Comment by brandyscarney** [comment]
We should give them the options to choose from for version and template, similar to commitizen's prompt:

<img width="607" alt="screen shot 2016-04-14 at 2 43 39 pm" src="https://cloud.githubusercontent.com/assets/6577830/14539679/58f061f8-024f-11e6-8cba-7fbe6eaac256.png">
