### ISSUE TITLE
Getting error on ionic serve

### ISSUE THREAD

**Issue by gopi2mohan** [ionic-team/ionic-cli#938]
I tryed to create an ionic2 project with command **sudo ionic start firstIonic --v2** and i am getting error on give **ionic serve** command i don't have any idea about this please help me.

>  ✗ Caught exception:
>  Error: EACCES, mkdir '/home/gopi/pot/www/build'
>     at Error (native) 
> 
> Mind letting us know? https://github.com/driftyco/ionic-cli/issues
> 
> In my UI i am getting two error like **GET http://localhost:8101/build/js/angular2-polyfills.js**  &  **GET http://localhost:8101/build/js/app.bundle.js**

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Is there a reason that you are running `ionic start firstIonic --v2` with `sudo` ? You should not have to use `sudo` with ionic start. Are you on linux (ubuntu, debian etc) or OSX?

**Comment by gopi2mohan** [comment]
thanks jgw96 but without using sudo i am not able to create a project for ionic --v2

**Comment by jgw96** [comment]
@gopi2mohan It seems that you may have some permissions issues with your system, as you should not have to use sudo with the ionic cli. Are you running linux (ubuntu, debian, mint) or OSX?

**Comment by Vagnerlg** [comment]
maybe this error only sintaxe javascript error

**Comment by wwwlike** [comment]
i donot no;
