### ISSUE TITLE
Cordova emulate flags throwing error with ionic

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic-cli#94]
So cordova's flags to target ios emulation are throwing an error

``` bash
$ ionic emulate ios --target="iPhone(Retina 4-inch)"
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `cordova emulate ios --target=iPhone(Retina 4-inch)'
```

But if you use cordova emulate, it works fine

``` bash
$ cordova emulate ios --target="iPhone(Retina 4-inch)"
```

**Comment by pencilcheck** [comment]
"iPhone(Retina 4-inch)" doesn't work for me, but I found a stackoverflow answer that solved my problem:

http://stackoverflow.com/questions/22310526/cordova-start-specific-ios-emulator-image
