### ISSUE TITLE
Inconsistent issues w/ Plugins and iOS

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic-cli#95]
I've seen this a few times now and initially I thought it was a fluke, but as it just happened again, I thought I should file it.

From time to time when I add a plugin, I am unable to do ios builds. I get an error like so:

clang: error: no such file or directory: '/Users/ray/Dropbox/projects/crunchtime2/platforms/ios/crunchtime2/Plugins/org.apache.cordova.splashscreen/CDVSplashScreen.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

2014-09-09 09:38:42.444 xcodebuild[59445:4703]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-5069/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:76
Details:  Failed to load dependencies output contents from ``/Users/ray/Dropbox/projects/crunchtime2/platforms/ios/build/crunchtime2.build/Debug-iphonesimulator/crunchtime2.build/Objects-normal/i386/CDVSplashScreen.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “CDVSplashScreen.d” couldn’t be opened because there is no such file." UserInfo=0x7fc50db6ed10 {NSFilePath=/Users/ray/Dropbox/projects/crunchtime2/platforms/ios/build/crunchtime2.build/Debug-iphonesimulator/crunchtime2.build/Objects-normal/i386/CDVSplashScreen.d, NSUnderlyingError=0x7fc50db6ec40 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/ray/Dropbox/projects/crunchtime2/platforms/ios/build/crunchtime2.build/Debug-iphonesimulator/crunchtime2.build/Objects-normal/i386/CDVSplashScreen.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString ___strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fc50db6eca0>{name = (null), num = 9}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
*_ BUILD FAILED **

The following build commands failed:
    CompileC build/crunchtime2.build/Debug-iphonesimulator/crunchtime2.build/Objects-normal/i386/CDVSplashScreen.o crunchtime2/Plugins/org.apache.cordova.splashscreen/CDVSplashScreen.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: /Users/ray/Dropbox/projects/crunchtime2/platforms/ios/cordova/run: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/ray/npm/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Process.ChildProcess._handle.onexit (child_process.js:820:5)

Note the mention of splashscreen. That is the plugin I just added. In previous encounters, if I removed the plugin, then re-added it, I was kosher. I just tried that and I still can't "ionic emulate ios."

**Comment by techntrails** [comment]
Same issue. Running a fairly vanilla project. I needed to remove the iOS platform, then re-add it so that the plugin would compile:

```
Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.35
Cordova CLI: 4.1.2
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.2
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1 
```

**Comment by josephfinlayson** [comment]
Getting exactly the same thing

    ionic platform add ios
    ionic plugin add com.ionic.keyboard
    ionic run ios 

//build fails so then

    ionic rm ios
    ionic add ios

Build succeeds
