### ISSUE TITLE
Ionic2 - Ionic login not working

### ISSUE THREAD

**Issue by sagivf** [ionic-team/ionic-cli#964]
I get "Error logging in"
Tried with two accounts.
It works through the web site.

Here are my system details:
![image](https://cloud.githubusercontent.com/assets/1857466/14886674/5353823a-0d52-11e6-912a-500b6d3a4d72.png)

**Comment by sagivf** [comment]
Any update on this? It's been a while...

**Comment by jgw96** [comment]
Hey @sagivf! Sorry about the wait on this! We are looking into this now.So you tried with two accounts, and both did not work and gave the same error correct?

**Comment by sagivf** [comment]
hey @jgw96 yes - both. works via the website. And I think it works without the beta.

**Comment by jgw96** [comment]
So I have some good news! The CLI team just took a look at it and it has already been fixed on the repo, but just has not been released yet as they are trying to get a few more things in before a release. I'll keep this issue open and update it as soon as they do the next release that has this fix. Again, so sorry it took so long to get back to you! Thanks for using Ionic!

**Comment by sagivf** [comment]
@jgw96 Much appreciated. By the way it seems that it isn't really an error - `ionic upload` works. I guess it's just showing an error message by mistake.

**Comment by jgw96** [comment]
@sagivf No problem at all! You are exactly right haha, it was a tiny bug that was causing the CLI to say there was an error when there wasn't one.

**Comment by mnadeemmdsol** [comment]
i am also facing same error, @jgw96  help me in this

**Comment by jgw96** [comment]
Hello @mnadeemmdsol ! As you can see above, there is currently a bug in the Ionic CLI that is causing it to say login failed even though the login went through fine. It has already been fixed in the repo and will make it into the next release. Thanks for using Ionic!

**Comment by mnadeemmdsol** [comment]
it is not working for me , when i can expect next release? @jgw96 
thanks for quick response.

**Comment by nmandyam** [comment]
I have exactly the same issue. Upload AND Login commands fail, while logging in online does work. And no, upload does not work for me. Help!

**Comment by shr9461** [comment]
Hi - when can we expect the next release? This same issue is affecting me and holding up a project I am working on currently that has a tight deadline.  I need to know if this next release is hours, das, or months away. Thanks.

**Comment by jgw96** [comment]
Hello @shr9461 ! You should still be able to use the upload feature even after the ionic-cli gives you the login failed error. Would you mind running `ionic info` and posting the output here? Thanks!

**Comment by Solitaryo** [comment]
Same Here. My info:

`Your system information:

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.3.1 Build version 7D1014`

**Comment by demirag** [comment]
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.0
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.0.0

Yes, -ionic login gives the error "Error loggin in" even if your credentials are correct. But seems like, it is a wrong. After that -ionic upload just works.

**Comment by jainnikhil781gmailcom** [comment]
I am also facing sampe problem 

ionic login/upload is not working

F:\MyIonic2Project>ionic login

To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

Email: jain.nikhil781@gmail.com
Password:
Email or Password incorrect. Please visit https://apps.ionic.io for help.

F:\MyIonic2Project>ionic login

To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

Email: jain.nikhil781@gmail.com
Password:
Email or Password incorrect. Please visit https://apps.ionic.io for help.

F:\MyIonic2Project>ionic upload
WARN: No 'upload:before' gulp task found!
If your app requires a build step, you may want to ensure it runs before upload.

No previous login existed. Attempting to log in now.

To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

Email: jain.nikhil781@gmail.com
Password:
Email or Password incorrect. Please visit https://apps.ionic.io for help.
Uploading app....
An error occurred uploading the build: TypeError: Cannot read property 'map' of undefined

TypeError: Cannot read property 'map' of undefined
    at Object.getDirectUploadKey (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\upload.js:262:18)
    at C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\upload.js:40:21
    at _fulfilled (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:509:49
    at flush (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


Cannot read property 'map' of undefined (CLI v2.0.0)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:
Node Version: v6.5.0

**Comment by coderdiaz** [comment]
`$ ionic login`

Not working for now :(

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20

**Comment by lluisnieto** [comment]
Still failing. can't believe this. Anyone else with this problem?

**Comment by sagivf** [comment]
its acctually been working well for a long time. can you add what you get from 'ionic info'?

**Comment by sagivf** [comment]
Try reinstalling ioni cli. npm install -g ionic. And try to be on a recent(6.x or 7.x) node version and npm version (3.x)

**Comment by lluisnieto** [comment]
I had to make a new account to make it work.

**Comment by anarvaez292** [comment]
I'm having the same issue.

**Comment by coderdiaz** [comment]
@anarvaez292 Are you try disable firewall?

**Comment by fabn** [comment]
Same issue here, I get this error

```
Request: POST https://api.ionic.io/login
Response: 404
Body:
{ link: null,
  message: 'No user found by that email',
  type: 'NotFound' }
```

Credentials are correct since they work with web ui.

Output of ionic info:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.1.3
    Cordova Platforms  : browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 2.1.0

System:

    Node  : v7.9.0
    npm   : 5.0.3
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b
```

**Comment by dwieeb** [comment]
@fabn Try using `ionic start` or `ionic link` with `--pro-id` before trying to log in. The CLI codebase has to work with both "backends", unfortunately.

**Comment by fabn** [comment]
@dwieeb `ionic link --pro-id` has worked, thanks.

**Comment by indrandr7** [comment]
Hi guys, I have same problem like that, but it was solve,
1. You have to create account free/pro is up to you, on ionicframework.com
2. Login > create 1 project > after that you will be given ID project like 14f7a683, and try to look     **Connect existing app** tab, there is on command how to link to your project like this **ionic link --pro-id 14f7a637**
3. Back to your CLI and then execute the command above > enter your ionicframework.com (email/password)
4. The last you can use **ionic cordova resources​** to generate icon and splash image
