### ISSUE TITLE
Ionic run android installs some other app instead of the project i am in 

### ISSUE THREAD

**Issue by raul1991** [ionic-team/ionic-cli#967]
I have made the app using the ionic creator and then exported the source code. Now when i do `ionic build android -> SUCCESS` , then i do `ionic run android -> SUCCESS` but now when i open the app installed on my connected device , it is some previous version of the app.

Any help would be great.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Have you tried completely uninstalling the app from your device and then doing `ionic run android` again? Also, does the same issue occur if you run `ionic serve`? And finally, what version of the ionic cli are you using? If you run `ionic info` from inside your project and post the output here that would be great!

**Comment by raul1991** [comment]
Hi,

Thanks for replying to my issue. I have tried

ionic serve - it shows the right app

uninstalled and installed the app but still no luck.

ionic cli version is 1.x.17

Plus i even deleted ny project , started another blank project and
installed on my phone but still that version gets installed.
On 02-May-2016 10:09 PM, "Justin Willis" <notifications@github.com> wrote:

Hello! Thanks for opening an issue with us! Have you tried completely
uninstalling the app from your device and then doing ionic run android
again? Also, does the same issue occur if you run ionic serve? And finally,
what version of the ionic cli are you using? If you run ionic info from
inside your project and post the output here that would be great!

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/driftyco/ionic-cli/issues/967#issuecomment-216287251>

**Comment by jgw96** [comment]
No problem! So you started a blank project and installed that to your phone and it still showed up as your creator project?

**Comment by raul1991** [comment]
Yes, exactly. Is there some kind of cache that ionic uses and i can clear
it .
Additionally i would like to share that i deleted that .ionic folder as
well to try if that works or not , but it did not.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!
